### PR TITLE
circuitpy_mpconfig.h: terse errors on non-full-builds

### PR DESCRIPTION
**Pull request by dhalbert**
Make error messages terse when `CIRCUITPY_FULL_BUILD = 0`. This saves about 1000 bytes on the `en_US` build and 1200 bytes on the `ru` build, which was overflowing.

### CODE REVIEW

**Comment by dhalbert** [comment]
Examples of `TERSE` vs `NORMAL` messages. The messages are still quite understandable; you just have to look at the context more carefully
```
"__init__() should return None"
"__init__() should return None, not '%s'"

"name not defined"
"name '%q' is not defined"

"cannot create instance"
"cannot create '%q' instances"

"unsupported type for operator"
"unsupported type for %q: '%s'"

"wrong number of values to unpack"
"need more than %d values to unpack"

"object not callable"
"'%q' object is not callable"

"indices must be integers"
"%q indices must be integers, not %s"
```

**Review by jepler — APPROVED** [review]
The change itself clearly does what it intends to do.

I think that as a practical matter we are going to have to do something about our most flash-constrained boards. Personally, I think this is a reasonable step to take, so that they don't hold back our overall progress.

**Comment by tannewt** [comment]
Is the space saved because there are more shared messages? I'd really rather not do this but understand we're hitting a code size wall on SAMD21.

**Comment by jepler** [comment]
My understanding is, they're terser, and some forego any %-formatting which also saves code space. There are definitely some that combine too, see mp_arg_error_terse_mismatch.

**Comment by dhalbert** [comment]
@tannewt Is it OK to merge this, to prevent further failed builds?

I am not sure why you'd rather not do this. Is it because the messages are different, because they are less informative, or some other reason?

My feeling is that they are almost the same, and only slightly less explicative. I don't foresee this being much of a support issue at all.

**Comment by tannewt** [comment]
Ya I'm ok merging it now to unblock us. I may try and turn it back on later if I come up with free space some other way.

I hesitate because good error messages are really helpful. We don't always have a good understanding of why the builds are growing either. I think we can be more disciplined about feature freezing to save the space instead.

**Pull request merged**
