### PR TITLE
Add PSRAM support to ESP32S2

### PR DESCRIPTION
**Pull request by tannewt**
When configured the CircuitPython heap will be on the external RAM.
When not available, the heap will be 48k inside the IDF heap.

### CODE REVIEW

**Comment by hierophect** [comment]
I'll try a control from `main` today. That error indicates some kind of invalid memory access, but not a null dereference as per `EXCVADDR` being nonzero.

**Comment by tannewt** [comment]
@ladyada What module does your Saola have? Does it have PSRAM? I suspect your issue may not be related to this PR.

**Comment by microDev1** [comment]
I tested PSRAM support on microS2 and it works. 👍 

repl_micro_s2_psram

**Comment by jerryneedell** [comment]
Works on my saola_wrover 
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.2-358-gf39708abb on 2020-08-26; Saola 1 w/Wrover with ESP32S2
>>> import gc
>>> gc.mem_free()
2048784
>>> ```

**Comment by hierophect** [comment]
I can confirm a null reference exception when attempting to use DisplayIO on the Saola Wrover. Investigating.

**Comment by hierophect** [comment]
@ladyada @tannewt I've confirmed that the issue with DisplayIO also happens on main and thus is probably unrelated to this PSRAM update. I've opened a new issue for it here: #3334. @ladyada if you'd like to keep testing this PR, I think most other sketches should still work, you just got unlucky with the one you tried landing on a new bug! It only occurs when the screen is physically plugged in, so removing it should allow you to recover your filesystem.

**Comment by dhalbert** [comment]
Should I wait for this for 6.0.0-alpha.3?

**Comment by tannewt** [comment]
@dhalbert Want to approve? Seems like it's ready to go in.

**Pull request merged**
