### PR TITLE
memory type for alt flash fix

### PR DESCRIPTION
**Pull request by ladyada**
I forgot to add this part which is required to support the two SPI flash types for itsybitsy m0!

### CODE REVIEW

**Comment by ladyada** [comment]
thanks! can we regen the itsybitsy m0 uf2? that's the only one affected

**Comment by dhalbert** [comment]
Could you test the travis-built .uf2 from here? https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/itsybitsy_m0/ We can do a quick 2.2.2 release if that works for you. It won't take long.

**Comment by ladyada** [comment]
done! i just tested on both USON flashes with the same hardware PCB!

**Comment by tannewt** [comment]
@ladyada would you like me to release 2.2.2 or are there other boards we
should add before releasing? Need it by Monday or can we release on Monday?

**Comment by ladyada** [comment]
i could add prelim pIRkey definition over the weekend, its a trivial trinket-like. lets see where we stand on monday

**Comment by tannewt** [comment]
Sounds good! keep us posted

**Pull request merged**
