### PR TITLE
Set default hostname

### PR DESCRIPTION
**Pull request by askpatrickw**
This how to set the default hostname for any ESP32-S2 based board.
Without this _every_ board will have the hostname "espressif".

Hostname can be 253 characters (a-z, A-Z, 0-9, -). Although caps are converted to lower case, they're fine to use.
I suggest using the same value as USB_PRODUCT from board/mpconfigboard.mk, but the board maker could use anything they want.

I tested this on a FeatherS2. Unexpected Maker is going to checkin his own change.

Additional work is needed to surface the [get_hostname](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/network/esp_netif.html#_CPPv422esp_netif_get_hostnameP11esp_netif_tPPKc) and [set_hostname](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/network/esp_netif.html#_CPPv422esp_netif_set_hostnameP11esp_netif_tPKc) APIs from the IDF.

### CODE REVIEW

**Comment by microDev1** [comment]
@askpatrickw I would like to add default hostname for my [microS2](https://circuitpython.org/board/microdev_micro_s2/), should I make a PR in your branch ?

**Comment by askpatrickw** [comment]
@microDev1 you can do your own PR direct from your branch. The changes are per board in their own sdkcondig so no conflicts.

**Comment by microDev1** [comment]
In my testing, caps aren't converted to lower case.

**Comment by askpatrickw** [comment]
Setting your host name programmatically is definitely a feature that should be implemented. 

It's definitely my _opinion_ that it is a better experience for new people to have the default name match the device name. It's also interesting that this setting exists in the IDF, which I take as an indication it is meant to be used by manufacturers. If the group disagrees that's fine. 

Re: upper and lower case. I was going to add a caveat that how I tested that was using Fing on my iPhone to scan the network. I deleted all the discovered devices but clearly it's caching because I changed the name from all lower to mixed case. I think the mixed case is fine too though. So I don't think it changes the PR. Again open to feedback. 

Thanks!

**Comment by askpatrickw** [comment]
I just realized I missed understood your comment. Setting this programmatically during connect versus the config file… Someone else should chime in on which is the preferred way￼￼. I don't have any strong feelings either way about that.￼

**Comment by tannewt** [comment]
Do you want to set it for other boards or just this one? Seems like we should add a property for it on the wifi.Radio object. https://github.com/adafruit/circuitpython/blob/main/shared-bindings/wifi/Radio.c

**Comment by microDev1** [comment]
A property in wifi.Radio object which defaults to `USB_PRODUCT` if no custom hostname is set would work well.

**Comment by askpatrickw** [comment]
This meant to be an example other boards could use. I don't think its _my_ place to make checkins for other Manufacturers boards. But since @tannewt  can speak for Adafruit, I thought it was a reasonable first PR to show an example.

If @microDev1  wants to run with adding it to wifi.radio, that's great!

**Comment by askpatrickw** [comment]
@tannewt  With #3547 merged, this should be good to go as well I think. Let me know if need anything else.

**Review by tannewt — APPROVED** [review]
Looks good to me!

**Pull request merged**
