### PR TITLE
Rename board bdmicro_vina_m0 to bdmicro_vina_d21 and update boardfiles.

### PR DESCRIPTION
**Pull request by bd34n**
Vina M0 got some updates - including a rename. Rename the board to VINA-D21, update the boardfiles appropriately, and update the build.yml workflow to reference the new board name.

Tested using latest code as of now:
Adafruit CircuitPython 6.0.0-alpha.3-284-gc55deb54f-dirty on 2020-09-16; BDMICRO VINA-D21 with samd21g18

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
What do you think about leaving the board ID alone? aka, not renaming the folder. That will preserve the link to past versions. You can still change the product name it reports as.

**Comment by bd34n** [comment]
That would work, of course, and then just update the board files. Would that cause confusion for end users and customers with regard to what board it refers to? For example, in the CircuitPython-org repo for firmware updates and similar?

I'd rather rename it if possible - but if it is a serious pain, then what you propose would work also. I just worry that customers might get confused as to what board to build if building from source. And it will seriously grate against my OCD. :-)

And, if accepted, I will have sister board to this one coming soon name bdmicro_vina_d51 - and at that point, the names within the ports/boards directory will not be consistent.

Note - I'm prepared to submit the necessary updates to the CircuitPython-org repo as well. I wanted to make sure this change went through before doing that, though.

**Comment by tannewt** [comment]
@bd34n I think some of my confusion comes from the current state of your board. Is it already for sale? Are you ok losing the link to the stable 5.3.1 release?

If you are ok with that then I'm ok with you changing the board id.

**Comment by bd34n** [comment]
@tannewt, totally understandable, I should have clarified when I submitted the PR. Vina-m0 is not for sale and never will be in the form it was. It got to a "coming soon" state. Then based on work on the M4 (D51) sister board, I went back and reworked some key areas on M0 (D21) to make them consistent w/regard to parts and on-board capabilities and redid all the PCBs, etc. I do have VINA-D21 up now, though. I'm working on getting the manual and associated documentation in order - I swear, that takes longer than the board(s) themselves. And not nearly as fun!

So if we can change the board id to bdmicro_vina_d21, that would make my day. :-)

**Review by tannewt — APPROVED** [review]
Okie doke. Will merge after the CI catches up.

**Comment by bd34n** [comment]
Soon after submission, 30+ CI tests succeeded, then 100+ seemed to stall in a "waiting" state for a couple of days. I rechecked this morning and it looks like the "waiting" tests failed. The Details link for the failures doesn't show any useful information. Any idea what happened?

**Comment by jepler** [comment]
GitHub actions sometimes has problems.  I have asked it to re-run the jobs, but that doesn't always work either.  If it does, great.  If not, the next thing to do is push a commit that does nothing -- you can create such a commit at the commandline with "git commit --allow-empty", assuming you have no modified files.

**Comment by dhalbert** [comment]
I have cancelled all the pending jobs in numerous PR's, and am going to re-run the PR actions one PR at a time.

**Pull request merged**
