### PR TITLE
Fixes for JEplayer

### PR DESCRIPTION
**Pull request by jepler**
This
 * fixes DMA hangs by taking an upstream update
 * makes MP3File objects reusable, eliminating out of memory errors
 * adds an "rms_level" property so we can animate some neopixels

### CODE REVIEW

**Comment by jepler** [comment]
Yes, I could, but it would ultimately be more finicky.  There are a BUNCH of separate memory allocations, and writing a mini-allocator to make them come out of a passed in block didn't seem like a good use of time.
 - disk I/O buffer
 - sample buffers
 - main mp3 decoder object
 - 7 internal pointers in mp3 decoder object

**Comment by tannewt** [comment]
You don't need to allocate everything out of that block, you just need to allocate the things that are hard to reallocate.

I'm wary of this change because it breaks the mental model of one MP3File per file. It'd be more of a MP3Decoder at that point. That may be ok but I feel like there may be a way to make the allocations more reliable instead.

**Comment by jepler** [comment]
There are at least 5 allocations each bigger than 1kB, the biggest is over 8kB.  What threshold would you consider for being "hard to allocate"?

**Comment by jepler** [comment]
fwiw in arudino, where of course it is a compile-time decision whether to use MP3 or not, they found it was reasonable to just statically allocate 1 playback object rather than do the allocations dynamically.

**Pull request merged**
