### PR TITLE
Added Unexpected Maker BlizzardS3 board for Espressif port.

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
Added UM Blizzard S3 board definitions

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Can't test, but looks fine!

Could you submit another PR to `main`? Note that `mpconfigboard.mk` and `sdkconfig` have changed significantly in our 9.0.0 revamp of various things, so just merging this from 8.2.x is not going to work. Check out some examples of your current boards in `main`.

**Comment by UnexpectedMaker** [comment]
> Can't test, but looks fine!
> 
> Could you submit another PR to `main`? Note that `mpconfigboard.mk` and `sdkconfig` have changed significantly in our 9.0.0 revamp of various things, so just merging this from 8.2.x is not going to work. Check out some examples of your current boards in `main`.

Yeah, sure thing. It 9.0 close? I am working on adding 2 more boards at the moment, so do I just add them to main and not bother with 8.x?

**Comment by dhalbert** [comment]
> Yeah, sure thing. It 9.0 close? I am working on adding 2 more boards at the moment, so do I just add them to main and not bother with 8.x?

9.0.0 is not that close. We are finishing the MicroPython v1.20.0 merge, and then we'll start doing alpha's, because the .mpy format will stop changing. But then we also need to do the v1.21.0 merge, and there's a lot of debugging to do too.

No issue if you want to wait and do all the boards at once for `main`.

**Comment by UnexpectedMaker** [comment]
> > Yeah, sure thing. It 9.0 close? I am working on adding 2 more boards at the moment, so do I just add them to main and not bother with 8.x?
> 
> 9.0.0 is not that close. We are finishing the MicroPython v1.20.0 merge, and then we'll start doing alpha's, because the .mpy format will stop changing. But then we also need to do the v1.21.0 merge, and there's a lot of debugging to do too.
> 
> No issue if you want to wait and do all the boards at once for `main`.

Ok, thanks for clarifying - I'll get all of the boards added for 8.2.x - I'm assuming there's going to be an 8.2.7 or more...  and then I'll work on getting them ready for main as well.
Cheers :)

**Comment by dhalbert** [comment]
An 8.2.7 may be imminent, in a day or two. But there will probably be an 8.2.8 also. We will just keep going every few weeks on 8.2.x if there are interesting changes, including new boards.

**Comment by tannewt** [comment]
I can update the board defs with the 8.2.x merge into main if needed.

**Comment by UnexpectedMaker** [comment]
> I can update the board defs with the 8.2.x merge into main if needed.

Thanks for the offer Scott :) but I should learn the differences, so I'll do them. I'm not quite ready with the other 2 boards yet anyway.

**Pull request merged**
