### PR TITLE
don't compile and link PicoDVI if CIRCUITPY_PICODVI=0

### PR DESCRIPTION
**Pull request by bablokb**
changed the Makefile: include PicoDVI conditionally only when PICODVI is set

### CODE REVIEW

**Comment by dhalbert** [comment]
Oh, this looks interesting!

**Comment by dhalbert** [comment]
@bablokb How much RAM does this save? Does this get back a lot of what you were missing?

**Review by dhalbert — APPROVED** [review]
This looks good and there is no downside. Thanks!

**Comment by bablokb** [comment]
> @bablokb How much RAM does this save? Does this get back a lot of what you were missing?

This only saves a few bytes. The change mainly speeds up the build and will make room in the firmware for other things.

**Pull request merged**
