### PR TITLE
update frozen libraries and remove stray space

### PR DESCRIPTION
**Pull request by dhalbert**
A stray space is causing pre-commit to fail.

### CODE REVIEW

**Comment by dhalbert** [comment]
Let's make this a little more useful and update frozen libraries.

**Review by kattni — DISMISSED** [review]
Looks good to me!

**Review by kattni — DISMISSED** [review]
Thanks for the fix!

**Review by jepler — APPROVED** [review]
thanks. I didn't individually check the submodule changes but it should be OK

**Pull request merged**
