### PR TITLE
Update `tj-actions` & Revert `fetch-depth` change

### PR DESCRIPTION
**Pull request by MicroDev1**
The latest working `tj-actions/changed-files` version is `v34.5.1`. Also, reverts `fetch-depth` change introduced in #7329.

### CODE REVIEW

**Comment by dhalbert** [comment]
This didn't seem to be necessary after some recent merges, so it may depend on how many commits back various things are. I will mark this as 8.x.x for now.

**Comment by jepler** [comment]
Closing this since the builds are working for now, and a potential longer term solution is to use partial clones. However, we can re-open this if we encounter the weird fetch errors again. Would rather not downgrade, as using old actions is not a long term solution (github loves to deprecate things used in actions)

**Comment by MicroDev1** [comment]
PR #7329 locked `tj-actions/changed-files@v34.5.3`, this version has a bug necessitating `fetch-depth: 0` to work.
Re-opening this to test if `@v34` works.

**Review by tannewt — APPROVED** [review]
Looks like it worked! Let's try it. Thank you!

**Pull request merged**
