### PR TITLE
Add Led_IR pin name to ATOM Lite

### LINKED ISSUE #8738: Ad Led_IR pin name to ATOM Lite ESP32 circuitpython
Adafruit CircuitPython 9.0.0-alpha.6 on 2023-12-12; M5Stack Atom Lite with ESP32

Pin 12/IR pin isn't named in https://github.com/adafruit/circuitpython/blob/main/ports/espressif/boards/m5stack_atom_lite/pins.c but it is on the pinmap and schematic at https://docs.m5stack.com/en/core/atom_lite

It can be accessed via microcontroller.pin.GPIO12

### PR DESCRIPTION
**Pull request by carson-coder**
Tries to fix #8738 
This is untested because I do not have the atom lite

### CODE REVIEW

**Comment by dhalbert** [comment]
@sctv you can test this with the build artifacts: https://github.com/adafruit/circuitpython/actions/runs/7294266870?pr=8747

**Comment by carson-coder** [comment]
[M5_stack_atom_lite.UF2.zip](https://github.com/adafruit/circuitpython/files/13752836/M5_stack_atom_lite.UF2.zip)
I converted it to a UF2 for you

**Review by jepler — APPROVED** [review]
Verified that GPIO12 matches the atom lite schematic at https://docs.m5stack.com/en/core/ATOM%20Lite#schematic
image

**Comment by sctv** [comment]
@dhalbert I have downloaded the artifact adafruit-circuitpython-m5stack_atom_lite-en_US-20231221-6a0c8ac.bin to my computer, but having trouble flashing it. Using https://espressif.github.io/esptool-js/ generates a warning: Image file at 0x1000 doesn't look like an image file, so not changing any flash settings. 
@carson-coder  The uf2 would be useful, but this vESP32-PICO-D4 doesn't turn up as a drive.

**Comment by dhalbert** [comment]
@carson-coder @sctv The M5Stack Atom Lite is an ESP32 board. Plain ESP32 does not have native USB support, so it will not display a drive, nor can you use a UF2.

@sctv There is also an AtomS3 Lite, which has an ESP32-S3. I want to confirm you have the Atom Lite and not the AtomS3 Lite

**Comment by sctv** [comment]
Flashed the binary(using a 0x0 offset) 
Got a listing for the IR/D12 with 
`import Board
dir(board)`
used a simple blink program work's with the IR reference.  

@dhalbert it is the AtomLite with ESP32-PICO-D4. I don't have the AtomS3 Lite to test.
Thanks.

**Pull request merged**
