### PR TITLE
Switch our workflows to ubuntu 20.04

### PR DESCRIPTION
**Pull request by jepler**
This switches some which were using ubuntu-latest and some which were using ubuntu-16.04, all to 20.04.  When 22.04 is added on GH Actions we can revisit this.

### CODE REVIEW

**Comment by jepler** [comment]
The lone failure was a network glitch.  However, as this PR's home branch is not adafruit/circuitpython, it doesn't actually test s3 uploads which @dhalbert mentioned as a potential incompatibility.

**Comment by dhalbert** [comment]
I looked over the `aws` changes, and I just see this as a possible issue:
https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager

Looks like we should set `AWS_PAGER` to nothing to avoid having it hang waiting for paging. (I'm surprised that a pager might not notice it's being run in a script and do nothing.)

**Review by dhalbert — COMMENTED** [review]
These steps use `ubuntu-latest` instead of an explicit version, so maybe we should change them to `ubuntu-20.04`. That way they won't change out from under us in two years.

```
workflows/create_website_pr.yml
13:    runs-on: ubuntu-latest

workflows/build.yml
418:    runs-on: ubuntu-latest

workflows/pre-commit.yml
14:    runs-on: ubuntu-latest
```

**Comment by jepler** [comment]
I had a mistaken commit in there (disabling ulab on some stm boards) so I rebased it out and force-pushed.

**Comment by dhalbert** [comment]
I just rememberd this: https://github.com/adafruit/circuitpython/pull/3629#pullrequestreview-521185497
@jepler says:
>turns out that when the branch is made in adafruit/circuitpython instead of jepler/circuitpython the upload steps can be tested. Nice, I didn't realize that.

**Comment by jepler** [comment]
I pushed it to an adafruit branch as well, run results will be at https://github.com/adafruit/circuitpython/actions/runs/368709935

**Review by dhalbert — APPROVED** [review]
Uploads in adafruit branch build look fine! Thanks for doing this!

**Comment by jepler** [comment]
@dhalbert excellent.  Looks like you have to re-review since I had entered this in draft state

**Review by dhalbert — APPROVED** [review]

**Comment by dhalbert** [comment]
I think it's not green just because of the one failing build (which is just network trouble).

**Pull request merged**
