### PR TITLE
Switch translate() to the header file

### PR DESCRIPTION
**Pull request by tannewt**
This allows the compile stage to optimize most of the translate()
function away and saves a ton of space (~40k on ESP). *However*, it
requires us to wait for the qstr output before we compile the rest
of our .o files. (Only qstr.o used to wait.)

This isn't as good as the current setup with LTO though. Trinket M0
loses <1k with this setup.

So, we should probably conditionalize this along with LTO.

### CODE REVIEW

**Comment by d-c-d** [comment]
What caused the Trinket M0
To grow by 1k with this setup? ( duplication of strings? )
Haven't studied the changes yet

**Comment by dhalbert** [comment]
I can experiment with this on other builds. Definitely conditionalize on LTO.

**Comment by dhalbert** [comment]
If you compiled `translate.c` with `-O3` or something like that, would it help the LTO builds (or the non-LTO builds)?

**Comment by tannewt** [comment]
> What caused the Trinket M0 To grow by 1k with this setup? ( duplication of strings? ) Haven't studied the changes yet

I suspect LTO is duplicating copies of the compressed data because each compilation unit (.o) now has it's own copy. So if the same error occurs in two files, there will now be two copies of it. I haven't proven this though.

**Comment by tannewt** [comment]
Ok, @dhalbert. This finally built. There is a lot of diff noise due to the header move. Let me know if you want me to clean it up. I considered folding the translate.h include into `py/runtime.h` but the include-what-you-use philosophy would have you list it I think.

**Review by dhalbert — CHANGES_REQUESTED** [review]
This is great work! One formatting oddity, and one change to improve the compile times.

**Comment by tannewt** [comment]
I think the simplest thing would be to have the TRANSLATE_OBJECT version on by default and only do the header thing when we need the space (like small S3 builds.)

**Review by dhalbert — APPROVED** [review]
I reran the latest build when nothing else was queued, and got a total runtime of 1h 16m 18s, which is only 10 minutes more than what I was getting in #6436. Thanks for spending the time on this: the space savings is great!

**Comment by dhalbert** [comment]
The single failure was a transient CI issue.

**Pull request merged**
