### PR TITLE
aesio: fix counter mode, add test

### PR DESCRIPTION
**Pull request by jepler**
Closes: #5566.

### CODE REVIEW

**Comment by jepler** [comment]
This is a potential incompatibility. Before,
 * IV was not required in CBC mode.  Now, it must be supplied.
 * counter was an int, and was not required in CTR mode.  Now it must be supplied, and its type is buffer.
 * IV/counter could be specified in ECB mode, and were ignored.  Now, it is an error if it is specified.

**Comment by jepler** [comment]
Test vectors taken from https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a.pdf

**Review by tannewt — COMMENTED** [review]
This should wait for 8.0.0 given the API changes. Any chance you can keep them compatible?

**Comment by jepler** [comment]
I think I could re-spin this compatibly, and hold the incompatible changes for 8.

The change would be smaller. For CTR mode only, accept a ReadableBuffer for `counter=`. (an int would remain accepted and ignored in all modes)

**Comment by jepler** [comment]
We should align this to be a compatible subset of https://pycryptodome.readthedocs.io/en/latest/src/cipher/aes.html which seems to be the standard python crypto library today.

For now, I'm not sure of the value of taking this patch. The code works as-is, except for any confusion (possibly mine) over the distinction between the IV and the counter in CTR mode. However, _not requiring `IV=` in CBC is a large footgun, and footguns should be avoided in crypto even more than in other contexts.

**Pull request closed without merging**
