### PR TITLE
nrf: Change pin names on DKs to match silkscreen

### PR DESCRIPTION
**Pull request by arturo182**
Revamped the `make-pins.py` script so it generates cleaner pin files which are used instead of the static board ones.

On the DKs you get `PX_YY` for both `board` and `microcontroller.pin` and on the feather52 you get silkscreen names like `A0`, `D13` or` SCK` for `board` and `PX_YY` for `microcontroller.pin`.

Tested with `digitalio` and `analogio` modules.

### CODE REVIEW

**Comment by microbuilder** [comment]
I need to get a bootloader PR in (likely later today) before the changes here, but I'll review and test this as soon as the nRF52840 serial bootloader PR is out.

**Comment by microbuilder** [comment]
BTW, if you put any new test code and examples together, feel free to include them in either the `ports/nrf/examples` folder or a board level `examples` folder if it's board specific.

I'm convinced a lot of people look directly at the code repo and examples that ship with it as their first point of contact, so having up to date examples there makes sense to me, and being in the repo generally increases the chance of them being up to date with the latest API changes, especially with things like BLE.

**Comment by arturo182** [comment]
Out of curiosity, why is the BL needed before this?

**Comment by microbuilder** [comment]
Because it will add another board to the repo that will need to be updated as well, and will create a conflict. I can merge this one in as well and the conflict will be in the BL PR, it just needs to be handled in one of them but I've had my head down in code all day and haven't had a chance to try this one out so I was going to submit the BL PR for review, and then find a solution to keep both of these happy.

If you want to get this in right away, I'll test it later tonight and manage the conflict in the BLE PR though.

**Comment by arturo182** [comment]
Ah, interesting to see a nRF52840 feather coming, I guess I got my changes in just in time for you guys ;)

**Comment by microbuilder** [comment]
It's just a shell on top of the PCA10056 for now until modules are available, but since this one will have a different flash layout I figured I may as well make a new board now rather than complicating the PCA10056 BSP. No ETA on when a proper board will be out, we still don't have any modules available since the final chips haven't been released yet. Thanks for the numerous PRs, though! It really helps having another sets of hands and eyes!

**Comment by arturo182** [comment]
What do you mean no modules available, how do you call this then? https://twitter.com/arturo182/status/951567482921332736 :joy:

**Comment by microbuilder** [comment]
There are early engineering samples available of chips, yes, but we need FCC approved modules of the final silicon, which is still a little ways out, and the final tapeout for the release silicon I believe hasn't happened yet (very soon), even though a couple generations of chips have been released to customers and early adopters for development.

**Comment by arturo182** [comment]
Yes, I am aware of all of this, I've been in contact with Nordic as well, was just joking around cause that's a module I designed and assembled :smile:

**Comment by microbuilder** [comment]
Ah, sorry ... clearly my humor gene is recessive 🙃

**Pull request merged**
