### PR TITLE
Revamp T-Deck port

### PR DESCRIPTION
**Pull request by bill88t**
A bunch of tiny fixes and improvements for the LILYGO T-Deck.
- Display power pulled high, not left floating.
- Pins reorganized, only exposing what is usable. (No pins renamed, BOOT pin added)
- Modules unusable on the board removed.
- Indicate support for T-Deck Plus.

Along with these I have created a [TinyUF2 port](https://github.com/adafruit/tinyuf2/pull/421).

### CODE REVIEW

**Comment by dhalbert** [comment]
The T-Deck and T-Deck Plus are different versions of the board, as far as I can tell. This appears to be for the Plus. Is it also compatible with the base version? Should the directory name change? Should there be two ports?

**Comment by dhalbert** [comment]
> The circuitpython.org listing can in turn also be updated to indicate support.

Could you do this after the merge? That would be great!

BTW, do you actually have one of these (plain or Plus)?

**Review by dhalbert — APPROVED** [review]
Thanks!

**Comment by bill88t** [comment]
> Could you do this after the merge? That would be great!

Yep, that's my plan. I plan on showing both the plain and plus side by side.

> BTW, do you actually have one of these (plain or Plus)?

Got the plus with 433MHz SX1262 and GPS. It can even fetch GPS time (on demo firmware).
It's just uart data, so i'll make a lib if there isn't one already.

**Pull request merged**
