### PR TITLE
Added Smart Bee Design Boards

### PR DESCRIPTION
**Pull request by strid3r21**
first time making a PR here for this. so please let me know if im missing anything or need to change anything. thank you.

### CODE REVIEW

**Comment by strid3r21** [comment]
> Looks like there is a mis-identation that pre-commit could fix: https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

I will look into fixing that when I get home in the morning.

Thanks

**Comment by strid3r21** [comment]
hmm, not sure why pre-commit is failing here. it passed when I ran it locally.
pre-commit

**Comment by tannewt** [comment]
I suspect it is due to pre-commit only running over changed files. I'll manually fix it for you.

**Comment by strid3r21** [comment]
> I suspect it is due to pre-commit only running over changed files. I'll manually fix it for you.

Thank you!

**Review by tannewt — APPROVED** [review]

**Pull request merged**
