### PR TITLE
try adding new feather def

### PR DESCRIPTION
**Pull request by ladyada**
feather esp32s2 with mini module (no PSRAM)

### CODE REVIEW

**Comment by ladyada** [comment]
could probably benefit from freezing adafruit_io in as well

**Comment by tannewt** [comment]
Why is the display disabled by default?

**Comment by ladyada** [comment]
hardfaulted/crashed on boot, i dont have build environment working (using artifacts for building) so turned off displayio for now. the pins work - i verified those!

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
