### PR TITLE
Request ROM bootloader when resetting using the 'serial trick'

### PR DESCRIPTION
**Pull request by jepler**
Closes: #5870.

### CODE REVIEW

**Review by microDev1 — COMMENTED** [review]
Do we want to request UF2 bootloader here instead of the default ROM bootloader? This won't work on non-UF2 boards.

**Comment by jepler** [comment]
For my use case, yes. This makes it just the same as other family Adafruit boards. Basically it allows me to have a single `make` rule which operates across different microcontroller families that builds & programs circuitpython all at once.

If there's a way to tell whether tinyuf2 is not present, and fall back to the ROM bootloader, that's fine. Or, if a specific board is designed to run without bootloader, we could make it compile-time conditional instead.  Or to notice at CP start that UF2 was requested but did not run(if that's possible) and then jump from there into the ROM bootloader?

**Review by microDev1 — DISMISSED** [review]
LGTM! I think the consistency with other boards should be enough for now, a new issue topic can be opened to discuss further.

**Comment by jepler** [comment]
I checked what Arduino does, and even if tinyuf2 is installed, the "1200 baud trick" sends it to the ROM bootloader. Which is better, consistency with Arduino or consistency with other uf2-bootloader boards?  I prefer uf2, because it can auto-reset into the new FW; esptool can't over USB for some reason I don't understand.

**Comment by tannewt** [comment]
1200 should go to ROM to match arduino because it's meant for folks to escape CP back into Arduino. CP's API can reset into UF2 to match our other boards.

**Comment by dhalbert** [comment]
@jepler is this all set to merge, or is there still something to discuss? It sounds to me like it's all OK.

**Comment by jepler** [comment]
@dhalbert sounds like scott's asking me to change it, so that the 1200 trick returns to the state that 'works for arduino'.

**Review by microDev1 — APPROVED** [review]

**Comment by tannewt** [comment]
@jepler if you want a baudrate way of resetting into uf2 you could add another magic baudrate.

**Pull request merged**
