### PR TITLE
frozen: Update Adafruit_CircuitPython_CircuitPlayground submodule

### PR DESCRIPTION
**Pull request by jepler**
> Merge pull request #79 from kattni/board-handling
  > Merge pull request #75 from kattni/remove-simpleio
  > Merge pull request #74 from kattni/bluefruit
  > Merge pull request #73 from adafruit/dherrada-patch-1
  > Merge pull request #72 from dherrada/master
  > Merge pull request #70 from dcbriccetti/tilt-instrument

### CODE REVIEW

**Comment by jepler** [comment]
This comes up 20 bytes short on one translated build. I'm open to suggestions on how to fix it.

**Comment by dhalbert** [comment]
It would be good to update all the frozen modules, not just this one.

**Comment by dhalbert** [comment]
Here is how I update all the frozen modules:
```
for x in *; do cd $x; pwd; git-checkout-latest-tag.sh ; cd ..;done
```
where `git-checkout-latest-tag.sh` is:
```
#!/bin/bash
git fetch --tags
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```

**Comment by dhalbert** [comment]
@jepler You can try lowering `CFLAGS_INLINE_LIMIT = 55` in `mpconfigboard.mk`.

**Comment by jepler** [comment]
I'll update all, check for space failures and update compiler flags to get it to work. I'll request a review once that's passing.

**Pull request merged**
