### PR TITLE
vectorio: Add width and height properties to rectangle

### PR DESCRIPTION
**Pull request by WarriorOfWire**
Closes: https://github.com/adafruit/circuitpython/issues/5695

Unfortunately I don't have a microcontroller handy to give this a go. If nobody volunteers first I'll have one later next week to try :-)

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Code looks fine to me. Maybe @FoamyGuy would be willing to do a quick test.

**Review by FoamyGuy — APPROVED** [review]
Tested successfully on PyPortal with:
```py
import time
import displayio
import vectorio
import board

display = board.DISPLAY
group = displayio.Group()

palette = displayio.Palette(1)
palette[0] = 0x125690
rectangle = vectorio.Rectangle(pixel_shader=palette, width=40, height=30, x=55, y=45)
group.append(rectangle)

display.show(group)

while True:
    for i in range(30, 150, 10):
        rectangle.width = i + 40
        rectangle.height = i
        time.sleep(0.3)
```

**Comment by WarriorOfWire** [comment]
@FoamyGuy thank you for checking this change! ❤️

**Comment by FoamyGuy** [comment]
@WarriorOfWire for sure! Thank you for working on it! And generally for making `vectorio`. We are starting to see more and more folks using it!

**Pull request merged**
