### PR TITLE
Fix ItsyBitsy RP2040 board definition

### PR DESCRIPTION
**Pull request by kattni**
The `LED` pin was incorrect.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
if it passes CI, merge it!

**Comment by kattni** [comment]
Please wait to merge this. There's another potentially incorrect pin. Troubleshooting now.

**Comment by kattni** [comment]
This fix has been verified against the schematic. I also built CircuitPython and tested all three pin changes. `LED`, `BUTTON` and `D5` now all work properly with this fix.

**Review by hierophect — APPROVED** [review]
LGTM pending CI

**Pull request merged**
