### PR TITLE
moar trinkz

### PR DESCRIPTION
**Pull request by ladyada**
rp2040 + qt + trinkey

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
LGTM. I checked the pin assignments for I2C and UART.

**Comment by ladyada** [comment]
thankx btw i cant seem to build on windwos from `main` latest

```
$ make -C mpy-cross
make: Entering directory '/c/Users/ladyada/Dropbox/micropython/circuitpython/mpy-cross'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Traceback (most recent call last):
  File "../py/makeqstrdata.py", line 744, in <module>
    encoding_table = compute_huffman_coding(translations, args.compression_filename)
  File "../py/makeqstrdata.py", line 382, in compute_huffman_coding
    cb = huffman.codebook(counter.items())
  File "C:/msys64/mingw32/lib/python3.8/site-packages/huffman/huffman.py", line 78, in codebook
    return Tree(symbolweights).codebook
  File "C:/msys64/mingw32/lib/python3.8/site-packages/huffman/huffman.py", line 53, in __init__
    self.root = heap.pop()
  File "C:/msys64/mingw32/lib/python3.8/site-packages/huffman/heapqo.py", line 40, in pop
    return heapq.heappop(self.heap)
IndexError: index out of range
make: *** [../py/py.mk:283: build/genhdr/qstrdefs.generated.h] Error 1
make: *** Deleting file 'build/genhdr/qstrdefs.generated.h'
make: *** Waiting for unfinished jobs....
../py/compile.c: In function ‘compile_built_in_decorator’:
../py/compile.c:841:24: error: ‘MP_QSTR_native’ undeclared (first use in this function); did you mean ‘MP_QSTR_write’?
  841 |     } else if (attr == MP_QSTR_native) {
      |                        ^~~~~~~~~~~~~~
      |                        MP_QSTR_write
../py/compile.c:841:24: note: each undeclared identifier is reported only once for each function it appears in
../py/compile.c:851:24: error: ‘MP_QSTR_viper’ undeclared (first use in this function); did you mean ‘MP_QSTR_upper’?
  851 |     } else if (attr == MP_QSTR_viper) {
      |                        ^~~~~~~~~~~~~
      |                        MP_QSTR_upper
../py/compile.c:856:24: error: ‘MP_QSTR_asm_thumb’ undeclared (first use in this function); did you mean ‘MP_QSTR_sum’?
  856 |     } else if (attr == MP_QSTR_asm_thumb) {
      |                        ^~~~~~~~~~~~~~~~~
      |                        MP_QSTR_sum
../py/compile.c:858:24: error: ‘MP_QSTR_asm_xtensa’ undeclared (first use in this function); did you mean ‘MP_QSTR_extend’?
  858 |     } else if (attr == MP_QSTR_asm_xtensa) {
      |                        ^~~~~~~~~~~~~~~~~~
      |                        MP_QSTR_extend
../py/compile.c: In function ‘compile_async_for_stmt’:
../py/compile.c:1828:27: error: ‘MP_QSTR___aiter__’ undeclared (first use in this function); did you mean ‘MP_QSTR___iter__’?
 1828 |     EMIT_ARG(load_method, MP_QSTR___aiter__, false);
      |                           ^~~~~~~~~~~~~~~~~
../py/compile.c:70:70: note: in definition of macro ‘EMIT_ARG’
   70 | #define EMIT_ARG(fun, ...) (comp->emit_method_table->fun(comp->emit, __VA_ARGS__))
      |                                                                      ^~~~~~~~~~~
../py/compile.c:1839:39: error: ‘MP_QSTR___anext__’ undeclared (first use in this function); did you mean ‘MP_QSTR___next__’?
 1839 |     compile_await_object_method(comp, MP_QSTR___anext__);
      |                                       ^~~~~~~~~~~~~~~~~
      |                                       MP_QSTR___next__
../py/compile.c:1846:22: error: ‘MP_QSTR_StopAsyncIteration’ undeclared (first use in this function); did you mean ‘MP_QSTR_StopIteration’?
 1846 |     EMIT_LOAD_GLOBAL(MP_QSTR_StopAsyncIteration);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
../py/compile.c:72:84: note: in definition of macro ‘EMIT_LOAD_GLOBAL’
   72 | #define EMIT_LOAD_GLOBAL(qst) (comp->emit_method_table->load_id.global(comp->emit, qst, MP_EMIT_IDOP_GLOBAL_GLOBAL))
      |                                                                                    ^~~
../py/compile.c: In function ‘compile_async_with_stmt_helper’:
../py/compile.c:1885:47: error: ‘MP_QSTR___aenter__’ undeclared (first use in this function); did you mean ‘MP_QSTR___enter__’?
 1885 |             compile_await_object_method(comp, MP_QSTR___aenter__);
      |                                               ^~~~~~~~~~~~~~~~~~
      |                                               MP_QSTR___enter__
../py/compile.c:1935:31: error: ‘MP_QSTR___aexit__’ undeclared (first use in this function); did you mean ‘MP_QSTR___exit__’?
 1935 |         EMIT_ARG(load_method, MP_QSTR___aexit__, false);
      |                               ^~~~~~~~~~~~~~~~~
../py/compile.c:70:70: note: in definition of macro ‘EMIT_ARG’
   70 | #define EMIT_ARG(fun, ...) (comp->emit_method_table->fun(comp->emit, __VA_ARGS__))
      |                                                                      ^~~~~~~~~~~
../py/compile.c: In function ‘compile_expr_stmt’:
../py/compile.c:2019:35: error: ‘MP_QSTR___repl_print__’ undeclared (first use in this function); did you mean ‘MP_QSTR___repr__’?
 2019 |             compile_load_id(comp, MP_QSTR___repl_print__);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   MP_QSTR___repr__
../py/compile.c: In function ‘compile_atom_expr_await’:
../py/compile.c:2808:27: error: ‘MP_QSTR___await__’ undeclared (first use in this function); did you mean ‘MP_QSTR___main__’?
 2808 |     EMIT_ARG(load_method, MP_QSTR___await__, false);
      |                           ^~~~~~~~~~~~~~~~~
../py/compile.c:70:70: note: in definition of macro ‘EMIT_ARG’
   70 | #define EMIT_ARG(fun, ...) (comp->emit_method_table->fun(comp->emit, __VA_ARGS__))
      |                                                                      ^~~~~~~~~~~
../py/compile.c: In function ‘compile_scope_inline_asm’:
../py/compile.c:3314:22: error: ‘MP_QSTR_uint’ undeclared (first use in this function); did you mean ‘MP_QSTR_int’?
 3314 |                 case MP_QSTR_uint:
      |                      ^~~~~~~~~~~~
      |                      MP_QSTR_int
../py/compile.c:3367:19: error: ‘MP_QSTR_label’ undeclared (first use in this function); did you mean ‘MP_QSTR_lower’?
 3367 |         if (op == MP_QSTR_label) {
      |                   ^~~~~~~~~~~~~
      |                   MP_QSTR_lower
../py/compile.c:3379:26: error: ‘MP_QSTR_align’ undeclared (first use in this function); did you mean ‘MP_QSTR_main’?
 3379 |         } else if (op == MP_QSTR_align) {
      |                          ^~~~~~~~~~~~~
      |                          MP_QSTR_main
../py/compile.c:3388:26: error: ‘MP_QSTR_data’ undeclared (first use in this function); did you mean ‘MP_QSTR_update’?
 3388 |         } else if (op == MP_QSTR_data) {
      |                          ^~~~~~~~~~~~
      |                          MP_QSTR_update
make: *** [../py/mkrules.mk:74: build/py/compile.o] Error 1
make: Leaving directory '/c/Users/ladyada/Dropbox/micropython/circuitpython/mpy-cross'
```

**Comment by ladyada** [comment]
oh wait it cant find gcc anymore. wtheck

**Comment by dhalbert** [comment]
try a clean build too; QSTR errors can occur when a build failed early and is redone

**Comment by ladyada** [comment]
aah i ifgured it out - i recently updated msys. i have to use 32-bit compatibility mode for gcc (!?)

**Comment by ladyada** [comment]
now something else, probably some windows default encoding thingy

```
$ make BOARD="adafruit_qt2040_trinkey" -j 32
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
{'sku': ['W25Q64JVxQ']}
   text    data     bss     dec     hex filename
    244       0       0     244      f4 build-adafruit_qt2040_trinkey/boot2.elf
QSTR updated
Traceback (most recent call last):
  File "../../tools/gen_display_resources.py", line 43, in <module>
    for line in args.sample_file:
  File "C:/msys64/mingw32/lib/python3.8/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 974: character maps to <undefined>
make: *** [../../supervisor/supervisor.mk:175: build-adafruit_qt2040_trinkey/autogen_display_resources.c] Error 1
make: *** Deleting file 'build-adafruit_qt2040_trinkey/autogen_display_resources.c'
make: *** Waiting for unfinished jobs....
```

**Pull request merged**
