### PR TITLE
RP2040 PWMAudioOut: Release DMA channels after play has finished

### PR DESCRIPTION
**Pull request by dhalbert**
Fix RP2040 `PWMAudioOut` stopping playing completely. It will stop playing after playing six samples.

"Scratchiness" and other audio quality issues are not necessarily addressed by this.

The essential problem was that the 12 DMA channels were being used up because the two that were being used were not freed after use, due to a missing
```c
        audio_dma_stop(&self->dma);
```
in `PWMAudioOut.c`.

In the course of this I made some other more minor changes:
- Rename `single_channel` to `single_channel_output` to clarify its meaning. This changed a lot of files.
- Do pin claiming in `PWMOut`, not in `PWMAudioOut`.
- Fix up uses of `DMA_CH0_CTRL_TRIG_EN_BITS` and  `DMA_CH1_CTRL_TRIG_EN_BITS`. They are actually the same value, but it's possible in some future processor they might not be, so I regularized the use.
- Reorder one struct's fields to save a bit of space.

### CODE REVIEW

**Review by tannewt — DISMISSED** [review]
Good find! Thank you!

**Comment by dhalbert** [comment]
Fixed one failing build. Ready for re-review. I will look at crackling audio separately, since this fixes an immediate problem.

**Comment by dhalbert** [comment]
@kevinjwalters This may partially fix #4208, but I have not tested it for noisy output yet. I was testing with an artificial audio file with non-audible data to make sure the buffers were filling properly.

**Review by jepler — APPROVED** [review]
Makes sense, but didn't test.

**Pull request merged**
