### PR TITLE
beetle esp32c3 "-" -> "_"

### PR DESCRIPTION
**Pull request by bill88t**
This is kinda important as with "-"'s in the name, we can't use board.board_id as part of an import name.
Also, uniformity.

### CODE REVIEW

**Comment by dhalbert** [comment]
@makermelissa How do we rename a board on circuitpython.org when its name changes in CircuitPython? This change will not propagate down until the next release.

**Comment by dhalbert** [comment]
> This is kinda important as with "-"'s in the name, we can't use board.board_id as part of an import name.

You can do `board.board_id.replace(board.board_id, "-", "_") for now.

**Comment by bill88t** [comment]
From what I have seen (from when I was porting Waveshare ESP32-S2-Pico)
all that needs to be done is the same rename on [circuitpython-org](https://github.com/adafruit/circuitpython-org).
Should you wish for me to do that too, just tell me so.

**Comment by dhalbert** [comment]
There will be name version skew between 7.x.x and 8.x.x. There is an alias mechanism as well.

**Comment by jepler** [comment]
If we want boards to be valid Python identifiers, we have more work to do and should do them all at once with a major release. Better to do it as soon as possible, or decide once and for all that board names are NOT required to be Python identifiers.

The following boards have hyphens in their names:
```
cp32-m4
kicksat-sprite
silicognition-m4-shim
ai_thinker_esp32-c3s
ai_thinker_esp32-c3s-2m
beetle-esp32-c3
lilygo_ttgo_t-01c3
lilygo_ttgo_t-oi-plus
morpheans_morphesp-240
raytac_mdbt50q-db-40
raytac_mdbt50q-rx
TG-Watch
zrichard_rp2.65-f
```

The following have ".":
```
espressif/boards/espressif_kaluga_1.3
espressif/boards/adafruit_magtag_2.9_grayscale
raspberrypi/boards/zrichard_rp2.65-f
```

The following does not start with a letter or underscore:
```
atmel-samd/boards/8086_commander
```

**Comment by bill88t** [comment]
This pr out of date, I will create a new one that is for all of the boards with invalid Python identifiers.
And let's discuss the yes/no there.

**Pull request closed without merging**
