### PR TITLE
Add socket select task to wake CP

### LINKED ISSUE #6552: Web workflow doesn't work without a display
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-27-g187f156ac-dirty on 2022-07-01; ESP32-S3-DevKitC-1-N8R2 with ESP32S3
```

### Code/REPL

```python
No user code is run on the microcontroller before the behavior occurs.
```

### Behavior

After initiating a GET via curl (and leaving it apparently waiting for a response) I then accessed the CIRCUITPY drive and renamed a file. When the new filename was saved, CURL picked up the following:

     C:\Users\Desktop\curl-7.84.0_3-win64-mingw\bin>curl -v http://10.0.0.189 --output -
     *   Trying 10.0.0.189:80...
     * Connected to 10.0.0.189 (10.0.0.189) port 80 (#0)
     > GET / HTTP/1.1
     > Host: 10.0.0.189
     > User-Agent: curl/7.84.0
     > Accept: */*         <---------------Stops here until FS/Flash operation is completed
     >
     * Mark bundle as not supporting multiuse
     < HTTP/1.1 200 OK
     < Content-Encoding: gzip
     < Content-Length: 482
     < Content-Type: text/html
     <
     Q?~u$?"???????^?????    ??o?+q?PV?§?#?r-fsEe?\~t??"     ? ??P6?,?4z_?¦??1E?8?-Iu?,?i???-???6?
     a?Q&???DS?A?F???????.l?c??Y?6?L?p??,af9U?C????i? \?j'?j?
     ?¤?};*M?h?Jz¦#?p0Yg?!? ?b??9?  * Connection #0 to host 10.0.0.189 left intact?L?L??8??????;???5??f???d?%?f?¦?u>s#?x??B??

When connecting via a browser rather than curl, the board behaved in the same way except that when a flash operation was completed, the web page was served up as expected rather than the curl binary dump shown here.

### Description

_No response_

### Additional information

 I commented out the following block in supervisor/shared/flash.c and the web pages started serving up fine without the need to complete a flash operation first:

    // Turn off ticks now that our filesystem has been flushed.
    if (filesystem_dirty) {
        supervisor_disable_tick();
    }

### PR DESCRIPTION
**Pull request by tannewt**
This fixes the web workflow on boards without a display.

Fixes #6552

### CODE REVIEW

**Comment by RetiredWizard** [comment]
Still hanging trying to load page. Control-D in REPL helps a little but sometimes results in the board freezing with this message on the USB port:

     Assertion 'num_triggered >= 0' failed, at file Socket.c:95

and the following on the DEBUG console:

     I (49499) gpio: GPIO[46]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0


     Backtrace:0x400A0FD9:0x3FFDAFD00x400A1C03:0x3FFDAFF0 0x400A0D59:0x3FFDB010 0x400A0E6B:0x3FFDB030 
     0x400B5056:0x3FFDB050

     I (49529) wifi:state: run -> init (0)
     I (49529) wifi:pm stop, total sleep time: lu us / lu us

     W (49539) wifi:<ba-del>idx
     I (49539) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
     W (49539) wifi:hmac tx: ifx0 stop, discard
     W (49549) wifi:hmac tx: ifx0 stop, discard
     W (49549) wifi:hmac tx: ifx0 stop, discard
     W (49559) CP wifi: disconnected
     W (49559) CP wifi: reason 8 0x08
     W (49559) CP wifi: sta stop
     E (49569) I2S: i2s_driver_uninstall(2006): I2S port 0 has not installed
     I (49639) CP webserver: Request GET /fs/
     I (49639) CP webserver: Header Host 10.0.0.187
     I (49639) CP webserver: Header Connection keep-alive
     I (49639) CP webserver: Header Cache-Control max-age=0
     I (49649) CP webserver: Header Authorization Basic OkNQMTIz
     I (49649) CP webserver: Header DNT 1
     I (49659) CP webserver: Header Upgrade-Insecure-Requests 1
     I (49669) CP webserver: Header User-Agent Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KH
     I (49679) CP webserver: Header Accept text/html,application/xhtml+xml,application/xml;q=0.9,image/avi
     I (49679) CP webserver: Header Referer http://10.0.0.187/
     I (49689) CP webserver: Header Accept-Encoding gzip, deflate
     I (49699) CP webserver: Header Accept-Language en-US,en;q=0.9
     E (49699) CP webserver: short send -113 17
     E (49709) CP webserver: short send -128 24
     E (49709) CP webserver: short send -11 16
     E (49719) CP webserver: short send -11 3
     E (49719) CP webserver: short send -11 2
     E (49729) CP webserver: short send -11 14
     E (49729) CP webserver: short send -11 9
     E (49729) CP webserver: short send -11 2
     E (49739) CP webserver: short send -11 2
     E (49739) CP webserver: short send -11 451

**Review by jepler — APPROVED** [review]
This allows the web workflow to work on an Adafruit Feather ESP32 V2, where it didn't before (note it also has to be enabled by editing the board definition in the draft PR).

I didn't follow the code in detail so there might be little problems, but this changed it from not working at all to seemingly working pretty well.  huzzah!

**Comment by RetiredWizard** [comment]
Decoded backtrace:

 0x400B5056:0x3FFDB050got ['0x400B5056', '0x400A0D59', '0x400A0E6B']
/home/pi/circuitpython/ports/espressif/common-hal/socketpool/Socket.c:95 (discriminator 1)
/home/pi/circuitpython/ports/espressif/../../main.c:997
/home/pi/circuitpython/ports/espressif/../../main.c:1004

**Comment by tannewt** [comment]
@RetiredWizard Any idea what caused the disconnect? I thought I was handling the case where a socket file descriptor becomes invalid but I must have missed one.

Will have an updated version of this shortly based on the ESP32 merge.

**Comment by RetiredWizard** [comment]
Nothing is jumping out at me, the board crash happens after several ctrl-D presses in the repl. I was having some success getting the board to service the background workflow a bit at a time by pressing the ctrl-D.

I took a look at the line referenced by the Assertion 'num_triggered >= 0' but I couldn't make anything of that section of code.

**Comment by RetiredWizard** [comment]
@jepler tested this on an ESP32 board that doesn't have the USB interface? If so I'm guessing that's the difference between his results and mine. That seems somewhat consistent with my observation that I could shake some background ticks loose by doing things over the serial USB connection.

**Comment by RetiredWizard** [comment]
I rebuilt after @tannewt 's last force-push and getting the same results. I'm not sure it's of any value but I grabbed the debug output as I was testing and commented along the way. It turns out slowing the process down in order to record it apparently avoided the board crash. Once I decided I had enough, I went ahead and started pressing Ctrl-D in the Repl without waiting as long between reboots and before long hit the same num_triggered >= 0 from line 91 of socket.c crash again.

In any case here's the debug console output from my testing session:
[debugsession.txt](https://github.com/adafruit/circuitpython/files/9107692/debugsession.txt)

**Comment by tannewt** [comment]
@RetiredWizard Please have the Developer Tools section open to the console in Chrome as well. It will likely have messages about while file loads are stopped. The network tab can be useful too.

The -104 is connection reset so chrome may be assuming the response is done.

**Comment by jepler** [comment]
@tannewt please consider enabling workflow for esp32 with this PR!

**Comment by RetiredWizard** [comment]
Just another observation of the behavior on the S2 chips, If I'm patient, I am sometimes able to coax the serial terminal into working. Once it connects and starts mirroring the REPL it seems to keep working and doesn't suffer the any disconnects or web loading delays.  Oddly, just using the serial terminal seems to allow the other web workflow pages to work on the lilygo ESP32-S2, but not on the UM Feathers2. I am using slightly different CP builds on those two devices, The UM is running Scott's debug build and the Lilygo is running a non-debug build of this PR.

**Comment by jepler** [comment]
I'm not sure if this is relevant, but I noticed a sequence of operations that makes the webserial repl get wedged up... still using the Feather ESP32 V2.

1. load the /cp/serial page in the browser
2. Hit the Ctrl-C button
3. Use the browser's reload button

This hangs waiting to load `/cp/serial/`. The only thing that seems to make it continue is pressing ctrl-d in a terminal connected to the USB serial port.

**Comment by tannewt** [comment]
Thanks for the feedback! Please file issues. I'm out next week so I'm going to try and get this passing CI and merged in. We can fix these issues later.

**Review by jepler — APPROVED** [review]
Thanks, I'll file an issue for the specific scenario I saw causing trouble on the Adafruit Feather ESP32 V2. Good to merge when green.

**Pull request merged**
