### PR TITLE
Track creation of board.I2C(), etc.

### LINKED ISSUE #5949: PYPORTAL -- latest builds won't boot
beginning with  adafruit-circuitpython-pyportal-en_US-20220121-9a353a4.uf2
CP will not boot on my PyPortal.
The previous build adafruit-circuitpython-pyportal-en_US-20220121-f2713af.uf2 
boots OK

### LINKED ISSUE #5950: SAMD51 build not working at all after #5422 (multiple board buses)
Various SAMD51 builds have been reported not to work as of right now at the tip of `main`. They simply don't start at all.

I did a bisect, which says that the problem commit is b6858e4ca7158b68074aef5082a46a1058f42079, which is part of
- #5422

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #5950.
- Fixes #5949.

Before #5422, the singletons for `board.I2C()` were stored as `i2c_singleton`, etc. and were `NULL` if not instantiated. #5422 allowed multiple `board`, objects, but removed the separate singleton storage slots, and relied on checking whether the objects were `deinited()` or not to see if they were valid. But all-zero objects were not recognized as `deinited()` in some ports (which caused crashes). For instance, in `atmel-samd`, `deinited()` checked for a pin being `NO_PIN` (which is 0xFF).

So restore tracking the creation of the singletons, and don't use `deinited()` to check their existence. This PR tracks them as booleans, instead of as pointers. The changed code now looks more like the code pre-#5422.

Tested on a Metro M4, with an I2C program that uses the default I2C object.

### CODE REVIEW

**Review by jerryneedell — COMMENTED** [review]
Tested on PyPortal - boots OK
Thank you!

**Comment by jerryneedell** [comment]
Looks like the "ru" build is just a few bytes over on a few of the samd21 builds.

**Comment by kmatch98** [comment]
I verified this PR now boots properly on the pyportal. Thanks @dhalbert!

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you for the quick fix.

**Pull request merged**
