### PR TITLE
Diskinfo api for web workflow

### LINKED ISSUE #7637: web workflow API endpoint to return free space on device
https://github.com/adafruit/circup code has a TODO to check free space on a device before installing a module. To support this for web workflow (https://github.com/adafruit/circup/issues/156) as well, the value available needs to be available via the [REST API](https://docs.circuitpython.org/en/latest/docs/workflows.html#file-rest-api).

### PR DESCRIPTION
**Pull request by FoamyGuy**
resolves #7637 

URL is `/cp/diskinfo.json` Response sizes are in bytes.

Example of response:
```
{"free": 212992, "block_size": 512, "total": 963072}
```
Maybe we don't really need `block_size` in the results? I can remove it if not. I added it initially in order to test how it's looked up, which is needed to find the correct multiplier to get to bytes units.

Tested successfully with Feather ESP32-S2 TFT.

Thank you to: isacben, Neradoc, and anecdata who all helped me in getting this far on implementing this API. Also Scott for the pointer to t_getfree(), the FatFs docs that were linked were quite helpful as well.

### CODE REVIEW

**Review by tannewt — DISMISSED** [review]
Looks great! Thank you.

I'd leave block size in case another filesystem is used in the future and has a different size.

**Comment by tannewt** [comment]
Could you bump web api version from 1 to 2? That'll simplify discovery of this endpoint.

**Comment by FoamyGuy** [comment]
latest commit increases api_version to 2.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
