### PR TITLE
Add board file for the hacked Trinket M0 Express

### PR DESCRIPTION
**Pull request by deshipu**
Board definition for a hacked Trinket M0 with added flash chip.
Based on https://daveastels.com/2017/09/01/trinket-m0-express-hack/
Details at https://hackaday.io/project/21578-pewpew-featherwing/log/68146-replicating-the-trinket-m0-express-hack

### CODE REVIEW

**Comment by deshipu** [comment]
I'm not sure if this is actually useful, but since I got it working, I thought I would make the pull request anyways.

**Comment by tannewt** [comment]
Thanks for this! I'm not exactly sure how we want to handle the branding for this since its a hacked up Trinket. I think it'd be ok to have it pulled in. We just likely want to caveat it.

**Comment by deshipu** [comment]
Done. I hope I didn't miss any. I also changed one "micropython" to "circuitpython" — you might want to do that in other boards too.

**Comment by tannewt** [comment]
Thanks @deshipu !

Which MicroPython did you change?

**Comment by deshipu** [comment]
https://github.com/adafruit/circuitpython/pull/303/commits/e6be16fdeb8919938aba96dce0e531c8124091b8#diff-c0809c6aa2f2d9455e27475a2bfe59fbL79

**Comment by tannewt** [comment]
Ah ok. Thanks!

**Pull request merged**
