### PR TITLE
update busdisplay docstring example code

### PR DESCRIPTION
**Pull request by FoamyGuy**
The docstring was showing the pre 9.x displayio API.

### CODE REVIEW

**Comment by dhalbert** [comment]
Could you change this to be merging against `9.0.x` instead of `main`? Thanks. You may just be able to click "Edit" to the right of the title and change the base.

**Comment by FoamyGuy** [comment]
there is an edit and it seems to have an option for changing branches but it doesn't show any branches in the list to choose from and typing `9.0.x` in there and then enter doesn't seem to do anything.
image

**Comment by FoamyGuy** [comment]
When I created the branch I used:
```
git checkout -b busdisplay_docs_fix adafruit/main --no-track
```
Would I need to make a new one with this instead?:
```
git checkout -b busdisplay_docs_fix adafruit/9.0.x --no-track
```

**Comment by FoamyGuy** [comment]
I think I do need to start this from the other branch instead of `main`. It seems that now it's wanting to change loads of things I didn't really touch.

**Pull request closed without merging**
