### PR TITLE
atmel-samd: USB mass storage tweaks.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by jerryneedell** [comment]
@tannewt Is there any conflict between turning the caches and the errata 1.6 regarding the DSU CRC32 which may fail if NVM caches are disabled? Does this apply?

**Comment by tannewt** [comment]
I don't think we're checking the CRC32 anywhere. We probably should though.

**Comment by jerryneedell** [comment]
Not with the cache disabled ;-) - Thanks for clarifying - I just wanted to make sure one fix was not going to introduce another latent bug.

**Comment by tannewt** [comment]
Yup, I appreciate the second set of eyes on it.

**Pull request merged**
