### PR TITLE
Add support for VIDI X board

### PR DESCRIPTION
**Pull request by lovrojakic**
Added support for VIDI X board (https://vidi-x.org/).

### CODE REVIEW

**Comment by dhalbert** [comment]
Hi @lovrojakic Are you still interested in working on this? If not, we can close the PR for now, and reopen it as needed. Note that the format of the header of the board files has changed fairly recently.

**Comment by lovrojakic** [comment]
Hi @dhalbert, everything seems to be working properly and I would appreciate if you could merge this PR. Thank you!

**Review by dhalbert — CHANGES_REQUESTED** [review]
Hi - the headers of the files for boards have changed recently. Could you look at typical board files at the tip of `main` and redo the headers in these files to match those? Thanks.

The license and copyright lines have been replaced with SPDX-style lines. The files that previously had no header lines now do have header lines.

**Review by dhalbert — APPROVED** [review]
Great, thank you! This will be merged to `main` and will go in the first 9.2.0 alpha or beta release.

**Comment by lovrojakic** [comment]
Thank you very much for your help!

**Pull request merged**
