### PR TITLE
Waveshare ESP32-S2 Pico psram definition improvements

### PR DESCRIPTION
**Pull request by bill88t**
Chip schematic [here](https://gr.mouser.com/datasheet/2/1127/APM_PSRAM_QSPI_APS6404L_3SQR_v2_3_PKG-1954826.pdf).
This is the chip on the board.

The datasheet says "133MHz for 32 Bytes Wrapped Burst operation at VDD=3.0V+/-10%".
The board 3v3 line is precisely on 3.3V (since it has a pretty good regulator), so within +/- 10% of 3.0V. So it would be within spec to run it at 133Mhz.
However there is no such option, so running it at 120Mhz. (Which may be for the best)

This pr also explicitly defines the interface to be qspi which the chip is wired for.
The speedup is pretty noticable.

Tested stable on 2 samples.

### CODE REVIEW

**Comment by bill88t** [comment]
Actually shouldn't the qspi pins be defined?
Even in the board definition of `adafruit_feather_esp32s3_4mbflash_2mbpsram` which seems to also be qspi, it only has one data pin defined..

**Comment by tannewt** [comment]
> Actually shouldn't the qspi pins be defined? Even in the board definition of `adafruit_feather_esp32s3_4mbflash_2mbpsram` which seems to also be qspi, it only has one data pin defined..

Defined where?

I definitely think this is an optimization we should be able to make on many ESP boards. We haven't ensured that we're running near the limit of the flash and RAM.

**Comment by bill88t** [comment]
In `ports/espressif/boards/adafruit_feather_esp32s3_4mbflash_2mbpsram/sdkconfig` we can see:
`CONFIG_SPIRAM_MODE_QUAD=y` and `CONFIG_SPIRAM_TYPE_AUTO=y`
`CONFIG_SPIRAM_MODE_QUAD` is for qspi, so shouldn't we define the rest of the data pins?
Currently only:
```
CONFIG_DEFAULT_PSRAM_CLK_IO=30
CONFIG_DEFAULT_PSRAM_CS_IO=26
```
are defined. So the board would run in normal spi?
Shouldn't there be something like:
```
CONFIG_DEFAULT_PSRAM_CS_IO1=26
CONFIG_DEFAULT_PSRAM_CS_IO2=26
CONFIG_DEFAULT_PSRAM_CS_IO3=26
```
I can't find any such definition on any board.

**Comment by tannewt** [comment]
> so shouldn't we define the rest of the data pins?

I think the pins are fixed, not flexible. So you don't need to define them.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
