### PR TITLE
update frozen libs

### PR DESCRIPTION
**Pull request by dhalbert**

### CODE REVIEW

**Comment by tannewt** [comment]
Did you make sure pixelbuf is enabled on all boards with NeoPixel frozen in? Otherwise one will still need to install pypixelbuf.

**Comment by anecdata** [comment]
Ditto for Dotstar?

**Comment by jepler** [comment]
I belatedly checked and each build that freezes in Adafruit_CircuitPython_NeoPixel builds in _pixelbuf, according to the support matrix.

pirkey_m0 freezes DotStar but does _NOT_ have _pixelbuf.  Other DotStar-freezing builds have _pixelbuf.  Does this mean that pirkey_m0 should remove DotStar?  I doubt it can add _pixelbuf, but I could be wrong.  @tannewt mind filing a PR that calls for the right thing to be done?

**Comment by jepler** [comment]
My mistake, the line to freeze dotstar into pirkey_m0 is commented out, so no action is needed.  My over-eager grep found it and I didn't look carefully.

**Comment by dglaude** [comment]
This raise a question about unused or never released board...
pIRkey was never released by @ladyada as a product, maybe just in a Top Secret with a few prototype.
This could be the story for PyGamer Advance.

Those are ghost board visible on https://circuitpython.org/downloads
If those start to make problem, it is a bit sad.

**Comment by tannewt** [comment]
> This raise a question about unused or never released board...
> pIRkey was never released by @ladyada as a product, maybe just in a Top Secret with a few prototype.
> This could be the story for PyGamer Advance.
> 
> Those are ghost board visible on https://circuitpython.org/downloads
> If those start to make problem, it is a bit sad.

We'll remove them if they start breaking the build but no need to do any work before that.

The downloads page is sorted by download count so that we can have all levels of boards from professional to one-off hobbyist. I don't want to add any sort of requirement to being listed besides having mainline support merged.

**Pull request merged**
