### PR TITLE
Enable collections deque for raspberrypi

### PR DESCRIPTION
**Pull request by rtyley**
Hi, I'd like to use [`collections.deque`](https://docs.circuitpython.org/en/latest/docs/library/collections.html#collections.deque) on my RP2040-based [Keybow 2040](https://circuitpython.org/board/pimoroni_keybow2040/). For MicroPython, `collections.deque` is enabled for all `rp2` devices, because they have [`MICROPY_CONFIG_ROM_LEVEL` set to 'extra features'](https://github.com/micropython/micropython/blob/cf7d962cf38db296d1ac419fc4d5302b64c59644/ports/rp2/mpconfigport.h#L44):

```
#define MICROPY_CONFIG_ROM_LEVEL                (MICROPY_CONFIG_ROM_LEVEL_EXTRA_FEATURES)
```

...which [includes `MICROPY_PY_COLLECTIONS_DEQUE`](https://github.com/micropython/micropython/blob/6bda80d81147217a1d830b99b93d2e35d372e8f9/py/mpconfig.h#L1225-L1227).

For CircuitPython, it looks like `MICROPY_CONFIG_ROM_LEVEL` defaults to 'core' (`MICROPY_CONFIG_ROM_LEVEL_CORE_FEATURES`) and isn't updated against any of the ports, so the only port getting `collections.deque` is the `unix` port, which explcitly sets `MICROPY_PY_COLLECTIONS_DEQUE`:

https://github.com/adafruit/circuitpython/blob/6925a001382d41940ea9b412b1d1ba517d9880f9/ports/unix/mpconfigport.h#L134

This commit just enables `MICROPY_PY_COLLECTIONS_DEQUE` in the same manner for the `raspberrypi` port.

See also:

* https://github.com/adafruit/circuitpython/issues/5734
* https://github.com/micropython/micropython/commit/970eedce8f37af46cb2b67fa0e91d76c82057541 which originally added `collections.deque` to MicroPython

### CODE REVIEW

**Comment by Neradoc** [comment]
I tried a local implementation with just this in `py/circuitpy_mpconfig.mk`
```C
MICROPY_PY_COLLECTIONS_DEQUE ?= $(CIRCUITPY_FULL_BUILD)
CFLAGS += -DMICROPY_PY_COLLECTIONS_DEQUE=$(MICROPY_PY_COLLECTIONS_DEQUE)
```

**Comment by dhalbert** [comment]
@rtyley did you mean to close this? I reopened.

**Comment by rtyley** [comment]
> did you mean to close this? I reopened.

I didn't mean to close it! I managed to make a mess with git, and accidentally pushed the branch when it had only an empty merge commit - so GitHub decided that the the PR was effectively merged, and closed it!!

I've now fixed the git branch, and updated as per your comment, just setting `MICROPY_PY_COLLECTIONS_DEQUE` if `CIRCUITPY_FULL_BUILD` is true, as is already done for `MICROPY_PY_COLLECTIONS_ORDEREDDICT`.

**Comment by rtyley** [comment]
Builds for [bluemicro833](https://github.com/adafruit/circuitpython/runs/6832873084?check_suite_focus=true#step:9:216), [feather_m0_express](https://github.com/adafruit/circuitpython/runs/6832877531?check_suite_focus=true#step:9:193), [kicksat-sprite](https://github.com/adafruit/circuitpython/runs/6832881283?check_suite_focus=true), [pca10100](https://github.com/adafruit/circuitpython/runs/6832886296?check_suite_focus=true#step:9:111), [simmel](https://github.com/adafruit/circuitpython/runs/6832891638?check_suite_focus=true#step:9:111), [metro_m0_express](https://github.com/adafruit/circuitpython/runs/6832882695?check_suite_focus=true#step:9:186) failed due to `Too little flash!!!` warnings, mostly just for one or two locales (`ru`, `fr`):

```
Error: Build bluemicro833 for ru took 30.86s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/nrf'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
237676 bytes used, -108 bytes free in flash firmware space out of 237568 bytes (232.0kB).
50896 bytes used, 80176 bytes free in ram for stack and heap out of 131072 bytes (128.0kB).
Too little flash!!!
```

I don't know if there's a convenient flag distinguishing between those boards and larger boards like the raspberrypi?

**Comment by dhalbert** [comment]
I can make some decisions about which builds to remove `deque` from, so that things fit. I'll push some commits to your PR that should fix. I may not do that immediately, but it will be on my short-term to-do list.

**Comment by rtyley** [comment]
Many thanks @dhalbert !

**Review by dhalbert — APPROVED** [review]
Thanks! I turned `deque` off on SAMD21 builds, and made it fit on a few nRF52833 builds that were too tight by turning off some other things that were generally not needed for those boards.

**Pull request merged**
