### PR TITLE
Increase the status LED brightness a bit so that newer DotStars

### PR DESCRIPTION
**Pull request by tannewt**
aren't super dim. This will make status NeoPixels a bit bright
but one can use samd.set_rgb_status_brightness() to dim them.

### CODE REVIEW

**Comment by dhalbert** [comment]
Just tried old and new on an ItsyBitsy. Nicely brighter but not too much.

**Comment by tannewt** [comment]
Try on a neopixel and let me know if its too much. Its borderline for me but folks can change it.

**Comment by dhalbert** [comment]
It is kind of bright especially when in REPL. Would it be easy to `#if` or `#ifdef` a different set of color values for DotStar vs NeoPixel?

**Comment by tannewt** [comment]
Yeah, we can. I was hoping not too but understand its unrealistic to think they will be the same.

**Comment by tannewt** [comment]
we could ifdef the default brightness instead too.

**Comment by tannewt** [comment]
I've dimmed the neopixel through the brightness control rather than the color definitions.

**Comment by dhalbert** [comment]
Retested and seems good. I had two Metros side by side and very similar, maybe a teeny bit dimmer on the brightness-controlled one, which is actually good.

**Comment by dhalbert** [comment]
Also retested Itsy and it's fine.

**Comment by dhalbert** [comment]
Build fails on boards with no rgb led (e.g. feather basic) :(

**Comment by tannewt** [comment]
Should be fixed for boards without a status pixel.

**Pull request merged**
