### PR TITLE
try to group travis jobs more logically

### PR DESCRIPTION
**Pull request by dhalbert**
First try: group by category. Ten jobs, which seems like too many, but let's see how long each one takes to run.

### CODE REVIEW

**Comment by dhalbert** [comment]
I think I'd like to remove `trinket_m0_haxpress`, `feather_m0_supersized`, and `feather_radiofruit_zigbee` from regular builds. @dastels, comments on the first two? @ladyada zigbee board is not a product?

**Comment by jerryneedell** [comment]
@dhalbert will the still be available for manual build. That is, will the board definitions remain in the repo?

**Comment by dhalbert** [comment]
@jerryneedell Yes, I just am not sure there are many physical instances of these in the real world. Do you have some?

**Comment by jerryneedell** [comment]
I have a feather_m0_supersized, but I'm fine with it not be part of the build process. As long as I can build it myself.

**Comment by jerryneedell** [comment]
Also, if you want to stop maintaining it completely, that is OK with me - Jus t so I know to keep what I need to build it locally in the future.

**Comment by dhalbert** [comment]
@tannewt the build time for the first subjob went to 1.5 hours after I accepted the `-flto` merge for nRF52. I rearranged things to this. Would you be willing to accept this for now to get the jobs more balanced again (and shorter) for now until GitHub actions is working? Here's the latest build: https://travis-ci.com/adafruit/circuitpython/builds/123654081. There's a short test-only job, a shorter nRF job, and the 5 others are similar to before. So not just 5 like before, but still some empty slots for other stuff to get a chance to run.

**Comment by dhalbert** [comment]
@jepler if you are willing to review this now we can speed up the builds before @tannewt wakes up :)

**Pull request merged**
