### PR TITLE
Feather esp32 s23 reverse tft

### PR DESCRIPTION
**Pull request by jepler**
This adds support for a prototype version of the Adafruit Feather ESP32-S3 Reverse TFT and Adafruit Feather ESP32-S2 Reverse TFT boards. At least one revision is anticipated before manufacture, so creating a draft PR.

Works (both):
 * CIrcuitPython starts
 * TFT 
 * WIFI 
 * neopixel
 * D13 LED
 * bme280 works with normal I2C pins: `b = board.I2C()`

Works (esp32-s2):
 * max17048 works with reversed I2C pins (known board bug) `b = busio.I2C(board.D3, board.D4)`

Broken (esp32-s3):
 * max17048 (reversed I2C pins) says `OSError: [Errno 19] No such device` but there's a deployable workaround -- I filed https://github.com/adafruit/Adafruit_CircuitPython_MAX1704x/issues/7 but it may be a core bug

Not tested yet:
 * low power performance

### CODE REVIEW

**Comment by jepler** [comment]
@ladyada see above for the results of my testing these modules

**Comment by ladyada** [comment]
noice! dont forget, will have PSRAM and possibly different amt of flash in final version (the PSRAM modules werent in stock)

**Comment by jepler** [comment]
@dhalbert @ladyada This has been updated and I build-tested locally, but I don't have the right HW for testing.

**Comment by dhalbert** [comment]
Build failures look like CI trouble. We can wait until it finishes and then re-run the failed jobs.

**Review by dhalbert — APPROVED** [review]
Re-run of build succeeded

**Pull request merged**
