### PR TITLE
Refine web workflow access control and http responses

### PR DESCRIPTION
**Pull request by Neradoc**
CORS (Cross Origin Resource Sharing) has the browser do [a "preflight" unauthenticated request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) using OPTIONS before it sends authenticated requests. This PR makes the web workflow respond to OPTIONS requests for `/fs/` and `/cp/` urls regardless of the authentication.

`ok_hosts` are tested ignoring the port.
"127.0.0.1" is added to the list to share a little bit of code.
"localhost" is added to the list.

Host comparisons are done with strncmp rather than memcmp: the origin can be shorter than the string it's compared to.
HTTP headers and methods are not case sensitive, use strcasecmp. I actually encountered a case where the "authorization" header's label was sent in lowercase by Firefox for some reason.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
I don't think the _origin_ok method does what one might expect. From my earlier testing it seems the "origin" passed in isn't the source of the request but rather the token (mdns name, dhcp name, ip address, etc) used to reach the microcontroller. So I really don't think there's much value in validating it against the hostname returned from common_hal_mdns_server_get_hostname. If the origin variable is some random hostname the traffic won't reach the microcontroller anyway. The same goes for checking that if it matches the microcontroller IP, if it doesn't the traffic won't get there.

The only way the origin could be 127.0.0.1 would be if the microcontroller itself was trying to access it's own web workflow page, that may be something that someone wants to do some day, but it's probably not something we need to validate for. I think the same goes for localhost. I also don't think it's possible that the origin variable could have a value of code.circuitpython.org unless someone created a local dns entry and assigned the microcontroller address to code.circuitpython.org.

The only other test is for the redirection but I believe that test is being done on the line that calls _origin_ok `} else if (strlen(request->origin) > 0 && !_origin_ok(request->origin)) {`

**Comment by Neradoc** [comment]
Origin is the cause of the request sent from the client.
It is what is in the address bar of the browser when the page makes a request to the server.

- If you are on the page of the workflow, say `http://cpy-123456.local`, the ajax requests (fetch in javascript) will have that address as Origin.
- If you are on http://code.circuitpython.org, the requests will have that address as origin.
- When I run a page on my own computer that is on `127.0.0.1` and does a fetch to the microcontroller as I showed on show and tell to get the list of files and update the library, the origin is `http://127.0.0.1`.

Allowing these addresses in `_origin_ok` lets us run code that accesses the Web Workflow API from those addresses.
Now, the Origin field can totally be spoofed, and I am in favor of allowing any origin, as long it's authenticated, so as to allow anyone to write a web app that uses the web workflow API.

**Comment by RetiredWizard** [comment]
Thanks for the explanation, your first example is what I had seen and led me to the conclusion that target would have been a better name than origin, however I did not understand the fetch behavior. My experience thus far has been simply accessing the microcontroller presented workflow page and the "origin" in that case has always been the address or logical representation (dns, dhcp) of the microcontroller, I guess because the microcontroller is hosting the javascript that is actually performing the fetch?

Given this explanation I can see an argument for maintaining some control of where fetches can come from. if _origin_ok is used we might want to consider adding the dhcp name:
`mp_obj_str_get_str(common_hal_wifi_radio_get_hostname(&common_hal_wifi_radio_obj))`
to the list in addition to the mdns name.

**Comment by tannewt** [comment]
> Now, the Origin field can be spoofed (I think), and I am in favor of allowing any origin, as long it's authenticated, so as to allow anyone to write a web app that uses the web workflow API.

Can it be spoofed from a browser? My hope was to make it harder for malicious websites to get local CP info. I don't care about custom HTTP request clients.

**Review by tannewt — APPROVED** [review]
Thank you so much for this! I'm excited that you are working with this API.

**Comment by Neradoc** [comment]
> Can it be spoofed from a browser? My hope was to make it harder for malicious websites to get local CP info. I don't care about custom HTTP request clients.

Maybe not, I'll admit I don't know much about that aspect of browser security, I think it's meant to protect against malicious pages that run a in a regular browser, so it's probably a good thing to have. But for example I can't share a demo of the installer by putting it on my website, one would have to download and run it from 127.0.0.1 (which is easy with `python3 -m http.server` but still).

**Comment by RetiredWizard** [comment]
>  I can't share a demo of the installer by putting it on my website,

Would it be possible to use a .env variable to authorize hosting websites in _origin_ok?

**Comment by tannewt** [comment]
> > I can't share a demo of the installer by putting it on my website,
> 
> Would it be possible to use a .env variable to authorize hosting websites in _origin_ok?

Ya, I think that's a good idea. Want to make an issue for it?

**Pull request merged**
