### PR TITLE
Socket: fix inconsistencies in argument types

### LINKED ISSUE #4127: Socketpool `socket.sendto()` cannot send UDP data to ports above 255
# Setup

* Microcontroller: UnexpectedMaker FeatherS2 (ESP32-S2) (fw: 0.2.1)
* CircuitPython: 6.1.0 & custom build from `main`
* Host computer: macOS 11.2 
* Tools used: Wireshark

# Description

It seems that `port` for `socket.sendto()` is bound to the length of an `uint8_t`, capping it out at `255`, and then overflowing back to `0` when port numbers above that are specified.

I confirmed this by seeing seemingly random ports show up when I was trying to send data over port `9000`, only to have my host machine with Wireshark report that the FeatherS2 was trying to connect over port `70`.

# Reproduce

Here's a testing script that reproduces this behaviour:

```python
import wifi
import ipaddress
import time
import socketpool

try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise

print("Connecting to WiFi")
wifi.radio.connect(secrets["ssid"], secrets["password"])
print("Connected to WiFi: {0} - IP: {1}".format(secrets["ssid"], wifi.radio.ipv4_address))

socketpool = socketpool.SocketPool(wifi.radio)

HOST_IP = "0.0.0.0" # change this to your host machine's private local IP (i.e: wherever you're running Wireshark)

while True:
    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 254)) # will appear as a request to port 254 (correct)

    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 257)) # will appear as a request to port 1 (incorrect)

    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 259)) # will appear as a request to port 3 (incorrect)

    time.sleep(1)
```

Set up Wireshark on the host/server machine and observe what ports the MCU tries to connect to (filter by the IP of the MCU).

image

# Fix

Changing the function `common_hal_socketpool_socket_sendto()` to accept `mp_int_t port` instead of `uint8_t port` fixes this error for me, in both `shared-bindings` and in the `ports/esp32s2` directories. This brings it in line with the TCP-based functions for `SOCK_STREAM`, etc. I reflashed my FeatherS2 with my newly-built version of CircuitPython, you can see here that I can send data on port `9000` now:

image

However, there are other functions such as `common_hal_socketpool_socket_bind()` which also take `uint8_t port` that may be affected as well. I'm unsure as to what impact that might have downstream as this is my first time modifying CircuitPython. I'm also unsure if this affects more than just my FeatherS2, but it seems likely given that the default `shared-bindings` C library also has `uint8_t`.

TCP connections with `socket.connect(...)` followed by `socket.send(...)` are unaffected, as far as I can tell. It seems to be limited exclusively to UDP connections, due to TCP already taking `mp_int_t port`.

### PR DESCRIPTION
**Pull request by hierophect**
The Common-Hal API for Socket had some inconsistencies argument size and type between functions, such as the "port" argument. Some of these were even using uint8_t, which is far too small for many common port values. This PR converts all arguments to uint32_t and adds some sign checking since Python always passes them in as signed ints. 

Further down the line, it may be appropriate to add more comprehensive input sanitation to this and other shared-bindings implementations.

Resolves #4127

### CODE REVIEW

**Comment by dhalbert** [comment]
@tannewt for background, I had a long chat with @hierophect on discord in #circuitpython about this. I think this PR does some good cleanup. Some general-purpose validation routines could be added, say in a top-level `shared-bindings/util.c` or whatever.

@hierophect looks like you need a (maybe) merge from upstream and definitely `make translate`.

**Comment by hierophect** [comment]
I even made a note to do the translate this time and I somehow forgot anyway

**Comment by StarWitch** [comment]
Thanks for the quick turnaround! I built this branch and flashed it onto my FeatherS2 and it works just fine, at least for `socket.sendto()`.

**Review by dhalbert — APPROVED** [review]
Thank you for cleaning this up!

**Pull request merged**
