### PR TITLE
Add support for PewPew M4 board

### PR DESCRIPTION
**Pull request by deshipu**
This is a minimalist SAMD51-based game console board. More information at https://hackaday.io/project/165032

### CODE REVIEW

**Comment by tannewt** [comment]
Please add it to the list of boards in .github/workflows/build.yml. Not sure why it didn't run for you at all.

**Comment by deshipu** [comment]
I will do that, but it seems like the stage library stopped displaying anything in the latest version, so I need to debug that first.

**Comment by tannewt** [comment]
It looks like the stage library grew too big to fit in the ugame10 and pewpew_m4 builds for some languages.

**Comment by deshipu** [comment]
Hmmm...
```
Failed to download action 'https://api.github.com/repos/actions/setup-python/tarball/v1'. Error Response status code does not indicate success: 401 (Unauthorized).
```

**Pull request merged**
