### PR TITLE
Refine error message for rp2040 audiobusio I2S object creation

### LINKED ISSUE #8058: Issue/confusing feedback creating I2S object on Seeed XIAO RP2040
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0 on 2023-05-22; Seeeduino XIAO RP2040 with rp2040
```

### Code/REPL

```python
>>> import board
>>> import audiobusio
>>> audio=audiobusio.I2SOut(bit_clock=board.D8, word_select=board.D9, data=board.D10)
```

### Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Bit clock and word select must be sequential pins
```

### Description

Attempting to create an I2S object in CircuitPython using the pins D8, D9 and D10 _seemingly_ fails despite the parameters being passed matching the requirements (ie `bit_clock` on D8, `word_select` on D9).

### Additional information

I took a look at the pin definitions for the XIAO RP2040 and realised that, behind the scenes, D10 comes before D9 - D10 is GPIO3, D9 is GPIO4. Swapping the `word_select` and `data` pins correctly creates an I2S object.

I guess the issue is more that the feedback you get, when trying to create the object, appears on the face of it to be wrong (when in actuality it is differently correct!). I'm not sure what the best thing to do would be to clear this up, so I thought reporting it here would pass it along in front of the eyes of a professional 😄

### PR DESCRIPTION
**Pull request by heygauri**
The error message for creating an I2S object on the rp2040 platform in CircuitPython can be misleading when the word_select and data pins are not sequential. This change updates the error message to provide clearer guidance by specifying "GPIO pins" instead of just "pins". The revised message now reads:

ValueError: Bit clock and word select must be sequential GPIO pins

Closes #8058

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
@heygauri run  `make translate` locally, and then commit the resulting change to `locale/circuitpython.pot`.

**Comment by heygauri** [comment]
> @heygauri run `make translate` locally, and then commit the resulting change to `locale/circuitpython.pot`.

I followed the same process, and it updated the error message in locale/circuitpython.pot. However, it also generated some unintended changes, approximately -518 lines, which I am not aware of.

**Comment by heygauri** [comment]
> > @heygauri run `make translate` locally, and then commit the resulting change to `locale/circuitpython.pot`.
> 
> I followed the same process, and it updated the error message in locale/circuitpython.pot. However, it also generated some unintended changes, approximately -518 lines, which I am not aware of. You can see those changes in this PR.

Update: I followed the document https://learn.adafruit.com/building-circuitpython/linux and below is the output:

$ make translate
find extmod lib main.c ports/atmel-samd ports/cxd56 ports/espressif ports/mimxrt10xx ports/nrf ports/raspberrypi ports/stm py shared-bindings shared-module supervisor -type d \( -path "ports/*/build-*" -o -path "ports/*/build" -o -path ports/atmel-samd/asf4 -o -path ports/cxd56/spresense-exported-sdk -o -path ports/espressif/esp-idf -o -path ports/mimxrt10xx/sdk -o -path ports/raspberrypi/sdk -o -path ports/stm/st_driver -o -path lib/tinyusb -o -path lib/lwip -o -path extmod/ulab/circuitpython -o -path extmod/ulab/micropython  \) -prune -o -type f \( -iname "*.c" -o -iname "*.h" \) -print | (LC_ALL=C sort) | xgettext -f- -L C -s --add-location=file --keyword=translate --keyword=MP_ERROR_TEXT -o - | sed -e '/"POT-Creation-Date: /d' > locale/circuitpython.pot

**Comment by dhalbert** [comment]
The missing error messages are because the `ulab` submodule was not loaded, so its messages were omitted. You can do `make fetch-all-submodules` from the top level, or descend into `ports/atmel-samd` (or most other ports), and then do `make fetch-port-submodules`, which will get `ulab`.

There were some new translations, so I merged from upstream, and re-did the `make translate`, and pushed new commits to your branch. Should be all set now. I'll review and merge when the build is done.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Comment by heygauri** [comment]
> The missing error messages are because the `ulab` submodule was not loaded, so its messages were omitted. You can do `make fetch-all-submodules` from the top level, or descend into `ports/atmel-samd` (or most other ports), and then do `make fetch-port-submodules`, which will get `ulab`.
> 
> There were some new translations, so I merged from upstream (upon reflection, probably not necessary), re-did the `make translate`, and pushed new commits to your branch. Should be all set now. I'll review and merge when the build is done.

Thank you for the help.

**Pull request merged**
