### PR TITLE
spresense: Fix USB CDC and MSC

### PR DESCRIPTION
**Pull request by kamtom480**
After the #4689, the Spresense port stopped working. EP descriptor for CDC and MSC set max packet size to 64. For `USB_HIGHSPEED` this should be 512.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Excellent, thank you! I thought there might be an issue with Spresense given the significant changes in USB, but I hadn't had a chance to test it yet.

Have you tested turning off any devices in boot.py? I hope I handled the endpoint assignment properly given your fixed endpoint assignments, but that is another thing to test.

**Comment by hathach** [comment]
@dhalbert this applies to imxrt port as well. For highspeed bulk endpoint size must be 512

**Comment by kamtom480** [comment]
@dhalbert  I tried these two functions and they worked:

`storage.disable_usb_device()`
`usb_cdc.enable(console=False, data=False)`

Do you know why the tests are not working?

**Comment by dhalbert** [comment]
> Do you know why the tests are not working?

GitHub Actions has had a lot of trouble in the past day. https://www.githubstatus.com/ looks OK now, but if you click on [Incident History](https://www.githubstatus.com/history), you'll see an extended period yesterday when it was not doing well.

MIDI also needs this same fix, so I will push a commit for it as well.

**Comment by dhalbert** [comment]
> @dhalbert this applies to imxrt port as well. For highspeed bulk endpoint size must be 512

Thanks -- it is port-independent code and will be applied across all.

**Comment by dhalbert** [comment]
I pushed a change, though there was git strangeness. I had to push twice.

Note also that we are using automated C code formatting now, and it indents the `#if`s. You can set this up for yourself by doing:
```sh
$ sudo add-apt-repository ppa:pybricks/ppa
$ sudo apt-get update
$ sudo apt install uncrustify
$ pip3 install pre-commit
$ cd <your repo clone>
$ pre-commit install   # only need to do this once
```
From this point on, it will run some checks before each commit, reformatting files as necessary. There are other checks besides the formatting. More info is here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Review by dhalbert — APPROVED** [review]
Thanks!

**Comment by kamtom480** [comment]
@dhalbert Thank you for the information! I will use it next time.

**Pull request merged**
