### PR TITLE
Fix getenv_int handling of "dos-style" newlines

### LINKED ISSUE #7380: CIRCUITPY_WEB_API_PORT being ignored - ProS3 / ESP32S3
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; ProS3 with ESP32S3
(Using latest U2F version with latest bootloader)
```

### Code/REPL

`settings.toml`
```python

CIRCUITPY_WIFI_SSID="GBD-TPLINK-Ext-2.4GHz"
CIRCUITPY_WIFI_PASSWORD="secretpassword"
CIRCUITPY_WEB_API_PASSWORD="password"
CIRCUITPY_WEB_API_PORT=3000
```

### Behavior

It looks as if CIRCUITPY_WEB_API_PORT is being ignored.
The webapi works but it just defaults to port 80 every time.

Tried a lower value of 70 for the port but it made no difference
Tried in and out of quotes (should be out of quotes) but made no difference
I kept my ssid real in case there's something in it messing with the setup, but not posting my password for obvious reasons, although that only contains letters and numbers but no special characters

### LINKED ISSUE #7394: Error parsing the _WEB_API_PORT from settings.toml
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.6-7-g81e9f5013 on 2022-12-28; FeatherS2 with ESP32S2
```

### Code/REPL

```python
# empty code.py
```

### Behavior

An error occurred while retrieving 'CIRCUITPY_WEB_API_PORT':
Invalid byte '\r'

### Description

Seems to be a problem parsing the port number if the number is followed by '\r\n'.

```
CIRCUITPY_WIFI_SSID="SAVETHEPLANET"
CIRCUITPY_WIFI_PASSWORD="secret-password"
CIRCUITPY_WEB_API_PASSWORD="web-api-password"
CIRCUITPY_WEB_API_PORT=80
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jepler**
I think this closes #7380 ; closes #7394.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Looks good to me, including the test coverage. @rsbohn and @grbd, would you like to test?  The build artifacts will be on this page in a little while: https://github.com/adafruit/circuitpython/actions/runs/3796145570

**Comment by grbd** [comment]
Just tested this seems to fix https://github.com/adafruit/circuitpython/issues/7380

**Comment by rsbohn** [comment]
Tested, working on Adafruit CircuitPython 8.0.0-beta.6-8-g8241edd52 on 2022-12-28; FeatherS2 with ESP32S2.

**Comment by dhalbert** [comment]
Thanks for the tests!

**Pull request merged**
