### PR TITLE
Check background pending before sleep

### LINKED ISSUE #5086: Teensy 4.1 cannot boot 7.0
### CircuitPython version

```python
7.0.0 alpha 5
7.0.0 alpha 4
7.0.0 alpha 3

6.3.0 Does not have this issue
```

### Code/REPL

```python
No COM/serial presented to OS via USB
```

### Behavior

I flash the mentioned 7.0.0 versions and when I plug the teensy back in, after about 3 minutes, all I get is this USB descriptor:
image

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
There is a race between when we run background tasks and when we
sleep. If an interrupt happens between the two, then we may delay
executing the background task. On some ports we checked this for
TinyUSB already. On iMX RT, we didn't which caused USB issues.
This PR makes it more generic for all background tasks including
USB.

Fixes #5086 and maybe others.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
This makes sense to me. Nice simplification.

**Comment by dhalbert** [comment]
I will do some audio testing when this builds.

**Comment by dhalbert** [comment]
Great find, and quick!

I tested audio on RP2040, SAMD51, nRF, ESP32-S2, and STM32F405. There was no change between alpha.6 and this.

STM PWM audio does not sound good, and I'l check on that.

The SAMD21 builds didn't work, so I didn't test those.

**Review by dhalbert — APPROVED** [review]
Thanks for really nailing the background processing down.

**Pull request merged**
