### PR TITLE
[Spanish - WIP] Translation of Unix/py directories

### PR DESCRIPTION
**Pull request by C47D**
Hi,

This is work in progress and before continuing i would like to get your opinion @carlosperate, about the translation of some words.

Example 1:
https://github.com/adafruit/circuitpython/blob/c23d2028a86d207fd02d274c809c62075f4595ed/py/argcheck.c#L64

Translated it as:
> a la función le hacen falta %d argumentos posicionales requeridos

Example 2:
https://github.com/adafruit/circuitpython/blob/c23d2028a86d207fd02d274c809c62075f4595ed/py/argcheck.c#L44

Translated as:
> la función no tiene argumentos por palabra clave

So i would like to know what do you think about the translation of:
- keyword (as **palabra clave**)
- arguments (as **argumento**)

Regards,
Carlos.

### CODE REVIEW

**Comment by sabas1080** [comment]
En lo personal se me hacen bien las traducciones

**Comment by C47D** [comment]
Gracias @sabas1080, cualquier otra sugerencia es bienvenida.

@tannewt i will continue with the translation of this strings after translating the strings on MixerIO module and updating the strings on another modules, is that ok?

**Comment by tannewt** [comment]
I'm ok with however you want to do it @C47D. Just let me know when you want things merged.

**Comment by carlosperate** [comment]
@C47D sorry for the delay, I'm currently on holiday. Translations in this PR look good, including the two cases you mentioned on the description for keyword and positional arguments.

**Comment by C47D** [comment]
@carlosperate, no problem, I will continue when I got some free time. Have a good holiday.

**Pull request merged**
