### PR TITLE
Simplify some ESP32-C3 board sdkconfig files

### LINKED ISSUE #6891: Clean up sdkconfig ESP32-C3 files
Some of the ESP32-C3 sdkconfig files can be simplified. Do it consistently across all the C3 boards.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #6891.

Some ESP32-C3 board `sdkconfig` had unnecessary settings. Removed extra stuff. Tested changes on a QT Py ESP32-C3; seems to act the same before and after, including that bootloader messages did not show up.

### CODE REVIEW

**Review by MicroDev1 — CHANGES_REQUESTED** [review]
Following is the diff of sdkconfig built after this change. 
```patch
diff --git a/ports/espressif/boards/microdev_micro_c3/sdkconfig b/ports/espressif/boards/microdev_micro_c3/sdkconfig
index 53796af53..75caa2d57 100644
--- a/ports/espressif/boards/microdev_micro_c3/sdkconfig
+++ b/ports/espressif/boards/microdev_micro_c3/sdkconfig
@@ -467,0 +468 @@ CONFIG_ESP_SLEEP_GPIO_RESET_WORKAROUND=y
+CONFIG_RTC_CLOCK_BBPLL_POWER_ON_WITH_USB=y
@@ -544,2 +545,2 @@ CONFIG_ESP_CONSOLE_NONE=y
-CONFIG_ESP_CONSOLE_SECONDARY_NONE=y
-# CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG is not set
+# CONFIG_ESP_CONSOLE_SECONDARY_NONE is not set
+CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG=y
```
I suggest adding the following in the esp32c3 common sdkconfig.
```python
#
# ESP System Settings
#
# CONFIG_ESP_SYSTEM_USE_EH_FRAME is not set
CONFIG_ESP_CONSOLE_SECONDARY_NONE=y
# CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG is not set
# CONFIG_ESP_DEBUG_STUBS_ENABLE is not set
# end of ESP System Settings
```

**Comment by dhalbert** [comment]
@MicroDev1 Thanks; it hadn't occurred to me to do that comparison. I added your suggestion, and had to add one more line to get it to compile. Now `sdkconfig` is identical with or without the PR for your C3 board and for QT Py ESP32-C3.

**Review by tannewt — APPROVED** [review]
Thank you!

**Review by MicroDev1 — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
