### PR TITLE
Add _bhb user module for Big Honking Button

### PR DESCRIPTION
**Pull request by theacodes**
BHB needs better accuracy from the ADC readings. To avoid changing the ADC configuration for all boards or adding complexity to AnalogIn, I implemented a custom user module to allow the BHB to talk to the ADC in the way that it needs to. I'm open to other approaches here, but this seemed like the least invasive and complex option.

### CODE REVIEW

**Comment by theacodes** [comment]
I would be happy to implement those for the SAMD21/51 boards in a later pull request (once I'm settled in after my move), are there any objections to merging this for now?

**Comment by theacodes** [comment]
> The current always-double-read in AnalogIn is because we don't know whether the state of the ADC has changed since the last read. It could have been used with different settings (e.g., to read CPU voltage or temperature). There could be a flag to keep track of that.

Yeah, a flag could be useful for that. In BHB I can be certain that the ADC isn't used for anything else.

**Comment by tannewt** [comment]
> BHB needs better accuracy from the ADC readings. To avoid **changing the ADC configuration for all boards** or adding complexity to AnalogIn, I implemented a custom user module to allow the BHB to talk to the ADC in the way that it needs to.

We'd love it for you to improve all of the boards. :-)

> I would be happy to implement those for the SAMD21/51 boards in a later pull request (once I'm settled in after my move), are there any objections to merging this for now?

Nope. This isn't how I'd want to do board specific modules because it doesn't have documentation and the bindings/impl split. **But,** it's ok for a "private" module with a `_` prefix temporarily.

> I'm fine with merging this now, as a board-specific special-purpose module. It would be great if you could do a more general PR later.
>
> @tannewt Do you have any comments?

No objections. Just that'd I'd love to see all CircuitPython boards benefit from these improvements.

**Comment by theacodes** [comment]
Thanks! This helps me solve a customer issue with BHB.

I definitely didn't want to do this for all boards just yet because it
would require either accepting conversions that are 64x longer for every
SAMD21 board or making changes to the API, which definitely warrants
further discussion.

When I'm on the other side of my move and done with the module I'm working
on I'll start the conversation for what a more flexible AnalogIn interface
would look like that lets folks configure multisampling, averaging, error
correction, and sample time.

**Comment by tannewt** [comment]
:+1: Note, we make no promises how fast AnalogIn is so 64x would be ok.

**Pull request merged**
