### PR TITLE
Add CIRCUITPY_MESSAGE_COMPRESSION_LEVEL

### PR DESCRIPTION
**Pull request by jepler**
to trade compile speed & flash size

Initially enable the faster mode on rp2040 and espressif, where there's usually plenty of flash available (these advanced techniques save hundreds to thousands of bytes, which is important on a lot of old samd21 boards but is a drop in the lake of a 4MB flash chip)

Levels are:
 - 1: fastest
 - 3: use qstrs
 - 5: use custom dictionary

Tested on the unix build (level 1) and still passes tests.

real time duration of running just maketranslationdata (not make) on a i5-1335U (newish laptop) for feather_rp2040 for various levels:
 - 1: 0.09s
 - 4: 0.29s
 - 9: 20.33s

### CODE REVIEW

**Comment by tannewt** [comment]
@eightycc What do you think? How does this interact with your changes?

**Review by tannewt — APPROVED** [review]
Looks good to me! I suspect eightycc will integrate their changes to speed up level 5.

**Comment by tannewt** [comment]
Very curious to see how much faster builds are since this step is run for every board and translation combination.

**Comment by eightycc** [comment]
Looks good to me, too. My changes will fit at level 5.

**Pull request merged**
