### PR TITLE
Add ability to disable BLE workflow

### LINKED ISSUE #5049: Adding the ability to control the state and behavior of the Bluetooth (sub-)system of the nRF52 chips in boot.py
While working on code for HID devices on the nRF52840 ItsyBitsy I am observing that as soon as power is applied to the board, it starts advertising (unknown to Windows) devices.
Only after code.py starts and executes code to present an HID device these "unknown devices" are "going away" and the device prepared in code.py gets advertised.
I think it would be helpful and allow a cleaner customer experience if the behavior of the default Bluetooth (sub-)system can be modified in boot.py as nowadays USB devices can be configured there.

If these, currently unknown to me devices, are necessary or helpful for OverTheAir updates or other useful things for customers, it would be good to add a API to allow the possibility in code.py to "to turn on" the original functionality in a user product.

### PR DESCRIPTION
**Pull request by tannewt**
Call `supervisor.disable_ble_workflow()` and the BLE workflow will
be disabled until the chip is reset.

This also includes a couple fixes:
1. Terminals can now be deinit by setting the tilegrid to NULL. This
  prevents using the tilegrid before display is init.
2. Fix BLE serial send amount when sending more than a single packet.

Fixes #5049

### CODE REVIEW

**Comment by tannewt** [comment]
@jepler I fixed the build so please take a look.

**Review by jepler — APPROVED** [review]
Thanks, and thanks for some quick answers in discord about the change.  No problems spotted, but no testing performed.

**Comment by ThomasAtBBTF** [comment]
This feature does exactly what I was asking for in #5049 
Thank you!
I can now call ```supervisor.disable_ble_workflow()``` in ```boot.py``` and no "strange" devices are appearing anymore after powering on the board.
As soon as the code in for my Bluetooth HID device is ready in ```code.py``` the correct advertising starts.

Remains the question: Is one of the initial devices providing the ability for "over-the-air" updates and if so, can the original workflow be reenabled by CiruitPython code?

**Comment by tannewt** [comment]
BLE provides functionality via services. A device can advertise different services at different times and provide different services at different times. Advertising only influences when something chooses to connect to another device. It doesn't limit what services are available once a connection is established.

If you want the BLE workflow stuff, then leave it enabled. The advertisements the core does shouldn't prevent HID from working because the HID advertisement will replace the first one.

**Pull request merged**
