### PR TITLE
Added initial support for my new TinyS3, FeatherS3 and ProS3

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
Added definitions for my new ESP32-S3 boards.
PIDs are from Espressif.

### CODE REVIEW

**Comment by prplz** [comment]
USB, flash and RAM never_resets don't need to be specified since: d99847b4106bfb767029e81eda810168ab5a5d03

**Comment by UnexpectedMaker** [comment]
> 

Hmm, ok, I'll go clean that up and also fix my pre-commit issues. Cheers!

**Review by dhalbert — CHANGES_REQUESTED** [review]
I don't know what the silk on these boards is, but you want to put the preferred name for a pin first in `pins.c` lists, so that it will print out that way and also will be used as the preferred pin name for the "PrettyPins" diagrams. See https://github.com/adafruit/circuitpython/pull/5652 for an example of where we reordered pin names.

Doing this as a "Request changes" just to flag it for attention.

**Comment by UnexpectedMaker** [comment]
> I don't know what the silk on these boards is, but you want to put the preferred name for a pin first in `pins.c` lists, so that it will print out that way and also will be used as the preferred pin name for the "PrettyPins" diagrams. See #5652 for an example of where we reordered pin names.
> 
> Doing this as a "Request changes" just to flag it for attention.

Hey Dan,

This is my preferred order for pins. Silkscreen is IO. I only include Dx and Ax for compatibility, but Dx and Ax should die in a big fire as it’s old legacy Arduino style and totally foreign to ESP32. 

I don’t use prettypins. My reference cards show IO first with Dx and Ax after.

**Review by dhalbert — APPROVED** [review]
OK, all set then!

**Comment by UnexpectedMaker** [comment]
For reference, this is what my pinout diagrams look like...
pins_feathers3

And is how all of my boards have been ordered in the past.

**Pull request merged**
