### PR TITLE
Upgrade ulab

### PR DESCRIPTION
**Pull request by jepler**
This version
 * moves source files to reflect module structure
 * adds inline documentation suitable for extract_pyi

There are some remaining markup errors in the specific revision of extmod/ulab but they do not prevent the doc building process from completing.

Once the docs have been merged into ulab's master branch we can update this PR and merge it.  We should do this sooner rather than later, because it will create an incompatible API change as well.

### CODE REVIEW

**Comment by tannewt** [comment]
:+1: We'll need newer `ulab` for GCC10 too. #3179

**Comment by v923z** [comment]
> 
> 
> 👍 We'll need newer `ulab` for GCC10 too. #3179

I think the issue concerns `microcpython` itself, and not the user modules. The relevant C flag is set in the Makefile, and not in the user-level make fragment. I haven't tried to compile with GCC10, but ping me, if there is a problem.

**Comment by jepler** [comment]
@tannewt this is the incompatible change I mentioned on discord

**Comment by v923z** [comment]
> Once the docs have been merged into ulab's master branch we can update this PR and merge it. We should do this sooner rather than later, because it will create an incompatible API change as well.

I think I am done with the reshuffling of the files/stubs. I would still like to merge the `norm` function for 6.0, but I am waiting for someone with that: https://github.com/v923z/micropython-ulab/pull/145.

**Comment by v923z** [comment]
@jepler Jeff, I fixed a number of indentation errors in the documentation. I can extract the stubs from the code without glitches. I don't know, whether the .rst files compile, though. I will check that out tomorrow.

**Comment by tannewt** [comment]
Note, this hits a sphinx autoapi issue: https://github.com/readthedocs/sphinx-autoapi/issues/234

**Comment by tannewt** [comment]
* Actually, the issue exists now so it shouldn't block this PR.

**Comment by v923z** [comment]
@tannewt Thanks for looking into this!

**Comment by tannewt** [comment]
What version of ulab does this update us to? (For release notes.)

**Comment by v923z** [comment]
> What version of ulab does this update us to? (For release notes.)

0.54.0.

**Pull request merged**
