### PR TITLE
Implement and use RUN_BACKGROUND_TASKS in place of MICROPY_VM_HOOK_LOOP

### PR DESCRIPTION
**Pull request by jepler**
I only touched the areas that I believe are specific to circuitpython, so as to reduce the chances of merge conflicts with upstream, so there are uses of the deprecated (to us) macro remaining.

Closes: #2013

### CODE REVIEW

**Comment by jerryneedell** [comment]
should this also be applied to HID as in #2050 ?

**Comment by jepler** [comment]
@jerryneedell yes, #2050 would need further (trivial) modification if this goes in first.  good catch.

**Comment by dhalbert** [comment]
I’ll review this by Tuesday. Thanks!

**Comment by dhalbert** [comment]
something weird about tinyusb update; investigating; don't merge yet

**Comment by jepler** [comment]
Ouch, I obviously made a mistake in my git use.  Do you want me to re-roll this whole PR to also get rid of the "reorder and reindent" part? @dhalbert

**Pull request merged**
