### PR TITLE
update nina-fw submodule

### PR DESCRIPTION
**Pull request by FoamyGuy**
update nina-fw submodule to latest commit from that repo so we get updated root cert in Circuitpython builds.

Not sure if I've done this properly, if there is something else needed or needs done differently let me know

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Review by jepler — APPROVED** [review]
Thanks. Looks like a sensible submodule update to me, didn't test.

**Comment by jepler** [comment]
@dhalbert do we want to bring this back to 7.2 as well? I don't know how many websites it's affecting.

**Comment by dhalbert** [comment]
> @dhalbert do we want to bring this back to 7.2 as well? I don't know how many websites it's affecting.

That's a good idea, though I don't think we have to have 7.2.1 immediately. @FoamyGuy, are the updated root certs broadly used?

**Comment by FoamyGuy** [comment]
The only specific site I know of that needs this is `https://jwst.nasa.gov/content/webbLaunch/flightCurrentState2.0.json?unique=12345`

I have not run into any others at this time.

**Pull request merged**
