### PR TITLE
Fix display invalid sh1107

### PR DESCRIPTION
**Pull request by jepler**
Closes: #6113

### CODE REVIEW

**Comment by jepler** [comment]
Testing performed:
 * pygamer still works
 * when running the crash reproducer from #6113, it doesn't crash

I did not immediately turn up an sh1107 display for testing, it would be good to test with one before merging this PR. Website says I do have a https://www.adafruit.com/product/4650 it just didn't immediately come to hand.

**Comment by ladyada** [comment]
@deshipu wanna test/review?

**Comment by jepler** [comment]
hmmm wait the issue says that SH1107 could be grayscale displays in which case this patch is wrong (it forces SH1107 quirk OFF except for 1-bpp displays).  https://cdn-shop.adafruit.com/product-files/5297/SH1107V2.1.pdf doesn't mention the possibility of a 2-bpp mode.

**Comment by dhalbert** [comment]
I added a validation check in `shared-bindings, and also left the forced fix in, because the `common-hal` routine can be called from other places, like a `board.c` file.

While looking through the messages for one I could reuse, I found several messages that are almost identical and could be merged. I'll make some PR for that later.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank!

**Review by dhalbert — APPROVED** [review]
All set now; thanks @jepler!

**Pull request merged**
