### PR TITLE
silabs: Fix _bleio.Descriptor.add_to_characteristic

### PR DESCRIPTION
**Pull request by picospuch**
New descriptors shall be added to characteristics succesfully now, tested on hid.py from adafruit_ble.

### CODE REVIEW

**Comment by dhalbert** [comment]
@silabs-ChatNguyen @silabs-BelaV Could you review this? Thanks.

**Review by silabs-ChatNguyen — APPROVED** [review]
This code resolves the issue related to adding a descriptor to a characteristic.
It looks good and should contribute to the source.

**Review by dhalbert — APPROVED** [review]
@silabs-ChatNguyen Thanks for the review.

**Comment by HonestQiao** [comment]
I tested on the EFR32xG24 Explorer Kit and was able to complete the ble hid function normally.
Thank you for your work! @picospuch

**Pull request merged**
