### PR TITLE
board.SPI() and board.I2C() for UnexpectedMaker Feather S2

### PR DESCRIPTION
**Pull request by FoamyGuy**
Tested successfully with 2.4" TFT Feather wing SPI display, and LSM6DS33 accelerometer sensor on I2C both set up using 
```python
i2c = board.I2C()
spi = board.SPI()
```

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I'm not sure what the remaining actions failures mean.

**Comment by dhalbert** [comment]
These failures seems to be AWS S3 upload failures that are network glitches or S3 glitches. Nothing to worry about.

**Comment by dhalbert** [comment]
Is it worth adding the default UART too?

**Comment by FoamyGuy** [comment]
Ah thank you. Yes I do think it will be good to add UART so this can match other devices (and re-use any existing code making use of it). 

I can add that today and push a new commit with it.

**Comment by FoamyGuy** [comment]
I did a quick test between UM Feather S2 and a Feather Sense with RX/TX connected running this "chirp" script:
```python
import board
import time

uart = board.UART()

b = bytearray()
text = "HELLO"
b.extend(text.encode())

while True:
    #read = uart.read()
    #if read:
    #    print("we got: {}".format(read))
    written = uart.write(b)
    print("wrote {} bytes".format(written))
    time.sleep(3)
```
It is working correctly for sending and receiving on both sides.

**Comment by UnexpectedMaker** [comment]
Great stuff @FoamyGuy !

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
