### PR TITLE
Update pins.c for lolin_c3_mini

### PR DESCRIPTION
**Pull request by chukwon**
also match lolin_c3_mini pins definition of new version

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
This is OK, but might you want to define a new board for the old and the new versions of the board? For instance, trying to blink `board.LED` in a simple way is going to fail on the NeoPixel version of the board.

**Comment by evildave666** [comment]
Since the v1.0 version of the board is depricated due to flaws in the antenna design and the board is already changed to match the v2.1 version, I'll take on making a new v1 board definition but may not get to it until after the holidays. circuitpython-org entry for the now-v2.1 board will need some edits removing the caveats regarding the antenna design flaw.

**Comment by dhalbert** [comment]
I'm thinking that if the v1.0 board is deprecated, a new board def may not really be needed. Instead, it could all be documented in the circuitpython.org description.

**Comment by dglaude** [comment]
I wonder what is the behaviour change on the V1 / V2.1 board.
I guess it is mostly the boot blinking vs colour that is affected.

So we have LED and NEOPIXEL alias, but if the goal is to focus on V2.1 then maybe LED can be removed.
That would make it perfect for V2.1 and V1 user just need to know that they can use NEOPIXEL to talk to their LED.

PS: I acquired both, but I will use the v1 for a non wifi and Arduino usage.

**Pull request merged**
