### PR TITLE
WIP: add simmel board

### PR DESCRIPTION
**Pull request by xobs**
This adds support for Simmel, an nRF52833-based bluetooth tracking
board designed to aid in pandemic tracing.

### CODE REVIEW

**Comment by ladyada** [comment]
@xobs plz add to the build queue so we can CI :)

```
Boards missing in .github/workflows/build.yml:
simmel
##[error]Process completed with exit code 1.
```

**Comment by xobs** [comment]
Thanks, added!

**Comment by ladyada** [comment]
@xobs k - when you push the addition, CI will re-run - if it passes we can review :)

**Comment by tannewt** [comment]
Looks like the CI needs to be changed so that it downloads the newer soft device.

**Comment by xobs** [comment]
Ah, the hexfile was in my local repo, but because `*.hex` is in `.gitignore` git silently ignored it.  Let's try this again.

**Pull request merged**
