### PR TITLE
enable CIRCUITPY_BLEIO_HCI on non-nRF boards where it will fit

### PR DESCRIPTION
**Pull request by dhalbert**
Boards with plenty of flash have room for the HCI version of `_bleio`. Previously this was enabled only for Metro M4 Airlift Lite, but since most any board can use an Airlift breakout, add it to all where it will fit. It is on by default for `CIRCUITPY_FULL_BUILD`.

`CIRCUITPY_BLEIO_HCI` is not enabled on SAMD21 boards due to size, and not on nRF since they have native BLE.

The added size is about 21.3kB.

I'll do this as a draft first to see what fails due to size.

### CODE REVIEW

**Comment by dhalbert** [comment]
This is ready for review. Everything passes. I had to make some minor adjustments to makefiles to get the `SRC_C` values correct.

@arturo182 This build does not need nvm. You might want to try this.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks @dhalbert.

**Comment by jerryneedell** [comment]
Should bleio_hci be built for the grand central_m4? I just built 6.0.0-rc0 and do not see it.

**Comment by dhalbert** [comment]
> Should bleio_hci be built for the grand central_m4? I just built 6.0.0-rc0 and do not see it.

It should be. Do you mean `import _bleio` does not work?

**Comment by jerryneedell** [comment]
never mind -- I forgot to look for the _   --- sorry for the false alarm

**Pull request merged**
