### PR TITLE
Sdcard odb fix

### LINKED ISSUE #3309: adafruit_sdcard causes device to lock up on versions newer than 4.1.2 when used with OnDiskBitmap
I have this code running on a PyPortal:
```python
import board
from adafruit_pyportal import PyPortal

# Set a data source URL
IMAGE_URL = "http://192.168.1.109:8000/image_compressed2.bmp"
TEXT_URL = "http://192.168.1.109:8000/test.txt"

# Create the PyPortal object
pyportal = PyPortal(
#    url=TEXT_URL,
#    image_url_path=IMAGE_URL,
    status_neopixel=board.NEOPIXEL,
    debug=True,
#    convert_image=False
)

pyportal.set_background(0xFF00FF)

# Go get that data
# print("Fetching")
# data = pyportal.fetch()

pyportal.set_background("/sd/cache.bmp")
print("after")
while True:
    pass
```
It was originally fetching the image to test an unrelated PR. Now it is just using `pyportal.set_background("/sd/cache.bmp")` to try to set the background to an image stored on the sdcard. 

When this code runs the PyPortal gets into a "stuck" state where `CIRCUITPY` becomes unresponsive and disappears. The serial console becomes unresponsive. If I press the reset button the device will reboot as normal but when the `set_background()` call executes it will get stuck again. If I press the reset button twice I do successfully get t bootloader mode. 

I can see 1 pixel (I think its 1) getting drawn at the top of the screen from my bmp image. But nothing else gets drawn on the screen and then the devices gets into the "stuck" state mentioned above. 

I have tested this on some older versions and have realized that back on Circuit Python version `4.1.2` this code works correctly. But `5.0.0` and anything newer (up to latest in S3) the code gets "stuck" as noted above. 

I'm guessing that something in the PyPortal library may need to be updated. But also perhaps there is a way in the core  to prevent this from getting into the "stuck" state?

### PR DESCRIPTION
**Pull request by FoamyGuy**
Resolves #3309 

Tested successfully with PyPortal.

@jepler helped create this fix for me. It was mentioned that there may need to be a similar solution added for framebuff APIs perhaps, that would be needed for the neopixels matrices if I understood correctly. 

I think I have the appropriate hardware to try to tackle that now but I will need a bit more guidance into where that fix is it within the code and whether the same strategy used here is applicable for it.

### CODE REVIEW

**Comment by jepler** [comment]
What I'm thinking--but haven't tested:
```
STATIC void _refresh_display(framebufferio_framebufferdisplay_obj_t* self) {
    self->framebuffer_protocol->get_bufinfo(self->framebuffer, &self->bufinfo);
    if(!self->bufinfo.buf) {
        return;
    }
    displayio_display_core_start_refresh(&self->core);
    const displayio_area_t* current_area = _get_refresh_areas(self);
```
This code in **shared-modules/framebufferio/FramebufferDisplay.c** needs to be changed so that it checks the return value of `displayio_display_core_start_refresh`.

The use in **shared-module/displayio/EPaperDisplay.c** should be corrected too.

I simply used `git grep` to list up all the files where the string `_refresh_display` appeared.

**Review by tannewt — COMMENTED** [review]
Is the top level background check not enough? https://github.com/adafruit/circuitpython/blob/main/shared-module/displayio/__init__.c#L43-L44

**Comment by jepler** [comment]
No, it's not.

We aren't entering background tasks recursively.  We're entering refresh recursively: first from a foreground refresh() call, then from background tasks run during SD card accesses by OnDiskBitmap.

**Comment by tannewt** [comment]
Do we need the top level test then? Could we remove it?

**Comment by jepler** [comment]
I think the test at https://github.com/adafruit/circuitpython/blob/main/shared-module/displayio/__init__.c#L43-L44 can be removed with or without this, because of `background_callback_run_all()`s checks for `!in_background_callback` -- https://github.com/adafruit/circuitpython/blob/main/supervisor/shared/background_callback.c#L71-L75

**Comment by tannewt** [comment]
Ok, @FoamyGuy please remove that outer display check. If you don't have time, let us know and we can finish it. Thanks!

**Comment by FoamyGuy** [comment]
@tannewt I think the latest commit removes the check you were referring to. Let me know if I've misunderstood and removed something different, or if I missed something else that needs to go with it.

I did not build this or test on a device after the latest commit. I can try that out later tonight.

**Comment by tannewt** [comment]
Yup! Thank you. That is what I was thinking.

**Comment by FoamyGuy** [comment]
I had missed one instance of that boolean variable being used. The latest commit takes care of that.

I did also build this version tonight and run it on a PyPortal and verify that the adafruit_sdcard and ondiskbitmap are still working properly.

**Review by tannewt — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
