### PR TITLE
Add PNG image support to the Stage library

### PR DESCRIPTION
**Pull request by deshipu**
That requires zlib to be enabled.

### CODE REVIEW

**Comment by deshipu** [comment]
I got it to fit even with the Japanese translation. No idea why one check was cancelled.

**Review by jepler — APPROVED** [review]
Neat, thanks!

**Comment by deshipu** [comment]
Sorry, I made one more small improvement, here comes version 1.3.4.

**Review by tannewt — APPROVED** [review]
Still good! CI failure is due to mac brownout.

**Pull request merged**
