### PR TITLE
Add Pimoroni Pico dv Demo Base (pico only)

### PR DESCRIPTION
**Pull request by RetiredWizard**
I'm submitting this as a Draft because WiFi on the Pico W version doesn't work yet. When the board boots, Web Workflow hasn't started and the board will crash into safe mode if you attempt the following:
```python
import wifi
wifi.radio.connect(ssid,passwd)
```
The standard Pico version of the Demo Base I've tested, The built-in SD card slot, I2S DAC and DVI out all seem to work great.

I've contacted Pimoroni and they've been very helpful with naming recommendations and obtaining the VID/PID pairs.
https://forums.pimoroni.com/t/adding-circuitpython-support-for-pico-dv/22012

### CODE REVIEW

**Comment by RetiredWizard** [comment]
Lady Ada demo'd a very similar build using a PIco Bell and the Pico W today, so I'm confident I just did something stupid and the Pico W version should work fine.

**Comment by RetiredWizard** [comment]
```python
import wifi
dir(wifi.radio)
```
Also causes a crash to safe mode.

**Comment by RetiredWizard** [comment]
I took the **board_init** function and the associated includes out of **pimoroni_pico_dv_base_w/board.c** and the crashes went away. I then ran the following script:
```python
import displayio
displayio.release_displays()

import time
import board
import picodvi
import framebufferio
from bitmaptools import draw_line

w=640
h=480
cd=1

fb = picodvi.Framebuffer(
    width=w, height=h, color_depth=cd,
    clk_dp=board.CKP, clk_dn=board.CKN,
    red_dp=board.D0P, red_dn=board.D0N,
    green_dp=board.D1P, green_dn=board.D1N,
    blue_dp=board.D2P, blue_dn=board.D2N)

display = framebufferio.FramebufferDisplay(fb)
```
and the DVI output worked along side the wifi module. One thing I did notice was that the IP address banner didn't display and looking at the demo Lady Ada posted her output did have that banner so I'm thinking this isn't the route she took. I'm guessing  that my problem has to do with the limited memory available after loading the core with both the DVI and WiFi modules and the board.c code:
```
#include "bindings/picodvi/Framebuffer.h"
#include "shared-module/displayio/__init__.h"
#include "shared-bindings/framebufferio/FramebufferDisplay.h"

void board_init(void) {
    picodvi_framebuffer_obj_t *fb = &allocate_display_bus()->picodvi;
    fb->base.type = &picodvi_framebuffer_type;
    common_hal_picodvi_framebuffer_construct(fb, 640, 480,
        &pin_GPIO7, &pin_GPIO6,
        &pin_GPIO9, &pin_GPIO8,
        &pin_GPIO11, &pin_GPIO10,
        &pin_GPIO13, &pin_GPIO12,
        8);

    framebufferio_framebufferdisplay_obj_t *display = &displays[0].framebuffer_display;
    display->base.type = &framebufferio_framebufferdisplay_type;
    common_hal_framebufferio_framebufferdisplay_construct(
        display,
        MP_OBJ_FROM_PTR(fb),
        0,
        true);
}
```

**Comment by RetiredWizard** [comment]
The only possibly useful observation I've made from todays poking at this is that when Web Workflow attempts to connect to the AP using **common_hal_wifi_radio_connect** it fails with a timeout (WIFI_RADIO_ERROR_UNSPECIFIED) after calling **cyw43_arch_wifi_connect_async**. However, attempting to execute ``wifi.radio.connect('ssid','password')`` from the REPL immediately crashes apparently without entering the **common_hal_wifi_radio_connect** module.

**Comment by RetiredWizard** [comment]
I'm removing the pico w version of this code and will submit that as a separate PR once I figure out my issue. I know Adafruit is working on a DVI PiCowbell that should work with the pico w so if I haven't figured it out by then, I suspect that release will point me to the solution.

This PR should be ready for review....

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
