### PR TITLE
fix French translations

### PR DESCRIPTION
**Pull request by supcik**
I found some small mistakes in the French (fr) translations.

### CODE REVIEW

**Comment by dhalbert** [comment]
@supcik Are you willing to make the changes through weblate? See https://github.com/adafruit/circuitpython/issues/1098. That helps us manage this better, automatically. THanks.

**Comment by supcik** [comment]
OK. I'll do that. Thank you for your reply.

**Comment by dhalbert** [comment]
@supcik Given how many changes you already made, I'm happy to merge this as is, so you don't have to redo the work, and then if you use weblate in the future, it will submit PR's automatically.

**Review by dhalbert — APPROVED** [review]
Thanks @supcik !

**Comment by supcik** [comment]
Thank you. I will use weblate for the future changes.

**Pull request merged**
