### PR TITLE
fix samd usb hid typo

### PR DESCRIPTION
**Pull request by hathach**
saw a couple of typos in usb hid. However, I didn't have samd board to test with, please double check to make sure this doesn't break anything.

### CODE REVIEW

**Comment by jerryneedell** [comment]
@hathach I tried the same test ```
from adafruit_hid.mouse import Mouse

m = Mouse()

# Click the left mouse button.
m.click(Mouse.LEFT_BUTTON)

# Move the mouse diagonally to the upper left.
m.move(-100, -100, 0)
```
on a feather m4 express with this PR  and it also works.

**Comment by jerryneedell** [comment]
It looks like the changes deal with the KEYBOARD, so this mouse test may not have been very meaningful.

**Comment by hathach** [comment]
@jerryneedell the extern with usb_hid_devices could be confusing as well. Some files may not linked to the correct implementations. Your test with mouse is also meaningful.

**Comment by jerryneedell** [comment]
@hathach  also tried this and it works
```
>>> from adafruit_hid.keyboard import Keyboard
>>> from adafruit_hid.keycode import Keycode
>>> kbd =Keyboard()
>>> kbd.send(Keycode.A)
>>> a
>>> kbd.send(Keycode.SHIFT,Keycode.A)
>>> A

```

**Comment by hathach** [comment]
:+1:

**Pull request merged**
