### PR TITLE
Fix RGB/BGR colors in Stage

### PR DESCRIPTION
**Pull request by deshipu**
This makes the colors used by the stage library compatible with those
used by the displayio library.

### CODE REVIEW

**Comment by deshipu** [comment]
I'm not sure to which branches I should make this pull request.

**Comment by tannewt** [comment]
`master` is good. We'll do a pre-release from it shortly.

**Comment by tannewt** [comment]
Hi hi, please push a new commit. The CI had trouble last night and it needs a push. Maybe add yourself as the copyright for these files?

**Comment by deshipu** [comment]
Those tests sure take a while to run...

**Comment by FoamyGuy** [comment]
I'm not sure what to do about the CI actions. But, I was able to build this and test with Pew Pew M4. All colors are appearing normal for me now. Thank you deshipu!

**Pull request merged**
