### PR TITLE
Enable bleio on esp32

### PR DESCRIPTION
**Pull request by microdev1**
Notable changes required to make this work:

1. Patch ESP-IDF:
    `BT_SOC_SUPPORT_5_0` was disabled for esp32.  
2. Enable `CONFIG_FREERTOS_PLACE_FUNCTIONS_INTO_FLASH`:
    The `iram0_0_seg` region overflowed by 3924 bytes. The documentation on optimizing IRAM usage is [here](https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32/api-guides/performance/ram-usage.html#optimizing-iram-usage).
3. Partition Scheme:
    The firmware overflowed by 11280K. This is a **Breaking Change** for esp32 and esp32c3 boards with 4MB flash.

Note: I have not tested this.

### CODE REVIEW

**Comment by MicroDev1** [comment]
The failed boards include esp32 boards with psram.
Even after disabling all `CONFIG_SPIRAM_CACHE_LIB**_IN_IRAM`, there is still an overflow of 3828 bytes.
`libesp_hw_support.a` alone contributes to an increase of 5199 bytes of IRAM usage.

**Comment by MicroDev1** [comment]
I went ahead and disabled `bleio` on esp32 boards with psram. This can be tracked in an issue.
Also, it would be nice if someone can test this. @Neradoc pinging you for interest.

**Comment by tannewt** [comment]
I'm waiting for someone to test this.

**Comment by Neradoc** [comment]
The only board without PSRAM I have is a Feather HUZZAH32 (v1) and it freezes on `import _bleio`, using the artifacts.
I might try to get a local debug build running later (also trying to make a 4MB-no-ota partition scheme to make it fit).

**Comment by dhalbert** [comment]
> I might try to get a local debug build running later (also trying to make a 4MB-no-ota partition scheme to make it fit).

It may be easier to turn off large things: `CIRCUITPY_ULAB = 0`, etc.

**Comment by Neradoc** [comment]
I got a debug=1 build that does output what is expected up until doing `import _bleio` in the REPL, after which it prints nothing, it just stops responding.

**Comment by MicroDev1** [comment]
> ...doing import _bleio in the REPL, after which it prints nothing, it just stops responding.

@Neradoc, thanks for testing. 

It's a bummer that this doesn't work. Our implementation is based on `BT-5.0` and the commit that enables `BT-5.0` on esp32 (https://github.com/espressif/esp-idf/commit/02636688eb08d3e86dc47aaf49c2ba2f265518f9) isn't in the `release/v4.4` branch.

I did a hacky patch of idf's BT Kconfig to enable `BT-5.0` on esp32 and was hoping that it works,
I think we should just wait for the switch to `esp-idf@v5.0` (#6913) and give this another shot then.

**Comment by jepler** [comment]
Would it make sense to close this PR and open a fresh one after switching to IDF 5.0?

**Comment by keen101** [comment]
Sorry to comment on something so old and seemingly unfixed / unresolved. 

But is it possible to get _bleio back for esp32 boards with psram, but tell it to not use the psram?

I was hoping to talk to a BLE temp sensor and tried using adafruit_ble to no avail since it relies on _bleio and it has been indefinitely disabled for ESP32. @dhalbert said in May 2023 that "ESP32-S3 boards have limited native _bleio support turned on." But I guess that was later changed in december the same year?

I would have thought such an issue would have been fixed by now, but it sounds like it may be a deep issue that is hard to resolve and not a high priority since regular bluetooth works? It sounds like micropython may do BLE a little differently, could the micropython way be adapted for circuitpython?

**Comment by dhalbert** [comment]
ESP32 boards for both 9.2.9 and 10.0.0-beta.3 have native `_bleio` enabled. This has been true for a while now. Is there something not working? Which board are you using?

**Comment by keen101** [comment]
> ESP32 boards for both 9.2.9 and 10.0.0-beta.3 have native `_bleio` enabled. This has been true for a while now. Is there something not working? Which board are you using?

Ah, ok, that's weird. I am running:

Adafruit CircuitPython 9.2.9 on 2025-09-07; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3
Board ID:adafruit_feather_esp32s3_4mbflash_2mbpsram
UID:8B8F268D0BC5

Mine does NOT seem to have _bleio. Even when i look using the REPL >>> help('modules'). I was trying to use adafruit_ble and got an error ImportError: no module named '_bleio'. Should I open a new bug for this? I do not want to clutter up this closed thread.

**Comment by dhalbert** [comment]
ESP32 is a specific chip, and ESP32-S3 is another specific chip -- it's confusing! `_bleio` was enabled for 4MB ESP32-S3 in earlier 10.0.0 dev releases, so try 10.0.0-beta.3.

**Comment by dhalbert** [comment]
You will need to update the bootloader. See https://learn.adafruit.com/adafruit-esp32-s3-feather/update-tinyuf2-bootloader-for-circuitpython-10-and-later

**Pull request closed without merging**
