### PR TITLE
Samd51: Allow setting dac (and ADC) reference voltage

### PR DESCRIPTION
**Pull request by jepler**
For instance, the following makes the audio output be 1V p-p at the output pins:
```
import samd
samd.reference_voltage_set(samd.ReferenceVoltage.V1_0)
samd.dac_reference_set(samd.DacReference.INTREF)
audio = AudioOut(...)
```

If this functionality is desired, I can continue to work on this PR.

This PR also includes the start of a (not properly divided out) API for enumerated types in Python that could reduce code size.  A "cp_enum_obj_t"  with convenience routines for finding a Python object for a given internal value, finding the internal value from a Python object, and for printing a value.  It could be used for pin direction, pull modes, etc. where each one has rolled its own code before now.  Probably the code savings is in the double-digit bytes, though, there's not a _LOT_ of code there.

### CODE REVIEW

**Comment by tannewt** [comment]
+1 to unifying enums internally.

-1 to `reference_voltage_set` method names. Instead, make an object to represent the DAC and statically create an instance so you can do `samd.dac.reference_voltage = 1.0`. I'd use floats for the voltage value for consistency. If the provided value is unsupported you could either raise an exception or pick the closest value below it and expect it to be read back. (We use this approach for bus frequency.)

**Comment by dhalbert** [comment]
> -1 to `reference_voltage_set` method names. Instead, make an object to represent the DAC and statically create an instance so you can do `samd.dac.reference_voltage = 1.0`. I'd use floats for the voltage value for consistency. If the provided value is unsupported you could either raise an exception or pick the closest value below it and expect it to be read back. (We use this approach for bus frequency.)

Many of the reference voltage values cannot be represented exactly in floating point, so there might be rounding issues. For instance, `1.1` can't be represented exactly. We might consider using millivolts or something else with an exact representation.

**Comment by jepler** [comment]
Integer millivolts if necessary, but I think enums are more self-documenting because a user doesn't have to do anything else except tab-complete in the repl to find out the valid values.

**Comment by dhalbert** [comment]
Have you thought about adding this to `analogio` to make it platform-neutral rather than `samd`?

**Comment by jepler** [comment]
Identifying a common API for reference voltages is harder.  Trying not to have "device-specific modules" for enhancing functionality of modules like ADC and DAC has led to us having only pretty basic functionality.  I thought that this would help with some MP3 playback problems (which it turns out not to) and I have no idea how to extend this to encompass multiple ports, so I guess we can just close this up.  I'll try to find time to see whether the enum factoring I started here actually gives a code size benefit when applied to stuff like pin directions and pulls, though.

**Pull request closed without merging**
