### PR TITLE
Cache configuration descriptor

### PR DESCRIPTION
**Pull request by tannewt**
We use it to open endpoints as they are used. Fetching the descriptor as needed can cause issues with devices that we're expecting a control packet while another transaction was ongoing. Specifically, a usb thumb drive didn't expect a control transaction while doing a SCSI transaction.

This PR also aborts transactions on timeout or ctrl-c interrupt. It doesn't always recover though...

### CODE REVIEW

**Comment by jepler** [comment]
I tried to update this PR by merging main into it, but github denied my attempt to push the result to tannewt's fork even though it says "maintainers are allowed to edit this pull request".  :shrug:

**Comment by dhalbert** [comment]
Scott had to give me extra permissions to do that. I think it's because it's forked from `micropython`.

**Comment by tannewt** [comment]
@jepler I sent you an invite to collaborate on my fork. Thanks for trying to update it!

**Review by jepler — APPROVED** [review]
pending the outcome of building

**Pull request merged**
