### PR TITLE
added new board - esp32 s3 pico

### PR DESCRIPTION
**Pull request by tirtharajsinha**

### CODE REVIEW

**Comment by tirtharajsinha** [comment]
Just finished testing thoroughly, everything looks good. Now waitng your review.

**Review by tannewt — APPROVED** [review]
Thanks!

**Comment by tirtharajsinha** [comment]
Thanks for merging. A quick question I created pull in main branch but noticed the bulid has been generated for only circuitpython 9.x.x. no build for 8.x.x. and 7.x.x. So to make them available on circuitpython download page do I have to create a pull request on branch 8.2.x and 7.3.x.

**Comment by tannewt** [comment]
Ya, you can cherry pick the commit onto 8.2.x and it will be in the next release. We're not planning on any more 7.x releases so no need to add it there. Next time, you can PR to 8.2.x and we'll merge it into main periodically.

**Pull request merged**
