### PR TITLE
 merge 2.x changes into master; touch up Makefile CFLAGS logic

### PR DESCRIPTION
**Pull request by dhalbert**
There are multiple commits here because they reflect all the commits to 2.x that are now being added to master. I'd suggest _not_ squashing these because they reflect the true history of the individual changes to 2.x.

### CODE REVIEW

**Comment by dhalbert** [comment]
rats - travis failure; CPX is overflowing flash with the internal frozen modules

**Comment by tannewt** [comment]
Ah, probably because its set up with the internal FS currently.

**Comment by dhalbert** [comment]
Gemma and similar do fit, with plenty of space. Also `-finline-limit=19` is causing breakage like I described in chat: some routines seem to have been optimized away. I have turned it off. That's weird, because `-finline-limit` works fine in 2.x. It may be due to some other `CFLAGS` changes.

I'll adjust things to disable the CPX frozen modules for now, except for neopixel.

**Comment by tannewt** [comment]
Looks like it needs a rebase. (Probably after your asf4 PR)

**Comment by dhalbert** [comment]
I'm seeing "This branch has no conflicts with the base branch" in github, so what makes it look like rebase is needed?

**Comment by dhalbert** [comment]
I did a regular merge instead of trying to rebase locall. I won't do that very often but I wanted to preserve the 2.x commits and I had applied all those after the asf4 pr. So not sure why it wasn't rebase-able but not worth spending too much time on.

**Comment by tannewt** [comment]
Ok, no worries! Thanks for doing that.

**Pull request merged**
