### PR TITLE
Add support for LILYGO TTGO T8 ESP32-S2-WROOM

### PR DESCRIPTION
**Pull request by fabaff**
Support for the [LILYGO TTGO T8 ESP32-S2-WROOM](http://www.lilygo.cn/prod_view.aspx?TypeId=50063&Id=1320&FId=t3:50063:3).

This board is similar to the `NanoESP32 S2 w/WROOM`.

<s>Like #6079 would this require a new VID/PID.</s>

### CODE REVIEW

**Comment by fabaff** [comment]
PID request: https://github.com/espressif/usb-pids/pull/37

**Comment by fabaff** [comment]
PID: `0x80EA`

**Review by dhalbert — CHANGES_REQUESTED** [review]
Could you merge or rebase from adafruit/circuitpython? There should not be a deletion in `locale/circuitpython.pot`.

**Review by dhalbert — APPROVED** [review]
(I'll merge once the CI completes.)

Thanks! Could you now submit a PR to https://github.com/adafruit/circuitpython-or for the board?

**Comment by fabaff** [comment]
Doc PR: https://github.com/adafruit/circuitpython-org/pull/872

**Pull request merged**
