### PR TITLE
Add new board crcibernetica-ideaboard

### PR DESCRIPTION
**Pull request by bborncr**
This is an ESP32 WROOM based board.  The board files modeled after the adafruit-feather-huzzah32.

### CODE REVIEW

**Comment by dhalbert** [comment]
Espressif boards need an `sdkconfig` as well as the other files mentioned in the guide. The best starting point is an `sdkconfig` from a similar board, with the same chip, etc.

**Comment by bborncr** [comment]
I have an `sdkconfig` file. The board is basically a copy of the Adafruit Feather Huzzah32 with pin changes. It appears that a `.gitignore` file removes the `sdkconfig` file.

**Comment by bborncr** [comment]
Here is the `.gitignore` that I believe removes my `sdkconfig` file:
https://github.com/adafruit/circuitpython/blob/main/ports/espressif/.gitignore

**Comment by Neradoc** [comment]
Oh yeah, I was working on adding a C3 board today and noticed that ports/espressif/.gitignore now ignores sdkconfig* (I noticed because it made `ag` skip those files by default). This comes from  #6974

**Comment by dhalbert** [comment]
@MicroDev1 Notice the .gitignore issue above, from #6974.

**Comment by MicroDev1** [comment]
> @MicroDev1 Notice the .gitignore issue above, from https://github.com/adafruit/circuitpython/pull/6974.

Following should allow inclusion of board skdconfig while blocking build files.
```patch
-sdkconfig*
+./sdkconfig*
```
@bborncr Can you make the changes? It seems like "Allow edit by maintainers" is turned off for this PR.

**Comment by bborncr** [comment]
Great! It worked! However, should it have built all Espressif boards?

**Comment by dhalbert** [comment]
> Great! It worked! However, should it have built all Espressif boards?

Yes, because changing the `.gitignore` file was at the top of `ports/espressif`, so it potentially influences anything below it.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
