### PR TITLE
traceback: fix for crash on non-native exceptions

### PR DESCRIPTION
**Pull request by timhawes**
Fix for #5704

### CODE REVIEW

**Comment by dhalbert** [comment]
@timhawes Could you make a PR against `7.1.x` instead of `main`? We would want to get this fix into `7.1.0`? Thanks!

**Review by microDev1 — CHANGES_REQUESTED** [review]
Thanks for the PR @timhawes. 

The reason for copying data from the pointer instead of pointing to the address is to avoid alteration of the traceback that is originally linked with the exception when a different traceback is supplied as a parameter.

Your changes gave me a hint regarding what is actually wrong here which is that native and non-native exceptions have different structures and the code is currently trying to copy the non-native exception on to a native exception struct, following should fix this issue:

```c
// From py/objexcept.c:
mp_obj_exception_t *get_native_exception(mp_obj_t self_in) {
    assert(mp_obj_is_exception_instance(self_in));
    if (mp_obj_is_native_exception_instance(self_in)) {
        return MP_OBJ_TO_PTR(self_in);
    } else {
        return MP_OBJ_TO_PTR(((mp_obj_instance_t *)MP_OBJ_TO_PTR(self_in))->subobj[0]);
    }
}

// Change to be made in shared-bindings/traceback/__init__.c:
mp_obj_exception_t exc = *get_native_exception(value);
```

**Comment by microDev1** [comment]
No need to create a new PR, I can rebase this for `7.1.x` and also make the suggested change.

**Review by microDev1 — APPROVED** [review]

**Comment by timhawes** [comment]
Thanks @microDev1.

I think there's still one more change needed. While the traceback should be attached to the native exception, we still need to pass the non-native exception into shared_module_traceback_print_exception(). Otherwise the final line of the traceback output will show the name of the native exception instead of the one that was raised.

**Comment by microDev1** [comment]
Thanks @timhawes for pointing that out, it should be fixed now.
Thanks @dhalbert for fixing formatting and traceback_test issues.

**Review by microDev1 — APPROVED** [review]

**Comment by dhalbert** [comment]
@timhawes We'll merge on your OK.

**Comment by timhawes** [comment]
Thanks @dhalbert @microDev1. I've retested on RP2040 and ESP32-S2 and I believe it's working correctly.

**Review by dhalbert — APPROVED** [review]
Thanks to both of you for this well-done fix!

**Pull request merged**
