### PR TITLE
SAM E54 Xplained Pro: add support for SST26VF064B flash chip

### LINKED ISSUE #8047: CIRCUITPY drive not appearing with SAM E54 Xplained Pro
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0 on 2023-05-22; SAM E54 Xplained Pro with same54p20
```

### Code/REPL

```
]0;🐍Done | 8.1.0\Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CIRCUITPY drive could not be found or created.
Press reset to exit safe mode.

Press any key to enter the REPL. Use CTRL-D to reload.
]0;🐍Done | 8.1.0\
```

### Behavior

USB drive appearing instead of CIRCUITPY drive.

### Description

Hello, could someone help me understand why after installing the latest CircuitPython to my SAM E54 Xplained Pro, the "CIRCUITPY" drive does not appear but "USB Drive" appears instead?

When trying to open the "USB Drive", a notification appears: "Please insert a disk into USB Drive (D:)."

I'm using the latest bootloader version (3.15).

storage.erase_filesystem() did not solve the issue.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tomiahola**
Fixes #8047

### CODE REVIEW

**Review by dhalbert — DISMISSED** [review]
Thanks for the update!

**Comment by tannewt** [comment]
@tomiahola Please test the build for the board under artifacts here: https://github.com/adafruit/circuitpython/actions/runs/5147018667?pr=8054

**Comment by dhalbert** [comment]
@tannewt Oddly these work:
```
ports/atmel-samd/boards/bdmicro_vina_d51_pcb7/mpconfigboard.mk:10:EXTERNAL_FLASH_DEVICES = "MX25L51245G","GD25S512MD"
ports/atmel-samd/boards/bdmicro_vina_d51/mpconfigboard.mk:13:EXTERNAL_FLASH_DEVICES = "MX25L12833F","MX25L51245G","GD25S512MD"
ports/atmel-samd/boards/bdmicro_vina_d21/mpconfigboard.mk:10:EXTERNAL_FLASH_DEVICES = "MX25L51245G","GD25S512MD"
```
Maybe because there are no spaces.

**Review by dhalbert — APPROVED** [review]

**Comment by tomiahola** [comment]
@tannewt, Hi, I downloaded the .uf2 file under the artifacts and installed it into the board: 
Now there is no response from the board, neither CIRCUITPY or USB Drive appears, and no COM port is detected.

**Comment by dhalbert** [comment]
I apologize this before testing; I misunderstood about whether testing had happened. Since it didn't work before, not such  big deal, but sounds like the flash chip definition may be wrong. There is no other board that uses this chip (or the smaller 2MB version), so there may be an error in the chip definition in `nvm.toml`.

**Pull request merged**
