### PR TITLE
Fix espressif run modes

### PR DESCRIPTION
**Pull request by MicroDev1**

### CODE REVIEW

**Comment by dhalbert** [comment]
@MicroDev1 Just to be clear, did you test this on a C3? I was going by what I saw in the datasheet but I may well be wrong.

**Comment by MicroDev1** [comment]
Yes, I did test it. The description for this can also be found in C3's [Technical Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-c3_technical_reference_manual_en.pdf#page=184).

> ...software can force switch the chip from SPI Boot mode to Download Boot mode
by setting register RTC_CNTL_FORCE_DOWNLOAD_BOOT and triggering a CPU reset...

**Comment by MicroDev1** [comment]
Yes, I did test it. The description for this can be found in C3's [Technical Reference Manual](https://www.espressif.com/sites/default/files/documentation/esp32-c3_technical_reference_manual_en.pdf#page=184).

> ...software can force switch the chip from SPI Boot mode to Download Boot mode
by setting register RTC_CNTL_FORCE_DOWNLOAD_BOOT and triggering a CPU reset...

**Review by dhalbert — APPROVED** [review]
Thank you for fixing and knowing the details about this!

**Pull request merged**
