### PR TITLE
Switch to using MP_ERROR_TEXT instead of translate, globally

### PR DESCRIPTION
**Pull request by jepler**
Most bits automatically generated by
```sh
git grep -l -F 'translate(' -- "**/*.[ch]" | xargs sed -i 's/\<translate(/MP_ERROR_TEXT(/g'
```

### CODE REVIEW

**Comment by jepler** [comment]
This also allows dropping differences in ulab for circuitpython (added to existing circuitpython 9 pull request at https://github.com/v923z/micropython-ulab/pull/647)

**Comment by jepler** [comment]
I think the reason this 'grew' some builds is that before this strings marked with MP_ERROR_TEXT weren't actually translated due to the regular expression in `makeqstrdefs.py`.

**Comment by jepler** [comment]
A useful way to view the diff is to check out the PR branch locally and
```
git diff -I'(translate|MP_ERROR_TEXT)\("'  origin/main HEAD
```
this suppresses any before/after line which is like `translate("` or `MP_ERROR_TEXT("`.
```diff
diff --git a/Makefile b/Makefile
index 88f8c54ad2..c834e413b1 100644
--- a/Makefile
+++ b/Makefile
@@ -227,7 +227,7 @@ pseudoxml:
 all-source:
 
 locale/circuitpython.pot: all-source
-	find $(TRANSLATE_SOURCES) -type d \( $(TRANSLATE_SOURCES_EXC) \) -prune -o -type f \( -iname "*.c" -o -iname "*.h" \) -print | (LC_ALL=C sort) | xgettext -f- -L C -s --add-location=file --keyword=translate --keyword=MP_ERROR_TEXT -o - | sed -e '/"POT-Creation-Date: /d' > $@
+	find $(TRANSLATE_SOURCES) -type d \( $(TRANSLATE_SOURCES_EXC) \) -prune -o -type f \( -iname "*.c" -o -iname "*.h" \) -print | (LC_ALL=C sort) | xgettext -f- -L C -s --add-location=file --keyword=MP_ERROR_TEXT -o - | sed -e '/"POT-Creation-Date: /d' > $@
 
 # Historically, `make translate` updated the .pot file and ran msgmerge.
 # However, this was a frequent source of merge conflicts.  Weblate can perform
diff --git a/extmod/ulab b/extmod/ulab
index 2df210f87a..eacb0c9af4 160000
--- a/extmod/ulab
+++ b/extmod/ulab
@@ -1 +1 @@
-Subproject commit 2df210f87a79deedc9003b1bbd6015a2fea7c03e
+Subproject commit eacb0c9af47f85f5d4864b721c3b28661364e8e3
diff --git a/locale/circuitpython.pot b/locale/circuitpython.pot
index 0aaca6ce69..e8530dab05 100644
--- a/locale/circuitpython.pot
+++ b/locale/circuitpython.pot
@@ -2958,6 +2958,10 @@ msgstr ""
 msgid "dtype must be float, or complex"
 msgstr ""
 
+#: extmod/ulab/code/ndarray_operators.c
+msgid "dtype of int32 is not supported"
+msgstr ""
+
 #: py/objdeque.c
 msgid "empty"
 msgstr ""
@@ -3822,6 +3826,10 @@ msgstr ""
 msgid "operation is not supported for given type"
 msgstr ""
 
+#: extmod/ulab/code/ndarray_operators.c
+msgid "operation not supported for the input types"
+msgstr ""
+
 #: py/modbuiltins.c
 msgid "ord expects a character"
 msgstr ""
diff --git a/ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.mk b/ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.mk
index 7ef2af6ddb..a53261995d 100644
--- a/ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.mk
+++ b/ports/atmel-samd/boards/arduino_nano_33_iot/mpconfigboard.mk
@@ -13,3 +13,4 @@ LONGINT_IMPL = NONE
 CIRCUITPY_FULL_BUILD = 0
 
 CIRCUITPY_RAINBOWIO = 0
+CIRCUITPY_NVM = 0
diff --git a/ports/espressif/common-hal/espcamera/Camera.c b/ports/espressif/common-hal/espcamera/Camera.c
index cdf7ab63c8..446e83d226 100644
--- a/ports/espressif/common-hal/espcamera/Camera.c
+++ b/ports/espressif/common-hal/espcamera/Camera.c
@@ -78,7 +78,7 @@ void common_hal_espcamera_camera_construct(
     camera_grab_mode_t grab_mode) {
 
     if (common_hal_espidf_get_reserved_psram() == 0) {
-        mp_raise_msg(&mp_type_MemoryError, translate(
+        mp_raise_msg(&mp_type_MemoryError, MP_ERROR_TEXT(
             "espcamera.Camera requires reserved PSRAM to be configured. See the documentation for instructions."));
     }
     for (int i = 0; i < 8; i++) {
diff --git a/ports/nrf/boards/arduino_nano_33_ble/mpconfigboard.mk b/ports/nrf/boards/arduino_nano_33_ble/mpconfigboard.mk
index 9b16834b50..cf6203bf18 100644
--- a/ports/nrf/boards/arduino_nano_33_ble/mpconfigboard.mk
+++ b/ports/nrf/boards/arduino_nano_33_ble/mpconfigboard.mk
@@ -6,3 +6,4 @@ USB_MANUFACTURER = "Arduino"
 MCU_CHIP = nrf52840
 
 INTERNAL_FLASH_FILESYSTEM = 1
+CIRCUITPY_ULAB = 0
diff --git a/py/makeqstrdefs.py b/py/makeqstrdefs.py
index cb229f9e5c..65f429ed54 100644
--- a/py/makeqstrdefs.py
+++ b/py/makeqstrdefs.py
@@ -146,7 +146,7 @@ def process_file(f):
         )
     elif args.mode == _MODE_ROOT_POINTER:
         re_match = re.compile(r"MP_REGISTER_ROOT_POINTER\(.*?\);")
-    re_translate = re.compile(r"translate\(\"((?:(?=(\\?))\2.)*?)\"\)")
+    re_translate = re.compile(r"MP_COMPRESSED_ROM_TEXT\(\"((?:(?=(\\?))\2.)*?)\"\)")
     output = []
     last_fname = None
     for line in f:
diff --git a/shared-bindings/pwmio/PWMOut.c b/shared-bindings/pwmio/PWMOut.c
index 1408696c11..fcb9d75fb1 100644
--- a/shared-bindings/pwmio/PWMOut.c
+++ b/shared-bindings/pwmio/PWMOut.c
@@ -268,7 +268,7 @@ STATIC mp_obj_t pwmio_pwmout_obj_set_frequency(mp_obj_t self_in, mp_obj_t freque
     pwmio_pwmout_obj_t *self = MP_OBJ_TO_PTR(self_in);
     check_for_deinit(self);
     if (!common_hal_pwmio_pwmout_get_variable_frequency(self)) {
-        mp_raise_AttributeError(translate(
+        mp_raise_AttributeError(MP_ERROR_TEXT(
             "PWM frequency not writable when variable_frequency is False on construction."));
     }
     mp_int_t freq = mp_obj_get_int(frequency);
diff --git a/supervisor/shared/translate/compressed_string.h b/supervisor/shared/translate/compressed_string.h
index 917f763d7d..442933a9c5 100644
--- a/supervisor/shared/translate/compressed_string.h
+++ b/supervisor/shared/translate/compressed_string.h
@@ -99,7 +99,7 @@ typedef struct compressed_string {
 // Return the compressed, translated version of a source string
 // Usually, due to LTO, this is optimized into a load of a constant
 // pointer.
-// mp_rom_error_text_t translate(const char *c);
+// mp_rom_error_text_t MP_ERROR_TEXT(const char *c);
 void serial_write_compressed(mp_rom_error_text_t compressed);
 char *decompress(mp_rom_error_text_t compressed, char *decompressed);
 uint16_t decompress_length(mp_rom_error_text_t compressed);
diff --git a/supervisor/shared/translate/translate.h b/supervisor/shared/translate/translate.h
index 76bc462625..fddf82675d 100644
--- a/supervisor/shared/translate/translate.h
+++ b/supervisor/shared/translate/translate.h
@@ -34,9 +34,8 @@
 // Map MicroPython's error messages to our translations.
 #if !defined(MICROPY_ENABLE_DYNRUNTIME) || !MICROPY_ENABLE_DYNRUNTIME
 #include "supervisor/shared/translate/compressed_string.h"
-#define MP_COMPRESSED_ROM_TEXT(x) translate(x)
 
-// translate() is a giant function with many strcmp calls. The assumption is
+// MP_ERROR_TEXT() is a giant function with many strcmp calls. The assumption is
 // that the build process will optimize this away and replace it with the
 // appropriate compressed data for each call site.
 
@@ -48,7 +47,7 @@
 #else
 // In link time optimized (LTO) builds, we can compile this once into a .o and
 // at link time the calls will be optimized.
-mp_rom_error_text_t translate(const char *c);
+mp_rom_error_text_t MP_COMPRESSED_ROM_TEXT(const char *c);
 #endif
 
 #else
diff --git a/supervisor/shared/translate/translate_impl.h b/supervisor/shared/translate/translate_impl.h
index a57f90ff41..e00480b58a 100644
--- a/supervisor/shared/translate/translate_impl.h
+++ b/supervisor/shared/translate/translate_impl.h
@@ -50,7 +50,7 @@ __attribute__((always_inline))
 #endif
 // Prevent instrumenting this because that disables the inlining we rely of for code size
 // optimization.
-__attribute__((no_instrument_function)) mp_rom_error_text_t translate(const char *original) {
+__attribute__((no_instrument_function)) mp_rom_error_text_t MP_COMPRESSED_ROM_TEXT(const char *original) {
     #ifndef NO_QSTR
     #define QDEF(id, hash, len, str)
     #define TRANSLATION(english_id, number) if (strcmp(original, english_id) == 0) { return (mp_rom_error_text_t)&translation##number; } else
```

**Review by dhalbert — APPROVED** [review]
This looks absolutely fine, and will open up more things to translate. Thanks for finishing off the differences from upstream.

**Pull request merged**
