### PR TITLE
Add AI thinker esp32c3s 2M

### LINKED ISSUE #5601: ESP-C3-32S   built-in 2MByte Flash
it seems the bin file at https://circuitpython.org/board/ai_thinker_esp32-c3s/ "adafruit-circuitpython-ai_thinker_esp32-c3s-en_US-7.1.0-beta.0.bin" is made with 4Mbyte partition table. and need to re make with 2MByte partion table.

### PR DESCRIPTION
**Pull request by prplz**
This board is a c3, so it can't support tinyuf2 and with only 2MB of flash, it doesn't have space for ota partitions.

- Add a new variable `UF2_BOOTLOADER` to the port makefile that is 1 when `IDF_TARGET` is esp32s2 or esp32s3
- Use `UF2_BOOTLOADER` to select whether to use a new partition variant, `partitions-xMB-no-uf2.csv`.
- Use `UF2_BOOTLOADER` instead of filtering out esp32c3 to select the .uf2 target

I made these changes with support for future (or past) non usb espressif chips in mind.

Tested on hardware.

Closes #5601

### CODE REVIEW

**Comment by prplz** [comment]
I have added the 4MB partition layout to fix the builds of the other c3 boards. Note this will stomp the filesystem of older c3 installations.

**Review by tannewt — APPROVED** [review]
Good idea! Thank you!

**Comment by prplz** [comment]
I just realized this breaks update_sdkconfig.py

**Comment by dhalbert** [comment]
Are the builds OK? I've put this in 7.2.0-rc.0.

**Pull request merged**
