### PR TITLE
Convert #include guards to #pragma once; add missing #pragma once

### PR DESCRIPTION
**Pull request by dhalbert**
- Add `#pragma once` to any CircuitPython-specific files that didn't have existing `#include` guards.
- Convert all CircuitPython-specific include files to use `#pragma once` instead of regular `#include guards`.

I was greatly aided in this by the https://github.com/cgmb/guardonce tool

#9257 had previously marked all CircuitPython-specific .c and .h files in their headers. I then applied this recipe:

```sh
# Add #pragma once to any .h files that didn't have it or regular 
ag --hh -l "this file is part of the circuitpython" |xargs checkguard | xargs sed -i -e '/\/\/ SPDX-License-Identifier/a\' -e '\' -e '#pragma once'
# I then reviewed the files quickly with gitk.
# A  couple of files after the above had to have a blank line added after `#pragma once`
# and devices/ble_hci/common-hal/_bleio/hci_include/l2cap_internal.h had to be touched up by hand.

# Then convert all include guards to #pragma once, stripping any trailing blank lines.
ag --hh -l "this file is part of the circuitpython" |xargs guard2once -s
```

### CODE REVIEW

**Review by jepler — APPROVED** [review]
As best I can tell, the changes are what's intended. github doesn't seem to like loading such a large diff but I did some local git work and it looks sensible.

**Comment by dhalbert** [comment]
There is some build warning here that is being ignored that I need to track down. It doesn't seem to affect the generated code, though. I did a smoke test and various qstrs look fine, so not sure if it's related to qstr generation.

From a local build of pico w, but I see this one any build:
```
Root pointer registrations updated
GEN build-raspberry_pi_pico_w/genhdr/root_pointers.h
Module registrations updated
GEN build-raspberry_pi_pico_w/genhdr/moduledefs.h
QSTR updated
GEN build-raspberry_pi_pico_w/genhdr/qstrdefs.generated.h
<stdin>:77:9: error: #pragma once in main file [-Werror]
cc1: all warnings being treated as errors
```

**Comment by jepler** [comment]
sorry for merging this prematurely. I should have left the review but not merged, but I was in a hurry and the board looked green. mea culpa

**Comment by dhalbert** [comment]
You didn't miss anything! It was green! I only saw the issue when I was doing a build locally for other reasons. I should have done more local testing.

**Comment by dhalbert** [comment]
I don't think this is actually causing any problems, but I should get rid of the warning.

**Pull request merged**
