### PR TITLE
Switch SAMD21 ticks to PER event

### LINKED ISSUE #3890: irremote-simpletest.py corrupts auto-reload, and other things on Circuit Playground Express
Using CircuitPython 6.0.0 on a Circuit Playground Express, after running the irremote-simpletest.py (below), auto-reload doesn't work (i.e. writing to CIRCUITPY doesn't force reload). Normal execution of a simple print loop with `time.sleep()` also doesn't seem to work properly. It hangs until keyboard input(?). The only recovery seems to be to re-install the bootloader AND CircuitPython (reset, and re-installing CircuitPython alone doesn't seem to fix the problem)

```
# Circuit Playground Express Demo Code
# Adjust the pulseio 'board.PIN' if using something else
import pulseio
import board
import adafruit_irremote

pulsein = pulseio.PulseIn(board.REMOTEIN, maxlen=120, idle_state=True)
decoder = adafruit_irremote.GenericDecode()

while True:
    pulses = decoder.read_pulses(pulsein)
    print("Heard", len(pulses), "Pulses:", pulses)
    try:
        code = decoder.decode_bits(pulses)
        print("Decoded:", code)
    except adafruit_irremote.IRNECRepeatException:  # unusual short code!
        print("NEC repeat!")
    except adafruit_irremote.IRDecodeException as e:  # failed to decode
        print("Failed to decode: ", e.args)

    print("----------------------------")
```

### PR DESCRIPTION
**Pull request by tannewt**
The EVSYS is used to generate an interrupt from the event. This
simplifies timing used in pulseio that conflicted with the
auto-reload countdown.

Fixes #3890

### CODE REVIEW

**Comment by DavePutz** [comment]
I tested this PR using  pulsein for a DHT11 on a Metro M0 Express. It consistently failed with too few pulses (between 69 and 73). The protocol is expecting 81 pulses. I will see if I can determine the cause.

**Comment by DavePutz** [comment]
It looks like the issue is that the line:
`
RTC->MODE0.COMP[0].reg = target;
`
in port_interrupt_after_ticks() is taking about 100us to complete. Since the pulses coming in from a DHT11 can be as short as
24us there can be more than one pulse counted as a single pulse. port_interrupt_after_ticks() looks to be getting called about every 525us, so in a ~4ms sequence of incoming pulses there will be several combined values, causing the inaccurate number of pulses. This looks like the same issue mentioned at https://www.avrfreaks.net/comment/2507091#comment-2507091; where modifying the COMP register on the SAMD21 can take up to 180us.

**Comment by tannewt** [comment]
Why does the duration of setting interrupt after tick matter? It should be interruptable by the pulsein code.

**Comment by DavePutz** [comment]
The time it takes to set and synchronize the COMP register is longer than some incoming pulses; and does not seem to be interruptible. This means we cannot afford to do that while an incoming pulse is taking place. As painful as it is, I think we need a way to simply avoid the COMP setting while in a pulse. I did some testing with a boolean flag that returns from  port_interrupt_after_ticks() in supervisor/port.c before hitting the COMP statement. It is set in pulsein_interrupt_handler( ) in PulseIn.c when  self->first_edge is true (i.e. at the very start of a pulse) and then is reset in common_hal_pulseio_pulsein_popleft() and common_hal_pulseio_pulsein_get_len() when self->len is 0 (i.e. as soon as possible at the the end of a pulse). This seems to work, allowing auto-reloads to work. I realize that there may be a slight delay if the reload gets scheduled while we're in the midst of an incoming pulse; but that window is ~4ms for a DHT and ~68ms for an irremote.

**Comment by tannewt** [comment]
Ok, @DavePutz. I added back the COMP set disable. I couldn't find a way to make it not stall the interrupt processing. It doesn't impact ticks anymore though because they use a separate EVSYS interrupt now.

**Comment by DavePutz** [comment]
I have found that moving the rtc_start_pulse from  common_hal_pulseio_pulsein_construct to the pulsein_interrupt_handler
shortens the pulsein window and lets the auto-reload work more consistently.  Patch file I used looks like:

```

--- a/ports/atmel-samd/common-hal/pulseio/PulseIn.c
+++ b/ports/atmel-samd/common-hal/pulseio/PulseIn.c
@@ -101,6 +101,9 @@ void pulsein_interrupt_handler(uint8_t channel) {
         start_overflow = overflow_count;
     }
     if (self->first_edge) {
+        #ifdef SAMD21
+        rtc_start_pulse();
+        #endif
         self->first_edge = false;
         pulsein_set_config(self, false);
     } else {
@@ -240,9 +243,6 @@ void common_hal_pulseio_pulsein_construct(pulseio_pulsein_obj_t *self,

     // Set config will enable the EIC.
     pulsein_set_config(self, true);
-    #ifdef SAMD21
-    rtc_start_pulse();
-    #endif

 }
```
Other than that the PR looks good.

**Comment by tannewt** [comment]
@DavePutz I don't want to move it to the interrupt handler because it could be delayed by a sleep. I did add a start/stop in resume/pause so that sleep will be allowed when pulsein is paused.

**Review by jepler — APPROVED** [review]
Thank you! No testing performed.

**Pull request merged**
