### PR TITLE
Merge 8.2.x to main

### PR DESCRIPTION
**Pull request by dhalbert**
This gets main up to date with 8.2.x. It includes a number of error message consolidations (not quite all, to avoid more skew) that were needed in 8.2.x to make a change fit.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
thanks!

**Comment by jepler** [comment]
looks like pre-commit wants some changes.

**Comment by dhalbert** [comment]
I did this in a fresh clone without fetching the submodules. I forgot that does not produce a correct result  for`make translate` because `ulab` is not available. Redid.

**Review by jepler — APPROVED** [review]
good to merge if green!

**Comment by dhalbert** [comment]
All builds are now OK. I had to revise a `board.c` that need changes for ESP-IDF 5.

**Review by jepler — COMMENTED** [review]
:christmas_tree:

**Review by jepler — APPROVED** [review]

**Pull request merged**
