### PR TITLE
BrainBoardz Neuron Commit (Final I Hope!) - Updated as Per Previous Instructions VID+PID Work

### PR DESCRIPTION
**Pull request by BrainBoardz**
Hi There: 

I've sorted out the VID/PID issues (it was actually just a re-install of MU!).  I've applied the changes that were requested on the Seventh Commit . Checked the firmware and all work fine.  Thanks for all the help with this!

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
This looks good!

As mentioned, please don't open a new PR for each commit. Just push a new commit to the existing PR with your changes. If you close a PR you can reopen it.

Also in the future please write descriptive commit messages, not "Fourth Commit", etc.

Now that this is merged, please submit a PR to https://github.com/adafruit/circuitpython-org to add the board to https://circuitpython.org.

**Comment by BrainBoardz** [comment]
Hi Dan:

That's great!  Thanks for all the help. I'm going to work on the PR for the
circuitpython-org and on the website over the weekend.

bye for now,

**Comment by makermelissa** [comment]
Hi @BrainBoardz, were you able to work on a PR for circuitpython-org? If you need help, we have a guide at https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website.

I was going to throw something up on circuitpython.org in its place for now, but I'm really not sure if this is for the Neuron Z3, Neuron M3, both, or a completely new board. I may just end up hiding it for now until you can get around to working on this.

**Comment by BrainBoardz** [comment]
Hi Mellisa:

If you could hide it for now I would really appreciate it. It won't be for
long! I'm waiting for final pre-production boards to come in before
submitting my PR to circuit python.org. I'd like to use a
photo of those production units on the site as they are the correct board
color etc.  If it can wait a little bit that would be great as the boards
will be arriving soon (they typically take a week or two at most). I was
going to work on the content for the page in the meantime.   Alternatively,
if updating the photo later would be not too much of a hassle I can
certainly proceed with what I have and get that to you this week. Please
let me know your preference.

In terms of the Neurons, I have two boards Z3 and M3, but they are
virtually identical in terms of capabilities (the M3 is smaller and does
not have the I2C header). Otherwise, they are identical and use
the same firmware and have the same components. They are both ESP32-S3's
with the same Flash and PSRAM.

**Comment by BrainBoardz** [comment]
Hi Mellisa:

Thanks for adding the temporary .md file etc. to circuit-python.org. It
looks like I should be getting my final boards delivered next week. I've
already started working on the description
etc. on my fork of the CircuitPython-org repository. So, the plan is to get
this all wrapped up by next week (hopefully!).

bye for now,

**Comment by makermelissa** [comment]
No worries. All good.

**Pull request merged**
