### PR TITLE
Pimoroni PICO DV Base w/Pico W (network disabled)

### PR DESCRIPTION
**Pull request by RetiredWizard**
I've spent several days trying to figure out if this board makes sense with a Pico W and if so how it should be configured. I've built the following configurations:

1) DVI and WiFi enabled and activated upon boot  ->  WiFi doesn't function and less than 50K working RAM
2) WiFi enabled and activated, DVI available but not activated -> less than 50K working RAM
3) WiFi/Cyw43 not included, DVI enabled and activated upon boot -> ~90K Working RAM

I really wanted option 2 to work but with less than 50K of RAM the REPL can be output but a displayio/framebuffer can't be loaded. The SD card and I2S audio work, although the audio has a lot of crackle. I suspect the WiFi is running and not leaving enough cycles to fully load the audio file from the SD card and play it smoothly. I'm not sure I see a lot of value in adding this carrier board to a Pico W if all it adds is the SD card slot and poor quality I2S audio.

I ended up going with option 3, which turns out to give the same capabilities as plugging in a normal Pi Pico to the carrier board. I suppose this might make sense if you wanted to use the Pimoroni board but only had a Pico W available. The display, SD card and I2S audio all work well. You do obviously give up any WiFi capabilities as well as the LED since on the Pico W, the LED is driven by the CYW43 module.

I left the Pico W firmware size adjustment in place even though with this build it's not necessary. Leaving it means that if a Pico W is re-flashed with this firmware the flash file system remains intact.

I haven't tested it yet, but I suspect, simply flashing the Pimoroni Pico DV Base for the Pico on a Pico W would give you virtually the same experience as using this build except that any files on the flash filesystem would be lost.

I'd appreciate any thoughts suggestions regarding my configuration choice and whether it makes sense to add a Pico W configuration for this carrier.

### CODE REVIEW

**Comment by tannewt** [comment]
Is it possible to use PicoDVI from user code? Or does the wifi init stuff prevent it?

**Comment by RetiredWizard** [comment]
> Is it possible to use PicoDVI from user code? Or does the wifi init stuff prevent it?

With option 2, you can bring up the PicoDVI HDMI output with user code. The REPL was displayed fine, but you're left with something like 45K of RAM memory free, which didn't seem to be enough to use the screen for anything else.

**Comment by tannewt** [comment]
I'm trying to get at whether a board def is valuable. If you can do PicoDVI from a normal Pico W build, then I'm not sure we want a compromised board def here.

**Comment by RetiredWizard** [comment]
I think you're right, it's probably not worth supporting a Pico W version of this if WiFi doesn't function. Let me build up the board without the DV init in the board.c (option 2) and try to do something useful with the display again.

I believe the PiCowbell DVI is in the exact same boat except that it doesn't have the other features (SD card, Audio DAC) that a custom firmware helps with.

**Comment by RetiredWizard** [comment]
I did some more testing with the full WiFi build, but with DVI output not initialized in board.c.

I didn't have any luck using any of the display helper libraries (adafruit_turtle, adafruit_display_text, adafruit_imageload), they all ran out of memory, however I was able to use the native displayio functions to display a bitmap image or draw pixels.

There's also a reset bug, the board will ctrl-D reset fine until ``display = framebufferio.FramebufferDisplay(fb)`` is executed, once the frame buffer is displayed pressing ctrl-D results in a crash to safe mode.

The user code I've been using to initalize the display is:
```py
import displayio
displayio.release_displays()

import board
import picodvi
import framebufferio

w=320
h=240
cd=8

fb = picodvi.Framebuffer(
    width=w, height=h, color_depth=cd,
    clk_dp=board.CKP, clk_dn=board.CKN,
    red_dp=board.D0P, red_dn=board.D0N,
    green_dp=board.D1P, green_dn=board.D1N,
    blue_dp=board.D2P, blue_dn=board.D2N)

display = framebufferio.FramebufferDisplay(fb)
```
Interestingly, the reset bug doesn't seem to be strictly related to memory used since the fb=picodvi... instruction is the one that uses the majority of available memory, but a ctrl-D reset works fine after executing that instruction.

**Comment by bill88t** [comment]
Even with almost no ram free, a simple "we receive display commands over uart / i2c / whatev" program can be used and makes *some* sense.

**Comment by tannewt** [comment]
@RetiredWizard I think that's enough. If folks need more, they can use a regular pico. Will the pico build work on the pico w to disable wifi? I don't think it is worth having a pico w build where wifi interfacing doesn't work.

**Comment by RetiredWizard** [comment]
So if we decide to include the Pico W version of this board I think this PR is ready. 

There's not enough memory to bring up the DVI display when the board boots, but it can be brought up with user code and both the WiFi and display function, albeit with only 40-50K of available memory.

The base board adds an SD card and I2S audio and both this PR and the existing PIco version firmware name those and the DVI pins appropriately.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
