### PR TITLE
Some cardputer definition improvements

### PR DESCRIPTION
**Pull request by bill88t**
Some tiny improvements.

The grove port pins are labeled as G1 & G2 on the physical product.
The current definition has literally every other name for the pins, other than these.
Note: They have never been labeled as any of the other names in docs or on the physical product.
Since this board was added in 9.0.x and not 9.1 I think we should leave the rest of the other pin names as is.

The port itself is labeled PORT.A, not the pins.
IMG_2024-05-25-01-00-52-226

While I was at it I fixed the M5Stack branding to match their website and the board default hostname.
Also for compilation time savings, I disabled the MAX3421E module, since this board doesn't have enough exposed pins to do spi (it's literally only got G1 and G2 exposed).

### CODE REVIEW

**Comment by dhalbert** [comment]
@jamesjnadeau @CDarius @RetiredWizard @joshua-beck-0908 Take a look.

**Comment by joshua-beck-0908** [comment]
> @jamesjnadeau @CDarius @RetiredWizard @joshua-beck-0908 Take a look.

Just looked through the commit.
I'm in favour of this change. 
It improves the consistency with what's actually written on the device.
Especially so for the uniformity of the board name, host name, and USB device name.

**Comment by jamesjnadeau** [comment]
Looks good to me, thanks for cleaning this up!

**Comment by RetiredWizard** [comment]
I'm phone access only (travelling 😀) so I didn't search the core to understand the MAX3421E parameter impact but the changes look good to me.

**Comment by CDarius** [comment]
Looks good to me too!

**Review by dhalbert — APPROVED** [review]
Thanks everyone for your reviews!

**Pull request merged**
