### PR TITLE
atmel-samd: add same51, feather_m4_can

### PR DESCRIPTION
**Pull request by jepler**
This is compile-tested, and requires updates in the related submodules:

https://github.com/adafruit/samd-peripherals/pull/35
https://github.com/adafruit/asf4/pull/37

This should not be merged until those can also be merged.

### CODE REVIEW

**Comment by dhalbert** [comment]
@jepler are the asf4 and samd-peripheral submodules up to the versions you want in the PR now?

**Comment by jepler** [comment]
No, I will tend to it tomorrow or monday.

**Comment by jepler** [comment]
@dhalbert I think this is ready to go, both the related PRs are closed merged.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Could you bump the submodule commits to the merge commits?

The merge commit for the latest asf4 is 
https://github.com/adafruit/asf4/commit/84f56af13292d8f32c40acbd949bde698ddd4507
Currently this is at https://github.com/adafruit/asf4/tree/1b87f18f8091f258e63f85cef54bcc7bafd44598

Similar for samd-peripherals: merge commit is https://github.com/adafruit/samd-peripherals/commit/2ff4ab05101ce7d3e105009cc6612df6e992123f.
This is at https://github.com/adafruit/samd-peripherals/tree/15fd96f4d8c38d5490767ea09469b82a231a768d

**Comment by jepler** [comment]
Happy to

**Review by dhalbert — APPROVED** [review]
:heavy_check_mark:

**Pull request merged**
