### PR TITLE
switch flash split to leave 512kB for CIRCUITPY

### PR DESCRIPTION
**Pull request by jepler**
I want to leave "at least 10% more free code space than raspberry_pi_pico". Switching CIRCUITPY storage to 512kB doubles what I had initially made it, while hopefully leaving enough space that we won't have to cut features from the Pico W that we enable on regular Pico.

Locally this gives:
```
1191372 bytes used, 377396 bytes free in flash firmware space out of 1568768 bytes (1532.0kB). (pico_w)
719248 bytes used, 325232 bytes free in flash firmware space out of 1044480 bytes (1020.0kB). (pico)
```

@bill88t I can't formally tag you as a reviewer but I would like your feedback. For your project, how much 'headroom' does 512kB leave you, or is it already too little?

This PR resizes the area for CIRCUITPY. This means that upgrading to this firmware, or subsequently downgrading to an older firmware, will erase CIRCUITPY. This means that switching between pico and pico_w firmware will erase CIRCUITPY. ***BACK UP YOUR CIRCUITPY BEFORE TESTING THIS PR*** -- **back up your CIRCUITPY before testing any new uf2 generated from this PR**

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]

**Comment by jepler** [comment]
OK, thanks for raising the issue @dhalbert ! The 4kB gap is needed for the nvm module, which also needed to be updated to allow the enlargement of the flash firmware area. I've updated the PR accordingly

**Comment by dhalbert** [comment]
I did similar stuff in `ports/atmel-samd/mpconfigport.h`, and in addition there I did some sanity checks on the given values to make sure they were not outside the range of flash memory, too big, etc.

**Comment by bill88t** [comment]
I do not know as to why this is not merged already, but in case you want a verification "it works",
image

**Review by dhalbert — APPROVED** [review]

**Comment by dhalbert** [comment]
@bill88t All set!

Btw, could you paste screen text in as text instead of images? Then we can copy/paste pieces of that further to reply. You can use the `< >` menu item to turn it into code-style text. Thanks.

**Pull request merged**
