### PR TITLE
docs: update sphinx conf.py to use cp_typing.

### PR DESCRIPTION
**Pull request by kbsriram**
- Adds circuitpython_typing to the intersphinx configuration.
- Adds a workaround to resolve TypeAliased references.

Fixes https://github.com/adafruit/circuitpython/issues/8119

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Thanks! this makes sense. I didn't look at the generated docs, though.

**Comment by kbsriram** [comment]
Thx for the quick turnaround! I downloaded the [docs.zip](https://github.com/adafruit/circuitpython/suites/14670086660/artifacts/832544293) artifact from the passing workflow for this PR, and did a spot check on a few files - they seem to have a clickable link in place now.
image

**Comment by jepler** [comment]
confirmed it's now correct in our published docs as well: https://docs.circuitpython.org/en/latest/shared-bindings/analogbufio/index.html#analogbufio.BufferedIn.readinto

**Comment by jepler** [comment]
Thanks for your sleuthing and a workable workaround!

**Pull request merged**
