### PR TITLE
uChip board support for Circuitpython environment

### PR DESCRIPTION
**Pull request by ITACAInnovation**
This is a pull request to add support for uChip into the Circuitpython environment.

We tested the attached code below and it seems to work with Circuitpython.
If there are any suggestions or changes needed, please let us know!

What is uChip in brief?
A complete USB dev board the size of a narrow 16-DIP package, featuring Atmel SAMD21 Cortex M0+ and onboard switching converters. (OTG compliant and power delivery up to 1A@5V or 3V3).
For more details refer to the ongoing campaign on kickstarter.
www.kickstarter.com/projects/1186620431/uchip-arduino-zero-compatible-in-a-narrow-dip-16-p

### CODE REVIEW

**Comment by dhalbert** [comment]
Please make the `.travis.yml` change in this PR by pushing another commit; I've closed #1701.

**Comment by ITACAInnovation** [comment]
Moved them all, check it out, there should be no more uChip folder now.

**Comment by dhalbert** [comment]
ok, great, we crossed while you were doing the renames.

**Comment by ITACAInnovation** [comment]
No problem, sorry for the delay.

**Comment by dhalbert** [comment]
The German (de_DE) build failed, almost certainly because of size. Add
```
CIRCUITPY_FREQUENCYIO = 0
```
to the end of your `mpconfigboard.mk` file, and it should be OK after that. See `gemma_m0/mpconfigboard.mk` as an example.

**Comment by ITACAInnovation** [comment]
The project built correctly I think.
Thanks for the support

**Pull request merged**
