### PR TITLE
Added nrfutil and S132 v5.0.0 support

### PR DESCRIPTION
**Pull request by microbuilder**
This pull request adds the nrfutil python code to the feather52/tools folder for easy installation. Instructions on properly installing nrfutil have been added to: `ports/nrf/boards/feather52/README.md`.

The SD download script has also been updated to download the S132 v5.0.0 SoftDevice header files.

### CODE REVIEW

**Comment by microbuilder** [comment]
We've had to make some changes to it, and it's likely quite static, but if you would prefer this in the /libs folder as a sub-module that's fine for me and I'll respin the PR accordingly, making a new nrfutil repo under the adafruit account.

**Comment by microbuilder** [comment]
Closing to resubmit at a later date.

**Comment by dhalbert** [comment]
OK by me, or did you have some changes?

**Comment by microbuilder** [comment]
I'm actually going to merge some other updates in to the PR, so it's easier to just make a new PR early this week. Thanks for the review, though, and you're right the /libs is the right place for this since it's a 3rd party codebase anyway.

**Comment by dhalbert** [comment]
In the asf4 repo, the master branch is as downloaded, master-bugfixes is clearly bugs, and then circuitpython is branched from that, with enhancements. Maybe that's a little excessive, but having at least "as-downloaded" and "my-changes" branches makes for easy merge updating.

**Pull request closed without merging**
