### PR TITLE
Add YD_ESP32_S3

### PR DESCRIPTION
**Pull request by bill88t**
Some info about this board can be found [here](https://github.com/vcc-gnd/YD-ESP32-S3).
~~Ongoing~~ Completed pid allocation pr [here](https://github.com/espressif/usb-pids/pull/90).

I will handle the circuitpython-org pr after this pr is approved.
There needs to be a note that for the neopixel to work, bridging the rgb pad is necessary.

### CODE REVIEW

**Comment by bill88t** [comment]
I have tested it a good bit on the n16r8 variant which I have. It's all good so far.
The pid pr should be merged soon, so I am marking this 'ready for review'.

**Comment by bill88t** [comment]
The pid has been secured.

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by bill88t** [comment]
For me, it works as is. Though I flash it manually.
I flash it with `esptool.py --after no_reset --chip esp32s3 --port /dev/ttyACM0 --baud 115200 write_flash 0x0 build-yd_esp32_s3_n16r8/firmware.bin)"`
I will test with `make flash`. If it needs to be changed to `qio` I will make a new PR.

**Comment by bill88t** [comment]
Flashing with:
`esptool.py --chip esp32s3 -b 2000000 -p /dev/ttyACM0 write_flash --verify -fm dio -ff 80m 0x0 build-yd_esp32_s3_n16r8/firmware.bin` works.
Flashing with: `esptool.py --chip esp32s3 -b 2000000 -p /dev/ttyACM0 write_flash --verify -fm qio -ff 80m 0x0 build-yd_esp32_s3_n16r8/firmware.bin` does not work. It doesn't boot.

```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x400454d5
SPIWP:0xee
mode:QIO, clock div:2
load:0x3fce3808,len:0x68
ets_loader.c 78
```

Meanwhile:
```
[bill88t@Pi400 | espressif]> esptool.py --chip esp32s3 -b 2000000 -p /dev/ttyACM0 flash_id
esptool.py v3.3.2
Serial port /dev/ttyACM0
Connecting...
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 34:85:18:98:63:44
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 2000000
Changed.
Manufacturer: c8
Device: 4018
Detected flash size: 16MB
Hard resetting via RTS pin...
```
Which if we run down to [flashchips.h](https://github.com/flashrom/flashrom/blob/master/include/flashchips.h) is a [GigaDevice GD25Q128](https://www.epal.pk/product/gigadevice-gd25q128-flash-memory-chip-128mbit-16mb/)
It is indeed Quad SPI, but I don't know why it doesn't boot like that.

**Comment by bill88t** [comment]
I would appreciate it if you could send the output of your `flash_id` @JiapengLi.

**Comment by bill88t** [comment]
Oh wait, your's can't boot either.
> I would like to change it to use qio, after change from dio to qio, the board fails booting.

I initially though yours did.
I have no idea honestly. But it certainly seems like our flash modules won't work with `qio` or `qout`.
For further discussion please open a new issue and ping me at it.

Some additional info I found while researching this issue:
https://docs.espressif.com/projects/esptool/en/latest/esp32s3/advanced-topics/spi-flash-modes.html#why-does-qout-dout-mode-work-but-qio-dio-mode-doesn-t-work

**Pull request merged**
