### PR TITLE
Add WeMos Lolin s2 mini wo/ psram

### PR DESCRIPTION
**Pull request by bill88t**
Well, today I happened to receive a lolin s2 from ebay that happens to have no psram.
Looks exactly the same as the original.

The original one is supposed to have 2mb, but this one does not.
The current circuitpy builds do not work with it, and instead bootloop cause of the missing psram.

This pr duplicates the currrent board configuration, with the changes needed.
Tested it. If I haven't forgotten any files, it is ready to go.

### CODE REVIEW

**Comment by dhalbert** [comment]
> Well, today I happened to receive a lolin s2 from ebay that happens to have no psram.
> Looks exactly the same as the original.

Is it clear it's genuine? Was it advertised as a Lolin S2 mini, or a different model?

**Comment by bill88t** [comment]
> Is it clear it's genuine?

It would be safe to assume it is not.

> Was it advertised as a Lolin S2 mini, or a different model?

Yes, it was advertised as a Lolin S2 mini, see for yourself, here is the [listing](https://www.ebay.com/itm/144742345862).

Here are the photos of what I received:
IMG_2022-11-28-21-42-17-929
IMG_2022-11-28-21-42-26-508

**Comment by dhalbert** [comment]
The listing even says: "ESP32 S2 Mini WIFI IOT Board ESP32-S2 4MB FLASH 2MB PSRAM For Arduino".

I would rather not add a counterfeit board. If it were clearly marked as a no-PSRAM version, that would be different, but I don't want to encourage these counterfeits that appear to be one thing but are really another. It will be a support headache.

**Comment by bill88t** [comment]
Well fair enough. Closing this pr then.

**Comment by overflo23** [comment]
i just bought the same counterfeit boards.
the differences are visible on silkscreen, marking on MCU and no ENIG finish on the PCB

comparsion_difference

the fake ones lack PSRAM you can see this when you put the board in flash mode (press O and RST, release RST)
than run 
esptool.py  chip_id

Chip is ESP32-S2FH4 (revision v0.0)
Features: WiFi, Embedded Flash 4MB, **No Embedded PSRAM**, ADC and temperature sensor calibration in BLK2 of efuse V1



more info:
https://forums.adafruit.com/viewtopic.php?t=197737

**Comment by bill88t** [comment]
'Files changed' is all you need to go ahead and make custom builds. They work a-ok.

**Comment by overflo23** [comment]
i just left this here so other people who run into the same problems can find more information.
but i agree, this venture is not worth the lifetime.

**Comment by shmick** [comment]
Looks like I managed to purchase a few of these boards and since I'm unable to get a refund from the seller, what would be the process to build the firmware for these boards that would allow them to work?

**Comment by dhalbert** [comment]
The `espressif_esp32s2_devkitc_1_n4` is an example of a board with 4MB and no PSRAM. It's pretty generic, since it's an official dev board, so you might just try loading that .bin or .uf2 and see what happens.

**Comment by shmick** [comment]
Thanks @dhalbert I'll give that a try. Thanks for the quick response!

**Comment by bill88t** [comment]
@shmick You can also just add a `CONFIG_SPIRAM_IGNORE_NOTFOUND=y` in sdkconfig of the regular board if you want to.

**Comment by shmick** [comment]
@dhalbert I loaded the bin for [ESP32-S2-DevKitC-1-N4](https://circuitpython.org/board/espressif_esp32s2_devkitc_1_n4/) onto the boards and it looks to be working. Thanks for the suggestion!

**Comment by probonopd** [comment]
Please do consider to add a `lolin_s2_mini_nopsram` configuration, or add `CONFIG_SPIRAM_IGNORE_NOTFOUND=y`.

This has cost me 4 hours today. The reality is that the boards without PSRAM are out there, and they are often even advertised as "without PSRAM", so I think this configuration without PSRAM should be supported.

Thank you very much for your kind consideration!

**Comment by dhalbert** [comment]
Is there anything about this board that makes it not generic? Are there missing pins or on-board devices?

If you'd like to submit a pull request for the board, that would be fine. See:
https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython
https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Comment by probonopd** [comment]
> Is there anything about this board that makes it not generic? 

What do you mean by this question? I think the only difference is the (advertised) absence of any PSRAM on this board variant.

**Comment by dhalbert** [comment]
I meant not generic compared to a "generic" ESP32-S2 board with no PSRAM and all the pins exposed. It's fine to have another board. I wonder if we could make a generic no-PSRAM build and make this board an alias of that one. There are a number of generic ESP-something boards that are have no special features -- they just expose all the pins, etc.

**Comment by probonopd** [comment]
Ah, I see. Yes, I can understand the push to keeping the number of boards down. Is there already a "generic ESP32-S2 board with no PSRAM and all the pins exposed" variant? I'd be happy to test that.

**Comment by dhalbert** [comment]
As mentioned above: https://github.com/adafruit/circuitpython/pull/7256#issuecomment-1722337702: the Espressif dev board with 4MB flash / no PSRAM. How much flash do you have?

**Comment by probonopd** [comment]
4 MB. The [ESP32-S2-DevKitC-1-N4](https://circuitpython.org/board/espressif_esp32s2_devkitc_1_n4/) seems to work on my board. (But it is not what people find when they search for "S2 Mini" on the download page. Maybe the description of that board could be expanded to point people without PSRAM to the correct one.)

**Comment by tannewt** [comment]
@bill88t Want to revisit this?

I'm for adding board defs for new boards. They leave opportunity for board specific customizations now and in the future.

**Comment by dhalbert** [comment]
I just want to make sure that a "Lolin S2 Mini no PSRAM" is really a "Lolin" board, and not some unauthorized use of a manufacturer's name.

**Comment by probonopd** [comment]
In this case, I'd leave away the "Lolin" and just call it generic "S2 Mini no PSRAM".

**Comment by bill88t** [comment]
> @bill88t Want to revisit this?
> 
> I'm for adding board defs for new boards. They leave opportunity for board specific customizations now and in the future.

Sure, what do you have in mind? I don't have a solution to this dilemma unfortunately.

> I just want to make sure that a "Lolin S2 Mini no PSRAM" is really a "Lolin" board, and not some unauthorized use of a manufacturer's name.

Yea the issue is usb PID/VIDs.
It's probably fine if it's a generic VID like espressif's, but if it's another company's, we can't exactly reuse that for boards that just.. look similar, yet are incompatible one way or another.

I still think the best case scenario would just have psram-less boards work on the main build, as every other solution has some bigger drawback.

**Comment by tannewt** [comment]
> Yea the issue is usb PID/VIDs.
> It's probably fine if it's a generic VID like espressif's, but if it's another company's, we can't exactly reuse that for boards that just.. look similar, yet are incompatible one way or another.

Get one from: https://github.com/pidcodes/pidcodes.github.com It is ok to have a closed source board if you aren't the creator of it.

**Pull request closed without merging**
