### PR TITLE
Switch all ports to auto-growing split heap

### LINKED ISSUE #7334: revamp supervisor allocation API
I have a sketch at https://github.com/jepler/circuitpython/commit/e635457a32b1cc3b4b611808fcdd16951d12f99c but it doesn't boot.

The idea is to do more to leverage the gc allocator to make the supervisor allocator work.

See the commit message for more details.

Entered as an issue at @tannewt 's request

I don't plan to work on this until after 8 is out, but it was in my brain and I had to do at least this much of it.

### LINKED ISSUE #8512: Adapt `gc_deinit()` and `gc_never_free()` to use split heaps
We added `gc_deinit()` and `gc_never_free()`, but I think they need work for split heap use.

Tentatively assigned to @tannewt as part of the split heap work.

### PR DESCRIPTION
**Pull request by tannewt**
This simplifies allocating outside of the VM because the VM doesn't take up all remaining memory by default.

On ESP we delegate to the IDF for allocations. For all other ports, we use TLSF to manage an outer "port" heap. The IDF uses TLSF internally and we use their fork for the other ports.

This also removes the dynamic C stack sizing. It wasn't often used and is not possible with a fixed outer heap.

Fixes #8512. Fixes #7334.

### CODE REVIEW

**Comment by bill88t** [comment]
This has the potential to fix a lot more issues than just these two.
For those as eager as me to test it, `make fetch-port-submodules` before compiling.

The first round of testing is however not so pleasant. MemoryErrors.
A simple way to reproduce it would be:
```py
>>> a = bytearray(60000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 60000 bytes
>>> import gc
>>> gc.mem_free()
4130048
```
Big bulky modules (even around 40kb) fail to load.

**Comment by RetiredWizard** [comment]
I tried loading the UM Tinypico artifact (hoping #7288 might be affected). Some moderately large programs that exhibited the memory variable corruption before now run fine, but the largest programs that exhibited the issue now simply don't load and immediate display the following message: 
```
Adafruit CircuitPython 9.0.0-alpha.2-12-g151e38eefe on 2023-11-01; TinyPICO with ESP32-PICO-D4
>>> import PyDOS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: 
```

**Review by dhalbert — CHANGES_REQUESTED** [review]
This is really wonderful. It's so much simpler and more straightforward. I added a couple of `CIRCUITPY-CHANGE` annotations and will just add those in myself and the approve and merge.

**Comment by dhalbert** [comment]
@bill88t @RetiredWizard

@tannewt and I discussed this. We will merge as is and then work on tuning to fix `MemoryError`s.

**Comment by RetiredWizard** [comment]
I did some more testing on the Unexpected Maker TinyPico and this does seem to fix #7288. The memory error I was getting on loading my largest program also goes away if I don't include the wifi parameters in settings.toml. It's probably not surprising that enabling the web workflow stresses the available memory, but perhaps some additional garbage collecting around the web workflow could help?

**Review by dhalbert — APPROVED** [review]

**Comment by tannewt** [comment]
> Edit: Just realizing web workflow is C based, garbage collecting probably doesn't apply 🤷
> I have also caused the memory error upon load without web workflow enabled by attempting to load an even larger program.

Ya, it doesn't do garbage collecting. With the split heap work, IDF allocations will be intermingled with CP heaps rather than leaving the PSRAM exclusively for CP. It won't work for ever larger programs unfortunately.

**Pull request merged**
