### PR TITLE
Add IncrementalEncoder for mimxrt1011

### PR DESCRIPTION
**Pull request by jepler**
.. and write a general 'pin change interrupt' facility to power it

This uses the same quadrature state machine as atmel-samd, nrf, and rp2040. The 1011 doesn't have a dedicated encoder peripheral, so we go the pin-change + software route.

### CODE REVIEW

**Comment by jepler** [comment]
Do I need to treat this new table of interrupt information as a GC root? in some weird case (like if you don't save your IncrementalEncoder object anywhere, i.e., a bug) it might be the only thing that would keep the object alive.

**Comment by jepler** [comment]
I added the pin change pointers to gc root. Let me know where the pin change infra should go, if not in Pins.c. I _envision_ that it would be shared with other possible uses of pin change interrupts (like pulsein?)

**Comment by tannewt** [comment]
> Do I need to treat this new table of interrupt information as a GC root? in some weird case (like if you don't save your IncrementalEncoder object anywhere, i.e., a bug) it might be the only thing that would keep the object alive.

I think you can use MP_STATE_PORT or use a finalizer to stop the interrupts when the object is GCed.

> I added the pin change pointers to gc root. Let me know where the pin change infra should go, if not in Pins.c. I _envision_ that it would be shared with other possible uses of pin change interrupts (like pulsein?)

I think `peripherals` is a good place for non-CP specific helper code.

**Comment by jepler** [comment]
I would be reluctant to introduce a finalizer since it would add code on all ports.

If the code is moved to the nominally CP-independent 'peripherals' then I couldn't put the pointer table in MP_STATE_PORT.

**Comment by gneverov** [comment]
fwiw, I started a pattern for interrupt tables in peripherals for rp2040 [here](https://github.com/adafruit/circuitpython/pull/7554/files#diff-f9d614d48685212feb0b6563c3a62d45fd1997d3ebe291dd0bc98b4b4339d2fb). I even independently created the same "port gc collect" function from this PR!

I didn't need to store anything in MP_STATE because the gc collect function is used to mark the peripheral's global variables as gc roots.

**Comment by tannewt** [comment]
> I would be reluctant to introduce a finalizer since it would add code on all ports.

It's not much. The flag in the GC and a mapping from `__del__` to the deinit function. Are you sure other ports handle this correctly now? I don't think we do this well in some places already.

> If the code is moved to the nominally CP-independent 'peripherals' then I couldn't put the pointer table in MP_STATE_PORT.

You don't need to gc_collect the pointer table if all of the objects remove themselves from it before their memory is freed. It's not useful to have a python object only alive from this pointer table.

**Review by tannewt — DISMISSED** [review]
Thank you!

**Comment by dhalbert** [comment]
One conflict to resolve.

**Comment by jepler** [comment]
Needs a re-review. No change besides fixing the merge conflict.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
