### PR TITLE
nrf: Fix SPI transfers with data larger than HW allows

### LINKED ISSUE #963: Unable to mount SD card on nrf52832
I just built the feather nrf52832 board from master and tried to mount my SDCard as I have routinely on this board, but it failed with:

```
Adafruit CircuitPython 3.0.0-rc.0-27-g91427b0 on 2018-06-26; Bluefruit nRF52 Feather with NRF52832
>>> 
>>> 
>>> import sdmount_lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sdmount_lib.py", line 12, in <module>
OSError: [Errno 19] ENODEV
>>> 

```
Did something change? Or did something break?

### PR DESCRIPTION
**Pull request by arturo182**
Fixes #963

### CODE REVIEW

**Comment by arturo182** [comment]
Yes, nRF52832 supports transfers up to 255 bytes at a time, but nRF52840 supports up to 65535 bytes, the vfs module tries to read 512 byte blocks and this is why it was failing only on the nRF52832.

**Comment by arturo182** [comment]
Noooo, my English has failed me 😭

**Comment by tannewt** [comment]
My english fails me too from time to time and it's the only language I
speak. You are way ahead of me. :-)

**Comment by jerryneedell** [comment]
Downloaded into current master and tested on feather32832 - fixes #963 Thank you!

**Pull request merged**
