### PR TITLE
ESP32-S2: AnalogOut

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds the AnalogOut module to the ESP32S2. Tested on a Saola 1 Wrover, works correctly across the ESP32S2's effective range of 0.1V minimum to 3.15V maximum.

Requires #3501 for merge compatibility. View latest commit for AnalogOut specific changes.

### CODE REVIEW

**Comment by tannewt** [comment]
Please update this now that the IDF switch is merged.

**Review by tannewt — CHANGES_REQUESTED** [review]
You've included reverting ports/atmel-samd/peripherals. Please undo it.

**Comment by hierophect** [comment]
@tannewt thanks for spotting that... how did it get in there? Git merge plays games with me that I'll never understand.

**Comment by tannewt** [comment]
Please merge in main so the diff here doesn't include the AnalogIn changes.

**Comment by hierophect** [comment]
@tannewt done

**Review by tannewt — APPROVED** [review]
Nice and simple! Thank you!

**Pull request merged**
