### PR TITLE
Merge MicroPython V1.14

### PR DESCRIPTION
**Pull request by microDev1**
This PR merges in upstream [MicroPython](https://github.com/micropython/micropython) changes till release [V1.14](https://github.com/micropython/micropython/releases/tag/v1.14).

**Notes :-**
- `mpy-cross` builds successfully. `CI` currently fails at `buid unix port`.
- I am doing a draft PR to get the changes reviewed before adapting the rest of the codebase to it. 

**Changes :-** 
- Upstream ran a code formatting script... so a lot of the changes are formatting related. 
  We can run the formatting script later in another PR after this is merged for consistency.
- Okay there's just too much to document here so I'd suggest to just dive write in... :)
- To be fair... I have only taken a look at the conflicting changes... can we split this up? I am thinking based on a directory basis.
  I'll update this section once there is more info for future reference.

### CODE REVIEW

**Comment by dhalbert** [comment]
Thank you for starting to work on this! The last time I did it was #1068, in 2018.

I would really like to understand the changes rather than just depend on automatic merging. To that end, I think it would be good to make some of the changes that MicroPython has made, by hand, first, so minimize the diffs.

For instance:
- Code formatting: If we reformat the code in advance according to the same style rules, that will greatly reduce the number of changes.
- Some macros were renamed or made lower-case. We can make those changes in advance.
- Some casting styles might have been changed, and we can make those changes too.
- We can remove things in advance that are still leftovers, or remove them in the merge. For example, we don't use `drivers/` much if at all, and if we can just discard the incoming files, that would be good.
- Discard all the code for new MicroPython ports (maybe you did this already).

The worst merge issues I had were in `extmod`, for the modules that we still used, like the `vfat` code. The `py` modules also merit very careful inspection.

We changed the signatures for Python API routines in `shared-bindings` and the leftovers in `extmod`, and we need to keep those changes. Again, maybe you did that already.

**Comment by microDev1** [comment]
@dhalbert Thanks! for the suggestions.

> Code formatting: If we reformat the code in advance according to the same style rules...

I ran the same script (i.e. [tools/codeformat.py](https://github.com/micropython/micropython/blob/v1.14/tools/codeformat.py)) on the whole `CPY` codebase. 
I had to modify it a bit as I got an `IndexError`. That reduced about 150 files from the diff.
I can make a PR for it... I think I should wait for the open PRs to come down a bit before doing that.

> Some macros were renamed... casting styles might have been changed... 

These can have another PR too... 

> We can remove things in advance that are still leftovers... we don't use `drivers` much if at all... Many of the new things in extmod we don't need or we should bring in selectively by hand...

Sure, I plan to rebase this a few times. These can be handled based on the reviews.

> Discard all the code for new MicroPython ports... We changed the signatures for Python API routines in shared-bindings and the leftovers in extmod, and we need to keep those changes...

Ya... I have only kept changes in `drivers` `extmod` `py` `lib` `mpy-cross` `tests` `tools` and some files in `root`.
I used `git blame` a lot to resolve conflicts so `CPY` specific changes are still present.

**Comment by microDev1** [comment]
[`V1.15`](https://github.com/micropython/micropython/issues/6832) is around the corner. Should we wait?

**Comment by tannewt** [comment]
I don't think so. I'd expect merging 1.15 in to be easier after 1.14 has already been. I suspect 1.14 merge will be much more difficult. We shouldn't merge 1.14 until we branch off for 6.2.0 though because it may lead to instability.

**Comment by dhalbert** [comment]
> I don't think so. I'd expect merging 1.15 in to be easier after 1.14 has already been. I suspect 1.14 merge will be much more difficult. We shouldn't merge 1.14 until we branch off for 6.2.0 though because it may lead to instability.

Though if 1.15 comes out before 6.2.0 is branched, I'm not sure it makes much difference if we start with 1.15.

**Comment by tannewt** [comment]
We've marked the `main` branch as 7.x so now is the time to do it. In particular, 1.14 will bring a new mpy version. The sooner we switch to it, the simpler it'll be to match 7.x mpys to 7.x CP builds.

**Comment by tannewt** [comment]
1.15 is out: https://github.com/micropython/micropython/releases/tag/v1.15

**Comment by tannewt** [comment]
I've started this merge work but am taking a different approach. I'm merging each MP release from 1.10 up to 1.15. This will make the merges a bit more tractable and easier to hunt errors/bugs as we find them. (Started in #4646 )

**Comment by microDev1** [comment]
> I'm merging each MP release from 1.10 up to 1.15. This will make the merges a bit more tractable and easier to hunt errors/bugs as we find them.

I agree, merging all of it at once is kinda overwhelming.

**Pull request closed without merging**
