### PR TITLE
serial.c filter uart console non utf-8 on startup

### LINKED ISSUE #9104: ESP32 Sunton board - Noise on USB Serial at startup causes occasional board freeze
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-14-gc035ade1fd on 2024-03-27; sunton_esp32_2432S028 with ESP32
```

### Code/REPL

```python
No Code.py

or

import sys
a = ""
while a != 'q':
    a=sys.stdin.read(1)
```

### Behavior

When the board powers up with no code.py running, random characters frequently appear as input to the REPL, I believe if the core reads the uart device for console input at the "press any key to enter REPL" prompt and encounters a non-utf8 character it sometimes hangs the device and requires a hard reset to recover.

When I run a code.py file that executes a `sys.stdin.read(1)` command the board doesn't freeze but the code.py program will occasionally crash with a Unicode error:
```
(81136)/>Traceback (most recent call last):
  File "code.py", line 5, in <module>
  File "PyDOS.py", line 1260, in <module>
  File "PyDOS.py", line 510, in PyDOS
  File "/lib/pydos_ui.py", line 593, in input
UnicodeError: 
```
The code.py issue is easy enough to work around by using a try/except block but when there's no code.py file the occasional hangs can be a pain. 

### Description

The root of this problem is most likely a hardware issue, however I think I've seen similar issues on other uart based console boards and I'm wondering if it's worth throwing a minor change into the core to ease the user experience on devices with this issue.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RetiredWizard**
Replace non UTF-8 character on serial UART input buffer during board startup at "Press any key to enter REPL" prompt.

Fixes #9104

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
We have seen similar junk on UART lines on startup, caused by other hardware issues: https://github.com/adafruit/circuitpython/issues/8890.

If this only happens on startup, then I think the fix is to clear the input buffer early on to discard any junk input.

I am not sure if your fix will work when a UTF-8 prefix is read and no further character is read immediately. Will the prefix then be discarded? If someone is trying to send a multi-byte UTF8 character then this I think may prevent that character from being read properly.

**Comment by RetiredWizard** [comment]
I thought I remembered seeing the issue before but I guess I didn't look hard enough. I like your idea of clearing the input buffer.

I think this PR only addresses a problem caused waiting for the "press any key to enter repl" prompt and it looks to me like that prompt only reads a single byte and doesn't really do anything with it except maybe check for ctrl-D. I don't understand how the non-utf8 char was causing the board to freeze but I haven't been able to reproduce the freeze since making this change, not that it happened all the time without the change either.

**Comment by RetiredWizard** [comment]
@dhalbert I tried moving the read loop down well below the board_init call hoping it would resolve #8890 but no matter where I tried the S3 I was testing on continued to come up with the stray byte. If you have any thoughts as to where the S3 needs the buffer cleared, let me know and I'll give it a try.

With the loop where I have it now seems to resolve the issue on the Sunton board.

**Comment by RetiredWizard** [comment]
Closing because tested solutions don't feel generally useful as they address a specific boards hardware quirk.

**Pull request closed without merging**
