### PR TITLE
Switch Sparkfun SAMD51 MicroMod to internal flash

### PR DESCRIPTION
**Pull request by stonehippo**
The Sparkfun SAMD51 MicroMod module ships with a 16MB external flash
chip, but the v1.2 version of the board has a design flaw which
prevents the SPI to the chip from working (PA10 cannot be MOSI).

The switches to the SAMD51's smaller internal flash, and reduces the
CircuitPython build to the minimum, similar to other boards that lack
external flash.

The current 7.0.0 .UF2 for this board has working safe-mode access to the REPL, but CIRCUITPY does not mount (since the SPI to the flash chip is broken). A test with these changes fixes that.

### CODE REVIEW

**Comment by dhalbert** [comment]
I notice this board is out of stock; you do know if they are fixing it? I would think so. Perhaps we should wait, since they may want to replace boards with the flaw, and I don't think we should necessarily support a broken board indefinitely.

**Comment by stonehippo** [comment]
@dhalbert I’ve asked, but it’s not clear if they’re going to fix the board. As you note, it’s out of stock and there’s no info on re-stocking plans, so my guess is that they’re aware and planning to fix it. Or it could be that the chip shortage is delaying any new spins.

The patch does allow the board to work, which can’t be said of the currently available version. If you don’t want to pull this in yet, then perhaps it makes to take the board off circuitpython.org until the hardware is fixed or it’s clear it’s not going to get an update.

**Comment by stonehippo** [comment]
Seems like they’re planning on fixing it.

https://github.com/sparkfun/MicroMod_Processor_Board-SAMD51/issues/2

**Comment by dhalbert** [comment]
> But anyone who has the current rev will be out of luck.

They said you'll be able to ask for a replacement. In the future, I think it makes sense to have only one board (the fixed one), since anyone with one can get it replaced. I'm not sure we should support defective products that are fixed.

**Comment by stonehippo** [comment]
@dhalbert sounds good. Does it make sense to pull the current download, too? I don’t know that it’s getting a lot of use, since it’s kinda broken.

**Comment by dhalbert** [comment]
Rather than removing it, since there will be a working replacement, perhaps we should add a note in circuitpython.org that the v1.2 version has a hardware flaw, but that a fixed version is expected. When v1.3 or v2.0 or whatever arrives, we can update that, and say that earlier versions are not supported due to a hardware flaw.

**Comment by stonehippo** [comment]
@dhalbert that makes sense to me. In the meantime, we can let this PR hang out, in case things resolve differently?

**Comment by dhalbert** [comment]
Sure, let's make it a draft, to hold it in suspense for now.

**Comment by dhalbert** [comment]
Closing in favor of a new pull request that will resolve #5590, when we know exactly what the new pin mapping is and can verify it.

**Pull request closed without merging**
