### PR TITLE
Xplain SAM21D Firmware update

### PR DESCRIPTION
**Pull request by robomike**
This version DOES NOT have External SPI Flash working for the Xplain Pro SAMD21 board.  There is an error when making the file system.

### CODE REVIEW

**Comment by tannewt** [comment]
Hi hi, could you up this now that its working? Thanks!

**Comment by robomike** [comment]
This version should have all merge issues resolved, fixed Xplain board, added capacitance to touchio, updated PINS.c for metro to avoid conflict with SPI flash.

**Comment by tannewt** [comment]
Hi Mike,
The review process for me will be much easier if each of these changes are separated. For example, one pull for the Xplained board, one for capacitance and one for metro pins.

To do that I suggest adding the adafruit repo as a remote (`git add adafruit git@github.com:adafruit/circuitpython.git`), `git fetch adafruit` and `git reset adafruit/master`. This should leave all of your changes but now show them as changes from adafruit master. Then, you can `git add` files for one PR to be committed and then commit them. Do this until all your files are committed again. Use `git log` to list the three commit ids and then `cherry-pick` each one into a separate branch. Then you should be able to create a small PR for each.

You'll also pick up my change to Travis to remove the code size check. Its breaking because Travis' GCC was updated and changed the code size a little.

Thanks!
~Scott

**Comment by robomike** [comment]
Hi Scott, do I need write access for that ? I've tried to commit to adafruit master before and got the error that I didn't have write access, that is why I had to fork , update, and pr... please advise , Mike

**Comment by tannewt** [comment]
You shouldn't need it. The intention is to just get the base commit
equivalent. Adding it as a remote is for reference.

**Comment by tannewt** [comment]
This is now in #137 so I'm going to close it.

**Pull request closed without merging**
