### PR TITLE
New ES locale strings

### PR DESCRIPTION
**Pull request by yeyeto2788**

### CODE REVIEW

**Comment by yeyeto2788** [comment]
@C47D, @sabas1080 when you guys get a chance, can you please check the PR? I might add more things tomorrow (28/Mar/2019).

Regards.

**Comment by C47D** [comment]
Hi @yeyeto2788 you beat me to it, i was planning to take a look into the translation later today. 👍

**Comment by yeyeto2788** [comment]
Hello guys! 

@C47D, @sabas1080, @tannewt 

Found some errors on build:
image

image

They seems to be regarding other languages and flash size issue, can anyone help me out to get the build working?

Another quick question? Where is the build for the ESP8266 or the ESP32? I don't see it on the CI job

**Comment by deshipu** [comment]
> Another quick question? Where is the build for the ESP8266 or the ESP32? I don't see it on the CI job

There was never a build for the ESP32, and ESP8266 is officially no longer supported in 4.0 and has been removed.

**Comment by dhalbert** [comment]
@yeyeto2788 Hi - your build problems are probably  due to changes from upstream that haven't been incorporated in your PR (we fixed the "too big" errors).

Instead of merging from `master` in your fork, try keeping your `master` in sync with adafruit/circuitpython. Do a local branch for your changes. This will be easier. We have a Learn Guide explaining our GitHub workflow here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github.

**Comment by yeyeto2788** [comment]
@deshipu thanks for the info, anyway to get lastes available realease for ESP8266 and ESP32?

@dhalbert I;ll read it and fix it. Thanks.

**Comment by yeyeto2788** [comment]
Wujuuuu! Finally working. Sorry for the mess.

**Comment by dhalbert** [comment]
Re releases:
The latest working ESP8266 release is 3.1.2: https://github.com/adafruit/circuitpython/releases/tag/3.1.2
There has never been a CircuitPython ESP32 build. There _is_ a MicroPython ESP32 build.

**Comment by yeyeto2788** [comment]
My bad, I thought there was one for the ESP32 but also with the ESP8266 one is good for me. Sad that is not supported now from 4.0 on.

Keep it up and if there is anythig I can help with, just let me know.

Regards.

**Pull request merged**
