### PR TITLE
bump protomatter to 1.5.10

### PR DESCRIPTION
**Pull request by jepler**
"Howdy. A customer was having issues with a long RGB matrix chain on Matrix Portal S3. Made a microscopic change in Protomatter that seems to improve the situation in Arduino. Could you see that the next CircuitPython build gets the same change? (1.5.9 release)"

Furthermore (1.5.10):
> I was doing some work on the Arduino side of Protomatter today and found that this latest batch of P4 and P5 matrix panels are super persnickety about the clock signal. Today’s 1.5.10 release should fix this, and the change (just moving some NOPs) ought to work in CircuitPython as well.
>
> I think what might’ve happened is occasionally there’s a PR that fixes one person’s flicker issue, unaware that this may lay waste to other situations. So earlier CircuitPython could sometimes behave better than later releases. Testing today on logic analyzer and six different panels, aiming for 50% duty cycle w/20 MHz CLK seems to produce the most reliable output across different hardware, and the code is now configured for such. Added a note to that repo’s README asking folks to open an issue rather than a PR if they have a problem and a “fix” for flicker, as it really needs monitoring and testing across a bunch of parts before merging.

### CODE REVIEW

**Comment by jepler** [comment]
@PaintYourDragon fyi

**Comment by dhalbert** [comment]
User with the issue is here: https://forums.adafruit.com/viewtopic.php?t=203310.

We can point them to the artifact after it's built for them to test, and I could make an 8.2.2 soon.

**Comment by PaintYourDragon** [comment]
Thank y’all! If this only partly remedies their problem, think it’s just a matter of further increasing this constant then.

**Comment by dhalbert** [comment]
User [reports](https://forums.adafruit.com/viewtopic.php?p=980734#p980734):
>  With that image + original hardware config (four 64 x 32 RGB Matrixes) + original sketch... No artifacts from the S3 observed when "bit_depth=3". Problems still there when "bit_depth=4"

@PaintYourDragon Would it make sense / is it possible to make that timing parameter `bit_depth` dependent, or maybe it should be a user-supplied parameter?

xref to https://github.com/adafruit/Adafruit_Protomatter/commit/5f0b40ed5991e22da63add5dbaeb7c194b72b607

**Comment by jepler** [comment]
This now updates to 1.5.10, and may fix #7912.

**Comment by dhalbert** [comment]
@PaintYourDragon posted https://forums.adafruit.com/viewtopic.php?p=981739#p981739 this evening. @PaintYourDragon should we wait on this?

**Review by dhalbert — APPROVED** [review]

**Comment by dhalbert** [comment]
I discussed this with @PaintYourDragon, and the problems mentioned in the forum post were not reproducible, so let's merge this.

**Comment by phantomsixthplayer** [comment]
Thought this might fix https://github.com/adafruit/circuitpython/issues/7682 but got this issue when installing CircuitPython 8.2.3 https://github.com/adafruit/circuitpython/issues/8303

**Pull request merged**
