### PR TITLE
Fix autoreload on SAMD21

### LINKED ISSUE #3528: Auto-reload works only occasionally on file save
Host PC: Macbook Pro running macOS 10.15.7 
Board: QT Py, with no peripherals  (also happens on Trinket M0)
CircuitPython version: 6-beta2

I've been noticing in CircuitPython 6 that the auto-reload doesn't seem to work much after saving a file.  For instance, in the CP program below (which plays random colors on the built-in Neopixel and prints out the current `time.monotonic()` and a string), I can edit the "hello" string, save the file, and auto-reload does not happen.

```py
import board
import time
import neopixel
from random import randint
pixel = neopixel.NeoPixel(board.NEOPIXEL, 1, brightness=0.2)
while True:
    print(time.monotonic(), "hello")
    pixel.fill( (randint(0,255), randint(0,255), randint(0,255) ))
    time.sleep(0.2)
```
Here's a screencast showing what I'm seeing.  
circuitpython6beta-noreload

(also at https://imgur.com/gallery/zAHgrNg)

In the screencast, there are two terminals: the bottom one shows the output of CP's USB Serial, in the top one I use `vim` to edit `code.py`, save it, and quit the editor.  In the serial terminal, nothing changes, until I Ctrl-C and Ctrl-D to stop & restart execution.

### PR DESCRIPTION
**Pull request by tannewt**
The issue was that a time.sleep() would set the RTC wake up
further into the future even if we wanted to tick every ms. Ticking
every ms is used to time the autoreload delay and without it,
autoreload doesn't work.

Fixes #3528

### CODE REVIEW

**Comment by tannewt** [comment]
@todbot, this should fix the autoreload issue.

**Review by gamblor21 — APPROVED** [review]
Built and tested on a Feather M0 Basic that I had tested the issue on previously. These changes fix the problem.

**Review by jepler — APPROVED** [review]
I didn't see anything to be concerned abut in the re-organization of _port_interrupt_after_ticks, and at a high level the explanation of the problem makes sense.  No testing performed.

**Comment by tannewt** [comment]
> I'm curious: what's the device-based testing regime like? Is that documented somewhere? I'd like to get into testing stuff like this and would like to leverage any existing work.

I think you are assuming we're more rigorous than we are. I just replicated the problem and then fixed it. I didn't test on other devices. I rely on folks trying their own `main` builds and the latest from S3 as a way to find other issues.

You can test PR changes by either pulling the PR down and building locally or waiting for the CI to complete. Once the CI is complete, you can access the built versions by:
1) Open the build results page by clicking any of the "Details" links. Example: https://github.com/adafruit/circuitpython/pull/3532/checks?check_run_id=1233432700
2) Click "Artifacts" in the top right and select the board of interest. It will download a zip of all the different language builds for a board. **This button only appears after the entire build is complete.**

> And thanks for such a quick turnaround on this!

No problem! It's core to the CircuitPython experience so it's good to get fixed.

**Comment by tannewt** [comment]
Yup! It's nice but a little slow. :-)

**Pull request merged**
