### PR TITLE
Some flash size optimizations related to string0.c (implementation of str/mem functions)

### PR DESCRIPTION
**Pull request by jepler**
This saves 124 bytes on trinket m0, though at some performance cost (I didn't measure). On "full build"s it saves 24 bytes, the rest is only saved on small builds.

Taking just the extra memset() removal part of the patch saves 24 bytes of flash, removing the int-at-a-time optimization from string0 saves 100.

It's lightly tested on a pygamer with the de-optimization manually enabled (it wouldn't be enabled on a pygamer by default).

### CODE REVIEW

**Comment by DavePutz** [comment]
I tested this on a CircuitPlayground express. The memset build took an extra 5812 bytes, but performance tested about the same between the two builds.

**Comment by jepler** [comment]
It's very surprising that this branch would take an extra 5812 bytes of flash storage. In case you looked at the size of this PR vs the size of main, I've updated the PR with the latest changes on main as of today.

**Comment by DavePutz** [comment]
@jepler , I was surprised as well. My numbers for a Trinket M0 build matched the ones you saw. I'll continue to investigate.

**Comment by DavePutz** [comment]
Re-tested CircuitPlayground Express with the latest changes. Size now looks much better, the increase was 148 bytes and performance was on a par with main. I built some boards with CIRCUITPY_FULL_BUILD = 0 (itsybitsy_m0, metro_m0_express, and qtpy_m0) and all saw reduced code sizes. The difference with CircuitPlayground Express looks to be due to it being a full build.  An itsybitsy_nrf52840_express build (which is also a full build) was 208 bytes larger.

**Comment by jepler** [comment]
hmm that's still odd.  If storage in flash isn't being freed up with this PR it doesn't make sense to take the change.

**Comment by dhalbert** [comment]
I tested the build sizes on a version of this merged with the latest `main`, on Trinket M0, CPX, Metro M0, and Metro M4. The savings are essentially as the same as reported in the OP, so I think this is safe to merge.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
