### PR TITLE
rp2: Add StateMachine(may_exec=, offset=)

### PR DESCRIPTION
**Pull request by jepler**
and also sanity-check the init instructions, thanks to the newly factored-out checker.

Closes: #8221

Not yet tested on hardware!

### CODE REVIEW

**Comment by jepler** [comment]
and it also adds offset= which is needed for encoder implementations like https://github.com/adamgreen/QuadratureDecoder/blob/master/QuadratureDecoder.pio

**Comment by jepler** [comment]
a discord user reports this doesn't work right, so I'll need to revisit it and do more testing

**Comment by jepler** [comment]
I tested this today with a QT Py RP2040 & jog wheel encoder.

Tests `may_exec=`: https://gist.github.com/jepler/597b80caa61a4a71f094959c1df66001 (note that I think this PIO code may have a bug that occasionally allows the incorrect value `~x` (bitwise not of the actual value) to be read; this is a bug in the PIO code and not in CP; I think this can be fixed by using 'y' as the temporary register)

Tests `offset=0`: https://gist.github.com/jepler/891a3c48e2f9f9fb9759bdb5ce081265 (revised by me so that values are continuously added to the FIFO, not only on change. otherwise, if the FIFO is allowed to fill, the latest value might not be read out because it was pushed while the FIFO was full)

**Comment by jepler** [comment]
@Ultrawipf please re-test if you have the time & interest!

**Comment by jepler** [comment]
updated yet again and using https://gist.github.com/jepler/0f162eb04c2b4e36e9ae9d6a228e4112 as test of `offset=`.

I also manually tested that offset conflicts are detected, though the error message says "All state machines in use" when the real problem is that the requested load address was not available.

This interactive session shows how the "same" program can be loaded multiple times at offset 0, then a 2nd program can be loaded at offset 0 of the second SM. A third program can't be loaded at offset 0 (it'd have to go in the third SM) but it can be loaded at another offset.

```
>>> p = adafruit_pioasm.assemble("jmp 0")
>>> sm1 = StateMachine(p, offset=0, frequency=1_000_000)
>>> sm2 = StateMachine(p, offset=0, frequency=1_000_000)
>>> sm3 = StateMachine(p, offset=0, frequency=1_000_000)
>>> p = adafruit_pioasm.assemble("nop")
>>> sm4 = StateMachine(p, offset=0, frequency=1_000_000)
>>> sm5 = StateMachine(p, offset=0, frequency=1_000_000)
>>> sm5 = StateMachine(p, offset=0, frequency=1_000_000)
>>> p = adafruit_pioasm.assemble("jmp x--, 0")
>>> sm6 = StateMachine(p, offset=0, frequency=1_000_000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: All state machines in use
>>> sm6 = StateMachine(p, frequency=1_000_000)
```

**Review by tannewt — CHANGES_REQUESTED** [review]
Thanks for the refactor. Very cool to see these advanced uses of PIO.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks for the updates!

**Pull request merged**
