### PR TITLE
String internationalization for Bahasa Indonesia

### PR DESCRIPTION
**Pull request by chalei**
Start to translate circuitpython to Bahasa Indonesia #1098 
 
In Progress, reaching line 236 so far

### CODE REVIEW

**Comment by tannewt** [comment]
Hi! Thank you for this! I'm excited to see another translation. We should merge this before you translate all the strings. I'll merge it once Travis passes. The current error is listed here: https://travis-ci.org/adafruit/circuitpython/jobs/462636827#L1079 Let me know if you need help getting it going. Thanks!

**Comment by dhalbert** [comment]
@chalei Hi, there are conflicts which are preventing a merge. Are you able to merge from `adafruit/circuitpython` again to bring this PR up to date? Then run `make translate` and double-check your file, and we should be able to merge this. Thanks!

**Comment by chalei** [comment]
Thanks @dhalbert  for updating, I am gonna try to merge this and continue the translation later this week

**Comment by chalei** [comment]
@tannewt I have successfully remove the error and updated the translation

> Hi! Thank you for this! I'm excited to see another translation. We should merge this before you translate all the strings. I'll merge it once Travis passes. The current error is listed here: https://travis-ci.org/adafruit/circuitpython/jobs/462636827#L1079 Let me know if you need help getting it going. Thanks!

**Pull request closed without merging**
