### PR TITLE
Create tests/_manual, add Socket tests

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds a new manual tests folder for scripts that are primarily useful for testing core modules (ie, that do not use libraries and focus on raw API access to a single module). It also adds three tests: Host, Client, and NTP access tests for the Socket module. Future additions to this testing folder should be sorted by module name, matching shared-bindings and common-hal.

### CODE REVIEW

**Comment by tannewt** [comment]
Why is there an underscore in the name?

**Comment by hierophect** [comment]
> Why is there an underscore in the name?

I thought it might be appropriate to distinguish them from the Micropython battery of tests that are run automatically by `run-tests`. The rest of the tests in that folder are very uniform in style and purpose, and these are different enough that I thought it'd be worth prefixing them.

**Comment by tannewt** [comment]
> > Why is there an underscore in the name?
> 
> I thought it might be appropriate to distinguish them from the Micropython battery of tests that are run automatically by `run-tests`. The rest of the tests in that folder are very uniform in style and purpose, and these are different enough that I thought it'd be worth prefixing them.

If anything we could do `circuitpy-manual` to mimic what we do in `py`.

Note, I added `manual` with my audiopwm changes that were merged in already.

**Comment by hierophect** [comment]
> If anything we could do `circuitpy-manual` to mimic what we do in `py`.

That sounds good to me, since there's already a convention there. I'll change this PR to merge the two under that name.

**Comment by tannewt** [comment]
> > If anything we could do `circuitpy-manual` to mimic what we do in `py`.
> 
> That sounds good to me, since there's already a convention there. I'll change this PR to merge the two under that name.

Ok, thanks!

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
