### PR TITLE
Bump circuitpython-stage to 1.1.1

### PR DESCRIPTION
**Pull request by deshipu**
This adds handling of GameOver exception as SystemExit in anticipation
of the new way of starting games from the menu.

### CODE REVIEW

**Review by cwalther — DISMISSED** [review]

**Review by cwalther — APPROVED** [review]
Smoke-tested on PewPew Standalone 10.2, `GameOver` in Othello working fine. (Although the display is very flickery and it runs more slowly than with CP 4.1.0, but that is obviously unrelated.)

**Comment by deshipu** [comment]
Ugh, I think the changes around system tick and sleep modes have broken it. I didn't have time to test it, but I've heard reports that gamepad, which also relies on system tick, is unreliable on SAMD21.

**Comment by deshipu** [comment]
@cwalther I reported https://github.com/adafruit/circuitpython/issues/3504, hopefully I will be able to look into it this weekend.

**Review by tannewt — APPROVED** [review]
Thanks! I made the issue blocking the next stable release.

**Pull request merged**
