### PR TITLE
Update EPaperDisplay to allow for two byte sequence length

### PR DESCRIPTION
**Pull request by dkulinski**
This update allows EPaperDisplay drivers with LUT tables larger than 128 bytes to be used. Specifically this fix is for the SSD1680 driver and the 153 byte LUT table on the Waveshare 2.9 inch V2 display. This fixes https://github.com/adafruit/circuitpython/issues/5850

### CODE REVIEW

**Comment by dhalbert** [comment]
Could this just be done dynamically by noticing whether the supplied LUT is >128 bytes?

**Comment by dkulinski** [comment]
I don't believe so (and please correct me if I'm wrong here) because the delay mask is in the 8th bit place and it is masked out from the size and this is what originally caused the issue. Because the LUT is just a byte string in the start_sequence there is no size supplied.

**Comment by tannewt** [comment]
I suggested this. I don't think there is a way to automatically detect it.

@dkulinski There are a couple boards that init eink in `board_init` that will need their constructors updated for your addition.

**Comment by dhalbert** [comment]
> I suggested this. I don't think there is a way to automatically detect it.

If the init sequence were broken into components, including the LUT, then it could be noticed, but I am not sure it is worth it, especially if the init sequence could be irregular in some way.

**Comment by dhalbert** [comment]
`adafruit_magtag_2.9_grayscale` and `openbook_m4` are failing for code reasons.

`stringcar_m0_express` is failing for space reasons. I suggest adding this to its `mpconfigboard.mk`:
```
CIRCUITPY_USB_MIDI = 0
```
since it has no need for MIDI. There are a bunch of other things that could be removed too, but that's probably enough.

**Comment by dhalbert** [comment]
> `stringcar_m0_express` is failing for space reasons. I suggest adding this to its `mpconfigboard.mk`:
> 
> ```
> CIRCUITPY_USB_MIDI = 0
> ```
> 
> since it has no need for MIDI. There are a bunch of other things that could be removed too, but that's probably enough.

It turns out I have to fix this for #5896 anyway, for the same reasons, so don't bother to do this yourself.

**Comment by dkulinski** [comment]
Ok, I have fixed the two boards that failed and have committed my changes.

**Review by tannewt — APPROVED** [review]
Looks good! Thank you for the update. I agree that the ESP builds being broken isn't your fault. Will merge anyway and we'll fix ESP separately.

**Pull request merged**
