### PR TITLE
espressif: always make new client sockets be non-blocking

### LINKED ISSUE #7431: Incorrect behaviour of timeout on socket / socket & serial port blocked - CP 8.0.0 beta6
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32-S3
Also tested and replicated on ESP32-S2 board
```

### Code/REPL

```python
from adafruit_httpserver.mime_type import MIMEType
from adafruit_httpserver.request import HTTPRequest
from adafruit_httpserver.response import HTTPResponse
from adafruit_httpserver.server import HTTPServer

pool = socketpool.SocketPool(wifi.radio)
server = HTTPServer(pool)
server.request_buffer_size = 2048
server.socket_timeout = 1
server.start(str(wifi.radio.ipv4_address))

@server.route("/")
def base(request: HTTPRequest):
    with HTTPResponse(request, content_type=MIMEType.TYPE_TXT, chunked=False) as response:
        try:
            print("REQUEST: /")
            response.send("HELLO")
        except OSError:
            response.send("ERROR")

while True:
    try:
        led.value = True
        time.sleep(0.05)
        led.value = False
        time.sleep(0.1)
        server.poll()
        
    except OSError as error:
        print(error)
        continue
```

### Behavior

If you use the code attached on cp 8.0.0 and make a request to the server from Chrome (which makes the request you ask for and then immediately a second request to keep a port open), the loop will stop for 60 seconds until Chrome closes the open socket. I would expect setting `server.socket_timeout` to 1 to abort the connection but it just stays blocked, seemingly at `sock.recv_into()` in the server.py include of the HTTP Server project.

### Description

This issue was found whilst investigating a problem with Chrome accessing the Adafruit HTTP Server together with @michalpokusa, original issue is here:

[https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/issues/31]( #https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/issues/31)

If a socket is opened and nothing is sent down it (as Chrome will do after every request), the socket will stay open and block, the `server.socket_timeout` setting does not seem to have any effect.

@michalpokusa also observed that while the code is stuck on `sock.recv_into()` the serial port is also blocked.

### Additional information

- This problem does not appear on CircuitPython 7.3.3, only on 8.0.0
- Problem exists on both ESP32-S2 and ESP32-S3
- On CP 7.3.3 after processing request program loops .pool(), on CP 8.0.0 most of the time it gets stuck on sock.recv_into()
- Serial connection seems to be blocked when stuck on sock.recv_into()
- The problem could be related to connections which are opened and no data sent down them

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #7431.

- The new client socket returned by `accept()` was not set to `O_NON_BLOCK` all the time, causing it to block until a request was made. Now ensure that it is always set to non-blocking.

Other fixes:

- `write()`s to `eventfd`s should always be 8 bytes. There was a write that was only 4 bytes (writing the `fd`). This should actually return an error, but it wasn't checked. @tannewt I don't see that the results of these writes are used anywhere, so I think this change is OK, but you can take a look. Internally they are added to a counter associated with the `eventfd`.
- Added a check for ctrl-C interrupts in loop where it was not present.

I tested this on a Metro ESP32-S2, and saw that requests from Chrome were not hanging. It is also now possible to ctrl-C the `HTTPServer`. Before this fix, it was blocking internally on an `lwip_recv()`, and could not be interrupted.

Also tested the web workflow, which seems to work the same as before. Using `HTTPServer` on port 80 can cause issues with the web workflow, as might be expected, but these issues are not worse with this fix.

@yousafs and @michalpokusa and anyone else: testing appreciated.

I think this makes https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/pull/32 not be needed.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Makes sense, didn't test

**Comment by michalpokusa** [comment]
I can confirm that in my testing on ESP32-S2 TFT Feather, these changes seem to fix the blocking behaviour in Chrome. Thanks @dhalbert!

The adafruit/Adafruit_CircuitPython_HTTPServer#32 was an experimental way to fix the issue before fix in CircuitPython itself. Right now it is indeed not needed anymore.

**Comment by dhalbert** [comment]
@Sinai The choice of non-blocking here is internal; we do timeouts outselves.

**Comment by Sinai** [comment]
@dhalbert  Thank you for your answer.
Yes i know.  but it doesnt work and server.poll() hangs forever....

I think when you setup a Server using Wifi is different than using eth.
I have to built my own socket class. and set a timeout on that..

**Pull request merged**
