### PR TITLE
Turn on MICROPY_OPT_COMPUTED_GOTO for 5x CPU-bound speedup

### PR DESCRIPTION
**Pull request by dhalbert**
Turning this on gives about a 5x speedup (!) for CPU-bound code.

I expect the first submission of this PR to fail because it won't fit on some boards. I'll adjust with further commits.

### CODE REVIEW

**Comment by shazz** [comment]
Tested, works on the pygamer.

**Comment by tannewt** [comment]
I did some size improvements here: https://github.com/tannewt/circuitpython/commit/5399f02395d8d24d2c5bbf62157dbfec8b01e3be

**Comment by dhalbert** [comment]
That jogged my memory: I saw breakage a long time ago when I set the inline limit relly low: #322. I tested it briefly with 23 but it was really just a smoke test

**Comment by dhalbert** [comment]
USB_MIDI is turned on for all builds. We could turn it off for small builds. Saves 728 bytes.

I looked at the pinyin translation in hopes of trimming it a bit. It's not that verbose in terms of character count: it's the double-byte characters that really push it up.

**Comment by dhalbert** [comment]
Using regular `-Os` instead of `-O3` (`SUPEROPT`) for `gc.c` saves 2144 bytes.

Using regular `-Os` instead of `-O3` (`SUPEROPT`) for `vm.c` only saves 524 bytes.

My inclination is to slow down gc for `CIRCUITPY_SMALL_BUILD` and/or for the overflowing builds, as you suggested. Then we can dial way back towards normal on `CFLAGS_INLINE_LIMIT`. I'll work on setting up compilation flags for this.

**Pull request merged**
