### PR TITLE
Latest arch uncrustify

### PR DESCRIPTION
**Pull request by bill88t**
Docs specify no uncrustify version.
Arch:latest provides version `Uncrustify_d-0.75.1_f` which produces the following during `pre-commit run --all`

### CODE REVIEW

**Review by microdev1 — CHANGES_REQUESTED** [review]
We are limited by the uncrustify version in [MicroPython](https://github.com/micropython/micropython/blob/master/CODECONVENTIONS.md#uncrustify). Changing ours will complicate a merge from upstream.
The [docs](https://github.com/adafruit/circuitpython/blob/main/BUILDING.md#code-quality-checks) mention this version limitation.

**Comment by bill88t** [comment]
Thanks and sorry for missing that.

**Comment by tannewt** [comment]
@bill88t I have a version of uncrustify 0.72 if you need it. I think we're also limited by what Ubuntu packages because that's what the CI uses.

**Comment by bill88t** [comment]
Aur has a nice package named `downgrade`, it got me to 0.71 in the blink of an eye. Thanks for the offer though.

**Comment by tannewt** [comment]
Thanks for the tip!

**Pull request closed without merging**
