### PR TITLE
Draft I2C FeatherRP2040 Peripheral

### PR DESCRIPTION
**Pull request by jposada202020**
@tannewt As discussed enclosed Draft for I2CPeripherals Feather RP2040.

To take into considerations:
1. I build the firmware, but I had to change a reference that I could not figure out, it is market with a TODO. Help is needed here.
2. Overwritten the Original i2cperipheral in shared-bindings, as I needed to build to verify errors
3. In a strange turn of events, the function `i2c_write_raw_blocking' paragraph 4.1.10.3.13 is not available in the SDK library in our REPO, so any writing to the slave via the FIFO would not work. I commented out this function.
4. There are some interesting comments in this post, not sure if we will need to take another approach: https://www.raspberrypi.org/forums/viewtopic.php?p=1823225

Be aware that is my first time working in the core. Anyway, if anything.. this is helping me loosing my fear to the core :)

For me, it would be easier implement the slave in the I2C function, as the definition for a salve is a easy as:
```void i2c_set_slave_mode (i2c_inst_t *i2c, bool slave, uint8_t addr)```
where:
```
slave: true
addr: slave addr by deafult 0x055
```

and we could define the writing and reading inside the present implementation.

### Device Testing:
I can see the module in the Pico

need to verify when Feather RP2040 arrives this week.

### CODE REVIEW

**Comment by microDev1** [comment]
Thanks! for the PR @jposada202020. I am converting this to draft for now.

**Comment by tannewt** [comment]
> @tannewt As discussed enclosed Draft for I2CPeripherals Feather RP2040.

Thanks for the PR! It is much easier to reply to and see the changes.

>     1. I build the firmware, but I had to change a reference that I could not figure out, it is market with a TODO. Help is needed here.

I glanced over the code but didn't see a TODO. Please ask me about it here.

>     2. Overwritten the Original i2cperipheral in shared-bindings, as I needed to build to verify errors

You shouldn't need to change shared-bindings at all. Usually you can provide empty functions in common_hal to make the compiler happy. What error were you getting?

>     3. In a strange turn of events, the function `i2c_write_raw_blocking' paragraph 4.1.10.3.13 is not available in the SDK library in our REPO, so any writing to the slave via the FIFO would not work. I commented out this function.

I suspect this may be because we need a new version of pico-sdk. 1.1.0 was just released, so it'd be good to update to that.

>     4. There are some interesting comments in this post, not sure if we will need to take another approach: https://www.raspberrypi.org/forums/viewtopic.php?p=1823225

I think we should keep the same API that already exists. That way code will move over easily.

> Be aware that is my first time working in the core. Anyway, if anything.. this is helping me loosing my fear to the core :)

Good job! I'm happy to see you digging in. :-)

**Comment by jposada202020** [comment]
@tannewt Thank you for reviewing this, and sorry for the delay reply.
2. You are right, I guess I never pushed the file changes including the TODO.  the problem is in this line.
https://github.com/adafruit/circuitpython/blob/ed7cb6de7c0e31356739f2e824aeee2ba1769731/shared-bindings/i2cperipheral/I2CPeripheral.c#L63
The raised error is that this `i2cperipheral_i2c_peripheral_type` is unknown. I tried to change to the object but it did not work. To be honest I do not what to use here,
4. Agree we should keep the same API, my main goal was to build and flash into the board, to understand how all the workflow works. But yes, the API needs to be the same, I will work on that.

Thank you for reviewing and the comments. I want to see the developments in the new SDK, and I want to understand more the process.

**Comment by tannewt** [comment]
I think you do want the type. It should be externed in the header and defined at the bottom of the c file. https://github.com/adafruit/circuitpython/blob/main/shared-bindings/i2cperipheral/I2CPeripheral.c#L222

I'd recommend get the shared-bindings back to the checked in state and then adding c functions into the common-hal side.

**Comment by jposada202020** [comment]
@tannewt yes, I would probably redo a lot of things, now that I understand better all things, and finally.... realizing the meaning of the word "shared-bindings".  I will work on this during the weekend. Thanks For the time that you are taking with this, I am putting time myself too!

**Comment by jposada202020** [comment]
Closing for now, not seeing me returning to this anytime soon. possible would reopen when other developments in the bundles are done.

**Pull request closed without merging**
