### PR TITLE
Partially revert "rgbmatrix: Avoid leaving an incompletely configured display bus"

### PR DESCRIPTION
**Pull request by jepler**
Reverts adafruit/circuitpython#9865

According to @retiredwizard this led to the problems reported in #9891.

Since the fix was only for failed matrix initialization, it seems we're better off just reverting it until it can be solved again properly.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Looks like your #9892 changes to `ports/atmel-samd/boards/itsybitsy_m4_express/mpconfigboard.mk` are still needed for space reasons.

**Comment by RetiredWizard** [comment]
I loaded the matrix S3 artifact and it appears to have resolved the safe mode issue. Thanks!

**Comment by RetiredWizard** [comment]
Well... This artifact doesn't have Dan's USB fix so maybe that's contributing to this latest behavior, but using this artifact, when I don't have the USB cable connected the matrix doesn't initialize, and if I disconnect the USB cable while the RGB matrix is active the board appears to crash (it's hard to tell exactly what's happening since the USB port isn't working for terminal or CIRCUITPY use without Dan's fix).

I've recently replaced my computer and perhaps this is an excuse to test a CircuitPy build. I think I need to build firmware with both Dan's fix and this reversion.....

**Comment by jepler** [comment]
I updated the branch to leave the itsy config changes & merge latest main.

**Review by dhalbert — APPROVED** [review]
@RetiredWizard thanks for testing. I'll merge if/when the builds finish successfully.

**Pull request merged**
