### PR TITLE
RGBMatrix: Detect invalid bit_depth selection

### LINKED ISSUE #3650: rgbmatrix.RGBMatrix with bit_depth=0 puts board in to bad state
With the below code on the CIRCUITPY drive, you can put the board in to a bad state where the disk won't mount and the tty device doesn't show up, even with the board unplugged from the matrix. Tested with adafruit-circuitpython-matrixportal_m4-en_US-6.0.0-rc.1.uf2

```python
import board
import displayio
import framebufferio
import rgbmatrix

displayio.release_displays()

matrix = rgbmatrix.RGBMatrix(
    width=64, bit_depth=0,
    rgb_pins=[
        board.MTX_R1,
        board.MTX_G1,
        board.MTX_B1,
        board.MTX_R2,
        board.MTX_G2,
        board.MTX_B2
    ],
    addr_pins=[
        board.MTX_ADDRA,
        board.MTX_ADDRB,
        board.MTX_ADDRC,
        board.MTX_ADDRD
    ],
    clock_pin=board.MTX_CLK,
    latch_pin=board.MTX_LAT,
    output_enable_pin=board.MTX_OE
)
display = framebufferio.FramebufferDisplay(matrix, auto_refresh=True)
```

### PR DESCRIPTION
**Pull request by jepler**
Closes #3650

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I tested this with the code from the issue and confirmed it does now throw this error `ValueError: Bit depth must be from 1 to 6 inclusive, not 0` and does not lead to any bad state. CIRCUITPY, and the REPL remain accessible.

**Review by dhalbert — DISMISSED** [review]
Thanks for arg validation!

**Comment by dhalbert** [comment]
Needs `make translate`

**Comment by jepler** [comment]
I also retargeted this at 6.0.x, we'll want to merge up into main at some point

**Comment by dhalbert** [comment]
I think we could omit this from 6.0.0 if rc.1 is going to be promoted to final, so I'm not going to merge this yet (and it needs `make translate` again on 6.0.x, due to the different branch).

**Comment by tannewt** [comment]
I'd be ok including this in 6.0.0 without an RC. It's extremely low risk.

**Comment by dhalbert** [comment]
@jepler could you `make translate` and try another push? I can put this in 6.0.0.

**Review by dhalbert — APPROVED** [review]
Thanks! I pushed a "make translate" to finish this off.

**Pull request merged**
