### PR TITLE
Update `on_next_reset` for new safe mode.

### LINKED ISSUE #1831: Failer to boot into Safe Mode
```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.BOOTLOADER)
microcontroller.reset()
```
works as expected but
```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.SAFE_MODE)
microcontroller.reset()
```

Does not enter safe mode. I was going to use it like "else statement" boots to safe_mode stopping code.

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #1831

### CODE REVIEW

**Comment by tannewt** [comment]
Will have to pick this up tomorrow. Looks like it should work with the button for CircuitPlayground single click into bootloader: https://github.com/adafruit/circuitpython/issues/350#issuecomment-349150782

**Comment by dhalbert** [comment]
Neither the `BOOTLOADER` nor `SAFE_MODE` worked when pressing the reset button once. Maybe the value is getting overwritten by the bootloader, since now it's a regular static: `static mcu_runmode_t next_reset;` instead of using `_ezero` ?

**Comment by tannewt** [comment]
@dhalbert I didn't expect it to work but I do now. :-) I swapped it back to setting values in `on_next_reset`.

**Comment by dhalbert** [comment]
Tested this further on Feather nRF52840 and it doesn't change the mode when reset either by hand or programmatically.

**Comment by dhalbert** [comment]
Ah, OK, I see issue #1868 for nrf support.

**Pull request merged**
