### PR TITLE
Definitions for StringCar M0 Express and AT25SF161-SSHD-T 2MiB SPI flash chip

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
Board definitions for the CedarGrove StringCar M0 Express. Added a device definition for the AT25SF161 flash chip used on the StringCar board. Includes the assigned custom VID/PID codes. Built and tested okay.

I'll need some help with the next steps. Have reached my skill/experience limit.  ;)

### CODE REVIEW

**Comment by CedarGroveStudios** [comment]
Wasn't able to find the .travis.yml file to update with the new board name. Is there a different process than the one described in the guide?

**Comment by dhalbert** [comment]
We now use GitHub actions, which is in https://github.com/adafruit/circuitpython/blob/master/.github/workflows/build.yml. But I'm not sure you can put that in a PR, for security reasons. @tannewt, how do we do this now?

**Comment by tannewt** [comment]
New board list is here: https://github.com/adafruit/circuitpython/blob/master/.github/workflows/build.yml#L75 Will edit the guide now. Thanks!

**Comment by CedarGroveStudios** [comment]
Thanks! Just added the board to the list.

**Comment by tannewt** [comment]
Guide is updated now too.

**Pull request merged**
