### PR TITLE
Feather ESP32-S2: turn on I2C power after reset

### PR DESCRIPTION
**Pull request by dhalbert**
This is the pretty much the same as #5776, but is a PR against 7.1.x instead of main. I read the code and could not understand why it didn't work, and after trying it myself, I was unable to repoduce the `D7 in use` message.

@ladyada, could you test, in your own way? I was using this, with the `DigitalInOut` commented out and not.

```py
import time
import board
import digitalio
import adafruit_bme280.basic

# Test with and without this.
# power = digitalio.DigitalInOut(board.I2C_POWER_INVERTED)
# power.switch_to_output(False)

i2c = board.I2C()  # uses board.SCL and board.SDA
bme280 = adafruit_bme280.basic.Adafruit_BME280_I2C(i2c)

while True:
    print("\nTemperature: %0.1f C" % bme280.temperature)
    print("Humidity: %0.1f %%" % bme280.relative_humidity)
    print("Pressure: %0.1f hPa" % bme280.pressure)
    print("Altitude = %0.2f meters" % bme280.altitude)
    time.sleep(2)
```

### CODE REVIEW

**Comment by jepler** [comment]
I'm not sure about this change. Specifically, I think it may behave differently when merged to main, where we've taken
 * https://github.com/adafruit/circuitpython/pull/5674

and specifically fae6d47a458778797a10a6fdcc7d3f6b3be77d12 where we now ensure that a "never reset" pin continues is marked as "in use" after `reset_all_pins()`.

This was needed to resolve a problem where the state of a displayio backlight pin was lost over soft resets.

**Comment by dhalbert** [comment]
That must be why it didn't work when I tested with an artifact from #5674.

**Comment by dhalbert** [comment]
@ladyada and I talked about turning on the power-enable in `reset_board()` instead of `board_init()`. `reset_board()` gets called each time the VM shuts down. That would cause any setting of the pin not to be sticky from `boot.py` to `code.py`, but that could be OK.

But #5674 makes the backlight pin unavailable for setting manually. Is that OK?

**Comment by dhalbert** [comment]
> and specifically [fae6d47](https://github.com/adafruit/circuitpython/commit/fae6d47a458778797a10a6fdcc7d3f6b3be77d12) where we now ensure that a "never reset" pin continues is marked as "in use" after `reset_all_pins()`.

This is true only on `espressif`. As another example, something similar is done for CPB, so we might want to be consistent across ports.

I think `never_reset` is being overloaded with responsibilities. Maybe we need to separate "never reset" and "never allocate".

**Review by ladyada — APPROVED** [review]
that did it! works great

**Comment by ladyada** [comment]
can u cherrypick into 7.1?

**Comment by dhalbert** [comment]
> can u cherrypick into 7.1?

This is already against 7.1.x, so it will go into 7.1.0-rc.1. We'll merge it into main as well.

**Comment by ladyada** [comment]
ok rad thanks! this should help with customer confusions

**Pull request merged**
