### PR TITLE
added enable_dim_neopixel(), disable_dim_neopixel(), set_dim_level()

### PR DESCRIPTION
**Pull request by asherlie**
This adds 3 functions to the samd module for the user to control the behavior of the neopixel:
- enable_dim_neopixel()
- disable_dim_neopixel()
- set_dim_level()

enable_dim_neopixel and disable_dim_neopixel turn on and off dim neopixel mode. set_dim_level takes in an integer from 0-255 and sets the brightness level of dim neopixel mode. The default brightness level for dim neopixel mode is 40. set_dim_level(0) will turn off the neopixel.

### CODE REVIEW

**Comment by tannewt** [comment]
Looks like the test is failing because the code is too large for the Arduino Zero, Gemma M0 and Trinket M0. How about adding a single `set_rgb_status_brightness` to `rgb_led_status.c` and removing the enable/disable calls? 0 can disable and !=0 can enable implicitly.

**Comment by dhalbert** [comment]
The 2.0.0-rc2 builds have only 56 bytes free on non-Express boards. You can get back some more space by lowering `-finline-limit` in the [Makefile](https://github.com/adafruit/circuitpython/blob/master/atmel-samd/Makefile#L140). `-finline-limit=57` right now. Lower it only a few at a time (like 2-5), since it will cost a little performance somewhere.

**Comment by asherlie** [comment]
I'll check it out tonight. I think I'll go the `set_rgb_status_brightness` route and not mess with the `-finline-limit`.

**Comment by dhalbert** [comment]
I agree with @tannewt about the API, though with only 56 bytes left, you may still need to make room by fiddling with `-finline-limit`.

**Comment by asherlie** [comment]
Oops. I'll fix this soon. Defined some variables in the wrong place relative to `#ifdef`s.

**Pull request merged**
