### PR TITLE
Itsybitsy m0 fixes

### PR DESCRIPTION
**Pull request by ladyada**
Update SPI Flash code to allow differing flash 'types' (seems like some are 0x40 some are 0x60
Update SPI Flash def's with the matching macros
Add W25Q16 USON Flash type
Add working Itsy Bitsy M0 Express support

### CODE REVIEW

**Comment by dhalbert** [comment]
Right now there are merge conflicts due to Tony's RFM board changes. Can you fetch from upstream and then do a rebase? Tnx.

**Comment by ladyada** [comment]
wierd i did a fix here https://github.com/adafruit/circuitpython/pull/541/commits/70b9c7a49f85915dccb4d259b9bb67f5996a0cda as GH requested but it didnt work right. ill try again

**Comment by ladyada** [comment]
i said some magic git words and i think it worked ?

**Comment by dhalbert** [comment]
I see you did mpconfigboard.h in such a way that it will be easier to port to master. Tnx!

**Comment by ladyada** [comment]
uhh yeah, thats totally on purpose and not because i accidentally added support to master by accident and then had to backtrack!

**Pull request merged**
