### PR TITLE
Turn on title bar everywhere and enhance it

### PR DESCRIPTION
**Pull request by tannewt**
The title bar now has code execution status on all builds and BLE workflow info on those.

This PR also has a number of tweaks and fixes (hopefully not too distracting):
* It uses libgcc from my Arch install for SAMD21 builds (saving >750 bytes it seems.)
* Adds a `UID: ` line to boot_out.txt so to identify a device from a mounted filesystem.
* Fixes BLE workflow. (It was broken by the workflow reset refactoring with web workflow changes.)
* Uses the ble name set on the adapter for the BLE workflow advertisements.
* Removes supervisor.enable/disable_autoreload in favor of supervisor.runtime.autoreload.
* Tweaks terminal scroll area so the bottom line is complete and the top is clipped under the title bar.
* Tweaks Blinka logo sizing to match font size when possible (12px or 16px.)
* Drops `Wi-Fi:` prefix when showing an IP to increase the likelihood it is all displayed.

### CODE REVIEW

**Comment by tannewt** [comment]
Related issues: #6668, #6621, #6566, #6078, #4705, #5352, #5414, #2791

**Review by dhalbert — CHANGES_REQUESTED** [review]
Great! The code looks good. I noted the following things:

1. The `@n ExceptionName` in the status bar does not include the filename. So for instance:
`code.py`:
```py
import busio
import x
```
`x.py`:
```py
1/0
```
says `@1 DivisionByZeroError` without saying which file it's in. If you feel there is room, I think including the filename would be good, since the error may be quite deep. The filename and the line number are more important than a possibly truncated exception name.

2. I connected, then changed the wifi password to be wrong, did a hard reset. I see "Authentication Failure" after a 15-second or so delay. Then I changed the password back to be correct, and did another hard reset. On the device display (Feather ESP32S2 TFT), the IP address is shown, but the terminal title bar (running `tio`) said "No IP", and it did not show the `code.py output:`. This is a little bizarre because it should have come up properly and printed the usual initial text. Instead tio just said "Connected" and idid not print anything. This seems like some kind of timing problem.

It's OK to merge as is, and consider these later. I can open issues about them.

**Comment by tannewt** [comment]
> If you feel there is room, I think including the filename would be good, since the error may be quite deep. The filename and the line number are more important than a possibly truncated exception name.

Ya, I agree that'd be better. I'm not exactly sure how to get that info atm. The line number was convenient and I was hoping it was the top level, not bottom. (But I obviously didn't test it.)

I can test on the Feather S2 TFT when I get to this. I didn't try it specifically. Up to you if you want to merge now or not. Either way these changes will cause full CI runs.

**Comment by dhalbert** [comment]
I will open some issues and merge now.

**Review by dhalbert — APPROVED** [review]
Thanks! Merging now and will open issues for further work.

**Comment by dhalbert** [comment]
Oops, there is a merge conflict anyway. Could you check on that, and then I'll approve and merge?

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
