### PR TITLE
Fix ci_fetch_deps.py for website PR generation

### PR DESCRIPTION
**Pull request by dhalbert**
@tannewt Is this the fix for the problem I encountered with the circuitpython.org PR generation for 7.1.0-beta.1? I don't see a reason to run `ci_fetch_deps.py` in `create_website_pr.yml`.

### CODE REVIEW

**Comment by tannewt** [comment]
Looks like I replaced a submodule fetch that got tags: https://github.com/adafruit/circuitpython/blob/387a8a46b37e9e16461afe23aeaab498097ed7a5/.github/workflows/create_website_pr.yml#L34

I think it will need this.

**Comment by dhalbert** [comment]
>Looks like I replaced a submodule fetch that got tags:

Comparing with what it used to be:
https://github.com/adafruit/circuitpython/commit/a1052d5f73ff679c5040863fd606fed22736c9fd#diff-b754fd8b187edf5ee02a9009efe657b874a3c021d90f8fe97120800a2ad0deec

@tannewt I could just revert to the old thing. Or I could add `website` as a handled arg, which doesn't fetch any submodules (I think). I'm a bit confused because the `depth: 0` would not fetch tags?

**Comment by dhalbert** [comment]
@tannewt, ok, I think the latest commit will work, because it fetches tags from `circuitpython`, but ignores all submodules.

**Review by tannewt — APPROVED** [review]
That looks good to me too. Thanks!

**Pull request merged**
