### PR TITLE
Enable implicit fallthrough diagnostic, note intentional fallthroughs.

### PR DESCRIPTION
**Pull request by jepler**
This is cumulative with #3404 since that also fixed a case of an unintentional fallthrough.

It's considered a common mistake to forget 'break' between cases of a case statement.  Help the compiler help us find them in the first place.

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
The changes so far look fine, but why did you only enable it for `atmel-samd`, instead of enabling in in py/circuitpy_defns.mk in `BASE_CFLAGS`?

**Comment by jepler** [comment]
For better or for worse, we apply more stringent warning flags to the atmel-samd port than to other ports.  If you like, I can move it and we can find out how much more is caught with a wider net.

**Comment by dhalbert** [comment]
I think it's a good idea, since it could catch a number of port-specific bugs. The main issue I had with the nRF port and its hal layers is that it does `#if` on undefined preprocessor macros.

>For better or for worse, we apply more stringent warning flags to the atmel-samd port than to other ports.

I looked in `atmel-samd/Makefile` and didn't see a lot of this. What are you thinking of?

**Comment by jepler** [comment]
Sorry for not being more specific, rather I have a general feeling of hitting some "wait, why didn't the compiler tell me" problems when not in the atmel sam port

**Comment by jepler** [comment]
cxd56 and mimxrt10xx don't enable -Werror.

**Comment by jepler** [comment]
@dhalbert happy you're here, are these FALLTHROUGHs or missing break;s?
```
common-hal/_bleio/PacketBuffer.c: In function 'packet_buffer_on_ble_server_evt':
common-hal/_bleio/PacketBuffer.c:175:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
  175 |             if (self->conn_handle == ble_evt->evt.gap_evt.conn_handle) {
      |                ^
common-hal/_bleio/PacketBuffer.c:179:9: note: here
  179 |         case BLE_GATTS_EVT_HVN_TX_COMPLETE: {
      |         ^~~~
common-hal/_bleio/PacketBuffer.c:180:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
  180 |             queue_next_write(self);
      |             ^~~~~~~~~~~~~~~~~~~~~~
common-hal/_bleio/PacketBuffer.c:182:9: note: here
  182 |         default:
      |         ^~~~~~~
```

```
        }
        case BLE_GAP_EVT_DISCONNECTED: {
            if (self->conn_handle == ble_evt->evt.gap_evt.conn_handle) {
                self->conn_handle = BLE_CONN_HANDLE_INVALID;
            }
        }
        case BLE_GATTS_EVT_HVN_TX_COMPLETE: {
            queue_next_write(self);
        }
        default:
            return false;
            break;
```

**Comment by dhalbert** [comment]
> @dhalbert happy you're here, are these FALLTHROUGHs or missing break;s?

Those are bugs! Both those `case`s are missing `break`.

**Comment by dhalbert** [comment]
Also you could remove the extraneous curly braces, which should only be there if there's a local declaration in the `case` arm. Thanks.

**Review by dhalbert — APPROVED** [review]
LGTM! Thanks for adding this warning. It was clearly worth it!

**Pull request merged**
