### PR TITLE
Add PicoDVI support

### LINKED ISSUE #7562: PyPortal TFT left hand edge getting cutoff when using case with 8.0.0 release
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0 on 2023-02-06; Adafruit PyPortal with samd51j20
```

### Code/REPL

```python
n/a
```

### Behavior

n/a

### Description

Left hand edge of display gets cutoff when using the PyPortal with the Desktop Stand case:
https://www.adafruit.com/product/4146

Looks OK with 7.3.3.

### Additional information

See related forum thread here:
https://forums.adafruit.com/viewtopic.php?p=959876

### LINKED ISSUE #7643: CIRCUITPY_PYSTACK_SIZE=4000 crashes ESP32S3 boards to safe mode
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-alpha.2-17-g00a03c323 on 2023-02-23; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3
Adafruit CircuitPython 8.1.0-alpha.2-17-g00a03c323 on 2023-02-23; BPI-PicoW-S3 with ESP32S3
```

### Code/REPL

```python
No code.py file is executed.
```

### Behavior

On esp32s3 boards setting CIRCUITPY_PYSTACK_SIZE=4000 causes a crash into safe mode.

```
Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Fault detected by hardware.
Please file an issue with your program at https://github.com/adafruit/circuitpython/issues.
Press reset to exit safe mode.

Press any key to enter the REPL. Use CTRL-D to reload.
```

A value of 3500 works fine. 

### Description

I've used values up to 7000 on a board with the raspberry pi RP2040 micro controller without a similar crash.

This may be a total red herring but building with micropy_stackless=1 prevents the crash, *however setting CIRCUITPY_PYSTACK_SIZE > 3500 still doesn't seem to improve the stack limitations* (EDIT: I'm not sure about this now, my stack depth test may have been faulty). I remember @bill88t mentioning that on some boards the parameter had an effective upper limit but I can't find the note right now. Perhaps the ESP32S3 was one of those boards.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
PicoDVI in CP support 640x480 and 800x480 on Feather DVI, Pico and Pico W. 1 and 2 bit grayscale are full resolution. 8 and 16 bit color are half resolution.

Memory layout is modified to give the top most 4k of ram to the second core. Its MPU is used to prevent flash access after startup.

The port saved word is moved to a watchdog scratch register so that it doesn't get overwritten by other things in RAM.

Right align status bar and scroll area. This normally gives a few pixels of padding on the left hand side and improves the odds it is readable in a case. Fixes #7562

Fixes c stack checking. The length was correct but the top was being set to the current stack pointer instead of the correct top. Fixes #7643

This makes Bitmap subscr raise IndexError instead of ValueError when the index arguments are wrong.

### CODE REVIEW

**Comment by bill88t** [comment]
The part where it fixes the stack crashes, has been tested by me and and Retiredwizard, across all esp mcu's.

**Comment by RetiredWizard** [comment]
Tested new stack code on RP2040 and SAMD51, no issues....

This is from the PR artifact:
ezgif-2-2db80e5a70

**Review by dhalbert — APPROVED** [review]
Great! Code looks good for consistency, etc. Other people tested the actual video, so I did not do that.

**Comment by jposada202020** [comment]
As discussed in Discord.. I think I reduced the code as much as I can... hopefully

Tested in
`Adafruit CircuitPython 8.1.0-beta.1-36-g7d02bff6b on 2023-04-20; Adafruit Feather RP2040 DVI with rp2040`

## Problem
```python

import board
import displayio
from bitmaptools import draw_line
display = board.DISPLAY
group = displayio.Group()

palette = displayio.Palette(1)
palette[0] = 0xFFFFFF

a2 = displayio.Group(x=0, y=0, scale=1)
a2bitmap = displayio.Bitmap(300, 300, 2)
tile2 = displayio.TileGrid(a2bitmap, pixel_shader=palette, x=0, y=0)
draw_line(a2bitmap, 1, 1, 1, 300, 1)
draw_line(a2bitmap, 1, 1, 200, 200, 1,)
a2.append(tile2)
group.append(a2)

display.show(group)


```
image


So Not sure if my display resolution is all wrong, but I should get 640x480? If it is my mistake, sorry :).
However this script works fine in the Pyportal Titano https://github.com/jposada202020/CircuitPython_uplot/blob/main/examples/uplot_readme_example.py
But with the DVI is blown-up and some of the plots could not be seen.

**Comment by dglaude** [comment]
The above message from @jposada202020 is discussed in #7894 (and is now a closed issue).

> As discussed in Discord.. I think I reduced the code as much as I can... hopefully

**Pull request merged**
