### PR TITLE
Ignore "makefile", which can be used to customize the build

### PR DESCRIPTION
**Pull request by jepler**
e.g., I put content in ports/_portname_/makefile like
```
BOARD=boardname
DEBUG=1
include Makefile
```
so that when I `make` it picks up these flags automatically.

This change means that these files won't be picked up by `git status` or removed by `git clean` (unless -x is specified).

### CODE REVIEW

**Comment by jepler** [comment]
The "Makefile" and the "makefile" are different files.

**Comment by jepler** [comment]
However, behavior on systems which don't distinguish between "Makefile" and "makefile", like windows, may be a reason to not accept this PR.  I can't easily check those systems.

**Review by dhalbert — CHANGES_REQUESTED** [review]
> However, behavior on systems which don't distinguish between "Makefile" and "makefile", like windows, may be a reason to not accept this PR. I can't easily check those systems.

Both Windows and MacOS also have case-insensitive filesystems by default. I think those are showstoppers.

Alternatives:

1. Add
```make
-include makefile.local
```
to the Makefiles, and put `makefile.local` in `.gitignore`. See  https://stackoverflow.com/questions/3910054/makefile-conditional-include.

2. According to the documentation, GNU make "will look for the makefiles GNUmakefile, makefile, and Makefile, in that order." If you're always planning to use GNU make, you could add `GNUmakefile` to .gitignore instead.

3. Alias `make` to a script that checks for, say, `makefile.local`, and put `makefile.local` in the `.gitignore`.

**Comment by tannewt** [comment]
I like `makefile.local` because it's clearer. That said, I don't think CircuitPython builds on case-insensitive filesystems already. I had a mounted image on Mac that was case-sensitive to store it.

**Comment by jerryneedell** [comment]
in my experience everything except the esp32s2 will build on a case-incentive file system on a Mac. The espressif idf requires a cease insensitive file system.

**Comment by jerryneedell** [comment]
It may only be necessary to have a case sensitive file system to build the xtesna toolchainn locally -- that is the only place I see it mentioned here -- https://gitdemo.readthedocs.io/en/latest/macos-setup.html

**Comment by jerryneedell** [comment]
It may only be necessary to have a case sensitive file system to build the xtesna toolchainn locally -- that is the only place I see it mentioned here -- 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/get-started/macos-setup-scratch.html

**Comment by jerryneedell** [comment]
FYI -- I just did a fresh close of the CP repo to a default (case-insesntive) MacOS file system and I am able to build the esp32s2 files.. The only issue I aide was with the version of gdbgui installed -- has to revert it to 0.13.2.0 (that hs noting to do with the file systems)

**Pull request closed without merging**
