### PR TITLE
Add missing Feather M0 boards: RFM69, RFM9x, nRF51, WINC1500

### PR DESCRIPTION
**Pull request by tdicola**
This is the partner of pull https://github.com/adafruit/circuitpython/pull/538 for 2.x but against master.  Support for the missing RFM69, RFM9x, nRF51, and WINC1500 boards is added to the atmel-samd port.  These are again based on the M0 basic but with the addition of internally routed pins for peripherals.

All build as expected:
```
tony-imac:atmel-samd tony$ make BOARD=feather_m0_rfm69
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
install -d build-feather_m0_rfm69
python3 tools/gen_usb_descriptor.py \
		--manufacturer "Adafruit Industries LLC"\
		--product "Feather M0 RFM69"\
		--vid 0x239A\
		--pid 0x8015\
		build-feather_m0_rfm69/autogen_usb_descriptor.c
Generating build-feather_m0_rfm69/genhdr/mpversion.h
GEN build-feather_m0_rfm69/genhdr/qstr.i.last
QSTR updated
GEN build-feather_m0_rfm69/genhdr/qstrdefs.generated.h

25244 bytes free in flash out of 188416 bytes ( 184.0 kb ).
5344 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_rfm69/firmware.bin
Create build-feather_m0_rfm69/firmware.uf2
python2 ../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_rfm69/firmware.uf2 build-feather_m0_rfm69/firmware.bin
Converting to uf2, output size: 326656, start address: 0x2000
Wrote 326656 bytes to build-feather_m0_rfm69/firmware.uf2.
tony-imac:atmel-samd tony$ make BOARD=feather_m0_rfm9x
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
install -d build-feather_m0_rfm9x
python3 tools/gen_usb_descriptor.py \
		--manufacturer "Adafruit Industries LLC"\
		--product "Feather M0 RFM9x"\
		--vid 0x239A\
		--pid 0x8015\
		build-feather_m0_rfm9x/autogen_usb_descriptor.c
Generating build-feather_m0_rfm9x/genhdr/mpversion.h
GEN build-feather_m0_rfm9x/genhdr/qstr.i.last
QSTR updated
GEN build-feather_m0_rfm9x/genhdr/qstrdefs.generated.h

25244 bytes free in flash out of 188416 bytes ( 184.0 kb ).
5344 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_rfm9x/firmware.bin
Create build-feather_m0_rfm9x/firmware.uf2
python2 ../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_rfm9x/firmware.uf2 build-feather_m0_rfm9x/firmware.bin
Converting to uf2, output size: 326656, start address: 0x2000
Wrote 326656 bytes to build-feather_m0_rfm9x/firmware.uf2.
tony-imac:atmel-samd tony$ make BOARD=feather_m0_nrf51
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
install -d build-feather_m0_nrf51
python3 tools/gen_usb_descriptor.py \
		--manufacturer "Adafruit Industries LLC"\
		--product "Feather M0 nRF51"\
		--vid 0x239A\
		--pid 0x8015\
		build-feather_m0_nrf51/autogen_usb_descriptor.c
Generating build-feather_m0_nrf51/genhdr/mpversion.h
GEN build-feather_m0_nrf51/genhdr/qstr.i.last
QSTR updated
GEN build-feather_m0_nrf51/genhdr/qstrdefs.generated.h

25244 bytes free in flash out of 188416 bytes ( 184.0 kb ).
5344 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_nrf51/firmware.bin
Create build-feather_m0_nrf51/firmware.uf2
python2 ../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_nrf51/firmware.uf2 build-feather_m0_nrf51/firmware.bin
Converting to uf2, output size: 326656, start address: 0x2000
Wrote 326656 bytes to build-feather_m0_nrf51/firmware.uf2.
tony-imac:atmel-samd tony$ make BOARD=feather_m0_winc1500
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
install -d build-feather_m0_winc1500
python3 tools/gen_usb_descriptor.py \
		--manufacturer "Adafruit Industries LLC"\
		--product "Feather M0 WINC1500"\
		--vid 0x239A\
		--pid 0x8015\
		build-feather_m0_winc1500/autogen_usb_descriptor.c
Generating build-feather_m0_winc1500/genhdr/mpversion.h
GEN build-feather_m0_winc1500/genhdr/qstr.i.last
QSTR updated
GEN build-feather_m0_winc1500/genhdr/qstrdefs.generated.h

25216 bytes free in flash out of 188416 bytes ( 184.0 kb ).
5340 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Create build-feather_m0_winc1500/firmware.bin
Create build-feather_m0_winc1500/firmware.uf2
python2 ../../tools/uf2/utils/uf2conv.py -b 0x2000 -c -o build-feather_m0_winc1500/firmware.uf2 build-feather_m0_winc1500/firmware.bin
Converting to uf2, output size: 326656, start address: 0x2000
Wrote 326656 bytes to build-feather_m0_winc1500/firmware.uf2.
```

### CODE REVIEW

**Comment by tannewt** [comment]
Thanks for doing this on both branches!

**Comment by tdicola** [comment]
I kept it nRF51 because it will lead to confusion with future nRF52 and other bluetooth boards that use the Bluefruit nomeclature.  To prevent any confusion it's explicit with the chip name.  The RFM69 and 9x boards go by 'RadioFruit' but again have confusion between which one is supported.

**Comment by tannewt** [comment]
I disagree. I think it will be more confusing now when it doesn't match the product name in the shop or the guide page. RFM69 and 9x LoRa are not called RadioFruit in the product name like the M0 Bluefruit LE is. (I'm looking here: https://learn.adafruit.com/adafruit-feather?view=all#lora-radio-feathers)

**Comment by tdicola** [comment]
How to resolve this then?
screen shot 2018-01-18 at 2 40 09 pm

**Comment by dhalbert** [comment]
How about feather_m0_bluefruit_le_nrf51? I know it's long but if there's a bluefruit_le_nrf52 they will be easy to disambiguate. Similar for the RFM boards: processor and chipset name.

Perhaps @ladyada has an opinion as well.

**Comment by tdicola** [comment]
Whatever we want to land on ultimately works for me--my suggestion is don't 'use up' feather_m0_wifi, feather_m0_bluefruit, etc. with these early boards like the WINC1500 and nRF51--it would be unfortunate when a fancier/better/etc. WiFi or BLE board comes around and wants to be the 'default' feather.

**Comment by ladyada** [comment]
i have been summoned!!!

i don't want an m0+nrf51 or m0+winc board definition at this time because we dont have drivers for em right now and no plans to write drivers, & if we have bins it will make people think that its supported

for the m0+radios, please keep the two as **feather_m0_rfm69** & **feather_m0_rfm9x**

**Comment by tdicola** [comment]
Sounds good, this is changed to remove the board definitions.  If anyone needs to access the internally routed pins on these boards check out the microcontroller module and a Feather M0 basic build.

**Comment by ladyada** [comment]
oop, i just realized that travis is running but it wont actually check this build! 
@tdicola please update .travis.yml and tools/build_adafruit_bins.sh for both

**Comment by tdicola** [comment]
Sure--I also show above the build is clean and works for all boards.  This was from a fresh pull of the repo with GCC 7.  Let me know if there's a doc or explanation of what to update in the travis file before I update it too.  I assume it just needs an addition similar to the M0 basic boards.

**Comment by tdicola** [comment]
Both pulls should be updated with what appears to be the way to add new boards.  One thing though, this will send the generated bins to rosie's ngrok URL just like the other boards.  If there's any state in rosie that needs to be made aware of these new boards let me know--it's not clear what happens once the bins are sent.  Travis should be building them though (both the .uf2 and .bin versions).

**Comment by tannewt** [comment]
Rosie will store them temporarily. It doesn't check the board name until later.

**Comment by tdicola** [comment]
Err actually now this pull is updated for the master branch.  It looks like the travis config is bifurcated between building on travis and other environments so the list of boards lives in two spots (.travis.yml and build_adafruit_boards.sh).  I've updated both places now, but should we remove the concept of ATMEL_BOARDS from build_adafruit_boards.sh?  This in particular: https://github.com/adafruit/circuitpython/blob/master/tools/build_adafruit_bins.sh#L5  Something to consider for future work.

**Pull request merged**
