### PR TITLE
Add board: seeed_xiao_esp32c3

### PR DESCRIPTION
**Pull request by prplz**
Adds a new board from seeed.
Purchase: https://www.seeedstudio.com/Seeed-XIAO-ESP32C3-p-5431.html
Pinout: https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/#pinout-diagram
Schematic: https://files.seeedstudio.com/wiki/XIAO_WiFi/Resources/Seeed_Studio_XIAO_ESP32C3_v1.0_SCH.pdf
Note about renaming of the xiao range: https://www.seeedstudio.com/blog/2022/07/06/notice-on-product-name-change/.

Tested all digital pins, wifi, i2c and uart on the hardware, didn't test analog or spi but they should be correct. Note there is no usable LED on this board.

Creation ID has not been obtained yet, @tannewt can you please create a repo for seeed studio creations.

### CODE REVIEW

**Comment by tannewt** [comment]
@prplz Here is the creations repo: https://github.com/creationid/seeed-studio-creations

**Comment by prplz** [comment]
Added creation ID, needs https://github.com/creationid/seeed-studio-creations/pull/1

**Comment by Neradoc** [comment]
The default extension is now set to "bin" for C3 in mpconfigport with #6629.
Undoing the change to `build_board_info.py` will resolve the conflict.

**Comment by prplz** [comment]
Should be ok now

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
