### PR TITLE
Driver for Pervasive Display's Aurora based E-ink display

### PR DESCRIPTION
**Pull request by wyrdsec**
A driver for Pervasive Displays Aurora CoG chipsets: 
https://www.mouser.com/new/pervasive-displays/pervasive-displays-aurora-mb-displays/

My group used these displays for a Circuitpython badge we created, and this driver came from that effort.

The driver uses `framebufferio.FramebufferDisplay` (very similar to the `sharpdisplay` module) to interact with `displayio`. I has support for the 1.44", 2", 2.7", 1.9", and 2.6" sized Aurora EPD products, however I only have the 2" sized EPD so that is all I can test at this time.

This module will not be included in compilation by default, as I set the `CIRCUITPY_AURORA_EPAPER` define to `0`. No other boards use this display AFAIK so I have just been setting that def in `mpconfigboard.mk`.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Thanks! Looks like you'll need to format via pre-commit and then it'll be good to go. https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

**Comment by wyrdsec** [comment]
I'm sorry but I can't seem to wrangle sphinx to do what I need. For some reason the second line of the docs comment is being included in the title of the page.

```
//| class AuroraMemoryFramebuffer:
//|     """A framebuffer for Pervasive Displays Aurora E-paper displays.
//|
//|     These displays are 2 color only.
```

Do I need another line break or special character to stop it from doing this?

**Comment by tannewt** [comment]
That looks right to me. Can you share a screenshot of what it is doing? There should be a matching .pyi file somewhere with the Python stub version. That may make it clearer.

**Comment by wyrdsec** [comment]
I was looking at the latest github build actions version here: https://circuitpython--9488.org.readthedocs.build/en/9488/shared-bindings/aurora_epaper/index.html

However, it seems like its working the way I expect now. I must have been seeing an old cached page on my browser.

**Review by tannewt — APPROVED** [review]
Great! Thank you!

**Pull request merged**
