### PR TITLE
Speed up JSON parsing with readinto (#3728 for 6.0.x)

### PR DESCRIPTION
**Pull request by dhalbert**
This backports #3728 to 6.0.x. It would be great if someone else could test this, because I'm not sure what a good simple test would be.

### CODE REVIEW

**Comment by dhalbert** [comment]
I'm thinking maybe this is not worth it because most ESP32-S2 users are on 6.1.x.

**Comment by tannewt** [comment]
It would help other SAMD51 portal projects though. If it's not too much work I think it's worth having.

**Comment by dhalbert** [comment]
I tested a very chonky (250kB) .json on ESP32-S2 and it worked.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
