### PR TITLE
Configure default espressif wifi power

### LINKED ISSUE #9235: Wemos C3 Mini should pre-set tx_power to 8.5
### CircuitPython version

```python
main
```

### Code/REPL

```python
n/a
```

### Behavior

As reported by multiple users, with the power-on default tx_power, the board does not successfully connect to wifi (https://github.com/adafruit/circuitpython/issues/6540 https://github.com/adafruit/circuitpython/issues/9058#issuecomment-2104612719 and probably others) but does work if boot.py executes `wifi.radio.tx_power=8.5`.

### Description

_No response_

### Additional information

The board init routine should set tx_power=8.5 by default, without needing lines in boot.py.

### PR DESCRIPTION
**Pull request by bill88t**
Please refer to https://github.com/adafruit/circuitpython/issues/9235#issuecomment-2181603272.
Fixes #9235.

### CODE REVIEW

**Comment by dhalbert** [comment]
@bill88t We started with choice of 8.5 dBm was from @askpatrickw on a particular board: #6540.

@askpatrickw It's been a while, but did you choose that value as the maximum practical for the board, or was it a quick choice that worked?

@karlfl's experimentation (https://github.com/adafruit/circuitpython/issues/9235#issuecomment-2181890602) where 18dBm seems like the max. I would be inclined to use a somewhat lower value, but I'm not sure about choosing 8.5 dBm, which is quite a bit less.

The regulatory max is 20 dBm, which is 100 mW. 10 dBm is 10mW. 8.5 dBm is about 7 mW. dBm is a log scale.

**Comment by bill88t** [comment]
I started testing (on the supertiny) by constantly switching between two networks, one really close (10cm) and one that is purposefully barely in range (about ~25m diagonally, vision obstructed).

I started from `tx_power=18` and climbed down 1.0 at a time.
While some values did work once or twice, once the board heated up (due to the wifi transmission power), the reliability plummeted to 0.
The board was let to cool before every value swap.

I decided 11 is fully reliable at normal operation.
(I let it reconnect between the two networks for 2 minutes.)

To simulate hotter environments, I ran `stress --cpu 20` on my thinkpad and put the board next to it's fan exaust and some plastic tape on it.
This slowly raised the board temperature to 68C.
When it equalized, value 11 was ~70% reliable at the faraway network switch.
However reducing the value to 10, drops reliability to 10%, due to range.

**Comment by bill88t** [comment]
No, this doesn't actually fix the 3D antennas. It makes em worse.

Furthermore, the only boards actually benefited from this are just the supertiny and the wemos c3 mini.

We should just add an override for those boards.

**Comment by askpatrickw** [comment]
To answer the question to me. I unfortunately	don't have any recollection about that specific value.

**Pull request closed without merging**
