### PR TITLE
Remove gamepad, gamepadshift

### PR DESCRIPTION
**Pull request by jepler**
These are effectively replaced by the new keypad module (#4877)

@deshipu @ladyada

### CODE REVIEW

**Comment by dhalbert** [comment]
Currently `keypad` is not turned off for all SAMD21 builds:
https://github.com/adafruit/circuitpython/blob/ae5080955e4be9a7f958dc8197662080c39dbe95/ports/atmel-samd/mpconfigport.mk#L53
So we need to turn it back on for some or all, especially those boards that depend on `gamepad` or `gamepadshift` for most of their use (e.g. pewpew boards) but there may be space issues for larger languages.

**Comment by jepler** [comment]
I've fixed build errors and explicitly enabled keypad on:
 * 8086_commander
 * pewpew_m4
 * ugame10
All other boards that HAD gamepad or gamepadshift seemed to already have keypad enabled.

**Comment by dhalbert** [comment]
> All other boards that HAD gamepad or gamepadshift seemed to already have keypad enabled.

Before I added `keypad`, pretty much all the SAMD21 CIRCUITPY_FULL_BUILD boards had `gamepad`, i.e. there was something like:
```
CIRCUITPY_GAMEPAD ?= $(CIRCUITPY_FULL_BUILD)
```
I had to set that to `0` for all SAMD21 to get the builds to fit. So if possible it would be good to put `keypad` back in the `CIRCUITPY_FULL_BUILD`

**Review by tannewt — CHANGES_REQUESTED** [review]
Please don't merge this until all examples and libraries have been updated.

**Comment by jepler** [comment]
I'll re-disable gamepad whereever it doesn't fit based on the above builds, and then wait for the signal that this can be merged.

**Comment by deshipu** [comment]
@jepler please don't disable gamepad on pewpew_m4 without first merging https://github.com/adafruit/circuitpython/pull/4942 — the Stage library needs to be modified to use keypad.

**Comment by ladyada** [comment]
i reviewed & merged #4942

**Comment by dhalbert** [comment]
These libraries are still using `gamepad` or gamepadshift`:

- [ ] `adafruit-circuitplayground`, `were_pressed()`, and in `conf.py`
- [ ] `adafruit-pybadger`
- [ ] `adafruit-cursorcontrol`
- [ ] `adafruit-clue`

**Comment by dhalbert** [comment]
I will update #5059 or open a new PR to include parts of this. `gamepad` and `keypad` together do not fit on some SAMD21 boards. But we'll leave `gamepadshift` in for 7.0.0 because it's harder to emulate, and not remove it until 8.0.0 after the libraries that use `gamepadshift` have been updated to use `keypad`.

**Pull request closed without merging**
