### PR TITLE
Add codeop.compile_command

### PR DESCRIPTION
**Pull request by jepler**
This function in standard Python is a building block for custom REPLs:
```python
from codeop import compile_command

print("Repl in (Circuit-)Python")
ns = {}

PS1="<<< "
PS2=",,, "
command = ""
while True:
    line = input(PS2 if command else PS1)
    if command:
        command = command + "\n" + line
    else:
        command = line
    try:
        if (code := compile_command(command)):
            command = ""
            exec(code, ns)
    except Exception as e:
        command = ""
        print(e)
```

```python
>>> import myrepl
Repl in (Circuit-)Python
<<< for i in range(10):
,,,  print(i, i*i)
,,, 
0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
<<< 3+3
6
<<< [
,,, 1
,,, ,
,,, 2,
,,, 3]
[1, 2, 3]
<<< 
```

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks good to me! What are you using it for?

**Comment by jepler** [comment]
I don't have a specific use case for it right now. I like the general idea of being able to build a custom Python REPL. If you don't want to include this when nobody's planning on a specific use for it, please feel free to close it up. Someone can revive it later.

**Comment by jepler** [comment]
(my real crazy dreams also require an async input() or something)

**Comment by RetiredWizard** [comment]
I currently use a python REPL on the LilyGo T-Deck and it's apparently been used by a few folks based on the [github](https://github.com/RetiredWizard/tdeck_repl) activity. It's useful when using the device as a standalone CP device.

As Jeff has shown above, this PR makes upgrading that REPL to support multiple line statments (For, If, etc) relatively easy,  although I had already started thinking about what was needed without this addition. There has also been mentions of possibly supporting additional keyboards in the native REPL which would certainly eliminate the need for this particular use case.

**Comment by tannewt** [comment]
> I don't have a specific use case for it right now. I like the general idea of being able to build a custom Python REPL. If you don't want to include this when nobody's planning on a specific use for it, please feel free to close it up. Someone can revive it later.

I'm fine for it to be merged in. I was just curious. Merging will prevent it from getting stale.

**Pull request merged**
