### PR TITLE
Fixes and Enhancement for Touch Alarm

### PR DESCRIPTION
**Pull request by microDev1**
A couple of fixes and an enhancement for `TouchAlarm`.

**Fixes :-** 
- Fix `wake_alarm` is set to touch alarm on auto-reload.
- Prevent touch alarm initialization if not set. _Issue #3968._

**Enhancement :-** 
- Add ability to have multiple touch alarms in light-sleep.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks! I tested the PR artifact on a MagTag. With no `TouchAlarm` enabled, power consumption is back down, about 230uA. Did you turn off something else that would have lowered it from the 260uA I saw before?

Deep-sleeping with a `TouchAlarm` enabled brings the sleep current back up to 2.something mA. Do you think it is possible to get this down further by setting the duty cycle lower with setting changes via `touch_pad_set_meas_time()` or other changes? We can ship with the higher current now, as long as `TimeAlarm` is low-current, but it would be nice to have lower consumption for touch.

**Comment by dhalbert** [comment]
@microDev1 could you merge from adafruit to get `circuitpython.pot` in sync, and the push again? Thanks. I could not [push to your PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by microDev1** [comment]
> Did you turn off something else that would have lowered it from the 260uA I saw before?

Not that I know of... the changes here are `TouchAlarm` specific.

> Do you think it is possible to get this down further by setting the duty cycle lower with setting changes via touch_pad_set_meas_time() or other changes?

The default touchpad config settings are being used at the moment... it might be possible to get lower current consumption by altering them. There is also a concern of stuff like `ULP` being on during sleep as `esp_sleep_pd_config()` is explicitly called.

 > We can ship with the higher current now, as long as TimeAlarm is low-current, but it would be nice to have lower consumption for touch.

I agree... current in `mA` range is too high.

**Review by dhalbert — APPROVED** [review]
Thanks! For now, ignoring a couple of de_DE builds that are too big.

**Pull request merged**
