### PR TITLE
Automate USB VID/PID Uniqueness Check

### LINKED ISSUE #2962: Automate USB VID/PID uniqueness check
We should add a CI check for USB VID/PID validity. It's a common issue with new board PRs

### PR DESCRIPTION
**Pull request by sommersoft**
Fixes #2962 

I added in my assumptions for ignore-able, whitelisted boards.

I imagine this will sit open a while, during any VID/PID reassignment. I'm more than happy to update `mpconfigboard.mk` entries here, or just defer it all to merge in changes prior to merging this one.

Example Actions run: https://github.com/sommersoft/circuitpython/runs/714747984?check_suite_focus=true#step:22:1
_(Or...the example run in this PR will work too. Not sure what I was thinking... lol)_

### CODE REVIEW

**Comment by tannewt** [comment]
@kattni Did you have a chance to look at this at all?

**Comment by kattni** [comment]
@tannewt No, not at all. Other things ended up taking priority.

**Comment by tannewt** [comment]
Ok, no problem! Just wanted to make sure the status here was up-to-date. Thanks!

**Comment by tannewt** [comment]
I'm going to do this tomorrow.

**Review by tannewt — APPROVED** [review]
Looks great! I've fixed it up to pass.

**Pull request merged**
