### PR TITLE
Add support for Serpente boards

### PR DESCRIPTION
**Pull request by arturo182**
A set of two simple boards with SAMD21E18 and 4MB of flash. They have the same HW and only differ in USB connector.

### CODE REVIEW

**Comment by arturo182** [comment]
Again the build issue :/

   ##[error]fatal: reference is not a tree: 454e971a4d6fda69fc0045d8deb7dc9cae08a960

**Comment by tannewt** [comment]
@arturo182 This is a bug that will hopefully be fixed in the near future. Until then, a workaround is to merge in master and push the merge commit to the PR. That will trigger a new build

**Comment by arturo182** [comment]
Seems that worked, checked out and building now.

**Comment by arturo182** [comment]
```Build serpente for de_DE took 16.98s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.

-236 bytes free in flash out of 253440 bytes ( 247.5 kb ).
24916 bytes free in ram for stack out of 32768 bytes ( 32.0 kb ).

Too little flash!!!```

I don't get it, I use the same `SAMD21E18A` like gemma_m0, trinket_m0 and many other, why is my board the only one that doesn't fit?

**Comment by arturo182** [comment]
@tannewt should be good now

**Pull request merged**
