### PR TITLE
protomatter: Update to version that supports tiling

### PR DESCRIPTION
**Pull request by jepler**
Update to a version of Protomatter that supports tiling.  This requires https://github.com/adafruit/Adafruit_Protomatter/pull/32 be merged upstream.

Testing performed: None yet, just that the matrixfeather firmware builds.

### CODE REVIEW

**Comment by jepler** [comment]
@PaintYourDragon if you care to do testing: [matrixportal-tiled.zip](https://github.com/adafruit/circuitpython/files/5875948/matrixportal-tiled.zip)

Code for creating a 64x64 display from two 32x64 displays in serpentine arrangement:
```
import displayio
import board
import rgbmatrix
import framebufferio

width = 64
height = 64
bit_depth = 3

addr_pins = [board.MTX_ADDRA, board.MTX_ADDRB, board.MTX_ADDRC, board.MTX_ADDRD]
rgb_pins = [
    board.MTX_R1,
    board.MTX_G1,
    board.MTX_B1,
    board.MTX_R2,
    board.MTX_G2,
    board.MTX_B2,
]
clock_pin = board.MTX_CLK
latch_pin = board.MTX_LAT
oe_pin = board.MTX_OE

displayio.release_displays()

matrix = rgbmatrix.RGBMatrix(
                width=width,
                height=height,
                bit_depth=bit_depth,
                rgb_pins=rgb_pins,
                addr_pins=addr_pins,
                clock_pin=clock_pin,
                latch_pin=latch_pin,
                output_enable_pin=oe_pin,
                tile=2, serpentine=True,
            )
display = framebufferio.FramebufferDisplay(matrix)
```

**Review by tannewt — DISMISSED** [review]
Looks good to me! Thanks for the update!

**Review by gamblor21 — COMMENTED** [review]
Tested using two 32x64 matrices with the Matrix portal. Worked fine in serpentine True and False. Reviewed the files and looks good to me.

**Review by tannewt — APPROVED** [review]
Thanks!

**Comment by ladyada** [comment]
🐍 🐍 🐍 🐍 🐍 
🐍 🐍 🐍 🐍 🐍 
🐍 🐍 🐍 🐍 🐍 
🐍 🐍 🐍 🐍 🐍

**Pull request merged**
