### PR TITLE
Add board definition files for ARAMCON2 Badge

### PR DESCRIPTION
**Pull request by bmeisels**
Due to Covid-19 the work on the badge was delayed but finally we are gearing up to host the conference in June.
The badge has been renamed from "AramCon Badge 2020" to "ARAMCON2 Badge".

VID/PID allocated here: https://github.com/adafruit/circuitpython/issues/2454

### CODE REVIEW

**Comment by ladyada** [comment]
please fix so its passing CI and then tag us to review! :)

**Comment by bmeisels** [comment]
There seems to be an issue in one of the tests which is unrelated to our board.
I have tried to rerun the CI.
Hopefully that will solve the issue.

**Comment by bmeisels** [comment]
@ladyada I rerun the CI and the feather_m4_can fails again.
This doesn't seem to be related to our changes.
Any idea on why this is happening?

**Comment by jepler** [comment]
This pull request modified the "protomatter" submodule.  It has to be set back to how it was in the main branch before this PR can pass CI.  Let us know if you need help getting that fixed.

**Comment by bmeisels** [comment]
I totally missed that.
Will fix it shortly.
Thanks @jepler !

**Review by ladyada — APPROVED** [review]

**Pull request merged**
