### PR TITLE
Turn on touchio for M0 boards.

### LINKED ISSUE #670: touchio not yet supported (CP 3.0 alpha 2)
It would be great to get touchio ported to the latest CircuitPython release.

Board: Trinket M0
Version: Adafruit CircuitPython 3.0.0-alpha.2-13-gdde5ade-dirty on 2018-03-10; Adafruit Trinket M0 with samd21e18

Replicate by: "import touchio" generates "ImportError: no module named 'touchio'"

### PR DESCRIPTION
**Pull request by tannewt**
M4 will come later once its supported by FreeTouch.

Fixes #670

### CODE REVIEW

**Comment by tannewt** [comment]
This depends on https://github.com/adafruit/Adafruit_FreeTouch/pull/5

**Comment by tannewt** [comment]
hold off on a review. I'm still testing this

**Comment by tannewt** [comment]
Ok, please take a look @dhalbert

**Comment by dhalbert** [comment]
Woot! Tested on CPX and it's fine. Non-Express builds are failing due to too little flash. For now, could you uncomment `##  CFLAGS += -finline-limit=50` in the Makefile? You can set it to 60 instead of 50 -- that works.

**Pull request merged**
