### PR TITLE
Fix some regressions on feather M7

### LINKED ISSUE #7944: metro m7 no longer gets midi events
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-beta.2 on 2023-04-26; Metro MIMXRT1011 with IMXRT1011DAE5A
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

import time

import usb_midi

import adafruit_midi

# from adafruit_midi.channel_pressure        import ChannelPressure
from adafruit_midi.control_change import ControlChange
from adafruit_midi.note_off import NoteOff
from adafruit_midi.note_on import NoteOn
from adafruit_midi.pitch_bend import PitchBend

# A subset of messages/events
# pylint: disable=unused-import
from adafruit_midi.timing_clock import TimingClock

# 0 is MIDI channel 1
midi = adafruit_midi.MIDI(midi_in=usb_midi.ports[0], in_channel=0)

print("Midi input test")

# Convert channel numbers at the presentation layer to the ones musicians use
print("Input channel:", midi.in_channel + 1)

while True:
        msg = midi.receive()
        if (msg := midi.receive()) is not None:
            print(time.monotonic(), msg)
```

### Behavior

no midi events are ever printed

### Description

Under 8.0.5, the test program prints note on/off messages when I send MIDI events to it using a virtual keyboard on my PC.

Under 8.1.0-beta.2, the notes are not received

### Additional information

8.1.0-beta.0 tests OK, 8.1.0-beta.1 fails my test. So the problem seems to have been introduced between those two versions.

@jedgarpark saw this too while working on preparing a demo last wednesday, I only now had time to confirm it.

### PR DESCRIPTION
**Pull request by jepler**
This closes #7944 but it's fishy -- why is such a large buffer required?  @hathach your feedback would be appreciated about this question.

It also includes a board-specific fix for #7952 but this may be needed on other boards. @tannewt do you know what's going on here? The USB_DM/USB_DP pins seem to just be dummy objects on 1011 but adding these to the list (as you did on the 1011 evk) does allow CP to start. If this is correct, the fix should be propagated to ALL boards, or incorporated at a better location.
```c
ports/mimxrt10xx/peripherals/mimxrt10xx/MIMXRT1011/pins.c:
const mcu_pin_obj_t pin_USB_OTG1_DN = { { &mcu_pin_type }, };
```

### CODE REVIEW

**Comment by tannewt** [comment]
> @tannewt do you know what's going on here? The USB_DM/USB_DP pins seem to just be dummy objects on 1011 but adding these to the list (as you did on the 1011 evk) does allow CP to start. If this is correct, the fix should be propagated to ALL boards, or incorporated at a better location.

I don't. I didn't think that the reset code would get this far because it should be bounded by the IOMUXC count. Must be some loop bounds error.

**Comment by jepler** [comment]
@tannewt can we merge this even if the reason the USB_DM/DP change fixes anything is murky? It's unfortunate and frustrating that metro m7 seems to simply not work at present.

**Comment by gamblor21** [comment]
Tested and this did give me access back to the Metro M7. If things work out I will get a new MIDI keyboard tomorrow and could try the MIDI part.

**Comment by jepler** [comment]
#7964 was the better fix for the not-booting-at-all problem. This is now just to fix the MIDI problem. I only increased the RX (to microcontroller) buffer, and only tested this direction. Before merging, both directions should be tested to find out if they work.

**Comment by jepler** [comment]
In my testing, the M7 can now receive (from linux vkeybd) and send (to linux timidity) midi events. So, the send buffer doesn't currently need a size increase, just the receive buffer.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
