### PR TITLE
Added Dxx names to analog pins on Feather M4 Express pins.c file

### PR DESCRIPTION
**Pull request by scs217**
I added digital pin names to A0-A5 and SCK, MOSI, MISO as shown in the product pinout. I discussed this change with Radomir Dopieralski on Discord help-with-circuitpython channel.

### CODE REVIEW

**Comment by scs217** [comment]
Thanks for the approval @ladyada ! I'll roll this out to other boards as I have time and submit a larger pull request for the lot.

**Comment by scs217** [comment]
@dhalbert Done!

**Comment by dhalbert** [comment]
OK, I wasn't as clear as I should have been - sorry! It's OK to keep the singleton lines together to save space, and then have a blank line before the three `board` things at the end. I just usually add blank lines around two or more of the same pin together.

**Comment by dhalbert** [comment]
The whole file here: https://github.com/adafruit/circuitpython/blob/master/ports/nrf/boards/circuitplayground_bluefruit/pins.c#L4 is an example of logical grouping.

**Comment by scs217** [comment]
Have a look now, I think it should be right.

**Comment by dhalbert** [comment]
Very nice, thanks for indulging my finickiness.

**Pull request merged**
