### PR TITLE
Fix stm32f412zg compile warning

### LINKED ISSUE #2122: build warning for stm32f412zg_discovery
Building the current master yields this warning for stm32f412zg_discovery.
Is something missing in the bsp?
```

Build stm32f412zg_discovery for en_US took 29.02s and succeeded
make: Entering directory '/home/jerryneedell/circuitpython_master/ports/stm32f4'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
GEN build-stm32f412zg_discovery/genhdr/moduledefs.h
QSTR updated
../../supervisor/stub/internal_flash.c:52:16: warning: 'convert_block_to_flash_addr' defined but not used [-Wunused-function]
 static int32_t convert_block_to_flash_addr(uint32_t block) {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

### PR DESCRIPTION
**Pull request by hierophect**
Resolves #2122. Removes an unnecessary function in the new flash stub file that causes a compiler warning for boards that use it. Also re-applies warning as error, which was removed for very early stm32 port work.

### CODE REVIEW

**Comment by dhalbert** [comment]
Why don't you just comment it out, because it will need to go back in when the stub is implemented, I think?

**Comment by hierophect** [comment]
> Why don't you just comment it out, because it will need to go back in when the stub is implemented, I think?

It isn't strictly universal, the implementation and naming differs across the nrf and atmel ports. It also isn't a part of the API. We could keep it, but should we also update nrf to match?

**Comment by dhalbert** [comment]
OK, seems fine. I'm not sure why the build isn't throwing an error on the warning. It's worth doing `-Werror` in the makefiles for stm32f4: we do that for the other ports, because  a warning indicates a possible problem, and ignoring them on builds can miss errors. If we need to turn off a bogus warning, we do (for example):
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wcast-align"
// code giving a warning
#pragma GCC diagnostic pop
```

**Comment by hierophect** [comment]
That's a good reminder. I removed that a while ago since it was getting in the way of very early port work. Now that things are cleaned up it should go back in.

**Pull request merged**
