### PR TITLE
Correctly handle settings.toml that ends without a newline

### LINKED ISSUE #7380: CIRCUITPY_WEB_API_PORT being ignored - ProS3 / ESP32S3
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; ProS3 with ESP32S3
(Using latest U2F version with latest bootloader)
```

### Code/REPL

`settings.toml`
```python

CIRCUITPY_WIFI_SSID="GBD-TPLINK-Ext-2.4GHz"
CIRCUITPY_WIFI_PASSWORD="secretpassword"
CIRCUITPY_WEB_API_PASSWORD="password"
CIRCUITPY_WEB_API_PORT=3000
```

### Behavior

It looks as if CIRCUITPY_WEB_API_PORT is being ignored.
The webapi works but it just defaults to port 80 every time.

Tried a lower value of 70 for the port but it made no difference
Tried in and out of quotes (should be out of quotes) but made no difference
I kept my ssid real in case there's something in it messing with the setup, but not posting my password for obvious reasons, although that only contains letters and numbers but no special characters

### PR DESCRIPTION
**Pull request by jepler**
The settings.toml parser did not handle a file that ended without a trailing newline. When such a file was encountered, retrieving the value on the last line would result in the error `Invalid byte 'EOF'`. For values fetched automatically e.g., by web workflow this message could not be shown.

However, such files are (A) frequently produced by text editors that folks actually use and (B) are specifically permitted by the TOML spec. (so my pedantic objection that (C) such files are not valid UNIX text files doesn't matter :wink:)

I had hoped this would help with #7380 but the reporter tested and it did not.

This PR also adds printing of the failure messages parsing values fetched automatically. This helps with web workflow (e.g., if you have the incorrect line `CIRCUITPY_WIFI_SSID='example'`  you'll now see `An error occurred while retrieving 'CIRCUITPY_WIFI_SSID': Invalid byte "'"` each time the interpreter resets) however, values that are only fetched once like CIRCUITPY_RESERVED_PSRAM will probably still have their error messages hidden because they occur just once before the serial output is visible.

DOS and UNIX-style line endings are both now explicitly tested, as is a no-eof file.

As a workaround, adding a comment line as the last line of the settings.toml should let it parse the last value.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Did not test but that's what your tests are for.

Could you use `%S` for that case in another PR where you made an error message into a QSTR?

**Comment by jepler** [comment]
@grbd if you can test with an artifact from this PR and let us know if the issue is fixed for you, that'd be helpful. Otherwise we'll probably merge it in the next day or so if we don't hear from you.

**Comment by grbd** [comment]
I just tried testing by adding a couple of newlines and comments at the bottom of `settings.toml`
but that didn't seem to fix it.
I'll have a go with the S3 daily firmware build once it hits there to see if it works

**Comment by jepler** [comment]
OK, I may be wrong about the cause then. I tested with a Pico W, perhaps there's a unique problem for esp32-s3 too.

**Pull request merged**
