### PR TITLE
Added Bast Pro Mini M0

### PR DESCRIPTION
**Pull request by sabas1080**
Hi

Port for Electronic Cats Bast Pro Mini M0

https://github.com/ElectronicCats/Bast-Pro-Mini-M0

Thanks!

### CODE REVIEW

**Comment by dhalbert** [comment]
@sabas1080 Could you merge from upstream and push a new commit? There were additions to `.travis.yml` (new boards) that are not in the version you pushed. Also, the translations have changed, so you'll want to merge that too.

**Comment by sabas1080** [comment]
update a new commits

**Comment by dhalbert** [comment]
Hi, your changes to `.travis.yml` are still out of date, and accidentally remove some new boards that were recently. Check the diff: https://github.com/adafruit/circuitpython/pull/1715/files#diff-354f30a63fb0907d4ad57269548329e3

image

**Comment by dhalbert** [comment]
The easiest thing might be to copy your new board definitions aside, do `git checkout master; git fetch upstream; git merge upstream/master`, and then create a new branch for this PR. Then edit `.travis.yml` to add your board, and copy the board definitions back into the the tree.

I notice you're merging from `master` in your fork. It's somewhat easier if you create a local branch in your fork for any changes. Keep `master` pristine and the same as upstream if you're trying to track upstream. We have a guide about the workflow we use: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github.

**Comment by tannewt** [comment]
I did an additional merge and will merge this if Travis gives the ok.

**Comment by dhalbert** [comment]
restarting hallowing build subjob, after latest fix reducing its size

**Comment by dhalbert** [comment]
all checks ok now

**Pull request merged**
