### PR TITLE
samd: Don't rely on RTC interrupt

### LINKED ISSUE #5985: time.monotonic_ns sometimes jumps forward, and then returns the correct value on the next call
### CircuitPython version

```python
pi@serialpi:~ $ more /media/CIRCUITPY/boot_out.txt 
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather M4 Express with samd51j19
Board ID:feather_m4_express
```

### Code/REPL

```python
# system is bigger than this, but this is the only code making calls to monotonic_ns
def get_new_now(prev):
    global previous_now
    global monotonic_ns_calls

    if prev is not None:
        previous_now = prev

    monotonic_ns_calls += 1
    now = time.monotonic_ns()

    if previous_now is not None:
        if previous_now > now:
            print(f"monotonic_ns MOVED BACKWARD! {previous_now} {now} : {monotonic_ns_calls} {count_string()}")
        elif now - previous_now > SECONDS_PER_NS * 3600 * 24:
            print(f"monotonic_ns JUMPED MORE THAN A DAY! {previous_now} {now} : {monotonic_ns_calls} {count_string()}")
            # monotonic_ns_calls += 1
            # now = time.monotonic_ns()
            # print(f"called monotonic_ns() again, now: {now}")

    return now
```

### Behavior

```
monotonic_ns JUMPED MORE THAN A DAY! 4194303992614752 4456447999938977 : 13388088 loop_count: 3868063 state_clock: 3868062
[...other stuff...]
monotonic_ns MOVED BACKWARD! 4456447999938977 4194304025573733 : 13388089 loop_count: 3868064 state_clock: 3868063
```

### Description

I have two Adafruit Feather M4 running programs that call time.monotonic_ns ~100 times a second. Each day with approximately a 10% chance it seems one them makes a monotonic_ns call and gets a result more than a day in the future. The next call then seem to be ok.

I have an Adafruit Bluefuit Circuit Playground running similar code that doesn't seem to present this problem. Aside from the CPU one difference is the M4's are setting rtc.RTC().datetime once an hour...thought the discontinues in monotonic_ns don't seem correlated with these calls.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jepler**
I instrumented RTC_Handler and determined that on SAMD51 it was possible for the interrupt to be delivered well before the actual overflow of the RTC COUNT register (e.g., a value as small as 0xffff_fffd could be seen at the time of overflow)

Rather than depending on the overflow interrupt coming in at the same time as COUNT overflows (exactly), rely only on observed values of COUNT in _get_count, overflowing when it wraps around from a high value to a low one.

With this change, PLUS a second change so that it is possible to warp the RTC counter close to an overflow and test in 20ms instead of 3 days, there was no problem detected over 20000+ overflows. Before, a substantial fraction (much greater than 10%) of overflows failed.

If a user program carefully avoids calling any time-related function for over 1.5 days, it's possible that an overflow would get lost with the new formulation.

Fixes #5985

Change to common-hal/rtc/RTC.c for time warping (plus make rtc_old_count non-static):
```patch
 void common_hal_rtc_set_calibration(int calibration) {
+    common_hal_mcu_disable_interrupts();
+
+    RTC->MODE0.COUNT.reg = 0xffffff00;
+    rtc_old_count = 0;
+    do {
+        while ((RTC->MODE0.SYNCBUSY.reg & (RTC_MODE0_SYNCBUSY_COUNTSYNC | RTC_MODE0_SYNCBUSY_COUNT)) != 0) { }
+    }
+    while(RTC->MODE0.COUNT.reg < 0xffffff00);
+    common_hal_mcu_enable_interrupts();
+
+    mp_printf(&mp_plat_print, "Warping RTC in calibration setter count=%08x rtc_old_count=%08x\n", RTC->MODE0.COUNT.reg, rtc_old_count);
```

Test program:
```python
import time
from rtc import RTC

i = 0
while True:
    RTC().calibration = 1 # Warps to ~16ms before overflow, with patch to RTC code
    t0 = time.monotonic_ns()
    et = t0 + 20_000_000 # 20ms
    while (t1 := time.monotonic_ns()) < et: pass
    i += 1
    print(f"{i:6d}: duration {t1-t0}")
    if t1-t0 > 200_000_000: break
    print()
```

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks for your excellent sleuthing on this.

**Comment by jepler** [comment]
@jwfmcclain any chance you would be able to take a look at this possible fix for your issue?

**Comment by jwfmcclain** [comment]
@jepler, sure, but I think I need a some help finding the right build artifact (M4 Feather Express).

**Comment by dhalbert** [comment]
The artifacts are at the bottom of this page: https://github.com/adafruit/circuitpython/actions/runs/2041944567, but GitHub is having trouble right now. Here is a Feather M4 build; just unzip to get the UF2:
[fm46202.zip](https://github.com/adafruit/circuitpython/files/8354364/fm46202.zip)

**Comment by dhalbert** [comment]
@jepler I tested this on a CPX, using your test code above, with the `SYNCBUSY` part commented out. I stopped it after the last runs below. Looks OK, if I understand correctly. Looks like the problem is not present on SAMD21.
```
Warping RTC in calibration setter count=ffffff06 rtc_old_count=00000000
 18725: duration 20141596

Warping RTC in calibration setter count=ffffff06 rtc_old_count=00000000
 18726: duration 20080574

Warping RTC in calibration setter count=ffffff06 rtc_old_count=00000000
 18727: duration 22644032

Warping RTC in calibration setter count=ffffff05 rtc_old_count=00000000
 18728: duration 20080560

Warping RTC in calibration setter count=ffffff06 rtc_old_count=00000000
 18729: duration 20141596
```

**Comment by jepler** [comment]
@dhalbert that's good, thanks for testing! While I think there's still the very unlikely problem in the case that the time isn't checked for a whole 3-day roll-over (or maybe just a 1.5 day half roll-over, not sure) that an overflow is lost, the fix of adding any calls to `time.monotonic()` in the program, even at extremely low frequency, would be a good user workaround.

**Comment by jwfmcclain** [comment]
Sorry, I didn't see Dan's message until this morning. Have both my M4 running the alpha code now

```
pi@serialpi:~ $ more /media/CIRCUITPY/boot_out.txt 
Adafruit CircuitPython 7.3.0-alpha.0-63-g372306411-dirty on 2022-03-25; Adafruit Feather M4 Express with samd51j19
Board ID:feather_m4_express
pi@serialpi:~ $ 
```

**Comment by dhalbert** [comment]
@jwfmcclain Did you see any issues yet? Maybe no new is good news :) .

**Comment by dhalbert** [comment]
Merging this to get it in. Will revisit if necessary.

**Comment by jwfmcclain** [comment]
_greps log files_

@dhalbert -- no sign of the problem with the `7.3.0-alpha.0-63-g372306411-dirty` build

Thanks

**Comment by jwfmcclain** [comment]
Still no signs of the problem while using 7.3.0-alpha.0-63-g372306411-dirty ... looking forward to 7.3

**Pull request merged**
