### PR TITLE
ulab: enable on most builds

### PR DESCRIPTION
**Pull request by jepler**
testing performed on stm32 feather, spresense, teensy 4.0:
```
>>> import ulab, ulab.numerical; ulab.numerical.sum(ulab.ones(10))
10.0
```

### CODE REVIEW

**Comment by ladyada** [comment]
awww yeah! this is rad - great for doing faster number/array/fft/convolution crunchin' on circuitpython :) taggin @paulstoffregen & @arturo182 to check out the new builds under the Actions->artifacts

https://github.com/adafruit/circuitpython/actions/runs/52529321

**Comment by jepler** [comment]
once the CI run is done I will add an additional commit to disable ulab on specific boards where there is not enough code space available.

**Comment by jepler** [comment]
It *looks like* it's only M0 boards that failed, so I re-disabled this on them, I'll check back again later.

**Comment by kevinjwalters** [comment]
I just noticed `ulab` missing on STM32 based KittenBot Meowbit. Was that an oversight? I tacked the question on the end of: [Adafruit Forums: Is memory set correctly for KittenBot Meowbit?
](https://forums.adafruit.com/viewtopic.php?f=60&t=179307).

**Comment by jepler** [comment]
See commit 70e978f48b587620bb1407d9717f0a8fc3d4cf26 -- I think this board has limited flash space.

**Comment by kevinjwalters** [comment]
@jepler I think it's 512kB with its STM32F401RET6, same as SAMD51?

**Comment by hierophect** [comment]
@kevinjwalters both thunderpacks are the F411CE, we don't support the STM32L series. The F401xE chips do have 512kB of flash, but we reserve 64 of it on the Meowbit for the UF2 bootloader, and the build itself takes up 367kB out of the 384kB remaining. Building with ULAB enabled shows an overflow of 56kB.

**Comment by hierophect** [comment]
wait, 512 - 64 is not 384. Let me check out the linker file.

**Comment by hierophect** [comment]
Oh, it's the dumb STM32 flash sector thing. STM32 has irregular flash sectors, and it's crucial for startup that the ISR vector table goes at the start of one. The bootloader takes up the first 64 bytes, but then the firmware ISR table has to reserve a whole 64 byte sector because there are no smaller ones left. We can manually pack libraries in there alongside it to free up space in the firmware sectors, which Micropython often does, but that's a trial and error process and wasn't done in this particular case - if enabling ULAB on the Meowbit is important to you, it's an approach you could try.

**Comment by kevinjwalters** [comment]
@hierophect Sounds murky, thanks for taking a look. I was just pondering getting [some code from the CLUE](https://www.youtube.com/watch?v=HZroEl_Y6d4) to work on the Meowbit as my friend's daughter has one.

**Pull request merged**
