### PR TITLE
restore nvm module

### PR DESCRIPTION
**Pull request by jepler**
Closes: #7013

### CODE REVIEW

**Comment by jepler** [comment]
sadly, it doesn't fit.

**Comment by dhalbert** [comment]
> sadly, it doesn't fit.

Let's make this draft and merge when it will fit.

**Comment by MicroDev1** [comment]
> sadly, it doesn't fit.

I turned off rainbowio on `arduino_zero` in my storage extension PR. https://github.com/adafruit/circuitpython/pull/7000/commits/f44288d58c78eb390d082d6672896535b2307b8e

**Review by MicroDev1 — COMMENTED** [review]
@dhalbert Your commit https://github.com/adafruit/circuitpython/pull/7014/commits/66f6d8efac085df1055ae0c7c489e48a43a47e36 includes esp-idf submodule update.

**Comment by dhalbert** [comment]
> @dhalbert Your commit [66f6d8e](https://github.com/adafruit/circuitpython/commit/66f6d8efac085df1055ae0c7c489e48a43a47e36) includes esp-idf submodule update.

Ugh, sorry, I was doing esp-idf bisecting in the same clone. Too much muscle memory: `git commit -a -m`  instead of `git commit -m`.

**Review by MicroDev1 — APPROVED** [review]

**Pull request merged**
