### PR TITLE
Espressif ESP32-S3 DevKitC-1-N32R8

### PR DESCRIPTION
**Pull request by anecdata**
Draft for now. I can't get it to build.

This is the board in the shop. It uses an ESP32-S3-WROOM-2 module. 32MB flash & 8MB PSRAM:
https://www.adafruit.com/product/5364

_edit:_ "it's complicated"? 
https://github.com/espressif/esp-idf/issues/7670

### CODE REVIEW

**Comment by kmatch98** [comment]
For what it’s worth, I tried the lates ESP IDF version and running `idf.py menuconfig` I only see an option for configuring a board with up to 16MB of flash.

**Comment by anecdata** [comment]
I had tried to flash N8R8 onto it before and it didn't work. Maybe some param I overlooked is different. But it will flash as a 16MB, so it's usable for now :-)
`Adafruit CircuitPython 7.2.0-alpha.2-23-gd4c2ffea2-dirty on 2022-02-14; ESP32-S3-DevKitC-1-N32ishR8 with ESP32S3`

**Comment by kylefmohr** [comment]
Any idea what next steps need to be done to get this working? @anecdata I also tried flashing the CircuitPython firmware for N8R8 on my N32R8 and got the same results, able to get to the REPL, but the CIRCUITPY drive doesn't show up.

**Comment by anecdata** [comment]
@kylefmohr All indications are that we are waiting for Espressif to complete the development discussed in the issue kmatch98 linked above.

**Comment by kmatch98** [comment]
Possibly some progress here: https://github.com/espressif/esp-idf/pull/7688

**Comment by kmatch98** [comment]
More progress here: https://github.com/espressif/esp-idf/commit/04959af6354ba28b5559f39ccb339b49521dc114

I did not verify whether this was backported to v4.4.

**Comment by anecdata** [comment]
There are indications 32MB+ support is merged into 4.4 (though not sure what snapshot we use). Taking out of draft to see what happens. This is only a test.

**Comment by tannewt** [comment]
> There are indications 32MB+ support is merged into 4.4 (though not sure what snapshot we use). Taking out of draft to see what happens. This is only a test.

We're using: https://github.com/adafruit/esp-idf/tree/circuitpython8

**Comment by tannewt** [comment]
@anecdata Do we have 32MB support now an updated version of the IDF? Or will we need IDF 5?

**Comment by anecdata** [comment]
I'm not really sure. If this is still our branch:
https://github.com/adafruit/esp-idf/tree/circuitpython8
We seem to be on 4.4.1?

igrr says [here](https://github.com/espressif/esp-idf/issues/8365#issuecomment-1089396309) that support is in 4.4.2.

espressif/esp-idf merged / closed  PR 7688 (link above) seems to be where the support is added. Issue 7670 is closed (link above), but oddly issue 8365 is still open (link above).

**Comment by dhalbert** [comment]
@anecdata The branch is now https://github.com/adafruit/esp-idf/tree/release/v4.4-circuitpython

**Comment by anecdata** [comment]
I see the "Update version to 4.4.2" comment there, so in theory it should work. I'm not set up to build and test for a while. Also very baffled about the conflicts... I thought I fixed it at one point (basically copying the then-new patterns), but there are a lot more diffs now that I don't grok at all. If someone else wants to jump in sooner, feel free.

**Comment by anecdata** [comment]
Thanks @MicroDev1!

**Comment by tannewt** [comment]
Does it work now?

**Comment by anecdata** [comment]
I may be flashing it wrong this time around, tried a few ways, but I get a boot loop:

> ESP-ROM:esp32s3-20210327
> Build:Mar 27 2021
> rst:0xc (RTC_SW_CPU_RST),boot:0x18 (SPI_FAST_FLASH_BOOT)
> Saved PC:0x421099f2
> SPIWP:0xee
> Octal Flash Mode Enabled
> For OPI Flash, Use Default Flash Boot Mode
> mode:SLOW_RD, clock div:2
> load:0x3fce3808,len:0x68
> load:0x403c9700,len:0x980
> load:0x403cc700,len:0x25a0
> entry 0x403c98a4

**Comment by MicroDev1** [comment]
@anecdata I just pushed a commit reverting flash mode back to `dio`, can you do a re-test.

**Comment by anecdata** [comment]
Still boot looping:

> ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x18 (SPI_FAST_FLASH_BOOT)
Saved PC:0x42109a36
SPIWP:0xee
Octal Flash Mode Enabled
For OPI Flash, Use Default Flash Boot Mode
mode:SLOW_RD, clock div:2
load:0x3fce3808,len:0x68
load:0x403c9700,len:0x980
load:0x403cc700,len:0x25a0
entry 0x403c98a4

The UART shows up correctly as `CP2102N USB to UART Bridge Controller`, but oddly the USB shows up as `USB JTAG/serial debug unit` (macOS). No REPL or CIRCUITPY.

**Comment by MicroDev1** [comment]
Does the `n8r8` definition still boot?
 The current board definition is basically the same as `n8r8` apart from obvious changes to accommodate `32MB` flash.

**Comment by anecdata** [comment]
The N8R8 `.bin` artifact also boot loops on the N32R8 board. I've tried two N32R8 boards, just to make sure one wasn't flaky. Something seems to have changed behind the scenes.

**Comment by jepler** [comment]
This might need to pull in https://github.com/espressif/esp-idf/pull/7688 to our esp-idf fork.

**Comment by MicroDev1** [comment]
> This might need to pull in https://github.com/espressif/esp-idf/pull/7688 to our esp-idf fork.

We now have those commits. This needs a re-test.

**Comment by dhalbert** [comment]
> We now have those commits. This needs a re-test.

I just ordered an ESP32-S3-DevKitC-1-N32R8 and should get it Friday or Saturday.

**Comment by anecdata** [comment]
Erased flash and loaded the `bin` with esptool.py v4.4. No CIRCUITPY, no REPL. It's boot looping.

The USB connector shows up as `USB JTAG/serial debug unit` (not good) and repeatedly displays:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x18 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4210b312
SPIWP:0xee
Octal Flash Mode Enabled
For OPI Flash, Use Default Flash Boot Mode
mode:SLOW_RD, clock div:2
load:0x3fce3808,len:0x68
load:0x403c9700,len:0x980
load:0x403cc700,len:0x2574
entry 0x403c98a4
```
The UART connector shows up as `CP2102N USB to UART Bridge Controller` (good) and repeatedly displays the same block as above.

N8R8 7.3.3 works as before (REPL, NO CIRCUITPY), N8R8 8.0.0-beta.6 also boot loops.

**Comment by dhalbert** [comment]
I got this branch and merged in the latest circuitpython `main`, which has the latest backports (as of late December) from `release/v4.4` in upstream. I erased flash and loaded the .bin. I get:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4210b566
SPIWP:0xee
Octal Flash Mode Enabled
For OPI Flash, Use Default Flash Boot Mode
mode:SLOW_RD, clock div:1
load:0x3fce3808,len:0x68
load:0x403c9700,len:0x980
load:0x403cc700,len:0x2574
SHA-256 comparison failed:
Calculated: d29ccdcc77968ff92a65aee87c562181025845513a5a17824c6a3facb469294c
Expected: d31b4e85d9f427cf4d4bd360a1cd8fa68cec4a669bda0cf6356a4042625dd388
Attempting to boot anyway...
entry 0x403c98a4
```
and it boot loops.

**Comment by dhalbert** [comment]
I'm going to push this to 8.x.x unless we figure something out. It is not urgent for 8.0.0.

**Comment by MicroDev1** [comment]
Switched the flash mode to `dout`:
```py
# Note: we use esptool.py to flash bootloader in
# dio mode for QIO/QOUT, bootloader then upgrades
# itself to quad mode during initialisation
config ESPTOOLPY_FLASHMODE
    string
    default "dio" if ESPTOOLPY_FLASHMODE_QIO
    default "dio" if ESPTOOLPY_FLASHMODE_QOUT
    default "dio" if ESPTOOLPY_FLASHMODE_DIO
    default "dout" if ESPTOOLPY_FLASHMODE_DOUT
    # The 1st and 2nd bootloader doesn't support opi mode,
    # using fastrd instead. For now the ESPTOOL doesn't support
    # fasted (see ESPTOOL-274), using dout instead. In ROM the flash mode
    # information get from efuse, so don't care this dout choice.
    default "dout" if ESPTOOLPY_FLASHMODE_OPI
```

**Comment by anecdata** [comment]
🎉REPL _and_ CIRCUITPY 🎉
```py
Adafruit CircuitPython 8.0.0-beta.6-63-gb8fa2c641-dirty on 2023-01-28; ESP32-S3-DevKitC-1-N32R8 with ESP32S3
>>> import os
>>> os.statvfs("/")
(2048, 2048, 15176, 15172, 15172, 0, 0, 0, 0, 255)
```

**Review by dhalbert — APPROVED** [review]
Thank you @MicroDev1, and thanks @anecdata for the final test!

**Pull request merged**
