### PR TITLE
[audiocore] `buffer_read` was never used

### PR DESCRIPTION
**Pull request by tyomitch**

### CODE REVIEW

**Comment by dhalbert** [comment]
@tyomitch Are you doing a by-hand code audit, or are you using a tool? Could you consolidate these into one or a few PR's? Thanks. Each PR generates about 40 minutes of CI time.

**Review by jepler — APPROVED** [review]
If this change compiles, it seems like it has to be right.

**Comment by jepler** [comment]
Thank you

**Comment by tyomitch** [comment]
> @tyomitch Are you doing a by-hand code audit, or are you using a tool?

That was not intended as a code audit; just the few rough spots I came across while working on  #4399

**Pull request merged**
