### PR TITLE
add Port of Sunton esp32 8048S050

### PR DESCRIPTION
**Pull request by sanhu88**
sunton_esp32_8048S050 ，Similar to sunton_esp32_8048S070, but with a 5-inch screen.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by sandzco** [comment]
Can you help change the board.TFT_TIMINGS["frequency"] to 16000000? Having 12500000 is making the board display a white screen in the ESP32-8048S050C_I. Can I assign this value at startup?
I compared and tested the factory default program with 12.5M value in Arduino IDE, it is having the same effect. Please help change this to 16M

**Comment by dhalbert** [comment]
@sandzco Here is a build that changes the display SPI frequency to 16 MHz. Could you test it? You'll need to unzip it first.
[sunton_esp32_8048S050-16MHz-display.zip](https://github.com/user-attachments/files/18235075/sunton_esp32_8048S050-16MHz-display.zip)

**Comment by sandzco** [comment]
@dhalbert It worked like a charm! 
Not sure if I am at fault or if this is a new version, I bought this from Guiton store instead of Sunton. Thanks for the files!

**Pull request merged**
