### PR TITLE
Add PWM based audio playback

### LINKED ISSUE #4037: Implement audiopwmio and enable audiocore

### PR DESCRIPTION
**Pull request by tannewt**
See
https://learn.adafruit.com/circuitpython-essentials/circuitpython-audio-out
to get started.

Fixes #4037

### CODE REVIEW

**Comment by ladyada** [comment]
tested, works pretty well!

**Comment by kevinjwalters** [comment]
Will stereo playback of samples work ok?

**Comment by tannewt** [comment]
> Will stereo playback of samples work ok?

Yes, it should work. The pins need to share a PWM slice under the hood.

**Comment by kevinjwalters** [comment]
I saw #4143 but haven't yet worked out exactly what's going on there, is that related to this? Is there anything simple that documents "the slices" or is in the monster datasheet?

**Comment by tannewt** [comment]
> I saw #4143 but haven't yet worked out exactly what's going on there, is that related to this?

This bug is fixed in main. (I'll close shortly.)

> Is there anything simple that documents "the slices" or is in the monster datasheet?

It's in the pin function section. It's simple though. The slice is pin number / 2 % 8 and the channel is pin number %2. In words, starting at zero the next two pins share a slice, then the next two do and so forth until pin 16 which starts the pattern again.

> A cytron maker board is on the way to me which uses GP18 and GP19 for stereo audio.

That should work. It will block PWM on pins GP2 and GP3 though.

**Review by jepler — APPROVED** [review]
No problems spotted, but I didn't do any testing.  (@ladyada did but didn't formally review the PR)

It's a bummer that the audio sample converter APIs I added didn't work out to use here, but I see why it wasn't used.

**Comment by tannewt** [comment]
What converter APIs? Please open a long term issue for us to unify buffer conversion. This DMA stuff is too tied to buffer conversion at the moment.

**Comment by jepler** [comment]
```
void audiosample_convert_u8m_s16s(int16_t *buffer_out, const uint8_t *buffer_in, size_t nframes);
void audiosample_convert_u8s_s16s(int16_t *buffer_out, const uint8_t *buffer_in, size_t nframes);
void audiosample_convert_s8m_s16s(int16_t *buffer_out, const int8_t *buffer_in, size_t nframes);
void audiosample_convert_s8s_s16s(int16_t *buffer_out, const int8_t *buffer_in, size_t nframes);
void audiosample_convert_u16m_s16s(int16_t *buffer_out, const uint16_t *buffer_in, size_t nframes);
void audiosample_convert_u16s_s16s(int16_t *buffer_out, const uint16_t *buffer_in, size_t nframes);
void audiosample_convert_s16m_s16s(int16_t *buffer_out, const int16_t *buffer_in, size_t nframes);
```
there are a bunch of these, for converting bit count, signedness, and mono-to-stereo.  Declared in **shared-module/audiocore/__init__.h**.

**Comment by kevinjwalters** [comment]
I just ran this

```
Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Raspberry Pi Pico with rp2040
>>> import pwmio
>>> import board
>>> pins = (board.GP0, board.GP1, board.GP2, board.GP3,
... board.GP4, board.GP5, board.GP6, board.GP7,
... board.GP8, board.GP9, board.GP10, board.GP11,
... board.GP12, board.GP13, board.GP14, board.GP15)
>>> pwms = [pwmio.PWMOut(p, frequency=2000, duty_cycle=3456) for p in pins]
```

On Cytron Maker Pi Pico which has LEDs on the pins. Even numbered ones light up, odd numbered ones stay off.  

```
>>> pwms[1].duty_cycle = 65534
>>> pwms[1].duty_cycle = 65535
```

That don't help. Is this a bug?

**Comment by kevinjwalters** [comment]
I can't find libraries which hold `PWMAudioOut` and `WaveFile` on `6.2.0-beta.2`:

```
Adafruit CircuitPython 6.2.0-beta.2 on 2021-02-11; Raspberry Pi Pico with rp2040
>>> import audiocore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'audiocore'
>>> import audiopwmio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'audiopwmio'
```

**Comment by tannewt** [comment]
@kevinjwalters Please file new issues that refer to a PR. Discussion on a merged PR is hard to track.

(For those following along, the library finding issue was due to this PR not being in beta.2. It was merged after and is available in "absolute newest" builds.)

**Pull request merged**
