### PR TITLE
Silabs' new Pull Request for submoduling the ports/silabs/tools/slc_cli_linux/

### PR DESCRIPTION
**Pull request by silabs-BelaV**
In the https://github.com/adafruit/circuitpython/pull/7833, the following were commented:
"The ports/silabs/tools/slc_cli_linux/* files were 150MB. That is much larger than anything else in this repo. We would really like these files to be somewhere else."
We are submoduling the ports/silabs/tools/slc_cli_linux/

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thank you for your patience with this, and for doing the submoduling. This PR does still have at least one commit (50d82ef30e9392186dd43a449429d48c5277664d) in it that adds the original .zip files (and then one that takes them away). So after a regular merge, the intermediate commit will still be in the history, and the .zip files will be part of the history, and will get fetched when the rjepo is cloned.

I think we could do a squash merge (these are currently disabled on this repo), and get rid of the intermediate commits. Or you could do a squash rebase in your current branch and then make a new PR. How comfortable do you feel about either of these?

It's good to create a branch for all PR's, instead of working in `main`. That way your `main` does not get out of sync with upstream main. (https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github/always-work-on-a-branch)

**Comment by dhalbert** [comment]
Brought this in up in our discord #help-with-git: https://discord.com/channels/327254708534116352/763904151155245066/1097885610133422120

**Comment by dhalbert** [comment]
Don't do extra work yet, because I think the squash merge on our end may be easiest, once I confirm it's OK.

**Comment by dhalbert** [comment]
I did a test build and got this error. Only extra thing I did beforehand was `sudo apt install default-jre`, on Ubuntu 22.04.
```
...
arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -T"build-devkit_xg24_brd2601b/autogen/linkerfile.ld" --specs=nano.specs -Xlinker -Map=build-devkit_xg24_brd2601b/circuitpython_efr32.map -Wl,--gc-sections @build-devkit_xg24_brd2601b/linker_objs -Wl,--start-group -lgcc -lc -lm -lnosys /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/radio/rail_lib/autogen/librail_release/librail_multiprotocol_efr32xg24_gcc_release.a -Wl,--end-group -o build-devkit_xg24_brd2601b/firmware.out
/home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a: file format not recognized; treating as linker script
/home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a:1: syntax error
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:150: build-devkit_xg24_brd2601b/firmware.out] Error 1
make: *** [Makefile:141: build-devkit_xg24_brd2601b/firmware.bin] Error 2
```

**Comment by ChatNV** [comment]
> I did a test build and got this error. Only extra thing I did beforehand was `sudo apt install default-jre`, on Ubuntu 22.04.
> 
> ```
> ...
> arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -T"build-devkit_xg24_brd2601b/autogen/linkerfile.ld" --specs=nano.specs -Xlinker -Map=build-devkit_xg24_brd2601b/circuitpython_efr32.map -Wl,--gc-sections @build-devkit_xg24_brd2601b/linker_objs -Wl,--start-group -lgcc -lc -lm -lnosys /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/radio/rail_lib/autogen/librail_release/librail_multiprotocol_efr32xg24_gcc_release.a -Wl,--end-group -o build-devkit_xg24_brd2601b/firmware.out
> /home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a: file format not recognized; treating as linker script
> /home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a:1: syntax error
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:150: build-devkit_xg24_brd2601b/firmware.out] Error 1
> make: *** [Makefile:141: build-devkit_xg24_brd2601b/firmware.bin] Error 2
> ```
@dhalbert  Have problem when cloning libbluetooth.a file.
You should install git LFS before cloning submodule gecko_sdk

**Comment by silabs-ChatNguyen** [comment]
> I did a test build and got this error. Only extra thing I did beforehand was `sudo apt install default-jre`, on Ubuntu 22.04.
> 
> ```
> ...
> arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -T"build-devkit_xg24_brd2601b/autogen/linkerfile.ld" --specs=nano.specs -Xlinker -Map=build-devkit_xg24_brd2601b/circuitpython_efr32.map -Wl,--gc-sections @build-devkit_xg24_brd2601b/linker_objs -Wl,--start-group -lgcc -lc -lm -lnosys /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a /home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/platform/radio/rail_lib/autogen/librail_release/librail_multiprotocol_efr32xg24_gcc_release.a -Wl,--end-group -o build-devkit_xg24_brd2601b/firmware.out
> /home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a: file format not recognized; treating as linker script
> /home/halbert/bin/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/halbert/repos/adafruit/scircuitpython/ports/silabs/gecko_sdk/protocol/bluetooth/lib/EFR32MG24/GCC/libbluetooth.a:1: syntax error
> collect2: error: ld returned 1 exit status
> make[1]: *** [Makefile:150: build-devkit_xg24_brd2601b/firmware.out] Error 1
> make: *** [Makefile:141: build-devkit_xg24_brd2601b/firmware.bin] Error 2
> ```

@dhalbert  Have problem when cloning libbluetooth.a file.
You should install git LFS before cloning submodule gecko_sdk

**Comment by dhalbert** [comment]
All set, built successfully, thanks!

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
