### PR TITLE
Add Italian translation

### PR DESCRIPTION
**Pull request by platipo**
Adding draft, it needs to be reviewed. 
Anyway I managed to translate all strings but 58 that I couldn't found a fitting expression so I let those blank.

See #1226.

### CODE REVIEW

**Comment by dhalbert** [comment]
Could you merge the latest and run `make translate` again? Build is failing with "message message ID".

**Comment by platipo** [comment]
I rebased the commit and run `make check-translate` and `make translations`, neither of them raised errors on my computer

**Comment by platipo** [comment]
It seemed that when I started the translation there was an extra line
```po
#: ports/nrf/common-hal/busio/SPI.c:170
msgid "Baud rate too high for this SPI peripheral"
msgstr "Baudrate troppo alto per questa periferica SPI"
```
And the script detected only the difference between the two, wouldn't it be more informative to do just:
```bash
for trans in $(ls locale/*.po); do
    diff <(grep "^msgid" locale/circuitpython.pot) <(grep "^msgid" $trans)
done
```

**Comment by tannewt** [comment]
Great job translating all of these messages! Leaving some blank is fine. This is a great start.

Looks like the build is failing due to a missing line ending: https://travis-ci.org/adafruit/circuitpython/jobs/438210422#L711

I don't think the diff command will find all cases because msgids can wrap on multiple lines. The python script should be able to detect it though.

**Pull request merged**
