### PR TITLE
Permit Gameduino 3X Dazzler support on Metro M4 AirLift Lite.

### PR DESCRIPTION
**Pull request by dglaude**
Totally untested, change request based on change made in #2581.
It might be my first PR in CircuitPython core...
Maybe this should be confirmed by @jamesbowman

Those are the two boards that seems supported:
* Metro M4 Express
* Metro nRF52840 Express

The only Metro that this PR concern:
* Metro M4 AirLift Lite

Other Metro I found and are maybe not supported:
* Metro ESP32-S2
* Metro M0 Express
* Metro M7 1011

### CODE REVIEW

**Comment by dglaude** [comment]
I do not fully master the Gameduino yet, but now I can run my test code without _eve.py and the benchmark goes much faster when using the artefact from this PR:

```
code.py output:
0.0922852
1000 points took 92.3 ms
```

VS what I have with the current firmware without this PR included.

```
code.py output:
0.454002
1000 points took 454.0 ms
```

**Review by tannewt — APPROVED** [review]
Thanks @dglaude. Feel free to enable it on others in a follow up PR.

**Comment by dglaude** [comment]
> Thanks @dglaude. Feel free to enable it on others in a follow up PR.

I don't have any other Metro board... I can try to write a PR, but no way to test the result.
Please advise if you want me to try.

**Comment by tannewt** [comment]
@dglaude No need. This is a good example for anyone who wants it on another metro. Thanks!

**Comment by jamesbowman** [comment]
@tannewt I enabled it for my raspberry_pi_pico. Works great. Is that possible?

**Comment by tannewt** [comment]
@jamesbowman Totally, just make a PR for it.

**Pull request merged**
