### PR TITLE
feat: Add support for Waveshare RP2040-LCD-1.28

### PR DESCRIPTION
**Pull request by fonix232**
Initial support for [Waveshare RP2040-LCD-1.28](https://www.waveshare.com/wiki/RP2040-LCD-1.28)

Testing underway.

Features:
- GC9A01A LCD controller, with a 240x240 circular LCD display, over SPI
- QMI8658C IMU, accelerometer and gyroscope, over I2C
- 2MB flash (W25Q32JVSSIQ according to schematics, but that's a 4MB flash)
- PH1.25-2P battery connector, with an ETA6096 battery charge/discharge controller
- VBAT is hooked up to GPIO 29 with a 0.50 bias via resistors

TODO:
- CircuitPython driver for GC9A01A
- CircuitPython driver for QMI8658C
- Investigate flash size inconsistencies (board doesn't seem to have any flash chips)
- Investigate schematic's three `S_KEY_` definitions (`UP`, `DOWN` and `CENTER`)

Schematics: https://www.waveshare.com/w/upload/6/60/RP2040-LCD-1.28-sch.pdf

### CODE REVIEW

**Comment by LazaroFilm** [comment]
When can this be added? I just bought this board for a project and going with CircuitPython would be great.

**Comment by tannewt** [comment]
@fonix232 Please let us know when this is ready for review.

@LazaroFilm You can help test using "artifacts" from the CI run. See the bottom artifact here: https://github.com/adafruit/circuitpython/actions/runs/3352586595

**Comment by tannewt** [comment]
> Digging further I cannot find the PID for this board on this page: https://github.com/raspberrypi/usb-pid

Good eye! Looks like it'll need to be requested like other Waveshare boards have.

**Comment by LazaroFilm** [comment]
I have issued a ticket on Waveshare's website requesting for the PID#. We'll see.

**Comment by fonix232** [comment]
@tannewt I've opened this as a draft due to not having an opportunity to test it thoroughly.

The PID/VID used in this PR is taken from the device as-is, running the factory firmware OOTB. If that's not appropriate (I was hoping it would be), then I'm open to suggestions on how to proceed, as well as to changes to the current code.

**Comment by tannewt** [comment]
> The PID/VID used in this PR is taken from the device as-is, running the factory firmware OOTB. If that's not appropriate (I was hoping it would be), then I'm open to suggestions on how to proceed, as well as to changes to the current code.

That PID is marked for the Pico rather than a waveshare board. It looks like they've requested PIDs for other boards so hopefully they will for this one too.

**Comment by LazaroFilm** [comment]
Yes they used the default Pico PID. The problem is that it conflicts in VSCODE plug-in as it's detected to have a different name than the pico with à pico PID which crashes the vscode plugin (in my opinion, that plug-in could benefit from a refactor to avoid crashing in this instance, it's a bit too strict of a PID check)

**Comment by LazaroFilm** [comment]
UPDATE: Waveshare had replied to me but my mail considered it as spam. Here is the email:
```

Waveshare Support (Waveshare)
Nov 21, 2022, 14:18 GMT+8

Hi,

Sorry for replying late.
We have approved your USB PID application for "RP2040-LCD-1.28"
Vendor ID = 0x2E8A
Product ID = 0x1039
See: https://github.com/raspberrypi/usb-pid
The table will be updated soon

```

**Comment by tannewt** [comment]
Glad they got one! I'd like to wait until the listing is public because I've had other folks get it wrong.

**Comment by fonix232** [comment]
@tannewt the listing should be public now (the LCD-1.28 is listed but without URL). I've updated the PR with it, should be merge-able (even with the missing drivers for QMI8658 and GC9A01).

**Review by tannewt — APPROVED** [review]
Thank you for your patience!

**Pull request merged**
