### PR TITLE
Add cp sapling rev b

### PR DESCRIPTION
**Pull request by skerr92**
Creating a draft PR for the CP Sapling Rev B board. Will update to open once I can confirm all changes.

### CODE REVIEW

**Comment by skerr92** [comment]
PID pending on Pid.Codes --> [PID Codes PID PR](https://github.com/pidcodes/pidcodes.github.com/pull/642)

**Comment by skerr92** [comment]
This is failing on the Japanese language build. Not sure why it ends up being bigger than the on board flash.. will need to investigate this...

**Comment by ladyada** [comment]
you can add a `CFLAGS_INLINE_LIMIT = 35` for japanese too

**Comment by skerr92** [comment]
> you can add a `CFLAGS_INLINE_LIMIT = 35` for japanese too

Not sure why when I added that flag it was still failing. I ended up looking at the Qt Py M0 mpconfigboard.mk file and matching that and it's built without issue. not sure what the reasoning for that ends up being.

**Review by gamblor21 — APPROVED** [review]
Looks good to me

**Pull request merged**
