### PR TITLE
Add UART subclassing

### PR DESCRIPTION
**Pull request by AdamCummick**
Corrects for bug found in #3897 

Adds subclassing functionality based on the implementation in "Group". Please take a look to make sure nothing was missed.

Quick test script I used to verify on a SAMD51 based board
```py
import board
import busio

class uart_subclass(busio.UART):
        def __init__(self, tx: microcontroller.Pin, rx: microcontroller.Pin, *, baudrate: int = 9600, bits: int = 8, parity: Optional[Parity] = None, stop: int = 1, timeout: float = 1, receiver_buffer_size: int = 64):
            super().__init__(tx, rx, baudrate=baudrate, bits=bits, parity=parity, stop=stop, timeout=timeout, receiver_buffer_size=receiver_buffer_size) 

        def subclass_method():
            print("cool method, right?")


msg = b'hello'

normal = busio.UART(board.TX1, board.RX1)
normal_dir = dir(normal)
normal.write(msg)
assert normal.read(len(msg)) == msg, "Normal did not echo"
normal.deinit()

subclass_uart = uart_subclass(board.TX1, board.RX1)
subclass_dir = dir(subclass_uart)
subclass_uart.write(msg)
assert subclass_uart.read(len(msg)) == msg, "Subclass did not echo"
subclass_uart.deinit()


print(normal_dir)
print(subclass_dir)
print("\nDone")

```

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
I don't see any issue with the code but we've run out of space in a few builds unfortunately. I wonder if we could make a shared `native_struct` function.

**Comment by dhalbert** [comment]
I shrank a number of builds and will try a re-run.

**Comment by AdamCummick** [comment]
> I shrank a number of builds and will try a re-run.

@dhalbert It doesn't look the pipeline ran again. Anything I need to do?

**Comment by dhalbert** [comment]
I think a did a re-run but it failed. I don't see a "Re-run" button anymore, maybe because it's too old. Could you merge from upstram and push a new commit?

**Review by tannewt — APPROVED** [review]
Thanks @AdamCummick and @microDev1

**Pull request merged**
