### PR TITLE
ulab: Get updates from upstream

### PR DESCRIPTION
**Pull request by jepler**
This has about 15 enhancements and bug fixes, mostly from @v923z.  It removes the two "known problems" we mentioned in the 5.1.0 and 5.2.0 release notes.

### CODE REVIEW

**Comment by tannewt** [comment]
Changes look ok. Needs a CI poke.

**Comment by jepler** [comment]
Complicating things, I think it was based off an old ref rather than master.  Rebased and force-pushed, which will give Actions a fresh crack at it.

**Comment by v923z** [comment]
@jepler https://github.com/v923z/micropython-ulab/pull/96 fixes a bug in the `dot` function, in case you want to pull it in.

**Comment by jepler** [comment]
Updated to include v923z/micropython-ulab#96.

**Comment by tannewt** [comment]
Unix port isn't building to run the tests.

**Pull request merged**
