### PR TITLE
Enable the PWM status LED on Pimoroni Tiny 2040 and PicoSystem

### PR DESCRIPTION
**Pull request by Neradoc**
Found no info on the PicoSystem pwm LED, let's assume it's inverted too until further notice.

### CODE REVIEW

**Comment by dhalbert** [comment]
@ZodiusInfuser Do you have details on the RGB LEDs on these boards?

**Comment by ZodiusInfuser** [comment]
@dhalbert Yes, both boards have a common anode RGB LED, so pins need to be active low.

Do the config changes proposed here allow for that? I am unclear why the pin defines were changed from `#define MICROPY_HW_LED_G (&pin_GPIO13)` to `#define CIRCUITPY_RGB_STATUS_G (&pin_GPIO13)`

**Comment by Neradoc** [comment]
Yeah the code was tested on the Tiny2040, it blinks as expected from #4743 
The defines were changed from `CP_RGB_STATUS_G` to `CIRCUITPY_RGB_STATUS_G` in it. I can't find any reference to `MICROPY_HW_LED_G` in Circuitpython (which explains why it wasn't updated with the others).

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Comment by tannewt** [comment]
@ZodiusInfuser I'm not sure they worked as-is. I think this will make it work.

**Pull request merged**
