### PR TITLE
update certificates to nina-fw 1.7.5

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by jepler** [comment]
ping @brentru

**Comment by brentru** [comment]
@jepler  Looks good, includes the new IO SSL Cert.

**Comment by dhalbert** [comment]
Could you test connection to AdafruitIO with a new build? Thanks.

**Comment by brentru** [comment]
@dhalbert  Do pull requests in this repository produce UF2 builds?

**Comment by anecdata** [comment]
@brentru In the "Checks" tab, select "Build CI" and find an esp32s2 board you have. The download will contain both `.bin` and `.uf2` firmware.

**Comment by brentru** [comment]
@dhalbert @jepler  IO Connection is OK,

Testing on `Adafruit CircuitPython 8.2.1-1-g82c429f714 on 2023-07-28; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3`


[Adafruit IO Test](https://learn.adafruit.com/adafruit-esp32-s3-feather/adafruit-io-send-and-receive-data)
```
Connecting to Adafruit IO...
Connected to Adafruit IO!  Listening for NeoPixel changes...
Current 'random' number: 91
Current 'random' number: 103
Feed neopixel received new value: hello
```

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
