### PR TITLE
keeping travis happy (with proper load-leveling)

### PR DESCRIPTION
**Pull request by maholli**
New PR due to something weird I did with the fork.

Added new board to proper Travis build.

### CODE REVIEW

**Comment by tannewt** [comment]
Looks like you needed to `git submodule sync && git submodule update --init --recursive .`

**Comment by tannewt** [comment]
I'm going to finish this so it gets into beta.7.

**Comment by maholli** [comment]
> 
> 
> I'm going to finish this so it gets into beta.7.

Thank you for finishing this up!

**Comment by tannewt** [comment]
@maholli No problem! I removed displayio support to get it to build with other translations.

**Pull request merged**
