### PR TITLE
Add new board: WIZnet W5100S EVB Pico2 (RP2350)

### PR DESCRIPTION
**Pull request by anecdata**
Also add `ssl` module to WIZnet W5100S EVB Pico (RP2040) board (per https://github.com/adafruit/circuitpython/pull/8954#issuecomment-2077738376)

### CODE REVIEW

**Comment by anecdata** [comment]
Tested `adafruit_requests` with `ssl` over Ethernet on:

- Adafruit CircuitPython 9.2.0-11-g1b8baca968 on 2024-11-04; W5100S-EVB-Pico with rp2040 (1st commit)
- Adafruit CircuitPython 9.2.0-12-g1bba7b9d14 on 2024-11-05; W5100S-EVB-Pico2 with rp2350a (2nd commit)

**Comment by anecdata** [comment]
@ViktorWiz Any comments on this? I noticed you did the original PRs for the W5500 and W5100S EVB Picos.

**Review by jepler — APPROVED** [review]
no hw so didn't test but everything looks in order from a quality standpoint. Thank you!

**Comment by anecdata** [comment]
I think this can be merged. If anything comes up, it should be straightforward to PR.

**Pull request merged**
