### PR TITLE
Update built-in help output for localization (Issue #3907)

### PR DESCRIPTION
**Pull request by hugodahl**
Adding localization values for the output of calls to help(<object>) can match the current firmware's language.

This change addresses issue #3907

n.b.: This is a recreation of PR #3908 since ran into issues with my previous local branch. Apologies for the noise and mess.

### CODE REVIEW

**Review by tannewt — DISMISSED** [review]
Thank you! I'd love to find a way to do the full help text too. I ran into an issue that gettext can't find the multiline contents when I tried before.

**Comment by hugodahl** [comment]
I'm certainly not an expert on GetText, but from what I've run into with other systems in the past, I suspect it might have to do with the default locale text being the key. So say the text is `"This help text spans\nmultiple lines"`, it might be transforming that into something like `"This help text spans\\nmultiple lines"`, some form of truncation or perhaps some other mutilation. Or it might just make a mess of itself and move on.

Ideally, the key text would be a simple string that the system doesn't have a chance (or need) to transform in any way. For example, using the message "division by zero". Within the code itself, in its place would be "DIVISION_BY_ZERO" or some other agreed-upon formatted text.

For a more complex example, using this string: 

"<br>
Please file an issue with the contents of your CIRCUITPY drive at 
https://github.com/adafruit/circuitpython/issues"

Its key could be something like "GITHUB_ISSUE_WITH_CONTENTS". That would require a good amount of refactoring, including creating the English "Translation", and ensuring that the builds for the `en` locale apply the text as appropriate. The upside is, it gets to be immediately obvious if there's an untranslated string. Particularly if a translation rule can be created, something like `[A-Za-z0-9][A-Za-z0-9_-]{4,}` to ensure both style, format and other rules (minimum length, etc).

**Comment by tannewt** [comment]
> Its key could be something like "GITHUB_ISSUE_WITH_CONTENTS". That would require a good amount of refactoring, including creating the English "Translation", and ensuring that the builds for the `en` locale apply the text as appropriate. The upside is, it gets to be immediately obvious if there's an untranslated string. Particularly if a translation rule can be created, something like `[A-Za-z0-9][A-Za-z0-9_-]{4,}` to ensure both style, format and other rules (minimum length, etc).

This is fine with me if you want to switch it to this!

**Comment by tannewt** [comment]
Please update the .pot again. I've merged lots of things in. Thanks!

**Comment by hugodahl** [comment]
Merged, although that was an odd conflict. Waiting for the checks to complete

**Comment by tannewt** [comment]
@dhalbert should these boards build now?

**Comment by dhalbert** [comment]
Yes, I will re-run

**Comment by dhalbert** [comment]
I would like to hold off on this PR for 6.1.0-beta.0. A number of de_DE builds are overflowing by small amounts. It would be nice to find some savings somewhere rather than radically shrink these builds, or do special de_DE builds.

**Comment by dhalbert** [comment]
> I would like to hold off on this PR for 6.1.0-beta.0. A number of de_DE builds are overflowing by small amounts. It would be nice to find some savings somewhere rather than radically shrink these builds, or do special de_DE builds.

This is not as complicated as I thought. I think I have the fixes I need.

**Review by dhalbert — APPROVED** [review]
All set! Thanks!

**Pull request merged**
