### PR TITLE
Update 42. Keebs Frood support for Rev7

### PR DESCRIPTION
**Pull request by piit79**
42. Keebs Frood Rev7 uses a new 4 MB flash chip (Winbond W25Q32JVUUIQ)

### CODE REVIEW

**Review by jepler — CHANGES_REQUESTED** [review]
I think you need to list the flash chip of all revisions here, separated by commas:
```
EXTERNAL_FLASH_DEVICES = "ZD25WQ16B, W25Q64JVxQ"
```
Otherwise, I think that running this on an older revision board with the ZD... chip would fail.

Typical example from an adafruit board:
```
ports/atmel-samd/boards/circuitplayground_express/mpconfigboard.mk:EXTERNAL_FLASH_DEVICES = "S25FL216K, GD25Q16C"
```

The syntax seems to be written `"A","B"` in some places and `"A, B"` in others. I'd use the syntax shown above.

**Comment by dhalbert** [comment]
W25Q64JVUUIQ is 8MB (64 Mbit). This new build will not work on the old boards with 2MB flash. Or are there no old boards?

**Comment by piit79** [comment]
Thanks @jepler, I had no idea I could do that! The firmware indeed works with both the new (Winbond) and the old (Zetta) revisions.

**Comment by piit79** [comment]
Thanks for spotting that, @dhalbert - I copied the wrong device identifier. The latest revision of my board uses W25Q32JVUUIQ, a 4 MB chip.

Funnily enough CircuitPython did actually work with the wrong second device identifier on both the old (2 MB) and the new (4 MB) boards...

**Pull request merged**
