### PR TITLE
Added board definition for upcoming 2MB variant of the Pimoroni Tiny 2040

### PR DESCRIPTION
**Pull request by ZodiusInfuser**
Also, updated the display name of the current Tiny 2040 to clarify it is 8MB.

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
Raised PR for the website too: https://github.com/adafruit/circuitpython-org/pull/808

**Review by tannewt — APPROVED** [review]
Thank you! If both the 8mb and 2mb are winbond chips, the builds may work across versions because the rp2 port detects the flash size.

**Comment by ZodiusInfuser** [comment]
Thanks Scott! They are both Winbond chips, but the codes are different so I thought that meant they were incompatible so went for a separate entry. 2MB has the code W25Q16JVxQ (same as the Pi Pico) whereas the 8MB has W25Q64JVxQ. Should the designation be changed to something like W25QxJVxQ going forward?

**Comment by tannewt** [comment]
I think a separate entry will still be clearer.

We'll want to keep the designation the same because some ports do need the size. Instead, `EXTERNAL_FLASH_DEVICES` can be a comma separated list of flashes and the stage2 script should determine a compatible config for both. See https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/boards/arduino_nano_rp2040_connect/mpconfigboard.mk#L10

**Pull request merged**
