### PR TITLE
STM: monotonic time even when RTC is changed

### LINKED ISSUE #7808: Setting the rtc on STM32 affects the value of time.monotonic()
### CircuitPython version

```python
Adafruit CircuitPython 8.0.4 on 2023-03-15; Adafruit Feather STM32F405 Express with STM32F405RG
```

### Code/REPL

```python
>>> import time
>>> import rtc
>>> r = rtc.RTC()
>>> time.monotonic()
30.029
>>> r.datetime = time.localtime(1680048046)
>>> time.monotonic()
7.33363e+08
>>> time.localtime(time.time() - int(time.monotonic()))
struct_time(tm_year=2000, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=0, tm_sec=59, tm_wday=5, tm_yday=1, tm_isdst=-1)
>>> time.monotonic_ns()
733363727297363288
```

### Behavior

Or in other words, `time.monotonic()` returns the time between `time.time()` and 01/01/2000.
On other ports, monotonic() it is not affected by setting the RTC.

This makes monotonic not be monotonic, and lose a lot of precision in the float conversion.
`monotonic_ns` is similarly affected, but it doesn't lose precision of course.

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #7808

Test:
```py
>> import time,rtc
>>> r = rtc.RTC()
>>> print(time.monotonic()); r.datetime = time.struct_time((2023,1,1,0,0,0,0,0,0)); print(time.monotonic())
1329.49
1329.49
>>> print(time.monotonic()); r.datetime = time.struct_time((2022,1,1,0,0,0,0,0,0)); print(time.monotonic())
1339.38
1339.38
>>> print(time.monotonic_ns()); r.datetime = time.struct_time((2022,1,1,0,0,0,0,0,0)); print(time.monotonic_ns())
1353792083741
1353791992187
>>> print(time.monotonic_ns()); r.datetime = time.struct_time((2024,1,1,0,0,0,0,0,0)); print(time.monotonic_ns())
1362228332530
1362227539062
>>> 
```
I also tested after ctrl-D: time.monotonic() is not reset to zero, which I think is OK.

The change looks bigger than it is: I had to reorder some things to avoid a forward declaration.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
makes sense, didn't test.

**Review by Neradoc — DISMISSED** [review]
This fixes #7808 from my tests on a Feather STM32F405 Express.
Thanks !

**Comment by dhalbert** [comment]
I need to look at this again. I didn't notice time is going backwards slightly here:
```py
>>> print(time.monotonic_ns()); r.datetime = time.struct_time((2022,1,1,0,0,0,0,0,0)); print(time.monotonic_ns())
1353792083741
1353791992187
```

**Comment by dhalbert** [comment]
`monotonic_ns()` now always goes forward. `subticks` (32 per tick) were not being taken into account.

I am not so fond of the STM32 RTC peripheral.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
