### PR TITLE
Added utime() to the os library

### PR DESCRIPTION
**Pull request by isacben**
Hi,

This PR is to add the utime() function to the os library, to solve issue #5978.

### Description

This implementation changes the timestamp of a file. The function takes 2 positional arguments:

- A string with the path to the file
- An int for the timestamp expressed in seconds

Example:

```python
import os
os.utime('file.log', 1663573240)
```

### Limitations

The implementation takes advantage of the function [f_utime()](http://elm-chan.org/fsw/ff/doc/utime.html) from the oofatfs library. Because of that, utime() sets the access time and the modified time of the file to the same timestamp. Due to this limitation, utime() only takes 1 integer for the timestamp expressed in seconds, compared to the CPython implementation, which takes a 2-tuple for the access time and the modified time express either in seconds or nanoseconds.

I tested with the **Adafruit Father RP2040**.

Thanks!

### CODE REVIEW

**Comment by dhalbert** [comment]
We are getting incredibly short on space on the non-Express SAMD21 builds again, so when #6247 is merged, this is probably going to make some builds too big. This is true even though I disabled the bulk of #6247 on the small builds. With #6247, before this addition, the `arduino_nano_33_iot` `ru` build has only 24 bytes free.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks for this! We want to make our API's be the same or a subset of what CPython provides. For that reason, could you make `utime()` take a 2-tuple instead of a plain int? Ignore one or the other value, I guess, or require that they are the same.

You can skip the `ns` argument support.

From https://docs.python.org/3/library/os.html#os.utime):
> `os.utime(path, times=None, *, [ns, ]dir_fd=None, follow_symlinks=True)`
>
>Set the access and modified times of the file specified by path.
>
> [utime()](https://docs.python.org/3/library/os.html#os.utime) takes two optional parameters, times and ns. These specify the times set on path and are used as follows:
> 
> - If ns is specified, it must be a 2-tuple of the form (atime_ns, mtime_ns) where each member is an int expressing nanoseconds.
> - If times is not None, it must be a 2-tuple of the form (atime, mtime) where each member is an int or float expressing seconds.
> - If times is None and ns is unspecified, this is equivalent to specifying ns=(atime_ns, mtime_ns) where both times are the current time.

**Comment by isacben** [comment]
Hi @dhalbert ,

Thank you for your review and feedback! I have completed the changes to accept a Tuple[int, int], and ignore the second int. Please let me know if you have any comments.

As you anticipated, there are a few builds that get too big with this change. Please let me know if there is anything I can help with.

Thank you in advance!

**Comment by dhalbert** [comment]
I squeezed some builds, but since the last time the jobs were run, there was other code added elsewhere, so I need to look further.

**Comment by isacben** [comment]
Hi Dan. I understand. I can see this can take some time and effort.
Thank you!

**Review by dhalbert — COMMENTED** [review]
Finally it fits! @isacben thanks for your patience!

**Review by dhalbert — APPROVED** [review]

**Comment by isacben** [comment]
Wow @dhalbert that's amazing!
Thank you for making it work!

**Pull request merged**
