### PR TITLE
Update the requests frozen library

### PR DESCRIPTION
**Pull request by arturo182**
Update the frozen Adafruit_CircuitPython_Requests submodule, so we get the Session class that's needed by the ESP32-S2 wifi API.

### CODE REVIEW

**Comment by ladyada** [comment]
hmm - which boards have it frozen? it isnt a great library to freeze...there's been a lot of churn in the network libraries and probably will be more to come

**Comment by dhalbert** [comment]
It is frozen in some i.MX 1011 boards.

**Comment by ladyada** [comment]
oooh yeah that makes sense, ok!

**Comment by arturo182** [comment]
I was also planning to freeze it in my esp32-s2 feather.

Maybe there should be a manual or automated job that updates all the frozen libraries either periodically or before a release that way all the boards that freeze libraries will get the latest versions in the release?

**Review by tannewt — APPROVED** [review]
No harm in updating this. However, it is already out of date. We don't suggest freezing it in for that reason.

**Pull request merged**
