### PR TITLE
Added built-in display bringup for Badger2040

### PR DESCRIPTION
**Pull request by ZodiusInfuser**
This is in response to @tannewt suggestion in https://github.com/adafruit/circuitpython/pull/6074#discussion_r812309726

I believe I have set it up correctly (certainly the sequences match what we do in C++ and MP). One query though, what is the default background color meant to be?

As it currently stands with our config it is white, but that means that to draw black text with displayio I have to do `label.Label(font, text=text, color=0xFFFFFF)` which seems backwards, but I cannot figure out a way to invert it without also inverting the background. Any input would be appreciated 🙂

### CODE REVIEW

**Comment by tannewt** [comment]
I believe the background should be black by default. That way it'll match displayio on TFTs.

**Comment by ZodiusInfuser** [comment]
Thanks for the clarification. So the CircuitPy mini REPL that appears on screen should be classic terminal style of white text on black?

I'll get that inverted then. A related question, how can I easily draw a white background from python code with display IO? I found some guides but it suggested that the only way to do it is to create a white bitmap that is then shown to the screen, but if feels like there's got to be a simpler way. Maybe I've been spoilt by our freedom with the custom Micropython builds we make that simply have a `display.clear(color)` function 😅 .

**Comment by FoamyGuy** [comment]
@ZodiusInfuser AFAIK the way to make a blank white screen with displayio is to make a white _something_ and add it as the first element in the group that you `show()` on the display, you could then stack more things on top of it.

There is some flexibility with what the white _something_  can be though... It could be a Bitmap that is the same size as the display filled with white pixels. Or it could be a Bitmap that is an even multiple smaller than the display and then use the `Group` object to scale it up by that multiple. This allows you to use a Bitmap smaller than the physical size of the display which can save some RAM. i.e. if your display is 296x128 pixels you could make a bitmap sized at 37x16 and then put it into a Group that is scaled 8x and it would then match the full display.

Another option is to use a `vectorio` object instead of a Bitmap. https://docs.circuitpython.org/en/latest/shared-bindings/vectorio/index.html Rectangle probably being the most fitting for this purpose.

There is no `display.fill()` or `display.clear()` style function like you mentioned with displayio because the core concept of displayio revolves around adding objects to the display to be shown rather than lower level pixel manipulations.

**Comment by ZodiusInfuser** [comment]
Thanks for the `vectorio` suggestion @FoamyGuy! That seems simple enough to set up.

I'm getting this twitter user to try a build with these changes in, and if it checks out I'll take this PR out of being a draft.
https://twitter.com/BeBoXoS/status/1503147248472973318?s=20&t=w7q_tvnk14GlHRFtjeUSsA

**Pull request merged**
