### PR TITLE
STM32: Add USB support to F412 Discovery 

### LINKED ISSUE #2125: STM32F412 Discovery board lacks USB support
Should be updated once https://github.com/hathach/tinyusb/issues/103 is completed.

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds USB support to the F412 Discovery, reflecting the most recent port in tinyUSB. Includes revisions to the linker for filesystem support. Updates tinyUSB to latest develop release. 

Closes #2125.

### CODE REVIEW

**Comment by ladyada** [comment]
@hierophect can ya drop me a .hex in a zip here?

**Comment by hierophect** [comment]
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3591578/firmware.bin.zip)
[firmware.hex.zip](https://github.com/adafruit/circuitpython/files/3591579/firmware.hex.zip)

**Comment by ladyada** [comment]
hmm nope, dont see any USB peripherals come up?

**Comment by ladyada** [comment]
hiero - those 2 work for you for sure to have a working USB CDC interface?

**Comment by hierophect** [comment]
My tests currently give me a working CDC and MSC interface, yes. Note that the F412ZG has a jumper that needs to be adjusted if you are using only the user USB port - JP3 needs to move from STLK to USB. Could that be it?

**Comment by hierophect** [comment]
You'll get a blinking red LED if something is wrong with the power jumper, and a green LED if things are set up OK. 

Alternatively, you can power the board from STLK and plug in the user USB with a different cable. That'll give dual access to both the STLink and the CircuitPy disks.

**Comment by ladyada** [comment]
ok i had 2 USB cables and both jumpers, i can remove the STLK jumper and try again

**Comment by hierophect** [comment]
I'm not sure it'll work backwards like that - if you have the STLK jumper in, the USB will also be powered. I don't know if it works the other way. I'd assume it has some current protection in there but I'd probably stick with either USB or STLK, but not both.

**Comment by ladyada** [comment]
ok for some reason the drag-n-drop hex to mbed disk technique isnt working. with st-link i can erase/program but...its till not enumerating. i gotta go, will investigate more later

@dhalbert @tannewt maybe one of y'all can try it?

**Comment by hierophect** [comment]
@ladyada it actually looks like this is general incompatibility with the .hex format. I just tried both methods with the .hex - the mbed disk doesn't respond to it at all (.bin files you drag in there don't ever appear as a file, they're redirected directly to the MCU), and st-flash does not result in successful enumeration or even set up the status LEDs. 

I'm sorry I provided the .hex file, I mistakenly assumed ST would support it. It looks like it's required to use .bin only for both methods.

**Comment by hierophect** [comment]
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3592145/firmware.bin.zip)

**Comment by ladyada** [comment]
so far so good! thanks

**Comment by ladyada** [comment]
huzzah!

**Pull request merged**
