### PR TITLE
Add support for the 16MB WeAct Studio Pico

### PR DESCRIPTION
**Pull request by domdfcoding**
Follow up to #6411, and based on Fabian's work there.

I only have the 16MB board, so as I can't test them I haven't added the 4 and 8MB versions.

### CODE REVIEW

**Comment by tannewt** [comment]
You'll want to add an entry here to share the USB VID/PID with the other version: https://github.com/adafruit/circuitpython/blob/main/tools/ci_check_duplicate_usb_vid_pid.py#L33

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by domdfcoding** [comment]
Presumably I also need to make a PR at https://github.com/adafruit/circuitpython-org for this board variant?

**Comment by tannewt** [comment]
> Presumably I also need to make a PR at https://github.com/adafruit/circuitpython-org for this board variant?

Yes please!

**Comment by prplz** [comment]
Is this needed? The rp2040 port auto detects flash size so it should work fine with the 2mb definition

**Comment by tannewt** [comment]
@prplz Maybe not. I think its ok to have though. Explicit tends to be better.

**Pull request merged**
