### PR TITLE
Fix endpoint checking; Clean up safe mode printing

### LINKED ISSUE #4746: changing USB descriptors on ESP32S2 crashes
Tested on the Feather S2. I expected that trying to use more endpoints than available results in reset to safe mode. Here are a few `boot.py` that cause issues. (Manual safe mode recovers).
```py
import usb_cdc
usb_cdc.enable(console=True, data=True)
```
- reset loop (status LED alternates purple and black)

```py
import usb_hid
usb_hid.disable()
import usb_cdc
usb_cdc.enable(console=True, data=True)
```
- code.py runs
- device connected seen on USB (ioreg) but no drive, no serial

### Those work as expected:
```py
import usb_hid
usb_hid.disable()
```
```py
import usb_cdc
usb_cdc.enable(console=True, data=False)
```
```py
import usb_hid
usb_hid.disable()
import storage
storage.disable_usb_drive()
import usb_cdc
usb_cdc.enable(console=True, data=True)
```

### LINKED ISSUE #4752: STM32(F4) USB HID support
I've bought a Feather STM32F405 Express and was expecting I could get it to act as a USB keyboard, but turns out USB_HID (and quite a lot of other features) aren't implemented for STM32 chips yet.

Is there any effort being made to implement USB_HID support?

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #4746.
Fixes #4752 (STM32 HID support).

- Endpoint count checking was off by one.
- `CIRCUITPY_USB_{HID,MIDI,MSC}_ENABLED_DEFAULT` default values were not set conditionally.
- Clean up `print_safe_mode_message()` to simplify logic, reduce size, and divide up safe-mode reasons more accurately.
- Redo logic of printing startup messages in `run_code_py()` to not print the safe-mode message twice, clean up newlines, and be more consistent about whitespace.
- Shortened and rephrased some messages slightly.
EDIT:
- Count in and out endpoints and check against provided limits. ESP32-S2 allows only 5 IN endpoints, so this enforces that limit
- Turn on MIDI and HID on some low-endpoint boards, but have them disabled. The user could disable something else (like the REPL) to add them.
- Add more information to documentation.

It appears to me that a `translate()` message with a `\n` in it is actually printed as a `\r\n` by `serial_write_compressed()`. I'm not sure if that's done during printing or during compression. But a bare `serial_write("\n")` does not print a `\r`. So I added `\r` as necessary in a few places.

### CODE REVIEW

**Review by jepler — DISMISSED** [review]
Looks OK, no testing performed.

**Comment by Neradoc** [comment]
It did not fix #4746 in my tests, both cases with issues now do a reset loop.

**Comment by dhalbert** [comment]
> It did not fix #4746 in my tests, both cases with issues now do a reset loop.

Thanks, because of debugging issues I was testing with an STM board, but will try with an ESP32-S2.

**Comment by dhalbert** [comment]
@Neradoc It turns out the ESP32-S2 endpoint situation is idiosyncratic. From the datasheet:

> * Endpoint number 0 always present (bi-directional, consisting of EP0 IN and EP0 OUT)
> * Six additional endpoints (endpoint numbers 1 to 6), configurable as IN or OUT
> * Maximum of five IN endpoints concurrently active at any time (including EP0 IN)

All the other chips have symmetric pairs of IN/OUT endpoints, but the ESP32-S2 does not. I am confused why we can support HID at all, because there don't appear to be enough singular endpoints. It's late and I will look in the morning. In any case, I will need to restrict the choices. It will be possible to add more HID devices, but I think the CDC data channel is not possible.

**Comment by dhalbert** [comment]
Note edit in previous comment.

**Review by tannewt — APPROVED** [review]
Looks fine to me. It might be good to try an update the translations so that the ones aren't lost about button presses.

**Comment by dhalbert** [comment]
Added:
- Count in and out endpoints and check against provided limits. ESP32-S2 allows only 5 IN endpoints, so this enforces that limit.
- Turn on MIDI and HID on some low-endpoint boards, but have them disabled. The user could disable something else (like the REPL) to add them.
- Add more information to documentation.

`make translate` seems to have fixed up some of the messages that would otherwise have been lost due to rewriting.  I will check after merging and address missing ones from weblate if I can.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
