### PR TITLE
Add ConnectionManager to frozen

### PR DESCRIPTION
**Pull request by justmobilize**

### CODE REVIEW

**Comment by justmobilize** [comment]
@dhalbert and @tannewt as an FYI, all builds pass with adding `ConnectionManager` and keeping the current `Requests` which is larger

**Comment by tannewt** [comment]
Great! Please un-draft and we'll merge it in so that a blanket frozen update that includes the requests changes works.

**Comment by justmobilize** [comment]
Done. Would appreciate a double check to make sure I didn't miss any boards. I just did a search for `frozen/Adafruit_CircuitPython_Requests`

**Comment by tannewt** [comment]
> Done. Would appreciate a double check to make sure I didn't miss any boards. I just did a search for `frozen/Adafruit_CircuitPython_Requests`

That's what I would do.

**Review by tannewt — APPROVED** [review]
Thanks!

**Pull request merged**
