### PR TITLE
Expand objdeque implementation

### LINKED ISSUE #8874: Deque is not iterable
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-alpha.6 on 2023-12-12; Waveshare RP2040-Zero with rp2040
```

### Code/REPL

```python
from collections import deque

sa = deque((), 4)

list(sa)
```

### Behavior

It's pretty self-explanatory:
image

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SAK917**
Fixes #8874 
This PR expands CP collections.deque functionality to be more congruent with the CPython implementation by adding iteration, subscription and initialization as well as pop(), appendleft() and extend().  Tests for the new functionality are also provided.

This code is a copy of [MP PR #10724](https://github.com/micropython/micropython/pull/10724) that was coded/submitted by LordFlashmeow and recently merged into MP.  I have built and tested versions of CP with this code for RP2040, ESP32S2 and atmel-samd M4 boards and everything compiles and works as expected.  I also confirmed that collections.deque is still not included in M0 builds as intended.

As per discussion with tannewt in [CP Issue #8874: Deque is not iterable](https://github.com/adafruit/circuitpython/issues/8874) and on the discord [circuitpython-dev channel](https://discord.com/channels/327254708534116352/327298996332658690/1219699287462514688), I am submitting this PR in the hopes the new functionality might be integrated into CP more quickly than the normal MP release / CP upstream merge cycle will take as I am using it for a current project.  But if this PR creates more work or headaches, I can certainly wait and keep using a custom version of CP until the functionality is officially integrated.

Last but not least, this is my first PR to a large open-source project so if you have any suggestions or requests for what I can / should do differently please feel free to let me know.

### CODE REVIEW

**Comment by SAK917** [comment]
It looks like for the 494 checks, all of the baseline checks and all but two of the board builds passed:

The nordic/hiibot_bluefi board [failed initializing submodules](https://github.com/adafruit/circuitpython/actions/runs/8364980563/job/22901823745?pr=9065#step:5:121); and,

The silabs/devkit_xg24_brd2601b board [failed building the en_US version](https://github.com/adafruit/circuitpython/actions/runs/8364980563/job/22901869389?pr=9065#step:10:18) (with Exit Code 2?).  Is it possible that this may be caused by the additional functionality increasing the size of the en_US build beyond some limit?  I ask because RAM usage for successful check builds of this board for many other languages indicated 100% RAM usage in the respective memory usage summaries.

I am afraid I am not sure how to troubleshoot these issues further as I am not that familiar with submodules nor builds of something as complex as CP, and the failure for the en_US silabs board build doesn't provide much information for amateur diagnosis.  If there is anything I can do to help get this across the finish line, please let me know and I am happy to do whatever I can.

**Comment by dhalbert** [comment]
@SAK917 I will re-run the failed jobs. It is not uncommon for there to be CI glitches.

**Comment by SAK917** [comment]
Looks like that did the trick @dhalbert, all checks passed!  Thanks for rerunning and I appreciate your help.

**Review by dhalbert — APPROVED** [review]
Thank you! This will go in 9.1.0.

**Pull request merged**
