### PR TITLE
board_deinit() everywhere

### PR DESCRIPTION
**Pull request by dhalbert**
SAMD sleep was only turned on for a few SAMD51 satellite boards. Other people want to use it now. When I turned it on for all SAMx5x boards, I had to define `﻿board_deinit()﻿`, which was conditionally prototyped in `supervisor/board.h` only when `CIRCUITPY_ALARM = 1`.

That means `board_deinit()` had to be conditional on `CIRCUITPY_ALARM = 1` in all `board.c` files, which is actually not true right now. Rather than do that, since it is usually an empty function anyway, I removed the conditionalization and added it to all boards.

I noted that now the Metro M4 can do a deep sleep, but it leaves the TX and RX LEDs on. I wonder if `main.c` should do a `status_led_deinit()` on a true deep sleep, or whether `board_deinit()` should do that.

@jepler @tannewt Let's discuss this, since I'm unsure how to proceed.

### CODE REVIEW

**Comment by tbjers** [comment]
I only reported this issue last night at 01:30. There's already a PR. Much love, my friends.

**Comment by jepler** [comment]
The prototype is simplest, I would make it unconditional.

I think Scott will know better than me how the `deinit` functions should be related. I would say that unless we think there's a reason that setting up for deep sleep shouldn't call `status_led_deinit()`, it becomes simpler (less prone to mistakes) if it is in main and not in `board_deinit`.

**Comment by tannewt** [comment]
I think we do want a status_led_deinit before deep sleep to shutdown any neopixels. We also want a new deinit_rxtx_leds to undo https://github.com/adafruit/circuitpython/blob/main/supervisor/shared/status_leds.c#L330

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
