### PR TITLE
Support for #703 ... Ethernet Featherwing on M0 Express and M4 Express platforms

### PR DESCRIPTION
**Pull request by nickzoic**
OK so this is working support for the WizNet 5500 on Metro M4 Express (with or without LWIP) and Metro M0 Express (no LWIP for M0, sorry, won't fit!).

To do: make this work within the shared-bindings / common-hal layout used by CircuitPython.

(WIP: Shared here in the spirit of "Commit early, commit often" :-) )

### CODE REVIEW

**Comment by tannewt** [comment]
@nickzoic and I discussed this yesterday and came up with the following changes (from his email note about it):

1. regularize both 'usocket.socket' and 'lwip.socket' into CPython-compatible 'socket.socket' and socket should become part of the shared-bindings / common-hal split.
2. move 'network.WIZNET5K' off into 'wiznet.WIZNET5K'
3. Merge 'WIZNET5K.active()' into the constructor and add a deinit() and __exit__ method to make it context-managery.
4. Make the SPI bus speed configurable
5. Cleanup and PR.

@nickzoic Any more outstanding questions from your end?

**Comment by tannewt** [comment]
Any updates on this?

**Comment by nickzoic** [comment]
Hiya Scott, not yet but I'm working on rearranging the micropython-style
code as it currently is into the circuitpython shared-modules style.
I'll get some work done on this tomorrow ...
-----N

**Comment by tannewt** [comment]
Ok, no worries.

**Comment by nickzoic** [comment]
Rethought, rewritten and rebased ... and now rePRed at #1236

**Pull request closed without merging**
