### PR TITLE
Added board definition for upcoming Pimoroni servo driver.

### PR DESCRIPTION
**Pull request by ZodiusInfuser**
A teaser can be seen here 🙂 
https://twitter.com/i/status/1489298380270575616

With any luck we'll be launching next week

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Good luck with the launch! :rocket:

**Comment by ZodiusInfuser** [comment]
Thanks! I thought you were on leave though? 😉

**Comment by tannewt** [comment]
Soon!

**Comment by ZodiusInfuser** [comment]
Thanks for the merge! Though .... I've just re-compared the pinout to the schematic and `LED_DAT` should be `LED_DATA` 🤦. Do I need to raise a separate PR for that, or can the change be merged again if I just update this branch?

Also, we have the 3 ADC pins labelled `ADC0`, `ADC1`, and `ADC2` in the schematic, but `A0`, `A1`, and `A2` in the pin def. I believe that's to be consistent with CircuitPython's typical naming so probably doesn't need changing 🤷 .

**Comment by ladyada** [comment]
once merged a PR cannot be amended. make a new PR plz

**Pull request merged**
