### PR TITLE
When reading data from a file into a str, check if it's utf-8

### LINKED ISSUE #6752: Reading invalid utf-8 character from file does not produce error
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-127-gf1053fb96 on 2022-08-11; Adafruit QT Py ESP32C3 with ESP32-C3FN4
```

### Code/REPL

```python
file = open('disconnect.txt')
badchar = file.read(1)
```

### Behavior

The attached disconnect.txt contains a mangled character created through a network error. I haven't been able to figure out how to recreate it programmatically but perhaps someone with a better understanding of character sets and CP string formats could.

[disconnect.txt](https://github.com/adafruit/circuitpython/files/9311941/disconnect.txt)

When this file is opened and a single character is read into badchar, an invalid utf-8 character of length 4 and value '\x07\n\r\x08' is loaded without displaying an error.

Attempting to obtain the ord(badchar) results in the following error:

     Traceback` (most recent call last):
       File "<stdin>", line 1, in <module>
     TypeError: ord() expected a character, but string of length 4 found

Here is what CPython gives when attempting to read in the same character:

     >>> f = open("/home/tannewt/Downloads/disconnect.txt")
     >>> c = f.read(1)
     Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
       File "/usr/lib/python3.10/codecs.py", line 322, in decode
         (result, consumed) = self._buffer_decode(data, self.errors, final)
     UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 0: invalid start byte

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jepler**
Otherwise, weird stuff can happen down the line when it is print()ed, especially as it can break the webrepl of circuitpython. Closes #6752.

This needs formal tests, not just the manual testing I did.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
This does now print an error when I attempt to read in the file containing an invalid utf character. 

But this also does enforce a new higher level of code compliance when dealing with files. For better or worse I have sometimes simply used a standard `open(filename)` statement to open files that contain binary data and this update will break that code.

I am not overly concerned with enforcing a stricter code compliance, the fix to the code is obvious and simple. While there's no doubt that by enforcing the utf-8 typing on the read, downstream "weirdness" will be avoided. if our primary concern is the webrepl then another option would be to catch and replace the binary data before displaying it in the serial terminal. This latter approach also has the advantage that it will prevent the serial terminal from disconnecting should a valid character be mangled in transmission by a network error.

I have grabbed the Feather ESP32-S3 4/2 artifact and am testing with that. So far the change is working as expected. 

As a further test, I'm modifying the open statements in my application to use the correct mode when I need to read binary data and then decoding the binary data if necessary. I'll update here if I encounter any issues or difficulties.

**Comment by jepler** [comment]
It's true, some of the ways of reading a file in 'default mode' where the content is actually binary won't work now. The fix is of course to specify the open mode as "rb", which is also required for standard python compatibility.

**Comment by RetiredWizard** [comment]
I've been running this build through some paces this weekend and haven't seen anything unexpected.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Pull request merged**
