### PR TITLE
enable I2C by default

### PR DESCRIPTION
**Pull request by ladyada**
folks can always turn it off to save power later

### CODE REVIEW

**Comment by ladyada** [comment]
@dhalbert this enables i2c by default

**Review by dhalbert — APPROVED** [review]
This will enabled I2C power after a hard reset, but will not change the pin state after a soft reload. For that we would add it to `reset_board()`.

So if you disabled power in boot.py by setting the pin high, it will stay high. Maybe this is what we want. If we moved pin setting to code.py, it would get changed every time code.py started.

I think that makes sense. It is similar to the CPB, which also turns _off_ stuff on hard reset, but doesn't adjust it on each soft reload.

This fix is in main, not 7.1.x. Do you want it backported to 7.1.x? (Probably a good idea).

**Review by dhalbert — CHANGES_REQUESTED** [review]
Test program that uses D7 gives this error on soft reboot:
```>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 6, in <module>
ValueError: D7 in use
```

**Comment by dhalbert** [comment]
Closing in favor of #5779, which is a near duplicate, but against `7.1.x` instead of `main`. I was unable to reproduce the error above after further testing with #5779.

**Pull request closed without merging**
