### PR TITLE
WIP: Blip improvements

### PR DESCRIPTION
**Pull request by ntavish**
If `ugame.py` is frozen, then LCD doesn't seem to initialize, WIP until fixed or till workaround.

### CODE REVIEW

**Comment by tannewt** [comment]
Hi! Why is this adding a different version of stage?

To add another frozen directory please add it as a submodule so that it's history is tracked outside of CircuitPython.

**Comment by ntavish** [comment]
hi @tannewt it's because of `audiopwmio` (for nrf port), instead of `audioio`, here's the issue in stage repository https://github.com/python-ugame/circuitpython-stage/pull/6.

This is marked WIP till there is a better solution. @deshipu suggested one possible solution can be that stage library gets the audioio/audiopwmio module as an object from `ugame.py`.

**Comment by tannewt** [comment]
I'd prefer it if the stage library was improved to work rather than adding a separate version. @deshipu is that doable?

**Comment by dhalbert** [comment]
@ntavish @deshipu Have you discussed this? I'm just making a pass over older PR's.

**Comment by tannewt** [comment]
Please reopen or create a new PR if this is still an issue. Thanks!

**Pull request closed without merging**
