### PR TITLE
Nickzoic/circuitpython nrf touchin 1048

### PR DESCRIPTION
**Pull request by nickzoic**
Adds touchio.TouchIn to the NRF port.  Works by driving an analog-capabile pin high and then measuring the rate of discharge through a 1Mohm resistor to ground.  See #1048 for details of implementation.

### CODE REVIEW

**Comment by ladyada** [comment]
thanks, we're having a lil nrf52 build issue but as soon as the builds work i can test this on hardware :)

**Comment by tannewt** [comment]
Is this ready to go in?

**Comment by ladyada** [comment]
@tannewt not yet - the current method is kinda finicky - i'd prefer to use the 'classic' 2-pin method instead, i replied in the issue

**Comment by tannewt** [comment]
So can we close this PR until the two pin method is ready?

**Comment by ladyada** [comment]
yep done - we will get workin' and re-submit :)

**Comment by nickzoic** [comment]
Sorry, I've been away on vacation.  The new '840 Feather has arrived, so
I'll give it a crack ASAP.

**Comment by ladyada** [comment]
yay! welcome back

**Pull request closed without merging**
