### PR TITLE
Rework displayio display bus transaction handling during refresh

### LINKED ISSUE #1612: displayio and SPI conflict
There appears to be some conflict with displayio and SPI.
I have a TFT featherewing on a Feather_m4_express ( same issue on a particle xenon)
and if I run the stmpe610_simpletest which reads the TFT touch screen it works normally as long as I have not configured displayio first. If set up diaplayio -- so the REPL is being echoed to the screen, and then try the stmpe610_simpletest, it crashes.

PR #1604 had no impact on this -- it behaved the same with or without it.

normal run
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-142-gced37c100 on 2019-03-02; Adafruit Feather M4 Express with samd51j19
>>> import stmpe610_simpletest
Go Ahead - Touch the Screen - Make My Day!
(1095, 2189, 62)
(1173, 2340, 21)
(1141, 2350, 25)

```
now configure displayio and reboot with REPL on display
and repeat
```
>>> import display

soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-142-gced37c100 on 2019-03-02; Adafruit Feather M4 Express with samd51j19
>>> import stmpe610_simpletest
Go Ahead - Touch the Screen - Make My Day!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stmpe610_simpletest.py", line 9, in <module>
  File "adafruit_stmpe610.py", line 230, in buffer_empty
  File "adafruit_stmpe610.py", line 178, in _read_byte
  File "adafruit_stmpe610.py", line 308, in _read_register
  File "adafruit_stmpe610.py", line 304, in _read_register
RuntimeError: Function requires lock
>>> 



```

### PR DESCRIPTION
**Pull request by dhalbert**
Success or failure of starting a display-bus transaction is now checked. For some routines, we busy-wait for the bus. For the background display refresh task, we just give up if the bus is not currently available.

Meant to fix #1612 and #1619.

### CODE REVIEW

**Comment by jerryneedell** [comment]
Ran a test on a feather_nerf52840 with a TFT featherwing --If I configure displayio then run the stmpe610 test using SPI, the stmpe610 test runs normally, but it causes the display to be deactivated -- that is I no longer see REPL output on the screen and even after a soft reboot, I can't get the REPL  to show up on the screen again. If I run the slideshow - it does not show any images. No erros, but no images. If I hard reset, the slideshow (non-sd) runs normally. The slideshow from the SD card runs as above, no errors, but no images. 
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-200-gc854f6617 on 2019-03-06; Adafruit Feather nRF52840 Express with nRF52840
>>> import slideshow_sd
cats1.bmp            Size: 37.0 KB
IMG_0493.bmp         Size: 37.0 KB
IMG_1027.bmp         Size: 66.2 KB
skye1.bmp            Size: 46.2 KB
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "slideshow_sd.py", line 56, in <module>
  File "adafruit_slideshow.py", line 200, in __init__
  File "adafruit_slideshow.py", line 318, in advance
KeyboardInterrupt: 
```

**Comment by jerryneedell** [comment]
on a pyportal slideshowsd seems to run fine

**Comment by jerryneedell** [comment]
also as in #1612, with this PR I can still mount/access the SDCard with the displayio device active -- teh REPL is echoing all the activity running a script from the SDCard.

**Comment by jerryneedell** [comment]
as suggested by @dhalbert  Tried adding a delay in the stmpe610 read_data loop. Added a .25 sec delay -- this works -- the display continues to echo the REPL throughout the test and after the program is stopped with a control-c.

**Comment by dhalbert** [comment]
@jerryneedell I fixed some remaining problems, and tested on PyPortal and a TFT FeatherWing with Feather M4 reading from SD card. Seems to work now. Might work better with SMPTE also.

**Comment by dhalbert** [comment]
Feel free not to test tonight :)

**Comment by dhalbert** [comment]
@tannewt Besides some general cleanup, this fix locks the SPI bus as necessary, but unlocks it between buffer writes, which gives the SD card code the access to read image data.

**Comment by jerryneedell** [comment]
Tested on feather_nrf62840 with TFT featherwing:
slideshow from SD Card worked normally!
stmpe610 test worked with one issue that is more a problem with the test than CP.
When the displayio device is in use, there is a noticable slowdown in the execution speed at the REPL. You can see it just typing. the response is sluggish.
For a device like the stmpe610 that buffers data quickly, this resulted in some significant lag issues. But that will likely have to be addressed by the user code.

tested on pyportal -- slideshow from SDCard worked normally
aslo tested mounting and executing a script from the SDCard -- worked fine
Note: the responsiveness of the REPL  in the PyPortal is much better than on the feather_nrf52840.
The "sluggishness" mentioned above  is not apparent.

This PR looks good to me -- I see it failed the German Metro M0 build on Travis as I found yesterday :-(

**Comment by dhalbert** [comment]
Travis is confused: both builds have finished successfully, but it hasn't noticed.

**Pull request merged**
