### PR TITLE
Better success using CIRCUITPY_FULL_BUILD=0

### PR DESCRIPTION
**Pull request by RetiredWizard**
After some poking, I was able to reproduce the compile errors I was getting when trying to build a DEBUG image. It turns out the problem shows up when you use the CIRCUITPY_FULL_BUILD=0 option. The issues I was seeing could have been resolved by turning on select modules (CIRCUITPY_DISPLAYIO=1 for example) and perhaps that's the expected route to take but I figured I'd put the changes I made into a PR just in case. I'm not sure these changes have been made in the most appropriate way or places but I'd be happy to modify them with a little direction :grin:

The boards with display's initialized in boards/_boardname_/board.c will still have issues. The only solution that I could think of for them was to surround the display initialization in an #if...#endif block in the individual board.c files. I can start working on that if that makes sense but that's obviously a bigger project.

Boards in the raspberrypi port need to have CIRCUITPY_BITBANGIO=1 and if the mpconfigboard.mk file has CIRCUITPY_PICODVI=1 defined in it, that has to be removed or set to zero. I couldn't see a workaround for the BITBANGIO because the conflict comes from the raspberrypi version of busio.I2C using bitbangio but busio for other ports don't so the raspberrypi is the only port that can't load busio without a conflict.

I tested a board from each port (except broadcom since I think they all init a display at startup) although some of the boards were tested using the code before Scott's recent "split displayio" PR was merged. I did test raspberrypi, atmel-samd and espressif against the code with "split displayio" applied and they seem to be working fine now with CIRCUITPY_FULL_BUILD set to 0.

### CODE REVIEW

**Comment by tannewt** [comment]
Why are you trying to make FULL_BUILD=0 work?

I'd rather have these settings dependencies raise an error when missing. So if you enable CAMERA without displayio it'll error for example.

**Comment by RetiredWizard** [comment]
The FULL_BUILD=0 option was the first thing I tried when the DEBUG=1 build didn't fit. I did get a build to work by turning off/on individual features which is fine, but I figured if there was a CIRCUITPY_FULL_BUILD flag it should work. 

I agree that raising an error message rather than simply ignoring the option would be a better option, I can try and rework this with error messages if you like, or if you think the FULL_BUILD option is not really needed I can see that point as well.

**Comment by tannewt** [comment]
I'm fine if you want to fix FULL_BUILD by having it error. I usually do different modules so I know which ones I've disabled. (ulab is usually first.)

**Comment by RetiredWizard** [comment]
Testing this involves a lot of compiles and is taking me some time to work through so I figured I'd switch to a draft while I'm working through the ports/boards in case there are any suggestions or comments on my approach.

**Comment by RetiredWizard** [comment]
Well I've probably put this off long enough that it's gotten stale and would need to be tested across all ports again. The _FULL_BUILD option doesn't seem to be be significant anyway as the general rule is to turn off individual features rather than selecting the minimum build and then adding features back in.

I'm going to go ahead and close this and work on more interesting/possibly useful things.

**Pull request closed without merging**
