### PR TITLE
Fix PIDs to match official espressif list

### PR DESCRIPTION
**Pull request by jepler**
See the slightly deceptively titled
 * https://github.com/espressif/usb-pids/pull/29

### CODE REVIEW

**Review by anecdata — DISMISSED** [review]
LGTM!

**Comment by anecdata** [comment]
oh, except I guess we need to delete the duplicate check?

**Comment by jepler** [comment]
oops, I'd changed that locally but forgot to commit!

**Review by anecdata — APPROVED** [review]
LGTM, for real this time. Passed all checks, numbers match Espressif registry.

**Pull request merged**
