### PR TITLE
Add espressif rotaryio divisor support.

### PR DESCRIPTION
**Pull request by domdfcoding**
Follow up to #5468, which don't include espressif support.

I have tested this on a QT Py ESP32-S2 with [this](https://www.ckswitches.com/products/switches/product-details/Rotary/ENC/) type of rotary encoder, which requires `divisor=1`. I've also tested with `divisor=2` and `divisor=4`, and a pulse is registered every 2 and 4 detents respectively as expected.

I had to change the order in `shared-bindings/rotaryio/IncrementalEncoder.c` as the divisor value needs to be known *before* configuring the peripheral. I don't think this will cause issues for other ports as the set_divisor function only sets a value on a struct, so the order of operations shouldn't matter.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
>I had to change the order in `shared-bindings/rotaryio/IncrementalEncoder.c` as the divisor value needs to be known *before* configuring the peripheral. I don't think this will cause issues for other ports as the set_divisor function only sets a value on a struct, so the order of operations shouldn't matter.

Rather than change the order, let's add the `divisor` argument to `_construct`, and change the other ports to handle that. Then we are not dependent on the being valid for all ports.

**Comment by domdfcoding** [comment]
I've realised the `divisor` property can be changed after creating the IncrementalEncoder object, but that would require reconfiguring the PCNT peripheral. I don't know why you'd want to change the property, so I've made it raise an error if the user tries to do that.

**Comment by dhalbert** [comment]
@domdfcoding you pushed 319ca85 after our discussions of making `divisor` read-only, etc. What are your current thoughts?

**Comment by domdfcoding** [comment]
With the current code the constructor doesn't need to know the divisor anymore, so the order is back how it was before this PR.

**Comment by jepler** [comment]
I think it depends what you think should happen when the divisor is changed.

Given that I don't know the real world reason for dynamically changing the encoder divisor, I don't feel confident stating how it should work.

I see three possibilities:
 * document that the position may change arbitrarily when changing divisor, the code can reset position to 0 if it wants
 * make new movement relative to the old position, applying any pending sub-counts according to the new divisor
 * multiply or divide the position according to the change in divisor, probably also accounting for sub-counts

Again, given that there's no particular scenario that we have in mind for changing this dynamically, I would probably take the simplest alternative: position is free to jump when changing divisor, the code can set the value (E.g., reset to zero) if it needs to.

**Review by jepler — APPROVED** [review]
If this passes your testing with divisors of 1 and 4, it's good enough for me. I didn't do any testing on HW myself.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
