### PR TITLE
Add Seeed Studio Xiao ESP32-S3 board

### PR DESCRIPTION
**Pull request by anecdata**
ESP32-S3 Xiao / QT Py form factor, with u.FL antenna connector, user LED, charge LED, `BOOT` button, `RST` button.

This is the plain version, not the Sense:
https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/

Needs Seeed VID / PID
(anyone know a process or contact for that?)

Tested loading UF2, mounting and editing from CIRCUITPY, operating REPL, toggling user LED, connecting to a wifi AP.

### CODE REVIEW

**Comment by anecdata** [comment]
Also need to figure out why `u = board.UART()` gets a hard fault on this board but not other S3 boards. Haven't spotted a difference in board defs from boards that work.

**Comment by dhalbert** [comment]
> Also need to figure out why `u = board.UART()` gets a hard fault on this board but not other S3 boards. Haven't spotted a difference in board defs from boards that work.

Did you fix this? Not sure if it ready to merge. Thanks.

**Comment by anecdata** [comment]
Not yet, converting to Draft. It will run the DevKitC N8R8 fine, but something is different in my changes.

Also needs Seeed VID / PID.

**Comment by deshipu** [comment]
Rebasng on latest main seems to fix the uart problem.

**Comment by deshipu** [comment]
By the way, that board comes with a b2b connector with some extra pins on it, do we want to include that in pins.c, or do we want a separate board definition for xiao esp32-s3 sense?

The pins are described in https://files.seeedstudio.com/wiki/SeeedStudio-XIAO-ESP32S3/res/XIAO_ESP32S3_Sense_Pinout.xlsx

**Comment by anecdata** [comment]
I has assumed a separate board def for the Sense version.

**Comment by deshipu** [comment]
I was thinking that the separate board definition would need a separate pid, which might be a problem, but it looks like it's a problem anyways...

**Comment by deshipu** [comment]
I asked for VID/PID on their support forums: https://forum.seeedstudio.com/t/usb-vid-pid-for-the-xiao-esp32-s3-and-xiao-esp32-s3-sense-for-circuitpython/272245

**Comment by anecdata** [comment]
> I asked for VID/PID on their support forums

The Seeed GitHub wiki was the other place suggested, if this doesn't pan out.

**Review by dupontgu — COMMENTED** [review]
Thanks for doing this! One note - looks like `xiao` is mispelled in the path (xaio)

**Comment by anecdata** [comment]
> Thanks for doing this! One note - looks like `xiao` is mispelled in the path (xaio)

Thanks for noticing, I'll fix it all up once we have a PID.

**Comment by anecdata** [comment]
Closing. It can be re-opened or a new PR can be opened on getting a PID. The changes aren't very extensive.

**Comment by romkey** [comment]
I have one of these boards. vid is 0x303a, pid is 0x1001

```
Bus 001 Device 004: ID 303a:1001 Espressif USB JTAG/serial debug unit
```

**Comment by anecdata** [comment]
? <https://github.com/espressif/usb-pids/blob/main/allocated-pids.txt>

**Comment by djairjr** [comment]
You can find VID/PID yourself:
https://superuser.com/questions/1106247/how-can-i-get-the-vendor-id-and-product-id-for-a-usb-device

For the ESP32-S3 Sense is:
USB_VID = 0x303A
USB_PID = 0x1001

**Comment by SeanTheITGuy** [comment]
1001 is also the pid for this esp32s3 7" display unit I have. So its not unique to that device, its a generic from espressif that, I guess, was intended to be changed by the boardmakers.

**Pull request closed without merging**
