### PR TITLE
Make requiring I2C pullups be optional

### LINKED ISSUE #2454: Request VID/PID for AramCon Badges
HI,
I would like to request PIDs for the conference badge we are working on and for the previous one (2 total).
AramCon Badge 2019
AramCon Badge 2020

We are planning to upstream later this year.
our circuit python fork https://github.com/urish/circuitpython
the badge repo https://github.com/urish/aramcon-badge

Thanks for all the great work on circuitpython!

### PR DESCRIPTION
**Pull request by dhalbert**
Addresses an issue raised in #2454. @bmeisels, working on the AramCon Badge, would like to turn off testing for powered I2C pullups, due to their particular situation with a board and its matching peripherals. 

This adds `CIRCUITPY_REQUIRE_I2C_PULLUPS`, which can be specified in `mpconfigboard.mk`. If 1 (the default), pullups are required. If 0, the checking is not done. Only the `nrf` and `atmel-samd` ports currently check for pullups. Tested on an nrf board.

@bmeisels please review and try.

### CODE REVIEW

**Comment by bmeisels** [comment]
@dhalbert Tested on our badge (nrf52840) and it works. I am not sure that this change makes sense for the Atmel samd port. Does the sercom peripheral enable internal pull-ups at all and even if it does if i read correctly in the datasheet they are very weak (40-60 kohm).

**Comment by arturo182** [comment]
Could you also add this in the commented-out code in the imx port? I want to make sure we keep it consistent between ports, even if it's not implemented yet.

https://github.com/adafruit/circuitpython/blob/master/ports/mimxrt10xx/common-hal/busio/I2C.c#L101

Thanks!

**Comment by dhalbert** [comment]
@bmeisels I have tried to make this consistently optional across ports. Though the specific use case you're mentioning doesn't apply to `atmel-samd`, I can imagine a use case, such a situation where one needs to set up the I2C object before powering the pullups. I don't expect it to be useful but I may as well do it. The alternative for consistency is to turn off the pullups in the nrf case, which would make your situation worse.

@arturo182 I pushed a commit for that.

**Comment by arturo182** [comment]
Thanks, @dhalbert and I agree, even though it's not as useful in samd, it doesn't hurt anything to have it and is more consistent so +1

**Pull request merged**
