### PR TITLE
Fix for Issue #4983 - stop state machine before restarting

### PR DESCRIPTION
**Pull request by DavePutz**
Correct state machine restart code by adding a stop before re-starting. Tested OK with the sample Python code provided.

### CODE REVIEW

**Comment by dmcomm** [comment]
Works for me with the example I provided, but unfortunately not with the "wait pin" scenario, so I'm preparing an example of that.

**Review by tannewt — CHANGES_REQUESTED** [review]
I think you'll want to stop before running the exec otherwise you risk the pc advancing before you can disable the state machine. IIRC the enable only changes the auto-pc advance behavior. exec will still execute commands when the sm is "disabled".

**Comment by dmcomm** [comment]
I mentioned in the issue thread that I was concerned about restart followed by the exec'd jump. If tannewt is right that exec still works when stopped, sounds like it could go stop,exec,restart.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
