### PR TITLE
update to ulab 4.0.0

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by tannewt** [comment]
Does this change any APIs?

**Comment by jepler** [comment]
> Does this change any APIs?

@v923z can you take a moment to answer?

I know it _optionally_ introduces new APIs, but the big thing (complex numbers) remains disabled in CP.

**Comment by v923z** [comment]
> > Does this change any APIs?
> 
> @v923z can you take a moment to answer?
> 
> I know it _optionally_ introduces new APIs, but the big thing (complex numbers) remains disabled in CP.

If complex is disabled, then there isn't any difference. There are two new functions, but you can disable them in the header file. 

I don't know if you want to resolve this https://github.com/v923z/micropython-ulab/issues/435 before merging into CP.

**Comment by dhalbert** [comment]
> I don't know if you want to resolve this v923z/micropython-ulab#435 before merging into CP.

@jepler: I can approve this, just wanted to follow up on the above.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
