### PR TITLE
Read only mac address rp2040

### LINKED ISSUE #7357: Fix error when trying to set cpu.frequency but not supported
According to [this forum post](https://forums.adafruit.com/viewtopic.php?p=952677#p952677) the error is "Attribute Error:
'Processor' object has no attribute 'frequency'" It should instead say it isn't settable. I suspect we need to remove the setter when setting isn't possible. The code now returns a NotImplementedException that is being caught internally and producing the error seen. So conditionalize this:

https://github.com/adafruit/circuitpython/blob/10138f43d62a90fa9d090c7eb4bdaaa087016abb/shared-bindings/microcontroller/Processor.c#L89-L91

Instead of this:

https://github.com/adafruit/circuitpython/blob/10138f43d62a90fa9d090c7eb4bdaaa087016abb/shared-bindings/microcontroller/Processor.c#L70-L78

### PR DESCRIPTION
**Pull request by dhalbert**
EDIT: Also fixes #7357.

https://forums.adafruit.com/viewtopic.php?p=952638: user found `AttributeError` message confusing when trying to set MAC address on Pico W. The attribute exists, despite the message, but is not settable (currently?) for CYW43.

- Used `NotImplementedError` instead, with a clarifying message.
- Share that message with another place.
- Merge "read-only` messages to reduce number of messages.

### CODE REVIEW

**Comment by dhalbert** [comment]
Will revise to fix #7357.

**Comment by jepler** [comment]
```
>>> class X:
...     @property
...     def p(self): return 1
... 
>>> x = X()
>>> x.p
1
>>> x.p = 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```
Python uses AttributeError for a non-settable property but it has a clearer error ("can't set" vs "has no attribute").

Maybe we should fix this by making the failure to set the attribute have a distinct message:
```
diff --git a/py/runtime.c b/py/runtime.c
index 6be5c22335..89d459648a 100644
--- a/py/runtime.c
+++ b/py/runtime.c
@@ -1247,7 +1247,7 @@ void mp_store_attr(mp_obj_t base, qstr attr, mp_obj_t value) {
     mp_raise_AttributeError(MP_ERROR_TEXT("no such attribute"));
     #else
     mp_raise_msg_varg(&mp_type_AttributeError,
-        MP_ERROR_TEXT("'%s' object has no attribute '%q'"),
+        MP_ERROR_TEXT("'%s' object can't set attribute '%q'"),
         mp_obj_get_type_str(base), attr);
     #endif
 }
```
It'd be up to you whether to have the sites you changed here use this style of message or the style of message that you already used.

**Comment by jepler** [comment]
(or save even more code space by making the property either a GET or a GETSET depending on #defines, which would let this site's error checking be reused)

**Comment by jepler** [comment]
@dhalbert let me know when you update this PR

**Comment by dhalbert** [comment]
@jepler on CYW43, is the fact you can't set the MAC address for station or AP mode inherent, or just not implemented yet? That affects my thinking about what error to raise.

I _am_ changing the the `AttributeError` message  in `py/runtime.c` to be `"can't set attribute '%q'"`, which will match CPython.

**Comment by jepler** [comment]
As far as I can tell the mac address is not settable in cyw43.

**Review by jepler — APPROVED** [review]
Thank you!

**Comment by dhalbert** [comment]
Tested on Pico W and Metro ESP32-S2.

**Pull request merged**
