### PR TITLE
Add Gravitech Cucumber R board definition

### PR DESCRIPTION
**Pull request by cotdp**
This is a work-in-progress for the Gravitech Cucumber R ESP32-S2 board (https://www.gravitech.us/curesdebo.html).  I cannot find a USB_VID for Gravitech and have left the Saola VID/PID as a temporary measure.

### CODE REVIEW

**Comment by cotdp** [comment]
- [ ] Update the USB_VID / USB_PID

**Comment by ladyada** [comment]
@gravitech-engineer please allocate a USB VID/PID for circuitpython

**Comment by cotdp** [comment]
Both Gravitech Cucumber R and Gravitech Cucumber M modules are booting with their respective versions.  Both variants have 4MB flash, but Gravitech Cucumber M is without PSRAM.

**Comment by tannewt** [comment]
Their github doesn't look very active so I emailed their sales email from their website.

**Comment by ladyada** [comment]
hihi - from the git history and lack of response it looks like @gravitech-engineer is AWOL or out of business? we like to see people being able to use their hardware even when the OEM stops supporting it, we'll grant a VID/PID to this board.

@dhalbert please allocate/assign a VID/PID to this PR and merge it at your convenience :)

**Comment by gravitech-engineer** [comment]
Hi,

 

Thanks for your email. Where we can locate the VID/PID for this board?

 

Thanks

Sharnon

**Comment by ladyada** [comment]
@gravitech-engineer USB VIDs are purchased or allocated *by the manufacturer* of the board - for your USB boards, what VID are you using for bootloader and runtime, did you purchase a VID or are you using someone elses?

**Comment by gravitech-engineer** [comment]
Our board doesn’t have any bootloader in it. There are two USB ports. One connect to the FTDI chip and another one connect directly to the ESP32-S2 OTG port. We can get one if it is necessary for circuitpython to work.

**Comment by ladyada** [comment]
yes please allocate a VID/PID for CircuitPython. You will also need one for Arduino (when you submit the PR for adding board support to espressif)

**Comment by ladyada** [comment]
@gravitech-engineer hi please reply to the request so we can add support

**Comment by gravitech-engineer** [comment]
We’re in the process of getting VID.

 

Thanks

Sharnon

**Comment by ladyada** [comment]
@gravitech-engineer hi is there any update?

**Comment by ladyada** [comment]
@cotdp @gravitech-engineer  please get a PID from espressif here https://github.com/espressif/usb-pids

**Comment by skieast** [comment]
I have requested and received a PIDs from Espressif for the CucumberRIS board.
I have also created a PR for the UF2 Bootloader using the appropriate PID.  

0x800C | GRAVITECH CUCUMBER RIS ESP32S2 - Arduino
0x800D | GRAVITECH CUCUMBER RIS ESP32S2 - CircuitPython
0x800E | GRAVITECH CUCUMBER RIS ESP32S2 - UF2 Bootloader

https://github.com/adafruit/tinyuf2/pull/69

**Comment by gravitech-engineer** [comment]
Thank you.

**Comment by ladyada** [comment]
ok great  @cotdp please update this PR :)

**Comment by cotdp** [comment]
Rebasing this on the latest from circuitpython/main and will re-open the pull request when ready.

**Pull request closed without merging**
