### PR TITLE
Add uploading a directory and its contents

### PR DESCRIPTION
**Pull request by tannewt**
This only works for one top level directory at a time.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
I like that subfolders being uploaded briefly show up in the Create Directory field, gives you a progress indication of sorts :). 

I manually merged this PR so perhaps I missed something but it looks like both the file selection and direction selection are both labeled "Choose Files".

**Comment by tannewt** [comment]
> I like that subfolders being uploaded briefly show up in the Create Directory field, gives you a progress indication of sorts :).

I added a progress bar now for the number of files that are done out of the total.

> I manually merged this PR so perhaps I missed something but it looks like both the file selection and directory selection are both labeled "Choose Files".

Ya, Firefox labels them differently. I added emoji labels to distinguish them.

Thanks again for testing!

**Comment by RetiredWizard** [comment]
Rebuilding your latest updates now, I didn't see any issue with recursive deletes in this version, I guess I was lucky.

I'll confirm once my poor little raspberry finishes the new build but on this version I just noticed that the directory "Choose Files" button is still active even when the !editable state is active (CIRCUITPY mounted). The interface goes through the motions but doesn't actually perform the upload.

**Comment by RetiredWizard** [comment]
The Folders "Choose Files" button is active even when CIRCUITPY is mounted. The upload doesn't work but the interface runs through the upload process just the same.

The progress bar doesn't do anything on a folder with a single file in it. That's not a problem, just an observation.

In the Developer Console I'm getting a number of timeout errors

image

It appears that if a folder only contains sub folders and no files then the upload doesn't work, even if the sub folders do contain files.  (/test/test2/2.bat)

image


On one upload I was moving the window around during the upload so focus was going in and out and along with the timeout errors I got a ERR_CONNECTION_RESET which seemed to crash the web workflow. No of the pages responded although I could connect to the REPL via the USB serial port. I don't know if this had anything to do with my moving the windows around or if it was just a fluke. I'll keep playing and see if it happens again.

image

**Comment by RetiredWizard** [comment]
I think the confirmation button on the pop-up window should be something other than "Upload". I tend to click it and think I'm launching the upload when there's actually another Upload button to click.

**Comment by RetiredWizard** [comment]
I managed to cause the ERR_CONNECTION_RESET error again by attempting to upload a single file while a larger folder upload was in progress, but it's not entirely repeatable.

**Comment by RetiredWizard** [comment]
Clicking on a folder and changing your current directory while an upload is occurring causes the upload to get confused and stop. 

Maybe it's obvious that while the upload is happening you shouldn't be clicking on anything else in the UI but it's clearly a bad idea :)

**Comment by RetiredWizard** [comment]
I turned off auto-reload and performed a folder upload. While the upload was underway I ran some python scripts via the USB serial REPL and the upload failed with an ERR_CONNECTION_RESET.

image

**Comment by RetiredWizard** [comment]
I deleted all the files from my microcontroller and made sure no code.py was running. The large folder upload then ran through without any of the timeout errors.

**Comment by RetiredWizard** [comment]
So I've been working this pretty hard for several hours and overall I think it's really solid. The things I've found this evening could easily be dealt with as issues after a merge.

The only troubling issue I've found so far is the occasional ERR_CONNECTION_RESET messages that usually correspond with the web workflow crashing. I haven't been able to reliable reproduce it yet but it really doesn't happen that often and I've been exercising the upload far harder than I think it will see in normal use.

With this and the rename, there's only one thing left I see missing from the whole workflow file management system and that is I don't see any easy way to move a large number of files say 20 or more to the root folder of a microcontroller via Web Workflow.

**Comment by tannewt** [comment]
Thanks again for all of the testing!

It is definitely a bug that mkdir fails when the parent is missing. I'll also tweak the disabled status of things to make it harder to have two uploads going at once. I'm not exactly sure how to deal with the timed out or connection reset errors. I'll keep an eye out for them.

**Comment by RetiredWizard** [comment]
Looks good, the folder with just folders uploads now, "Choose files" is not active either when CIRCUITPY is mounted or an upload is in progress and clicking the Upload button on the pop-up now starts the upload :)

The folder I've been uploading contains about 40 sub-folders and 70 data files and the microcontroller has about 70 files and 2 folders already in the root directory and another 40 files and a few more subfolders in the two root folders.  During my test folder upload I typically get around ten timeout errors but all the files seems to upload correctly. If I didn't have the developer console open, I wouldn't know there was an issue at all.

**Review by dhalbert — APPROVED** [review]
Took a quick look - approving without merging. @RetiredWizard Thanks again for all this testing!! @tannewt merge when you are ready.

**Pull request merged**
