### PR TITLE
displayio: Add lightweight Rectangle

### PR DESCRIPTION
**Pull request by WarriorOfWire**
Shape uses a bitmap to represent blocked regions.  This is fine
  for some shapes, but others may be more compactly represented.

This lets users make large, possibly overlapping areas of their screen be colored without running out of memory due to bitmap arrays in adafruit_display_shapes.Rect.

image

Used like:
```
palette = displayio.Palette(1)
palette[0] = 0x001100
bitmap_grid = displayio.TileGrid(
    displayio.Rectangle(320, 220),
    pixel_shader=palette,
    x=0,
    y=20,
)
display_group.append(bitmap_grid)
```

### CODE REVIEW

**Comment by WarriorOfWire** [comment]
Investigating hallowing memory and alternate shape ideas.

**Comment by k0d** [comment]
The error in the building isn't down to your code, it's something to do with the Korean font. I don't know much about that, but I just wanting to let you know it wasn't your code.

**Comment by WarriorOfWire** [comment]
Thanks for letting me know.  I'll work something else out.

**Comment by tannewt** [comment]
You could split Rectangle out into a `shapes` module or similar and only include it on larger boards. M0 boards are basically out of space for new features.

**Pull request closed without merging**
