### PR TITLE
Improve usb.core.Device exception handling and reporting

### PR DESCRIPTION
**Pull request by samblenny**
This PR includes a fix for the null pointer dereference from issue #9670 and adds short error message strings to help distinguish between different types of usb.core.USBError exceptions.

I understand that adding unique strings to the core is generally problematic, but I don't know how to avoid it in this case. For writing USB device drivers, it's very helpful to be able to identify the specific causes of the different types of exceptions that get grouped together under USBError. If there were a way to set the value of USBError.errno, that would be ideal. But, my understanding is that errno is generally not supported in MicroPython. Maybe I'm wrong about that?

In my test builds, these changes add about 132 bytes to the used flash firmware space for `BOARD=adafruit_feather_esp32s3_tft`. Shortening the "Pipe error" and "No configuration set" messages saved about 16 bytes. When I experimented with using single character strings vs. 4-5 character strings, it didn't seem to save any additional space.

### CODE REVIEW

**Comment by samblenny** [comment]
I added a fix for the failing pre-commit check (translation file needed changes). I'm not convinced that my approach here of adding error strings and updating the translation file is the right way to solve the problem of distinguishing types of USB errors. If there were a way to set USBError.errno, I would prefer to do that. But, I don't know if or how that would be possible.

**Comment by dhalbert** [comment]
@samblenny Did you just do `make translate` at the top level? That updates `circuitpython.pot` programmatically. You should not need to edit `circuitpython.pot` by hand.

**Comment by samblenny** [comment]
I'm new to this. When I looked around for possible ways of invoking the translation pre-commit hook (skipped normally), the best looking documentation option I found was to run `pre-commit run --all-files` as mentioned in https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit. So, that's what I did.

**Comment by samblenny** [comment]
I tried running `make translate` just now, and it didn't appear to make any additional changes.

**Comment by dhalbert** [comment]
> I tried running `make translate` just now, and it didn't appear to make any additional changes.

Probably what you did was equivalent. But when pre-commit complains, just run `make translate` and commit those changes. We should put that in a message somewhere (though I thought that was somwhere already).

**Comment by samblenny** [comment]
tannewt, I know you're pressed for time at the moment and probably don't have much bandwidth to discuss this. If you have any concerns about the error messages, I'd be happy to add a commit putting them back like they were before (leaving the just the changes to fix the null pointer dereferences).

**Review by tannewt — CHANGES_REQUESTED** [review]
Sorry for not getting back to you! Yes, I'd prefer to back out the error changes. The new messages aren't very actionable for users. It's fine for debugging but I wouldn't leave them. The cost of leaving them is translation and firmware size.

**Comment by samblenny** [comment]
> ... I'd prefer to back out the error changes...

ok. sounds good. will try to get you a new commit soon.

**Comment by samblenny** [comment]
Just pushed a commit to remove the error message changes. Now the remaining changes are limited exclusively to avoiding null pointer dereferences.

**Review by tannewt — APPROVED** [review]
Thanks! I poked the CI so it'll retry.

**Comment by dhalbert** [comment]
The only build failure was readthedocs. I removed `get_html_theme_path()` from `conf.py`, which is the same fix we just had to do to all the libraries.

**Review by tannewt — APPROVED** [review]
Thanks @dhalbert !

**Pull request merged**
