### PR TITLE
ESP32S2: Support for WatchDog

### PR DESCRIPTION
**Pull request by microDev1**

### CODE REVIEW

**Comment by tannewt** [comment]
cc @astrobokonon

**Comment by microDev1** [comment]
```python
from microcontroller import watchdog as w
from watchdog import WatchDogMode
import time

# Set a timeout of 10 seconds
w.timeout=10
w.mode = WatchDogMode.RESET

# Removing w.feed causes a watchdog reset
while True:
    w.feed()
    time.sleep(5)
```

**Review by tannewt — DISMISSED** [review]
Looks good to me! Is there more you want to add?

**Comment by microDev1** [comment]
@tannewt Yes... I have to figure out a way to differentiate between `RAISE` & `RESET` modes in `esp_task_wdt_isr_user_handler(void)` which is called on watchdog interrupt.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Pull request merged**
