### PR TITLE
update ESP32S3 camera to rev D

### PR DESCRIPTION
**Pull request by ladyada**
Hardware pin changes

### CODE REVIEW

**Review by jepler — APPROVED** [review]
merge if green :)

**Comment by jepler** [comment]
```
boards/adafruit_esp32s3_camera/board.c:90:9: error: passing argument 19 of 'common_hal_busdisplay_busdisplay_construct' makes pointer from integer without a cast [-Werror=int-conversion]
   90 |         45,  // backlight pin
      |         ^~
      |         |
      |         int
In file included from ../../shared-module/displayio/__init__.h:28,
                 from boards/adafruit_esp32s3_camera/board.c:33:
../../shared-bindings/busdisplay/BusDisplay.h:44:78: note: expected 'const mcu_pin_obj_t *' but argument is of type 'int'
   44 |     uint8_t *init_sequence, uint16_t init_sequence_len, const mcu_pin_obj_t *backlight_pin, uint16_t brightness_command,
      |                                                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
```
the argument needs to be something like &pin_GPIO45, not just the number.

**Comment by tannewt** [comment]
I think the branch needs the newer changes from adafruit/main merged in to fix the build.

**Comment by jepler** [comment]
I merged main to this PR branch

**Review by jepler — DISMISSED** [review]
now is green! mark out of draft when ready

**Comment by ladyada** [comment]
thanks! i was about to sit down and figure this out and its done for me <3 it :)

**Review by tannewt — APPROVED** [review]
Thanks!

**Pull request merged**
