### PR TITLE
pewpew m4: enable CDC back

### PR DESCRIPTION
**Pull request by deshipu**
CDC got disabled on this board by mistake

### CODE REVIEW

**Comment by deshipu** [comment]
This should fix #7498 7498

**Comment by dhalbert** [comment]
@deshipu Now some languages  don't quite fit. These are the included modules from the last RTD build:
```
_stage, analogio, array, audiocore, audioio, audiomixer, board, builtins, busio, collections, digitalio, displayio, fontio, keypad, math, microcontroller, nvm, os, random, storage, struct, supervisor, synthio, sys, terminalio, time, watchdog, zlib

Frozen Modules: pew, stage, ugame
```

There are some specialized disablers you could use:
```
CIRCUITPY_BUSIO_SPI = 0         no busio.SPI
CIRCUITPY_BUSIO_UART = 0     no busio.UART
```
Also this can squeeze some space:
```
CIRCUITPY_COMPUTED_GOTO_SAVE_SPACE = 1
```

**Comment by FoamyGuy** [comment]
We could try disabling zlib with `CIRCUITPY_ZLIB = 0` instead of current `1`. 

I didn't check all the languages, but did try a few and got successful builds from this branch with the change to disable zlib.

**Comment by deshipu** [comment]
@FoamyGuy I need zlib to decode png images.
@dhalbert I think we can disable analogio, I will update the PR.

**Comment by deshipu** [comment]
Also disabled watchdog

**Review by dhalbert — APPROVED** [review]
Thanks for the quick work on this. It will be in rc.0.

**Pull request merged**
