### PR TITLE
Add default I2C pins for STM32F411CE

### PR DESCRIPTION
**Pull request by djix123**

### CODE REVIEW

**Comment by ladyada** [comment]
hmm does the blackpill have markings for i2c? how'd these pins get picked? im for this PR, just wanna make sure we are consistant :)

**Comment by hierophect** [comment]
Hi @djix123, thanks for the PR! The Blackpill does not have silkscreen markings for a default I2C channel, and there are actually 8 different equally viable combinations of I2C outputs on the pins it exposes. We don't typically mark pins as default unless they are clearly outlined on the silkscreen as such.

If you selected these pins for compatibility with python sketches written for the Feather F405, please note that:
`myi2c = board.I2C()` 
is functionally identical to:
`myi2c = busio.I2C(board.B6, board.B7)`
I'd recommend you use the second in your blackpill projects.

Do you have any other reasons for suggesting this change?

**Comment by ladyada** [comment]
could be because we have `board.I2C()` in many example codes and they have a confusing error that folks may think means I2C is not supported. (i am not a big fan of `board.I2C()` for this reason even though it is easier to read )

**Comment by djix123** [comment]
Yes, @ladyada - added them because of the many examples that use board.I2C() ... the actual pins chosen - board.B6/board.B7 are the defaults that the STM32 Arduino core chooses for this board.

**Comment by ladyada** [comment]
i guess thats ok then! better than nothing :D

**Review by ladyada — APPROVED** [review]

**Pull request merged**
