### PR TITLE
.github: update actions to versions that use Node.js 20

### LINKED ISSUE #8832: .github: update actions to use Node.js 20
A [recent PR run](https://github.com/adafruit/circuitpython/actions/runs/7643094513?pr=8830) complained:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4, actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

We may be able to depend on these actions being updated, or we may need to bump the versions on the actions. Need to research each one.

The deadline is "Spring 2024".

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #8832.

`checkout@v4` has a new `show-progress: true|false` option that allows suppressing progress lines, which can make a log a lot longer. Sounded good to me, so I added `progress:false` everywhere it was used.

`upload-artifact@v4` and `download-artifact@v4` [have been completely rewritten, with some upward incompatibilities](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/). I think they should still work for us, though.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by jepler** [comment]
the doc build error:
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

It is now an error for two different steps to upload artifacts with the same name. Some people do it on purpose, though I do not know whether we do or not. I imagine the change was made out of belief that it was an error that should be diagnosed.

the silabs error is the usual spurious build error, which remains not fully understood.

**Comment by dhalbert** [comment]
I opened this issue: https://github.com/carlosperate/arm-none-eabi-gcc-action/issues/49 to ask for that action to be updated. We could submit a PR too.

I may also make the -j4 change here too: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

**Comment by dhalbert** [comment]
> It is now an error for two different steps to upload artifacts with the same name.

I fixed this, now it builds `doc-html` and `doc-latexpdf`, instead of two `doc`s.

**Comment by dhalbert** [comment]
I took out the `PARALLEL` stuff in `tools/build_release_files.py` because it wasn't actually used anywhere.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
