### PR TITLE
Feathers2 nsync

### PR DESCRIPTION
**Pull request by askpatrickw**
This is draft because I'm not sure of the commits from pull cp/main.

The changes though are to being the FeatherS2 files NSync with the only changes being the actual changes between the two boards.

I have tested board.I2C() works on the pre-release.

### CODE REVIEW

**Comment by askpatrickw** [comment]
I'm up for cleaning up the commit history, but the changes are just what were expected. Ready for Review.

**Comment by ladyada** [comment]
@unexpectedmaker please take a look!

**Review by UnexpectedMaker — CHANGES_REQUESTED** [review]
Thanks for doing this @askpatrickw 
IO13 is still in pins.c twice for FeatherS2 and Prerelease - lines 93 & 12
Please remove lines 93 in both files
Cheers
Seon

**Comment by askpatrickw** [comment]
@UnexpectedMaker This last commit fixes that dupe IO13 and removes some whitespace.

**Review by UnexpectedMaker — APPROVED** [review]
I just found out why IO13 was in there twice. One was supposed to be IO14 - Seems I have an incorrect label on my silk and pinout card. 
@tannewt Can this please be merged, so I can fix the IO13/IO14 issue for the next update?
Thanks :)

**Review by ladyada — APPROVED** [review]

**Comment by UnexpectedMaker** [comment]
Thanks @ladyada :)

**Pull request merged**
