### PR TITLE
Creating config files for Seeed Xiao ESP32-S3 Sense Board

### PR DESCRIPTION
**Pull request by djairjr**
Trying to comply with Seeed Spreedsheet in wiki.
https://files.seeedstudio.com/wiki/SeeedStudio-XIAO-ESP32S3/res/XIAO_ESP32S3_Sense_Pinout.xlsx

Added camera pinout and remove unused pins.

### CODE REVIEW

**Review by djairjr — COMMENTED** [review]
Removed CIRCUITPY_ESPCAMERA = 1 not working with Seeed Xiao ESP32-S3 Sense

**Review by djairjr — COMMENTED** [review]
Configuring PSRAM in order to give Camera suport

USB_VID = 0x303A
USB_PID = 0x1001
USB_PRODUCT = "Seeed Xiao ESP32-S3 Sense"
USB_MANUFACTURER = "Seeed Studio"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

CIRCUITPY_ESP_PSRAM_MODE = qio
CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_FREQ = 80m

**Comment by deshipu** [comment]
> Removed CIRCUITPY_ESPCAMERA = 1 not working with Seeed Xiao ESP32-S3 Sense

What is not working exactly? I had it working in 8.x. Even it there is a bug that makes it not work right now, I think it should be still enabled and the bug fixed?

**Comment by deshipu** [comment]
By the way, there is an old PR for that board: https://github.com/adafruit/circuitpython/pull/8095

**Comment by djairjr** [comment]
I think that the real problem is the PSRAM settings.
Now appears to be working. I will add CIRCUITPY_ESPCAMERA = 1 again and see if it works;

**Comment by deshipu** [comment]
The pre-commit is failing on extra white space at the ends of the lines in pins.c

**Comment by djairjr** [comment]
How can I change that? I am using notepad ++ to change files here.

**Comment by deshipu** [comment]
Just delete the extra spaces.

**Comment by djairjr** [comment]
I think now I've done. Sorry for this. Is my first time doing this.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please get a unique PID for this board instead of using the generic one. https://github.com/espressif/usb-pids

**Comment by djairjr** [comment]
> Please get a unique PID for this board instead of using the generic one. https://github.com/espressif/usb-pids

I'm sorry, but this is what appears when I follow the steps outlined here: https://superuser.com/questions/1106247/how-can-i-get-the-vendor-id-and-product-id-for -a-usb-device

I think this is something that Seeed Studio should address?

**Comment by deshipu** [comment]
> I think this is something that Seeed Studio should address?

Yes, we asked them for it on their forum, at https://forum.seeedstudio.com/t/usb-vid-pid-for-the-xiao-esp32-s3-and-xiao-esp32-s3-sense-for-circuitpython/272245/10 but either they don't understand, or they are not interested.

**Comment by tannewt** [comment]
I give out USB PIDs for open source software on third-party boards from https://pid.codes too. Make sure to link to your branch of CircuitPython with the changes.

**Comment by deshipu** [comment]
To make this work in 9.1 the following needs to be added to mpconfigboard.mk:

```make
CIRCUITPY_ESP_PSRAM_SIZE = 8MB
CIRCUITPY_ESP_PSRAM_MODE = opi
CIRCUITPY_ESP_PSRAM_FREQ = 80m
```

**Comment by djairjr** [comment]
Guys, about VID and PID from Seeed, read this: 
https://github.com/adafruit/circuitpython/issues/9507#issuecomment-2298119726

Seeed Xiao ESP32-S3
VID: 0x2886
PID: 0x8056

**Pull request closed without merging**
