### PR TITLE
Add bytearray.decode() for CPython compatibility

### PR DESCRIPTION
**Pull request by theacodes**
CPython has a `decode()` method on `bytearray`. This adds that method using the code from `bytes.decode`.

Test program:

```python

byte_boi = bytes([0x6D, 0x65, 0x65, 0x70])
print(byte_boi)  # b'meep'
byte_boi_str = byte_boi.decode("utf-8")
print(byte_boi_str)  # meep

byte_array_boi = bytearray(byte_boi)
print(byte_array_boi)  # bytearray(b'meep')
byte_array_boi_str = byte_array_boi.decode("utf-8")
print(byte_array_boi_str)  # meep

print(byte_array_boi_str == byte_boi_str)  # True

```

### CODE REVIEW

**Comment by tannewt** [comment]
Does this unintentionally add it to `array` objects as well? It shouldn't.

For CPython:
```
>>> import array
>>> byte_boi = bytes([0x6D, 0x65, 0x65, 0x70])
>>> a = array.array("B", byte_boi)
>>> a.decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'array.array' object has no attribute 'decode'
```

**Comment by dhalbert** [comment]
Also note this, though I'm not sure whether it's relevant: https://github.com/adafruit/circuitpython/issues/384

**Comment by theacodes** [comment]
@tannewt made it where decode only applies to `bytearray`.

```python
print(dir(array.array))
# ['__class__', '__name__', 'append', 'extend']
print(dir(bytearray))
# ['__class__', '__name__', 'append', 'decode', 'extend']
```

**Comment by theacodes** [comment]
As I feared, giving bytearray a separate locals table pushed some of the smaller boards over capacity. :(

**Comment by dhalbert** [comment]
I shrank the crickit build. Let's see if it works.

**Comment by theacodes** [comment]
Thanks, @dhalbert

**Comment by dhalbert** [comment]
I'm pretty puzzled by this. I checked out the exact same commit locally (a3ca9401b4eab35d4fa3190141d576bcd059d070z_, and my builds are about 500 bytes smaller, and they fit. I'm using the same `arm-none-eabi-gcc`. My regular gcc is newer, but that's just for mpy-cross and shouldn't matter.

**Comment by dhalbert** [comment]
@tannewt it builds now; I think you already took a look so if it's easy for you to finish the review go ahead

**Pull request merged**
