### PR TITLE
Add RP2040-Tiny

### PR DESCRIPTION
**Pull request by bill88t**
Another weird board. The USB port is detachable.
Looks almost identical to RP2040-Zero, but has less pins exposed.

USB pid:vid [pending](https://github.com/raspberrypi/usb-pid/pull/11).

### CODE REVIEW

**Comment by tannewt** [comment]
I think you'll need to fill out a form instead of making a PR to that repo.

**Comment by bill88t** [comment]
I saw the form, however it requires company info and stuff.
And since I'm not the board manufacturer I can't do that.
I'm at least hopeful it can be done with a PR, since there have been [others added like that](https://github.com/raspberrypi/usb-pid/pull/9).

**Comment by coffandro** [comment]
> I saw the form, however it requires company info and stuff. And since I'm not the board manufacturer I can't do that. I'm at least hopeful it can be done with a PR, since there have been [others added like that](https://github.com/raspberrypi/usb-pid/pull/9).

that seems to be on the main RP repo, not circuitpython?

**Comment by bill88t** [comment]
> that seems to be on the main RP repo, not circuitpython?

Yes, that PR is directed towards RP, for a product id (PID) from their vendor id (VID, 0x2E8A).
For a proper CircuitPython port we need to have a unique VID:PID for every board that exposes USB.

**Comment by coffandro** [comment]
ah okay, that makes sense

**Comment by ghollingworth** [comment]
> Yes, that PR is directed towards RP, for a product id (PID) from their vendor id (VID, 0x2E8A). For a proper CircuitPython port we need to have a unique VID:PID for every board that exposes USB.

Is that really true?  Why do you _need_ to have a unique VID:PID?  Why can't you instead have a standard VID:PID for a particular piece of silicon and identify the board through the Product ID?

**Comment by dhalbert** [comment]
> Is that really true? Why do you _need_ to have a unique VID:PID? Why can't you instead have a standard VID:PID for a particular piece of silicon and identify the board through the Product ID?

I'm not sure what you're suggesting here. The "Product ID" is the "PID". The RP2040 chip itself presents a single VID:PID because it has a built-in bootloader in ROM. But when the board is running Arduino or CircuitPython, it presents an Arduino-specific VID:PID or a CircuitPython-specific VID:PID for that particular kind of board. So a Pico and an Adafruit RP2040 have different Arduino and CircuitPython VID:PIDs. The different VID:PID for each kind of board allow an IDE or other external software to identify the kind of board.

**Comment by tannewt** [comment]
> Is that really true? Why do you _need_ to have a unique VID:PID? Why can't you instead have a standard VID:PID for a particular piece of silicon and identify the board through the Product ID?

Host OSes (like Windows) may cache the USB information based on the VID:PID combination. For Adafruit boards we usually do one PID per board x software combination to ensure that caching isn't triggered.

**Comment by ghollingworth** [comment]
Sorry I wasn't being clear, the iProduct field in the device descriptor defines the product string descriptor.  You could use a single VID/PID descriptor for a particular device, then use the product string descriptor to identify the specific board.  

This is the way the ARM CMSIS-DAP works, it just needs "CMSIS-DAP" in the product string descriptor and OpenOCD will automatically detect the device.

**Comment by bill88t** [comment]
Drafting till I get the usb pid:vid, since it may take a while.

**Comment by bill88t** [comment]
Got a VID.

**Review by dhalbert — APPROVED** [review]
Thanks for your patience!

**Pull request merged**
