### PR TITLE
STM32: rename feather_stm32f405_express, fix makefile defs issue

### PR DESCRIPTION
**Pull request by hierophect**
This PR changes the Feather for the F405 to use a clearer name, matching it with its aws bucket. It also removes a tinyusb makefile define that was quietly overriding the frequency of the feather and pyboard, which has been fixed in upcoming PRs but should probably go live ASAP.

### CODE REVIEW

**Comment by hierophect** [comment]
We should let CI run on this first, sometimes it gets huffy about changes to the yml. I don't think I missed anything this time, though.

**Comment by ladyada** [comment]
yep dont merge till it passes!

**Comment by dhalbert** [comment]
> It also removes a tinyusb makefile define that was quietly overriding the frequency of the feather and pyboard, which has been fixed in upcoming PRs but should probably go live ASAP.

I am not sure what you mean by this. Do you mean it's fixed in some upcoming PR's of yours, or in tinyusb?

**Comment by hierophect** [comment]
@dhalbert in the tusb makefile defines (which were one of the first things added to the port) there was this line `-DHSE_VALUE=8000000` which I guess was in there because tusb examples don't use the HAL_CONF file that's standard for most STM32 implementations. This was quietly overriding the HAL value and messing up a lot of frequency stuff, but it doesn't explicitly break anything until you start using UART and PWM. 

I've included it here since support for the feather and pyboard is a little more "official" now and I don't want people encountering the wrong frequency if PWM somehow takes a long time to merge.

**Comment by hierophect** [comment]
Actually, it is in the BSPs for tusb... I'm not sure why Thach puts it in all his makefiles.

**Comment by dhalbert** [comment]
> Actually, it is in the BSPs for tusb... I'm not sure why Thach puts it in all his makefiles.

Would be fine to ask that in a tinyusb issue.

**Comment by dhalbert** [comment]
I tapped "Merge" on my phone, not sure why it didn't merge :)

**Pull request merged**
