### PR TITLE
Add file and directory renaming

### LINKED ISSUE #6647: Add move support to the web workflow

### PR DESCRIPTION
**Pull request by tannewt**
Internally this is done with a MOVE HTTP verb. It is modeled after
WebDAV MOVE but not exact to keep the Destination header shorter
and have more consistent response codes.

Fixes #6647

### CODE REVIEW

**Comment by RetiredWizard** [comment]
If you clear the "rename to" field and then press cancel the file is renamed to null.

**Comment by RetiredWizard** [comment]
I'm a little disappointed that the edit option has gone away for unknown file types. I know editing a .mpy file didn't make much sense but it didn't crash anything and it was useful to be able to edit files like "menu.bat" or ".env"

**Comment by RetiredWizard** [comment]
Probably can just add to the known file types as we go though. .env is really the only file type I can think of right know that needs to be added.

**Comment by RetiredWizard** [comment]
Was the lack of any error reporting (target file exists, move to nonexistent folder) intentional?  The rename seems to do the right thing in these cases which is nothing :)

**Comment by tannewt** [comment]
> If you clear the "rename to" field and then press cancel the file is renamed to null.

Haha, oops. Thanks for the testing!

> I'm a little disappointed that the edit option has gone away for unknown file types. I know editing a .mpy file didn't make much sense but it didn't crash anything and it was useful to be able to edit files like "menu.bat" or ".env"

This is just the link. You can create the link yourself and the edit page won't be wiser. I did add .env support now.

> Was the lack of any error reporting (target file exists, move to nonexistent folder) intentional? The rename seems to do the right thing in these cases which is nothing :)

I'm hesitant to add it because it'll add a lot of strings to the code. We can see what folks say when using it.

**Review by dhalbert — APPROVED** [review]
This looks ok by me. `_decode_percents` looks like it will give you garbage if the input string is truncated and doesn't have a second character after a `%`, but that doesn't really matter, I think.

I will leave use testing to @RetiredWizard.

**Comment by RetiredWizard** [comment]
The null file rename issue is fixed, I've tried to break it everyway I can think of but I think I'm stumped :)

**Pull request merged**
