### PR TITLE
Tweak pybadge and fix display bugs

### PR DESCRIPTION
**Pull request by tannewt**
* Update pybadge pins and flash for rev D
* TileGrid now validates the type of the pixel_shader.
* Display actually handles incoming subclass objects.
* MicroPython will inspect native parents to see if special accessors are used.

### CODE REVIEW

**Comment by dhalbert** [comment]
I cancelled this build because it needs PR #1775 to finish successfully. Once #1775 is merged this can be restarted.

**Comment by dhalbert** [comment]
Build restarted.

**Comment by dhalbert** [comment]
Two classes of build errors:
1. Test errors due to new subclass stuff, I think. See build .1
2. itsy_bitsy_m0_express too large for pl translation

**Comment by dhalbert** [comment]
PyBadge tweaks are same as in #1777, so I'll go ahead and merge that. No regression issues on that.

**Comment by tannewt** [comment]
@dhalbert Build is working now. Needed to check for NULL.

**Pull request merged**
