### PR TITLE
Port Arduino MKR1010 and NINAESP32 error

### PR DESCRIPTION
**Pull request by sabas1080**
Hi @tannewt 

I am trying to port the mkr1010 together with the esp32_spi library

I have changed firmware wifinina of adafruit in the ESP32, but i have the next error

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 309, in status
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 298, in _send_command_get_response
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 224, in _send_command
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 221, in _send_command
RuntimeError: ESP32 timed out on SPI select
```

Thanks

### CODE REVIEW

**Comment by ladyada** [comment]
we use different pins on the ESP32 firmware i think GPIO23 not GPIO12 so you need to use their firmware which has that pinout - but, honestly, i do not think samd21 can handle the WiFi core - it uses a lot of memory once you try to actually connect to sites :/

**Comment by sabas1080** [comment]
Oh ok the problem is MOSI in MKR is GPIO12 and in nina_adafruit is GPIO14 of the ESP32, but with arduino firmware it did not work either 🤔 - recommend WiFi Core only in samd51 or memory SPI in SAMD21 fine?

**Comment by ladyada** [comment]
yeah SAMD51 or nrf52840 recommended! not sure why MKR1010 isnt' working for you either

**Comment by tannewt** [comment]
@sabas1080 Do you still want to merge this?

**Comment by tannewt** [comment]
Please reopen this PR or make a new one if you want the MKR1010 merged in. I believe it's blocked on getting wifi going at the moment.

**Comment by sabas1080** [comment]
Yes, Insufficient memory, thanks

**Pull request closed without merging**
