### PR TITLE
add pin def for BAT

### LINKED ISSUE #1149: Add a BATTERY pin to board pins
`BATTERY` was already added to the hallowing, but `BATTERY` is not an alias for `D9` on Feathers. Would be convenient so you don't have to remember which pin. Suggested by @jedgarpark and @caternuson.

### PR DESCRIPTION
**Pull request by sajattack**
Fixes #1149

### CODE REVIEW

**Comment by dhalbert** [comment]
Build errors on itsy_bitsy_m4_express: https://travis-ci.org/adafruit/circuitpython/jobs/441508064#L1143

**Comment by sajattack** [comment]
Ok. I looked at the [schematic](https://cdn-learn.adafruit.com/assets/assets/000/057/242/original/arduino_compatibles_schem.png?1531010817) and it looks like PB01 was the correct pin connected to the BAT pin. Do I have to define it somehow?

**Comment by dhalbert** [comment]
@sajattack That schematic is for the Feather M4, which uses the 64-pin SAMD51J19. The Itsy Bitsy uses the 48-pin SAMD51G19. I don't see any voltag monitoring stuff on the Itsy M4. Schematic here: https://learn.adafruit.com/introducing-adafruit-itsybitsy-m4/downloads.

Neither the Itsy M0 nor M4 have a voltage divider for monitoring. So remove the BATTERY pin from the Itsy M0 as well, in your changes.

**Comment by tannewt** [comment]
Thank you!

**Pull request merged**
