### PR TITLE
Feather ESP32-S2 Reverse TFT: Update PID to match internal list

### PR DESCRIPTION
**Pull request by jepler**
@ladyada please check this and leave a review so it's right this time :)

### CODE REVIEW

**Comment by ladyada** [comment]
yes!

**Comment by dhalbert** [comment]
@jepler I'm confused, now there is a dupe between:
`adafruit_feather_esp32s2_reverse_tft`
and
`adafruit_feather_esp32s2_tftback_nopsram`

**Comment by ladyada** [comment]
adafruit_feather_esp32s2_tftback_nopsram was never/will never be made

**Comment by jepler** [comment]
@dhalbert should we remove the other board definition (it's been there for quite awhile!) or permit the duplicate ID?

**Comment by dhalbert** [comment]
Let's remove `adafruit_feather_esp32s2_tftback_nopsram`, and any sign of it on circuitpython.org.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
