### PR TITLE
Update documentation for microprossors with multiple cpus

### PR DESCRIPTION
**Pull request by DavePutz**
Added documentation for microprocessor module when chip has multiple cpus.

### CODE REVIEW

**Comment by jepler** [comment]
Alternately, maybe .cpu should be the current CPU, and a new list property .cpus should be added.  As it is, the way microcontroller.cpu is defined on rp2040 is a backwards incompatibility.

**Comment by DavePutz** [comment]
I understand what you are saying about incompatibility; the current
implementation breaks microcontroller.cpu (i.e.
a script that works on other platforms will get errors on an MP2040). But
since there currently doesn't seem to be
a way to get the id of your current CPU, I'm not sure that using .cpu for
the current CPU is very useful - you won't
know which CPU you are looking at. Would it be possible to implement it so
that  microcontroller.cpu always gives you
cpu 0, but if you want other cpus you could still use
microcontroller.cpu[1]?

**Comment by tannewt** [comment]
I'm open to cpu or cpus. One thing to think about is controlling the second CPU from the first. My interest is to use SWD to control small assembly code running on the second core.

@DavePutz Thanks for updating these docs.

**Comment by dhalbert** [comment]
I like `cpus` because it down't overload the existing `.cpu` attribute.

**Comment by dhalbert** [comment]
There could be a new `.cpu.index` or `.cpu.number` property to tell you the number of the current cpu.

**Comment by DavePutz** [comment]
I don't have any problem with adding attributes (such as .cpus or
cpu.index). The question remains,
though, about what to do with microcontroller.cpu on an multi-core chip?
Should it return cpu 0, the
current cpu, or throw an error?

**Comment by tannewt** [comment]
@DavePutz Current cpu I think.

**Comment by DavePutz** [comment]
OK, I will work on a patch to implement things that way and see about
adding a microcontroller.cpus
attribute. Would you prefer  microcontroller.cpus to take an argument for
cpu id or use an index?

**Comment by tannewt** [comment]
@DavePutz index like I switched cpu to.

**Comment by jepler** [comment]
Closing this since we settled on a different resolution

**Pull request closed without merging**
