### PR TITLE
Spi enhancements

### LINKED ISSUE #4494: another problem with busdevice-in-core and bitbangio?
I found that with the following code, the with-statement is never entered (circuitpython waits forever).  However, if I change the type of spi bus to board.SPI() aka busio.SPI, it completes.

```python
# spi = board.SPI()
spi = bitbangio.SPI(board.SCK, MISO=board.MISO, MOSI=board.MOSI)
cs = digitalio.DigitalInOut(board.D10)
dev = adafruit_bus_device.spi_device.SPIDevice(spi, cs)
print("before with-statement")
with dev as card:
    print("with-statement")
print("after with-statement")
```

### PR DESCRIPTION
**Pull request by jepler**
This required both adding support for the "default write value" in bitbangio.SPI, and also supporting duck-typing in adafruit_bus_device's SPIDevice which, surprisingly, was overlooked when we fixed I2C.

Now, the following code works, tested on RT1010-EVK:

```python
import os
import board
import bitbangio
import adafruit_sdcard
import storage
import digitalio

spi = bitbangio.SPI(board.SCK, MISO=board.MISO, MOSI=board.MOSI)
cs = board.D10
sdcard = adafruit_sdcard.SDCard(spi, digitalio.DigitalInOut(cs))
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")
print(os.listdir("/sd"))
```

Closes #4494.

### CODE REVIEW

**Review by gamblor21 — APPROVED** [review]
Looks good to me. I haven't tested it, I can try just have to see if I have a display with an SD card on the back laying about somewhere.

**Comment by ladyada** [comment]
will test when there's artifacts!

**Comment by ladyada** [comment]
verified with a TFT shield on a metro m7!

**Comment by ladyada** [comment]
also verified with a teensy 4.1's SDIO card slot

**Pull request merged**
