### PR TITLE
Teknikio Bluebird Support

### PR DESCRIPTION
**Pull request by JoeBakalor**
Added support for the Teknikio Bluebird https://www.teknikio.com/pages/bluebird

### CODE REVIEW

**Comment by ladyada** [comment]
i only did initial 'style' review, needs to pass CI before merging

**Comment by ladyada** [comment]
ill let @dhalbert or @tannewt do secondary review/merge. note the internal filesystem on the nrf52840 is not working very well at this time!

**Comment by dhalbert** [comment]
> note the internal filesystem on the nrf52840 is not working very well at this time!

We believe this is fixed as of #2376.

**Comment by ladyada** [comment]
oh yay :) 
@JoeBakalor please also PR into https://github.com/adafruit/circuitpython-org so it appaers on the download page

**Comment by JoeBakalor** [comment]
Awesome! I'll submit a PR https://github.com/adafruit/circuitpython-org

**Pull request merged**
