### PR TITLE
Add support for Spotpear ESP32C3 w/ 1.44" LCD.

### PR DESCRIPTION
**Pull request by SeanTheITGuy**
https://spotpear.com/index/product/detail/id/1354.html

Adds support for this ESP32C3 based device with a SPI 1.44" LCD built in. Device has 3 user programmable buttons and a 2.54mm pin header with 5 user GPIO pins for additional peripherals.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by gabriel-gagnon** [comment]
Hi @SeanTheITGuy 

I tried to flash my _Spotpear ESP32C3 LCD 1.4_ device with the version 9.2.3 of CircuitPython from that link:
[https://circuitpython.org/board/spotpear_esp32c3_lcd_1_44].   After a small fix on the CircuitPython site, I was able to flash it.  However, it seems that the firmware makes the board rebooting over and over, with the following errors:
```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40383246
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x120
load:0x403cc710,len:0x900
load:0x403ce710,len:0x2178
entry 0x403cc710
```
I asked the following question on the CircuitPython forum [https://forums.adafruit.com/viewtopic.php?t=216227].

Do you have an idea what could be making the board rebooting?
Are you experiencing the same with yours?

Thank you very much! Have a great day!

**Comment by SeanTheITGuy** [comment]
@gabriel-gagnon Can confirm this is not your problem. 9.2.3 does NOT work on this board.  It results in, exactly as you say, a boot loop.
I went through the older versions, and it worked up to 9.2.1, but something was introduced in 9.2.2 that causes this issue.

https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/spotpear_esp32c3_lcd_1_44/en_US/

If you can grab 9.2.1 from there and flash, you'll most likely find it works perfectly.  I'm not sure what issue might have been introduced, but I will take a cursory glance when time allows, or hopefully someone with more knowledge than I will.  I will file an issue tomorrow.

**Comment by gabriel-gagnon** [comment]
Thanks @SeanTheITGuy for your extremely fast feedback!
I'll have a try tomorrow or on Sunday.
Thank you very much!

**Comment by gabriel-gagnon** [comment]
Thanks @SeanTheITGuy for the proposed [fix](https://github.com/adafruit/circuitpython/pull/9997).

**Pull request merged**
