### PR TITLE
Make `next_code_allocation` and `prev_traceback_allocation` movable

### PR DESCRIPTION
**Pull request by microDev1**
Changes in this PR:
- move the allocations to movable group.
- revert https://github.com/adafruit/circuitpython/commit/ff807f8f19a991c1aba7504b8ba17023ee738fa6 which made the allocations immovable.

### CODE REVIEW

**Comment by jerryneedell** [comment]
This does fix #5332 
```
ode done running.
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-rc.1-62-g7316c742c on 2021-09-12; Adafruit Feather M4 Express with samd51j19
>>> import supervisor
>>> supervisor.get_previous_traceback()
'Traceback (most recent call last):\r\n  File "code.py", line 56, in <module>\r\n  File "adafruit_rfm9x.py", line 788, in receive\r\n  File "adafruit_rfm9x.py", line 638, in rx_done\r\nKeyboardInterrupt: \n'
>>> 
```

**Review by dhalbert — APPROVED** [review]
Not tested by me, but looks good, and now it's all internally consistent.

**Comment by dhalbert** [comment]
Thank you @jerryneedell for testing.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Oh, bleah, I did not see the build failures. A few small builds with lots of pins are just over the flash size.

**Comment by microDev1** [comment]
> A few small builds with lots of pins are just over the flash size.

Moving allocations to movable group leads to the inclusion of [`supervisor_move_memory()`](https://github.com/adafruit/circuitpython/blob/cf5c32be3b3708035271ee264f978207ce928dd1/supervisor/shared/memory.c#L244) on every build.

**Comment by dhalbert** [comment]
@microDev1 I have a `Makefile` change that may fix the overflowing builds. Could you allow me to push commits to your branch? https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

The change is this, in `ports/atmel-samd/Makefile`:
```
--- a/ports/atmel-samd/Makefile
+++ b/ports/atmel-samd/Makefile
@@ -150,7 +150,8 @@ else
   CFLAGS += -flto -flto-partition=none
 
   ifeq ($(CIRCUITPY_FULL_BUILD),0)
-    CFLAGS += --param inline-unit-growth=15 --param max-inline-insns-auto=20
+    # This is making the build larger in some cases (gcc 10.2.1), so turn it off for now.
+    # CFLAGS += --param inline-unit-growth=15 --param max-inline-insns-auto=20
   endif
```

For `arduino_nano_33_iot`, it makes the overflowing builds fit, and I think it will work for the other ones too. @tannewt has already fixed the pca10100 overflow in #5339.

**Comment by microDev1** [comment]
@dhalbert Thanks for looking into this. I enabled edits from maintainers on this PR so you should be able to push to my branch now.

**Comment by microDev1** [comment]
@dhalbert Thanks for looking into this. I enabled edits by maintainers on this PR so you should be able to push to my branch now.

**Comment by dhalbert** [comment]
> I have a `Makefile` change that may fix the overflowing builds.

I thought this worked, but it didn't. I have evidence of _something_ working in my terminal log, but it might have been a glitch. So I reverted this.

**Review by dhalbert — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
