### PR TITLE
Add: added Seeed's Wio Terminal Board Support

### PR DESCRIPTION
**Pull request by ansonhe97**
Added Wio Terminal as board support.

### CODE REVIEW

**Comment by tannewt** [comment]
Oops, I didn't see the tests failed. You'll want to add the board here: https://github.com/adafruit/circuitpython/blob/main/.github/workflows/build.yml#L242

That way it'll be built every commit and automatically released. Thanks!

**Comment by ansonhe97** [comment]
Hi @tannewt

I have added wio terminal here, not sure what is missing: https://github.com/ansonhe97/circuitpython/blob/main/.github/workflows/build.yml#L243

**Comment by ansonhe97** [comment]
For now, I have not seen an example with circuitpython using SPI LCD yet, may be you have some reference? That would be very helpful :D

**Comment by tannewt** [comment]
> Hi @tannewt
> 
> I have added wio terminal here, not sure what is missing: https://github.com/ansonhe97/circuitpython/blob/main/.github/workflows/build.yml#L243

The check is picky and wants it sorted. So wio before xiao.

**Comment by tannewt** [comment]
> For now, I have not seen an example with circuitpython using SPI LCD yet, may be you have some reference? That would be very helpful :D

Here is a SPI example: https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/pygamer/board.c#L73 What display IC controls the display? We may already have a board with the correct init sequence.

**Comment by ansonhe97** [comment]
Our LCD is ILI9341, any luck? :)

**Comment by ansonhe97** [comment]
Also there is a new CI error, what exactly is this and how can i fix this?

**Comment by tannewt** [comment]
I don't think we have a board with it natively. I didn't do a great job documenting it in the board.c. The init sequence is here though: https://github.com/adafruit/Adafruit_CircuitPython_ILI9341/blob/master/adafruit_ili9341.py#L72

You'll just need to convert is to a C array.

**Comment by ansonhe97** [comment]
For now, can we simply use this driver:https://github.com/adafruit/Adafruit_CircuitPython_ILI9341 (will also test with  wio terminal), may be we can add it later?

**Comment by ansonhe97** [comment]
For now, can we simply use this driver:https://github.com/adafruit/Adafruit_CircuitPython_ILI9341 (will also test with wio terminal), may be we can add it later?

**Comment by tannewt** [comment]
Yup! Will merge this now and a follow PR can add native display support. Testing from CircuitPython first is a good idea.

**Pull request merged**
