### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [CircuitPython/main](https://hosted.weblate.org/projects/circuitpython/main/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
@jessyjones Vous avez changez array" à ¨matrice¨. Dans la documentation officielle de Python, le mot « tableau » est utilisé à la place du mot « array » https://docs.python.org/fr/3/library/array.html?highlight=array#module-array le mot.

"Matrice" est pour numpy, bien sur, maybe peut être pas pour "array"?

**Comment by jessyjones** [comment]
Hello @dhalbert , if I understand correctly you're referring to the use of "matrice" instead of "tableau" in the translations I submitted ? 
If that's the case, I chose to use matrice since it appeared to be used in numerous other locations in the french translation, and I thought it'd be more consistent for the user. I'd be happy to change it to "tableau" if you think it's better to stick with the official Python term, but then I would have to change it in the translations strings that were already done ?

**Comment by dhalbert** [comment]
@jessyjones Is it "matrice" in other places? I'd prefer to use the term that the documentation prefers, which seems to be "tableau", if you think that makes sense. On the other hand, the French translation of the official documentation is pretty incomplete, and I know that often there is not consistency about how to translate various terms

"Matrix" in Python usually means something with >1 dimension. The French examples I could find went along with that. If you have some French Python textbooks or other material, maybe you can see what they say. 

@neradoc do you have an opinion about this as well?

**Comment by jessyjones** [comment]
Yes, it is, I believe the oldest translation using the word "matrice" is this one : https://hosted.weblate.org/translate/circuitpython/main/fr/?checksum=924279b02128dd8f

**Comment by jessyjones** [comment]
@hugodahl I believe this was a choice of yours (based on the translation history), do you mind sharing your reasons ? I'd be happy to discuss it further if you think "tableau" is not appropriate :-) !

**Comment by dhalbert** [comment]
"bytearray" is not translated, but "array" is. In this case the reference is usually to the specific Python module (`array`, used as `array.array`, etc.), so perhaps `array` doesn't need to be translated at all?

E.g., there is this inconsistency from before this PR. Given the mention of `bytearray` here, I would stick with `array`, and change the "matrice" to "array" here and similar places, where we mean an object of type `array`.
```
#: shared-bindings/analogbufio/BufferedIn.c
msgid "%q must be a bytearray or array of type 'H' or 'B'"
msgstr "%q doit être un bytearray ou matrice de type 'H' ou 'B'"

#: shared-bindings/audiocore/RawSample.c
msgid "%q must be a bytearray or array of type 'h', 'H', 'b', or 'B'"
msgstr "%q doit être a bytearray ou array de type 'h', 'H', 'b', ou 'B'"
```

**Comment by jessyjones** [comment]
Alright, I've gone ahead and modified the strings I had translated and I believe I removed all mentions of "matrice". 
Most of the time I used "array" except when it was obvious that the original message was referencing array as a word and definitely not the module: I figured if someone's using these librairies, they're most likely to know what we mean by array, so that'd be the safest option.

Let me know if there's anything else !

**Comment by jessyjones** [comment]
On a slightly unrelated note, there's this string where I wasn't sure what the message was referring to : https://hosted.weblate.org/translate/circuitpython/main/fr/?checksum=fb0963ba87e05c38

My understanding of the code is that show was never meant to be used and the message is suggesting the coder uses ".root_group =" instead. 

Would that be correct ?

**Comment by dhalbert** [comment]
`.show()` was available previously, but was deprecated in 8.x.x; users were told to use `.root_group =` instead. In 9.0.0, `.show()` has been removed completely, but we are printing this warning to help users make the transition.

So `.show()` is obsolete and was removed.

(`.show()` was misleading, because it didn't actually cause something to be shown immediately. Instead it was used to set the base displayio `Group` that should be displayed, hence `.root_group =`.)

**Comment by jessyjones** [comment]
Thanks for the clarification, I've just updated the translation !

**Review by dhalbert — APPROVED** [review]
@jessyjones Thanks for your patience on this!

**Pull request merged**
