### PR TITLE
Fix the nRF builds with GCC 11.2

### PR DESCRIPTION
**Pull request by tannewt**
See adafruit/Adafruit_nRF52_Bootloader#221
for background on the flag.

### CODE REVIEW

**Comment by jerryneedell** [comment]
Are you using GCC 11.2 now?

**Comment by tannewt** [comment]
I'm starting to locally. The CI is 10.3 still.

**Comment by jerryneedell** [comment]
Good to know. Thanks. I'll give it a try and try creating a Raspberry pi build.

**Comment by rdoursenaud** [comment]
Confirmed working here on a Feather nRF52840 Express.
Lost USB connectivity without the patch.

**Review by dhalbert — APPROVED** [review]
lgtm

**Comment by jerryneedell** [comment]
AH -- I see that 11.2 has not been released on the arm developers site yet <https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads>  -- will we be officially  staying at 10.3 until it is available there?

**Comment by rdoursenaud** [comment]
@jerryneedell GCC 11.2 has been released upstream and is already in Arch.

The CI is indeed still 10.2.1: https://github.com/adafruit/circuitpython/blob/09859a60e776c08bc7134764a9ff431e9bff2102/.github/workflows/build.yml#L246

**Comment by dhalbert** [comment]
We stick with the official ARM downloads for wide availability reasons: most people are not using Arch. We haven't yet upgraded to 10.3-2021.07 because the changes were not relevant to us, but probably will upgrade to that after 7.0.0 final. I would expect the ARM release to go to 11.x in December or January.

Someone should report the 11.2 issue to Nordic in [DevZone](https://devzone.nordicsemi.com/) to give them a heads up. It could be me, but I don't have a good understanding of the issue yet.

**Pull request merged**
