### PR TITLE
Merge MicroPython v1.9.2

### PR DESCRIPTION
**Pull request by dhalbert**
Some notes on MicroPython v1.9.2 changes. There are many fixes, and also many stylistic changes. I'll put this in the commit message or a pull request comment as well:

`Micro Python` -> `MicroPython` everywhere.

`#include` guard `#define`'s lose their leading and trailing double underscores

(The above two affect many files and account for the majority of changes in the merge. I've edited our own code to include those stylistic changes going forward.)

`nlr_raise_whatever` -> `mp_raise_whatever` (higher level exception raising).

Double precision added, including `libm_dbl` double precision math library added.

Many tests improved.

For `STATIC` dicts, `mp_map_elem_t` replaced by `mp_rom_map_elem_t`, and the macros defining the entries changed from `OBJ_NEW_whatever` to `MP_ROM_whatever`. I made pass over our own code to do this as well.

`mp_uint_t` -> `size_t` where appropriate.

`..` -> `$(TOP)` in makefiles.

Some changes and additions to rst documentation markup. See `CODECONVENTIONS.md` for details. In particular, argument names are asterisk'd, not backquoted. Addition of `docs/templates/replace.inc`; it includes boilerplate text that can be inserted by inserting a small `|something|` marker.

### CODE REVIEW

**Comment by willingc** [comment]
@dhalbert @tannewt This a big PR. I'm wondering if it would make sense to break this into 4 PRs: Jun 14, Jun23, Jul 24, Jul 29. It might make the review, tests, and `git bisect` easier if any regressions are introduced with 1.9.2.

**Comment by tannewt** [comment]
I'm ok with just pulling it all in. I'd prefer to get it in so we have people using it sooner.

**Comment by willingc** [comment]
@tannewt What's rosie-ci? A custom ci machine of yours?

**Comment by dhalbert** [comment]
[started wring this before @tannewt's comment above] I looked at the original diffs of nearly all the files, which took a couple of hours. I only skipped over files in implementations we don't cover (cc3200, etc.). What I would say is that if we need to debug a regression, we could do that in micropython instead of circuitpython. I don't mind importing new bugs if they are the same bugs in MicroPython.

We don't make very many changes in the `py/` and similar parts of the tree. Most of our work is in `atmel-samd/`.

**Comment by willingc** [comment]
@dhalbert Nice work going through each module. I would say merge and correct the Feather M0 Express in a separate PR :cake:

**Comment by dhalbert** [comment]
Hi @willingc - rosie is an RPi with one of each different CPy-compatible board attached (except ESP8266, I think). It loads up the appropriate firmware and then runs a set of Python tests. I think @tannewt meant that the attached Feather M0 Express board doesn't seem to be working. I did see a test failure on one of the working boards, but that might be a red herring. Once Scott gets it up again, I'll take a look at the rosie results and do another push if necessary.

**Comment by willingc** [comment]
Great @dhalbert. Thanks for the more detailed explanation.

**Comment by tannewt** [comment]
Thanks a bunch @dhalbert! It looks really good.

**Pull request merged**
