### PR TITLE
Board names changed to be valid python identifiers

### LINKED ISSUE #7267: Change board names to be valid Python identifiers
- Tracking issue for #6979.

### PR DESCRIPTION
**Pull request by bill88t**
This PR is a followup to #6856.

Basically I replaced all "-" and "." with "_".
As for the 8086_commander, I opted to just swap the words around.

Additional requirements for this change to go well:
- The same changes will have to be done on the -org repo.
  I will do that pr if you decide to go ahead with this.
- This and the -org PRs will have to be merged EXACTLY when `8.0.0` releases.
  Because the board names will remain unchanged on `7.x`.
- When new boards are being ported, a check (perhaps github action)
  should be in place to prevent boards from having invalid python identifiers as their name.

Fixes #7267.

### CODE REVIEW

**Comment by bill88t** [comment]
I am very confused as to why the usb id check failed.. I did `mv` it correctly, checked my history..

**Comment by jepler** [comment]
Looks like the PR needs to changed `tools/ci_check_duplicate_usb_vid_pid.py` as well.

PS this script might be one place to add enforcement of the policy for board names to only be valid Python identifiers.

**Comment by jepler** [comment]
also it looks like at least one "-" is left after this, [boards/espressif_kaluga_1-3/board.c](https://github.com/adafruit/circuitpython/pull/6979/files#diff-c2cb0f209aeef14eab11ccae25ead9aa0b7c798c2b5a7e0589dfea502170c9d9)

**Comment by jepler** [comment]
I was thinking the ci_check_duplicate script could just have it added, but a separate step/script is fine too.

**Comment by dhalbert** [comment]
There is an board alias mechanism which could be used to ease the transition, though I'm not sure if it would produce multiple picture entries in circuitpython.org.

It's also true that the old names are used in the directory tree structure in S3: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin. If we rename the directories there, we need to track down any links besides the ones in circuitpython-org. There may be many in the Learn Guides.

If we are going to do a big renaming, we might also consider renaming the older adafruit boards that don't have `adafruit_` as a prefix.

I a bit worried whether there's too much churn created by this. One can always take the given board name and substitute `_` for `-` using `str.replace()` at run-time. I agree it would be good to enforce a standard naming going forward.

**Comment by dhalbert** [comment]
I am going to make this a draft while we cogitate on this.

**Comment by tannewt** [comment]
I think a CI check for new boards is best. Is there tooling that needs the python identifier property for all boards?

**Comment by dhalbert** [comment]
We discussed closing draft issues that are stuck in the CircuitPython meeting on 2022-11-28 in In the Weeds.

Closing for now. Can be reopened. Tracking in issue #7267, which will remain open.

**Pull request closed without merging**
