### PR TITLE
Fix for #2204

### PR DESCRIPTION
**Pull request by furbrain**
This PR provides a fix for issue #2204. It fixes a moderate bug which results in hard segfaults when you repeatedly initialise a display. The original context for this is a display which is powered down prior to the processor going in to light sleep

### CODE REVIEW

**Comment by tannewt** [comment]
Please explain what the bug is. It isn't immediately obvious to me.

**Comment by furbrain** [comment]
I will use line numbers from the original source code
`gc_never_free` will crash the fourth time it is called.
* First time it is called the `permanent_pointers` item of `mp_state` is set to null.
  The while block on line 1017 is skipped and `next_block` is allocated - a set of four pointers
  The if statement on line 1029 evaluates as true and line 1030 executes, correctly storing the address of `next_block` in `permanent_pointers`
  the pointer passed into the function is stored in index [1] of `current_reference_block`
* second and third time around it loads the previously allocated block from `permanent_pointers` into `current_reference_block` correctly just places the pointer into `current_reference_block`[2] and [3]
* Fourth time around `current_reference_block` looks like this:
   [0] = NULL
  [1] = ptr1 (first pointer added)
  [2] = ptr2 
  [3] = ptr 3
As there is nowhere to store the new pointer current_reference_block is set to current_reference_block[0] - which is NULL - indicating that we need to create a new block
However, on line 1032 we set current_reference_block[0] to the new block. 
**But at this point `current_reference_block` is NULL**
So line 1032 tries to set the memory at 0x00000000 to the address of next_block - which segfaults

**Comment by furbrain** [comment]
My fix keeps a record of the previous `current_record_block` so we can assign the next block into it correctly.

**Comment by akoebbe** [comment]
@furbrain Thanks for this change. Just wanted to confirm here that this change resolves #7974 . The only _possible_ side effect is that auto-reload crashes, though pressing reset does bring it back. Again, I can't confirm that this fix has anything to do with that, but just something to keep an eye out for.

**Review by tannewt — APPROVED** [review]
Thanks for the fix!

**Comment by tannewt** [comment]
(and the thorough explanation.)

**Comment by dhalbert** [comment]
@furbrain I am closing all the issues you think are related. Let us know if you think not.

**Pull request merged**
