### PR TITLE
Clarified I2C init error msg

### PR DESCRIPTION
**Pull request by BiffoBear**
When creating an instance of an i2c bus with no wires connected, SCL / SDA wires crossed, no power to the board when SCL and SDA wires are correctly connected, CircuitPython raises the exception:

`RuntimeError: SDA or SCL needs a pull up`

This a confusing error message that is probably seen often, especially by beginners who are likely to be using an i2c breakout board with pull ups.

I suggest changing the message to:

`Check your I2C wiring, also SDA or SCL may need a pull up`

I've made this change to the en-US.po translation file as per a suggestion from @tannewt

### CODE REVIEW

**Comment by dhalbert** [comment]
I agree the original could be phrased better. How about  `No pull-up detected on SDA or SCL; check your wiring`?

**Comment by BiffoBear** [comment]
> I agree the original could be phrased better. How about `No pull-up detected on SDA or SCL; check your wiring`?

Thanks for your suggestion, I like your phrasing better than mine

**Comment by dhalbert** [comment]
I would just as soon change the original message, instead of just the translation. Many of our volunteer translators are pretty good at keeping up.

**Comment by BiffoBear** [comment]
I think changing the original message is a better long term solution. After replacing the text in the C file, how do I handle the translation files?

Do I replace the `msgid` and set the `msgstr` to "" in the circuitpython.pot and each language file?

**Comment by BiffoBear** [comment]
I'm looking at Weblate and gettext and it seems to me that all I need to do is change the C source code?

**Comment by dhalbert** [comment]
Right , you don't need to change `circuitpython.pot` or any of the `.po` files. Just change the actual message in `I2C.c`

**Comment by BiffoBear** [comment]
Reverted change to en_US.po. Changed error message in C source files to `No pull-up detected on SDA or SCL; check your wiring`

**Comment by BiffoBear** [comment]
Build CI test is failing for the trinket_m0 ja translation with:
`Build trinket_m0 for ja (clean_build) took 34.80s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
QSTR updated

188168 bytes used, -8 bytes free in flash firmware space out of 188160 bytes (183.75kB).
10060 bytes used, 22708 bytes free in ram for stack and heap out of 32768 bytes (32.0kB).

Too little flash!!!`

**Comment by BiffoBear** [comment]
Builds OK on my local machine:

`$make BOARD=trinket_m0 TRANSLATE=ja

Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
QSTR updated

186896 bytes used, 1264 bytes free in flash firmware space out of 188160 bytes (183.75kB).
10060 bytes used, 22708 bytes free in ram for stack and heap out of 32768 bytes (32.0kB).

Converting to uf2, output size: 374272, start address: 0x2000
Wrote 374272 bytes to build-trinket_m0/firmware.uf2
`

**Comment by dhalbert** [comment]
@BiffoBear Your latest commits rolled back the `ulab` submodule a few commits by accident. I think this may have been due to not pulling from your own repo after I made changes to the PR, so they got out of sync. Also the `circuitpython.pot` may have lost a bunch of new messages.

Let's start over again to clean this up. Could you get the latest adafruit/main into your `main`, start a new fix branch, and then include only the error message changes in the various `I2C.c` files, and my shrink of `trinket_m0?` Then make a new PR. I'll close this one. Make sure you update the submodules after getting the latest main. Do this:
`git submodule sync --quiet --recursive && git submodule update --init`

**Pull request closed without merging**
