### PR TITLE
Added SPEAKER and TFT pins to HalloWing M4 for code compatibility

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by ladyada** [comment]
ditto

**Comment by makermelissa** [comment]
I'm not sure why a pin addition for the HalloWing M4 would cause a bunch of other boards to fail, but I queued for a restart.

**Comment by makermelissa** [comment]
Added a few more pins to address the other Learn Guide issue

**Comment by makermelissa** [comment]
I'm not sure why it's failing checks. It seems kinda random.

**Comment by makermelissa** [comment]
I'm almost certain this is related to the message on my git status:
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   lib/tinyusb (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```
But I can't seem to figure out how to get that to go away, what it means, why it appeared, or how to fix it. @tannewt maybe you could shed some light on this. This is a little outside my git knowledge. Thanks.

**Comment by makermelissa** [comment]
Ok, never mind, I figured out how to fix that. Still can't figure out the build errors.

**Comment by tannewt** [comment]
These build errors are your fault. GitHub CI is unreliable. :-/

The original failures could probably be solved by moving us off of "use" statements since they appear to require a download.

The rerun fails because master has had a commit merged and the rerun isn't exactly the same as the original. The workaround for this is to merge master into the PR branch and push the merge commit to trigger a new build.

**Comment by makermelissa** [comment]
Ok, I'm good with that. Thanks.

**Pull request merged**
