### PR TITLE
Renumber endpoints for only chosen USB interfaces; fix HID report ids

### PR DESCRIPTION
**Pull request by dhalbert**
- Endpoint renumbering was done over all the possible USB devices, not the selected ones.
- Handling of no report ID when only one HID devices was incorrect.
- Reordered where to put HID in descriptor (just for consistency).

### CODE REVIEW

**Comment by hierophect** [comment]
While it looks conceptually fine to me I'm not an experienced enough Python coder to notice issues with the implementation. I'd recommend having at least one other person check it out.

**Comment by dhalbert** [comment]
@hierophect can you test it on STM32F412 with reduced USB devices to see if the Windows enumeration problem crops up? I can give you a build if you want.

**Comment by hierophect** [comment]
@dhalbert sure can you pass me a binary?

**Comment by dhalbert** [comment]
I tested this on a '412 board, using the commit from #2132 just before this commit https://github.com/adafruit/circuitpython/pull/2132/commits/d8251ae4ab8b9634754ddc1fe545179a609417d8. Works fine on Linux and Windows.

**Comment by ladyada** [comment]
thank you!

**Comment by dhalbert** [comment]
Fixes bugs in #2116.

**Pull request merged**
