### PR TITLE
Latest Feather nRF52840 pin revisions

### PR DESCRIPTION
**Pull request by dhalbert**
Pins revised based on latest rev C schematic. Some pin names revised.

Only Q is if the `SWITCH` should be called `BUTTON`, since it's momentary. Left it at `SWITCH` for now.

### CODE REVIEW

**Comment by ladyada** [comment]
checkin out by checking out

**Comment by ladyada** [comment]
ok there's enough weird stuff - QSPI not workin, neopixel malloc crashes, and then tinyusb, that will need to pause reviewing this until there's some other fixes. i did get the red led to blink but thats kinda it :)

**Comment by ladyada** [comment]
im ok preliminarily merging even tho QSPI isnt working - all the other GPIO are tested!

**Comment by dhalbert** [comment]
I set the SPI flash chip to GD25Q16C, per the schematic. Is that correct? Previously was GD25Q64C, maybe from the Trellis?

**Comment by ladyada** [comment]
yeha its correct - we got it working in SPI mode, but not QSPI mode, it busywaits for some reason. we're not sure why but i dont think its related to the pin names, maybe something in the QSPI peripheral?

**Comment by dhalbert** [comment]
OK by me if you want to merge it with QSPI broken, so we can test it against upcoming USB changes easily. If you approve I will merge. The QSPI thing is weird, but if those are different pins or a different chip than anything used with the nRF52840 before, I could believe it needs more debugging.

**Comment by ladyada** [comment]
cool - yeah i think its not the definition here. approvin'!

**Pull request merged**
