### PR TITLE
Shrink the smallest builds with compile options

### PR DESCRIPTION
**Pull request by dhalbert**
The `trinket_m0` build was running out of space on the latest PR's. It has more in it due to having a DotStar (I think).

These compile options saved about 500 bytes total.

Still left as a possibility is to use a `-Os` `libgcc.a`, instead of the current `-O2 one`, which makes software floating point and various other arithmetic routines noticeably smaller (by at least 1kB or 2kB, I forget which). I have not measured the performance decrease.

### CODE REVIEW

**Comment by dhalbert** [comment]
I am getting paradoxical results on `pewpew_m4`: the `--param max-inline-insns-auto` increase is increasing the size rather than decreasing it as on the `trinket_m0`. Turning this into a draft while I experiment.

**Review by jepler — DISMISSED** [review]
This is fine by me. A number of things make debugging tough on these samd21 boards as it is.

**Comment by jepler** [comment]
Unfortunately, the gains are not uniform.  for instance, "meowmeow" no longer fits:
```
Build meowmeow for de_DE took 17.64s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
/usr/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: build-meowmeow/firmware.elf section `.text' will not fit in region `FLASH_FIRMWARE'
/usr/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH_FIRMWARE' overflowed by 16 bytes
collect2: error: ld returned 1 exit status
make: *** [Makefile:418: build-meowmeow/firmware.elf] Error 1
```

**Comment by dhalbert** [comment]
The single failure in the latest build was a network error, on a build that did not fail before. @jepler, this is ready for re-review.

**Review by jepler — APPROVED** [review]
Thank you

**Pull request merged**
