### PR TITLE
Remove ESP_CONSOLE_UART from sdkconfig for 666 S3 Display panels

### LINKED ISSUE #9569: boot loop on Hacktablet and Makerfabs matouch 7" S3 display boards
### CircuitPython version

```python
CircuitPython 9.2.0-alpha.2351
```

### Code/REPL

```python
No code executed
```

### Behavior

> [13:24:07.365] Connected to /dev/ttyACM0
I (623) esp_image: segment 0: paddr=00010020 vaddr=3c150020 size=3acc0h (240832) map
I (660) esp_image: segment 1: paddr=0004ace8 vaddr=3fc9f200 size=05330h ( 21296) load
I (664) esp_image: segment 2: paddr=00050020 vaddr=42000020 size=14718ch (1339788) map
I (869) esp_image: segment 3: paddr=001971b4 vaddr=3fca4530 size=00128h (   296) load
I (869) esp_image: segment 4: paddr=001972e4 vaddr=40374000 size=1b19ch (111004) load
I (896) esp_image: segment 5: paddr=001b2488 vaddr=600fe000 size=00100h (   256) load
I (897) esp_image: segment 6: paddr=001b2590 vaddr=600fe100 size=01008h (  4104) load
I (914) boot: Loaded app from partition at offset 0x10000
I (914) boot: Disabling RNG early entropy source...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xb (SPI_FAST_FLASH_BOOT)
Saved PC:0x40378d11
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x16dc
load:0x403c9700,len:0x4
load:0x403c9704,len:0x1054
load:0x403cc700,len:0x3090
entry 0x403c9a68
I (26) boot: ESP-IDF v5.1.1 2nd stage bootloader
I (26) boot: compile time Aug  9 2024 13:55:41
I (26) boot: Multicore bootloader
I (29) boot: chip revision: v0.1
... etc...

### Description

After installing CircuitPython 9.2.0-alpha.2351 firmware on both the Hacktablet (espressif ESP32-S3 Dev Kit N8R8) and the Makerfabs Matouch 7" display boards a boot loop occurs. The boot loop doesn't occur with 9.1.2.

I've loaded the same firmware on the Adafruit ESP32S3 reverse TFT, Qualia S3 (without a display attached) and the ESP32-S3-GEEK display boards without seeing the same issue.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by RetiredWizard**
This fixes #9569 boot loop for the Hacktablet and Makerfabs 7" TFT ESP32-S3 666 Dotclock display boards.

It looks to me like in addition to the Hacktablet and Makerfabs TFT 7" boards, the Espressif ESP32S3_LCD_EV and possibly (I don't know if non-S3 boards are affected) the Lilygo twatch_2020_v3 may be affected by this issue. I don't have either of those devices to test with but could add the same sdkconfig changes for those boards if that makes sense?

### CODE REVIEW

**Review by jepler — COMMENTED** [review]
Thanks for submitting this! I have some questions though...
 * Didn't this configuration work once upon a time?
 * Does removing the sdk uart configuration have any downsides, like preventing visibility of early boot messages?
 * I found 4 boards with CONFIG_ESP_CONSOLE_UART=y in sdkconfig but this PR changes 2. Any reason to leave the other two unchanged?

**Comment by RetiredWizard** [comment]
> * Didn't this configuration work once upon a time?

Yes it did, the boot loop didn't occur in 9.1.2/9.1.3.

> * Does removing the sdk uart configuration have any downsides, like preventing visibility of early boot messages?

On the two boards I have/tested, I was still able to connect to the REPL over the UART but you are right, the early boot messages are no longer visible :cry:

> * I found 4 boards with CONFIG_ESP_CONSOLE_UART=y in sdkconfig but this PR changes 2. Any reason to leave the other two unchanged?

Since I didn't know or track down the reason for the change, I went back and forth about adding the other boards since I couldn't test them as well, but I certainly could add them to the PR.

**Comment by dhalbert** [comment]
> The early boot messages are no longer visible

I think this is fine, because this is just noise to most users anyway. I would prefer these be suppressed for ordinary use.

**Comment by RetiredWizard** [comment]
> I would prefer these be suppressed for ordinary use.

Okay, but remember that at least on the boards I'm testing, their are two USB connectors, for ordinary use you would connect to the connector labeled USB which brings up the CIRCUITPY drive and shows up as /dev/ttyACM0, that connection doesn't show the early boot messages anyway. If you're connecting to the UART connector /dev/ttyUSB0 you don't get the CIRCUITPY drive and you're probably doing some debugging. That's the connection that I assume is affected by this PR.

**Comment by dhalbert** [comment]
@RetiredWizard Ah, sorry, I misunderstood. Maybe I am seeing the boot messages on the non-full-USB boards.

**Comment by RetiredWizard** [comment]
> @RetiredWizard Ah, sorry, I misunderstood. Maybe I am seeing the boot messages on the non-full-USB boards.

Now I'm not sure, I did some retesting and there is a smaller set of the boot messages on the normal port....

**Comment by dhalbert** [comment]
I would merge this but I think it's worth seeing which other similar boards still have `ESP_CONSOLE_UART`.

**Comment by RetiredWizard** [comment]
It looks to me like in addition to the Hacktablet and Makerfabs TFT 7" boards, the Espressif ESP32S3_LCD_EV and possibly (I don't know if non-S3 boards are affected) the Lilygo twatch_2020_v3 may be affected by this issue. I don't have either of those devices to test with but I'm happy to update the PR to include the same changes for those two boards as well.

I would feel better about changing the boards I can't test if I had an idea why this change is necessary for 9.2.x and not 9.1.2.

**Comment by RetiredWizard** [comment]
I've been testing #9634  using main (9.2.0-alpha.2351-39-g1e36e05380-dirty on 2024-09-16; MakerFabs-ESP32-S3-Parallel-TFT-With-Touch-7inch with ESP32S3) as a base and haven't been seeing the boot looping that this was supposed to address. I'm not sure why but I'll do some more testing to see if this has been fixed by something since I was seeing the issue.

**Comment by RetiredWizard** [comment]
Okay, I'm not seeing the issue anymore using Absolute Newest:

Adafruit CircuitPython 9.2.0-alpha.2351-37-g015a5cf922 on 2024-09-16; MakerFabs-ESP32-S3-Parallel-TFT-With-Touch-7inch with ESP32S3
Adafruit CircuitPython 9.2.0-alpha.2351-37-g015a5cf922 on 2024-09-16; ESP32-S3-DevKitC-1-N8R8-with-HACKTABLET with ESP32S3

**Comment by dhalbert** [comment]
@RetiredWizard Could you make the same change on `espressif_esp32s3_lcd_ev`? That board also specifies GPIO43 and GPIO44. However, the LILYGO watch board uses special UART pins, so I'd be inclined to leave that alone.

I would have made the same change myself but you have disallowed upstream maintainers from pushing to your repo.

**Comment by RetiredWizard** [comment]
While I'm at it, is circuitpy a good LWIP hostname for the espressif_esp32s3_lcd_ev board?

```py
# LWIP
#
CONFIG_LWIP_LOCAL_HOSTNAME="circuitpy"
# end of LWIP
```

**Comment by RetiredWizard** [comment]
I just noticed that #9608 adds a new version 1.5 of the s3-lcd-ev board and in that PR Scott suggested along with all the lines this PR is removing from sdkconfig, the CONFIG_LWIP_LOCAL_HOSTNAME can be dropped as well.

Lots of boards have that configured, but I could go through and cut it from all the S3 boards as long as we're updating these three?

**Comment by dhalbert** [comment]
> the CONFIG_LWIP_LOCAL_HOSTNAME can be dropped as well.

That is OK too, there are plenty of boards without that. It doesn't serve a lot of purpose.

**Comment by RetiredWizard** [comment]
Okay, I'll put the removal of the LWIP hostnames from S3 boards in a new PR so it doesn't hold this one up.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Pull request merged**
