### PR TITLE
ESP32 synthio channels to 12

### PR DESCRIPTION
**Pull request by todbot**
I noticed ESP32 boards have the default `CIRCUITPY_SYNTHIO_MAX_CHANNELS` of 2.
This puts it at 12, like RP2040 and others.

Tested on ESP32S3 QTPy and I2S DAC.

### CODE REVIEW

**Comment by dhalbert** [comment]
> @dhalbert Want this in 8.2?

I think so!

@todbot, would you be willing to test with ESP32 and ESP32-S2?  I'm not sure why @jepler did not increase it for all? Is there significant use of RAM when it's increased, or only if you use more voices?

**Comment by jepler** [comment]
fwiw the "significant resource use" is computation & RAM bandwidth

**Review by dhalbert — APPROVED** [review]
Thank you for testing!

**Comment by dhalbert** [comment]
Will backport to 8.2.x

**Pull request merged**
