### PR TITLE
Add esp32 feather v1

### PR DESCRIPTION
**Pull request by jepler**
Adding this as a draft because there are a number of unresolved problems.  However, the repl comes up and the internal filesystem can be read on a feather esp32 "v1"

- [x] The pin reset stuff needs to be scrutinized, so that it can be right for feather v1 and v2 and for future esp32 boards. without reintroducing the wroom/wrover(/pico) distinction, which @dhalbert thinks was unhelpful and error-prone
- [x] need to determine why turning off spiram support breaks it. ("spiram enabled but optional" is OK except it breaks some of the pins for users)
- [x] need to determine why debug uart defaults breaks it
- [x] need to correct the i2c/spi/uart in mpconfigboard
- [x] need to remove the neopixel definition

### CODE REVIEW

**Comment by RetiredWizard** [comment]
I tried building this and putting it on my Feather ESP32 Huzzah32 w/4Mb Flash (V1 I assume) but ended up in a boot loop.

If it's of any value to have me try and get it working and you have any suggestions let me know :)

**Comment by dhalbert** [comment]
@RetiredWizard We were having trouble figuring out the right way to specify no PSRAM. If you have any insight, go ahead and try. We also have some things we are going to try. There is probably something wrong with the `sdkconfig` settings.

**Comment by jepler** [comment]
Yeah it needs some good low-level sleuthing, and Dan's right that doing a thorough comparison of the sdkconfig with a "known good one" (could be arduino or micropython) would be a good idea

That said, I didn't expect this thing to bootloop for you, since it worked for me on a 4MB flash / no psram Feather ESP32. Having (A) a legible picture of the metal enclosure of the ESP32 module from your Feather and (B) any output that is shown on the TX pin of the module (at 115200 baud) might be helpful. I happen to know my feather is "R3" version of the silicon, but older Feather ESP32s could have older chip revisions, which is why I ask about that.

**Comment by RetiredWizard** [comment]
This shows up over the the usb serial, I didn't see any output on the rx/tx pins.

     rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     ets Jul 29 2019 12:21:46
IMG_20220725_205925802

**Comment by RetiredWizard** [comment]
Same results on USB serial with unmodified PR

**Comment by RetiredWizard** [comment]
Heh, just looked more carefully, there is a difference with the reset code:

     rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     invalid header: 0xffffffff
     ets Jul 29 2019 12:21:46

**Comment by jepler** [comment]
The failure to boot with the "invalid header" messages is something I've seen before but I remember when or what fixed it for me.

can you erase the whole flash with `esptool erase_flash` and then flash it again?

what flash line are you using? It should be similar to
```
esptool.py --chip esp32 -p $(PATH) --before=default_reset --after=no_reset --baud 921600 write_flash --flash_mode dio --flash_freq 40m --flash_size 4MB 0x0000 build-adafruit_feather_esp32_v1/firmware.bin
```

Flashing the wrong file (e.g., circuitpython-firmware.bin) or at the wrong offset (not 0x0) could leave the module in a non-booting state. I use "make flash BOARD=... PORT=..."  as that should always get the right values.

The "E" suffix indicates it's a revision 3 chip, from what I'm able to see -- so, same as what I'm testing with.

My local builds are done with DEBUG=1 and also removed ulab and wifi to make the build & flash cycle faster so ... maybe disabling debug reveals some other problem.

This is all a bit off the top of my head, but just wanted to run through what came to mind.

**Comment by RetiredWizard** [comment]
Well give me a second to wipe all the egg off.... Yep, I just modified the flash command I was using for my S2 boards swapping out the --chip. With your flash command I'm no longer boot looping. Time to start testing :)

**Comment by jepler** [comment]
Yay! Please add any observations you have on this PR.

**Comment by dhalbert** [comment]
Thanks for your work on this. I will make a new PR that includes more up-to-date code, and will close this. @tannewt is working on dynamic determination of which pins are never-reset due to use for SPI/QSPI/DSPI flash and SPIRAM

**Pull request closed without merging**
