### PR TITLE
Add basic SAM E54  support and SAM E54 Xplained board

### PR DESCRIPTION
**Pull request by jepler**
Few peripherals are actually tested.  However, USB, I2C and GPIO seem to work.

The default SPI, I2C, and UART are the ones on the EXT2 header.  This is arbitrary, but the I2C on this connector is shared with the on-board I2C devices and the PCC header, making it the most versatile.

Only 16MiB of the 32MiB (256Mbit) flash is supported, due to the supervisor code for flash assuming 24-bit addresses.

This depends on adafruit/samd-peripherals#33 and adafruit/asf4#35 which are in draft status at the moment.  I figure this PR is likely to be a better place to discuss the issues before moving them out of draft status.

The main reason I'm working on this is because this board has an SD card slot wired for SDIO, so it will resolve any questions about correct wiring in #2863.

```
Adafruit CircuitPython 5.4.0-beta.1-19-gce8ebc779-dirty on 2020-06-18; SAM E54 Xplained Pro with same54p20
>>> import board
>>> i2c = board.I2C()
>>> i2c.try_lock()
True
>>> i2c.scan()
[40, 54, 86, 94]
```

### CODE REVIEW

**Comment by dhalbert** [comment]
> Most pins are silkscreened with the "PX00" style, so the board module only includes the small number that are screened differently, mostly on the PCC header. I can fill out the board module with these names if desired.

I suggest filling `board` with all the pins in `Px00` style,instead of relying on `microcontroller.pin`. I did this for the nrf dev boards like `pca10056`, so that all the silk-screened pins have a name under `board`, for consistency.

**Comment by jepler** [comment]
Initially I wrote this so that SAMD51 and SAME54 preprocessor defines were both defined for the new board. This is tricky because when you write the #if blocks to do something different, you have to put the SAME54 block first, so I think it's not a good idea.

I'm rewriting it so that SAMx5FAM is defined for both systems, and then just one of SAMD51 or SAME54 is defined. Thoughts @dhalbert @tannewt ? Especially if you want to intervene on the naming, sooner is better. This'll require additional changes in peripherals submodule too.

**Comment by dhalbert** [comment]
> I'm rewriting it so that SAMx5FAM is defined for both systems, and then just one of SAMD51 or SAME54 is defined. Thoughts @dhalbert @tannewt ? Especially if you want to intervene on the naming, sooner is better. This'll require additional changes in peripherals submodule too.

Discussion is in https://github.com/adafruit/samd-peripherals/pull/33

**Comment by jepler** [comment]
I verified that the asf4 and peripherals submodule commits are within the circuitpython and master branches of those repos respectively.

**Pull request merged**
