### PR TITLE
Add support for PyGamer to Stage library

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by deshipu** [comment]
Note that ``board.JOYSTICK_X`` and ``board.JOYSTICK_Y`` are reversed, because that's how they are in the current builds.

**Comment by ladyada** [comment]
didnt test hardware, just looked at PR for typos :)

**Comment by tannewt** [comment]
Looks like you need to rebase to make git happy.

**Comment by deshipu** [comment]
Sorry, there is something broken with my repository, I need to make a new PR: #1955

**Pull request closed without merging**
