### PR TITLE
Repair mixgo_ce frozen lib to frozen/

### PR DESCRIPTION
**Pull request by dahanzimin**
Thank you very much for your help

### CODE REVIEW

**Comment by dahanzimin** [comment]
@[dhalbert](https://github.com/dhalbert)  
`Run sudo apt-add-repository -y -u ppa:pybricks/ppa
  sudo apt-add-repository -y -u ppa:pybricks/ppa
  sudo apt-get install -y gettext uncrustify
  pip[3](https://github.com/adafruit/circuitpython/runs/6557101266?check_suite_focus=true#step:4:3) install black polib pyyaml
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.[4](https://github.com/adafruit/circuitpython/runs/6557101266?check_suite_focus=true#step:4:4)/x[6](https://github.com/adafruit/circuitpython/runs/6557101266?check_suite_focus=true#step:4:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[10](https://github.com/adafruit/circuitpython/runs/6557101266?check_suite_focus=true#step:4:11).4/x64/lib
Error: retrieving gpg key timed out.
Error: Process completed with exit code 1.`

Why did ash cause this error! It's going to cause trouble

**Comment by jepler** [comment]
I ran the failed check again and it passed this time.

**Review by dhalbert — APPROVED** [review]
Thanks!

If you are using https://gitee.com, I think we could point to a submodule there, since the fetching is done strictly with git, which should not care.

The only issue I see is the error I get when trying to browse a gittee.com repo without being logged in:

> 为了营造绿色健康的开源社区，推动中国开源生态建设，当前仓库仅限 [登录](https://gitee.com/login) 用户访问。
Gitee 公开仓库作者需要先进行申请，审核后才能开放匿名访问。
如果你是仓库持有者，请检查你是否处于登录状态。

I had to Google translate this to read it, but my understanding is that though it's not the default, you could authorize anonymous cloning of the repo.

**Comment by dhalbert** [comment]
I am going to go ahead and merge this anyway so our builds will work for now, and we can think more at gitee.com later.

**Comment by dahanzimin** [comment]
OK, I will try gitee later. I believe that technology knows no borders. Thank you again for the completion of this tortuous road

**Comment by dahanzimin** [comment]
Finally, let me ask you a question. Has circuitpython considered the transplantation and construction of esp32-s3 of espressif in terms of [AI](https://github.com/espressif/esp-dl)

**Comment by tannewt** [comment]
> Finally, let me ask you a question. Has circuitpython considered the transplantation and construction of esp32-s3 of espressif in terms of [AI](https://github.com/espressif/esp-dl)

We haven't thought much about AI APIs yet. Please open a new issue if you want to discuss it. We'd probably want to model after an existing Python API

**Pull request merged**
