### PR TITLE
 fix kw_arg checking for time.struct_time()

### LINKED ISSUE #1493: call to time.struct_time() fails in beta-0
Just tried running some code I have been using for quite awhile on 4.0 alpha but it now breaks.
```
uto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 114, in <module>
  File "code.py", line 79, in <module>
  File "/lib/adafruit_gps.py", line 110, in update
  File "/lib/adafruit_gps.py", line 186, in _parse_gpgga
TypeError: time.struct_time() takes exactly 1 argument
```
has time.struct_time changed?

I'll look at the gps lib but something has changed and broken....

### PR DESCRIPTION
**Pull request by jerryneedell**
fixes #1493  -- change suggested by @tannewt 
tested on metro_m4_express and itsybitsym4_express

### CODE REVIEW

**Comment by jerryneedell** [comment]
I just submitted thia PR -- but it does not appear to have kicked off Travis build -- did I do something wrong?

**Comment by jerryneedell** [comment]
travis ran on travis-ci.org and passed, but I don't know how to get it to migrate my fork to travis-ci.com?

**Comment by dhalbert** [comment]
Hi, we enrolled in the Travis beta migration program: https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg. Once we were in it, a list of repos we could migrate showed up on https://travis-ci.org/account/repositories at the bottom, if I remember right, with "Migrate" buttons. You can also just wait for them to migrate your repo eventually.

**Comment by dhalbert** [comment]
The PR should have triggered a build, though; we're not sure why it didn't happen. Neither Travis nor GitHub are reporting problems currently.

**Comment by jerryneedell** [comment]
So-any idea how to proceed?

**Comment by tannewt** [comment]
I think its low risk so I'll approve and merge.

**Pull request merged**
