### PR TITLE
Add A3 pin to Raspberry Pi Pico

### PR DESCRIPTION
**Pull request by xorbit**
We want to be able to use this to measure VSYS.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Ah! That's what it's used for! Do you have any reason to call it `A3`? We commonly have a `VOLTAGE_MONITOR` pin name on other boards. That'd make it clearer that the pin isn't broken out.

**Comment by xorbit** [comment]
How about having both `A3` and `VOLTAGE_MONITOR` names available?  The RPi Pico docs seem to call it `A3` so I would think it would be best to have this name available for the people coming from that side but `VOLTAGE_MONITOR` for the people who come from the Adafruit / CircuitPython side.

**Comment by dhalbert** [comment]
> How about having both `A3` and `VOLTAGE_MONITOR` names available? The RPi Pico docs seem to call it `A3` so I would think it would be best to have this name available for the people coming from that side but `VOLTAGE_MONITOR` for the people who come from the Adafruit / CircuitPython side.

That's fine with me. Could you push a new commit to add `VOLTAGE_MONITOR`?

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
