### PR TITLE
Retry send if only some bytes sent

### LINKED ISSUE #6654: Web Workflow file manager screen occasionally doesn't list files
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-69-gbc926b041-dirty on 2022-07-26; Adafruit QT Py ESP32C3 with ESP32-C3FN4
Adafruit CircuitPython 8.0.0-alpha.1-69-gbc926b041-dirty on 2022-07-26; Adafruit Feather ESP32S2 with ESP32S2
Adafruit CircuitPython 8.0.0-alpha.1-69-gbc926b041-dirty on 2022-07-26; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3

Circuit Python Built from Pull Request #6651
```

### Code/REPL

```python
cmd = ""
while cmd.upper() != "EXIT":
    cmd = input(":>")
```

### Behavior

Upon opening or refreshing the Web Workflow file manager, occasionally the displayed directory will be blank and no files will be listed.

image
Usually the browser dev tools console displays the following message:

image

The following messages have also been displayed though:

C3 file browser dev console errors
C3 file browser when at press any key

When this issue does occur, simply refreshing the file manager browser window usually resolves it.

### Description

This issue is easiest to reproduce on the ESP32-C3 but I have seen it happen on both the S2 and S3. In my testing of the C3 board the networking has been getting better, but has been somewhat hit or miss. I may be at the edge of it's range from my wireless router.

### Additional information

I did this testing using builds from PR https://github.com/adafruit/circuitpython/pull/6651

### LINKED ISSUE #6689: Web Workflow serial terminal occasionally disconnects
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-89-gb38109c48-dirty on 2022-08-02; ESP32-S3-DevKitC-1-N8R2 with ESP32S3
Adafruit CircuitPython 8.0.0-alpha.1-89-gb38109c48-dirty on 2022-08-02; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3
Adafruit CircuitPython 8.0.0-alpha.1-89-gb38109c48-dirty on 2022-08-02; Adafruit Feather ESP32S2 with ESP32S2
```

### Code/REPL

```python
from supervisor import runtime
print("Press any key to stop output")
while runtime.serial_bytes_available == 0:
    print("0123456789"*5+"abcdefghijklmnopqrstuvwxyz")
```

### Behavior

Usually Within a 10 or 20 seconds or so of starting this python script the Web Workflow serial terminal will become disconnected (stop showing output from the serial port and the ctrl-c,d and send buttons go grey). Refreshing the screen will reconnect the terminal and output will continue unless it has been stopped from the usb serial terminal.

### Description

In most cases the following message is displayed in the browser developer console:

image

But occasionally this message is displayed:
 
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #6654 and fixes #6689

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
This looks good. But if `sent ==0`, then i think the connection has been closed? Should this handle that somehow?

**Comment by tannewt** [comment]
> This looks good. But if `sent ==0`, then i think the connection has been closed? Should this handle that somehow?

I don't think sent can be 0. It'll return an error instead.

**Comment by RetiredWizard** [comment]
Looks like you nailed this one. I've done *many* refreshes from both a solid network connection (right next to the router) and a less solid connection and the file listing has showed up every time. I did get a couple `net::ERR_CONNECTION_RESET` messages in the developer console screen but the file manager seemed to operate fine regardless of that message being displayed.

**Comment by dhalbert** [comment]
I was thinking about _received_ count being zero, sorry! :forehead-slap:

**Comment by RetiredWizard** [comment]
While testing this on the ESP32-C3 and ESP32-S3 I noticed a possible issue. When I run the following code:

     from supervisor import runtime
     i=0
     print("Press any key to stop output")
     while runtime.serial_bytes_available == 0:
         i+=1
         print(str(i)+"012345678"*5+"abcdefghijklmpqrstuvwxyz")

in the Web Workflow serial terminal it will run for a short time (how long varies from run to run and depends on the particular ESP chip) and then stop. The code will properly exit if a key is pressed. The behavior varies somewhat depending on whether a usb serial terminal is connected or not. I believe that there's a display buffer that's being filled at which point Circuit Python attempts to pause the program until the Web Workflow serial terminal can catch up. My guess is that while the serial terminal is catching up, web workflow ends up yielding program control to background operations and control isn't returned until a key press is detected.

I modified the web_workflow_send_raw function as follows:

        if (sent > 0) {
            total_sent += sent;
            if (total_sent < len) {
                // Yield so that network code can run.
                port_idle_until_interrupt();
            }
        } else if (sent == -EAGAIN) {
            port_idle_until_interrupt();
        }
 
This resulted in the display stopping sooner and much more consistently than the original version.

**Comment by RetiredWizard** [comment]
Moving the C3 close to the router and running the test script resulted in the program running much longer than it was with the weaker network connection. This is making me think my original guess that there was a display buffer being filled may have been off and network errors may actually be the triggers causing Web Workflow to yield control.

**Comment by RetiredWizard** [comment]
I removed the extra call to port_idle_until_interrupt and added an ESP_LOGE print just before the original call to port_idle_until_interrupt.

The output of the program stops after the second call to port_idle_until_interrupt. The number of lines that print varies from a few hundred to a few thousand but there are always two calls to the idle function and the program appears to stops just after the second call is made.

**Comment by RetiredWizard** [comment]
When the output has stopped on the serial terminal, any Web Workflow activity on another open browser window (i.e. clicking on a link in the Web Workflow file manager) will restart the output until two more idle calls are made.

**Comment by tannewt** [comment]
> When the output has stopped on the serial terminal, any Web Workflow activity on another open browser window (i.e. clicking on a link in the Web Workflow file manager) will restart the output until two more idle calls are made.

Ah, I have an idea. The idle call causes FreeRTOS to yield. The socket select task should wake CP but I don't think I have it set to do that when a socket is writable. I'll look into it.

**Comment by RetiredWizard** [comment]
Looks like you got it! The output seems to be running indefinitely now.

**Review by dhalbert — APPROVED** [review]
Thanks again @RetiredWizard !

**Pull request merged**
