### PR TITLE
add OV2640 support to sdkconfig for esp32s3_eye build

### LINKED ISSUE #8883: espcamera IDFError with CP 9.0beta.0  -- works OK with CP 8.2.9
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-beta.0 on 2024-01-27; ESP32-S3-EYE with ESP32S3
```

### Code/REPL

```python
import board
import espcamera


cam = espcamera.Camera(
    data_pins=board.CAMERA_DATA,
    external_clock_pin=board.CAMERA_XCLK,
    pixel_clock_pin=board.CAMERA_PCLK,
    vsync_pin=board.CAMERA_VSYNC,
    href_pin=board.CAMERA_HREF,
    pixel_format=espcamera.PixelFormat.JPEG,
    frame_size=espcamera.FrameSize.SVGA,
    i2c=board.I2C(),
    external_clock_frequency=20_000_000,
    grab_mode=espcamera.GrabMode.WHEN_EMPTY)
cam.vflip = True
```

### Behavior

Adafruit CircuitPython 9.0.0-beta.0 on 2024-01-27; ESP32-S3-EYE with ESP32S3

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 15, in <module>
espidf.IDFError: Operation or feature not supported

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

### Description

I am trying to run the AIO webcam example from https://learn.adafruit.com/capturing-camera-images-with-circuitpython/example-webcam-with-adafruit-io  but I have stripped open the code to produce this error when trying to initialized the espcamera.

The code runs OK on CP 8.2.9 (both the full code and the stripped down test)

Line 15 is
```
grab_mode=espcamera.GrabMode.WHEN_EMPTY)
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jerryneedell**
fixes #8883

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks!

**Comment by tannewt** [comment]
Do we want to update this instead? https://github.com/adafruit/circuitpython/blob/main/ports/espressif/esp-idf-config/sdkconfig.defaults#L113-L125 That's the global setting for camera support.

**Comment by jerryneedell** [comment]
That probably makes sense. It is confusing. Where dead OV5640 get enabled? It seems like it is globally enabled but I don't see it in there.

**Comment by jerryneedell** [comment]
for example, I just built the esp32s3_metro and in the generated sdkconfig it has
```
# CONFIG_OV7670_SUPPORT is not set
CONFIG_OV7725_SUPPORT=y
# CONFIG_NT99141_SUPPORT is not set
# CONFIG_OV2640_SUPPORT is not set
CONFIG_OV3660_SUPPORT=y
CONFIG_OV5640_SUPPORT=y
```

but the sdkconfig in boards/adafruit_metro_esp32s3  does not have ny camera specified.  It would probably be good to get bot the OV5640 and OV2640 here as well

**Comment by tannewt** [comment]
> That probably makes sense. It is confusing. Where does OV5640 get enabled? It seems like it is globally enabled but I don't see it in there.

It is on by default in the kconfig: https://github.com/espressif/esp32-camera/blob/master/Kconfig#L40

With 9.x we only include non-default settings in our kconfigs.

**Comment by jerryneedell** [comment]
> > That probably makes sense. It is confusing. Where does OV5640 get enabled? It seems like it is globally enabled but I don't see it in there.
> 
> It is on by default in the kconfig: https://github.com/espressif/esp32-camera/blob/master/Kconfig#L40
> 
> With 9.x we only include non-default settings in our kconfigs.

but in line 26 https://github.com/espressif/esp32-camera/blob/master/Kconfig#L26  OV2640 is also enabled, but we don't get it without specifying it...

**Comment by dhalbert** [comment]
Yes, I am confused by why the `Kconfig` has them all on by default but we are not seeing that in the generated `sdkconfig` in the build. Maybe we are not using the `esp32-camera` `Kconfig` properly.

**Comment by tannewt** [comment]
The ` is not set` are not actually just comments. They actually set the value to off. See https://github.com/zephyrproject-rtos/zephyr/issues/5443 for background.

**Pull request merged**
