### PR TITLE
Added default LWIP hostnames to FeatherS2 boards

### PR DESCRIPTION
**Pull request by UnexpectedMaker**

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Please include `UnexpectedMaker` in the name. This will not be the only Feather form factor S2 board.

**Comment by UnexpectedMaker** [comment]
Hmm, but mine *should* be the only board called "FeatherS2" as that is its actual name, not "Feather S2".  This is what appears on someones local LAN, so I cant see any issue with keeping the name as is and it's what I'd prefer.

**Comment by dhalbert** [comment]
FeatherS2 is pretty generic, because "Feather" is generic. How about "UMFeatherS2"?

**Comment by UnexpectedMaker** [comment]
> FeatherS2 is pretty generic, because "Feather" is generic and there are many ESP32S2 boards. How about "UMFeatherS2"?

Yeah, that works for me, good idea!

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
