### PR TITLE
same51: enable specific modules based on chip family

### LINKED ISSUE #4590: Built-In library for Feather M4 CAN missing rgbmatrix module
**Firmware**

Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather M4 CAN with same51j19a

**Code/REPL**

```python
import rgbmatrix

```

**Behavior**

code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
ImportError: no module named 'rgbmatrix'

**Description**

I have a Feather M4 CAN that I was trying to connect to a Featherwing RGB Matrix. It appears the "rgbmatrix" module is included in the 6.2.0 release for Feather M4 Express, but not in the build for the Feather M4 CAN. Is it going to be added or is there some issue running the M4 CAN?

**Additional Info**

### PR DESCRIPTION
**Pull request by jepler**
closes #4590

### CODE REVIEW

**Comment by dhalbert** [comment]
Build failure: looks like `protomatter` is only handling `SAMD51`, not a more general `SAMx5x`.

**Comment by jepler** [comment]
OK, we'll have to wait for https://github.com/adafruit/Adafruit_Protomatter/pull/38 to be merged and a release to be made.

**Comment by tannewt** [comment]
The `feather_m4_can` build is broken.

**Review by ladyada — APPROVED** [review]

**Comment by Fred-GitHub-001** [comment]
You're awesome. Tested and working great. Thanks!

**Pull request merged**
