### PR TITLE
Gain back space in small builds by using lib/libm instead of toolchain libm.

### PR DESCRIPTION
**Pull request by dhalbert**
1. Use lib/libm for small (non-Express builds) to gain back a lot of flash space.
2. Add flag INTERNAL_LIBM to mpconfigboard.mk files to signal using lib/libm.
3. Fix floating-point warnings in lib/libm
4. Turn off -finline-limit, no longer needed due to 1.
5. Add explicit flags for SPI_FLASH_FILESYSTEM and INTERNAL_FLASH_FILESYSTEM to mpconfigboard.mk files, so they don't need to know the name of the .c file that implements those. Makefile takes care of checking the flags and including the right files.

### CODE REVIEW

**Comment by dhalbert** [comment]
Didn't start a test build, I think due to my specifying the wrong upstream branch initially. Looks like I can trigger by closing and reopening. Will try that.

**Comment by tannewt** [comment]
I poked Rosie and restarted Travis.

Why not use the internal libm for all builds? Seems like consistency might be better.

**Comment by dhalbert** [comment]
ignore any churn right now -- committed some stuff to the wrong branch and undid it

**Comment by dhalbert** [comment]
@tannewt This is ready to look at again. Using internal libm for all atmel-samd builds now. Removed the pulseio addition on Gemma/Trinket: that will go in a new pull request.

**Pull request merged**
