### PR TITLE
Remove non-CircuitPython ports

### PR DESCRIPTION
**Pull request by dhalbert**
Remove non-CircuitPython ports. We discussed this a week or two ago in the weekly CircuitPython meeting, and there was general agreement to remove these for clarity. These ports have not kept up  with CircuitPython, except for `esp8266`, which was dropped. If and when we do a port to one of these platforms, we may choose a different directory name so as not to conflict with the MicroPython port name. (For example, we are using `stm32f4` for our port, instead of `stm32`.)

These ports have been removed. Each is in one commit, so it may be reverted easily, for whatever reason.

- `bare-arm`
- `cc3200`
- `esp32`
- `esp8266`
- `minimal`
- `pic16bit`
- `qemu-arm`
- `stm32`
- `teensy`
- `windows`
- `zephyr`

These ports remain:
- `atmel-samd`
- `nrf`
- `stm32f4`
- `unix`

Further work in this direction will bring the `unix` port closer to CircuitPython, such as removing dependencies on `extmod` in favor of `shared-*`.

### CODE REVIEW

**Comment by arturo182** [comment]
I believe there are submodules that are used only by the ports being removed so they could be removed too, for example "lib/stm32lib" and "lib/berkeley-db-1.xx".

**Comment by arturo182** [comment]
Does this also mean some of the old code only used by those ports will be removed too, like the machine modules?

**Comment by dhalbert** [comment]
@arturo182 `extmod`, which includes `machine`, will go away later, after i updated the remaining ports, including the `unix` port, to not use anything in `extmod`. We need to move various things in `extmod` like `re` and `json` to `shared-*`. I can clean up the submodules at that time as well; thanks for pointing those out.

**Comment by arturo182** [comment]
Sounds good to me. Nice to see CP dropping dead and unsupported code :)

**Comment by dhalbert** [comment]
@tannewt, OK, finally built correctly again.

**Pull request merged**
