### PR TITLE
Add the return value for the set_next_stack_limit function referenced…

### PR DESCRIPTION
**Pull request by spencer-burke**
… in #4520

Changes to be committed:
	modified:   shared-bindings/supervisor/__init__.c

### CODE REVIEW

**Comment by spencer-burke** [comment]
I have made a change and created the pr, if you would like me to write some tests of some kind I would be happy to.

**Review by microDev1 — CHANGES_REQUESTED** [review]
Thanks for the PR @spencer-burke.

I don't think this resolves issue #4520. The `stack` size is set on the next `VM` run so with the function call there isn't a way to confirm whether the requested `stack_limit` is used or the `default_limit` is used. 

I think changing the function name to something more appropriate like `set_next_stack_limit_maybe` should be enough here. This will result in a breaking change and the PR will have to be considered for `8.0.0` rather than merging it now

**Comment by spencer-burke** [comment]
Alright, I will revert the changes I have made, and change the function name.

**Comment by tannewt** [comment]
I don't think it's helpful to return the passed in value. Thanks for the PR anyway!

**Pull request closed without merging**
