### PR TITLE
nrf: put supervisor enable/disable tick in place

### PR DESCRIPTION
**Pull request by jepler**
I assume that the "same" fix as samd is needed in order to make audio play properly after reduced power.

Testing performed: only building the software

### CODE REVIEW

**Comment by jepler** [comment]
@tannewt I can look into it if you have a pointer to where else we're doing this.  In samd audio it looks like audio interrupts "are involved" (e.g., we look at event_interrupt_active to decide whether more data needs to be fed) but it still didn't work, which is why #2889 had a similar "fix" for audio weirdness.  I guess both could use further looking into rather than speculative fixes.

**Comment by jepler** [comment]
e.g., in nRF I2SOut we can allow EVENTS_TXPTRUPD  to generate an interrupt.  But there is no explicit handler defined for it.  Does this mean it would get a dummy interrupt handler and all would be well?

**Comment by tannewt** [comment]
> @tannewt I can look into it if you have a pointer to where else we're doing this. In samd audio it looks like audio interrupts "are involved" (e.g., we look at event_interrupt_active to decide whether more data needs to be fed) but it still didn't work, which is why #2889 had a similar "fix" for audio weirdness. I guess both could use further looking into rather than speculative fixes.

Ya, I should have thought about it more with the samd fix as well. I'm ok having it in temporarily. It would be good to look into for the longer term though. Relying on tick is a heavy handed way of getting it to work.

> e.g., in nRF I2SOut we can allow EVENTS_TXPTRUPD to generate an interrupt. But there is no explicit handler defined for it. Does this mean it would get a dummy interrupt handler and all would be well?

I don't think the interrupt handler itself is actually needed. The main thing is that it wakes up the  WFI in sleep and then clears the interrupt in the background task.

**Comment by tannewt** [comment]
@jepler Do you have time to look into using DMA interrupts instead of ticks?

**Pull request merged**
