### PR TITLE
camera: Update camera_make_new arguments

### PR DESCRIPTION
**Pull request by kamtom480**

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Was the compiler unable to detect this? Shouldn't this have broken the build with the 1.17 update?

**Comment by microDev1** [comment]
> Was the compiler unable to detect this? Shouldn't this have broken the build with the 1.17 update?

The warning is being ignored:
```c
../../shared-bindings/camera/Camera.c: In function 'camera_make_new':
../../shared-bindings/camera/Camera.c:68:30: warning: passing argument 2 of 'mp_arg_check_num' makes integer from pointer without a cast [-Wint-conversion]
   68 |     mp_arg_check_num(n_args, kw_args, 0, 0, false);
      |                              ^~~~~~~
      |                              |
      |                              mp_map_t * {aka struct _mp_map_t *}
In file included from ../../shared-bindings/camera/Camera.c:28:
../../py/runtime.h:87:59: note: expected 'size_t' {aka 'unsigned int'} but argument is of type 'mp_map_t *' {aka 'struct _mp_map_t *'}
   87 | static inline void mp_arg_check_num(size_t n_args, size_t n_kw, size_t n_args_min, size_t n_args_max, bool takes_kw) {
      |                                                    ~~~~~~~^~~~
../../shared-bindings/camera/Camera.c: At top level:
../../shared-bindings/camera/Camera.c:130:17: warning: initialization of 'void * (*)(const mp_obj_type_t *, size_t,  size_t,  void * const*)' {aka 'void * (*)(const struct _mp_obj_type_t *, unsigned int,  unsigned int,  void * const*)'} from incompatible pointer type 'void * (*)(const mp_obj_type_t *, size_t,  void * const*, mp_map_t *)' {aka 'void * (*)(const struct _mp_obj_type_t *, unsigned int,  void * const*, struct _mp_map_t *)'} [-Wincompatible-pointer-types]
  130 |     .make_new = camera_make_new,
      |                 ^~~~~~~~~~~~~~~
../../shared-bindings/camera/Camera.c:130:17: note: (near initialization for 'camera_type.make_new')
```

**Review by microDev1 — APPROVED** [review]
LGTM! Thanks @kamtom480.

**Comment by jepler** [comment]
Thank you! I'm sorry I didn't catch this during the 1.17 merge, but as you may have guessed I was relying solely on fatal compiler diagnostics to find all the relevant sites.

  If possible, as a fresh PR, can you enable -Werror & other diagnostic flags so that we catch these errors during builds? If there are sites in the SDK that have diagnostics, they can be selectively disabled; there are examples of this in the atmel-samd port.

If you're able to take on that additional work, thank you again!

**Pull request merged**
