### PR TITLE
Add new board: Cytron Maker Nano RP2040

### PR DESCRIPTION
**Pull request by waiweng83**
Hi, can you please help to add this new board?

https://www.cytron.io/maker-nano-rp2040-simplifying-projects-with-raspberry-pi-rp2040

Thanks.

### CODE REVIEW

**Comment by waiweng83** [comment]
May I know what's wrong with my PR causing the test to fail?
It seems like the files that causing the fail is not from my PR.

**Comment by dhalbert** [comment]
> May I know what's wrong with my PR causing the test to fail? It seems like the files that causing the fail is not from my PR.

The failures are due to a new version of `black` being used to check the formatting of `.py` files in the source tree. There are some minor spacing changes it wants. I added these changes in #5667 but if that is not going to be accepted right away I can make a new PR that is just the spacing changes, and that should get approved quickly. I will check with the other core developers.

**Comment by dhalbert** [comment]
Your PR is otherwise fine, so I don't see why the formatting issues should hold it up.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Comment by dhalbert** [comment]
Note that this PR is against `main`. We have now made a branch, `7.1.x`, so this will not get into `7.1.0`, but will be in the 7.2.x series and later. If you want it in 7.1.x, could you make a PR against `7.1.x`? It could just be a cherry-pick of the commits here.

**Comment by waiweng83** [comment]
> Note that this PR is against `main`. We have now made a branch, `7.1.x`, so this will not get into `7.1.0`, but will be in the 7.2.x series and later. If you want it in 7.1.x, could you make a PR against `7.1.x`? It could just be a cherry-pick of the commits here.

Ok noted. Will do.

Thanks a lot.

**Pull request merged**
