### PR TITLE
ESP32: Control rx Echo when pasting into REPL paste mode in order to prevent data loss 

### LINKED ISSUE #9429: Pasting large amounts of text to REPL on ItsyBitsy ESP32 results in dropped data
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0 on 2024-07-10; Adafruit ItsyBitsy ESP32 with ESP32
```

### Code/REPL

```python
None
```

### Behavior

When pasting more than about 500 characters into the REPL, either normal mode or CTRL-E paste mode, some of the characters being pasted get dropped.

### Description

I started trouble shooting this in issue #9362 by pasting a 12.5K python script into the REPL using the Ctrl-E paste mode. The basic observation was:

> When I paste code to a Ctrl-E repl of the ItsyBitsy ESP32 it consistently starts dropping characters after 255 characters. After skipping about 275 characters, another 124 characters are correctly received and then 937 characters are dropped followed by another 152 properly transmitted characters, etc.....  

### Additional information

I was able to improve the size of the file that could be pasted without error by decreasing the UART baud rate or increasing the `console_uart_rx_buf` size.

By commenting out the console echo of the pasted data, I was able to successfully paste the entire 12.5K script without error. 

I also made a modification to `common_hal_busio_uart_write` module in ports/espressif/common-hal/busio/UART.c which I believe prevented the routine from waiting for the UART to become available when transmitting (echoing to the display) a character. This mod resulted in intermittent characters not being echo'd, however the REPL did receive the entire file without error. Increasing the SOC_UART_FIFO_LEN from 128 to 250 had the same result, I'm guessing this prevented the `uart_ll_get_txfifo_len` function from ever reporting the transmit buffer as full so the uart_writes were not held up. 

After a lot of hacking and staring my current theory about what's happening is that the UART rx interrupts are coming in so fast and frequently that the UART is not able to echo the characters back out to the console. I think this results in the FIFO receive buffer filling up which causes ESP-IDF to disable the uart interrupts. That allows the transmit buffer to empty and display the first buffer full of characters, however while the interrupts are disabled, any characters being pasted are lost. The ESP-IDF then re-enables the interrupts when there is FIFO buffer space again and the cycle repeats.

Without the ability to get flow control to the CH9102 chip, I can't think of a great solution to this issue especially since it seems to be limited to the ESP32 boards. It should be noted that the issue doesn't impact RAW REPL mode, presumably because it doesn't echo data and therefore attempt to simultaneously use the UART for RX and TX functions.

### PR DESCRIPTION
**Pull request by RetiredWizard**
Fixes #9429 

I took this further than I was planning, but these changes do resolve the UART issues when pasting large files into the REPL paste (CTRL-E) mode on ESP32 boards that don't have uart flow control capability.

The first [commit](https://github.com/adafruit/circuitpython/commit/e1e6aed68515bd2974af910233fcc1387e6e6c7a) simply drops any echo characters when the ESP-IDF indicates the transmit buffer is not available (full?) and does allow the successful paste of large files, however the echo'd output is pretty sparse and doesn't much resemble the transmitted file.

The final version uses the vstr variable the pasted data is being loaded into as a UART output buffer so that the echo (tx process) can fall behind the pasted data input (rx). The routine doesn't attempt to echo if there is serial data available for input and whenever serial input is detected or the tx routines detect that the transmit buffer is unavailable no more attempts to transmit are made for 100ms.

Other than the CTRL-E pasting loop in pyexec.c there were basically two changes made to get this to work. 

The first was a bit of a hack, because I didn't want to add a new parameter to all of the modules in the uart tx chain (mp_hal_stdout_tx_strn->serial_write_substring->common_hal_busio_uart_write) as that would involve updating any module that called any of those routines. So instead I used the sign of the "length" argument as a flag to indicate whether the common_hal_busio_uart_write module should do it's normal retry loop until the data was transmitted or simply try once for each character being transmitted. If a negative length was passed, the uart_write module would essentially not retry the writes and would also not kick off the BACKGROUND_TASKS that normally ran while the retries were occurring.

The second change was to update the serial TX modules to properly pass back the number of bytes actually transmitted. After making this change, it turned out that the ESP32 uart tx functions are not completely reliable in detecting when a tx fails (my guess is that if between the time the routines check the availability of the tx buffer and the time the data is put onto the output registers the tx buffer becomes unavailable, then the data will not transmit). Since the tx failure detection was not completely reliable some of the echo output were still being lost (the echo'd display did much more closely resemble the pasted data though), adding the 100ms delay to tx write seems to resolve any lost echo'd data issues.

I don't have any training or real experience in writing C code so if the Adafruit folks think this PR is worth pursuing, don't worry about commenting on what I'm sure are my many poor programming style/functional choices :grin:

### CODE REVIEW

**Comment by RetiredWizard** [comment]
Okay, I'm not sure but I think this CI failure is not my fault :grin:

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks for thinking about this. I would say:

- `common_hal_busio_uart_write()` is used for `busio.UART()` in general, so adding specialized features like the negative length hack for this very specific case is not the place to do this. Instead, I would create a specialized path for the console UART when it has no flow control available. It is just an accidental convenience that we have been using `common_hal_busio_uart_write()` for console writes. It would be better to create a specialized routine to do the delayed writes for this specific case.
- REPL paste mode, as developed by MicroPython and also provided by us, assumes good flow control. It is a casual feature that doesn't even exist in CPython. If it doesn't work on boards with no flow control, that's a problem we don't really have to solve. Better to use an intermediary like Thonny or other smart editor or just add some delay per character or per newline when using a terminal program so a solution in CircuitPython is not necessary. For instance, `tio` can add delays between characters or lines. In other words, I want to define the problem away by having the paste rate-limited externally.

**Comment by RetiredWizard** [comment]
I agree completely :grin: I really started just to convince myself there was no HW/SW flow control option and got trapped down the rabbit hole :laughing:

It was really fun getting the pastes to work and echo perfectly though....

**Comment by dhalbert** [comment]
One interesting thing that you have anticipated is that upstream, as of MicroPython v1.22, `mp_hal_stdout_tx_strn()` _does_ return a length rather than being `void`. I am in the middle of doing that merge and haven't yet looked at why that return value was added.

**Comment by dhalbert** [comment]
@RetiredWizard No problem, it's good to think out of the box on this. This issue provoked a discussion internally where we came up with the terminal-program idea.

**Pull request closed without merging**
