### PR TITLE
Updated UM FeatherS2 boards

### PR DESCRIPTION
**Pull request by UnexpectedMaker**
Updated board files for FeatherS2 & FeatherS2 Prerelease

### CODE REVIEW

**Comment by tannewt** [comment]
Why are you including .py files in the board directory? If you are trying to ship with a demo that uses it, then the files should live on the FAT filesystem along with the example code.py.

Generally, frozen modules should only be used to save RAM on constrained devices like the SAMD21. The ESP32-S2 doesn't have that constraint and really shouldn't have frozen modules. Frozen code is hard to understand because it isn't on the drive. It's typically older code and it's impossible for the user to update.

**Comment by UnexpectedMaker** [comment]
> Why are you including .py files in the board directory? If you are trying to ship with a demo that uses it, then the files should live on the FAT filesystem along with the example code.py.
> 
> Generally, frozen modules should only be used to save RAM on constrained devices like the SAMD21. The ESP32-S2 doesn't have that constraint and really shouldn't have frozen modules. Frozen code is hard to understand because it isn't on the drive. It's typically older code and it's impossible for the user to update.

Because I think it's confusing for folks having just on the FS when they might not understand why it's there, when on "constrained devices" they don't have to have it there to use their Dostar. Seems inconsistent, but I'm happy to unfreeze and put it on the FS if that's what you prefer.

I did speak to you about this a while ago when I was asking you how to freeze modules and you asked me why back then ;)

**Comment by UnexpectedMaker** [comment]
@tannewt Please let me know if you are ok with what I have now. I really want it in for beta 1 :)

**Review by tannewt — DISMISSED** [review]
Yup! This looks good.

**Comment by tannewt** [comment]
You'll need to add the prerelease board name to the github workflow to get the CI to pass: https://github.com/adafruit/circuitpython/pull/3463/checks?check_run_id=1162679057 and adjust the line endings for these two files: https://github.com/adafruit/circuitpython/pull/3463/checks?check_run_id=1162679034 (Exactly one line at the end.)



> Because I think it's confusing for folks having just on the FS when they might not understand why it's there, when on "constrained devices" they don't have to have it there to use their Dostar. Seems inconsistent, but I'm happy to unfreeze and put it on the FS if that's what you prefer.

I prefer having it on the FS so folks know they can update it.

> I did speak to you about this a while ago when I was asking you how to freeze modules and you asked me why back then ;)

I know but this time it looks like I can convince you. :-P

> EDIT: I already put my feathers2.py helper in the FS anyway, so I can just put the Dotstar lib with that. Is it good practice to put them in the lib folder? or just in the root?

I'd leave the feathers2.py helper outside of lib because it is board specific but put the rest in lib for clarity. That way the top level only has feathers2.py and code.py.

**Comment by UnexpectedMaker** [comment]
Ok, sounds good!

**Comment by UnexpectedMaker** [comment]
@tannewt I fixed the last lines on the 2 .mk files, but I have no idea how to do...

> You'll need to add the prerelease board name to the github workflow to get the CI to pass: https://github.com/adafruit/circuitpython/pull/3463/checks?check_run_id=1162679057

I've never used (or even looked at) git workflows before, sorry. Git noob here!

**Comment by tannewt** [comment]
Here is a better link: https://github.com/adafruit/circuitpython/pull/3463/checks?check_run_id=1175885989#step:22:7

You need to add the new board name here: https://github.com/adafruit/circuitpython/blob/main/.github/workflows/build.yml#L423

**Comment by UnexpectedMaker** [comment]
> Here is a better link: https://github.com/adafruit/circuitpython/pull/3463/checks?check_run_id=1175885989#step:22:7
> 
> You need to add the new board name here: https://github.com/adafruit/circuitpython/blob/main/.github/workflows/build.yml#L423

Ok, I hope I did it correctly!

**Comment by tannewt** [comment]
@UnexpectedMaker You'll want to make the change on this PR's branch. I closed the other PR.

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker You'll want to make the change on this PR's branch. I closed the other PR.

Done - I think!

**Comment by UnexpectedMaker** [comment]
@tannewt Ok, 3rd times a charm? It didn't like me doing it from my other Mac for some reason.
This PR has now been updated. Pleaser delete the other one I created a few mina ago _ I don't seem to be able to delete it myself.

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by tannewt** [comment]
Failing test was a network error. Unrelated to this PR.

**Pull request merged**
