### PR TITLE
make Pin hashable

### LINKED ISSUE #6179: Make `microcontroller.Pin` hashable, so pins can be used as dictionary keys
There are examples (e.g., https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/pull/114), where it would be desirable to use `Pin`s directly as dictionary keys.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #6179.

I keep encountering cases where I would like to `microcontroller.Pin` objects to be in a `set()` or be dictionary keys.

### CODE REVIEW

**Comment by jepler** [comment]
Can you use this existing function?
```c
mp_obj_t mp_generic_unary_op(mp_unary_op_t op, mp_obj_t o_in) {
    switch (op) {
        case MP_UNARY_OP_HASH:
            return MP_OBJ_NEW_SMALL_INT((mp_uint_t)o_in);
        default:
            return MP_OBJ_NULL;      // op not supported
    }    
}
```
It's used, for instance, for function objects unary op slot so that they can be set members...

**Comment by dhalbert** [comment]
> Can you use this existing function?

Oh, sure, I didn't realize it existed. I have some other places I can use it too.

**Review by jepler — APPROVED** [review]
Thank you! Looks good, didn't test.  Too bad none of the other savings are in things enabled in our tiniest ports.

**Review by jepler — COMMENTED** [review]
I don't see what changed since the previous iteration, still looks OK as long as it's green.

**Review by jepler — APPROVED** [review]

**Comment by dhalbert** [comment]
There was a stray `<` character at the end of one file, I think from typing in the wrong window. Thanks!

**Pull request merged**
