### PR TITLE
refactor displayio set_pixel for use in bitmap_tools

### PR DESCRIPTION
**Pull request by kmatch98**
This refactors `_set_pixel` function into its two main functions, updating the dirty area and writing the pixel.  This allow reuse of the `_set_dirty_area` and `_write_pixel` with other bitmap manipulation functions (and providing a minor speedup to `_blit`).

I updated the `_blit` function to use these new sub-functions.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
This makes sense to me.

**Comment by kmatch98** [comment]
I forgot to mention. I ran `make translate`and the diff showed one entry that was removed “ Group full.”  I didn’t touch that file so maybe this is some leftover from Deshipu’s group update to displayio?

Let me know if I need to add the `locale/circuitpython.pot` to this PR.

**Comment by dhalbert** [comment]
Groups no longer have a limit, so that makes perfect sense.

**Comment by jepler** [comment]
.. and the translation check only signals an error in the case of NEW messages, not REMOVED ones. This is perhaps unexpected, but it's what the code says.

**Comment by kmatch98** [comment]
Thanks for clarifying. (I was mainly worried that my poor git skills somehow caused it.)

**Pull request merged**
