### PR TITLE
Sleep API changes and fix for main.c silent issue

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds the `common_hal` prefix to a number of sleep-related functions to identify that they are implemented on the port level, and adds the new weakly linked `common_hal_alarm_pretending_deep_sleep` function, which is required for both the NRF and STM32 sleep implementations. It also fixes a small problem with the deep sleep implementation in `main.c`, where the 5 second USB delay would set up to use `port_idle_until_interrupt` but never actually call it.

Result of a discussion with @dhalbert. Contains the api breaking elements of both #4388 and #4236, ideally it should be merged before/immediately after either of them so all implementations of Alarm can be on the same page going forward.

### CODE REVIEW

**Comment by dhalbert** [comment]
I made this a draft just so it's not merged accidentally.

**Comment by hierophect** [comment]
@dhalbert There shouldn't be anything breaking the Circuitpython API in here, it'd just add extra work for @jun2sak if merged before their PR. If we merge NRF first, then I'll handle the merge here in this one.

**Comment by hierophect** [comment]
@dhalbert if you're ready to give this a review, I can handle the merging on the NRF port.

**Review by dhalbert — APPROVED** [review]
These clarifications are good and fine with me!

**Pull request merged**
