### PR TITLE
ulab: Update to release tag 1.1.0

### PR DESCRIPTION
**Pull request by jepler**
Disable certain classes of diagnostic when building ulab.  We should submit patches upstream to (A) fix these errors and (B) upgrade their CI so that the problems are caught before we want to integrate with CircuitPython, but not right now.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by tannewt** [comment]
meowbit and thunderpack builds ran out of space.

**Review by tannewt — APPROVED** [review]
Looks good to me! Just needs a merge.

**Comment by dhalbert** [comment]
@jepler want to get this in to the beta?

**Comment by jepler** [comment]
Rebased to resolve translation conflict, no other changes intended.

**Review by tannewt — APPROVED** [review]
Looks good to me!

**Pull request merged**
