### PR TITLE
sys: remove nonstandard print_exception

### PR DESCRIPTION
**Pull request by jepler**
CircuitPython provides this at `exception.print_exception()`, with improved compatibility with standard Python.

This is an alternative to #9427, which adds documentation for the non-standard function.

One reason NOT to take this change is that the traceback module is not built on samd21s, leaving non-standard `sys.print_exception` as the only way to print an exception object (besides raising it)

### CODE REVIEW

**Comment by dhalbert** [comment]
I looked in the bundle and in the Learn Guide code, and `sys.print_exception()` is only used in code that runs on larger boards. It _is_ used, so the few places it's used should be fixed to used `traceback`.

```
libraries/drivers/mcp2515/examples/mcp2515_canio_test.py
libraries/helpers/debouncer/examples/debouncer_unittest.py
```

**Comment by dhalbert** [comment]
I think I am OK with samd21 not being able to print tracebacks "manually". There are so many other things limited in that port, this is not such a big deal. You can still print info about the exception.

**Comment by tannewt** [comment]
Let's remove in CP10 and add a FutureWarning now because code can be moved to `traceback` now. (I assume `traceback` is in 8.x too.)

**Comment by jepler** [comment]
OK I'll close this up but leave the branch.

**Comment by jepler** [comment]
Yes it's in 8.2.x https://docs.circuitpython.org/en/8.2.x/shared-bindings/traceback/index.html

**Comment by tannewt** [comment]
@jepler Can you add the warning? RetiredWizard's PR only updates the docs.

**Comment by RetiredWizard** [comment]
Great minds think alike.... :grin: #9450

**Pull request closed without merging**
