### PR TITLE
Retry connection when getting NOT_AUTHED

### PR DESCRIPTION
**Pull request by tannewt**
I saw it once with a correct password. Retrying may still fail
but at least it'll try first.

@todbot, this may help you too.

### CODE REVIEW

**Comment by tannewt** [comment]
@todbot I think you are hitting a separate issue. This was only intended to fix the "unknown failure" on connection.

**Comment by anecdata** [comment]
Naive question, but on second thought (ref: Discord comments on `WIFI_REASON_...`) do we care what the reason is once we know we're in SYSTEM_EVENT_STA_DISCONNECTED state, unless we want to log it or raise it to the user? All reasons mean we're already disconnected, and we need to re-connect (unless scanning or intentionally disconnecting (which we don't yet have an API for).

**Comment by tannewt** [comment]
@anecdata Yes, we don't want to retry if we initiated the disconnect.

**Review by jepler — APPROVED** [review]
I don't know enough to judge, but this looks okay.

(I do also see hangs during wifi connecting to 2 out of my 3 APs, but when this happens the last log messages are
```
W (46652776) wifi: connected
I (46652786) wifi:AP's beacon interval = 102400 us, DTIM period = 2
```
so I don't think this will fix my problems)

**Pull request merged**
