### PR TITLE
merge hexky_s2 board

### PR DESCRIPTION
**Pull request by CircuitART**
Hello, please add support to my custom esp32-s2 board.
thanks

### CODE REVIEW

**Comment by dhalbert** [comment]
Could you say where you got the VID/PID from?
```
USB_VID = 0x303A
USB_PID = 0x80D9
```

**Review by dhalbert — CHANGES_REQUESTED** [review]
Hi, your `mpconfigboard.h` file is using tabs instead of spaces for some indentation. Please use only spaces, and make them line up. I think this is causing the formatting error mentioned in https://github.com/adafruit/circuitpython/runs/5491224618?check_suite_focus=true. You can check for this in your local repo by using pre-commit: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

**Comment by CircuitART** [comment]
> https://github.com/adafruit/circuitpython/runs/5491224618?check_suite_focus=true

my VID/PID from espressif, here is a link to the approval from them
https://github.com/espressif/usb-pids/pull/32

**Comment by CircuitART** [comment]
> Could you say where you got the VID/PID from?
> 
> ```
> USB_VID = 0x303A
> USB_PID = 0x80D9
> ```

my VID/PID from espressif, here is a link to the approval from them
https://github.com/espressif/usb-pids/pull/32

**Comment by CircuitART** [comment]
> Hi, your `mpconfigboard.h` file is using tabs instead of spaces for some indentation. Please use only spaces, and make them line up. I think this is causing the formatting error mentioned in https://github.com/adafruit/circuitpython/runs/5491224618?check_suite_focus=true. You can check for this in your local repo by using pre-commit: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code

OKay will check now. thanks

**Comment by dhalbert** [comment]
> my VID/PID from espressif, here is a link to the approval from them [espressif/usb-pids#32](https://github.com/espressif/usb-pids/pull/32)

Great, thanks!

**Comment by dhalbert** [comment]
Problem now is trailing spaces after the commas in `pins.c`.

**Comment by dhalbert** [comment]
> Problem now is trailing spaces after the commas in `pins.c`.

Some editors have settings to remove trailing spaces automatically.

**Comment by CircuitART** [comment]
> > Problem now is trailing spaces after the commas in `pins.c`.
> 
> Some editors have settings to remove trailing spaces automatically.

working on that still. had to switch from mac to windows

**Review by CircuitART — COMMENTED** [review]
whitespaces removed

**Review by dhalbert — APPROVED** [review]
Great! Thanks for your patience.

**Comment by CircuitART** [comment]
Thank you for your help, have a great day

**Pull request merged**
