### PR TITLE
Save wake alarm info in static storage, simplifying recording of alarm

### LINKED ISSUE #6483: pico: alarm.wake_alarm not set after deep-sleep
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0 on 2022-05-23; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
n.a.

 Example program: https://github.com/bablokb/pico-sleepcurrent/blob/main/cp-memory/main.py
```

### Behavior

...

### Description

After deep-sleep with a timer-alarm, the variable `alarm.wake_alarm` is not set. The test-program linked above works as expected while connected to an usb host (simulated deep-sleep). I.e. in this case `alarm.wake_alarm` is set. But if not connected (only powered), the variable is not set.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #6483; subsumes PR #7137.

Changes how alarm.wake_alarm is set. Instead of creating an alarm on the heap, after the VM is set up, a static alarm object is used instead, which can be set up outside of the VM.

This simplifies how and when to store the alarm info, and removes the need for the `first_run` boolean that was passed around in `main.c`.

Use `#pragma once` instead of `#ifdef` `#include` guards for alarm-related `.h` files: some were missing, so I just changed them all, to be consistent. Also make some other naming more consistent.

@georgboe, @bablokb your testing is welcome. Tested with fake deep sleep and real deep sleep with a battery on Adafruit Feather RP2040, Feather M4, Feather STM32F405, Feather nRF52840, and Feather ESP32-S2.

Test program, which writes to UART, for battery operation, and to USB:
```py
import digitalio
import board
import alarm
import time

uart = board.UART()
uart.baudrate = 115200

led = digitalio.DigitalInOut(board.LED)
led.switch_to_output(True)
time.sleep(2)
led.value = False
msg = "Alarm was " + str(alarm.wake_alarm) + "\r\n"
print(msg, end = "")
uart.write(msg.encode("utf-8"))

time_alarm = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + 5)

msg = "Entering deep sleep at " + str(time.monotonic()) + "\r\n"
print(msg, end="")
uart.write(msg.encode("utf-8"))
time.sleep(0.1)   # allow time for uart.write() to finish

alarm.exit_and_deep_sleep_until_alarms(time_alarm)
```

### CODE REVIEW

**Comment by georgboe** [comment]
@dhalbert I tested now on a Pico W and it works perfectly.

**Comment by dhalbert** [comment]
> @dhalbert I tested now on a Pico W and it works perfectly.

Thank you for testing!

**Review by jepler — APPROVED** [review]
Thanks! I don't 100% follow the changes in main.c but I am relying on the testing.

**Comment by bablokb** [comment]
Tests ok with TimeAlarm and PinAlarm, thanks. There might be a  regression: entering deep-sleep should release the display. At least there was a pull-request for that as far as I remember. And it does work for a few cycles (run-deep-sleep-run-...) and then stops working. Not sure if this is related to this patch, because I have not tested before merging your patch, but I will do so within the next few days.

**Pull request merged**
