### PR TITLE
Nickzoic/circuitpython nrf touchin 1048

### PR DESCRIPTION
**Pull request by nickzoic**
A much-simplified approach to touch sensing for #1048 !

This is a capacitive touch sensing routine using a single digital
pin.  The pin should be connected to the sensing pad, and to ground
via a 1Mohm or thereabout drain resistor.  When a reading is taken,
the pin's capacitance is charged by setting it to a digital output
'high' for a few microseconds, and then it is changed to a high
impedance input.  We measure how long it takes to discharge through
the resistor (around 50us), using a busy-waiting loop, and average
over N_SAMPLES cycles to reduce the effects of noise.

### CODE REVIEW

**Comment by nickzoic** [comment]
Manually tested on Feather NRF52832 and Feather NRF52840 Express boards, with code like:
```
import board
import touchio
import time

def auto_set_threshold(t):
    t.threshold = int(sum(t.raw_value for _ in range(0,100)) / 95))

t0 = touchio.TouchIn(board.A0)
t1 = touchio.TouchIn(board.A1)

auto_set_threshold(t0)
auto_set_threshold(t1)

while True:
    print("%4d %d %4d %d" % (t0.raw_value, t0.value, t1.raw_value, t1.value))
```

**Comment by tannewt** [comment]
How about auto setting a threshold on object creation? That's what the SAMD does already. That way folks don't need to set it themselves before using it.

**Comment by nickzoic** [comment]
Sure, we can totally do that. I'll add it in.

**Comment by ladyada** [comment]
tested, works well - thanks!

**Pull request merged**
