### PR TITLE
Pico_Plus_2: cleanup pin-names

### PR DESCRIPTION
**Pull request by bablokb**
This PR does some cleanup on pin-names:

* renamed `SPICE_xxx` to `SPCE_xxx` (Pimoroni calls their connector SP/CE)
* removed `SPI` (`board.SPI()` throws `NotImplementedError` anyways)
* added normal `GPxx` names since all pins are normal GPIOs as well
* removed `SPICE_TX` and `SPICE_RX`. RX/TX pin names are UART-related on other boards. Here, they are only inclusive names for MOSI/MISO. It turns out that `SPICE_TX` is an UART-RX and vice versa. So to avoid confusion, I removed the names.

Adding a `board_spi_obj` (thus preventing the `NotImplementedError`) would be possible, but I don't think this makes sense. The SP/CE connector lacks a DC-pin and busy-pin. So to drive a SPI-screen, it is better to create an SPI object without MISO and use the pin for DC.

I would even suggest to remove `SCK`, `MISO` and `MOSI` as well. They are already defined as `SPCE_SCK` (and so on). The pure names suggest that there is something like a default SCK/MISO/MOSI on the Pico, which is not the case and is not implemented for other Pico-boards.

@ZodiusInfuser: maybe you could chime in and share your opinion regarding the pin-names

### CODE REVIEW

**Comment by ZodiusInfuser** [comment]
I believe the SPICE name was copied from what @gadgetoid set within our C header for the product (e.g. https://github.com/pimoroni/pimoroni-pico-rp2350/blob/feature/wireless/micropython/board/PIMORONI_PICO_PLUS2/pimoroni_pico_plus2w_rp2350.h), though why he included the `I` I don't know.

The other changes sound sensible to me.

**Comment by Gadgetoid** [comment]
"SPICE" flows better and is easier to say, I will die on this hill.

image

**Comment by dhalbert** [comment]
Whatever is consistent for your pin names elsewhere (MicroPython, Arduino, board silk, etc.) is OK with us.

**Comment by bablokb** [comment]
Although I use SPICE for simulation and when I am cooking, I have no problem reverting to SPICE naming again to make all spice boys and girls happy. Just let me know.

**Comment by dhalbert** [comment]
@ZodiusInfuser @Gadgetoid Is Pimoroni in agreement that it should be `SPICE`? It have found only one use of that term on pimoroni.com, in the forums. We can also have an alias with `SP_CE` as part of the name.

**Comment by Gadgetoid** [comment]
I'm going to defer to @ZodiusInfuser on this one 👀 

We can probably change the Pico SDK headers to `SPCE` without too much hassle since it's still early days.

**Comment by ZodiusInfuser** [comment]
Thanks for that .....

Go with `SPCE` like this PR already does. We'll (*cough* @Gadgetoid ) fix it in other places.

**Review by dhalbert — APPROVED** [review]
I think we have settled on the names. Thanks everyone.

**Pull request merged**
