### PR TITLE
Merge 7.2.2 changes into main

### PR DESCRIPTION
**Pull request by tannewt**
This brings in the reload changes which will be good to test on main. It also brings in the removal of `CIRCUITPY_AUTORELOAD_DELAY_MS` definitions in each board that were never changed but copied everywhere.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
And also the espressif I2c pullup fix

**Comment by dhalbert** [comment]
@tannewt want to pull in the latest autoreload stuff?

**Comment by tannewt** [comment]
Sure, I might as well since the CI didn't run on that last commit. Will look at the supervisor.reload issue first.

**Review by dhalbert — APPROVED** [review]
Thanks! Hope this fits.

**Pull request merged**
