### PR TITLE
Reset cwd before looking for files to run

### LINKED ISSUE #8295: Current working directory survives reload
### CircuitPython version

```python
Adafruit CircuitPython 8.2.3 on 2023-08-11; Fluff M0 with samd21e18
```

### Code/REPL

```python
# /code.py

import supervisor
import os

print("changing directory to /test")
os.chdir('/test')
supervisor.reload()
```

```python
# /test/code.py

import supervisor
import os

print("inside /test")
print("__file__=", __file__)
print("cwd=", os.getcwd())
```

### Behavior

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
inside /test
__file__= code.py
cwd= /test
```

### Description

Seems like cwd survives a reload to the point where the code checks for `code.py` file, and if there is such a file in the current directory, it is executed instead of the `code.py` in the root directory.

### Additional information

I stumbled upon this trying to make the game selection menu for my handheld game console. It makes it impossible to return back to the menu once the game finished running.

### PR DESCRIPTION
**Pull request by deshipu**
Make sure we only look for the files in the root directory.

Fixes #8295

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
This doesn't reset the current directory until `code.py` is run, after. The current directory should probably be reset for `boot.py`, `safemode.py`, and `code.py`. So I think it should be reset in `start_mp()`. Or should it _not_ be reset between `boot.py` and `code.py`? That's something to ponder, about whether to make `boot.py` be able to change the current directory in a sticky way.

Also, if the filesystem is not working, I think `chdir()` may throw an error. Maybe better to check with `filesystem_present()` before claling it.

**Comment by deshipu** [comment]
There is no way to change the directory before `boot.py` runs, so I don't think there is a need to reset it there. Also, `start_mp` only runs once at the beginning, but the nature of the problem comes from cwd persisting across reloads, not from the initial conditions.

I don't see the `maybe_run_list` function checking for the filesystem, so I assumed that by this point it has already been checked? I don't really have a way of testing this without a filesystem.

**Comment by dhalbert** [comment]
Good point about `boot.py`, I wasn't thinking too clearly.

To fake not having a filesystem, temporarily add a `return false;` just before `// try to mount the flash` in `filesystem_init()` in `supervisor/shared/filesystem.c`.

**Comment by deshipu** [comment]
When I do that, I get:

```
Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CIRCUITPY drive could not be found or created.

Press any key to enter the REPL. Use CTRL-D to reload.
```

No crash.

**Comment by dhalbert** [comment]
So it never gets to running the code.py that's good.

**Review by dhalbert — APPROVED** [review]
My concerns (some incorrect) all accounted for. Thanks!

**Comment by deshipu** [comment]
There is still the case when someone uses chdir in boot.py and the board goes into safe mode and runs the wrong safemode.py, but I think that's a self-inflicted wound?

**Comment by dhalbert** [comment]
`ja` `pygamer` is overflowing, but we don't need to fix that here.

**Comment by dhalbert** [comment]
> There is still the case when someone uses chdir in boot.py and the board goes into safe mode and runs the wrong safemode.py, but I think that's a self-inflicted wound?

safemode.py is run after a hard reset, so I think that cannot happen?

**Comment by deshipu** [comment]
Excellent.

**Pull request merged**
