### PR TITLE
8.2.x backport waveshare-esp32-s3-pico

### PR DESCRIPTION
**Pull request by tirtharajsinha**
I have added this board to main branch but noticed only circuitpython 9.x.x build is available And also no direct download and installation option on page. Userd have to find that build from s3. 

This board is comparatively new and manufacturer tergets beginner audience. So trying to make new users journey as smooth as possible.

To make this board available for circuitpython 8.2.x trying to backport it. 

thanks.

### CODE REVIEW

**Comment by dhalbert** [comment]
> I have added this board to main branch

I'm confused: is this related to #8188, which is for the `main` branch? That has a different author.

**Comment by tirtharajsinha** [comment]
> > I have added this board to main branch
> 
> I'm confused: is this related to #8188, which is for the `main` branch? That has a different author.

let me clear things up for you. 

pull request #8188 has not been merged.

but pull request for same board [#8352](https://github.com/adafruit/circuitpython/pull/8352) has been merged.

**Review by dhalbert — APPROVED** [review]
Thanks - somehow I did not find #8352. Approving and merging into 8.2.x.

**Comment by dhalbert** [comment]
@tirtharajsinha I was merging `8.2.x` into `main`. One thing I saw is that this backport has differences from the one you did for `main`. Most of the changes are clear, but you made the default RX and TX pins here be GPIO44 and GPIO43. I think you meant GPIO12 and GPIO11, because that's what's in `pins.c`. So in the merge, I changed it.

**Comment by tirtharajsinha** [comment]
thanks @dhalbert , may be I had missed that part. Thanks for noticing.

**Comment by tirtharajsinha** [comment]
One more thing, as you updated the files in ```main``` it's still unchanged in branch ```8.2.x```. Should I cherry-pick from `main` to `8.2.x`?

**Comment by dhalbert** [comment]
Good idea -- I forgot that the 8.2.x UART pins were wrong in 8.2.x.

**Pull request merged**
