### PR TITLE
fix espressif latest idf

### LINKED ISSUE #3516: Update ESP-IDF to official version
Despite the name, #3492 does not actually update to the master branch of the ESP-IDF - due to a compatibility issue in TinyUSB, we are now simply on a more up-to-date fork. Once TinyUSB is working with the most recent version of the Espressif IDF repo, we should switch to a stable release. This will allow faster integration of new features and newly enabled modules, which are still under active development for the ESP32-S2.

### PR DESCRIPTION
**Pull request by hathach**
[Not working yet]
I am trying to fix #3516 , I have  fixed the build issue with hal file got move around with latest IDF. However, I got an linking issue. @hierophect  Would you mind help me to fix this, then I will try to test out the usb patch.

```
xtensa-esp32s2-elf-gcc: error: esp-idf/components/xtensa/esp32s2/libhal.a: No such file or directory
xtensa-esp32s2-elf-gcc: error: esp-idf/components/xtensa/esp32s2/libhal.a: No such file or directory
make: *** [Makefile:319: build-espressif_saola_1_wrover/firmware.elf] Error 1
```

### CODE REVIEW

**Comment by hierophect** [comment]
@hathach please use git to revert commit https://github.com/adafruit/circuitpython/pull/3492/commits/e01e8dd6b9c886c091bdbe735f4a3f63a4fb6859. I already did all the porting work to move the file names over, and this commit is where I moved them all back in order to support the older IDF version that worked well with TinyUSB. If you revert that commit, it should bring up everything back to a compile-able state.

**Comment by hathach** [comment]
> @hathach please use git to revert commit [e01e8dd](https://github.com/adafruit/circuitpython/commit/e01e8dd6b9c886c091bdbe735f4a3f63a4fb6859). I already did all the porting work to move the file names over, and this commit is where I moved them all back in order to support the older IDF version that worked well with TinyUSB. If you revert that commit, it should bring up everything back to a compile-able state.

Ah thanks, I could get it build and fixed the usb configure with latest idf. And mark this PR as ready for review

**Review by hierophect — APPROVED** [review]
Looks good to me! Tested on a Saola and it seems to be working just fine. Glad that all that time I spent chasing down those headers wasn't wasted - thanks for looking into this so quickly!

**Comment by hathach** [comment]
I am glad that helps out.

**Pull request merged**
