### PR TITLE
Creat ar.po

### PR DESCRIPTION
**Pull request by mesa177**
Arabic translation, incomplete, needs further editing. Suggest testing before continuing translation

### CODE REVIEW

**Comment by tannewt** [comment]
Thank you! This is perfect for testing our pipeline to make sure everything works. I think the first step we need to do is turn off the terminalio output until we can do the rendering natively. 

Is there a reason you started with the German translation? I'd expect the untranslated messages to be empty and fall back to English.

**Comment by tannewt** [comment]
@mesa177 I removed a trailing \n the build didn't like to see what happens if it is correct. So, make sure to pull the latest version of the branch from GitHub if you have a local copy.

**Comment by mesa177** [comment]
@tannewt Hey Scott! It's Alaa from Lamba Labs.

So I used the German copy for 2 reasons: 1) was learning the lingo for a while before I stopped, so wanted to sink my teeth back into it. 2) saved me time adding necessary annotations. 2 birds, 1 stone.

Just make sure that what's being printed on screen characters wise and orientation wise matches the comments that I wrote in Arabic. If that's ok, then will proceed with the translation and pull a later version from my local copy.

PS: thanks for the edit!

**Comment by tannewt** [comment]
Based on my eye it looks like it is partially working in iTerm with screen on Mac OSX. (I don't expect it to work on built in displays yet.)

I believe the line in the traceback is correct but the `code.py : output` line needs the filename in the translated string itself and the Arabic portion is reversed.

Screen Shot 2020-02-25 at 3 44 42 PM

I think translating these two would be helpful: https://github.com/adafruit/circuitpython/pull/2652/files#diff-bb56709f94baf02d2b6842bf597a2d53R336 and https://github.com/adafruit/circuitpython/pull/2652/files#diff-bb56709f94baf02d2b6842bf597a2d53R1175

The best approach is probably to copy circuitpython.pot to ar.po in one PR and then do PRs onto that for translations.

Thank you so much! I'm excited to work through the issues and get it working.

**Comment by mesa177** [comment]
Good eye!

Yes indeed the Arabic portion is reversed. On the other hand, the nature of the written Arabic letters retain their proper forms (so the middle lam has the correct writing shape, the initial alef, and so forth...) Hope that makes sense :) 

On another note, I tried continue translating some other lines and hit a snag on one of them (line 141 to be exact, 0x%x apparently doesn't like having Arabic writing within the same sentence hehe). For now I recommend just commenting it until I figure out why.

Will look into the other 2 files and probably tackle those first if they impact this file's translation.

This is really exciting!!

**Comment by tannewt** [comment]
Thank you for the additional translations! Here is an updated view. I tried adding the filename into the output translation but it still messes up the direction of the Arabic portion.

Screen Shot 2020-02-26 at 10 55 19 AM

Do you know how the mixing of directions is supposed to work? Are there unicode characters to designate direction that we may be dropping? Maybe @joeycastillo knows.

**Comment by joeycastillo** [comment]
This might be an issue with iTerm's RTL support... displaying ar.po in the macOS terminal on the left and iTerm on the right, only iTerm seems to have the directionality issues: 

Screen Shot 2020-02-26 at 2 13 34 PM

**Comment by mesa177** [comment]
@joeycastillo is right, and it seems to be a common issue:

https://gitlab.com/gnachman/iterm2/issues/1611
https://gitlab.com/gnachman/iterm2/issues/2686

Someone on the forum started to do something about it about 5 months ago, but it seems they haven't gotten far with iTerm / iTerm2:

https://gist.github.com/XVilka/a0e49e1c65370ba11c17
https://gitlab.gnome.org/GNOME/vte/issues/53
https://gitlab.com/gnachman/iterm2/-/milestones/12

Not sure how to move forward...

**Comment by tannewt** [comment]
@joeycastillo Ah ha! Thanks for trying that!

@mesa177 I think it is fine to just tell folks to use Terminal instead of iTerm2. The CircuitPython serial looks correct in Terminal too.

Screen Shot 2020-02-26 at 4 32 59 PM

Would you like me to get an empty .po going and put all of the translations here into it?

**Comment by mesa177** [comment]
@tannewt  sure ok! Mind you, it looks like some of the translated sentences with English and Arabic content written together don't retain the right order of wording for some reaon. I think I will need to figure out a solution for that as well. I am stocked that we took a nice big leap in the right direction though, so yay!! 

Big thanks to @joeycastillo for helping us figure this out.

**Comment by mesa177** [comment]
@tannewt I opened a new file for the Arabic translation for us to test an alternate way of displaying messages so that the Arabic writing of words retains proper order in a sentence with English words. Whenever you can, please test it out and screenshot the result. I also added commented lines of the displayed message strings within the code so you can see how it's supposed to be displayed.

Hope this resolves things!

**Comment by tannewt** [comment]
> @tannewt sure ok! Mind you, it looks like some of the translated sentences with English and Arabic content written together don't retain the right order of wording for some reaon. I think I will need to figure out a solution for that as well. I am stoked that we took a nice big leap in the right direction though, so yay!!

Could you describe the issue? I don't trust my own computer to render your notes correctly. Here is a screenshot of VS Code, Sublime Text and the CircuitPython build in Terminal.

Screen Shot 2020-03-03 at 10 37 58 AM

Note that I had to fix the ver2 file because multi-line entries do not have "msgstr" after the first line.

**Comment by mesa177** [comment]
> > @tannewt sure ok! Mind you, it looks like some of the translated sentences with English and Arabic content written together don't retain the right order of wording for some reaon. I think I will need to figure out a solution for that as well. I am stoked that we took a nice big leap in the right direction though, so yay!!
> 
> Could you describe the issue? I don't trust my own computer to render your notes correctly. Here is a screenshot of VS Code, Sublime Text and the CircuitPython build in Terminal.
> 
> Screen Shot 2020-03-03 at 10 37 58 AM
> 
> Note that I had to fix the ver2 file because multi-line entries do not have "msgstr" after the first line.

The issue was the order in which the words in the sentence are written is jumbled. So even though the Arabic writing and English writing of the words are right, their placement order within the sentence was wrong. When I split the sentence over multiple lines (PS: sorry had to write msgstr for the remaining lines because when the content of the sentence is in Arabic, the writing disappears and I can no longer edit. My bad, should have removed them when I was done.)

Compare the CircuitPython build in Terminal on the second go with our first. You would notice the order of words is different even though the same words comprise the sentence. The first go had the order wrong. Buuuuuuuuuut the second gooooo..... has it right!! (well, almost, there was one tiny problem but it's very fixable). This means that my approach for splitting the content of the displayed error messages over multiple lines works great.

I will try to keep my unedited code with multi line entries on an offline version, and will modify the code when I copy the edits to GitHub.

Thanks for bearing with me @tannewt !

**Comment by tannewt** [comment]
I'm glad it's working! I'm happy to fix it up so no worries. I appreciate your help.

**Comment by mesa177** [comment]
I have not abandoned the project, but I have to hit the pause button until we resolve the issues pertaining the COVID19 DIY ventilator project here in Lebanon and on the Open Source COVID19 group.

Hope I can get back on track soon!

**Comment by tannewt** [comment]
No problem @mesa177. Take care of yourself and your community. I will close both of the PRs but the branches will still be available and we can create a new PR when ready. Thanks!

**Comment by jepler** [comment]
@mesa177 When you're ready to get started on this again let us know and we will set up an empty `ar.po` for Arabic translation on Weblate. https://hosted.weblate.org/projects/circuitpython/main/

**Pull request closed without merging**
