### PR TITLE
Add support for ThingPulse Pendrive S3

### PR DESCRIPTION
**Pull request by squix78**
This adds support for the ThingPulse Pendrive S3:
https://thingpulse.com/product/esp32-s3-pendrive-s3-128mb/

I couldn't find out how to add a reference to the CIRCUITPY drive. Is there a way I can define the default content of the drive?

### CODE REVIEW

**Comment by skieast** [comment]
First is to get your own VID/PID as per the instructions here https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/frequently-asked-questions
I believe you are currently using an Adafruit combo. 

There's probably more and I don't know the answer to your question for defining the initial content.  You can include frozen modules in the firmware by following instructions here: https://learn.adafruit.com/building-circuitpython/adding-frozen-modules

**Comment by tannewt** [comment]
> Is there a way I can define the default content of the drive?

Not really. It takes up space in the flash image so we try to keep it minimal.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please get your own USB VID/PID combination as folks commented on the commit about.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks for getting a PID.

**Comment by squix78** [comment]
Allow me one more question: how does the board get a listing here? https://circuitpython.org/downloads
I (wrongly?) assumed that adding it to this repository would do that...

**Comment by tannewt** [comment]
> Allow me one more question: how does the board get a listing here? https://circuitpython.org/downloads I (wrongly?) assumed that adding it to this repository would do that...

Nope, one more step: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Pull request merged**
