### PR TITLE
Remove Nrf52 bootloader target and hex

### PR DESCRIPTION
**Pull request by hathach**
<s>To prevent adding hex file each time we modify bootloader. Bootloader comes with pre-builtin hex for S140 6.1.0 and S132 6.1.0 for feather & pca10056.</s> Bootloader related targets and hex are removed, user need to clone the bootloader repo should they need to flash or upgrade board's bootloader. 

- SD version for S140 is upgraded to 6.1.0, since it is binary compatible with 6.0.0, I can still work. However bootloader 6.1.0 has some bug fix, it is better to flash the new one. 
- nrf52832 is left as it is, waiting for @arturo182
<s>- bootloader does also include nrfx and tinyusb, kind of duplication. But it is also standalone, have no idea to go around this.</s>

### CODE REVIEW

**Comment by tannewt** [comment]
I don't think we should add any knowledge of the bootloader to CircuitPython. It's only used to provide convenience targets in the Makefile to flash the bootloader. Those targets should be removed. The documentation and Makefile in it's [own repo](https://github.com/adafruit/Adafruit_nRF52_Bootloader) is enough.

**Comment by hathach** [comment]
@tannewt the bootloader target in the makefile is to flash the bootloader on the device with jlink, or you are referring to other targets. Could you say the target name specifically.

**Comment by hathach** [comment]
Hmm, probably it is a bit confusing, I will update the readme a bit.

**Comment by hathach** [comment]
update: the readme does mentions dfu-flash and dfu-flash already, @tannewt  would you mind to tell which lines of the makefile you want to remove.

**Comment by hathach** [comment]
@dhalbert @tannewt maybe we shouldn't add bootloader as submodule at all. A download script like SD's one should be enough ?

**Comment by dhalbert** [comment]
I think @tannewt is saying to not have anything about the bootloader in the `circuitpython` repo. If they are not already there, you can move the `Makefile` targets that load the bootloader to the https://github.com/adafruit/Adafruit_nRF52_Bootloader repo. If someone wants to load the bootloader they can follow instructions in the bootloader repo and/or use `Makefile` targets there.

We don't have targets that load the UF2 bootloader in the `atmel-samd/Makefile`, so they don't

**Comment by hathach** [comment]
@dhalbert ah that make sense, thanks. I understand what @tannewt  means now. Since `bootloader` target existed previously, I haven't done anything with it in this PR. I will remove  bootloader and dfu-bootloader target.

**Comment by hathach** [comment]
@dhalbert  maybe we should remove bootloader as the submodule as well, just tell people to clone the bootloader and flash it there in the readme.md

**Comment by hathach** [comment]
close this one by now, I need to do a few more things with bootloader repo and submit a separate PR.

**Pull request closed without merging**
