### PR TITLE
matrixportal: remove ulab to make room to freeze portalbase

### LINKED ISSUE #6461: Matrix Portal M4 Network object is getting heavier
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0 on 2022-05-23; Adafruit Matrix Portal M4 with samd51j19
Board ID:matrixportal_m4

adafruit-circuitpython-bundle-7.x-mpy-20220604
```

### Code/REPL

```python
import gc
import board
import rgbmatrix
import framebufferio
import displayio
from adafruit_display_text import bitmap_label
from adafruit_matrixportal.network import Network

print("starting mem", gc.mem_free())
bit_depth = 2
base_width = 64
base_height = 32
chain_across = 2
tile_down = 1
serpentine = True

width = base_width * chain_across
height = base_height * tile_down

addr_pins = [board.MTX_ADDRA, board.MTX_ADDRB, board.MTX_ADDRC, board.MTX_ADDRD]
rgb_pins = [
    board.MTX_R1,
    board.MTX_G1,
    board.MTX_B1,
    board.MTX_R2,
    board.MTX_G2,
    board.MTX_B2,
]
clock_pin = board.MTX_CLK
latch_pin = board.MTX_LAT
oe_pin = board.MTX_OE

displayio.release_displays()
matrix = rgbmatrix.RGBMatrix(
    width=width,
    height=height,
    bit_depth=bit_depth,
    rgb_pins=rgb_pins,
    addr_pins=addr_pins,
    clock_pin=clock_pin,
    latch_pin=latch_pin,
    output_enable_pin=oe_pin,
    tile=tile_down, serpentine=serpentine,
)
display = framebufferio.FramebufferDisplay(matrix)
print("mem after display", gc.mem_free())

group = displayio.Group()
print("mem after display group", gc.mem_free())

#update to font file on system your system
label = bitmap_label.Label(<font file>, anchor_point=(0, 0))
label.color = 0xFF0000
label.text = "hello world"
label.x = 10
label.y = 10
print("mem after label", gc.mem_free())

group.append(label)
print("mem after appending label", gc.mem_free())

display.show(group)
print("mem after display show", gc.mem_free())

network = Network(status_neopixel=board.NEOPIXEL)
print("mem after network creation", gc.mem_free())

response = network.fetch("http://example.com")
print("mem after response", gc.mem_free())
```

### Behavior

This code initializes a display and network object and prints out free memory after each action. When upgrading from CircuitPython 7.2.0 to CircuitPython 7.3.0 i noticed the free memory is reduced by 16,000 at the start of the application. If there is no network connection import, then the free memory is roughly the same. A loss of 16k worth of free memory is quite a bit and causing my board to run out of memory on more complicated applications

### Description

_No response_

### Additional information

Running 7.2.0 without importing network prints
starting mem 112272
mem after display 103824
mem after display group 103744
mem after label 102656
mem after appending label 102656
mem after display show 102656

Running 7.3.0 without importing network prints 
starting mem 112000
mem after display 103552
mem after display group 103472
mem after label 101200
mem after appending label 101200
mem after display show 101200

Running 7.2.0 with a network connection prints 
starting mem 71536
mem after display 63088
mem after display group 63008
mem after label 60816
mem after appending label 60816
mem after display show 60816
mem after network creation 59648
mem after response 58400

Running 7.3.0 with a network connection prints 
starting mem 55712
mem after display 47264
mem after display group 47184
mem after label 44528
mem after appending label 44528
mem after display show 44528
mem after network creation 43456
mem after response 42176

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #6461, creating more RAM space in MatrixPortal, by restoring `adafruit_portalbase` as a frozen library.

We've removed and then replaced BLE support in MatrixPortal once already:
- #6152
- #6154 

I think it was restored because the MatrixPortal Guide included the standard mirrored AirLift BLE page. However, I see no Learn Guide projects that use it. We can hide or remove that page in the Guide.

@caternuson (author of #6152) Do you know of any specific reason why we need BLE support in MatrixPortal? Note that the AirLift BLE support only supports acting as a BLE peripheral, not a central.

@makermelissa tagging you for interest and any comment you have.

### CODE REVIEW

**Comment by caternuson** [comment]
Looking at that issue I wrote - it looks like something I did proxy style for something someone brought up in the forums. But I didn't add a forum link unfortunately. It may have been nothing more than someone working through that one Learn page and hitting the import error.

If there's no current Learn project that uses BLE with MP, then I guess this can be a design choice for the CP devs. I think it'd be neat to leave it in if possible. Could make projects that use the Connect app to interact in some way, etc. - which would be peripheral mode. [Similar to this project.](https://learn.adafruit.com/circuit-python-tft-gizmo-candy-hearts/using-ble-connect-app)

But if there's a design choice to remove it, then definitely should hide that Learn page and anything else that indicates BLE is supported on the MP CP build.

**Comment by dhalbert** [comment]
@ladyada I discussed this with @caternuson on discord. He suggested there were more potential projects the would use BLE (see above for an example) than `ulab`. So I'm disabling `ulab` instead of BLE support for now. In the long run some of these libraries might get smaller.

**Comment by dhalbert** [comment]
@jepler Adding you as a reviewer. Current choice of disabling ulab is based on discussion at end of Monday's meeting.

**Review by caternuson — APPROVED** [review]

**Comment by CedarGroveStudios** [comment]
Is there an alternative method for using `ulab` on the matrix portal. The software-based RGB brightness control library I wrote (PaletteFader) depends on `ulab`.

**Comment by CedarGroveStudios** [comment]
Thanks. Good to know. I’ll stick with 7.3.2 and will place a note in PaletteFader to warn users. A note in CircuitPython.org would be helpful to bring attention to the one-off incompatibility. Is there a possibility of creating a ulab library instead?

**Comment by jepler** [comment]
This discussion reminds me of  https://learn.adafruit.com/ocean-epoxy-resin-lightbox-with-rgb-led-matrix-image-scroller/circuitpython-code -- it was coded before matrixportal, but does use ulab & rgbmatrix together.

**Comment by CedarGroveStudios** [comment]
> This discussion reminds me of ...

... and was the inspiration for the palette calculation portion of PaletteFader. Thank you @jepler and @ladyada!.

Also, ulab was fundamentally useful for the bilinear interpolation method in https://learn.adafruit.com/improved-amg8833-pygamer-thermal-camera.

**Pull request merged**
