### PR TITLE
Change ST drivers to use ST's driver repos as submodules

### PR DESCRIPTION
**Pull request by sgauche**
This will update the ST drivers to the latest from ST, as well as fix issue https://github.com/adafruit/circuitpython/issues/5968 .

I had to have the CMSIS_5 submodule point to tag 5.4.0, as I was getting the error in the below issue when trying to build CircuitPython with the latest CMSIS_5.

https://github.com/ARM-software/CMSIS_5/issues/1397

### CODE REVIEW

**Comment by tannewt** [comment]
Thank you! Do you want to wait for ST or should I fork and fix that build error? That's normally what we do if the source repo has a bug.

**Comment by sgauche** [comment]
@tannewt I'll leave that up to you.  If/when they eventually fix it, I'm guessing we can switch back to theirs?

**Comment by sgauche** [comment]
It is probably safe to fork and fix by just removing the unused variable, it looks like the f7 qspi driver has this fixed:
https://github.com/STMicroelectronics/stm32f7xx_hal_driver/blob/27458ea876aabd8fd568c5e2a8a3448f082e2817/Src/stm32f7xx_hal_qspi.c#L874

**Comment by tannewt** [comment]
> @tannewt I'll leave that up to you. If/when they eventually fix it, I'm guessing we can switch back to theirs?

Yup, that'd be the idea.

I'll make a fork and remove that line. Would you mind updating this PR after I do?

**Comment by tannewt** [comment]
Done in: https://github.com/adafruit/stm32f4xx_hal_driver/commit/abb4cd6a27ce4b95dd76d262a13d0e2c688b1f10

**Comment by sgauche** [comment]
STM32F4 HAL driver submodule changed to the fork in adafruit to fix the unused variable error until ST fixes it in their repo.

**Comment by jepler** [comment]
It's also possible to silence diagnostics strictly within source files and headers from a third party, meaning it may not be necessary to fork a repo just to make the ST code compile cleanly with our preferred CFLAGS.

To silence a warning inside a header controlled by a third party, modify the CFLAGS so that it is the "-isystem" flag that introduces the location where the header resides, rather than "-I" or "-iquote". For example, in the espressif port we have
```
espressif/Makefile:     -isystem esp-idf \
```

To silence a warning inside a source file controlled by a third party, modify CFLAGS for that file only.  For example, in the raspberrypi port we have
```
$(patsubst %.c,$(BUILD)/%.o,$(SRC_SDK)): CFLAGS += -Wno-missing-prototypes
```
where SRC_SDK is filled with the list of files from the pico sdk that we use.

**Comment by sgauche** [comment]
@jepler you're getting outside my comfort zone.  If you can tell me what to add to what file, I can switch back to using the ST submodule and add something to the Makefile to ignore unused variable warnings just for the qspi driver.

**Comment by sgauche** [comment]
I think the method that @tannewt suggested with the Adafruit fork is a little cleaner and easier to remember what to update when ST does fix their code.

**Review by tannewt — APPROVED** [review]
Thanks for the quick update!

@jepler Thanks for the tip. I didn't know we could do that for C files. Perhaps we need a separate file or section for fixes like that.

**Pull request merged**
