### PR TITLE
Add support for sunton_esp32_2432S024C board

### PR DESCRIPTION
**Pull request by gitcnd**
More info about these cool "Cheap Yellow Display" aka CYD boards here: https://www.aliexpress.com/item/1005005865107357.html

I've tested wifi, serial, the 3-color LED, display, display backlight - all good.

Has ambient light detection, speaker, SD card, buttons, ports, and what looks like power/battery related circuitry - still need checking.

There's 2 models of this - capacitive touch (the one I've got) and restive. touch still needs testing, and so does the "power off" of the screen etc for deep sleep

### CODE REVIEW

**Comment by lboue** [comment]
@gitcnd Is it still a draft?

**Comment by gitcnd** [comment]
@lboue I'm planning to build a display controller using this in the next week or so, at which point I'll check all those other features are working properly, pick all the correct naming, maybe write some examples to make it easy to get started, then do the submission.

If you need it now - what I've done so far is good enough to work from.  I can post the firmware build if you just want to try it out without the hassle of pulling this and building yourself.

**Comment by bablokb** [comment]
There is already a 2432S028C board, which is very similar.

Be aware of the battery charging chip: this is a chip targeted at power-banks. It will kill smaller LiPos, since it uses 1A for charging. Also, sleep-modes won't work because this chip will cut power if the current is too low. And since the USB-power is also routed via this chip, this not only affects battery, but also normal plugged operation.

Now I don't own this board, but I own two very similar boards so I just assume it is the same chip. You need good eyes to identify the chip, since it was not documented in the schematics.

**Comment by jepler** [comment]
@gitcnd can we help with anything holding this issue from being marked "ready for review"?

**Comment by gitcnd** [comment]
I've forgotten where I was upto on this.  Anyone wanting to take this over is welcome.  Be aware that there are at least 2 different boards with resistive touch-screens (and using different display drivers) and the capacitive version is also different, and many of these boards have assorted hardware "bugs" (like wrongly soldered leds and light sensors at least) and other subtle differences between them

**Comment by RetiredWizard** [comment]
I believe this has now been merged as #9918

**Comment by dhalbert** [comment]
Superceded by #9918.

**Pull request closed without merging**
