### PR TITLE
STM32: Core temperature and voltage

### LINKED ISSUE #2194: STM32: Incomplete implementation for microcontroller µs delay, get temperature
The Microcontroller module currently has several empty functions, which for one reason or other are unusually complicated to implement via the STM32 HAL. These functions should either be completed properly or filled with more appropriate placeholders.

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds the core temperature and core voltage measurements to the Microcontroller module. Resolves #2194.

Also includes some standardization of the `mphalport` files to match the other ports, though I admit that's just cargo-cult programming on my part. It's essentially a micropython compatibility layer, correct?

### CODE REVIEW

**Comment by hierophect** [comment]
Hmmm. There's a translations failure in the CI, doesn't look like it's anything to do with my additions.

**Comment by hierophect** [comment]
@tannewt I've got no idea what this translate error is, any thoughts? I've rerun the test and it's the same error.

**Comment by tannewt** [comment]
@hierophect you added two new error messages. When you add anything in `translate()` then you also need to run `make translate` at the top level. It'll then put the new strings in the translation files so that translators have access to it there.

**Comment by hierophect** [comment]
> @hierophect you added two new error messages. When you add anything in `translate()` then you also need to run `make translate` at the top level. It'll then put the new strings in the translation files so that translators have access to it there.

Huh. Did it just never come up before because I was using words that had already been translated, or something?

**Comment by dhalbert** [comment]
There is a target in the top-level `Makefile`, `make check-translate`, which will tell you whether you need to `make translate`.

**Comment by hierophect** [comment]
@tannewt ping; ready for review/merge.

**Comment by tannewt** [comment]
Is the voltage the reference voltage for the ADC or the core voltage? @dhalbert, it should be adc reference voltage right?

**Comment by dhalbert** [comment]
> Is the voltage the reference voltage for the ADC or the core voltage? @dhalbert, it should be adc reference voltage right?

The voltage reading is the "input voltage to the microcontroller", not the regulated core voltage. The idea is to be able to detect sagging input voltage before we hit the brownout limit. So that voltage (wherever it comes from) needs to be compared against a stable internal reference (bandgap-based, probably).

**Comment by hierophect** [comment]
@dhalbert @tannewt the voltage that I'm measuring is the analog reference voltage, compared to the STM32's internal stable reference voltage. The calculation VREFINT/VREFIN_CAL (calibrated value) creates a fraction that can be used to correct for the difference between the actual Analog reference and the ideal (micropython does this). I was wondering if you'd like me to actually use this fraction in the ADC module.

**Comment by hierophect** [comment]
(for the record, the value returned by my current implementation is usually 3.28 when plugged into USB)

**Comment by dhalbert** [comment]
For `Processor.voltage`, we want to measure the VDD coming into the chip. There is an available channel, VDDA, which is the VDDA pin. On the Feather '405, the VDD and VDDA pins are connected to the 3.3V supply from the off-chip regulator.

In the nrf implementation, we read a similar voltage, scale it by 1/6, and compare it to the internal bandgap ref.

In the atmel-samd implementation, there is a scaled version of VDD which we also compare with an internal reference (there are multiple internal reference channels available). There's a complication for SAMD51 because the SAMD51 ADC is buggy in various ways, and I couldn't get the simplest way  to work. The SAMD21 is more straightforward.

So we are not trying to measure the internal ref; we are using the internal ref to measure against an external voltage which is hopefully around 3.3V but might sag below that as a battery gets low. If there's a calibration value that can fine-tune the internal reference, great, but it's not vital. The most important thing is not to assume that VDDA is known.

This might be different from the usual measurements you want to make with the ADC for a typical analog input.

**Comment by hierophect** [comment]
@dhalbert that's what I mean. To be more clear, here's the actual calculation I do (same as micropython). Pseudocode:

```
value = HAL_ADC_GetValue(Handle_ADC_CHANNEL_VREFINT)
adc_fraction = ((float)(*VREFIN_CALIBRATION_VALUE)) / ((float)value);
return adc_refcor * 3.3f;
```

The actual value provided by that analog read is the VDDA voltage divided by the internal reference voltage which is like 1.25 or something. The VREFIN_CALIBRATION_VALUE is a factory-determined value for this ADC read done in the factory for exactly 3.3V, which is stored in read only memory. 

What I'm suggesting is that this `adc_fraction` variable could be used to bias ADC values in the actual AnalogInOut module to make them more accurate, if we felt like it. 

All that said, I don't understand why micropython puts the actual value in the denominator, that doesn't make sense? I only just noticed that now on reviewing, it should be Vreal/Vcalib to get the actual fraction to multiply outputs by, unless there's some wonky inversion thing going on?

**Comment by hierophect** [comment]
Oh, I get it now. VREFINT readings go up as VDDA goes down, since it's the stable internal reference voltage compared to the external voltage. So VREF_CAL/VREF is the correct ratio. 

@tannewt @dhalbert translation fix is in so this should be good to go, regardless of whether we want to add correction to the ADC in the future.

**Pull request merged**
