### PR TITLE
Vm size optimizations: Get back 1500 bytes for 3.2% VM speed decrease

### PR DESCRIPTION
**Pull request by jepler**
I found two size optimizations in the main "virtual machine" implementing function, mp_execute_bytecode. It causes a modest speed decrease, so it's only turned on for samd21 builds.

There were two optimizations:
 * First, (thanks to @dhalbert for a related idea about "pointer compression") a table called `entry_table` was reduced from being a 4-byte type to being a 2-byte type; however, a small amount of arithmetic was added to each `DISPATCH()`, making the size savings about half of what I'd hoped for
 * Second, realizing that the code in the DISPATCH macro itself is a significant part of the overall code size of `mp_execute_bytecode`, consolidate all of them into a single `ONE_TRUE_DISPATCH()`, which the others reach by `goto`. This saves much more space, at the expense of one additional jump for every bytecode encountered.

Sizes and timings from a Feather M0 Adalogger and the English language build.

<table>
<tr><th>Version <th>Free Flash <th>Increase <th>Benchmark Time <th>Increase
<tr><th> Original <td> 2100 bytes <td> <td> .655s <td>
<tr><th> Compress Table <td> 2332 bytes <td> +232 <td> .666s <td> +1.7%
<tr><th> One True Dispatch <td> 3600 bytes <td> +1268/+1500 <td> .676s <td> +1.7%/+3.2%
</table>

Simple timing program:

```python
import time
t0 = time.monotonic()
s = 0
for i in range(10000):
    s += i
t1 = time.monotonic()
print (t1-t0, s)
```

### CODE REVIEW

**Comment by dhalbert** [comment]
This is great!!!

**Comment by jepler** [comment]
CI failures _seemed_ to be network-related.

**Comment by ladyada** [comment]
i kicked it :)

**Comment by ladyada** [comment]
i kicked it :)

**Review by dhalbert — APPROVED** [review]
Thanks very much for this! In the long run I have been thinking about labeling builds as "192kB", "256kB", etc., rather than "FULL_BUILD", etc. to give a little more information. But the SAMD21 distinction works well for the current mix of boards.

**Comment by tannewt** [comment]
Nice work! cc @dpgeorge

**Comment by dpgeorge** [comment]
Interesting!

Did you try compiling with MICROPY_OPT_COMPUTED_GOTO disabled, ie using a big switch in the VM?  I just tried this patch out here and it seems that a big switch is still smaller than what is here.

Using minimal port, cross compiled to Cortex-M4 with -Os:
```
build options                                       fw size     diff to baseline
baseline MICROPY_OPT_COMPUTED_GOTO=0                67224       +0  
MICROPY_OPT_COMPUTED_GOTO=1                         69008       +1784   
MICROPY_OPT_COMPUTED_GOTO=1 w/ compressed table:    68516       +1292   
MICROPY_OPT_COMPUTED_GOTO=1 w/ one-true-dispatch:   67844       +620    
MICROPY_OPT_COMPUTED_GOTO=1 w/ both above:          67336       +112

```

**Comment by dhalbert** [comment]
We have not disabled `MICROPY_OPT_COMPUTED_GOTO` because turning it on produced a 5x (!) gain in speed: https://github.com/adafruit/circuitpython/pull/1934

**Comment by dhalbert** [comment]
We did not run a benchmark suite but instead a simple loop test: https://github.com/adafruit/circuitpython/issues/1933#issuecomment-500881999

**Pull request merged**
