### PR TITLE
update tinyusb to fix disconnect/suspend issue with #1681

### PR DESCRIPTION
**Pull request by dhalbert**
Also check for disconnect while writing a string, in case a disconnect happens during writing.

### CODE REVIEW

**Comment by dhalbert** [comment]
Fixes #1681.

**Comment by dhalbert** [comment]
Changing from draft to ready for review didn't trigger a build :(

**Comment by dhalbert** [comment]
Was able to trigger a build by closing and reopening.

**Comment by hathach** [comment]
@dhalbert you should also merge this PR for usb descriptor https://github.com/adafruit/usb_descriptor/pull/7

 and bump it up in this pr as well

**Comment by dhalbert** [comment]
> @dhalbert you should also merge this PR for usb descriptor [adafruit/usb_descriptor#7](https://github.com/adafruit/usb_descriptor/pull/7)
> 
> and bump it up in this pr as well

Done! I didn't see that.

**Comment by dhalbert** [comment]
@tannewt or @hathach This is ready for approval and merging (finally).

**Pull request merged**
