### PR TITLE
INVERT the sense of the I2C_POWER pin (active low)

### PR DESCRIPTION
**Pull request by anecdata**
I don't have the board to test, but this was reported and discussed on Discord. Probably only relevant for the BME280 version of the board.

### CODE REVIEW

**Comment by jerryneedell** [comment]
From the schematic, VSENSOR also goes out to the STEMMA connector - so this may also impact the non BME280 version

**Comment by jerryneedell** [comment]
Unfortunately,  today, I have been unable to get it to fail regardless of whether the I2C_POWER pin  is set to True or False...

**Comment by jerryneedell** [comment]
this is the code I am using to test -- I just change the ip.value from False to True but today , it does not seem to care.

```
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

import time
import board
from adafruit_bme280 import basic as adafruit_bme280
import digitalio

ip = digitalio.DigitalInOut(board.I2C_POWER)
ip.switch_to_output()
ip.value = False
# Create sensor object, using the board's default I2C bus.
i2c = board.I2C()  # uses board.SCL and board.SDA
bme280 = adafruit_bme280.Adafruit_BME280_I2C(i2c)

# OR create sensor object, using the board's default SPI bus.
# spi = board.SPI()
# bme_cs = digitalio.DigitalInOut(board.D10)
# bme280 = adafruit_bme280.Adafruit_BME280_SPI(spi, bme_cs)

# change this to match the location's pressure (hPa) at sea level
bme280.sea_level_pressure = 1013.25

while True:
    print("\nTemperature: %0.1f C" % bme280.temperature)
    print("Humidity: %0.1f %%" % bme280.relative_humidity)
    print("Pressure: %0.1f hPa" % bme280.pressure)
    print("Altitude = %0.2f meters" % bme280.altitude)
    time.sleep(2)
```

**Comment by anecdata** [comment]
@jerryneedell Do you have a Rev.A board?

**Comment by jerryneedell** [comment]
How can I tel if it is Rev A?

**Comment by anecdata** [comment]
On the silk, in theory

**Comment by jerryneedell** [comment]
I don't see any indication.

**Comment by anecdata** [comment]
huh, maybe only gets the silk treatment when it changes to Rev.B

**Comment by jerryneedell** [comment]
The schematic I saw is Rev B -- what changed from Rev A?

**Comment by ladyada** [comment]
rev A did not have power control

**Comment by jerryneedell** [comment]
How can I tell Rev A from Rev B board?

**Comment by jerryneedell** [comment]
I am looking at the V+ pin on the STEMMA connector with a scope. If I set I2C_POWER to False, it stays steady at 3.3V.
If I set it to True, then the voltage drops just below 3V and when the BME280 sensor is accessed, it drops briefly  (10ms) to <1.5 V.  Does this sound like Rev A or Rev B?

**Comment by jerryneedell** [comment]
I2C_POWER = True
DS1Z_QuickPrint6

I2C_POWER=False
DS1Z_QuickPrint7

**Comment by ladyada** [comment]
you're probably seeing parasitic power thru the I2C pins. you *definteitely* need to pull the power pin low to access i2c

**Comment by jerryneedell** [comment]
@ladyada should I assume I have a rev b board.?

**Comment by ladyada** [comment]
if you're not me or i think scott, you have only a rev B board. we never shipped rev A thru the shop :)

**Review by dhalbert — APPROVED** [review]
Thanks, this is good!

**Pull request merged**
