### PR TITLE
Minor fixes to bug report template

### PR DESCRIPTION
**Pull request by tekktrik**
Minor fixes I noticed in the bug report template while creating one for the libraries.

### CODE REVIEW

**Review by jepler — DISMISSED** [review]
looks fine, thanks!

**Review by MicroDev1 — CHANGES_REQUESTED** [review]
I would keep the python rendering as is. It prettifies the text. What is the issue you encountered?

**Comment by tekktrik** [comment]
I just saw that the syntax wasn't actually Python and was highlighting "random" parts so I just removed it, but there weren't any actual issues really.

**Comment by tekktrik** [comment]
I'm definitely not the main consumer of the bug reports, so happy to do whatever is best for those that do.

**Comment by MicroDev1** [comment]
@tekktrik This should be good to merge with the two python changes backed out.

**Review by MicroDev1 — APPROVED** [review]
LGTM! Thanks @tekktrik.

**Pull request merged**
