### PR TITLE
bitmaptools: add alphablend

### PR DESCRIPTION
**Pull request by jepler**
This blends two "565"-format bitmaps, including byteswapped ones. All the bitmaps have to have the same memory format.

The routine takes about 63ms on a Kaluga when operating on 320x240 bitmaps. Of course, displaying the bitmap also takes time.

There's untested code for the L8 (8-bit greyscale) case. This can be enabled once gifio is merged.

The demo below is real-time.  It's using directio (`display_bus.send(44, bitmap)`) to send bitmap data to avoid displayio overhead.

https://user-images.githubusercontent.com/1517291/140423321-b1ee8963-f2d5-44b2-a865-d01fbebed821.mp4

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Looks good to me. Just needs to be updated.

**Comment by jepler** [comment]
It doesn't fit on pybadge or pygamer.

**Comment by jepler** [comment]
The PR has been updated to include "L8" (greyscale) blending, & several boards that are unlikely to need it have had framebufferio disabled in order for this to fit.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
