### PR TITLE
Use GCC @file to shorten linker command length

### PR DESCRIPTION
**Pull request by tannewt**
This hopefully fixes linking on Windows with cmd.exe

### CODE REVIEW

**Comment by ladyada** [comment]
```
$ make BOARD=adafruit_feather_rp2040 -j 32
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Traceback (most recent call last):
  File "gen_stage2.py", line 82, in <module>
    typer.run(main)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/typer/main.py", line 859, in run
    app()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "gen_stage2.py", line 14, in main
    flashes = cascadetoml.filter_toml(pathlib.Path("../../data/nvm.toml"), skus)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/cascadetoml.py", line 159, in filter_toml
    raise ValueError("Missing root .cascade.toml")
ValueError: Missing root .cascade.toml
make: *** [Makefile:271: build-adafruit_feather_rp2040/stage2.c] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by tannewt** [comment]
What is your current path? I was hoping pathlib would handle the path stuff for windows.

**Review by ladyada — APPROVED** [review]
yay now builds!

**Comment by tannewt** [comment]
(The build issue was that `data/nvm.toml` was empty and needed a `git submodule update --init`.)

**Pull request merged**
