### PR TITLE
Enable built-ins compile for all boards

### PR DESCRIPTION
**Pull request by bill88t**
This enables builtins.compile() for all espressif boards.

~~This is currently in draft as I want to run more tests and see how it affects storage space.~~

I have already implemented some basic compilation support within ljinux which heavily relies on `exec` and the results are pretty impressive.
However since I still haven't made a benchmark, I have no numbers to present.
I suggest as you try for yourselves.

I want to enable this on more and more ports, but I plan on doing it in different PRs, one step at a time.
If we end up enabling it on everything, then we can just revert the per-port PRs and enable it globally.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
Still on the ESP32-S3, I decided to try timing a program:

Running with exec(compile())
```
(8155376)/>bench 
time
The current time is: 13:01:20
turtle
Turtle time! Lets draw a rainbow benzene
Press Enter to continue... 
time
The current time is: 13:01:53
```

Running with just exec()
```
(8160288)/>bench 
time
The current time is: 00:01:33
turtle
Turtle time! Lets draw a rainbow benzene
Press Enter to continue... 
time
The current time is: 00:01:41
```

The turtle program ran much faster without the compile modification, however if I execute `exec(compile('import turtle','','exec'))` it matches the faster speed of 8 seconds.

**Comment by bill88t** [comment]
First of all, applications like ljinux are python scripts for the most part, not shell scripts.
So the kernel does not get back control at all while the app runs.
And for long running apps that have plenty of loops and/or user interactions, like nano for example, where we open it once and spend minutes inside, not having to re-interpret anything is pretty massive.
In the backround the code is just looping over and over. If the loops are in ASM already, it's instant.

Let's spice up the code example and run it on C3.

```
import time

n = 1000

def timeit(title, f):
    t0 = time.time()
    for _ in range(n): f()
    t1 = time.time()
    dt = t1 - t0
    print(f"{title:<20}: {dt:8.3f}")
    
codestr = """
for i in range(1000):
    a = sum(range(100)) ^ i
    b = int(a / 3)
"""

timeit("compile", lambda: compile(codestr, "", "exec"))
timeit("code", lambda: exec(code))
timeit("exec", lambda: exec(codestr))
```

C3 Results:
```
compile             :    3.000
code                :    0.000
exec                :  149.000
```

This is because of the interpreter.
Having repetitive logic in bytecode, even if we use it only a few times really makes a difference.

**Comment by RetiredWizard** [comment]
After some Discord discussions will @bill88t I was really confused by my earlier benchmark results and re-tested. Upon re-testing the compile option ran in 8 seconds rather than the 33 seconds I got earlier.

I was using web workflow to move some files back and forth and was seeing issues with the web workflow apparently locking up the serial REPL and possibly crashing the WiFi interface. I haven't been able to isolate for a reproducible issue yet but I suspect it was WiFi issues that slowed down the earlier Compile test.

**Comment by bill88t** [comment]
Briefly tested on nrf and rp2. I can't test the others, since I don't have any.

**Comment by RetiredWizard** [comment]
I ran a couple quick tests on the SAMD51 and mimxrt10xx. I didn't do run any benchmarks and didn't notice any speed differences but the build seemed to work fine.

**Pull request merged**
