### PR TITLE
Pico W wifi code improvements.

### PR DESCRIPTION
**Pull request by bill88t**
- AP can now be started / stopped seperately from STA.
- AP and STA can work at the same time.
- AP can now be made OPEN (no password).

Known issues:
- If the AP is started and then stopped it cannot be started back up again.
  It does start, but CP has no idea it's up (CYW43_LINK_DOWN & no IPs).
  Mitigation: Add check in `start_ap` and a proper error message.

### CODE REVIEW

**Comment by anecdata** [comment]
Can you adjust the shared-bindings docs to match? authored I think would be the main one.

**Comment by bill88t** [comment]
Sure, but I don't see anything in need of updating.

The docs incorrectly stated that picow could do OPEN already.
But that now is correct.

However there is no notes regarding the AP not working.
Adding one.

**Review by tannewt — COMMENTED** [review]
Does this require a specific version of the pico sdk and/or the CYW firmware?

**Comment by bill88t** [comment]
Last I tried stuff were far more broken.
For example, you needed to stop both STA and AP to stop STA.
That is no longer the case.
I just retried everything now that [picosdk was updated](https://github.com/adafruit/circuitpython/pull/8091).
I have never touched the cyw firmware, nor do I know how.

**Review by tannewt — APPROVED** [review]
Sounds good. Thanks!

**Pull request merged**
