### PR TITLE
Change sys.version to return the whole port identification.

### LINKED ISSUE #8802: sys.version reports as micropython
### CircuitPython version

```python
Main branch
```

### Code/REPL

```python
import sys
print(sys.version)
```

### Behavior

It reports back `3.4.0; MicroPython 9.0.0-alpha.6-17-g2c453390ec on 2024-01-09`.
Should this really be left to be reported as MicroPython?

Shouldn't it be something like:
`3.4.0; CircuitPython 9.0.0-alpha.6-17-g2c453390ec on 2024-01-09; M5Stack Timer Camera X with ESP32`?
to match the repl prompt somewhat?

If this is intentional feel free to immediately close this issue.
Otherwise I can go and fix it.

### PR DESCRIPTION
**Pull request by bill88t**
```
>>> sys.version
'3.4.0; Adafruit CircuitPython 9.0.0-alpha.6-25-g6bdf06c9e5-dirty on 2024-01-17; M5Stack Timer Camera X with ESP32'
```
Same string as `pyexec_friendly_repl`. This is also a great way to get the board info during runtime all at once!

Fixes #8802

### CODE REVIEW

**Comment by dhalbert** [comment]
Don't remove the `const`. Let's figure out what's going on first. Do a local pre-commit check or compile.

**Comment by bill88t** [comment]
I put it back. It's just that locally it builds and runs fine.
I can't repro the CI failure.

**Comment by dhalbert** [comment]
I'll look at it in more detail a little later, since this is not urgent.

**Comment by bill88t** [comment]
Same here. I will try building in a container tomorrow.

**Comment by jepler** [comment]
Try with:
```diff
diff --git a/py/makeversionhdr.py b/py/makeversionhdr.py
index 430b9bef4b..edcb994b4f 100644
--- a/py/makeversionhdr.py
+++ b/py/makeversionhdr.py
@@ -119,7 +119,7 @@ def make_version_header(repo_path, filename):
 #define MICROPY_VERSION_STRING "%s"
 // Combined version as a 32-bit number for convenience
 #define MICROPY_VERSION (MICROPY_VERSION_MAJOR << 16 | MICROPY_VERSION_MINOR << 8 | MICROPY_VERSION_MICRO)
-#define MICROPY_FULL_VERSION_INFO "Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME
+#define MICROPY_FULL_VERSION_INFO "Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_BANNER_MACHINE
 """ % (
         git_tag,
         git_hash,
```

On the "unix port", MICROPY_HW_BOARD_NAME and MICROPY_HW_MCU_NAME are not defined. mpconfig picks one of two forms of BANNER depending on definedness so it should give what you want:

```c
// String used for the second part of the banner, and sys.implementation._machine
#ifndef MICROPY_BANNER_MACHINE
#ifdef MICROPY_HW_BOARD_NAME
#define MICROPY_BANNER_MACHINE MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME
#else
#define MICROPY_BANNER_MACHINE MICROPY_PY_SYS_PLATFORM " [" MICROPY_PLATFORM_COMPILER "] version"
#endif

```

**Comment by jepler** [comment]
I went ahead and added that change to this PR

**Review by jepler — DISMISSED** [review]
Good to go if the build is green

**Comment by tannewt** [comment]
@jepler Looks like the REPL tests were broken.

**Comment by bill88t** [comment]
Oh whoops, sorry for the late response, I'm having exams currently, so I'm not very active.
Thanks Jepler for the fix.

```
Adafruit CircuitPython 9.0.0-alpha.6-32-gc7701709ef on 2024-02-16; DFRobot FireBeetle 2 ESP32-S3 with ESP32S3
>>> import sys
>>> sys.implementation
(name='circuitpython', version=(9, 0, 0), _machine='DFRobot FireBeetle 2 ESP32-S3 with ESP32S3', _mpy=262)
>>> sys.version
'3.4.0; Adafruit CircuitPython 9.0.0-alpha.6-32-gc7701709ef on 2024-02-16; DFRobot FireBeetle 2 ESP32-S3 with ESP32S3'
```

Works as intended. I will try to take a look at the tests.

**Review by jepler — COMMENTED** [review]
In a video chat, Dan reiterated his concern about the growth of flash due to including the long "MICROPY_FULL_VERSION_INFO" so we might just make the smaller change in mpconfig.h and leave the rest aside for now.

**Comment by bill88t** [comment]
> growth of flash due to including the long "MICROPY_FULL_VERSION_INFO"

Even though that string already exists in flash?
Well if that's the case I will just go and change it back.

**Comment by dhalbert** [comment]
> Even though that string already exists in flash?

`MICROPY_FULL_VERSION` is there, but the compile-time concatenated `"3.4.0; " MICROPY_FULL_VERSION` is not. So it's a new string. The board name is available from a couple of other sources, so I'd like to leave it out for now.

**Review by dhalbert — APPROVED** [review]
Thanks for persevering on this as I changed my mind, and thanks for fixing the tests.

**Pull request merged**
