### PR TITLE
mimxrt1011: pwmio: Enable basic PWMOut functionality

### PR DESCRIPTION
**Pull request by jepler**
After this change, the following program works for me on the MIMXRT1010-EVK:
```python
import pwmio
import board

p = pwmio.PWMOut(board.D13, frequency=1_000_000, variable_frequency=True)
p.duty_cycle = 32868

while True:
    pass
```

Querying and varying the duty_cycle and frequency work as well.

The lowest frequency obtainable is about 2kHz; there is an additional divider which would allow lower PWM frequencies (I think 1kHz is important for servos?)

In the commit message I wrote that something odd happens with low duty cycles, but it's just the length of the very smallest pulses being shorter than the sample time of my logic analyzer, not a real problem.

### CODE REVIEW

**Comment by ladyada** [comment]
50 or 60 hz needed for servos

**Comment by jepler** [comment]
Also, the pwm "X" channel is probably not working.

**Review by tannewt — DISMISSED** [review]
Code looks good but you'll need to fix the CI.

**Comment by jepler** [comment]
@ladyada this is ready-ish for testing. I have not added:
 * never-reset PWMs (like for backlight)
 * correct checking for PWM sharing
 * support for "X-channel" PWM, if possible (no code in SDK for it) - this affects only pin A2 (and ESP_READY) on the metro m7 1011
 * ... more that I forgot

However, frequencies down to 15Hz and duty cycles from 0..65535 work for me.

**Review by ladyada — DISMISSED** [review]
tested on metro m7 with a range of frequencies!

**Comment by jepler** [comment]
@tannewt can I have a re-review & merge now that it's green?

**Review by ladyada — APPROVED** [review]

**Comment by arturo182** [comment]
Glad to see imxrt port getting some love <3

**Pull request merged**
