### PR TITLE
Add Espress ld flags to more closely match CMake builds

### PR DESCRIPTION
**Pull request by dhalbert**
#7280 added a single `-u ...` value to Espressif links to force the correct routine to be linked in,  instead of a WEAK version.

I looked over the output of ninja.build and found several more things that potentially should be added to the links. I've added this in the Espressif `Makefile`. I tested with the usual "Internet test" that's in the Learn Guides on an ESP32-S2 and S3, and it works. One of the added `-u` symbols is relevant to I2C, so I also tried ESp-32S3 I2C with a problematic clock-stretching device and sadly it does not fix things.

I am not sure whether these changes are worth it, but they do make the build "more correct" vis-a-vis the CMake builds. Making this a draft since we might not want to merge.

The `FIRST` and `LAST` flag groups were chosen to imitate what the current link is doing. The wrapping functions also have to be positioned early or the link fails.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
I'm ok adding this.

**Review by jepler — APPROVED** [review]
Makes sense. I removed the duplicate. However, let's merge this for 9 instead of 8.1; I'll set a milestone.

**Comment by dhalbert** [comment]
This should be delayed until ESP-IDF v5 update, and reviewed and redone then.

**Comment by tannewt** [comment]
I'm going to close this since it will be redone with the switch to IDF 5 #6913

**Pull request closed without merging**
