### PR TITLE
Adafruit TRRS Trinkey M0

### PR DESCRIPTION
**Pull request by dhalbert**
EDIT: This is outdated now. See below.

Pins:
```
>>> dir(board)
['__name__', 'NEOPIXEL', 'RING_1', 'RING_1_SWITCH', 'RING_2', 'SLEEVE', 'TIP', 'TIP_SWITCH', 'board_id']
```
Modules:
```
__future__        adafruit_hid/mouse                  math              storage
__main__          analogio          microcontroller   struct
adafruit_hid/__init__               array             micropython       supervisor
adafruit_hid/consumer_control       board             neopixel          sys
adafruit_hid/consumer_control_code  builtins          neopixel_write    time
adafruit_hid/keyboard               collections       nvm               touchio
adafruit_hid/keyboard_layout_base   digitalio         os                usb_cdc
adafruit_hid/keyboard_layout_us     gc                random            usb_hid
adafruit_hid/keycode                keypad            rotaryio          usb_midi

```
- `adafruit_hid` and `adafruit_neopixel` are frozen in. 
- ~~`busio` _is not_ included~~
-  ~~`rotaryio` (for a possible external rotary encoder) _is_ included~~
- `touchio` _is_ included
-  `analogio` _is_ included, in case external potentiometer is desired
- `keypad` _is_ included, which is unusual for such a small board

~~480 bytes left over on `ja` translation, which is largest at the moment. If we had to drop something, maybe `rotaryio`.~~

Jack schematic:
image

### CODE REVIEW

**Comment by ladyada** [comment]
id remove rotaryio, i dont think we need it, and add busio instead

**Comment by ladyada** [comment]
tested

```
import time
import board
import keypad
import digitalio
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keyboard_layout_us import KeyboardLayoutUS
from adafruit_hid.keycode import Keycode
import neopixel

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1, brightness=0.4)

sleeve = digitalio.DigitalInOut(board.SLEEVE)
sleeve.switch_to_output(False)
ring = digitalio.DigitalInOut(board.RING_1)
ring.switch_to_output(False)

keys = keypad.Keys((board.TIP, board.RING_2), value_when_pressed=False, pull=True)

time.sleep(1)  # Sleep for a bit to avoid a race condition on some systems
keyboard = Keyboard(usb_hid.devices)
keyboard_layout = KeyboardLayoutUS(keyboard)  # We're in the US :)

while True:
    event = keys.events.get()
    if event:
        print(event)
        if event.pressed:
            if event.key_number == 0:
                keyboard_layout.write("Hello")
                pixel[0] = [0, 255, 0]
            if event.key_number == 1:
                keyboard.press(Keycode.SHIFT, Keycode.A)
                keyboard.release_all()
                pixel[0] = [0, 0, 255]
            time.sleep(0.1)
            pixel[0] = 0
```

**Comment by ATMakersBill** [comment]
I agree. If we need a rotary knob we can use the stemma board, make a
custom build or use Arduino

Bill Binko
***@***.***

"Helping Makers Help Others"
Join us at http://atmakers.org

**Comment by dhalbert** [comment]
@ATMakersBill @ladyada 
I added `busio.I2C` and appropriate `board.` names for the STEMMA/QT connector.

These choices are currently made:
- `keypad`
    - simple `Keys` is on.
    - Matrices are off.
    - `ShiftRegisterKeys` is on. @ATMakersBill: `ShiftRegisterKeys` is for things like SNES controllers that use a shift register to handle many buttons. Is this a potential use case for you?
- `rotaryio` is OFF
- `touchio` is ON
  - @ladyada is touch practical with a TRRS jack?
  - @ATMakersBill If it works electrically, I'd think this is a common use case for you, right?
- `adafruit_hid` is frozen in. This is very common and will save a lot RAM for other purposes.
- `neopixel` is NOT frozen in. I could trade it off for `ShiftRegisterKeys` or `touchio`. It's <2kB RAM if not frozen in, but a little less convenient if you want to use the on-board NeoPixel for signaling. Any thoughts on this?

**Comment by ATMakersBill** [comment]
I agree on the many buttons: Chris uses “chording” to increase his
effective buttons and we’d use this.

I think touch might work if we used only one pin (tip probably) and left
the rest floating?  I doubt a trrs cable could carry multiple touch signals
(right?). If it does work it would be very helpful. Also, using the “ring”
tab on top of the jack as a touch signal to change modes (with no plug in
jack) might be handy.

On neopixel can we leave it unfrozen (to keep touchio if it works) but
include it on the standard image?  That would let us delete it to save
memory if we didn’t need it but have it by default?


Bill Binko
***@***.***

"Helping Makers Help Others"
Join us at http://atmakers.org

**Comment by ATMakersBill** [comment]
One more thought. We have HID mouse and keyboard… can we add gamepad or
does it have a C component?  Also we’d want to use the custom HID profile
to enable only one gamepad (without mouse and keyboard) so it can work on
XAC

Bill Binko
***@***.***

"Helping Makers Help Others"
Join us at http://atmakers.org

**Comment by dhalbert** [comment]
> I agree on the many buttons: Chris uses “chording” to increase his effective buttons and we’d use this.

Does Chris use a shift-register in some controller? There are older controllers that do this but I don't know if it is common any more with any kind of AT or game controller.

> I think touch might work if we used only one pin (tip probably) and left the rest floating? I doubt a trrs cable could carry multiple touch signals (right?). If it does work it would be very helpful. Also, using the “ring” tab on top of the jack as a touch signal to change modes (with no plug in jack) might be handy.

Touch is on now. If it doesn't work after testing we could turn it off.

> On neopixel can we leave it unfrozen (to keep touchio if it works) but include it on the standard image? That would let us delete it to save memory if we didn’t need it but have it by default?

There is no way right now to include an unfrozen library in `lib/`, and there is no way to "unfreeze" a library, because it's part of the firmware in the UF2. So whatever libraries one needed would just get copied after the UF2 was set up. I don't see that as a big deal because the code.py and whatever else needs to be copied over anyway. I see freezing HID more as saving significant RAM, not as a matter of convenience. A frozen library takes little RAM when imported, unlike an unfrozen library, which takes about as much RAM as the size of the .mpy file.

**Comment by dhalbert** [comment]
> Chris uses “chording” to increase his effective buttons and we’d use this.

Detecting chording is possible with `keypad.Keys`, since you know when keys went down and up. You need to keep some state to keep track of what's currently pressed down/

**Comment by ladyada** [comment]
shiftregisterkeys can be removed. touchio can stay - it's theoretically possible but id use a TRRS terminal breakout rather than a cable, so the signals stay apart as much as possible.

**Comment by ladyada** [comment]
can leave neopixel out for now, while its nice-to-have it isnt essential, id rather have the flash space free

**Comment by ATMakersBill** [comment]
Chris mainly uses Arduino on his devices. However those copying his
approaches would be better off starting in Python

As for the libraries, I thought on the samd21 the image and storage were
both in the UF2. That’s why we could make a UF2 file that included the code
and libraries. On chips with separate memory we could do that. Doesn’t that
mean the UF2 could include libraries?  Or at you saying there’s no build
process to do that (which would be fine)

Bill Binko
***@***.***

"Helping Makers Help Others"
Join us at http://atmakers.org

**Comment by dhalbert** [comment]
> Or are you saying there’s no build process to do that (which would be fine)

Yes, there's no mechanism for adding files like that right now.

**Comment by dhalbert** [comment]
In the `ja` translation, with `touchio` on:
- `ShiftRegisterKeys` off,  freeze `neopixel`, there are 268 bytes free.
- `ShiftRegisterKeys` on,  no freeze `neopixel`, there are 608 bytes free.
- ShiftRegisterKeys` off,  no freeze `neopixel`, there are 1768 bytes free. That's confusing - I don't know why it's more than the sum of the above, might be translation-table savings.

So I can freeze NeoPixel for now, might have to take it away if something else grows.

**Comment by dhalbert** [comment]
The `ru` translation overflowed with the above, so `neopixel` is no longer frozen.

**Pull request merged**
