### PR TITLE
nrf nvm: touchups to nickzoic PR #1768

### PR DESCRIPTION
**Pull request by dhalbert**
Hi @nickzoic - This is your PR with some additions. Subscripting was not working when I tested `nvm` on nrf. I think there were some more rebase issues. I've corrected that and changed a few typos. Could you test? If it's ok I'll merge this one and close the other one. I've tried pushing new commits to a PR, and though it's supposed to work based on the permissions we have set up, it does not seem to.

### CODE REVIEW

**Comment by nickzoic** [comment]
Hey Dan, thanks for the patch, I'll check this out this weekend.

I've got to get into the habit of writing an automated test for these things so I don't keep stuffing up last minute changes!

Cheers, Nick

**Comment by nickzoic** [comment]
Hang on, not sure this is right.
The changes in fdaff00c move the NVM space to the end of the FATFS space:

```
#define NVM_START_ADDR ((uint32_t)__fatfs_flash_start_addr + \
     (uint32_t)__fatfs_flash_length - CIRCUITPY_INTERNAL_NVM_SIZE)
```

and I think this has undone that and moved it back to where I initially had it, incorrectly, at the end of flash where it overlaps the "Bootloader Settings" segment defined in boards/adafruit_nrf52840_s140_v6.ld
This can brick the board if you write to nvm[0:4] ... I'm having a closer look now.

**Comment by nickzoic** [comment]
OK so yeah.  I've checked out 18908c2 and that's in the correct place and subscripts seem fine to me: what problem did you have @dhalbert ?

@tannewt we probably should revert this ... writing into that bootloader config segment can leave the board unbootable (needing a new bootloader flashed, anyway)

**Comment by dhalbert** [comment]
@nickzoic When I did subscripting I got range errors. The `self->len` value was not being set and was coming in as zero. See this commit:  864910559bc712deed112e072f61fd482adea1a6

**Comment by dhalbert** [comment]
I think you are right about the `NVM_START_ADDR`, but it had appeared to me that was leftover from the old PR. I'm sorry about that.

**Comment by nickzoic** [comment]
On Tue, 16 Apr 2019, at 12:49, Dan Halbert wrote:

> @nickzoic <https://github.com/nickzoic> When I did subscripting I got range errors. The `self->len` value was not being set and was coming in as zero. See this commit: 8649105


Which board was this on?

**Comment by dhalbert** [comment]
Tested on Feather nRF52840.

**Comment by dhalbert** [comment]
Here's what happened when I built 18908c2, pulling from your repo and checking out that branch:
```
halbert@salmonx:~/repos/nickzoic/micropython/ports/nrf$ git log -1
commit 18908c21f7998b13493fe75d0020bd9ad1bd1b60 (HEAD, origin/circuitpython-nickzoic-1042-nrf-nvm-bytearray-2)
Author: Nick Moore <nick@zoic.org>
Date:   Tue Apr 9 12:53:11 2019 +1000

    Fixups for adafruit/circuitpython#1042
```
```
halbert@salmonx:~/repos/nickzoic/micropython/ports/nrf$ repl
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.6-65-g18908c21f on 2019-04-15; Adafruit Feather nRF52840 Express with nRF52840
>>> 
>>> import microcontroller
>>> microcontroller.nvm[3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: ByteArray index out of range
```

**Comment by dhalbert** [comment]
I'm in discord if you want to chat there. Maybe there were some uncommitted files in your repo??

**Comment by nickzoic** [comment]
Oh super weird
```
Adafruit CircuitPython 4.0.0-beta.6-65-g18908c21f on 2019-04-16; Adafruit Feather nRF52840 Express with nRF52840
>>> from microcontroller import nvm
>>> len(nvm)
4096
>>> nvm[0:5] = b"hello"
>>> nvm[5:10] = b"world"
>>> nvm[0:10]
bytearray(b'helloworld')
>>> nvm[0:4096] = b'abcd' * 1024
>>> nvm[:] == b'abcd' * 1024
True
>>> nvm[3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: ByteArray index out of range
>>> nvm[3:4]
bytearray(b'd')
```
You know, I don't think in any of the tests I did I ever checked that reading a single byte works ... *sigh*.
OK, I'll fix that up ... and I'll log into discord in a mo ...

**Pull request merged**
