### PR TITLE
update tinyusb to fix cdc connection race

### PR DESCRIPTION
**Pull request by hathach**
Update tinyusb stack with PR https://github.com/hathach/tinyusb/pull/557 that fix race condition with host terminal on cdc connection. That cause echoed back message on connection with esp32 as follows.

```
Adafruit CircuitPython 6.0.0-278-g66fb09506 on 2020-11-16; MagTag with ESP32S2
>>> uto-reload is o
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'uto' is not defined
>>> 
```

The issue is also observed with nrf52840 as mentioned by @jepler

### CODE REVIEW

**Comment by dhalbert** [comment]
Some M0 de_DE builds are too big again. Not sure what to trim. We could turn `_pixelbuf` off temporarily on these builds until we get gcc 10.

There is a gcc 10 preview release, but I'm not sure if we should use it. The usual Nov/Dec gcc ARM toolchain release is not out yet.

**Comment by hathach** [comment]
> Some M0 de_DE builds are too big again. Not sure what to trim. We could turn `_pixelbuf` off temporarily on these builds until we get gcc 10.
> 
> 
> 
> There is a gcc 10 preview release, but I'm not sure if we should use it. The usual Nov/Dec gcc ARM toolchain release is not out yet.

Ooops, the build must be very tight before since the code size increase is very minimal.

**Comment by dhalbert** [comment]
> Ooops, the build must be very tight before since the code size increase is very minimal.

@hathach, yes, totally not your fault, we are suffering from translations that are too complete :smile:. @tannewt says gcc 10 should recover a couple of thousand bytes, but the expected gcc toolchain release is not there yet. (It's not late, but we are anxiously awaiting it.)

**Comment by tannewt** [comment]
Jeff just found a bit of space to add .rotation to epaper. You might be able to squeeze in now with it.

**Comment by hathach** [comment]
@dhalbert the `tud_connected()` also got piggy packed here as well. There may be side-effect with not-required DTR pr.

**Comment by jepler** [comment]
I have this to offer to further reduce the size of circuitpython.  It looks like it lets de_DE fit on feather_m0_express feather_m0_supersized and metro_m0_express along with the changes in this PR: https://gist.github.com/jepler/1f40cdadfabe61661c5fbad8ab58f030

It removes a little-used (I believe!) feature, calling the built in function `pow` with 3 arguments: `pow(a,b,c)`.  This is perhaps useful if you want to implement the RSA cryptosystem in pure Python code, but otherwise not much.  Nothing in learn system or circuitpython bundle uses it (in fact, the implementation of RSA in there has its own implementation of 3-arg pow, because it was probably from before we enabled it in the core)

I can (I think) add it to this PR if that's desired.  @tannewt is it OK to give up this bit of functionality?

**Comment by tannewt** [comment]
@jepler Yup! That's ok with me. Want to turn it off everywhere or for all SAMD21s at least?

**Review by jepler — APPROVED** [review]
The single failure is an artifact upload failure.

**Pull request merged**
