### PR TITLE
Rebrand EInk Portal to MagTag

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by makermelissa — DISMISSED** [review]
Looks good to me. :)

**Comment by ladyada** [comment]
@tannewt hihi since there will be other versions (4.2", 5.65", tricolor etc) could we name this one "MagTag 2.9 inch grayscale"  or somethin?

**Comment by tannewt** [comment]
@ladyada Yup! `adafruit_magtag_2.9_grayscale`?

**Comment by ladyada** [comment]
yezplz

**Review by ladyada — APPROVED** [review]

**Pull request merged**
