### PR TITLE
fixing the wrong rx,tx gpio related issue in 8.2.x for board waveshare-esp32-s3-pico

### PR DESCRIPTION
**Pull request by tirtharajsinha**
Updating the rx tx gpio numbers suggested by @dhalbert in #8372 .

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks! Will be in next 8.2.x release (no immediate plans for that).

**Comment by michael-ring** [comment]
When I understand correctly this patch frees up Pins GPIO33 and GPIO34, but I cannot see that they are added back to pins.h so that they actually can be used.

**Comment by dhalbert** [comment]
@michael-ring Did you mean GPIO43 and GPIO44? Those are the pins that were changed. On this board, I do not see that GPIO43 and GPIO44 are broken out. I'm looking at the pinout diagram here: https://www.waveshare.com/wiki/ESP32-S3-Pico#Pinout_Definition

**Comment by michael-ring** [comment]
I mean physical pins 11 and 12, GP33 and GP34 in picture 

This is what I see in pins.c, pin_GPIO33 and pin_GPIO34 are missing:

    { MP_ROM_QSTR(MP_QSTR_IO20), MP_ROM_PTR(&pin_GPIO20) },
    { MP_ROM_QSTR(MP_QSTR_IO21), MP_ROM_PTR(&pin_GPIO21) },
    { MP_ROM_QSTR(MP_QSTR_IO35), MP_ROM_PTR(&pin_GPIO35) },
    { MP_ROM_QSTR(MP_QSTR_IO36), MP_ROM_PTR(&pin_GPIO36) },

**Comment by dhalbert** [comment]
I agree with that. There are other missing pins too. https://github.com/adafruit/circuitpython/blob/8.2.x/ports/espressif/boards/waveshare_esp32_s3_pico/pins.c has a much more complete list, without the pin aliases (Ax, etc.).

@tirtharajsinha would you be able submit a PR to correct `pins.c` in `main` here to match `8.2.x`? I  am wondering if  this `pins.c` was copied from another board that wasn't a good match. @michael-ring If you would like to do a PR to make this match the `8.2.x` version that would be fine too.

**Comment by michael-ring** [comment]
I am setting up a build environment for esp32 atm, when this is ready I can check differences between s2 and s3 for pins.c and try on my board.

**Comment by tirtharajsinha** [comment]
thanks for addressing the issue, I have created a pull requested #8463 . @dhalbert 

As you update the `main` from `8.2.x` regularly, so I have not created pull request in `main`

**Comment by dhalbert** [comment]
Thanks. The `pins.c` in `main` is very different from the one in `8.2.x`, so this may just generate a merge conflict or cause a bad mergewhen we merge from 8.2.x to main. Could you submit a PR against `main` to minimize the differences in the board definitions? There _are_ necessary differences in the `sdkconfig` and maybe other places which will remain different.

**Comment by tirtharajsinha** [comment]
Hi, @dhalbert I have created a pull request against `main` in #8464 .

But at the time of rechecking I found a another issue, Pin 19 and 20 were added in pins.c mistakenly. These pins are broken out in these specific board. these pins are used as USB peripheral. 

So I have created a another PR ##8465 on `8.2.x`. I have already fixed this issue regarding pin (19,20) in PR #8464 to `main` 

Maker of these board have taken some very unusual decisions on remaping the pins.

**Pull request merged**
