### PR TITLE
MAX PWMOut frequency

### PR DESCRIPTION
**Pull request by s-light**
analyzed and documented the maximal PWMOut frequency.

tested on Adafruit ItsyBitsy M4 Express Pin D9 and D12:
~~output peak-to-peak voltage
→ @  6MHz 3.3V
→ @  7MHz 3.1V
→ @ 10MHz 2.7V
→ @ 15MHz 1.8V
→ @ 30MHz 0.35V~~
→ values above 30MHz generate no output.

~~Voltage Levels are correct if my old scope and my measuring is correct ;-)
so please someone with a good high-speed scope verify this..
the currently hard-coded 6MHz was eventually chosen as up to this point there is no drop in the peak-
to-peak voltage?~~
→ this was caused by my old scope..

eventually it would make sense to calculate the maximal pwm-frequency based on the Timer and prescaler options?!
but as Dan pointed to on [discord (link to message)](https://discordapp.com/channels/327254708534116352/327298996332658690/517111227223113740) it eventually makes more sense to add a simple `ClockOut`or `FrequencyOut`

please let me know what you think

### CODE REVIEW

**Comment by s-light** [comment]
a `FrequencyOut` would be a good fit as counterpart to the proposed / wip [ `FrequencyIn`](#1144)

**Comment by tannewt** [comment]
I can't remember where the 6mhz limit comes from but it doesn't seem good to allow frequencies that drop the voltage. We could do FrequencyOut using a GCLK but I'd prefer to have PWMOut drop duty cycle resolution in order to create a fast PWM frequency.

**Comment by dhalbert** [comment]
I agree with @tannewt. At higher frequencies, just make the duty cycle the coarsest necessary to preserve a 50% duty cycle (if not 0 or 100%).

**Comment by s-light** [comment]
ok thanks for your comments!
@dhalbert so do you mean to change the behavior of the timer initialization >6MHz to create a 50% duty-cycle?
i don't know if the voltage drop comes from my meassurement mistakes/ my osiliscope or eventually from some not 50% dutycycle?! 
anyone an idea how i can test this more? 
or do you think it is just good leaving 6MHz max, adding the 'magic number' fix and a comment (similar to what i have done currently)?

**Comment by dhalbert** [comment]
@s-light what is the spec'd bandwidth of your oscilloscope? (Or, what model is it?) If you are looking at the waveforms and they look more like sine waves than square waves (of some width), then the limited bandwidth of the scope may be giving incorrect peak-to-peak results.

As the frequency increases, the duty cycle granularity will increase. At some point only 0, 50%, and 100% will be possible. 6 MHz may or may not have been an exact calculation: it may have just been "that's a good upper bound".

**Comment by s-light** [comment]
my oscilloscope is a Hameg HM407 (Analog Digital Scope) - 40MHz 100Ms/s
i only can measure the fast outputs with the help of the *x10* button (on the time-scale)
and overall - Channel 1 is a little bit rusty (it goes down in Voltage if the Frequency is over 2KHz)
so i don't know how accurate the Channel 2 is at > 6MHz any more ;-)

i will look at the code some more and check what currently happens.. and if needed look into if its simple to implement / change to the graceful degrade..

@tannewt what do you mean with 'hook up to a new one'? 
i thought every timer object (i know the get reused if possible for multiple pwm outputs)
has its own prescaler and clock source? i will have a read again on this section of the datasheet...

**Comment by tannewt** [comment]
@s-light Right, the TC has a clock source that is one of the GCLKs. I believe we hook it up to the 48mhz GCLK now. We also have a 2mhz GCLK (48 / 24) and a 120mhz GCLK (2 * 60) that runs the CPU. The data sheet caps out the input clock to a TC to 100mhz IIRC (look under electrical characteristics at the end.) So we'd need a fourth GCLK setup at 96 (48 * 2) to get closer to the peripherals limit.

**Comment by tannewt** [comment]
Thanks for the update @s-light !

**Comment by tannewt** [comment]
I'm closing this because the refactoring doesn't account for the difference in limit between the SAMD21 and the SAMD51. Please reopen if you add it. Thanks!

**Pull request closed without merging**
