### PR TITLE
docs: usb_cdc.Serial.readinto has no nbytes parameter

### PR DESCRIPTION
**Pull request by Neradoc**
And returns int.

### CODE REVIEW

**Comment by dhalbert** [comment]
Build failure in build-doc is:
```
Warning, treated as error:
Using the :property: flag with the py:method directiveis deprecated, use ".. py:property::" instead.
Error: Process completed with exit code 2.
```

**Comment by Neradoc** [comment]
Wow that has to come from a sphinx related update, I didn't get that locally.
Now when I try to make locally with a fresh venv I get that:
```
WARNING: Using the :property: flag with the py:method directive is deprecated, use ".. py:property::" instead.
WARNING: Using the :property: flag with the py:method directive is deprecated, use ".. py:property::" instead.
WARNING: Using the :property: flag with the py:method directive is deprecated, use ".. py:property::" instead.
WARNING: Using the :property: flag with the py:method directive is deprecated, use ".. py:property::" instead.
```
Which is super useful.
When I run `ag ":property:"` I get these.
```
shared-bindings/rp2pio/index.rst
282:      :property:
288:      :property:

shared-bindings/sdioio/index.rst
117:      :property:
124:      :property:
```
These are generated files, so:
```C
//|     @property
//|     def writing(self) -> bool:
//|         """Returns True if a background write is in progress"""
//|
```
Becomes:
```rst
   .. method:: writing(self) -> bool
      :property:

      Returns True if a background write is in progress
```
I would think we shouldn't use `@property` in the docs, a property should just be documented as a property, `@property` is an implementation detail. Nevertheless, that's a new error.
I would change it to:
```C
//|     writing: bool
//|     """Returns True if a background write is in progress"""
//|
```
I can add those changes to this PR, but I get another error in the template, due to sphinx version, I'm curious to see if the CI gets it too.

**Comment by Neradoc** [comment]
Ok this time the CI does give the same error I get locally:
```
An error happened in rendering the page BUILDING.
Reason: ValueError('too many values to unpack (expected 3)')
```
This is a sphinx-rtd-theme issue:
https://github.com/readthedocs/sphinx_rtd_theme/issues/1343

We can temporarily set the sphinx version to 5.1.1

**Comment by jepler** [comment]
> We can temporarily set the sphinx version to 5.1.1

Mind adding that to this PR? If you do please tag me for reviewing.

**Comment by Neradoc** [comment]
Pushed the workaround:
```
sphinx!=5.2.0.post0
```

**Review by jepler — APPROVED** [review]
If this finally builds it's good to merge. I added the 3.10.6 python pin for the doc build

**Comment by jepler** [comment]
Thanks!

**Pull request merged**
