### PR TITLE
Add the AI-Thinker ESP32-CAM board initial support

### PR DESCRIPTION
**Pull request by evildave666**
Support for the ESP32-CAM board from AI-Thinker (http://www.ai-thinker.com/pro_view-24.html)

Tested:
Wifi, including web workflow
Both onboard LEDs (on IO4/IO33)
IO0/2/12-15
Onboard microSD card via SPI (sdio is not yet supported on espressif)

IO16 is broken out but is used for the PSRAM CS so the pin is left undefined

Untested:
Camera support, but necessary defines in pins.c have been made already.

Creationid registered in https://github.com/creationid/creators/pull/18

### CODE REVIEW

**Comment by jepler** [comment]
Hi! Right now we know there are problems with canio on esp32 as noted in https://github.com/adafruit/circuitpython/issues/6605 -- all I tested was loopback mode, as I didn't assemble a setup with transceiver boards &c.

if you can test and provide any additional information on that PR or perhaps help us resolve it, that could be helpful.

**Comment by jepler** [comment]
Converting to draft until you verify the camera works. Please also let us know if you see unexplained weirdness with or without camera similar to #6745 as we have no good grasp of just what is going on there yet.

**Comment by evildave666** [comment]
I tried compiling in camera support, but I'm kind of going in blind. I usually don't buy these boards with the camera and I actually only have a single camera module.

After working out the errors in the documentation I am getting the following when I try to run this code from the camera-enabled build:

```
import board
import busio
import esp32_camera

cami2c = busio.I2C(board.CAMERA_SCL,board.CAMERA_SDA)

while not cami2c.try_lock():
    pass

print(cami2c.scan())

camera=esp32_camera.Camera(data_pins=board.CAMERA_DATA, pixel_clock_pin=board.CAMERA_PCLK,
                           vsync_pin=board.CAMERA_VSYNC,href_pin=board.CAMERA_HREF, i2c=cami2c,
                           external_clock_pin=board.CAMERA_XCLK,external_clock_frequency=200000,
                           powerdown_pin=board.CAMERA_PWDN, pixel_format=esp32_camera.PixelFormat.RGB565,
                           frame_size=esp32_camera.FrameSize.QQVGA)

```
```
>>> %Run -c $EDITOR_CONTENT
[]
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
espidf.IDFError: Requested resource not found
```

Am I doing something wrong?

**Comment by jepler** [comment]
The camera module should be seen by the `scan()`. The error from esp-idf is because it didn't detect any camera.

**Comment by jepler** [comment]
oh the i2c detection might not work before the external clock signal is provided on the appropriate output pin from the esp32 microprocessor.so it might be "expected" that it didn't show up in scan.

**Comment by evildave666** [comment]
What would be a reasonable value for external_clock_frequency for testing?

**Comment by jepler** [comment]
20MHz is used [by the esp32_camera example](https://github.com/espressif/esp32-camera/blob/master/examples/main/take_picture.c#L118) from espressif:
```    .xclk_freq_hz = 20000000,
```

**Comment by jepler** [comment]
in fact there are comments in there that say how to configure the espressif example for the ai thinker esp32-cam so maybe you should build that and see if it works, as an independent test of the camera.

**Comment by evildave666** [comment]
OK, I've made progress of a sort. When I changed the XCLK from 200KHz to 20MHz I no longer get the espidf.IDFError, the board reboots instead.

I'm at a loss on where to proceed at this point.

**Comment by jepler** [comment]
Can you try building espressif's code sample for this board?

**Comment by jepler** [comment]
@dhalbert what do you think of merging in this state, where the camera is known not to work?

**Comment by dhalbert** [comment]
> @dhalbert what do you think of merging in this state, where the camera is known not to work?

I don't think I would do it, because it would just encourage more support questions. "The board is there, how come the camera doesn't work?"

**Comment by evildave666** [comment]
Since this is going to require directory/board id renaming as well, I'm going to close this and start with a fresh PR after cleaning up my build environment and trying against the current esp-idf. I'm suspecting the camera issues are probably due to my cargo-culting sdkconfig and having some setting wrong so going to experiment with that.

I tried building the espressif sample code but was unable to get it working in VS Code and didn't have much time to devote to it for a while (white-sand beach vacation).

**Comment by jepler** [comment]
I belatedly notice about the code here that the i2c bus is left locked when the camera constructor is called. This is incorrect and should result in an exception. It should now result in an OSError with the errno value of EWOULDBLOCK. But at the time this PR was in progress, the problem might not have been detected.

**Pull request closed without merging**
