### PR TITLE
Add DAC* and RTL_* pin assignments to Wio Terminal board.

### PR DESCRIPTION
**Pull request by t-ikegami**
This PR defines DAC* and RTL_* pins in board module of Wio Terminal.  Addition of RTL_MOSI (=PB24) is essential, because PB24 is missing in microcontroller.pin.  With this PR, the following code works to communicate with RTL8720.
```
import board
import digitalio as dio
import busio
import time

pwr = dio.DigitalInOut(board.RTL_PWR)
pwr.switch_to_output()
pwr.value = False
time.sleep(0.1)
pwr.value = True
time.sleep(0.1)

u = busio.UART(board.RTL_MOSI, board.RTL_MISO, baudrate = 614400)
time.sleep(0.1)

buf = bytearray([ 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00 ])
header = bytearray(b'\x08\x00\xc9\xd0')
u.write(header + buf)
time.sleep(0.1)
u.read()      # -> b'\x11\x00\xd1\xab\x02\x01\x01\x01\x00\x00\x00\x00\x05\x00\x00\x002.1.2'
```
The crude code above sends an eRPC request to get the RTL8720 firmware version.

### CODE REVIEW

**Comment by tannewt** [comment]
Would you mind fixing `microcontroller.pin` as well? The list is here: https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/common-hal/microcontroller/__init__.c#L268

**Comment by t-ikegami** [comment]
I didn't touch the __init__.c, because I suspect that some pins are intentionally left undefined.  If it is not the case, I'm happy to add PB2[4-9] to the file.   One concerning point: the former fix required 268 bytes of ROM space, and the latter requires another 132 bytes.  Is it worth it?

**Comment by tannewt** [comment]
> I didn't touch the `__init__.c`, because I suspect that some pins are intentionally left undefined. If it is not the case, I'm happy to add `PB2[4-9]` to the file. One concerning point: the former fix required 268 bytes of ROM space, and the latter requires another 132 bytes. Is it worth it?

I don't think it's intentional. It's just hard to track in the datasheet. Boards that need more space can use the IGNORE_ macros to turn them off.

Ya, I think the space is worth it.

Thanks!

**Comment by t-ikegami** [comment]
Got it.

**Comment by Neradoc** [comment]
What do you think of putting additional names for the 40-pin header ?
I filed that after somebody asked about missing pins in the discord, but I don't have the board to check:  #4586

**Comment by t-ikegami** [comment]
The pin names of GP* come from Raspberry Pi, and I have no idea of their use cases.  Defining I2S_* pins will be convenient when using audiobusio module.  However, I also wonder if it may not be necessary to define aliases of those pins used as a group (such as RTL_* and I2S_*), as far as they are accessible in other ways.  Which option do you think is suitable?

1. Add I2S_* definitions to board module.
2. Remove RTL_* definitions from board module (only DAC0/1 remain)
3. Others

In addition, thanks to tannewt suggestion, I will add IGNORE_ macros on Wio Terminal for the following pins:
PA00, PA01, PA03, PA23, PB15, PB22, PB23, PC00
They are Xtal, AREF, or NC.

**Comment by tannewt** [comment]
> The pin names of GP* come from Raspberry Pi, and I have no idea of their use cases. Defining I2S_* pins will be convenient when using audiobusio module. However, I also wonder if it may not be necessary to define aliases of those pins used as a group (such as RTL_* and I2S_*), as far as they are accessible in other ways. Which option do you think is suitable?
> 
>     1. Add I2S_* definitions to board module.
> 
>     2. Remove RTL_* definitions from board module (only DAC0/1 remain)
> 
>     3. Others

I think it's fine to have more than one name for a pin. It can allow code to work across boards when the names are standardized.

> In addition, thanks to tannewt suggestion, I will add IGNORE_ macros on Wio Terminal for the following pins:
> PA00, PA01, PA03, PA23, PB15, PB22, PB23, PC00
> They are Xtal, AREF, or NC.

:+1: 

The CI will be happier after it runs again. main was broken for a bit.

**Comment by t-ikegami** [comment]
I've added 4 I2S_* pin assignments in board module, and removed 8 pins above from microcontroller.pin for Wio Terminal.

**Review by tannewt — DISMISSED** [review]
Changes look good. Thank you!

**Comment by dhalbert** [comment]
I fixed the merge conflict, which appeared to be just an indentation difference between two different additions of pins PB24-PB29.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
