### PR TITLE
Enable _uasyncio module

### PR DESCRIPTION
**Pull request by t-ikegami**
This PR fixes ticks in moduasyncio.c to work with adafruit version of asyncio, and enables _uasyncio module.  With this PR, C-version of Task and TaskQueue are used in the asyncio.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
The `_uasyncio` implementation of `Task` does not provide`__await___()`. Our internal implementation of `async/await` (done by @WarriorOfWire) requires that. Otherwise code is going to fail. I had to add `__await__()` in the Python version in a couple of places:
https://github.com/adafruit/Adafruit_CircuitPython_asyncio/blob/28ef812f14ef1fde1036eb83a4878bd14aa9a67d/asyncio/task.py#L152
https://github.com/adafruit/Adafruit_CircuitPython_asyncio/blob/28ef812f14ef1fde1036eb83a4878bd14aa9a67d/asyncio/core.py#L52-L53

I started to add `__await__()`, but because `__iter__()` is provided in a special way, I had not yet figured out how to make it work, and so did not use `_uasyncio` initially.


In addition, I would like to rename `_uasyncio` to `_asyncio`, but that is minor.

**Comment by t-ikegami** [comment]
Thank you for the comment.  Now I understand why _uasyncio is missing in the modules.  I'll close this PR.

**Comment by dhalbert** [comment]
If you can see how to add `__await()__`, that would be great. but it's rather deep in method resolution. I haven't had time to look further.

**Comment by dhalbert** [comment]
I appreciate your work, and we can use these commits in the future, in any case.

**Comment by t-ikegami** [comment]
The `__await__` method is added to Task class, which is just a wrapper of getiter.  The name of the module is not modified for now, because the renaming should be in sync with adafruit/asyncio.  With this PR, Task object becomes awaitable, and the following code works.
```
import asyncio

async def coro(s) :
    print("coro start", s)
    await asyncio.sleep(s)
    print("coro done", s)
    return f"coro result({s})"

async def main() :
    print("main start")
    res = await asyncio.gather(coro(1), coro(2), coro(3))
    print(res)
    print("main end")

asyncio.run(main())
```

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thank you for doing this, and testing it! I have a few changes, but I'm glad you were able to figure out an easy way to do this.

**Comment by t-ikegami** [comment]
The module is renamed from _uasyncio to _asyncio.  I couldn't figure out MICROPY_PORT_BUILTIN_MODULES stuff well, but the module is now registered not in objmodule.c but by MP_REGISTER_MODULE.  (I referred modure.c and modujson.c.)

**Review by t-ikegami — COMMENTED** [review]
I appreciate the clarification.

**Comment by dhalbert** [comment]
> I appreciate the clarification.

You were right to use `MP_REGISTER_MODULE`. The comments re `MICROPY_PORT_BUILTIN_MODULES` were obsolete. I am having trouble getting it to pass one test. Not quite there yet.

**Comment by t-ikegami** [comment]
> I am having trouble getting it to pass one test. Not quite there yet.

I suspect that tests/unix/extra_coverage.py.exp should be updated (_asyncio module may appear in repl auto-completion), though I failed to build unix/micropython-coverage so far.

**Comment by dhalbert** [comment]
> I suspect that tests/unix/extra_coverage.py.exp should be updated (_asyncio module may appear in repl auto-completion), though I failed to build unix/micropython-coverage so far.

Yes, that was it. I had to `sudo apt install pkgconf libffi-dev` to get `micropython-coverage to build:
`make VARIANT=coverage -j12` # or whatever -j is appropriate for you

**Review by t-ikegami — COMMENTED** [review]
Thank you for the update.

**Review by dhalbert — APPROVED** [review]
After my last set of tweaks, I tested this with a two-task blinking LEDs program on a Metro M4, and it's working. Thanks for this, @t-ikegami !

**Comment by dhalbert** [comment]
I have to shrink the matrixportal build slightly, or perhaps turn off uasyncio in that build.

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
