### PR TITLE
Switch to GCC 13.2

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
`thunderpack_v12` is overflow on some languages. That's the only build issue.
https://github.com/adafruit/circuitpython/actions/runs/6701701119/job/18209634951?pr=8546

**Comment by dhalbert** [comment]
en_US builds:

atmel-samd (uses LTO): Trinket M0 is 1228 bytes smaller with gcc13.2; Metro M4 is 1960 bytes smaller. 
stm (does not use LTO): thunderpack_v12 is 7444 bytes larger, hence the overflow. It appears that some `ulab` functions have grown a lot. Maybe we need to check the optimization flags for ulab?

Size growth (positive) or shrink (negative) from gcc 12 to gcc 13: (a few unique names discarded):
[diffs.txt](https://github.com/adafruit/circuitpython/files/13218377/diffs.txt)

**Comment by tannewt** [comment]
I disabled AESIO and BUSDEVICE on thunderpack and it fits now.

**Review by dhalbert — APPROVED** [review]
Thanks! Eventually we want to figure out why certain `ulab` functions grew so much with gcc 13.2

**Pull request merged**
