### PR TITLE
RFM9x -- freeze library into build

### PR DESCRIPTION
**Pull request by jerryneedell**
This freezes adafruit_bus_device and adafruit_rfm9x into the build for the feather_m0_rfm9x.
I had to take out several modules.
At this point, pulseio is removed. It may be possible to put it back once #3236 and #3237 are implemented. Right now some of the larger translations will not build with it and it does not work on the SAMD21 anyway.  We can revisit this.
The main downside to removing it is we cannot support the DHT sensors.

I waned to get this out so it can be reviewed and be available for anyone to test.

adds Adafruit_CircuitPython_RFM9x to the frozen folder

### CODE REVIEW

**Comment by brentru** [comment]
@jerryneedell  I'll be testing this today, added to TODOs

**Comment by brentru** [comment]
@jerryneedell  Was too optimistic, will get to this tomorrow

**Comment by brentru** [comment]
@jerryneedell  Ok, I checked out the branch and built the `uf2`. Had to delete default `images` folder to fit the simpletest `code.py` for the RFM9x.

Importing `adafruit_rfm9x` at the REPL throws the following `ImportError`
```
Adafruit CircuitPython 6.0.0-alpha.2-295-g5cf41c0d1 on 2020-08-17; Adafruit Feather M0 RFM9x with samd21g18
>>> import adafruit_rfm9x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'adafruit_rfm9x'
```

**Comment by jerryneedell** [comment]
> @jerryneedell Ok, I checked out the branch and built the `uf2`. Had to delete default `images` folder to fit the simpletest `code.py` for the RFM9x.
> 
> Importing `adafruit_rfm9x` at the REPL throws the following `ImportError`
> 
> ```
> Adafruit CircuitPython 6.0.0-alpha.2-295-g5cf41c0d1 on 2020-08-17; Adafruit Feather M0 RFM9x with samd21g18
> >>> import adafruit_rfm9x
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: no module named 'adafruit_rfm9x'
> ```

Not sure I understand where the “images” folder came from.

**Comment by jerryneedell** [comment]
works for me
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.2-175-g5f60bec85 on 2020-08-17; Adafruit Feather M0 RFM9x with samd21g18
>>> 
>>> import adafruit_rfm9x
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.



Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.2-175-g5f60bec85 on 2020-08-17; Adafruit Feather M0 RFM9x with samd21g18
>>> import rfm9x_simpletest
Sent Hello World message!
Waiting for packets...
Received nothing! Listening again...
Received nothing! Listening again...
Received nothing! Listening again...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rfm9x_simpletest.py", line 53, in <module>
  File "adafruit_rfm9x.py", line 745, in receive
  File "adafruit_rfm9x.py", line 595, in rx_done
  File "adafruit_rfm9x.py", line 359, in _read_u8
  File "adafruit_rfm9x.py", line 351, in _read_into
  File "adafruit_bus_device/spi_device.py", line 90, in __enter__
KeyboardInterrupt: 
>>> 



```

**Comment by jerryneedell** [comment]
@brentru just tested #3237  on an rfm9x build with pulseio enabled and it can now support the DHT sensors.
perhaps we should hold off on this until #32327 is merged and I can see if I can fit pulseio back into the build.

**Comment by brentru** [comment]
> perhaps we should hold off on this until #32327 is merged and I can see if I can fit pulseio back into the build.

@jerryneedell  I don't see any learn guides/projects which utilize the DHT+LoRa RFM9x (aside from TTN ones, and those should be run on the SAMD51). Are you OK with merging this as-is, and we can create another PR to fit `pulseio` after?

**Comment by jerryneedell** [comment]
> Works! Thanks for making room

I can try to get pulseio back in tomorrow and if all is OK we move ahead -- it will pick up #3237 whenever it is ready -- don't really have to wait.

**Comment by jerryneedell** [comment]
> > perhaps we should hold off on this until #32327 is merged and I can see if I can fit pulseio back into the build.
> 
> @jerryneedell I don't see any learn guides/projects which utilize the DHT+LoRa RFM9x (aside from TTN ones, and those should be run on the SAMD51). Are you OK with merging this as-is, and we can create another PR to fit `pulseio` after?

Yes -- absolutely -- go ahead -- pulseio may not fi anyway

**Pull request merged**
