### PR TITLE
Add GD25Q32C flash device definition

### PR DESCRIPTION
**Pull request by arturo182**
Tested with a board I'm working on :)

### CODE REVIEW

**Comment by arturo182** [comment]
The build failed but that doesn't seem to be my code's fault :sweat_smile: 

```Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
msgfmt: error while opening "build/genhdr/en_US.mo" for writing: No such file or directory
../../py/py.mk:320: recipe for target 'build/genhdr/en_US.mo' failed
make: *** [build/genhdr/en_US.mo] Error 1
```

**Comment by dhalbert** [comment]
@arturo182 I simulated the build on my own machine and didn't see this issue. I re-ran the build a couple of times and now it's failing even earlier, not being able to find a commit. I'd guess there are some issues on the GitHub Actions side; we can try again in the morning.

**Comment by arturo182** [comment]
No worries, this is not a high prio commit, just wanted to have it here so I don't lose track of it :)

**Comment by dhalbert** [comment]
I tried re-rerunning this morning and the check-run again failed trying to find a commit. I made a trivial typo fix to force a new commit and new check run, and it worked.

**Comment by dhalbert** [comment]
Thank you for the addition!

**Pull request merged**
