### PR TITLE
Circuitpython nickzoic 1046 nrf rtc

### PR DESCRIPTION
**Pull request by nickzoic**
This is an implementation of #1046 , with a couple of things missing:

* I was having trouble with the weak references to common_hal_rtc_get_time and common_hal_rtc_set_time which I've got a workaround for but not really an explanation for
* There's no calibration for this RTC.  It could be calibrated by scaling the RTC counter values slightly but there's no facility for tuning the RTC clock itself.

### CODE REVIEW

**Comment by dhalbert** [comment]
I have been unable to get `-flto` to work on the nRF build, which is really strange (see https://github.com/adafruit/circuitpython/issues/1396). I'm not sure if that might be related to the weak references issue, but possibly.

**Comment by nickzoic** [comment]
I'm very puzzled about the whole thing.  I'm not, at this point, sure if it is a flaw in my understanding of `__attribute__((weak))` or something genuinely weird going on, maybe in combination with inheriting the `__attribute__((noreturn))` from the raise?

I got as far as working out that if I removed the weak declarations, *OR* changed the error messages raised by the weak declarations to be different, then the problem goes away. 8a88a6f uses this workaround so at least I could make some progress on this issue, but I'm not real happy about it.

**Comment by nickzoic** [comment]
(oh, and because I changed that error message it's upset the translations, which is what Travis is complaining about.  I'm seeking a better way)

**Comment by bboser** [comment]
Possibly this could be combined with deepsleep, which also needs an RTC timer as timeout and to advance the systick so time.monotonic() returns a reasonable result after sleep. This however would require a lower divide value (1024). My implementation of deepsleep is here: https://github.com/bboser/iotpython/blob/master/ports/nrf/common-hal/microcontroller/__init__.c.

The other possible issue is that apparently the softdevices (BT?) also use RTC timers. Somewhere I read that RTC0 is used by the softdevice but I cannot locate the reference.

**Comment by tannewt** [comment]
@nickzoic Are you blocked by anything on this?

**Comment by nickzoic** [comment]
Hi Scott!  I got sidetracked trying to work out the weak reference thing.  See comments at end of #1046.
Perhaps Dan's changes to make system will avoid this problem?  It is very curious that it is a problem with `-O2` set and not `-O1`, and very much repeatable.

**Comment by nickzoic** [comment]
OK so I've rebased it and sadly, no change.  I've just changed one of the messages for now and provided translations as best I can approximate for the new message.

**Comment by tannewt** [comment]
I think we should get this in once the translations are merged. It should be good to go otherwise.

**Comment by nickzoic** [comment]
Did I get the push wrong again? I'm away for a few days but have laptop so can amend if necessary ...

-----Nick

**Comment by tannewt** [comment]
@nickzoic please take a look when you are back. There are files that need to be merged.

**Comment by nickzoic** [comment]
OK @tannewt trying yet again to get this to pass CI checks ...

**Comment by dhalbert** [comment]
@nickzoic Just saw this issue in micropython: https://github.com/micropython/micropython/issues/4590. Is it relevant to your impl?

**Comment by nickzoic** [comment]
@dhalbert you mean for the problems with the Ethernet wing like #1500, right?
(I think there was another one too, or maybe that was a discussion on Discord)
I've never been able to successfully replicate those so haven't got anywhere tracking them down.

The Wiznet5K implementation for circuitpython doesn't use LWIP but it might be worth looking at the error handling in `wiznet5k_socket_send()` and see if there's situations there where we should retry rather than erroring out.

**Comment by dhalbert** [comment]
RIght - I didn't know how much of your code was common with the MPy code, if any.

**Comment by nickzoic** [comment]
On Fri, 29 Mar 2019, at 03:30, Scott Shawcroft wrote:
> *@tannewt* approved this pull request.

> Tweaked one old comment and looks good otherwise. Will merge after Travis gives the ok. Thanks for your persistence on this!


Thanks Scott! Yeah, getting languages to merge is a bit of a bear, eh ... every time I think it's working they get out of date again!

(I do think multilingual support is a great feature though, I just wish it was easier to merge!)

**Comment by tannewt** [comment]
Ya, I looked into having a smarter merge but didn't see any great options.

**Comment by tannewt** [comment]
@nickzoic Want to take a look at why this broke BLE? Totally ok if you don't have the time.

**Comment by bboser** [comment]
The BLE soft device uses RTC 0. Just a hunch. See my earlier comment on
github.

Bernhard

**Comment by nickzoic** [comment]
On Tue, 2 Apr 2019, at 09:13, Bernhard Boser wrote:
> The BLE soft device uses RTC 0. Just a hunch. See my earlier comment on
>  github.

Yeah, I saw that one (thanks!) but didn't get around to following up (sorry!)

A quick google suggests you're correct ...
https://devzone.nordicsemi.com/f/nordic-q-a/5235/usage-of-rtc0-as-time-basis-system-time-possible
https://devzone.nordicsemi.com/f/nordic-q-a/305/rtc0-rtc1-and-the-app_timer-with-softdevice
https://devzone.nordicsemi.com/f/nordic-q-a/22941/how-to-enable-and-use-rtc0-rtc1-and-rtc2----nrf52832

Suggests RTC0 is used by the softdevice and RTC1 is used by the app_timer library which is used in other libraries.

So maybe, so long as we're no longer targeting the '32 revision A, we should move it to RTC2?
https://www.nordicsemi.com/DocLib/Content/Errata/nRF52832_EngA/latest/ERR/nRF52832/EngineeringA/latest/anomaly_832_10 

I'll have to work out how BLE works so I can actually test this I suppose!

Re: your other comments about deepsleep, definitely yes, that'd be a good idea.

-----N

**Comment by nickzoic** [comment]
OK so I've changed it across to RTC2 and it works from the point of view of the RTC, has anyone got some code which demonstrates it *not* working with BLE which would work with BLE stuff I might have lying around?

**Comment by dhalbert** [comment]
See the example in https://github.com/adafruit/circuitpython/pull/1726. Try that. If that doesn't cause an immediate error, then doing something like https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/examples/ble_uart_echo_test.py with the Adafruit Bluefruit LE Connect app on the other end would be a simple test.

**Comment by dhalbert** [comment]
Also, take out the `MP_WEAK` attributes on the functions. That should not be necessary. If they ever were, they are not needed now.

**Comment by nickzoic** [comment]
OK that UART example works with nickzoic/micropython@48f056647f which now uses RTC2.  Thanks for the pointer, I hadn't tried using BLE for anything yet.

You mean the MP_WEAKs in shared-bindings? Does the new build system avoid building the shared-bindings for non-existent modules now? It'd be great if we didn't need them any more, but I don't know about the other ports?

**Comment by dhalbert** [comment]
Yes, we don't compile the source files for modules that are turned off. But `rtc.RTC` was the only one that ever used MP_WEAK. I'm not sure why it was done that way to begin with. If you grep for MP_WEAK, you'll find very few uses. You don't need the `NotImplemented` versions. But a use or two here or there may need to check `#if CIRCUITPY_RTC`.

Or maybe I am all wrong about this, but looking at the uses of RTC, it does not seem to need fallback routines.

**Comment by nickzoic** [comment]
Yep, I've removed them altogether since both atmel-samd and nrf ports have RTC anyway.

**Pull request merged**
