### PR TITLE
update ulab to 6.3.2

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]

**Comment by jepler** [comment]
OK, the test failure is _wild_

Any change can add or remove qstrs, which also changes the numbering of qstrs. Strings used as identifiers also get added as qstrs.

The line `\.\+63` is intended to check that the bytecode of the function ends with a 63 instruction, AKA RETURN_VALUE. However, with this exact set of qstrs the identifier `g` gets the qstr number `0x0463` which appears in the instruction bytecode as `04 63`, which gets matched by the regular expression.

That causes the remainder of the parsing to all be off by one line, and the test is treated as failed.

**Comment by jepler** [comment]
It looks like the updated version over-fills a number of boards' flash space :-/

**Comment by jepler** [comment]
I had to slim down a number of builds for this to fit. Are we entering the era of this for samd51 ? :sweat:

**Comment by dhalbert** [comment]
> I had to slim down a number of builds for this to fit. Are we entering the era of this for samd51 ? 😓

We could also consider turning off little-used features in `ulab`. I think we already made the SAMx5x builds `-Os`, but you could check that.

**Comment by dhalbert** [comment]
> think we already made the SAMx5x builds `-Os`, but you could check that.

Yes, they are already `-Os`.

**Review by dhalbert — APPROVED** [review]
Thanks for seeing this through.

**Comment by tannewt** [comment]
> I had to slim down a number of builds for this to fit. Are we entering the era of this for samd51 ? 😓

I think we need a plan for `ulab` since it keeps growing. Maybe we need to freeze versions for smaller MCUs. We basically do this by omitting newer python modules.

**Comment by gamblor21** [comment]
> > I had to slim down a number of builds for this to fit. Are we entering the era of this for samd51 ? 😓
> 
> I think we need a plan for `ulab` since it keeps growing. Maybe we need to freeze versions for smaller MCUs. We basically do this by omitting newer python modules.

After looking at ulab for the synth filter stuff, if parts of the ulab python need to be omitted having someplace where people can find the omitted parts of the library would be helpful. I never realized that a lot of ulab is written in python and if split could be added if the author requires it.

**Comment by dhalbert** [comment]
> I never realized that a lot of ulab is written in python

What parts are you seeing in Python? Everything in https://github.com/v923z/micropython-ulab is C except for tests.

**Comment by gamblor21** [comment]
> > I never realized that a lot of ulab is written in python
> 
> What parts are you seeing in Python? Everything in https://github.com/v923z/micropython-ulab is C except for tests.

Ah sorry! I got confused with the CPython implementation.

**Comment by tannewt** [comment]
FYI This PR needed to update .gitmodules to point to @jepler's ulab repo because of the fix commit: https://github.com/jepler/circuitpython-ulab/commit/3728d22732dedc8a591b7df18a16d3ef1aed6a39

**Comment by jepler** [comment]
https://github.com/jepler/circuitpython-ulab/commit/3728d22732dedc8a591b7df18a16d3ef1aed6a39 was merged to their main branch so it should be OK?

**Comment by tannewt** [comment]
I wonder if something changed with GitHub. `make fetch-all-submodules` isn't working for me if I use the repo it was merged into.


Here is my esp32-camera failure even though I merged your PR yesterday:
```
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'ports/espressif/esp32-camera', but it did not contain 2cd2a6d69faaba9ebb6105814a50039d82e2f899. Direct fetching of that commit failed.
```

**Comment by tannewt** [comment]
I didn't do remove. I manually removed the troubled one.

**Pull request merged**
