### PR TITLE
Extend EVE hardware opcodes for future-compatibility

### PR DESCRIPTION
**Pull request by jamesbowman**
Extend the bitfields of these instructions: BitmapHandle, ClearTag, Tag, BitmapSource, PaletteSource
Add instructions: BitmapSourceH PaletteSourceH

All the new bits and opcodes are ignored by earlier hardware, so this change is backwards-compatible.

Passes tests on all EVE hardware.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Looks fine to me! Thanks!

**Comment by dhalbert** [comment]
@tannewt I had to make room on Feather M4 and Metro M4. I turned off `aesio`, but should we turn off something else instead? @jamesbowman Are these boards used with eve hardware?

**Comment by dhalbert** [comment]
@tannewt @jamesbowman I was able to remove `microcontroller.pin.<somepin>` for a few pins that were not connected on Feather M4 and Metro M4, and so left `aesio` alone. This is good for a short while. Probably eventually we'll need to turn off something larger.

**Review by dhalbert — APPROVED** [review]
Now that this builds for all boards we can merge it.

**Pull request merged**
