### PR TITLE
picow: turn off CIRCUITPY_USB_HOST and CIRCUITPY_PICODVI

### LINKED ISSUE #9174: SSL not working when importing Adafruit-azureiot on a rpPico W
### CircuitPython version

```python
Adafruit CircuitPython 9.0.3 on 2024-04-04; Raspberry Pi Pico W with rp2040
Board ID:raspberry_pi_pico_w
```

### Code/REPL

```python
import os
import time
import adafruit_ntp
import rtc
import ipaddress
import ssl
import wifi
import socketpool
import adafruit_requests
import board
import busio
import terminalio
import displayio
from adafruit_display_text import label
from adafruit_st7735r import ST7735R
from adafruit_azureiot import IoTCentralDevice


#  ntp clock - update tz_offset to your timezone
pool = socketpool.SocketPool(wifi.radio)
ntp = adafruit_ntp.NTP(pool, tz_offset=-4)
rtc.RTC().datetime = ntp.datetime

if time.localtime().tm_year < 2023:
    print("Setting System Time in UTC")
    rtc.RTC().datetime = ntp.datetime

else:
    print("Year seems good, skipping set time.")

cal = ntp.datetime
year = cal[0]
mon = cal[1]
day = cal[2]
hour = cal[3]
minute = cal[4]

# Support both 8.x.x and 9.x.x. Change when 8.x.x is discontinued as a stable release.
try:
    from fourwire import FourWire
except ImportError:
    from displayio import FourWire


# *** The following code is for the WiFi radio ***
print(f"My MAC address: {[hex(i) for i in wifi.radio.mac_address]}")

print("Available WiFi networks:")
for network in wifi.radio.start_scanning_networks():
    print("\t%s\t\tRSSI: %d\tChannel: %d" % (str(network.ssid, "utf-8"),
                                             network.rssi, network.channel))
wifi.radio.stop_scanning_networks()

print(f"Connecting to {os.getenv('CIRCUITPY_WIFI_SSID')}")
wifi.radio.connect(os.getenv("CIRCUITPY_WIFI_SSID"), os.getenv("CIRCUITPY_WIFI_PASSWORD"))
print(f"Connected to {os.getenv('CIRCUITPY_WIFI_SSID')}")
priv_ip = wifi.radio.ipv4_address
print(f"My IP address: {str(priv_ip)}")


print("-" * 40)

# *** The following code is for pinging ***
ping_ip = ipaddress.IPv4Address("8.8.8.8")
ping = wifi.radio.ping(ip=ping_ip)

if ping is None:
    print("Couldn't ping 'google.com' successfully")
else:
    # convert s to ms
    print(f"Pinging 'google.com' took: {ping * 1000} ms")

print("-" * 40)

# *** The following code is for fetching text from a URL ***
pool = socketpool.SocketPool(wifi.radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())
TEXT_URL = "https://minip.no/"
print(f"Fetching text from {TEXT_URL}")
response = requests.get(TEXT_URL)
print("-" * 40)

# split the response text into lines and print the second line, it should be the external IP address
lines = response.text.split('\n')
if len(lines) > 1:
    #print(lines[1])
    parts = lines[1].split(" ")
    ext_ip_address = parts[5]  # The IP address is the 6th part when splitting by space
    print("External IP: " + ext_ip_address)
else:
    print("Response text does not have a second line.")

print("-" * 40)


# *** The following code is for the ST7735R display ***

# Release any resources currently in use for the displays
displayio.release_displays()

spi = busio.SPI(clock=board.GP10, MOSI=board.GP11, MISO=None)
tft_cs = board.GP9
tft_dc = board.GP8

display_bus = FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=board.GP12)

display = ST7735R(display_bus, width=128, height=130, colstart=2, rowstart=1, bgr=False)

# Draw Yggdrasil
bitmap = displayio.OnDiskBitmap("/yggdrasil.bmp")
tile_grid = displayio.TileGrid(bitmap, pixel_shader=bitmap.pixel_shader)
group = displayio.Group()
group.append(tile_grid)

# Draw a label for the private IP
text = str(priv_ip)
text_area = label.Label(terminalio.FONT, text=text, color=0xFFFFFF, x=35, y=80)
group.append(text_area)

# Draw a label for the external IP
text = ext_ip_address
text_area = label.Label(terminalio.FONT, text=text, color=0xFFFFFF, x=35, y=100)
group.append(text_area)

# Draw a text label
text = "Yggdrasil"
text_area = label.Label(terminalio.FONT, text=text, color=0xFFFFFF, x=40, y=120)
group.append(text_area)

display.root_group = group


# *** The following code is for the Azure IoT Central device ***
esp = None
pool = socketpool.SocketPool(wifi.radio)
device = IoTCentralDevice(
    pool, esp, os.getenv("id_scope"), os.getenv("device_id"), os.getenv("device_primary_key")
)

print("Connecting to Azure IoT Central...")
device.connect()

   
    

print("Connected to Azure IoT Central!")



while True:
    pass
```

### Behavior

    Fetching text from https://minip.no/
    x509-crt-bundle:PK verify failed with error FFFFBD70
    x509-crt-bundle:Failed to verify certificate
    Traceback (most recent call last):
      File "adafruit_connection_manager.py", line 271, in get_socket
    OSError: (-12288, 'MBEDTLS_ERR_X509_FATAL_ERROR')

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "code.py", line 80, in <module>
      File "adafruit_requests.py", line 591, in get
      File "adafruit_requests.py", line 525, in request
      File "adafruit_connection_manager.py", line 282, in get_socket
    RuntimeError: Error connecting socket: (-12288, 'MBEDTLS_ERR_X509_FATAL_ERROR')

### Description

SSL not working when importing Adafruit-azureiot on a rpPico W, I get this error when I try to reach a HTTPS-site. When I comment out "from adafruit_azureiot import IoTCentralDevice" and the code running it, it is working. It is also working if I get HTTP-site. 

Not a big problem for me since I can use HTTP, but might be a problem someone wants to look at, when I googled it I found very little.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #9174, or at least improves the situation somewhat.

Free up RAM on the Pico W build so that more networking can be done, by disabling `CIRCUITPY_USB_HOST` and `CIRCUITPY_PICODVI`. Note that `CIRCUIPY_PICODVI` off by default on many RP2040 boards.

It still seems to be the case that once a networking error happens, the co-processor or its supporting code may get into a bad state that requires a hard reset.

### CODE REVIEW

**Comment by dhalbert** [comment]
@bablokb @anecdata pinging for interest

**Review by anecdata — COMMENTED** [review]
**Config:**
`Adafruit CircuitPython 9.1.0-beta.3-16-g9601f4e58b on 2024-06-04; Raspberry Pi Pico W with rp2040`
`adafruit-circuitpython-bundle-9.x-mpy-20240604` (except for HTTP Server from [#88](https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/pull/88)):

<details>
<summary>Code...</summary>

```py
# HTTP[S] Server Test
# Pico W + W5100S hat

import time
time.sleep(3)  # wait for serial
import gc
print(f'{gc.mem_free()=}')

import os
import board
import digitalio
import ssl
import adafruit_connection_manager
import adafruit_httpserver
print(f'{gc.mem_free()=}')

PORT = 443
NATIVE = True
HTTPS = False

time.sleep(3)  # wait for serial

if NATIVE:
    import wifi
    
    print(f"cm={adafruit_connection_manager.__version__} h={adafruit_httpserver.__version__}")
    radio = wifi.radio
    radio.connect(os.getenv("WIFI_SSID"), os.getenv("WIFI_PASSWORD"))
    ipv4_address = str(radio.ipv4_address)
else:
    import busio
    from adafruit_wiznet5k import adafruit_wiznet5k
    from adafruit_wiznet5k.adafruit_wiznet5k import WIZNET5K
    
    print(f"cm={adafruit_connection_manager.__version__} w={adafruit_wiznet5k.__version__} h={adafruit_httpserver.__version__}")
    spi = busio.SPI(board.GP18, board.GP19, board.GP16)
    cs = digitalio.DigitalInOut(board.GP17)
    rst = digitalio.DigitalInOut(board.GP20)
    radio = WIZNET5K(spi, cs, reset=rst, mac='de:ad:be:ef:fe:cd')
    ipv4_address = radio.pretty_ip(radio.ip_address)

pool = adafruit_connection_manager.get_radio_socketpool(radio)
server = adafruit_httpserver.Server(
    pool,
    root_path="/static",
    https=HTTPS,
    certfile="cert.pem",
    keyfile="key.pem",
    debug=True,
)

@server.route("/")
def base(request: adafruit_httpserver.Request):
    gc.collect()
    return adafruit_httpserver.Response(request, f"Hello from {ipv4_address}:{PORT} {gc.mem_free()=}")

server.start(ipv4_address)
while True:
    try:
        poll_result = server.poll()
    except OSError as error:
        print(error)
```
</details>

**Results:**

Not quite enough for the HTTP Server library with TLS, but should give a good bit more headroom for more complex HTTP[S] client, HTTP Server, or socket-level projects.

PicoW HTTP Server:
71408 bytes free during each Response

WIZnet HTTP Server:
33328 bytes free during each Response

PicoW HTTPS Server:
`MemoryError: ` (in `poll`)

WIZnet HTTPS Server:
`MemoryError: memory allocation failed, allocating 2120 bytes` (in `poll`)

**Comment by tannewt** [comment]
How much do you gain by leaving PICODVI on? I could see it being useful for data display from wifi.

Does usb host work at all as-is?

**Comment by dhalbert** [comment]
`CIRCUITPY_USB_HOST` and `CIRCUITPY_PICODVI` both on (current settings `main`):
```
Memory region         Used Size  Region Size  %age Used
  FLASH_FIRMWARE:     1408412 B      1532 KB     89.78%
             RAM:      106772 B       256 KB     40.73%
```
Only CIRCUITPY_USB_HOST on:
```
  FLASH_FIRMWARE:     1397816 B      1532 KB     89.10%
             RAM:      103076 B       256 KB     39.32%
```
Only CIRCUITPY_PICODVI on:
```
  FLASH_FIRMWARE:     1379108 B      1532 KB     87.91%
             RAM:       93732 B       256 KB     35.76%
```
Both off (this PR):
```
  FLASH_FIRMWARE:     1368176 B      1532 KB     87.21%
             RAM:       90036 B       256 KB     34.35%
```
So `CIRCUITPY_USB_HOST` uses 3.7kB RAM even before instantiation and `CIRCUITPY_PICO_DVI` uses 13kB before instantiation.

So I'm inclined to turn them both off, especially `CIRCUITPY_PICO_DVI`.

>Does usb host work at all as-is?

I don't know at all, but I think using the Pico W for any reasonable-sized web work outweighs both of the above.

**Comment by tannewt** [comment]
How are the other boards with picow soldered down setup? I guess this is ok for picow because folks can use the pico build if they don't want wifi.

**Comment by dhalbert** [comment]
@tannewt
| Board | PICODVI  (off by default)| USB_HOST (on by default) | notes |
|--------|--------|--------|--------|
| cytron_edu_pico_w | + | + | lots of frozen modules, no display |
| pajenicko_picopad | + | - | gaming board with display |
| pimoroni_badger2040w | - | - | e-ink badge|
| pimoroni_inky_frame_5_7 | - | - | e-ink picture frame |
| pimoroni_inky_frame_7_3 | - | - | e-ink picture frame |
| pimoroni_pico_dv_base_w | + | + | point of board is DVI , non pico-W build available |
| pimoroni_plasma2040w | - | - | RGB LED driver |
| raspberry_pi_pico_w | + | + | current |

**Comment by bablokb** [comment]
> I guess this is ok for picow because folks can use the pico build if they don't want wifi.

@tannewt: I don't think so. The board led is wired differently. And VBUS and VSYS monitoring also are different.

**Pull request merged**
