### PR TITLE
nrf: implement audiobusio.PDMIn

### PR DESCRIPTION
**Pull request by jepler**
So far, this supports only 16kHz and 16-bit samples with a fixed gain. This is enough to support the basic functionality of e.g., sensing ambient sound levels.  Stereo support is coded but untested.

Testing performed:
 * all tests performed on Particle Xenon with PDM Mic Breakout
 * recorded and played back short samples (using PWM Audio Out)
 * adapted the "playground sound meter" program (using a NeoPixel stick board)

Additionally, @ladyada  reports "tested this and it works great on my CPB"

### CODE REVIEW

**Comment by ladyada** [comment]
yes indeed :)

**Comment by dhalbert** [comment]
:( failed, do `make translate` and re-push

**Comment by dhalbert** [comment]
aargh, conflicts, you'll have to merge from upstream, then `make translate`

**Comment by jepler** [comment]
I'll check back on this in the morning.

**Comment by dhalbert** [comment]
Bleh, still says "missing message ID". The `.po` files are very re-ordered: maybe the merge didn't work out that well. Also, what version of `xgettext` are you using? Mine is:
```
$ xgettext --version
xgettext (GNU gettext-tools) 0.19.8.1
...
```
```
Maybe take the content of `locale/*` wholesale from upstream, and then do
```
make translate
make check-translate
```
since it's `check-translate` that's failing.

@tannewt Maybe we should make `make check-translate` be part of what `make translate` does, instead of being a separate target. Also `tools/check-translations.py` could print out which message ids are missing, which might be a debugging clue.

**Comment by jepler** [comment]
I'm on debian stretch x86_64.  ```
jepler@babs:~$ xgettext --version
xgettext (GNU gettext-tools) 0.19.8.1
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by jepler** [comment]
@dhalbert thanks for cleaning up my mess!  I wish I knew at what step I made a mistake.  When I "make translate" at the tip of master, no errors, no grand reordering, and "check-translate" passes, so usually it works as expected.    I must have made a mistake due to being in a hurry.

**Comment by dhalbert** [comment]
I'm not sure what happened, but I think the simplest explanation is just that `make translate` didn't get done after the merge. No worries!

**Pull request merged**
