### PR TITLE
Coproc Module Enhancements 

### PR DESCRIPTION
**Pull request by MicroDev1**
Implements more checks and sleep support enhancement:
1. Check memory address range.
2. Check firmware size at an earlier stage.
3. Check coproc running status.
4. Add light and pretend-to-deep sleep support.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Don't see any particular issues. Since this is experimental I'll approve so people can try it.

**Comment by jepler** [comment]
While this PR says it checks the memory address range, it's trivial to HardFauilt CircuitPython using CoprocMemory. Here, the type pointer of a list object is nuked (since the id of an object is its location in memory)

Would it be possible to simply move the address range checking from the Coproc construction to the CoprocMemory construction?

```
Adafruit CircuitPython 8.0.0-beta.3-10-g773bb99c96-dirty on 2022-10-22; ESP32-S3-EYE with ESP32S3
>>> import coproc
>>> l = []
>>> c = coproc.CoprocMemory(id(l), 4)
>>> c[:] = b'\0' * 4
>>> l

[tio 15:00:53] Disconnected
[tio 15:01:01] Connected
Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Crash into the HardFault_Handler.
Please file an issue with the contents of your CIRCUITPY drive at 
https://github.com/adafruit/circuitpython/issues

Press any key to enter the REPL. Use CTRL-D to reload.
```

**Comment by jepler** [comment]
By the way, I'm planning on trying this module out soon (timeframe uncertain) to interface to an odd Atari keyboard that is a bit of a poor fit for both keypad and PIO, so I may have more questions & hopefully some more concrete & constructive feedback for you when that happens.

**Comment by MicroDev1** [comment]
> move the address range checking from the Coproc construction to the CoprocMemory construction

I'd prefer to disable direct construction of `CoprocMemory` from python side and move it to:
```python
Coproc(buffer, shared_mem_address, shared_mem_length)
```
Also, the access to memory can be limited and allowed only in the `run-to-halt` interval.

**Comment by jepler** [comment]
Anything that gets rid of the user constructing a CoprocMemory instance that can be used to hose the general RAM of the machine is good, as long as it doesn't remove capabilities.

Why can't it be allowed before run? For instance, in the LED blink example, you might want to pre-load the first blink interval before calling run.

By the way, I'm not sure about limiting the region to be read/written via CoprocMemory. For instance, in the LED blink example a compile-time default could be set by 
```
EXPORT uint8_t shared_mem[1024] = {10};
```
so that element 0 is initialized to 10. However, as I understand the restriction on CoprocMemory ranges, since this byte would have come from the buffer loaded by the Coproc constructor, it would not be usable for CoprocMemory.  Further, since symbol offsets are from the start of the memory block, addressing a symbol by its address from Python becomes more cumbersome because you would have to subtract the program length off of the variable address before access.

**Pull request merged**
