### PR TITLE
NXP LPC port backbone support

### PR DESCRIPTION
**Pull request by EmergReanimator**
Here is initial NXP LPC1768 and LPC55S28 support.
So far CPY NXP port has been tested on two boards: up and running on Keil MCB1700 and NXP LPCXpresso55S28 boards.
Serial interface, HAL digitalio and time modules are supported at current moment.

### CODE REVIEW

**Comment by dhalbert** [comment]
image

This is still out of sync with `adafruit/main`.

**Comment by dhalbert** [comment]
> @dhalbert I'll let you review but feel free to mention me if you want me to look too.

It sounds like you're quite familiar with the platform(s). Feel free to review! I'll be taking a look more at the internals, but I don't know the peripherals or HAL at all.

**Comment by hathach** [comment]
Just want to chime in for tinyuf2, currently the lpc55 bootloader size is set to 64KB for developing purpose with initial LOG. The actual size for bootlaoder for release should be 32 KB. I will make update for tinyuf2 shortly and post update here, just in case you guys using it for testing.

**Comment by EmergReanimator** [comment]
Dropping current PR because major changes in the NXP LPC integration has been performed recently. New PR is going to be issued.

**Pull request closed without merging**
