### PR TITLE
Add new board Maker Nano RP2040 to branch 7.1.x.

### PR DESCRIPTION
**Pull request by waiweng83**
Hi, I would like to add this board to v7.1.x.

https://www.cytron.io/maker-nano-rp2040-simplifying-projects-with-raspberry-pi-rp2040

It's already merged to the main in PR #5668

Thanks.

### CODE REVIEW

**Comment by waiweng83** [comment]
Should I be concerned about the test that failed?

**Comment by tannewt** [comment]
This build error is a bug in our tooling. I'll try and rerun your build. That may fix it.

**Comment by waiweng83** [comment]
> This build error is a bug in our tooling. I'll try and rerun your build. That may fix it.

Thanks. But looks like it's still failing.

**Comment by dhalbert** [comment]
@waiweng83 Could you try pushing an empty commit?
```sh
git commit --allow-empty -m "empty commit"
git push
```
That will reset the commit to merge against to the latest.

**Comment by waiweng83** [comment]
> @waiweng83 Could you try pushing an empty commit?
> 
> ```shell
> git commit --allow-empty -m "empty commit"
> git push
> ```
> 
> That will reset the commit to merge against to the latest.

Thanks.

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
