### PR TITLE
add stackrduino_m0_pro

### PR DESCRIPTION
**Pull request by StackRduino**
added stackrduino_m0_pro to build.yml and board files

### CODE REVIEW

**Review by StackRduino — COMMENTED** [review]
changed CFLAGS_INLINE_LIMIT = 55

**Review by StackRduino — COMMENTED** [review]
reduced to CFLAGS_INLINE_LIMIT = 35 for tranaslations

**Review by dhalbert — APPROVED** [review]
We may be able to remove some of the special-casing of certain translations now that we've switch to gcc10, which produces smaller builds, but we can get to that later.

**Comment by StackRduino** [comment]
> We may be able to remove some of the special-casing of certain translations now that we've switch to gcc10, which produces smaller builds, but we can get to that later.

That would be great. Thank you

**Pull request merged**
