### PR TITLE
 fix CPB SPI pin definitions

### LINKED ISSUE #3582: CPB default SPI pins incorrect
The pin definitions in mpconfigboard.h do not match those in pins.c

using board.SPI() will get the wrong pins.

https://github.com/adafruit/circuitpython/blob/main/ports/nrf/boards/circuitplayground_bluefruit/pins.c#L10
```
    { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_P0_02) },
    { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_P0_02) },
    { MP_ROM_QSTR(MP_QSTR_SCK),  MP_ROM_PTR(&pin_P0_02) },

    { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_P0_29) },
    { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_P0_29) },
    { MP_ROM_QSTR(MP_QSTR_MISO), MP_ROM_PTR(&pin_P0_29) },

    { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_P0_03) },
    { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_P0_03) },
    { MP_ROM_QSTR(MP_QSTR_MOSI), MP_ROM_PTR(&pin_P0_03) },
```

https://github.com/adafruit/circuitpython/blob/main/ports/nrf/boards/circuitplayground_bluefruit/mpconfigboard.h#L62
```
#define DEFAULT_SPI_BUS_SCK         (&pin_P0_05)
#define DEFAULT_SPI_BUS_MOSI        (&pin_P1_03)
#define DEFAULT_SPI_BUS_MISO        (&pin_P0_29)
```

SDA and SCK are in conflict
```
#define DEFAULT_I2C_BUS_SDA         (&pin_P0_05)

#define DEFAULT_SPI_BUS_SCK         (&pin_P0_05)
```

SCK should be P0_02
MOSI should be P0_03

I tried changing the definitions and now board.SPI() works -- I'll submit a PR.

### PR DESCRIPTION
**Pull request by jerryneedell**
fixes #3582 

tested on CPB with mini-tft featherwing.

### CODE REVIEW

**Comment by ladyada** [comment]
you dont by chance have a tft gizmo or eink gizmo?

**Comment by jerryneedell** [comment]
> you dont by chance have a tft gizmo or eink gizmo?

I have a tft-gizmo

**Comment by ladyada** [comment]
could you test with that too?cause thats what we use for SPI interfacing!

**Comment by jerryneedell** [comment]
> could you test with that too?cause thats what we use for SPI interfacing!

sure -- will do.

**Comment by jerryneedell** [comment]
@ladyada 
yikes! this will be a problem

the tft-GiZMO uses A3 for the backlight and uses SDA for MOSI ???



```
        self, *, spi=None, cs=board.RX, dc=board.TX, backlight=board.A3, rotation=180
    ):
        displayio.release_displays()
        if spi is None:
            import busio  # pylint: disable=import-outside-toplevel

            spi = busio.SPI(board.SCL, MOSI=board.SDA)
```

**Comment by jerryneedell** [comment]
> @ladyada
> yikes! this will be a problem
> 
> the tft-GiZMO uses A3 for the backlight and uses SDA for MOSI ???
> 
> ```
>         self, *, spi=None, cs=board.RX, dc=board.TX, backlight=board.A3, rotation=180
>     ):
>         displayio.release_displays()
>         if spi is None:
>             import busio  # pylint: disable=import-outside-toplevel
> 
>             spi = busio.SPI(board.SCL, MOSI=board.SDA)
> ```

ah -- but since it does not call board.SPI() it should be OK

**Comment by ladyada** [comment]
yeah we 'recycle' the I2C pins - to keep pin compatibilitiy with CPX!

**Comment by jerryneedell** [comment]
Testes on CPB with TFT gizmo -- no problems.

**Review by ladyada — DISMISSED** [review]

**Comment by jerryneedell** [comment]
FYI -- this came up in a forum question about using a mini-tft with the CPB. https://forums.adafruit.com/viewtopic.php?f=58&t=170634

**Comment by jerryneedell** [comment]
@jepler I assume this CI failure is the same as ones that have been occurring for the past few days. Anything I need to do about it?

**Comment by tannewt** [comment]
@jerryneedell Would you mind rebasing this onto 6.0.x? That way it'll be fixed for 6.0.0

**Comment by jerryneedell** [comment]
> @jerryneedell Would you mind rebasing this onto 6.0.x? That way it'll be fixed for 6.0.0

Sure -- How do I do that?

**Comment by jerryneedell** [comment]
> > @jerryneedell Would you mind rebasing this onto 6.0.x? That way it'll be fixed for 6.0.0
> 
> Sure -- How do I do that?

OK -- I think I did that correctly. If not, let me know.

**Comment by jerryneedell** [comment]
But why does it now have all these other changes associated with it?

**Comment by jerryneedell** [comment]
PR is corrupted -- closing and will resubmit

**Pull request closed without merging**
