### PR TITLE
Add support for VCC-GND Studio YD-RP2040

### PR DESCRIPTION
**Pull request by fabaff**
Add support for VCC-GND Studio YD-RP2040

- Details: http://152.32.187.208:8080/yd-data/YD-RP2040/
- Request for PID: not done, it's unknown how the manufacturer could be contacted

### CODE REVIEW

**Comment by tannewt** [comment]
Where did you purchase the board? Do we know if raspberry pi is ok requesting a PID on a manufacturer's behalf?

**Comment by fabaff** [comment]
I was able to get in touch with a human from VCC-GND Studio. The PID should be requested now.

**Comment by dhalbert** [comment]
Converting to draft until PID is updated.

**Comment by evildave666** [comment]
Should probably have the flash chips for the 4mb and 16mb versions of the board added to EXTERNAL_FLASH_DEVICES, although they both seem to function with just the 2mb chip defined.

**Comment by DerBroader71** [comment]
Same board is available from Estar Dyn shop https://www.aliexpress.com/item/1005004316882797.html but with different VID/PID 2E8A/0003 and in 4mb (W25Q32JVxQ)

**Comment by DerBroader71** [comment]
Looks like the PID has been assigned https://github.com/raspberrypi/usb-pid/commit/690a77c1e3061db7aa20557bd422ba0b707a190c

**Review by dhalbert — APPROVED** [review]
Thanks @DerBroader71 for finding the new PID and for testing the latest changes!

**Comment by dhalbert** [comment]
OOPS! Forgot to add files. Will make a new PR.

**Pull request merged**
