### PR TITLE
Fixes neopixel show() after deinit() not raising an exception

### LINKED ISSUE #4218: neopixel: calling show() after deinit() doesn't raise an exception
I was surprised at this:
```python
>>> n = neopixel.NeoPixel(board.GP0, 1, auto_write=False)
>>> n.deinit()
>>> n.show()
>>> 
```

Expected behavior: `n.show()` raises an exception since the related object has been deinitialized
Actual behavior: `n.show()` does not raise an exception

I only tested on Pico, so this may be a port-specific problem.  However, I didn't label it as such initially.

### PR DESCRIPTION
**Pull request by tammymakesthings**
Previously, the calling neopixel.show() after calling neopixel.deinit() would not raise an exception. Now it does.

Fixes #4218, but I'm not sure how to link them.

### CODE REVIEW

**Comment by anecdata** [comment]
oops, finger slipped, but there's a "Linked issues" setting in the right on the GitHub web page

**Comment by tammymakesthings** [comment]
@anecdata I see the Linked Issues panel on the right, but it doesn't appear to be editable by me. Quite possibly I'm doing something wrong, however. :-)

**Comment by dhalbert** [comment]
I edited your OP slightly to make it link. Here is the magic: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by tammymakesthings** [comment]
Thanks so much! I'm much more familiar with Microsoft's Azure Repos UI, and - well, I'm learning. :-)

**Comment by dhalbert** [comment]
Extra changes:

- `ru` translation failed on one SAMD21 board with external flash. Other builds were very close to overflowing. Disabled `atexit` and `getpass` for these SAMD21 `CIRCUITPY_FULL_BUILD` builds. This should give us some breathing room.
- `black` went to version 22.1.0 in the past few minutes, so pre-commit Pytyhon `black` checks were failing. Only issue was it wanted spaces around the `**` operator.

**Review by dhalbert — APPROVED** [review]
Thanks for catching this! And it provoked some other things we needed to as well.

**Pull request merged**
