### PR TITLE
Add M5Stack Core2

### PR DESCRIPTION
**Pull request by CDarius**
Add baord M5Stack [Core2](https://docs.m5stack.com/en/core/core2)

### CODE REVIEW

**Comment by dhalbert** [comment]
@CDarius could the AXP code just be written as a CircuitPython library? I don't know how low-level it needs to be. For instance, if a non-espressif board had an AXP192 attached, or the AXP192 were on a breakout, would you just want a library?

There are examples of port-specific modules, such as `samd` or `espulp`. Look in `ports/*/bindings`.

**Comment by CDarius** [comment]
@dhalbert Yes it could be written as CircuitPython python library, AXP192 is just an I2C device with some register that handler LDOs and GPIOs.
The AXP192 must be initialize at boot on M5Stack boards to make them work properly, is not optional. It's possible to achieve this with a CircuitPython library?

**Comment by dhalbert** [comment]
> The AXP192 must be initialize at boot on M5Stack boards to make them work properly,

Could you explain this in more detail? What makes that necessary compared with just initializing them in `code.py`?

**Comment by CDarius** [comment]
> Could you explain this in more detail? What makes that necessary compared with just initializing them in `code.py`?

The AXP192 is a power management IC, it handle the board power supply from different sources (battery, usb, m-bus) and power the different devices.

For example on Core2 the `board_init` intialize the onboard display but before initiliaze the display `board_init` need to power up the display via AXP192.
In addition to pwer up the on board devices AXP192 handle alse the on board battery charging. On power up AXP192 charge the battery with a 780mA current but this is too high on Stick C, it is mandatory to lower the charging current to 100mA.

For your reference the Core2 [schematics](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/schematic/Core/CORE2_V1.0_SCH.pdf)

**Comment by dhalbert** [comment]
Thanks, got it. So adjusting the power management in, say, `boot.py`, sounds like it would be a bad idea. It should be done properly, always on startup, because if it's not done, the battery could be charging at a dangerous level, etc. If you can refactor the common code for the AXP192 that would be more elegant and would make updating it easier if things change.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Pull request merged**
