### PR TITLE
Custom board build

### PR DESCRIPTION
**Pull request by MicroDev1**
You can now create a custom board build in your fork. 🐍🚀

### CODE REVIEW

**Comment by MicroDev1** [comment]
**Steps:** (See: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow)
1. Fork the `adafruit/circuitpython` repository.
2. Activate GitHub Actions in your fork.
3. Select "Custom board build" workflow.
4. Click on "Run workflow".
5. You will be presented with the following menu.

custom-board-build-menucustom-board-build-menu-dark

**Menu:**
- **Board:**
  - The `board_id` of the board to build.
  - Can be found in `ports/*/boards/[board_id]`
- **Version:**
  - The version of CircuitPython to build.
  - Can be a tag or a commit. Anything above https://github.com/adafruit/circuitpython/commit/c8a325a40b1755c7b193f4289e06ad2b0803e296 should work but `>=8.1.0` is better to communicate.
- **Language:**
  - The language of the build.
  - Can be found in `locale/[language].po`
- **Flags:**
  - The flags to use for the build.
  - Example: `CIRUITPY_WIFI=1`.
- **Debug:**
  - Whether or not to make a debug build.
  - Check the box to make a debug build.

The resulting build command executed in the port directory:
```python
make -j2 $FLAGS BOARD=... DEBUG=... TRANSLATION=...
```

The generated `build-*/firmware.*` files will be available as an artifact.

> **Note**
> The firmware version will have `-dirty` appended to it if the flags are provided or it is a debug build.

**Comment by MicroDev1** [comment]
custom-board-buildcustom-board-build-dark

**Comment by MicroDev1** [comment]
Related to #4552.

**Comment by dhalbert** [comment]
Also fixes `main` merge builds not being uploaded to AWS S3. (per discord discussion)

**Pull request merged**
