### PR TITLE
add port-specific modules to support matrix

### LINKED ISSUE #7555: port-specific modules not included in module support matrix
`espcamera` is not in the module support matrix, though it is turned on for a number of boards (e.g. Metro ESP32-S2). This may be due to its not being in `shared-bindings`, but in `ports/espressif/bindings`. That may be special-cased?

There are other missing modules, like `samd` and `rp2pio`.

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #7555.

Also ran  `docs/shared_bindings_matrix.py` through `black`.

### CODE REVIEW

**Comment by Neradoc** [comment]
When trying to test it locally, I get an error because the content is empty when trying to retrieve the previous files.json.
```py
❯ RELEASE_TAG=8.0.0 DEBUG=1 python build_board_info.py
Not logged in
Traceback (most recent call last):
  File "/Volumes/circuitpython-dev/repositories/test-pr/tools/build_board_info.py", line 268, in <module>
    generate_download_info()
  File "/Volumes/circuitpython-dev/repositories/test-pr/tools/build_board_info.py", line 207, in generate_download_info
    git_info, current_info = get_current_info()
  File "/Volumes/circuitpython-dev/repositories/test-pr/tools/build_board_info.py", line 103, in get_current_info
    current_list = json.loads(base64.b64decode(response["content"]).decode("utf-8"))
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I believe the reason is that the file is now above 1MB:
https://docs.github.com/en/rest/repos/contents#size-limits

> Between 1-100 MB: Only the raw or object custom media types are supported. Both will work as normal, except that when using the object media type, the content field will be an empty string and the encoding field will be "none". To get the contents of these larger files, use the raw media type.

Calling it like this retrieves just the file, but not the associated sha:
```py
    response = github.get(
        "/repos/adafruit/circuitpython-org/contents/_data/files.json?ref=" + commit_sha,
        headers={"Accept": "application/vnd.github.raw+json"}
    )
```
Or we can retrieve the file if the content field is empty:
```py
    if response["content"] != "":
        # if the file is there
        current_list = json.loads(base64.b64decode(response["content"]).decode("utf-8"))
    else:
        # if too big, the file is not included
        download_url = response["download_url"]
        response = requests.get(download_url)
        if not response.ok:
            print(response.text)
            raise RuntimeError("cannot get previous files.json")
        current_list = response.json()
```
With that, the PR does as expected.

**Comment by dhalbert** [comment]
The problem @Neradoc observed is now happening even before this PR is merged:
https://github.com/adafruit/circuitpython/actions/runs/4421756938/jobs/7752932114#step:8:1
This is on my 8.0.4 release.

**Comment by dhalbert** [comment]
@Neradoc I tried both of the above patches to `build_board_info.py` by hand, but the problem I encountered is that I need `response["sha"]`, and neither gets that. However, I may have done something wrong. Could you show me your patched `build_board_info.py`.

**Comment by Neradoc** [comment]
Here it is:
https://github.com/adafruit/circuitpython/compare/8.0.x...Neradoc:get-files-json-when-big

**Review by microdev1 — APPROVED** [review]
LGTM! Thanks, @dhalbert and @Neradoc.

**Pull request merged**
