### PR TITLE
Added support for the Waveshare Touch LCD 1.28

### PR DESCRIPTION
**Pull request by minordemon**
I have created a copy of the Waveshare RP2040 LCD 1.28, because the Waveshare RP2040 Touch LCD 1.28 has the LCD Reset pin on GP13 instead of GP12.

It is not a very advanced port. I'll try and add the initialization for the display next. (But the one I copied doesn't have initialization either).

Next steps would be:
- Display initialization
- Adding touch pins
- Add initialization for other modules (like touch, and accelerometer)

Reference:
https://www.waveshare.com/wiki/RP2040-Touch-LCD-1.28

### CODE REVIEW

**Comment by minordemon** [comment]
Changed the title to make the pull request more clear.

**Review by tannewt — COMMENTED** [review]
Which is the original board? Totally fine to have another for a slightly different board.

**Comment by tannewt** [comment]
Ah, I see. This has "Touch" in the name.

**Review by tannewt — APPROVED** [review]
Thank you! Looks good

**Pull request merged**
