### PR TITLE
Update WaveShare ESP32s2-Pico pins

### PR DESCRIPTION
**Pull request by bill88t**
I had done some major oofs in the pins.c, hopefully it's good now.
[Link](https://www.waveshare.com/w/upload/3/35/ESP32-S2-Pico_Sch.pdf) to ws schematic for anyone who wishes to check.

### CODE REVIEW

**Comment by dhalbert** [comment]
I am really confused by your pin renaming in this PR. Consider, say, GP34. It's labeled as GP34 on the silkscreen and in the pin diagram.
: https://www.waveshare.com/wiki/ESP32-S2-Pico#/media/File:ESP32-S2-Pico-details-9-2.jpg
image

The schematic shows it connected to GPIO34 (chip pin 38):
image

The ESP32-S2 datasheet shows:
image

So why is it now `pin_GPIO8` in `pins.c`?

**Comment by bill88t** [comment]
To my understanding:
ESP pin 38 is "internally" named GP34, but then connected to a line named GPIO34, and that line goes to board's pin 19?
image

I will (prolly) tonight go solder some headers finally and test it

**Comment by bill88t** [comment]
Ah wait nvm the pins on the pic are uhh.....
Yea, I'll fix it.

**Comment by dhalbert** [comment]
We generally recommend going by the silkscreen names - that is best for users without schematics, etc. We don't usually go by consecutive pins numbers around the edges if there are silkscreen numbers or names.

**Comment by bill88t** [comment]
Now that I unfliped it in my head, all the pins make sense and match with the silkscreen.

**Comment by bill88t** [comment]
Yea, didn't notice it's the same, sorry for wasting your time. Closing it.

**Comment by bill88t** [comment]
Yea actually this pr was fixing IO39 too.. and I deleted the commits.. so new pr..

**Pull request closed without merging**
