### PR TITLE
Create zh.po

### PR DESCRIPTION
**Pull request by hexthat**
Chinese-Hanyu Pinyin

### CODE REVIEW

**Comment by hexthat** [comment]
I'm not sure where you want "zh_Latn_pinyin", do you mean the file should be called "zh_Latn_pinyin.po"?

I think it is ready to merg.

**Comment by tannewt** [comment]
@hexthat yup I meant the filename. Both versions were ok to have although I know the simplified chinese won't work with the displayio terminal due to the font size.

**Comment by tannewt** [comment]
Did you find a font that works for pinyin as well? I think I'll need to add a way to change the font for a language but it shouldn't be too hard.

**Comment by hexthat** [comment]
I made this font by editing the default.

[ter-u12n.zip](https://github.com/adafruit/circuitpython/files/3061393/ter-u12n.zip)

**Comment by tannewt** [comment]
@hexthat Nice! Can you include the updated font in a new directory under tools and hook it in? That should fix the build. Thanks!

**Comment by hexthat** [comment]
@tannewt I don't know how to do that. Is that in the CP github [guide](https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github/overview)? I'm working on Japanese Romaji translate currently.

**Comment by tannewt** [comment]
Closing in favor of #1788

**Pull request closed without merging**
