### PR TITLE
Update frozen libraries

### PR DESCRIPTION
**Pull request by makermelissa**
This pulls in the latest frozen libraries. The main one I need updated was PortalBase, but thought I'd update the others as well.

### CODE REVIEW

**Comment by dhalbert** [comment]
> I was thinking 8.0.0 branch, but this could probably be applied to the 7.3.x branch as well.

I have to make a new release for 7.3.x to get the update. Is there a particular fix you want people to have?

**Comment by dhalbert** [comment]
Did you use `make update-frozen-libraries` at the top level? Usually I do this just before a release, but we will probably not make a release until early next week.

**Comment by makermelissa** [comment]
> Did you use `make update-frozen-libraries` at the top level? Usually I do this just before a release, but we will probably not make a release until early next week.

Yep, that's exactly what I did. We can close this if you'd rather wait until just prior to release.

**Comment by makermelissa** [comment]
> I have to make a new release for 7.3.x to get the update. Is there a particular fix you want people to have?

Nothing major. It just updates the status lights to be consistent with the documentation.

**Comment by dhalbert** [comment]
OK, thanks, let's wait. We'll definitely do it before the next beta release so we get the absolute latest libraries.

**Pull request closed without merging**
