### PR TITLE
Blit swap bytes

### PR DESCRIPTION
**Pull request by FoamyGuy**
This adds a new argument `swap_bytes` to `bitmaptools.blit()` which lets the caller indicate they want to perform a byte-swap on  565 color values as they are blitted. 

This allows you to blit from a source rgb888 Bitmap that came from a .bmp file (which will be using a ColorConverter to get into 565 colorspace) into a destination Bitmap that was populated by JpegDecoder from a .jpg file (which uses 565_Swapped colorspace) and have the resulting combined image look correct.

More generally it means if you have an destination Bitmap that uses the 565_Swapped Colorspace, with this change you'll be able to successfully blit data from the 565 (non-swapped) Colorspace into it by setting this argument to `True`

### CODE REVIEW

**Comment by jepler** [comment]
You mention rgb888, but the code you've written doesn't seem to convert from rgb888 to rgb565, whether swapped or not. It does convert color numbers of the form 0xPPQQRRSS to 0xPPQQSSRR, which would change between rgb565 and rgb565_swapped (in which case P and Q are both 0). If the value is actually an rgb888 value, then it would convert it to an rbg888 value.

Perhaps instead of the explicit bit operations you can just use `__builtin_bswap16`, which we use elsewhere. This can use the ARM instruction "rev16". I made a simple mock-up of this code and `__builtin_bswap16` generates shorter (& probably faster) code: https://godbolt.org/z/v488GTP4j (but also swaps the top bytes to 0xQQPPSSRR so the effect on >16 bit color values is different)

Please add a test of this functionality.

There are some "non sensibly spelled" ways to convert a whole bitmap between rgb565 and rgb565_swapped now. One is:
```
import ulab as np
arr = np.frombuffer(bitmap, dtype=np.uint16)
arr.byteswap(inplace=True)     
```

**Comment by dhalbert** [comment]
> This allows you to blit from a source rgb888 Bitmap that came from a .bmp file (which will be using a ColorConverter to get into 565 colorspace)

Could you use the `ColorConverter` to get into 565-swapped space directly? (I'm not very familiar with this stuff, so apologies if I am missing something.)

**Comment by FoamyGuy** [comment]
> You mention rgb888, but the code you've written doesn't seem to convert from rgb888 to rgb565, whether swapped or not.

The original source .bmp file is RGB888 here are the files I used [source_test_bmps.zip](https://github.com/adafruit/circuitpython/files/14284019/source_test_bmps.zip)

I tried using RGB565 directly in those .bmp files but I was unable to get them to load with adafruit_imageload successfully with that format. When the RGB888 .bmp source file is loaded a ColorConverter() is used with adafruit_imageload like this:
```
frame_bmp, _ = adafruit_imageload.load("med64_rgb888.bmp", palette=ColorConverter(input_colorspace=displayio.Colorspace.RGB888))
```

This makes it so that when other code accesses the pixels within the bitmap like `frame_bmp[10,10]` they will "see" the converted RGB565 representations of the color rather than the RGB888 ones that are actually in the file.


Thank you for the suggestions of `__builtin_bswap16` and np `arr.byteswap` I think the latter might offer a solution for my use-case without needing this (or any) core modifications. I'll close if if that turns out to be the case when I test. 

If the ulab method doesn't work for some reason I'll look into `__builtin_bswap16` and change this code to use that instead of a new function.


> Could you use the ColorConverter to get into 565-swapped space directly? 

To the best of my knowledge currently ColorConverter only supports converting _to_ 565 standard. It can convert _from_ a handful of other colorspaces, but always converts _to_ 565 standard. I did consider trying to add  `output_colorspace` selection functionality to it, and I do think that may still be a worthwhile addition some day, but I ended up with this solution which felt like a more manageable sized change for my current abilities.

**Comment by jepler** [comment]
OK, I now understand -- the ColorConverter is involved in the imageload step and not in the blit step.

**Comment by FoamyGuy** [comment]
This is indeed unnecessary for my use-case. The numpy code works and serves the same purpose, thanks again @jepler!

**Comment by jepler** [comment]
glad I could help!

**Pull request closed without merging**
