### PR TITLE
Change reference of "libraries" to "classes

### LINKED ISSUE #2095: Remove reference to "libraries", consider replacing with "classes"
Documentation refers to classes as libraries here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/audiobusio/__init__.html

Likely worth verifying this is not also the case elsewhere.

### PR DESCRIPTION
**Pull request by tekktrik**
Resolves #2095 by changing "libraries" to "classes"

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Could you double check that this isn't written elsewhere? I suspect I copy and pasted this many places. Thanks!

**Comment by tekktrik** [comment]
Will do!

**Comment by tekktrik** [comment]
After a search, this was the only place in `shared-bindings` and `shared-module` that used "libraries" where it should have used "classes"!

**Review by tannewt — APPROVED** [review]
Huh, that surprises me. Thanks for checking!

**Pull request merged**
