### PR TITLE
do background tasks and handle interrupt during boundary fill

### LINKED ISSUE #7485: bitmaptools.boundary_fill() should do background processing
I landed here after having some freeze problems. Just keeping this here for future reference and in case somebody gets to the same point as myself.
When I tried the following modified code,  the communication was lost and the editor (MU) and became unresponsive. 
I did the same using TIO and Screen command in ubuntu causing disconnection problems. After a while the code will show the expected result, however the communication is lost with the board. This is a little problem, but if people is impatient as I am, the board will get in safe mode very easily :)

```python
import board
import displayio
import bitmaptools

display = board.DISPLAY

bitmap = displayio.Bitmap(display.width, display.height, 3)

palette = displayio.Palette(3)
palette[0] = 0x000000
palette[1] = 0xffffff
palette[2] = 0x0000ff

tile_grid = displayio.TileGrid(bitmap, pixel_shader=palette)
group = displayio.Group()
group.append(tile_grid)
display.show(group)

# Draw a rectangle
for x in range(150, 170):
    bitmap[x, 30] = 1
    bitmap[x, 50] = 1
for y in range(30, 51):
    bitmap[150, y] = 1
    bitmap[170, y] = 1

# Draw a non-rectangle
for i in range(30, 120):
    bitmap[i, i] = 1
    bitmap[i+30, i] = 1

for x in range(0, 30):
    bitmap[x+30, 30] = 1
    bitmap[x+120, 120] = 1

# fill rectangle white
bitmaptools.boundary_fill(bitmap,display.width//2, display.height//2, 1, 0)

# fill non-rectangle blue
bitmaptools.boundary_fill(bitmap,40, 35, 2, 0)

while True:
    pass
```

### RESULTS

* Screen
```
home@home:~$ screen /dev/ttyACM0 115200
[screen is terminating]
home@home:~$ 
```

* TIO
```
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; Adafruit PyPortal Titano with samd51j20
>>> import q
[tio 19:51:52] Disconnected
[tio 19:52:33] Connected
🐍REPL | 8.0.0-beta.6

```

Tested on `Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; Adafruit PyPortal Titano with samd51j20`

_Originally posted by @jposada202020 in https://github.com/adafruit/circuitpython/issues/5145#issuecomment-1401227189_

### PR DESCRIPTION
**Pull request by FoamyGuy**
attempt to resolve #7485 

Added code to run background tasks and bail if interrupted.

Tested successfully on PyPortal Titano with the reproducer code in the issue. 

This resolves the problem of getting "stuck" during the fill, but the underlying crux is that boundary_fill is fairly slow for filling large spaces. The current implementation is based on this https://en.wikipedia.org/wiki/Flood_fill#Moving_the_recursion_into_a_data_structure There some other more efficient algorithms discussed further down on that page. Perhaps there is some performance to gain using one of those implementations instead, probably still on the slower side for large spaces on some devices, but maybe better than current version.

### CODE REVIEW

**Review by gamblor21 — COMMENTED** [review]
The code looks good to me, my only thought is have you looked at performance? If  you are checking every loop that may have an effect on speed more then intended.

**Comment by FoamyGuy** [comment]
I'm not sure why the unix port build is failing. It reports this error:
```
../../shared-module/bitmaptools/__init__.c: In function ‘common_hal_bitmaptools_boundary_fill’:
../../shared-module/bitmaptools/__init__.c:380:9: error: ‘RUN_BACKGROUND_TASKS’ undeclared (first use in this function)
  380 |         RUN_BACKGROUND_TASKS;
      |         ^~~~~~~~~~~~~~~~~~~~
```

Which seems like perhaps there is a missing `#include` that is needed. But I'm not sure which one if that is the case. Atmel and Esspressif ports do build successfully for me locally. 

I found the command to build the unix port locally and I see the same error as in the actions.

It seems like `RUN_BACKGROUND_TASKS` is defined in `py/circuitpy_mpconfig.h` so I tired adding this:
```
#include "py/circuitpy_mpconfig.h"
```

but it results in this error:
```
In file included from ../../shared-module/bitmaptools/__init__.c:37:
../../py/circuitpy_mpconfig.h:221:10: fatal error: mpconfigboard.h: No such file or directory
  221 | #include "mpconfigboard.h"
      |          ^~~~~~~~~~~~~~~~~
```

I'm not not sure that would have been a correct solution anyway though because other usages of `RUN_BACKGROUND_TASKS;`  in other places do not have that import and seem to be working fine without it.

**Comment by dhalbert** [comment]
Looking at other `shared-module/` examples with `RUN_BACKGROUND_TASKS`, try
```c
#include "py/runtime.h"
```

**Comment by FoamyGuy** [comment]
It's got `py/runtime.h`  include already here: https://github.com/adafruit/circuitpython/blob/0ca6cc7741103ced6e2c35fb3d7da708fb030d7f/shared-module/bitmaptools/__init__.c#L34

Could it need a different order or something more specific to the function where it's used?

**Comment by dhalbert** [comment]
Order shouldn't matter, but I'm wondering if the unix port is not compiling the other files with `RUN_BACKGROUND_TASKS`. The most likely one to be compiled is `shared-module/os/__init__.c`. You can try putting an `#error` in that file and see whether it gets hit when you do the unix port compile. if it does get compiled, then check what that includes and how, and try to replicate.

**Comment by FoamyGuy** [comment]
Ahh, it looks like you are correct on that. 

I added `#error` inside of `shared-module/os/__init__.c` and it does not stop the unix build from completing (if I remove the RUN_BACKGROUND_TASKS stuff that the PR is adding). So it seems unix port doesn't build that file.

**Comment by FoamyGuy** [comment]
I'm not really sure how to move this forward. I'm guessing it comes down to two high level options:
- Make the Unix port have access to `RUN_BACKGROUND_TASKS` as the other builds do. That should allow it to successfully complete the build
- Make the Unix port not compile bitmaptools so that it won't have a problem with the fact that it doesn't have access to `RUN_BACKGROUND_TASKS`

I don't really know how to do either of those, or which would be preferred.

I guessed that the latter would be possible by modifying a .mk file somewhere to disable bitmaptools, and I made an attempt at doing that but was unsuccessful. I tried adding `CIRCUITPY_BITMAPTOOLS = 0` here: https://github.com/adafruit/circuitpython/blob/bca7d6e99933ef77af7cb29e5cb8c25d735051e1/ports/unix/mpconfigport.mk#L42 but it didn't seem to have any effect when building the unix port the same way the actions do.

I also tried setting this to `0` https://github.com/adafruit/circuitpython/blob/bca7d6e99933ef77af7cb29e5cb8c25d735051e1/ports/unix/variants/coverage/mpconfigvariant.mk#L55 but same thing with that, doesn't seem to have any effect, build still fails due to `RUN_BACKGROUND_TASKS` undeclared.

**Comment by tannewt** [comment]
How about adding `#define RUN_BACKGROUND_TASKS ` to `mpconfigport.h` so that it gets replaced with nothing?

**Review by dhalbert — APPROVED** [review]
The code looks fine. Do you see any kind of noticeable performance degradation that might make it worthwhile to run the background tasks only sometimes around the loop?

**Pull request merged**
