### PR TITLE
8.2.x backport picopad by @lynt-smitka

### PR DESCRIPTION
**Pull request by dglaude**
All credit to @lynt-smitka for adding the support for PicoPad to main, but the release of 9.0 might be very far, and waiting for that it is confusing end-user to get the right firmware, having to pick one in the S3. The board is targetted at education, so making this as smooth as possible is important.

PicoPad support was not picked up in the recent 8.2.3 release.
This is an attempt at cherry-picking the thing (my first backporting, so I hope this preserve the credit) and could be included in the next 8.2.4, that would be great.

### CODE REVIEW

**Comment by dglaude** [comment]
I took an UF2 from the artifacts, it boot and run complex piece of code provided by @lynt-smitka that use the wifi network, ntp and display internal temperature on the screen.
So it "Works for Me."

**Review by jepler — APPROVED** [review]
This looks like it has an extremely low chance of causing any problems, and as you point out it'll be beneficial for those with the boards.

**Comment by lynt-smitka** [comment]
Yes, it would be great to have proper download options for PicoPad users. 😊 

I'm putting up a beginner's tutorials on how to get started with CircuitPython and PicoPad, and it will come in handy.

**Comment by dglaude** [comment]
@lynt-smitka if you could give a try to the artefact and confirm it also works for you, it will be easier for reviewers without the hardware to accept this PR.

PS: I believe Adafruit will want to make an 8.2.4 release soon that makes the new Metro ESP32S3 more accessible. Both PicoPad and that metro are the only recent board I could find without an easy download. I don't see the backport, but I have identified the four PR needed, I even feel like proposing one myself, but I don't have the hardware.

**Comment by lynt-smitka** [comment]
Tried and everyhting works fine 👍

**Pull request merged**
