### PR TITLE
Enable deep sleep on all ESP chips

### LINKED ISSUE #9056: Deep Sleep / Alarm module for ESP32-C6 ('alarm' module not found)
It would be lovely to have deep sleep available on all the chips that can support it. I'm running the esp32-c6-devkitM-1 build from downloads (rc1)

### PR DESCRIPTION
**Pull request by tannewt**
Features of each chip is documented in this spreadsheet: https://docs.google.com/spreadsheets/d/1NyKzHOWeWMb8UttDDugeeOANZ4m-idMHM6kiTlUUVIg/edit?usp=sharing

Fixes #9056

### CODE REVIEW

**Comment by tannewt** [comment]
This CI will need https://github.com/adafruit/circuitpython/pull/9325. I didn't realize esp_sleep_enable_ext1_wakeup_io was introduced in 5.2.2.

**Comment by tannewt** [comment]
Tested on Feather ESP32-S3 No PSRAM and it works. (I thought it didn't because I hadn't set pull.)

**Review by dhalbert — APPROVED** [review]
Thanks for fixing this, and doing the detailed differences between the chips. This might be docuumented in shared-bindings in a **Limitations:** section, but we don't have to do that now.

**Comment by linuxhuskarl** [comment]
Hey, I am currently trying to get XIAO ESP32C3 board to go into deep sleep. I don't fully understand why `alarm` is unavailable for its port. This PR explicitly says that all ESP boards should have it available. I think most ESP32C3 ports don't have it. See for example my board:

https://circuitpython.org/board/seeed_xiao_esp32c3/

`alarm` module is unavailable for both CirPy v9 and v10.

Can you help me understand the issue?

**Comment by Neradoc** [comment]
Hi, it's disabled by default on some boards with 4MB of flash or less, but will be added in Circuitpython 10 once we change the partition scheme (which will be relatively painless on C3 boards if you are used to save your files before updating Circuitpython with esptool).
https://github.com/adafruit/circuitpython/blob/ad73d0bc8eea469c852f4f088931d8bbb6c49e7a/ports/espressif/mpconfigport.mk#L280-L288

**Comment by linuxhuskarl** [comment]
Hey, thanks for the quick response!

> Hi, it's disabled by default on some boards with 4MB of flash or less, but will be added in Circuitpython 10 once we change the partition scheme 

Is there a ETA for this?

> Currently building with it would require modifying this file and disabling other modules to make some space.

I will look into that in the meantime. Thanks for the suggestion!

**Comment by dhalbert** [comment]
> Is there a ETA for this?

We don't give ETA's but it's actively being worked on. We need new bootloaders first.

**Pull request merged**
