### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/circuitpython/main/) for CircuitPython/main.

### CODE REVIEW

**Comment by jepler** [comment]
Remember when we found huge amount of spare storage for M0s?  Looks like the ja translation takes that all back and more.

**Comment by tannewt** [comment]
Should we modify the compression code to support literals for when the compression is longer than the original?

**Comment by jepler** [comment]
I think the "compression increased length" message is inaccurate.  It is comparing the length in Unicode code points to the length in bytes of the compressed string.

so for example, consider this one:
```
Note: compression increased length '演算子がサポートしていない型' 14 18
len(utf8) = 42 len(utf16) = 28
```
The length in code points is 14, the compressed length in bytes is 18, but it's MUCH less than the length in UTF-8 encoding of 42 bytes, or in UTF-16 encoding of 28 bytes.

**Comment by jepler** [comment]
A "literal" compression could compress each unicode code point into a ceil(log2 |values|) bit number, so that's probably the "best" comparison.  By that measure, only 3 of the ja strings in circuitbrains_basic_m0 have their length increased by compression.  For example:
```
Note: compression increased length 'インデントの解除が、外側のどのインデントレベルにも一致しません' 31 35
len(unicode) = 31
len(utf8) = 93
len(utf16) = 62
len() * log2 |values| = 35
```
Since you have to pay 1 bit per message to indicate whether you're using literal or huffman for the particular message, the ~64 bits from increased-length messages probably don't pay for themselves -- there are many more than 64 messages.

I dusted off the "digram compression" branch again, but ja doesn't benefit much from it, either.

**Pull request merged**
