### PR TITLE
slim down thunderpack v12 more

### PR DESCRIPTION
**Pull request by imnotjames**
drops ulab from the thunderpack v12 to drastically reduce the flash usage

### CODE REVIEW

**Comment by imnotjames** [comment]
This is to fix the failure in #8647

**Review by dhalbert — APPROVED** [review]

**Comment by dhalbert** [comment]
Add this change to #8647 instead, so we don't have to do two full builds.

**Comment by imnotjames** [comment]
> Add this change to #8647 instead, so we don't have to do two full builds.

Sure - wasn't sure the approach that should be done for this & how it would affect rollbacks.

**Comment by dhalbert** [comment]
> Sure - wasn't sure the approach that should be done for this & how it would affect rollbacks.

This is minor enough that it's fine. We have often had to slim down multiple builds in the past when new features are added.

**Comment by imnotjames** [comment]
Done - closing in favor of including this fully within #8647

**Pull request closed without merging**
