### PR TITLE
Include pulseio only on CIRCUITPY_FULL_BUILD

### PR DESCRIPTION
**Pull request by dhalbert**
`PWMOut` is no longer in `pulseio` as of 7.0.0. `pulseio` is still large, and we cannot make dynamic USB descriptors and some other new things fit on smaller boards without removing something larger.

I am only removing `pulseio` from non-`CIRCUITPY_FULL_BUILD` boards. So it will remain on CPX, which has IR transmit and receive. I hope dynamic USB and the other new things will then fit. `pulseio` could be restored on some other boards if I have forgotten its utility on them.

(I was thinking at first of dropping it from all SAMD21 boards, but that is not right for CPX.)

I think this should make more than enough room. I think this is a tradeoff we have to make for 7.0.0.

### CODE REVIEW

**Comment by jerryneedell** [comment]
Can  pulseio be left in the pirkey_m0 build? It has irremote frozen  in which requires pusleio.  Or is it time to drop support for the pirkey_m0 completely?

**Comment by deshipu** [comment]
We can enable pulseio on the pirkey explicitly.

**Comment by dhalbert** [comment]
> Can pulseio be restored to the pirkey_m0 build? It has irremote frozen in which requires pusleio. Or is it time to drop support for the pirkey_m0 completely?

Yes,thanks,  I meant to do that but forgot that it was not enabled explicitly already. Pushed a new commit.

**Comment by ladyada** [comment]
pirkey_m0 wasnt supposed to be shipped - it can barely do anything. it will be redesigned as an "IR trinkey" with RP2040 which will make pirkey 'usable' :) so we can drop it completely.

**Comment by jerryneedell** [comment]
The pirkey_m0 is not "completely" useless, but it is a challenge. I managed to get a couple when they were briefly available from Digi-key. The only thing I've used it for is as a simple 2FA helper. I store my GitHub key on it and have it send it when I push a button on my ir-remote. It works but I have no objection to support for it being dropped. I've already replace it with a new-trinky so I can send the 2FA key by touching the trinket and the new rp2040 version sounds much better. It was was fun to play with, but happy to move on.

**Comment by dhalbert** [comment]
When this gets merged, it should fix many of the broken builds in #4689 (dynamic USB).

**Review by ladyada — APPROVED** [review]

**Pull request merged**
