### PR TITLE
RP2040 longint support

### PR DESCRIPTION
**Pull request by DavePutz**
Memory is sufficient on the RP2040 for longint support. My build for the raspberry_pi_pico went from 499040 bytes to 512380 bytes used, leaving 536196 free.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks! It might have just been an oversight. Will merge after a good build.

**Comment by tannewt** [comment]
Can you enable it at the port level instead of board? We should be able to assume we can fit it since they always use external flash.

**Comment by dhalbert** [comment]
@tannewt Could you smoke-test this when the build finishes? Thanks.

**Comment by dhalbert** [comment]
I moved the setting to mpconfigport.mk

**Comment by ladyada** [comment]
tested on hardware

```
>>> print(0x1000000)
16777216
>>> print(0x10000000000)
1099511627776
>>> print(0x10000000000000000000000)
309485009821345068724781056
```

**Review by ladyada — APPROVED** [review]
>>> print(0x1000000)
16777216
>>> print(0x10000000000)
1099511627776
>>> print(0x10000000000000000000000)
309485009821345068724781056

**Pull request merged**
