### PR TITLE
Pixelbuf: Add support for 2D pixelbufs

### PR DESCRIPTION
**Pull request by jepler**
I'm not sure we necessarily want to take this code, I wrote it while prototyping protomatter, using pixelbuf to hold the framebuffer.

It was useful to be able to index the pixels with (row,column) pairs.  However, this is probably not the direction we're going to go with protomatter as we'd like to run it with displayio instead.

### CODE REVIEW

**Comment by ladyada** [comment]
could this be useful for stuff like
https://www.adafruit.com/product/1487
?

**Comment by jepler** [comment]
@ladyada yeah it sure might be

**Comment by jepler** [comment]
The "565-format" part would not be relevant, that's purely for protomatter

**Comment by jepler** [comment]
@ladyada any interest in seeing me pursue this in the near term?  If not I'll go ahead and close it up without merging.  It's not going to be relevant to protomatter or other framebuffer displays.

**Pull request closed without merging**
