### PR TITLE
build: Update to gcc10

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by dhalbert** [comment]
Dec 11, 2020 release is now 10.2: 
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by dhalbert** [comment]
The SAMD51 builds I think that use `-O2` are all much too large now, so I think they will need to be rolled back to `-Os`. There is some improvement on at least some of the `-Os` builds. For example `qtpy_m0` `de_DE` had 196 bytes free and now has 692.

**Comment by dhalbert** [comment]
As of gcc 10: _-finline-functions is now enabled at -O2_ (https://gcc.gnu.org/gcc-10/changes.html). This may explain the large growth of `-O2` compiles.

**Comment by dhalbert** [comment]
This is now working on all builds. @tannewt and @jepler I am OK with going to gcc 10 for `main` now, if you are. Thanks Jeff for the joint work on all the issues this brought up.

**Comment by dhalbert** [comment]
@hierophect Take note too. This will not affect the ESP32-S2 builds, since they have their own toolchain, but the STM builds would change.

**Comment by hierophect** [comment]
@dhalbert noted. What steps in particular are required? I assume I'll want to go back into my notes to reinstall the toolchain, and are all the makefiles changing as well? A list of upgrade steps might be beneficial to all.

**Comment by jerryneedell** [comment]
FYI -- for the Raspberry Pi aficionados, I am compiling a toolchain for the Raspberry Pi -- takes about 8 hours -- it's 4 hours not it ... if it succeed,,  I'll make it available as I have in the past. Hopefully soon after it is merged into main and I have a change to test it.

**Comment by jerryneedell** [comment]
I am testing this PR with My Raspberry Pi build -- I noticed the when I switch to this PR there are some changes made to the underlying repo
port/esp32s2/certificates/nisn-fw  is attempted to be deleted
frozen/Adafruit_CircuitPython_Requests
and
lib/tinyusb
are modified
Are any of those concerns?

I was able to build the atmel-samd/matrixportal_m4  with my newly compiled gcc-10 so I think the compiler is OK

**Comment by dhalbert** [comment]
> I am testing this PR with My Raspberry Pi build -- I noticed the when I switch to this PR there are some changes made to the underlying repo

This PR was started quite a while ago, so working at that commit does not include a bunch of changes. The PR test merge commits are more interesting.

**Comment by jerryneedell** [comment]
@dhalbert OK -- I don't think there is any problem - just want to be sure I understood.  My new compiler seem OK on the Pi and Jeff has made it available to anyone who wants it. Ready when this gets merged.

**Review by tannewt — APPROVED** [review]
I'm ok with this! Thanks for doing the final switch.

**Comment by dhalbert** [comment]
I think the next step is to do some smoke tests with gcc10 firmware buildsand see that they work on some sample programs. Then we can notify @ circuitpythonistas, and also I will update the Building CircuitPython guide.

**Comment by dhalbert** [comment]
I did some smoke tests and am satisfied.

**Pull request merged**
