### PR TITLE
Fix for issue #4937 - Implement minimum PulseOut time

### LINKED ISSUE #4937: PulseOut crashes if pulse is too short
**Firmware**

```python
Adafruit CircuitPython 7.0.0-alpha.3-433-g5a4a80336 on 2021-06-25; Raspberry Pi Pico with rp2040
```

**Code/REPL**

```python
import array
import board
import time
import pulseio
import pwmio

pwm = pwmio.PWMOut(board.GP0, frequency=38000, duty_cycle=2**15)
pulseOut = pulseio.PulseOut(pwm)

pulses = array.array('H', [1000,1000,1000,2000,1,1000])

while(True):
    print(".")
    pulseOut.send(pulses)
    time.sleep(5)
```

**Behavior**

The PWM output is continuously on. The terminal doesn't respond to Control-C. The CIRCUITPY drive still works but the auto-reload does not occur.

**Other**

If you make it so that 0 is accepted but guaranteed to do nothing, that would also provide a workaround for #4923 .

### PR DESCRIPTION
**Pull request by DavePutz**
Since PWM is being used for PulseOut, there can never be a pulseout pulse that is less than the 'high' portion of a PWM pulse. The hang reported in issue #4937 was due to the timer being set to less than the time required for a single PWM pulse. This fix calculates a minimum pulseout pulse based on the selected PWM frequency and enforces no timer delays less than that value.

Fixes #4937.

### CODE REVIEW

**Comment by dmcomm** [comment]
Hi, I guess you missed my update on the issue. I posted another example just now.

**Comment by DavePutz** [comment]
@dmcomm - There was an issue when the timer interval being used to time the pulses was too short. I've made a modification to correct that. If you have a chance could you test again (with the fix I was successful running your newest test script).

**Comment by dmcomm** [comment]
Sounds good! I don't have the build system set up (my comment on this pull request was only based on the description).

**Comment by dhalbert** [comment]
@dmcomm - We'll wait for your testing before merging.

**Comment by dmcomm** [comment]
OK I'll get back to you on that.

**Comment by dhalbert** [comment]
@dmcomm you can get the already-built artifacts here: (got to here from the checks):
https://github.com/adafruit/circuitpython/pull/4964/checks?check_run_id=3002465675

Click on the Artifacts drop down which is toward the right:
image

**Comment by dmcomm** [comment]
* My example with the countdown now runs to completion.
* PulseOut crashes with the same symptoms if the first pulse is less than 40us, at both 38kHz and 500kHz.
* I retested the first example in #4908 but changed to 500kHz, and that was OK for as long as I watched it for.
* If we want to guarantee that a pulse is output for too-small values, stretching to half a cycle doesn't achieve that. I expect a full cycle is needed.

**Comment by DavePutz** [comment]
@dmcomm, a PWM 'cycle' includes both high and low states, whereas a pulsein
'pulse' is only one or the
other. That is the reason for using a half-cycle for PulseOut. I will check
on the short initial pulse, I did not test for that.

**Comment by dmcomm** [comment]
I meant that experimentally, a duration of 13us doesn't guarantee that a pulse will be output at 38kHz 50%. I thought that might be because the 13us window fell on the wrong phase of the PWM cycle, but PulseOut timing isn't that precise anyway, so maybe not.

**Comment by DavePutz** [comment]
Changes made to correct handling of short initial pulses as well as (hopefully) improve short pulse accuracy somewhat.

**Comment by dmcomm** [comment]
Great, I haven't managed to crash it!

A full PWM cycle still seems to better. Requesting 1ms pulses at 1kHz gives a good result:

pulseout_crashfixed_1kHz_1000us

Requesting 500us gives unwanted behaviour like this:

pulseout_crashfixed_1kHz_500us

Similarly at 38kHz with 26/13us.

```
import array
import board
import time
import pulseio
import pwmio

pwm = pwmio.PWMOut(board.GP0, frequency=1000, duty_cycle=0x8000)
pulseOut = pulseio.PulseOut(pwm)
x = 500
pulses = array.array('H', [x,4*x] * 8)

while True:
    time.sleep(5)
    pulseOut.send(pulses)
```

**Comment by tannewt** [comment]
@DavePutz Any idea what could cause the second screen? Should we just merge this as-is?

**Comment by dmcomm** [comment]
I propose making the minimum pulse time a whole PWM cycle instead of half.

**Comment by DavePutz** [comment]
@tannewt - let's not merge this yet. I'll see if I can get things to have
more consistent timing.

**Comment by DavePutz** [comment]
@dmcomm - I agree with your proposal; I changed the minimum pulse to be a whole PWM cycle and it helps. Also, I'm not sure if your excellent test scripts are just to show a condition; but if you want more accurate pulseout timings on the RP2040 you should consider changing the PWM duty_cycle value to 65535. That helps the pulse consistency, particularly for shorter pulses. @tannewt I think we can merge this one now.

**Comment by dmcomm** [comment]
@DavePutz thanks! Yes, these scripts are just for illustration. I did previously try to do non-modulated output with a high frequency and 100% duty cycle, but my signal was too fast for that, so using PIO now.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks @DavePutz. CI issues are unrelated so I'll merge now.

**Pull request merged**
