### PR TITLE
Rp2040 i2ctarget support

### PR DESCRIPTION
**Pull request by gamblor21**
For #4536 adding support for I2C Target for the RP2040 based on work by @kstillson and @im-redactd.

Test code from my KB2040
```python
import board
from i2ctarget import I2CTarget

target = I2Ctarget(board.D7, board.D6, [0x41])

while True:
    request = target.request()
    if request is not None:
        if request.is_read:
            print("Write request ")
            request.write(b'B')
        else:
            r = request.read()
            if r == "T":
                print("Read a T")
```

And test controller code
```python
import board
import time

i2c = board.I2C()

while True:
    i2c.try_lock()

    print("Sending T")
    i2c.writeto(0x41, b'T')
    time.sleep(1)

    t_bytes = bytearray(1)
    i2c.readfrom_into(0x41, t_bytes)
    print("Read ", t_bytes)
    i2c.unlock()
    time.sleep(5)
```

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by wattsie** [comment]
Awesome work all...
I am about a week or two away from finishing 3d printing and wiring up eight RP2040's to a single Pi4 over the i2c bus.
Look forward to testing this code.
Cheers.

**Comment by tannewt** [comment]
> Awesome work all... I am about a week or two away from finishing 3d printing and wiring up eight RP2040's to a single Pi4 over the i2c bus. Look forward to testing this code. Cheers.

Beware that (I think) this CP API uses I2C clock stretching and that Pi's are notorious for not supporting clock stretching. Clock stretching is used while waiting for python to respond.

**Comment by wattsie** [comment]
> > Awesome work all... I am about a week or two away from finishing 3d printing and wiring up eight RP2040's to a single Pi4 over the i2c bus. Look forward to testing this code. Cheers.
> 
> Beware that (I think) this CP API uses I2C clock stretching and that Pi's are notorious for not supporting clock stretching. Clock stretching is used while waiting for python to respond.

Thanks I will check/test it out...

Any idea if the Pico has a limited of a single target address? 
I see the constructor is being passed an array, but it the count is greater than one it fails with a warning.

Cheers.

**Comment by gamblor21** [comment]
> Any idea if the Pico has a limited of a single target address? I see the constructor is being passed an array, but it the count is greater than one it fails with a warning.

The Pico does limit it to one. The `atmel-samd` port can support more then one, but ESP and RP2040 only support a single address.

In theory you could set up both I2C chip peripherals as I2C targets and have two addresses that way.

**Pull request merged**
