### PR TITLE
io naming for gpio (credit to @kattni)

### PR DESCRIPTION
**Pull request by ladyada**
can add D pins later!

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
The pins look good, and this fits with the results of our conversation.

It's not obvious which pins are the default `board.UART()`. GPIO5 is RX and GPIO6 is TX. Even though they're not labeled on the silk, shall we add TX and RX as aliases to IO5 and IO6?

**Comment by ladyada** [comment]
yah doing

**Review by dhalbert — APPROVED** [review]
OK, thanks!

**Comment by dhalbert** [comment]
Failed check is a GitHub Actions issue.

**Pull request merged**
