### PR TITLE
Fix pad assignments on atmel-samd UART

### LINKED ISSUE #7612: UART write does not work on QT Py SAMD21 with CircuitPython 8.x
### CircuitPython version

```python
Tested with CP 8.0.2 and CP 20230218-12d3640.

Code works properly with CP 7.3.3.
```

### Code/REPL

```python
import time
import board
import busio

e5_uart = busio.UART(
    board.TX, board.RX,
    baudrate=9600,
    timeout=0.01
)

while True:
    out_bytes = bytes('From QT Py\n\r', 'utf-8')
    e5_uart.write(out_bytes)
    in_bytes = e5_uart.read(10)
    if in_bytes:
        print(in_bytes)

    time.sleep(1)
```

### Behavior

I have the QT Py Tx and Rx pins connected to a USB-TTL serial converter connected to my Linux PC.  For CP 8.x versions, no characters are received on the PC.  When I send characters from the PC to the USB-TTL converter, the QT Py does properly receive them, as indicated by characters being printed on the QT Py Serial console.

The above code works properly with CP 7.3.3.

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #7612.

- SERCOM USART TXPO computation was not correct on SAMD21 for TX pins using pad 2, due to changes introduced in #6434. SAMD21 and SAMx5x are different: SAMx5x does not allow pad 2 for TX. In addition, checking for allowed pins based on their pads was not as rigorous as it should have been. Code is somewhat restructured.
- Signature for `busio.UART()` was missing several arguments and did not account for `None` values.
- Did more pin validation in `shared-bindings` `busio.UART()`. Ensure pins are distinct, and that both TX and RX are not None. Removed now-redundant checks for TX and RX both being none in `ports/*/common-hal/busio/UART.c`.

Tested that original bug (#7612) is now fixed. Did not test that flow control is working. Did verify that TXPO and RXPO are correct for a variety of pin choices, with and without RTS/CTS. It's not clear whether TXPO 0x2 is OK on SAMD51 if RTS and CTS are not used, but did the safe thing.

Also tested on a Metro M4, confirming that the standard TX and RX still work in both directions.

@stonehippo You may want to re-test with these changes.

### CODE REVIEW

**Comment by stonehippo** [comment]
Thanks @dhalbert. I'll try this out out SAMD21 and SAM5x boards I have which expose the right pins for flow control.

**Comment by dhalbert** [comment]
Test program I used to find working combinations, a variation on https://learn.adafruit.com/circuitpython-essentials/circuitpython-uart-serial#wheres-my-uart-2985036. Generates thousands of combinations, and takes a while to run. Includes cases where pins are `None`.

```py
import board
import busio
from microcontroller import Pin

def is_hardware_uart(tx, rx, rts, cts):
    try:
        p = busio.UART(tx, rx, rts=rts, cts=cts)
        p.deinit()
        return True
    except ValueError:
        return False

def get_unique_pins():
    exclude = ['NEOPIXEL', 'APA102_MOSI', 'APA102_SCK']
    pins = [pin for pin in [
        getattr(board, p) for p in dir(board) if p not in exclude]
            if isinstance(pin, Pin)]
    unique = []
    for p in pins:
        if p not in unique:
            unique.append(p)
    return [None] + unique

for tx_pin in get_unique_pins():
    for rx_pin in get_unique_pins():
        if is_hardware_uart(tx_pin, rx_pin, None, None):
            print(f"TX: {tx_pin}\tRX: {rx_pin}")
            for rts_pin in get_unique_pins():
                for cts_pin in get_unique_pins():
                    if is_hardware_uart(tx_pin, rx_pin, rts_pin, cts_pin):
                        print(f"\tRTS: {rts_pin}\tCTS: {cts_pin}")
```

**Review by tannewt — APPROVED** [review]
Looks good! Thank you for the quick fix

**Comment by tannewt** [comment]
Will wait for @stonehippo to test before merging.

**Comment by dhalbert** [comment]
Will merge for now since this is an 8.0.0 regression on a number of boards, breaking UART. @stonehippo we are still interested in your test results, of course!

**Comment by stonehippo** [comment]
@dhalbert I finally got around to testing this out and RTS/CTS flow control seems to work as expected on both SAMD21 and SAMD51 boards where I could get at the correct pins for hardware flow control on a given board (e.g. Feather M0 Adalogger, MicroMod SAMD51).

**Comment by dhalbert** [comment]
@stonehippo glad to hear it's working for you

**Pull request merged**
