### PR TITLE
fix rp2040 use of tud_disconnect

### LINKED ISSUE #4066: RP2040 Pico - storage.erase_filesystem() does not reformat and erase
Board: RP2040 Pico
Firmware: 6.2.0 beta and 20210126-a2ac2da build
OS: Ubuntu 20.04.1 LTS

The drive appears almost full but the files do not add up to used space. Reloading the uf2 file doesn't change the filesystem contents (I'm not sure if this should). Running "storage.erase_filesystem()" in the REPL causes the board to unmount (presumable reset) but does not auto re-mount. When unplugged and plugged back in the filesystem contents appear unchanged.

Here's output of df -h:
```bash
brett@panini:/media/brett$ df -h /media/brett/CIRCUITPY/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb1      1004K 1001K  3.0K 100% /media/brett/CIRCUITPY
```

and ls -la:
```bash
brett@panini:/media/brett$ ls -la /media/brett/CIRCUITPY/
total 21
drwxr-xr-x  2 brett brett 16384 Dec 31  1969 .
drwxr-x---+ 3 root  root   4096 Jan 25 19:40 ..
-rw-r--r--  1 brett brett    96 Sep  1  2016 boot_out.txt
-rw-r--r--  1 brett brett    15 Jan 25 19:29 code.py
-rw-r--r--  1 brett brett     0 Jan 25 19:29 .code.py.swp
```

### PR DESCRIPTION
**Pull request by hathach**
- fix #4066, need https://github.com/hathach/tinyusb/pull/700 to merged [EDIT: now merged-@dhalbert] ~~first to be able to bump up tinyusb (draft for now)~~ and ready for review
- also use the normal usb_irq_handler() as well with dcd_int_hanlder() wrapper added with tinyusb recently.

### CODE REVIEW

**Comment by dhalbert** [comment]
The xtensa builds are using an old cache id. We can ignore their failures.

**Comment by hathach** [comment]
> The xtensa builds are using an old cache id. We can ignore their failures.

I am doing rebase and will push force again.

**Review by jepler — APPROVED** [review]
Testing performed: Loaded a FW from this PR, ran storage.erase_filesystem().  It worked.

Thank you!

**Comment by dhalbert** [comment]
Let's ignore the build failures for now, though I'm surprised the rebase did not help.

**Pull request merged**
