### PR TITLE
turn off brownout before deep sleep

### LINKED ISSUE #4025: ESP32-S2  coming out of deep sleep with POWERON status
Now that I'm using a Debug Build of CP 6.1.0 RC I'm collecting a lot of data. My program is collecting temp and humidity data on a once per minute basis, and deep sleeps the reset of the time. I found that I get as many as 36 exits from deep sleep with the DSLEEP status, but too many are POWERON status. I first noticed this when my alarm.memory counter was getting reset to zero.

I have 2 logs: one is the Debug UART and the other is the normal UART on pins 5/6. My program log shows the code handles the exceptions like no WIFI connection correctly without resetting the MCU.

Since a program coming out of deep sleep has to work as if it was coming out of Reset, the code works, but the NVM counter is reset. I'm still chasing a problem where the MCU just stops sending data after 10-24 hours. But this error is found usually in less than 5 minutes.
[Metro-uart.log](https://github.com/adafruit/circuitpython/files/5832438/Metro-uart.log)
[screenlog.log](https://github.com/adafruit/circuitpython/files/5832439/screenlog.log)
I've posted the code and logs also in the forum. Not sure where stuff goes.

[code.txt](https://github.com/adafruit/circuitpython/files/5832448/code.txt)

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #4025.

### CODE REVIEW

**Comment by dhalbert** [comment]
@jfabernathy Could you test this fix? It disables brownout detection just before doing a deep sleep. You can find a build for your board in the "Artifacts" dropdown on [this page](https://github.com/adafruit/circuitpython/pull/4159/checks).

image

I tried testing with simpler test programs that did and did not use wifi but could not reliably generate the problem.

**Comment by jfabernathy** [comment]
Just so I'm clear. I double press reset on the Metro ESP32-S2 and then drag over the UF2 file I got from the "Artifacts" dropdown for Metro ESP32-S2 to the CIRCUITPY dir. The boot_out.txt shows:

 Adafruit CircuitPython 6.2.0-beta.1-136-g5c129f813 on 2021-02-08; Adafruit Metro ESP32S2 with ESP32S2

My lib folder items are all from Feb 4 2021.
The app I'm testing is my full application that sends temp and humidity via miniMQTT and then deep sleeps for 60 sec. It also post it's loop count so I'll know if it comes out of deep sleep vs. poweron.  Only exception would be if the app locks up and the WDT resets it.  either way the loop count goes to 0. For the past week with my custom build with BOD disabled completely there have been no loop count resets.  
So this is what I'll be testing unless you think something needs to change.

**Comment by dhalbert** [comment]
Right, thanks, that's exactly what I would expect you to do. This build does not have brownout detection disabled completely like your previous test version. Instead it turns it off before just before deep sleep (and actually doesn't turn it back on -- not sure if we should or it's automatic).

**Review by tannewt — APPROVED** [review]
Code looks good to me! Thanks!

**Comment by jfabernathy** [comment]
The first hour (67 loops) are flawless.  I'll let you know tomorrow what the first day looks like.

**Comment by jfabernathy** [comment]
My test on the Metro ESP32-S2 has worked flawlessly for over 12 hours. I'd say it fixed.  I also put the right .UF2 file on the Magtag with a test that reads temp, humidity, and the loop count from alarm.memory and displays them every 60 seconds and them deep sleeps.  It's over 11 hours without a problem.  I'd say it's fixed.

**Comment by dhalbert** [comment]
@jfabernathy Thank you for the thorough testing!

**Pull request merged**
