### PR TITLE
added ICBbuy ESP32-C3Mini board

### PR DESCRIPTION
**Pull request by toaster-robotics**
- Working build for the [ICBbuy ESP32-C3Mini board](https://wiki.icbbuy.com/doku.php?id=developmentboard:esp32-c3mini)
- couldnt get it to build without including a **CIRCUITPY_CREATOR_ID** and **CIRCUITPY_CREATION_ID**, so I just copied the IDs from seeed_xiao_esp32c3 (sorry)
- used the **USB_VID** and **USB_PID** from the existing SuperMini NRF52840 board

### CODE REVIEW

**Comment by dhalbert** [comment]
Are you associated with the manufacturer or are you a consumer? Is this board identical to an existing one like the Seeed C3 board?

Submit PR's for new creation ids here: https://github.com/creationid/. Pick the appropriate repository.

This board does not need USB_VID and USB_PID because it does not support USB access (except for serial).

**Comment by toaster-robotics** [comment]
Hello,
I'm a consumer. Just spent almost all day getting this to work so I thought I would share. It's not identical to the Seeed C3 board. The pins are all different. They are using the same ESP32-C3 chip though. I was using the Seeed board files as an example. Should I try to get creation ids if I'm just a user?

**Comment by dhalbert** [comment]
It's fine for you to get creation ID's. But I cannot find a shopping link this board in a simple websearch. Could you give one? I am a bit reluctant to add random boards that have very few buyers. Someone else asked about a adding a board that had a total of two buyers on AliExpress, for instance.

**Comment by SeanTheITGuy** [comment]
I was looking into this board as well, and it is pin-identical to the ESP32-C3-DevKitM-1-N4 except the ICBbuy/MakerGo/DFRobot/DIYUser ESP32-C3-Supermini lacks pins 18 and 19, but the rest are all mapped the same.

**Comment by dhalbert** [comment]
Yes, if you can use a more generic build, I think that is best until/if this style of board becomes popular.

**Comment by toaster-robotics** [comment]
Here are two links. I bought mine from Lazada (currently living in Thailand). They're dirt cheap.
https://www.aliexpress.com/item/3256805781327184.html
https://www.lazada.co.th/products/i4954930372-s20827365800.html

**Comment by SeanTheITGuy** [comment]
I would like to rescind my comment from earlier. This board is NOT compatible with the ESP32C3-Devkit, as I thought, as it requires diferent UART settings.  The beetle-esp32-c3, however, does work with it. That said, unless people who want to work with these boards dig in the source code or happen upon this thread, chances are that doesn't help anyone.  They're among the cheapest ESP32C3 devboard available now, and might be worthy of reconsideration for adoption if their popularity on the eastern marketplaces continues to rise.

**Comment by tyeth** [comment]
Looks identical to the one I wanted to add, https://www.aliexpress.com/item/1005006170575141.html?spm=a2g0o.order_list.order_list_main.11.5b451802QRLpyP

**Comment by SeanTheITGuy** [comment]
The beetle c3 is near exactly the same in terms of pins and functionality.  I also have a supermini target created but since this was rejected once, I never bothered to submit it.

**Comment by bill88t** [comment]
This board seems identical to https://circuitpython.org/board/makergo_esp32c3_supermini/

**Comment by dhalbert** [comment]
> This board seems identical to https://circuitpython.org/board/makergo_esp32c3_supermini/

@toaster-robotics Try that and see how it works. I am not sure which board is the "clone" here and which is the "original".

**Comment by SeanTheITGuy** [comment]
This board was submitted first, but it seemed like work on it had stalled before getting the checks to pass, so I submitted the work I had done for the MakerGo version of the board, which was functional and passed checks to get merged.

**Comment by dhalbert** [comment]
Then I'll just close this, unless there is some difference between the boards.

**Pull request closed without merging**
