### PR TITLE
Add a font protocol

### PR DESCRIPTION
**Pull request by jepler**
@tekktrik noticed that there was no convenient way to specify that a function takes "any kind of Font", including the built in one and the ones from the `adafruit_bitmap_font` package. By defining this _protocol_ in our stubs, it's hoped that `fontio.FontProtocol` can be used instead of an ad-hoc `Union[]` of several known font types.

image

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Great idea, and interesting this is a "no-code" addition to `shared-bindings`.

**Comment by tekktrik** [comment]
Excellent!  Let me know if/when it's good to start typing with this then!

**Comment by jepler** [comment]
I think that when the 7.2.0alpha release is tagged on github, the stubs will be uploaded to pypi as a prerelease. That'll allow use of the new protocol type.

**Comment by tekktrik** [comment]
Perfect!  Thank you for this!

**Pull request merged**
