### PR TITLE
fix espressif DigitalInOut open-drain

### LINKED ISSUE #3845: Open Drain outputs don't work (also breaks bitbangio.I2C)
On the Kaluga, I have two sensors attached to the I2C bus at IO10/11.  They are detected if I scan with busio.I2C but not with bitbangio.I2C.  When I scope bitbangio, there is literally no activity on the pins 10/11; there is the expected activity with busio.I2C.

```
>>> import board,bitbangio
>>> bus = bitbangio.I2C(board.IO10, board.IO11); bus.try_lock(); bus.scan(); bus.deinit()
True
[]
>>> import busio, board
>>> bus = busio.I2C(board.IO10, board.IO11); bus.try_lock(); bus.scan(); bus.deinit()
True
[11, 112]
```

I'm testing a local build.  Possibly important, this is a `DEBUG=1` build.

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #3845.

Open-drain and output both need to be set. Discovered while researching #5865, which is not yet fixed.

Tested with a Saleae and a QT Py ESP32-S2.

### CODE REVIEW

**Comment by Neradoc** [comment]
I tested the PR with a DS18B20 on a Feather S2 and it's detected and gives me temperatures, while latest doesn't. ( #3822 )

**Comment by dhalbert** [comment]
> I tested the PR with a DS18B20 on a Feather S2 and it's detected and gives me temperatures, while latest doesn't. ( #3822 )

That's good! I have a DS18B20 wired up and it's still not working for me, on the QT Py ESP32-S2.

**Comment by Neradoc** [comment]
My experience with you and I having different results is that tinyuf2 is usually the difference and...

Installing Circuitpython (from the PR) with esptool on the QTPY ESP32S2, the sensor is **not** detected.
Reinstalling tinyuf2 (latest release) and CP from the PR, the sensor is detected and reports temperatures.
I did a couple of back and forth with consistent results.

I don't know if it's related to the open-drain issue or belongs more to the OneWire issue.

**Comment by dhalbert** [comment]
Before this PR fix, I saw no signal on the onewire pin with my Saleae, and simple manipulation of the output with a `DigitalInOut` and open-drain drive did not work. With the `.bin` from this fix, I do see the signal, but the timings are a bit off (too long). The Saleae display program says that the waveform is in error, and the sensor does not respond.

I'll try the UF2, and see whether the timings are different. Something that TinyUF2 is doing may be changing the clock handling in some way. It might show up in frequency differences for other things, too.

**Comment by dhalbert** [comment]
I tried the UF2 version, and it does not work for me on my QT Py setup, but it gets a lot further, usually, and eventually gets a CRC error. Below is a screenshot showing the two. The top is the UF2 version: the SEARCH ROM command works, and there's a lot more waveform to the right. The bottom is the BIN version. It has a longer delay before the SEARCH ROM (1m vs about 560us), and you can see the SEARCH ROM pulse timings seem rather messed up.

I looked briefly at TinyUF2, and don't immediately see what setup it might be doing that the BIN version is not, but there must be something. I'll inquire further about this. Thanks for thinking to try the UF2 vs the BIN!

**Review by jepler — COMMENTED** [review]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/gpio.html#_CPPv411gpio_mode_t Is it possible that CircuitPython should be setting  `GPIO_MODE_INPUT_OUTPUT_OD` = `((GPIO_MODE_DEF_INPUT) | (GPIO_MODE_DEF_OUTPUT) | (GPIO_MODE_DEF_OD))` instead? If the state of the pin needs to be read back in, the DEF_INPUT bit may need to be set.

The docs also read a bit like the _DEF_ macro should not be used directly but the _MODE_ enums instead..

**Comment by dhalbert** [comment]
> If the state of the pin needs to be read back in, the DEF_INPUT bit may need to be set.

I was able to print the output value of the pin from the REPL without DEF_INPUT being set. Hmm. The `shared-module` code for bitbang OneWire does not assume that the pin can be bidirectional: it flips the direction back and forth to write and read.

I agree with you about the macros: I didn't read the doc carefully enough to realize those constants were available.

**Review by jepler — APPROVED** [review]
Thanks, it's clearly a distinct improvement even if it might need to be tweaked again in the future.

**Pull request merged**
