### PR TITLE
Adafruit funhouse

### PR DESCRIPTION
**Pull request by dhalbert**
- Add FunHouse board
- Make `PWMOut` constructor return status values instead of throwing exceptions. `PWMOut` may be created before exceptions can be thrown for backlight, etc. Changes in `esp32s2` and `stm` due to this (hence tagging @hierophect for a look).

### CODE REVIEW

**Comment by dhalbert** [comment]
draft for now; backlight issues

**Comment by dhalbert** [comment]
I tested STM changes on a Feather STM32405, creating PWMOut's in the REPL to check the new error handling.

**Review by ladyada — APPROVED** [review]
dotstars/LED/backlight/TFT works. i have more to test but this is good for now

**Review by hierophect — COMMENTED** [review]
Retroactive LGTM. The only thing we lose here is telling users that they might want to reshuffle certain initializations on STM32 so the dynamic timer allocation doesn't reserve timers on pins that require PWMOut. That was an STM32 specific issue, so I didn't want to abstract it to the shared bindings level. That only comes up if you're using PWMOut and PulseIO/Protomatter simultaniously though, so it's probably fine to leave debugging to the user.

Remind me the incentive for standardizing these exceptions again, does it have a benefit for displays? It's been a while since I touched it.

**Comment by dhalbert** [comment]
> Remind me the incentive for standardizing these exceptions again, does it have a benefit for displays? It's been a while since I touched it.

The reason to remove the exceptions and pass back status codes was that the on-board display initialization in `boards/<someboard>/board.c` is done before exceptions will work or can be reported. `common_hal_displayio_display_construct()` was calling `common_hal_pwmio_pwmout_construct()`, and when the latter failed, an exception was getting raised. So I made it uniformly return a status code instead, so that `common_hal_displayio_display_construct()` could decide what to do.

There are a lot more cases for STM32 `PWMOut` creation failure than some other ports, so I added some, and unified a few others, mostly trying to report the ones that would be meaningful to the end user. The main disadvantage of this change I saw is that it grows the code for all ports a bit because now `shared-bindings/pwmio/PWMOut.c` knows how to deal with all the possible failures across all ports.

**Comment by hierophect** [comment]
@dhalbert that's right, I remember that now. I thought I had a custom handler for that but I guess not. I guess we could make `common_hal_pwmio_pwmout_construct()` aware of whether it's being called from board.c or the python code, but that's maybe too much work for some minor flash savings and failure conditions.

**Pull request merged**
