### PR TITLE
Add board MicroDev microC3

### PR DESCRIPTION
**Pull request by microDev1**
Add `esp32c3` based MicroDev microC3 development board.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Are you actively working on adding BLE workflow support? I'm a bit worried we're going to start getting a support burden of people trying to use C3 boards over USB.

**Comment by microDev1** [comment]
> We should probably add a support note about the C3 to the README too.

Sure, I'll add it in a separate PR.

> Are you actively working on adding BLE workflow support?

Yup! I have started working on it and have got the basic stuff ported to `esp` from `nRF` implementation.
I started with the smaller things like `UUID`, `Descriptor`, `Service` etc. and am incrementally moving to the larger things.

**Comment by microDev1** [comment]
I have got nothing functional with `BLE` yet and things will probably remain in this state for a while.
My concern is that CI is not being run for `esp32c3` at present due to no boards. 
I think we can have an `esp32c3` board with a big note in `README` for the time being. :-)

**Comment by tannewt** [comment]
Big note in README is fine with me. Thanks!

**Pull request merged**
