### PR TITLE
Fixup translations and remove location to reduce diffs

### PR DESCRIPTION
**Pull request by tannewt**
This adds a script to re-merge translations from the git history. It skips any changes that set a translation to empty or to the message id.

It also removes any obsolete translations. They live on in git history.

### CODE REVIEW

**Comment by Tasm-Devil** [comment]
Remove file locations was a bad idea in my opinion.
1. It's important to know where the String came from
2. The Strings are now sorted by alphabet and not by modules. This means, I cannot translate module by module.

Plz. undo this mod.

**Comment by dhalbert** [comment]
I see your point. I'm wondering if I should revert this for now. Suppose we suppressed the line number but kept the filename? That would reduce the diffs substantially but still associate the string with a file.

**Comment by Tasm-Devil** [comment]
Wait with it. I'm currently doing more translations

**Comment by Tasm-Devil** [comment]
plz. merge this first: https://github.com/adafruit/circuitpython/pull/1589

**Comment by tannewt** [comment]
I don't know of an option in msgmerge to keep filename but delete line number. @Tasm-Devil do you have your own CircuitPython build or do you just use the file? If you have a repo we could add a make target that leaves the locations in temporarily.

**Comment by dhalbert** [comment]
`msgmerge` has an option to generate filename/linenumber, just filename, or suppress all (like `--no-location`)
```
‘-n’
‘--add-location=type’
Generate ‘#: filename:line’ lines (default).

The optional type can be either ‘full’, ‘file’, or ‘never’. If it is not given or ‘full’, it generates the lines with both file name and line number. If it is ‘file’, the line number part is omitted. If it is ‘never’, it completely suppresses the lines (same as --no-location).
```

**Pull request merged**
