### PR TITLE
Switch to finaliser for PWMOut and audiopwmio

### LINKED ISSUE #8726: pulseio PulseIn causes hard crashes
### CircuitPython version

```python
Adafruit CircuitPython 8.2.7 on 2023-10-19; Adafruit Metro M4 Express with samd51j19
```

### Code/REPL

```python
import pulseio
import time
import board

pulses = pulseio.PulseIn(board.D2)

while (1):
    print(time.monotonic())
```

### Behavior

I have a wire connected to D2, but its not connected to anything else.

If I save this file to the board a few times (causing soft resets), or wave my hand near the wire, or just wait for a while, I get a hard crash:
'''

 | 8.2.7Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Hard fault: memory access or instruction error.
Please file an issue with your program at github.com/adafruit/circuitpython/issues.
Press reset to exit safe mode.
'''

### Description

If I comment out the "pulses = ..." line, the board becomes rock solid. I can't get it to hard crash with any number of saves, resets, touching the wire, etc, etc.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #8726 which was caused by a mix of bulk reset and finaliser use.

Work towards #8960.

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Various build failures in atmel-samd and raspberrypi due to now-missing routines.

**Comment by tannewt** [comment]
Builds are fixed @dhalbert

**Comment by dhalbert** [comment]
Thanks! I will do some hw testing a little later.

**Review by dhalbert — APPROVED** [review]
Tested on an RP2040, creating some PWMOuts and then restarting the VM. Things seem fine. I'm impressed the code has gotten smaller!

**Pull request merged**
