### PR TITLE
fixed typo (path) in postCreateCommand

### PR DESCRIPTION
**Pull request by bablokb**
fixes a typo in the path of the postCreateCommand

### CODE REVIEW

**Comment by bablokb** [comment]
When I look at the failed checks, these are all architecture-builds which are not relevant for this pull-request.

Is there a way to configure the `.devcontainer`-subdirectory to prevent all these builds? This would save time and ressources.

**Comment by jepler** [comment]
the script `ci_set_matrix.py` in `tools` controls which boards are built based on the changed files. It has to be hand modified for exceptional files. It doesn't look like it has a facility right now to ignore whole directories, just individual files. So you could list your individual files, or you could add a facility to filter whole directories.

btw is there any possibility / utility to testing `.devcontainer` during our build? If a typo goes unnoticed, that's not great. If we could have found the problem automatically at CI time, that would have been better.

**Comment by bablokb** [comment]
There is the possibility to pre-build containers. But I'm not sure that this catches problems with the postCreateCommand. And I think pre-build containers are not suitable for CircuitPython-builds, because I think it is important to do the whole fetch-submodule logic every time after a fresh-clone.

I will try to find something useful in the Github-docs.

BTW: this error prevented the postCreateCommand to run at all, but there could be errors in the script as well. Or the script is outdated because something changes in the build-environment. So the question here is if it is possible to reuse (parts of) your CI-pipeline.

**Comment by bablokb** [comment]
I checked pre-build containers, but they don't execute the postCreateCommand at all.

**Review by jepler — APPROVED** [review]
I can merge this as-is, or I can wait for you to make the change to the script so updates to this file don't cause excess builds; ping me and let me know.

**Comment by bablokb** [comment]
I'll make a pull request for the script, but that won't be before Wednesday.

**Pull request merged**
