### PR TITLE
NRF: Minor Simmel fixes

### PR DESCRIPTION
**Pull request by xobs**
This patchset includes several minor fixes to Simmel fixes:

* Makes SPIM3 optional, for boards that don't want to dedicate 8 kB of RAM
* Disables SPIM3 on Simmel
* Enables `CIRCUITPY_AESIO` on Simmel
* Corrects the SPI_CSn pin mapping

### CODE REVIEW

**Comment by tannewt** [comment]
I've tried to rerun the checks. It looks like some of the larger translations were failing for the simmel build.

**Comment by xobs** [comment]
Which are failing?

**Comment by tannewt** [comment]
Looks like de_DE, pl, fr, it_IT, es, ko, fil, and zh_Latn_pinyin: https://github.com/adafruit/circuitpython/pull/2869/checks?check_run_id=657239982

**Comment by xobs** [comment]
Thanks, I didn't notice that among the other build failures.  I've reduced the flash filesystem by one block.

Incidentally, I opened up https://github.com/adafruit/circuitpython/issues/2884 which I've run into several times while figuring the optimal internal filesystem size.  We'll probably enable SPI flash at some point soon, but for now I'll be doing the flash filesystem dance.

**Pull request merged**
