### PR TITLE
STM32: OS and Struct support

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds basic OS and Struct support to assist with libraries. Uses #2151

### CODE REVIEW

**Comment by ladyada** [comment]
woopz i think this got mixed with another i2c PR? if its easier we can wait till i test the other open PR so it can be merged

**Comment by hierophect** [comment]
@ladyada It's a direct branch of my existing PR, since I need that code to test I2C libraries

**Comment by ladyada** [comment]
ahh ok

**Comment by hierophect** [comment]
Binary (untested)
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3633243/firmware.bin.zip)

**Comment by ladyada** [comment]
tested, this is good!

```
>>> import os
>>> os.stat("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 2] No such file/directory
>>> os.stat("boot_out.txt")
(32768, 0, 0, 0, 0, 0, 108, 1480810702, 1480810702, 1480810702)
>>> dir(os)
['__class__', '__name__', 'chdir', 'getcwd', 'listdir', 'mkdir', 'remove', 'rename', 'rmdir', 'sep', 'stat', 'statvfs', 'sync', 'uname', 'unlink', 'urandom']
>>> os.mkdir("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 30] Read-only filesystem
>>> os.uname()
(sysname='stm32f4', nodename='stm32f4', release='5.0.0', version='5.0.0-alpha.4-53-g18c5be883-dirty on 2019-09-19', machine='STM32F412G_DISCO with STM32F412xGS')
>>> os.urandom()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes 1 positional arguments but 0 were given
>>> os.urandom(1)
b'\x04'
>>> os.urandom(8)
b'\x04\x04\x04\x04\x04\x04\x04\x04'
>>> os.listdir()
['.fseventsd', '.metadata_never_index', '.Trashes', 'lib', 'boot_out.txt', 'System Volume Information']
>>> 
```

**Comment by hierophect** [comment]
Let's make sure we merge the original first!

**Comment by ladyada** [comment]
ok ill test that one now

**Comment by hierophect** [comment]
Closes #2169

**Comment by tannewt** [comment]
I'd suggest rebasing the os and struct commits onto master for this PR. That way this PR doesn't depend on the other and we can review and merge in parallel. Let me know if you need help with git. It's got a steep learning curve.

**Comment by hierophect** [comment]
@tannewt I'd be happy to rebase, but since there are no modules I'm aware of that can even make use of OS and Struct without I2C being available, it'd make this hard to test independently, which is why I had it as a branch. I can probably fix your comments on I2C pretty quickly, do you still want me to move it?

**Comment by tannewt** [comment]
You can test os and struct yourself with a test script like what @ladyada did above. Please do move it and make any PRs you do in the future independent so we can have multiple review cycles going.

**Comment by hierophect** [comment]
Ok, I thought the rebase was going to be simple but it's turning out to be a huge pain, so I'm just going to go ahead and delete/recreate this.

**Pull request closed without merging**
