### PR TITLE
Web workflow skip init when no password, freeing socket. Also reconnect wifi on reload.

### PR DESCRIPTION
**Pull request by bill88t**
If no password is passed via settings.toml, the wifi connection will occur, but the web workflow will not start at all.
This frees up a (as it turns out, very precious) socket.

Closes https://github.com/adafruit/circuitpython/issues/7598

### CODE REVIEW

**Comment by anecdata** [comment]
I think this would close https://github.com/adafruit/circuitpython/issues/7598

**Comment by bill88t** [comment]
I do think so too. Adding it to the first message to have it take effect.

**Comment by anecdata** [comment]
https://docs.circuitpython.org/en/latest/docs/workflows.html#web will need an update

**Comment by bill88t** [comment]
Wifi now is auto-connecting on reload.
The web-workflow will not init on a reload, only on boot.
This matches `raspberrypi` behaviour, treating wifi as always enabled when it's set via `settings.toml`.

**Comment by anecdata** [comment]
If I understand correctly, the `raspberrypi` behavior (wifi connection surviving reload with or without Web Workkflow) will change if MicroPython fixes issue 9505, but this PR would auto-[re]connect wifi on either port _if_ Web Workflow is enabled.

**Review by tannewt — APPROVED** [review]
Thanks! This will go in for 9.x.

**Comment by bill88t** [comment]
> If I understand correctly, the `raspberrypi` behavior (wifi connection surviving reload with or without Web Workkflow) will change if MicroPython fixes issue 9505 (and we merge it), but this PR would auto-[re]connect wifi on either port _if_ Web Workflow is enabled.

@anecdata  cyw43 is a persistent object we just never reset.
Our implementation is just not bothering disconnecting it, so it persists.
That's all there is to that.
Our picow wifi stuff is all of our own, not really taking any of micropy's work.
I have used them as a reference, but not copied code directly.
So future changes of theirs will not affect us.

**Pull request merged**
