### PR TITLE
Fix delays and rounding in samd PWM

### PR DESCRIPTION
**Pull request by timchinowsky**
Blocking delays are observed when setting `duty_cycle` in the samd port of CircuitPython (see https://github.com/adafruit/circuitpython/issues/7653), behavior which interferes with some applications of PWM, and which differs from from that of other ports.  Investigation of this issue revealed another problem:  In some cases, the API will round a non-zero duty cycle down to zero, causing the PWM signal to stop cycling at all.  The changes proposed in this PR address both of these issues.

Detailed description of how these fixes were tested contains many plots and can be found in (https://github.com/timchinowsky/circuitpython/blob/fix-samd-pwm/tools/pwm/pr.md) and (https://github.com/timchinowsky/circuitpython/blob/fix-samd-pwm/tools/pwm/README.md).

### CODE REVIEW

**Review by dhalbert — CHANGES_REQUESTED** [review]
Another place to put the tests is in `tests/circuitpython-manual`. I'm not sure we should put the very detailed testing screenshots and discussion in the repo. I'd suggest putting it in this PR and putting a link to it somewhere with the tests.

**Comment by timchinowsky** [comment]
> Another place to put the tests is in `tests/circuitpython-manual`. I'm not sure we should put the very detailed testing screenshots and discussion in the repo. I'd suggest putting it in this PR and putting a link to it somewhere with the tests.

`tests/circuitpython-manual` is certainly on-point.  I'd want to put a couple images there to illustrate what "good" and "bad" look like.  I put the test data in the repo bc it's hard to wrangle a lot of images if you just "attach" them.  Probably I should just put them in a PDF, like this: [pr9343.pdf](https://github.com/user-attachments/files/15893180/pr9343.pdf).

**Comment by timchinowsky** [comment]
For test documentation, seems like the repo issues and PRs are the defacto places for this, but I'll add some lines to the online docs for `PWMOut` to clarify the rounding behavior.

**Review by tannewt — APPROVED** [review]
Looks great! Thank you!

**Comment by dhalbert** [comment]
I shrank the PNG images by about 70% using https://tinypng.com, and pushed them. I see little if any visible change.

**Review by dhalbert — APPROVED** [review]
I shrank the images, and will merge.

**Pull request merged**
