### PR TITLE
Esp32 dev kit v1

### PR DESCRIPTION
**Pull request by m1cha1s**
Added board definition for ESP32 devkit v1 board.

### CODE REVIEW

**Comment by DerBroader71** [comment]
Is there any chance to be more specific over which make/model board this is, as there are 3 version of the ESP32 Devkit V1 that I have come across - 30/36 and 38 pin?

**Comment by tannewt** [comment]
I don't think you should be adding an `uncrustify.cfg` file. Please remove it from the PR.

**Comment by dhalbert** [comment]
@m1cha1s You were using URL links instead of @ references to tag people. Did you mean to do that? I edited the previous post to change them to @ references.

**Review by tannewt — CHANGES_REQUESTED** [review]
Please add `doit_` to the start of the board name (its folder) because that is the manufacturer.

**Comment by m1cha1s** [comment]
@tannewt I've changed the name. @dhalbert thx for the fix :).

**Review by tannewt — DISMISSED** [review]
You'll need to delete the files for the old name (using `git rm`).

**Comment by Anutrix** [comment]
Any updates on this?

**Comment by m1cha1s** [comment]
@Anutrix everything should be fixed. The review is the only thing that needs to be done for it to be merged I believe.

**Review by dhalbert — APPROVED** [review]
Looks OK! Merging.

**Comment by dhalbert** [comment]
Thanks! Please make a PR to https://github.com/adafruit/[circuitpython-org](https://github.com/adafruit/circuitpython-org) if you have not already done so.

**Comment by VictorioBerra** [comment]
Should I be able to find this on the downloads page here https://circuitpython.org/downloads ?

Can someone tell me where I can download the Firmware?

**Comment by microdev1** [comment]
> Should I be able to find this on the downloads page here https://circuitpython.org/downloads ?
> 
> Can someone tell me where I can download the Firmware?

Yes, you can search for it in the downloads page. A direct link: https://circuitpython.org/board/doit_esp32_devkit_v1/

**Pull request merged**
