### PR TITLE
Switch to generic flash init for now

### PR DESCRIPTION
**Pull request by tannewt**
This will support more flash chips at the expense of a performance
hit when loading from the flash. This shouldn't hurt execution
performance in most cases because Python code is parsed and stored
in RAM.

We'll refine this with #4041

### CODE REVIEW

**Review by jepler — APPROVED** [review]
I see from internal comms that Limor tested this successfully.

**Comment by ladyada** [comment]
tested feather artifact, its good!

**Review by ladyada — APPROVED** [review]
tested both pico and feather 2040, both enumerate

**Comment by tannewt** [comment]
Superseded by #4308

**Pull request closed without merging**
