### PR TITLE
Adding support for M5Stack Stick C Plus

### PR DESCRIPTION
**Pull request by n0xa**
Based on the M5Stack Stick C Board, I modified the LCD settings so the display works at the higher resolution and is aligned with the screen boundaries. I added GPIO for the built-in speaker which was added to this version of the board, and verified the other GPIO pins match the data sheet from M5Stack.

### CODE REVIEW

**Comment by tannewt** [comment]
Please make a PR for the new creation ID here: https://github.com/creationid/creators/blob/main/creations/m5stack.md

Thanks!

**Comment by n0xa** [comment]
Thanks, I've got a PR open on the creators repository now.

**Comment by dhalbert** [comment]
I approved and merged the creation id PR.

Just to be clear, do you have one of these, and did you test the build? Thanks.

**Comment by n0xa** [comment]
I do have one. The build runs Hello World. Photo of screen attached. It is not showing up as a circuitpy drive and I haven't gotten REPL to work via USB. I can list files over USB with adafruit-ampy, which I'm not too familiar with but found during my troubleshooting. Ampy get fails on module ubinascii. Additional guidance is welcome. I'm in the discord channel.

**Comment by n0xa** [comment]
Following up: REPL works fine from USB serial if I specify the baud rate. WebSerial ESPTool works, Wifi works, and I can upload libraries and code to it through the wifi web file browser. From my end, I'm happy with this and I'm actively using it. Let me know if anything else is needed.

**Review by tannewt — APPROVED** [review]
circuitpy drive won't work because the ESP32 doesn't have native USB. This is good enough. Thanks!

**Pull request merged**
