### PR TITLE
Enabling gifio on Meowbits

### PR DESCRIPTION
**Pull request by dglaude**
Based on suggestion by deʃhipu to help katylase on #help-with-circuitpython

### CODE REVIEW

**Comment by dhalbert** [comment]
Not all the translations fit, sorry!

**Comment by dhalbert** [comment]
You could turn off `CIRCUITPY_BLEIO_HCI`, that is probably less popular than `gifio` would be.

**Comment by deshipu** [comment]
I didn't know meowbits had ble...

**Comment by dhalbert** [comment]
> I didn't know meowbits had ble...

They don't, that is for attaching an external AirLift.

**Comment by dglaude** [comment]
Are you sure GIFIO is still enable?
It feel like it has been lost in the diff, I don't see the line, nor as =0 nor as =1. Or by default if it is not there it is =1?

**Comment by dhalbert** [comment]
> Are you sure GIFIO is still enable? It feel like it has been lost in the diff, I don't see the line, nor as =0 nor as =1. Or by default if it is not there it is =1?

It is on by default if `displayio` is on.

**Comment by Katylase** [comment]
Thanks guys! I'll try it right away!^^

**Review by jepler — APPROVED** [review]
Since this thing has a specific display type built in, disabling other displays makes sense as a trade-off.

**Pull request merged**
