### PR TITLE
Full UART support for RPI

### LINKED ISSUE #5650: Broadcom build for RPI 4B not booting
This issue is so there is a place to track troubleshooting. I realize the Broadcom build is pre-alpha....

I have built CP for both the RPI Zero 2W and the 4B.
When I connect a USB to Serial converter to GND, TX,RX on the Zero 2W it boots to the REPL as expected.

When I try the same on the 4B, I see no output on the serial port.
If I connect an HDMI monitor, I see no text to the screen, but it does go to a large multicolored square on the display.

I'm curious if anyone else has tried the 4B? 
If you have, could you post or post a a link to the working .zip file so I can try it.

I have tried 7.1.0-beta.1 from circuitpython.org as well just to verify it is not my build -- same results.

### PR DESCRIPTION
**Pull request by tannewt**
This adds PL011 UART support which is more plentiful.

It also:
* Fixes PI4 build by including .dtb files on the SD card.
* Enables the activity LED as the status LED on PI4 and CM4 I/O.
* Adds that LED as board.LED.

Fixes #5650 and progress on #5629

### CODE REVIEW

**Comment by jerryneedell** [comment]
Built locally and tested on RPi 4B -- Boots to REPL!!

**Review by dhalbert — DISMISSED** [review]
Thanks to @jerryneedell for testing. The logic looks good to me, but I did not test.

Good grief, 13k file changes everytime they change something?!
image

**Comment by jerryneedell** [comment]
FYI -- here is a dmesg output --- not seeing CIRCUTPY drive... not sure if it is expected ...
```
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: new full-speed USB device number 38 using xhci_hcd
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: New USB device found, idVendor=2e8a, idProduct=f001, bcdDevice= 1.00
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: Product: Raspberry Pi 4B
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: Manufacturer: Raspberry Pi
[Mon Dec  6 21:55:58 2021] usb 3-3.4.3: SerialNumber: 100000000A3D7CF5
[Mon Dec  6 21:55:58 2021] cdc_acm 3-3.4.3:1.0: ttyACM0: USB ACM device
[Mon Dec  6 21:55:58 2021] usb-storage 3-3.4.3:1.2: USB Mass Storage device detected
[Mon Dec  6 21:55:58 2021] scsi host8: usb-storage 3-3.4.3:1.2
[Mon Dec  6 21:55:58 2021] input: Raspberry Pi Raspberry Pi 4B Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.4/3-3.4.3/3-3.4.3:1.3/0003:2E8A:F001.0015/input/input60
[Mon Dec  6 21:55:58 2021] input: Raspberry Pi Raspberry Pi 4B Mouse as /devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.4/3-3.4.3/3-3.4.3:1.3/0003:2E8A:F001.0015/input/input61
[Mon Dec  6 21:55:58 2021] input: Raspberry Pi Raspberry Pi 4B Consumer Control as /devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.4/3-3.4.3/3-3.4.3:1.3/0003:2E8A:F001.0015/input/input62
[Mon Dec  6 21:55:58 2021] hid-generic 0003:2E8A:F001.0015: input,hidraw3: USB HID v1.11 Keyboard [Raspberry Pi Raspberry Pi 4B] on usb-0000:00:14.0-3.4.3/input3
[Mon Dec  6 21:55:59 2021] scsi host8: scsi scan: INQUIRY result too short (5), using 36
[Mon Dec  6 21:55:59 2021] scsi 8:0:0:0: Direct-Access     Raspberr Raspberry Pi 4B  1.0  PQ: 0 ANSI: 2
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: Attached scsi generic sg3 type 0
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] 59840513 512-byte logical blocks: (30.6 GB/28.5 GiB)
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] Write Protect is off
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] Mode Sense: 03 00 00 00
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] No Caching mode page found
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] Assuming drive cache: write through
[Mon Dec  6 21:55:59 2021]  sdd: sdd1
[Mon Dec  6 21:55:59 2021] sd 8:0:0:0: [sdd] Attached SCSI removable disk
[Mon Dec  6 21:56:04 2021] FAT-fs (sdd1): error, invalid access to FAT (entry 0x08202059)
[Mon Dec  6 21:56:04 2021] FAT-fs (sdd1): Filesystem has been set read-only
````

**Comment by jerryneedell** [comment]
WooHoo! I can even blink the LED

**Comment by jerryneedell** [comment]
Looks like something in this PR breaks the zero2w build...

**Comment by jerryneedell** [comment]
zero2w builds now -- thanks!

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
