### PR TITLE
mimxrt10xx: add 1050 support

### PR DESCRIPTION
**Pull request by hierophect**
Continues off of #2918, adding support for the imx.RT 1052 EVK board. Fixes to this PR include adding the new reset register values (based on reference manual), never_reset flash pin protections, and an updated SDK submodule. 

Currently not working - I don't believe the flash_config.c file is set up correctly. After loading the chip with a Jlink, the debugger reports a location that's partway into the program, not at the reset_handler as it should be. @arturo182 or @tannewt, do you have a sense for what could be going on with that?

### CODE REVIEW

**Comment by tannewt** [comment]
@hierophect My guess is that the flash data structures aren't correct and you are still in the ROM bootloader. You can use a logic analyzer on the SPI flash chip select line to see if code ends up being loaded off of it.

**Comment by hierophect** [comment]
@tannewt where could I find the configuration for that? On closer inspection of flash_config.c, it seems to be more or less identical across all the i.MX chips we support. I'll take a look at the SPI chip, but do you have a sense of which file I should be researching/tweaking to resolve the issue?

**Comment by tannewt** [comment]
@hierophect If you don't see more than a few reads to SPI flash, then I'd suggest reading the `9.7 Program Image` section of the reference manual and triple checking both the image vector table and the device configuration data. I also wouldn't trust JLink's reset because the problem is so early in the boot process. Plugging and unplugging will be a pain but it'll assure you that you are starting from zero.

**Comment by hierophect** [comment]
@sabas1080 were you successful in getting Circuitpython to load on the 1050 when you made your first PR?

**Comment by sabas1080** [comment]
Hi @hierophect 

I have been away from this project, I plan to return in about 3 weeks, my last status I have not loaded circuitpython to the board

**Comment by hierophect** [comment]
> I have been away from this project, I plan to return in about 3 weeks, my last status I have not loaded circuitpython to the board

No biggie, I'm shelving this for now to work on some other things.

**Comment by tannewt** [comment]
We're closing this for now because getting the dev kit going requires understanding hyperflash config. We'll reopen when ready to work on it again or create a new PR.

**Pull request closed without merging**
