### PR TITLE
Increase number of LWIP timers for MDNS (fixes #7333)

### LINKED ISSUE #7333: raspberrypi 8.0.0 socket exceptions when web workflow is enabled
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.5 on 2022-12-08; Raspberry Pi Pico W with rp2040
```

### Code/REPL

```python
import time
import traceback
import wifi
import socketpool
import ssl
import adafruit_requests
from secrets import secrets

TEXT_URL = "http://wifitest.adafruit.com/testwifi/index.html"

print("Connecting...")
wifi.radio.connect(secrets["ssid"], secrets["password"])
print("My IP address is", wifi.radio.ipv4_address)

pool = socketpool.SocketPool(wifi.radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())

while True:
    try:
        print("Fetching text from", TEXT_URL)
        response = requests.get(TEXT_URL)
        print("-" * 40)
        print(response.text)
        print("-" * 40)
    except Exception as e:
        traceback.print_exception(e, e, e.__traceback__)
    time.sleep(5)
```

### Behavior

The above code, slightly modified boilerplate internet connect code, does not work on `raspberrypi` 8.0.0-beta.5 when web workflow is enabled (wifi credentials in `.env` file).

Consistently gets exception:
```
Traceback (most recent call last):
  File "code.py", line 139, in get_http
  File "adafruit_requests.py", line 718, in post
  File "adafruit_requests.py", line 679, in request
OutOfRetries: Repeated socket failures
```
It seems that the timeout in requests is kicking in within the library. No data is received. Occasionally `ETIMEDOUT`.

Underlying exceptions to the `OutOfRetries` occur (discovered through some print-debugging in `adafruit_requests`) if a manual timeout is supplied. Exceptions are initially `OSError: [Errno 116] ETIMEDOUT` in `recv_into`, waiting for the `H` of `HTTP` to kick off the receive. Then `OSError: 32` in `_send` takes over on later requests. But again, sometimes there is no error, just no data received.

I suspect some low-level socket shenanigans. There should be 8 sockets available, web workflow uses at least one for the TCP `listen`, probably something for mDNS, and more with client(s) accessing web workflow features?

Interestingly If requests alternate between two URLs, after several failures for both, the second will succeed once. Rinse, repeat.

No issue with the above code on 8.0.0-beta.4, or on 8.0.0-beta.5 with web workflow disabled (no `.env` file).

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gneverov**
The proximate cause of this issue [here](https://github.com/adafruit/lwip/blob/239918ccc173cb2c2a62f41a40fd893f57faf1d6/src/core/timeouts.c#L188), where this memory allocation fails.
```
timeout = (struct sys_timeo *)memp_malloc(MEMP_SYS_TIMEOUT);
```
This raises two questions:
1. Why did the memory allocation fail?
2. Why wasn't the failure more fatal (e.g., crash instead of continue as usual)?

### Why did the memory allocation fail?
LWIP uses statically sized arrays from which it allocates each type of struct. In this case we exhausted the static array for the timeout struct. The size of the array is determined by `MEMP_NUM_SYS_TIMEOUT` which has some preprocessor magic to calculate the maximum number of allocations needed, so we should never run out. However this macro only knows about stuff in lwip/core; it doesn't know about lwip/apps.

From lwip/apps, we use mdns. In the code for mdns, there is this well hidden [comment](https://github.com/adafruit/lwip/blob/239918ccc173cb2c2a62f41a40fd893f57faf1d6/src/apps/mdns/mdns.c#L11):
```
You need to increase MEMP_NUM_SYS_TIMEOUT by one if you use MDNS!
```
So we need to manually increase the value of MEMP_NUM_SYS_TIMEOUT in lwip/core from 7 to 8 and unfortunately we can't use the magic macro calculation anymore.

But it doesn't end there! A different mdns [file](https://github.com/adafruit/lwip/blob/239918ccc173cb2c2a62f41a40fd893f57faf1d6/src/apps/mdns/mdns_out.c), allocates a further 3 timers per IP version. And unlike the first file, there doesn't appear to be a comment to increase MEMP_NUM_SYS_TIMEOUT to compensate.

So that is how the new value of MEMP_NUM_SYS_TIMEOUT is calculated and it is sufficient to fix the issue.

### Why wasn't the failure more fatal?
When the memory allocation fails, the code calls `LWIP_ASSERT`, which in turn calls `LWIP_PLATFORM_ASSERT`, which is defined [here](https://github.com/raspberrypi/pico-sdk/blob/2e6142b15b8a75c1227dd3edbe839193b2bf9041/src/rp2_common/pico_lwip/include/arch/cc.h#L72):
```
#define LWIP_PLATFORM_ASSERT(x) do { if(!(x)) while(1); } while(0)
```
The problem is that the parameter, `x`, to `LWIP_PLATFORM_ASSERT` is not the assert predicate, but the assert message. The message string constant is statically non-null, so this whole macro simplifies into a no-op instead of an infinite loop. This means the assert after the memory allocation failure does nothing and the program continues normally instead of halting, which would be appropriate for this non-recoverable error.

The fix for this is of course trivial; it's not necessary to fix #7333, but it is useful to catch similar bugs earlier. Currently Adafruit does not maintain its own fork of pico-sdk, so I will submit the PR to Raspberry Pi. Unless someone thinks it is worthwhile to create the fork.

### CODE REVIEW

**Review by DavePutz — COMMENTED** [review]
Tested and confirmed that this fixes issue #7333

**Comment by dhalbert** [comment]
@gneverov Could you change the base to `8.0.x` and I will get this in the next 8.0.x release? Thanks!

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by gneverov** [comment]
BTW, it turns out the `LWIP_PLATFORM_ASSERT` secondary issue is already fixed in the upstream pico-sdk. Perhaps you want to update the circuitpython submodule.

**Pull request merged**
