### PR TITLE
Add A Pirate Translation (English)

### PR DESCRIPTION
**Pull request by sommersoft**
Obviously, Pirate is not (yet) an official language. However, I think its a fun idea that @CedarGroveStudios inadvertently suggested.

This is meant to be a community effort. I only did a handful of translations just to get it started.

Mr. Certainly has expressed in interest in helping, and @ATMakersBill mentioned he has an affiliation with [ITLAP](http://talklikeapirate.com/wordpress/).

For the IETF language code, I used `en_x_pirate`, utilizing the "private-use" subtag.

Lastly, for the record, I am not fluent in Pirate. But I be tryin'! ☠️

### CODE REVIEW

**Comment by siddacious** [comment]
I plan on updating all my build aliases to use this but yea, I'm not sure it's worth the travis tax. We can still do builds for announced releases, right?

**Comment by sommersoft** [comment]
> do we like this enough to pay the cost of longer Travis build times

Fair point. I'm not married to an ever-present Pirate translation. Maybe turn it on around International Talk Like A Pirate Day? A "target audience" in my head is the teaching community; "today kids, we'll be programming like pirates". Lofty goals, I know. :smile:

Is there currently a way to turn off any particular translation in the Makefile? I can gladly update it with this PR.

**Comment by tannewt** [comment]
We could but not building on Travis means it may not build at release time.
Right now all assets are built and uploaded automatically. I think its ok
to turn on if you really want it. It only incurs ~10 seconds per board.
Adding a new board is more costly.

**Comment by kattni** [comment]
It seems worth it as a vector for bringing in new contributors, and giving them an easy option to see their contributions in action. I think it could be a fun way to get more people involved, as sommersoft pointed out with education and so on. But I understand the choice to not include it as well.

**Comment by tannewt** [comment]
I agree with @kattni. I think its worth the extra couple minutes of build time.

**Pull request merged**
