### PR TITLE
Enable CS "active-high" device support

### PR DESCRIPTION
**Pull request by michthom**
Reference issue #71 in Adafruit_CircuitPython_BusDevice
Enables SPIDevice to be used for devices which requires CS to be active high.
Adds a new boolean parameter cs_active_value.
Linked PR raised against Adafruit_CircuitPython_BusDevice

### CODE REVIEW

**Review by gamblor21 — COMMENTED** [review]
The changes look good to me but I have not had a chance to test them out. I will look at the library PR as well to see how they compare. I set the workflow to run to make sure it builds.

**Comment by michthom** [comment]
@gamblor21 I've no idea why one translation (Japanese) failed for one board (pyb_nano_v2) - any idea how I'd find out?

**Comment by gamblor21** [comment]
> @gamblor21 One translation (Japanese) failed for one board (pyb_nano_v2) - `Too little flash!!!` - does this mean that there should be an exclusion for this language on this board (I can see some others are already skipped: `Note: Not building languages {'cs', 'el', 'hi', 'ko'}`)?

The build was short of space. This module does not have to be in the core so add the line:
`CIRCUITPY_BUSDEVICE = 0`
to the file `ports/stm/boards/pyb_nano_v2/mpconfigboard.mk` right at the end. This will remove the module from the core.

Let me know if you cannot find where.

**Comment by dhalbert** [comment]
@michthom We don't exclude language builds for a particular board. Instead we shrink the build in some way so it accommodates all the languages available. The excluded languages you see are excluded for all builds, because their translations are very incomplete.

**Comment by michthom** [comment]
@gamblor21 Hopefully this is ready for a new build test now.

**Comment by michthom** [comment]
@gamblor21 Looks like all of the espressif builds failed but at a common point - installing the IDF tools, so I'm presuming this is nothing I can fix in my code?

**Comment by gamblor21** [comment]
> @gamblor21 Looks like all of the espressif builds failed but at a common point - installing the IDF tools, so I'm presuming this is nothing I can fix in my code?

Yeah I'm not sure why those failed. The build that previously failed now passed.

**Comment by microDev1** [comment]
The espressif build failure is due to esp-idf cache key. Please do a merge from upstream after PR #5386 is merged.

**Comment by michthom** [comment]
@microdev1 @gamblor21 I've pulled from upstream and can see the IDF cache key fix is in my fork now, so it should be safe to rerun the build prior to review / merge.

**Comment by gamblor21** [comment]
> @microDev1 @gamblor21 I've pulled from upstream and can see the IDF cache key fix is in my fork now, so it should be safe to rerun the build prior to review / merge.

You will have to push a nothing commit to the PR and then it should build correctly against the latest merged code.

**Review by dhalbert — APPROVED** [review]

**Comment by gamblor21** [comment]
@michthom Thanks for all your work working through this and the library build. And congrats on your first PR! 👏

**Comment by michthom** [comment]
@gamblor21 Team effort - I certainly needed your support.

**Pull request merged**
