### PR TITLE
Restore default epoch to 1970

### LINKED ISSUE #4893: 7.0.0-alpha.3 time.mktime() returns wrong seconds
```py
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit FunHouse with ESP32S2
>>> import time
>>> 
>>> s = time.mktime((2021, 06, 16, 20, 0, 0, -1, -1, -1))
>>> s
1623873600
>>> 
```
vs.
```py
Adafruit CircuitPython 7.0.0-alpha.3 on 2021-06-03; Adafruit FunHouse with ESP32S2
>>> import time
>>> 
>>> s = time.mktime((2021, 06, 16, 20, 0, 0, -1, -1, -1))
>>> s
677188800
>>> 
```

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #4893. Rolls back changing the epoch to 2000, which happened due to #4744.

### CODE REVIEW

**Comment by anecdata** [comment]
LGTM
```py
Adafruit CircuitPython 7.0.0-alpha.3-493-gb830eccbf on 2021-07-02; Adafruit MagTag with ESP32S2
>>> import time
>>> 
>>> s = time.mktime((2021, 06, 16, 20, 0, 0, -1, -1, -1))
>>> s
1623873600
>>> time.time()
1625220470
>>> time.localtime(s)
struct_time(tm_year=2021, tm_mon=6, tm_mday=16, tm_hour=20, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=167, tm_isdst=-1)
>>> time.localtime(time.mktime((2021, 06, 16, 20, 0, 0, -1, -1, -1)))
struct_time(tm_year=2021, tm_mon=6, tm_mday=16, tm_hour=20, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=167, tm_isdst=-1)
>>> time.mktime(time.localtime(s))
1623873600
```

**Comment by jepler** [comment]
What's the impact of this on builds without long ints?

**Comment by dhalbert** [comment]
> What's the impact of this on builds without long ints?

The `time`, etc. operations that depend on longints are still turned off at compile-time by a longint check, not by checking which epoch is in use. So I think this should be fine. Before the merge from upstream, we were using 1970 as the epoch.

**Review by jepler — APPROVED** [review]
OK, now I understand better about the effect on non-express boards and agree that we can make this change across the (er) board.

**Pull request merged**
