### PR TITLE
Update stage library to use keypad module on pygamer and pybadge

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by cwalther** [comment]
While we’re updating `stage`, have you taken a look at https://github.com/python-ugame/circuitpython-stage/pull/14?

**Comment by deshipu** [comment]
Ouch, I missed it, even though I now have an e-mail filter specially for this. I guess I will need to make that change to all three files now.

**Comment by cwalther** [comment]
Possible – I don’t have a PyBadge or PyGamer so I didn’t check what keys they have and how they are handled.

**Comment by deshipu** [comment]
Updated now to include @cwalther's fix.

**Review by microDev1 — APPROVED** [review]
LGTM! Thanks @deshipu.

**Pull request merged**
