### PR TITLE
Add floppyio

### PR DESCRIPTION
**Pull request by jepler**
Initially enabled for samd51, this enables reading raw flux data as well as DOS/MFM formatted media.

This is only the low-level code for reading & decoding flux pulses from a floppy drive. high level details will live in a Python library.

[Adafruit_CircuitPython_floppy](https://github.com/jepler/adafruit_circuitpython_floppy) takes care of details like stepping from track to track, etc.

### CODE REVIEW

**Comment by jepler** [comment]
Let's hold this for a bit, @ladyada wants to re-org files in Adafruit_Floppy, which we submodule here.

**Comment by dhalbert** [comment]
@jepler Are you still waiting for a review? I thought you might be still churning this on a daily basis.

**Comment by jepler** [comment]
I think there'll still be churn before this is really ready to go in, so we can close it or switch it to draft.

**Comment by dhalbert** [comment]
I made it draft, np.

**Comment by jepler** [comment]
I need to go through a round of testing on this, but we decided to go ahead with this limited functionality in CircuitPython. Most users will probably want to use Arduino for more advanced stuff (or just the gw-compatible firmware), and that's OK.

After I re-test mfm floppy reading on hardware, I'll set this as ready for review.

**Comment by jepler** [comment]
I brought this up to date and re-tested with a Feather M4 & 5.25" floppy drive.

**Review by dhalbert — APPROVED** [review]
Great work! Will merge to get it available.

**Pull request merged**
