### PR TITLE
Espressif ESP32 DevKit Board Definitions: esp32 devkitc v4 wrover and wroom-32e

### PR DESCRIPTION
**Pull request by dlizotte-uwo**
These are board definitions for these older ESP32 devkits from Espressif:

[https://www.digikey.ca/en/products/detail/espressif-systems/ESP32-DEVKITC-VE/12091812](https://www.digikey.ca/en/products/detail/espressif-systems/ESP32-DEVKITC-VE/12091812)

(ESP32, 8MB SPI flash, 8MB SPIRAM) which I have, and

[https://www.adafruit.com/product/3269](https://www.adafruit.com/product/3269)

(ESP32, 4MB SPI flash, no SPIRAM) which I don't have. (Same board, different modules.) Built and tested on the WROVER version; the web workflow works great.

### CODE REVIEW

**Comment by tannewt** [comment]
Please run pre-commit on your changes: https://learn.adafruit.com/improve-your-code-with-pylint/check-your-code-with-pre-commit

**Comment by dlizotte-uwo** [comment]
Sorry about that - now realize I forgot to figure out/request VID and PID. I'll do that.

**Comment by dlizotte-uwo** [comment]
Should be set I think. One thing: I specified 'qio' for the SPI mode of flash and psram but I am not 100% sure that is correct (or if it matters) for the ESP32. I think you folks know what is best?

**Comment by tannewt** [comment]
> Should be set I think. One thing: I specified 'qio' for the SPI mode of flash and psram but I am not 100% sure that is correct (or if it matters) for the ESP32. I think you folks know what is best?

That is usually right. Did you confirm it works?

**Comment by dlizotte-uwo** [comment]
> > Should be set I think. One thing: I specified 'qio' for the SPI mode of flash and psram but I am not 100% sure that is correct (or if it matters) for the ESP32. I think you folks know what is best?
> 
> That is usually right. Did you confirm it works?

Works on the WROVER board, but I do not have the other board to try.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
