### PR TITLE
remove CIRCUITPY_ESP_FLASH_MODE and CIRCUITPY_ESP_FLASH_FREQ

### PR DESCRIPTION
**Pull request by dhalbert**
`CIRCUITPY_ESP_FLASH_MODE` and `CIRCUITPY_ESP_FLASH_FREQ` were present in all espressif `mpconfigboard.mk` files. They were frequently wrong, and caused confusion. They were used only to pass flash mode and frequency arguments to `esptool.py`, but they don't appear to be necessary (anymore?). `esptool.py` works fine without them, as far as I can tell. I have my own `esptool.py` aliases that don't use them.

This PR removes these settings and their uses in `ports/espressif/Makefile`.

Quoting from https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-commands.html:

> ### Setting Flash Mode and Size
> You may also need to specify arguments for flash mode and flash size, if you wish to override the defaults. For example:
> ```
> esptool.py --port /dev/ttyUSB0 write_flash --flash_mode qio --flash_size 32m 0x0 bootloader.bin 0x1000 my_app.bin
> ```
> Since esptool v2.0, these options are not often needed as the default is to keep the flash mode and size from the .bin image file. See the [Flash Modes](https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/flash-modes.html#flash-modes) section for more details.

Note that `CIRCUITPY_ESP_FLASH_SIZE` _is_ used for useful purposes, and was not removed.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Thanks!

**Review by MicroDev1 — CHANGES_REQUESTED** [review]
I ran a couple of `esptool.py --chip esp32s2 image_info --version 2 build-microdev_micro_s2/circuitpython-firmware.bin` queries:
```python
esptool.py v4.3

# BEFORE:

ESP32S2 image header
====================
Image version: 1
Entry point: 0x4002b814
Segments: 8
Flash size: 16MB
Flash freq: 80m
Flash mode: QIO

# AFTER:

ESP32S2 image header
====================
Image version: 1
Entry point: 0x4002bddc
Segments: 7
Flash size: 1MB
Flash freq: 40m
Flash mode: QIO
```
Following is the serial output of the `DEBUG=1` build.
```python
I (62) boot.esp32s2: SPI Speed      : 40MHz
I (67) boot.esp32s2: SPI Mode       : DIO
I (72) boot.esp32s2: SPI Flash Size : 16MB
...
I (1015) spi_flash: detected chip: winbond
I (1020) spi_flash: flash io: dio
```
The build does run but it seems like the flash speed and mode are wrong.
Note: The above test was done with `idf@v5.0` as `idf@v4.4` doesn't have `esptool.py image_info --version 2` flash data.

**Comment by dhalbert** [comment]
@MicroDev1 Ah, the flash size is used to create the .bin. I removed that from the Makefile; that is wrong. Pushing a new commit.

**Comment by dhalbert** [comment]
Sorry. Closing: the basic premise of this PR is wrong: the `CIRCUITPY_ESP_FLASH_MODE` and `CIRCUITPY_ESP_FLASH_FREQ values are needed by `esptool.py elf2image`.

That doesn't mean that the values for the boards are right; a lot of people copy them blindly.

**Pull request closed without merging**
