### PR TITLE
Reuse "Not connected" message in bleio

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by deshipu** [comment]
I need to wait for the other pull request to merge, so that I can run ``make translate`` — to avoid conflicts.

**Comment by dhalbert** [comment]
Could you merge from upstream? I think your PR may be reverting the updates to the frozen libraries.

**Comment by deshipu** [comment]
I tried this:
```
sheep@ghostwheel:~/dev/circuitpython/circuitpython$ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
sheep@ghostwheel:~/dev/circuitpython/circuitpython$ git pull git@github.com:adafruit/circuitpython.git
From github.com:adafruit/circuitpython
 * branch                HEAD       -> FETCH_HEAD
Already up to date.
sheep@ghostwheel:~/dev/circuitpython/circuitpython$ git checkout typo3
M	frozen/Adafruit_CircuitPython_BusDevice
M	frozen/Adafruit_CircuitPython_HID
M	frozen/Adafruit_CircuitPython_Motor
M	frozen/Adafruit_CircuitPython_NeoPixel
M	frozen/Adafruit_CircuitPython_seesaw
Switched to branch 'typo3'
Your branch is up to date with 'origin/typo3'.
sheep@ghostwheel:~/dev/circuitpython/circuitpython$ git rebase master
Current branch typo3 is up to date.
sheep@ghostwheel:~/dev/circuitpython/circuitpython$ git push --force
Everything up-to-date
```

**Comment by deshipu** [comment]
I think I got it now. The submodule stuff seems to be somehow tracked outside of the normal repository and is ignored by rebase.

**Pull request merged**
