### PR TITLE
Add new board to nrf port: holyiot_nrf52840

### PR DESCRIPTION
**Pull request by Edrig**

### CODE REVIEW

**Comment by ladyada** [comment]
@Edrig hi please get unique PID/VID for this board, you cannot re-use an adafruit USB identifier!
also check some text formatting issues noted in
https://github.com/adafruit/circuitpython/pull/3610/checks?check_run_id=1311673547

**Comment by tannewt** [comment]
Is this a module?

**Review by tannewt — CHANGES_REQUESTED** [review]
Ah, so holyriot isn't actually the manufacturer. Please name based on the board, not the module.

**Comment by Edrig** [comment]
@tannewt we change the board name to ADM_B_NRF52840_1 (AtelierDuMaker_Breakout_NRF52840_1 for first version)

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!

**Comment by tannewt** [comment]
Don't forget to add your board to circuitpython.org: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Comment by dhalbert** [comment]
Ping for @Edrig:

> Don't forget to add your board to circuitpython.org: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Pull request merged**
