### PR TITLE
Optionally parallelize the testsuite

### PR DESCRIPTION
**Pull request by jepler**
On my laptop with a 4-thread, 2-core CPU, this reduces the elapsed time taken to run the tests by about 50%.  Here are some timings, though they're actually of micropython, not circuitpython:
```\
Elapsed time, seconds, best of 3 runs with each -j value:

before patchset: 18.1
            -j1: 18.1
            -j2: 11.3  (-37%)
            -j4:  8.7  (-52%)
            -j6:  8.4  (-54%)
```

This is the CircuitPython version of micropython/micropython#3694

### CODE REVIEW

**Comment by jepler** [comment]
Sooooo this appears to actually slow down travis builds down in elapsed time. :frowning:

**Comment by tannewt** [comment]
I see it ~30 seconds longer for the unix part of the test. I'm willing to pay that price because it speeds it up for you locally. :-)

**Comment by dhalbert** [comment]
We could put in a check for travis vs local.

**Comment by jepler** [comment]
@dhalbert just change each `--auto-jobs` to -j1 in `.travis.yml`, I think.

**Pull request merged**
