### PR TITLE
Update protomatter to latest commit

### PR DESCRIPTION
**Pull request by MicroDev1**
Support psram rgbmatrix on all esp32 variants.
Note: Pending PR: https://github.com/adafruit/Adafruit_Protomatter/pull/55

### CODE REVIEW

**Comment by jepler** [comment]
Thanks for grabbing this.

What testing did you perform? Is this change alone sufficient to make protomatter work on such boards?

In CircuitPython, it looks like we unconditionally define _PM_allocate: `shared-module/rgbmatrix/allocator.h:#define _PM_allocate common_hal_rgbmatrix_allocator_impl`. I am surprised that does not need to change for this to work.

**Comment by MicroDev1** [comment]
> What testing did you perform? Is this change alone sufficient to make protomatter work on such boards?

I haven't tested this.

**Comment by jepler** [comment]
I can confirm that protomatter 1.5.3 does _NOT_ work as-is on Adafruit Feather ESP32-S3 TFT.  But we don't want to use an unreleased protomatter either. 1.5.2 doesn't build, and the commit in this PR is a non-accepted PR, not a release.

With modifications I can get the matrix to come up _once_ but not a second time (including over soft reset). The code runs, but no display is visible.

Possibly because the featherwing uses TX and RX pins, running in DEBUG= mode makes it crash.

I will continue debugging this, since I have access to hardware.

**Comment by MicroDev1** [comment]
Closing this as the changes are unpolished.

**Pull request closed without merging**
