### PR TITLE
Freeze adafruit_requests and adafruit_esp32spi into mimxrt1011 Feathers

### PR DESCRIPTION
**Pull request by arturo182**

### CODE REVIEW

**Comment by arturo182** [comment]
Note, this is only for my 1011 Feather, not the M7 1011, should I freeze these into that one too?

**Comment by ladyada** [comment]
yep!

**Comment by ladyada** [comment]
ok by the time i get home this should be ready to merge :)

**Comment by arturo182** [comment]
@dhalbert was a bit reluctant about merging stuff just before the 5.0.0 release, but up to you :)

**Comment by ladyada** [comment]
ill let @dhalbert decide as this is not code related and imx is super alpha 😀

**Comment by dhalbert** [comment]
I have already made a `5.0.x` branch, so we are free to merge new stuff into `master`, and I'll go ahead. We can choose  to merge these and further changes into `5.0.x` for `5.0.0` now or later. I'm thinking about maybe making an `rc.1` soon just to test the new download links, so I might merge this in to help test that.

**Pull request merged**
