### PR TITLE
`stop_station` when no wifi-reconnect

### PR DESCRIPTION
**Pull request by bill88t**
Closes https://github.com/adafruit/circuitpython/issues/8369.
@anecdata

### CODE REVIEW

**Comment by anecdata** [comment]
the only artifact is mpy-cross?

**Review by tannewt — CHANGES_REQUESTED** [review]
How does this work on ESP? This shared supervisor code shouldn't need port-specific defines.

**Comment by bill88t** [comment]
> the only artifact is mpy-cross?

No idea man. Actions sus.

> How does this work on ESP? This shared supervisor code shouldn't need port-specific defines.

@tannewt  This PR exists to just make `raspberrypi` act the same way as `espressif`.
The espressif` wifi connection is not preserved upon reload, however the `raspberrypi` one is, since the object is persistent. With this change, both will close their wifi connection on reload.

**Comment by tannewt** [comment]
> the only artifact is mpy-cross?

This must be a bug in the build matrix script.

> @tannewt This PR exists to just make `raspberrypi` act the same way as `espressif`.

I understand that. My intention was to ask how that behavior was implemented on ESP. My goal is to remove the special case from the supervisor code. ESP doesn't need it and therefore RP2 shouldn't either. The wifi reset must happen in some other call on ESP and RP2 should copy that.

**Comment by bill88t** [comment]
Ok, now picow uses `wifi_reset` like how esp does.
Wifi reset meant to reset the wifi, but disconnecting it is the best we can do right now.
With this `wifi.radio.enabled = False` now also disconnects both STA and AP.

**Review by anecdata — APPROVED** [review]
Tested articfact `Adafruit CircuitPython 9.0.0-alpha.1-52-g034caf701d on 2023-09-28; Raspberry Pi Pico W with rp2040`...

Confirmed no regression with web workflow / auto-connect enabled:
• after reload or soft reset, station is connected to wifi.

With web workflow / auto-connect not enabled:
• connected station is disconnected after reload or soft reset
• AP is not active after reload or soft reset
• connected station is disconnected and AP is not active after `wifi.radio.enabled = False`

Thanks, @bill88t

**Review by tannewt — APPROVED** [review]
Awesome! That looks much better. Thank you!

**Pull request merged**
