### PR TITLE
ESP32 USE uart_param_config

### LINKED ISSUE #6254: ESP32-S3 and S2 issues with uarts - data output corrupt
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0-beta.0 on 2022-04-01; ESP32-S3-DevKitC-1-N8R2 with ESP32S3
```

### Code/REPL

```python
>>> import board, busio
>>> uart1 = board.UART()
>>> uart1.deinit()
>>> uart1 = busio.UART(board.TX, board.RX, baudrate=38400)
>>> uart2 = busio.UART(board.IO17, board.IO18, baudrate=38400)
>>> uart1.write(b'abcdefghijklmnopqrstuvwxyz')
26
>>> uart2.write(b'abcdefghijklmnopqrstuvwxyz')
26
>>>
```

### Behavior

Wrong data output,  looks like maybe a queue issue:  Here is what was seen on the Logic Analyzer

For uart1:
image

For uart2:
image

### Description

_No response_

### Additional information

Note: I also tried this with baud of 1000000 and also the data output was not correct.

### PR DESCRIPTION
**Pull request by KurtE**
Use this function instead of several individual configuration functions
to configure such things as Baud rate, transfer size, stop bits,
parity...

This function also resets both the RX and TX Hardware Fifo
reset functions are called to setup the hardware.

This is a First attempt at what was mentioned in issue.

If it works:
resolves #6254 

My initial tests are working,  
Would be good if others tried this and see if other configurations of UARTS work with this change.

### CODE REVIEW

**Comment by ThomasAtBBTF** [comment]
Hi,
I see and understand what you are changing. 
But do we know the **root cause** of the problem?
I would feel better if we could point to the code where the problem is and not just do it differently.
Btw: can you provide a UF2 for your build? I am happy to test. (I have nearly every ESP32-S3 board model and also some ESP32-S2)

**Comment by KurtE** [comment]
@ThomasAtBBTF and all,

> Hi,
> I see and understand what you are changing.
> But do we know the **root cause** of the problem?
> I would feel better if we could point to the code where the problem is and not just do it differently.
> Btw: can you provide a UF2 for your build? I am happy to test. (I have nearly every ESP32-S3 board model and also some ESP32-S2)

From the best I can tell from the debugging, the main issue is that the hardware FIFO queues are not properly setup.  It appears like the main functions for doing this in the IDF were the calls to:
```
    uart_hal_rxfifo_rst(&(uart_context[uart_num].hal));
    uart_hal_txfifo_rst(&(uart_context[uart_num].hal));
```
And these functions do not have any higher level wrappers defined on them to allow them to be called outside of the IDF.  Except for the main configuration function that this switched to using. 

But again *warning* I am not an ESP32 user,  So if someone knows this better and can fix it, in a better way, that would be great. 

Again I have not done a complete exhaustive test of all of the possible configurations of UART options, but as I mentioned in last posting in issue, that the test sketch there which daisy chains one UART to the next back to the first now worked.

I also hacked up a test sketch on the S3, that does a few different options:

```
# version to test different settings and see that we see it in the hardware.
import time
import board
import busio
import supervisor
from digitalio import DigitalInOut, Direction, Pull

uarts = []
board.UART().deinit()
uarts.append( busio.UART(board.IO6, board.IO7, baudrate=9600, bits=7, parity=busio.UART.Parity.EVEN, stop=2, 
            timeout=0.25, receiver_buffer_size=255))
uarts.append(busio.UART(board.IO16, board.IO17, baudrate=115200, stop=1, timeout=0.25, receiver_buffer_size=255))
uarts.append(busio.UART(board.IO10, board.IO11, baudrate=1000000, stop=2, timeout=0.25, receiver_buffer_size=255))
for uart in uarts:
    uart.reset_input_buffer()

def EchoTextBack(uart, b):
    index = uarts.index(uart)
    uart.write(b)
    
    data = uart.read()
    print("(", index, ")>> in:", b, " Out", data, "EQ? ", b == data) 

while True:

    text = input()
    print("*** Serial input ***", text)
    b = bytearray()
    b.extend(text)

    for uart in uarts:
        EchoTextBack(uart, b)
    time.sleep(0.5)

```

Where I did loop back test by connecting the TX to the RX of each uart...
And they appear to be looping back
```
code.py output:
abcdefghijklmnopqrstuvwxyz
*** Serial input *** abcdefghijklmnopqrstuvwxyz
( 0 )>> in: bytearray(b'abcdefghijklmnopqrstuvwxyz')  Out b'abcdefghijklmnopqrstuvwxyz' EQ?  True
( 1 )>> in: bytearray(b'abcdefghijklmnopqrstuvwxyz')  Out b'abcdefghijklmnopqrstuvwxyz' EQ?  True
( 2 )>> in: bytearray(b'abcdefghijklmnopqrstuvwxyz')  Out b'abcdefghijklmnopqrstuvwxyz' EQ?  True
1234567890
*** Serial input *** 1234567890
( 0 )>> in: bytearray(b'1234567890')  Out b'1234567890' EQ?  True
( 1 )>> in: bytearray(b'1234567890')  Out b'1234567890' EQ?  True
( 2 )>> in: bytearray(b'1234567890')  Out b'1234567890' EQ?  True
```

I then removed the jumpers and hooked up LA to TX pins to verify the stuff:
And from high level you can see must be different baud rates:
image

The 9600 7E: (Note just showing part of output)
image

115200: 
image

1MBS 2 stop bits:
image

**Comment by KurtE** [comment]
>... Btw: can you provide a UF2 for your build? I am happy to test. (I have nearly every ESP32-S3 board model and also some ESP32-S2)

@tannewt @ladyada - Was wondering with your pre-build checks, It looks like it builds all of the boards... 

Question I wondered about, was are those saved?  That is if someone like @ThomasAtBBTF wishes to test out a change such as this one, without having to setup to build everything, what is the best way to do this?  

I did upload zip file which contained the .uf2 for of the two boards I was testing with. 

Thanks
Kurt

**Comment by ThomasAtBBTF** [comment]
I think I will have a working build-VM on a server by next week.
I already had this once for Version 5 and the ItsyBitsy M4
But this is outdated and needs a clean reinstall.
What certainly would be helpful would be an image of such a VM somewhere in the cloud.

**Comment by ladyada** [comment]
artifacts are built for all PRs through actions CI - go to the CI run summary and scroll down to find the zip for your board :)
e.g. for the run above
https://github.com/adafruit/circuitpython/actions/runs/2425263098

**Comment by KurtE** [comment]
> artifacts are built for all PRs through actions CI - go to the CI run summary and scroll down to find the zip for your board :) e.g. for the run above https://github.com/adafruit/circuitpython/actions/runs/2425263098

Thanks, I figured there may be something already setup :D

**Comment by ThomasAtBBTF** [comment]
Any estimation, when this pull request will be reviewed?

**Review by gamblor21 — COMMENTED** [review]
Looks good to me reading the code over. I'll see if I have a chance to test it on actual hardware today or tomorrow.

**Review by gamblor21 — APPROVED** [review]
The code changes all look good to me. I was able to test this on a FeatherS2 TFT and it worked. I don't have a S3 setup to test. I'll leave it unmerged pending any other reviewer having an opinion on it.

**Comment by KurtE** [comment]
> The code changes all look good to me. I was able to test this on a FeatherS2 TFT and it worked. I don't have a S3 setup to test. I'll leave it unmerged pending any other reviewer having an opinion on it.

I tested it on espressif_esp32s3_devkitc_1_n8r8 about 11 days ago, I believe.  as well as the FeatherS2. The only other one I could test on is a: espressif_esp32s3_devkitc_1_n8r2 and I have another S2 board (with 2 usb connectors).  

But not sure if that would give any additional information.

**Comment by ThomasAtBBTF** [comment]
I am happy to confirm, that with the "Absolute Newest" firmware on Amazon S3 the UART on my Adafruit Feather ESP32-S3 "no PSRAM" now works fine.

Thank you very much KurtE !

**Comment by KurtE** [comment]
You are welcome.

**Comment by ThomasAtBBTF** [comment]
Over time I continued to have problems with the TX-Queue on my ESP32S3 board during development. During the first run of every CircuitPython program after power up and a hard reset, all is fine and remains fine while the initial CircuitPython program is running.
However, when breaking with control-c or uploading a next version of the CircuitPython application the TX-queue went “out of sync”.  (Note that calling microcontroller.reset()  in such a situation does not fix the problem! Only power on or pressing reset works.)
With this I mean, probably the head and tail pointer of the TX-queue is not reset correctly. This can be observed, by continuing to send characters over the UART and after a while, these characters war “appearing” on the “other side” of the serial line.
Observing the behavior, I found out that the offset is always 126 characters!
So I started guided by KurtE’s findings to look at the esp-idf code.

Without having good documentation and no real guide on how CP library functions are implemented and finally executed in c-code, I was looking where uart_hal_rxfifo_rst / uart_hal_txfifo_rst are called inside the esp-idf and also where uart_hal_rxfifo_rst / uart_hal_txfifo_rst is implemented.

I found that `uart_hal_rxfifo_rst / uart_hal_txfifo_rst` are implemented in \esp-idf\components\uart_hal_iram.c as wrappers for `uart_ll_rxfifo_rst / uart_ll_txfifo_rst`.
Not understanding clearly where and when uart_hal_rxfifo_rst / uart_hal_txfifo are actually called and where the call to uart_hal_txfifo is missing, I decided to try a “ugly hack”.
Assuming that calling uart.reset_input_buffer() eventually would end up in uart_hal_rxfifo_rst, I added a call to uart_ll_txfifo_rst there.

So the `uart_hal_rxfifo_rst` finally looks like so:
```
void uart_hal_rxfifo_rst(uart_hal_context_t *hal)
{
    uart_ll_rxfifo_rst(hal->dev);
    uart_ll_txfifo_rst(hal->dev);
}

```
Building  CP 7.3.3 with this hack solves the problem!
Hopefully, someone with a better understanding can come up with a more appropriate fix.

**Pull request merged**
