### PR TITLE
Esp32s2 protomatter

### PR DESCRIPTION
**Pull request by jepler**
This is now pretty stable ~~until you involve wifi(?)~~.  I tested:
 * Running an animation directly on the framebuffer
 * Creating a terminal, typing in it
 * Running a dogecoin price display (wifi)
In each case, I made sure to do it across multiple (between 8 and 16) soft resets, as that had been a bug initially.  It went from 99% fail to 0 fail so it is either entirely fixed or is super rare now.

I used a 16x32 matrix for initial tests, with separate power from a 5V 2A adapter.  For the doge test, I switched to 64x32.  No physical modification of the RGB Matrix Shield was required.

~~However, when soft resetting from a wifi demo, or encountering an exception in it, it usually crashes now.~~

~~This works well enough to do a framebuffer demo but only with specific pins, and it tends to crash after a soft reset.~~

Framebuffer rainbow demo:
```python
import _pixelbuf
import array
import board
import supervisor
import sys
import time
import math
import rgbmatrix
import displayio

def rgb888_to_rgb565(x):
    r = (x >> 16)
    g = (x >> 8) & 0xff
    b = x & 0xff
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def _wheel565(x):
    return rgb888_to_rgb565(_pixelbuf.colorwheel(int(x % 256)))

wheel565 = [_wheel565(x) for x in range(256)]

# wait for serial connection
while not supervisor.runtime.serial_connected:
    pass
time.sleep(0.1)
while supervisor.runtime.serial_bytes_available:
    sys.stdin.read(1)

print("press any key", end="")
while not supervisor.runtime.serial_bytes_available:
    pass
sys.stdin.read(1)
print()

displayio.release_displays()
print("construct")
matrix = rgbmatrix.RGBMatrix(
    width=32,
    bit_depth=6,
    rgb_pins=[board.IO7, board.IO8, board.IO9, board.IO10, board.IO11, board.IO12],
    addr_pins=[board.A0, board.A1, board.A2], #, board.A3],
    clock_pin=board.IO13,
    latch_pin=board.IO15,
    output_enable_pin=board.IO14,
)

fb = memoryview(matrix)
while True:
    t = time.monotonic()
    d1 = 7 + math.sin(t * .7) * 14
    d2 = 9 + 18*math.cos(t * .2)
    print(d1, d2)
    for i in range(matrix.width):
        for j in range(matrix.height):
            fb[i + j*matrix.width] = wheel565[int(i*d1 + j*d2) & 0xff]

    matrix.refresh()

print("constructed")
while True:
    pass
```

Manually constructing display in repl:
```python
displayio.release_displays()
matrix = rgbmatrix.RGBMatrix(
    width=32,
    bit_depth=4,
    rgb_pins=[board.IO7, board.IO8, board.IO9, board.IO10, board.IO11, board.IO12],
    addr_pins=[board.A0, board.A1, board.A2],
    clock_pin=board.IO13,
    latch_pin=board.IO15,
    output_enable_pin=board.IO14,
)
display = framebufferio.FramebufferDisplay(matrix)
```

dogecoin demo:
```python
import framebufferio
import _pixelbuf
import array
import board
import supervisor
import sys
import time
import math
import rgbmatrix
import displayio
import wifi
import ipaddress
import ssl
import socketpool
import adafruit_requests
import terminalio
import random
import colorsys

# Get wifi details and more from a secrets.py file
try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise
 
displayio.release_displays()

def hls(h,l,s):
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    r = int(r)
    g = int(g)
    b = int(b)
    assert 0 <= r < 256
    assert 0 <= g < 256
    assert 0 <= b < 256
    return (r<<16) | (g<<8) | b

saying_colors = [hls(i/256, .25, 1) for i in range(256)]

def init_display():
    global matrix
    global display

    matrix = rgbmatrix.RGBMatrix(
        width=64,
        bit_depth=4,
        rgb_pins=[board.IO7, board.IO8, board.IO9, board.IO10, board.IO11, board.IO12],
        addr_pins=[board.A0, board.A1, board.A2, board.A3],
        clock_pin=board.IO13,
        latch_pin=board.IO15,
        output_enable_pin=board.IO14,
    )
    display = framebufferio.FramebufferDisplay(matrix, rotation=180)
    display.auto_refresh=False

CURRENCY = "USD"
# Set up where we'll be fetching data from
DATA_SOURCE = f"https://sochain.com//api/v2/get_price/DOGE/{CURRENCY}"
DATA_LOCATION = ["data", "prices", 0, "price"]


def init_wifi():
    global wifi, pool, requests

    import wifi

    print("My MAC addr:", [hex(i) for i in wifi.radio.mac_address])

#    print("Available WiFi networks:")
#    for network in wifi.radio.start_scanning_networks():
#        print("\t%s\t\tRSSI: %d\tChannel: %d" % (str(network.ssid, "utf-8"),
#                network.rssi, network.channel))
#    wifi.radio.stop_scanning_networks()
     
    print("Connecting to %s"%secrets["ssid"])
    wifi.radio.connect(secrets["ssid"], secrets["password"])
    print("Connected to %s!"%secrets["ssid"])
    print("My IP address is", wifi.radio.ipv4_address)
     
    ipv4 = ipaddress.ip_address("8.8.4.4")
    print("Ping google.com: %f ms" % (wifi.radio.ping(ipv4)*1000))
     
    pool = socketpool.SocketPool(wifi.radio)
    requests = adafruit_requests.Session(pool, ssl.create_default_context())

def text_transform(val):
    if CURRENCY == "USD":
        return "$%s" % val
    if CURRENCY == "EUR":
        return "€%s" % val
    if CURRENCY == "GBP":
        return "£%s" % val
    return "%s" % val
 

init_wifi()
init_display() 

from adafruit_display_text.bitmap_label import Label
g = displayio.Group()
label = Label(font=terminalio.FONT, text="")
label.x = 6
label.y = 15
saying = Label(font=terminalio.FONT, text="")
g.append(saying)
g.append(label)
display.show(g)
doge_sayings = "wow/much coin/how money/so crypto/rich very".split("/")
#print(saying_colors)

while True:
    try:
        response = requests.get(DATA_SOURCE)
        value = response.json()['data']['prices'][0]['price']
        print("Response is", value)
        label.text = text_transform(value)
    except (ValueError, RuntimeError) as e:
        print("Some error occured, retrying! -", e)
 
    for i in range(3*60):
        display.auto_refresh = True
        time.sleep(1)
        display.auto_refresh = False
        saying.x = random.randint(-24, 40)
        saying.y = random.randint(8, 24)
        saying.text = random.choice(doge_sayings)
        saying.color = random.choice(saying_colors)
```

### CODE REVIEW

**Comment by jepler** [comment]
It looks like the failing check is spurious, or at least unrelated.  While installing build dependencies via pip:
```
ERROR: Could not find a version that satisfies the requirement click (from versions: none)
ERROR: No matching distribution found for click
```

**Comment by tannewt** [comment]
Is this ready for review?

**Comment by jepler** [comment]
@tannewt yes

**Review by gamblor21 — COMMENTED** [review]
I reviewed all the code and it looks good to me, based on my past LED matrix experiences. Were you looking to have someone else also try it out on an actual device? I have a FeatherS2 but unsure if I have the cables to hook it up. I may be able to rig up something with jumper wires though.

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Pull request merged**
