### PR TITLE
Added option to enable toggling CS between init commands

### LINKED ISSUE #1684: displayio: Option needed to allow SPI Chip Select Toggle between init commands
Due to the way the ST7789 display works, the only way I was able to get it to work was to have the CS briefly go High, then Low between commands. I found this by examining the Arduino Driver and it seems particular to this display. I have confirmed that toggling this in CircuitPython does fix the display working. I am preparing my first PR to fix this and will submit when it passes on Travis.

### PR DESCRIPTION
**Pull request by makermelissa**
The ST7789 requires the Chip Select to toggle High then Low between init commands in order to successfully initialize. I added an option to enable this which is off by default so it won't break any existing configurations. This is needed for the ST7789 displayio driver. This PR fixes #1684

### CODE REVIEW

**Comment by ladyada** [comment]
these displays tend to want CS toggled before each command - i'd make it the default behavior rather than the exception

**Comment by makermelissa** [comment]
Ok thanks. Easy enough change.

**Comment by makermelissa** [comment]
Should I also set it to enabled for the PyPortal, Hallowing, and PyBadge? Those are in the board.c files for each.

**Comment by ladyada** [comment]
yeah, i think it should always do that - its the expected behavior, in fact it may be one of the reasons i've seen gamma not always set.
 if something breaks we'll find out soon :)

**Comment by makermelissa** [comment]
Yeah, I can go through and remove the option now. Originally added when I thought it would default to false.

**Comment by makermelissa** [comment]
Ok, this has been cleaned up so that it always has the toggle happen.

**Comment by ladyada** [comment]
in arduino, traditionally we toggle CS on the beginning of every command

**Comment by makermelissa** [comment]
Great idea. I'll go with that. It will make things even simpler.

**Pull request merged**
