### PR TITLE
sunton esp32-8048s070 support

### PR DESCRIPTION
**Pull request by SeanTheITGuy**
Second attempt. I'll try not to mess the PR up, this time.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
I don't understand how the touch screen is working but all's well I guess. I worked on the makerfabs tt7 display board which shared the USB pins with I2S audio and the pins gave resource errors unless the firmware was built with USB disabled.....

**Comment by RetiredWizard** [comment]
I don't have the hardware to test but I looked over the schematics and the only issue I saw doesn't appear to be a problem when tested on the hardware.

**Comment by RetiredWizard** [comment]
Ahh, You have CIRCUITPY_USB = 0 in mpconfigboard.mk. That's why you're not seeing the conflict. Wouldn't that shuts down the CIRCUITPY drive doesn't it? Does the device enumerate a USB port on the host machine?

**Comment by SeanTheITGuy** [comment]
The USB port is hooked to a USB TTL, not to the native USB pins on the S3.  Seems an odd choice on the part of the manufacturer, but it is what it is.

**Comment by RetiredWizard** [comment]
Cool, so does the CIRCUITPY drive still work over USB TTL?

**Comment by SeanTheITGuy** [comment]
Unfortunately not, and as you said, you'd have a choice of either touch or usb drive.

**Comment by RetiredWizard** [comment]
Well now that there's Web Workflow it's actually not a terrible trade-off to get a few more GPIO pins :grin:. I wish Makerfabs had done that with their version....

**Review by dhalbert — APPROVED** [review]
Sounds like everything is resolved. The lack of real USB is still :shrug:

**Comment by dhalbert** [comment]
Please open a PR to add this board to circuitpython.org: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Pull request merged**
