### PR TITLE
Set DRVSTR on output pins to strong (more current capability).

### LINKED ISSUE #332: PIN STRONG!
are we using strong mode? lets do it!
image

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #332. Tested by Limor; makes for brighter LEDs, etc.

### CODE REVIEW

**Comment by fab672000** [comment]
I noted that for the arduino code pinMode() function (even up to 1.5.7)  unfortunately resets the DRVSTR bit, because it writes the full PINCFGn register where n is the pin number, zeroing this bit.
I wrote a special code that does set the DRVSTR **at the same time we set the pinMode as output** (so that as soon as we are  set as OUTPUT we we have the DRVSTR drive on) :
`// like pinMode(pin, OUTPUT), but to set drive strength (max is 2mA if false, 8mA if true)
bool setHighStrengOutputPinMode( uint32_t ulPin)
{
#if defined(_VARIANT_GRAND_CENTRAL_M4_)

  // Handle the case the pin isn't usable as PIO
  if ( g_APinDescription[ulPin].ulPinType == PIO_NOT_A_PIN ) return false;

  EPortType port = g_APinDescription[ulPin].ulPort;
  uint32_t pin = g_APinDescription[ulPin].ulPin;
  uint32_t pinMask = (1ul << pin);

  // enable input, to support reading back values, with pullups disabled and DRVSTR set
  PORT->Group[port].PINCFG[pin].reg=(uint8_t)(PORT_PINCFG_INEN | PORT_PINCFG_DRVSTR) ;
  // Set pin to output mode
  PORT->Group[port].DIRSET.reg = pinMask;
#else
  pinMode(ulPin, OUTPUT); // keep this code compatible with other MCU's that don't have DRVSTR
  return false;
#endif
  
  return true;
}
`

**Comment by dhalbert** [comment]
@fab672000 Are you noticing an issue with CircuitPython, or did you want to comment on the SAMD51 Arduino board support package? (https://github.com/adafruit/ArduinoCore-samd/)

**Comment by fab672000** [comment]
Just wanted to comment on the arduino code side because it was not clear to me before I looked at your source code if your change would also affect my arduino code (thought the code was factorized), looking at your code though, it seems cleaner that the current samd arduino code as I think you use the bits structure as opposed to bit masks operations BTW.

**Comment by dhalbert** [comment]
Please do open an issue or PR on https://github.com/adafruit/ArduinoCore-samd/ if you think there's something to be done, since we don't share code with that repo.

**Comment by fab672000** [comment]
Thanks! done.
Also suggested a fix for it that does not alter accidentally other user config bits (basically using the bit datat structure in the union)

**Pull request merged**
