### PR TITLE
raspberrypi: allow directly specifying the original boot .S file

### PR DESCRIPTION
**Pull request by jepler**
.. all the necessary steps to transform it into a padded, checksummed file are now done by the build system.

Since it is assigned by "?=", it _should_ be the case that individual builds can override it.

I did not "test" this per se, but it gives the same content and checksum (except for the identifying comment with a path) as #4302.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Thanks! Want to switch the pico back to the qspi version?

**Comment by jepler** [comment]
That would be a good test, will do

**Comment by ladyada** [comment]
tested pico & feather rp2040 - both artifacts enumerate

**Review by tannewt — APPROVED** [review]
Great! Thank you!

**Pull request merged**
