### PR TITLE
nRF: Change analog reference voltage

### PR DESCRIPTION
**Pull request by jepler**
Datasheet reading explains one reason why readings might have been 10% low.

### CODE REVIEW

**Comment by ladyada** [comment]
thanks - there does not seem to be a way to use plain 3.3V (VDD) right? it must be 3.6?

**Comment by jepler** [comment]
@ladyada, there is an option to use a VCC/4 reference and a 1/4 prescaler, instead of a 0.6V reference and 1/6 prescaler as it does now.  I can do some testing with both, but how to decide which is preferable?

**Comment by ladyada** [comment]
prior is better - eventually having this be adjustable (reference) would be ideal cause you can get absolute voltages but for now, VCC/4 + 4x matches every other chip :)

**Comment by jepler** [comment]
OK, now it will be vcc-referenced.  Gives a nice consistent 65520 counts (0xfff0) when VCC is connected to an analog in or my little trimmer resistor is turned all the way to one end of its travel.

**Comment by ladyada** [comment]
ok i think this is good

**Pull request merged**
