### PR TITLE
Update espressif port

### PR DESCRIPTION
**Pull request by microDev1**
Changes in this PR:
- Update esp-idf to v4.4.
- Add esp32s3 support.
- Add analogio on esp32c3.
- Disable rgbmatrix on all espressif soc.
- Formatting changes in espressif makefile.

Thanks @tannewt and @UnexpectedMaker for the initial heavy-lifting.

### CODE REVIEW

**Comment by jepler** [comment]
What's up with disabling rgbmatrix, can you explain why it was necessary?

**Comment by microDev1** [comment]
> What's up with disabling rgbmatrix, can you explain why it was necessary?

Nothing major, `protomatter` needs to be updated, `timer_index_t` struct has changed in the newer idf.
I have got a PR out https://github.com/adafruit/Adafruit_Protomatter/pull/41 but don't have the hardware to test it.

**Comment by tannewt** [comment]
@jepler Want to update protomatter next week for this?

**Comment by tannewt** [comment]
Thank you! The changes all look good to me. We just need to update protomatter so that we can leave rgbmatrix enabled.

**Comment by jepler** [comment]
Yeah if there's code that builds I can at least test it on esp32-s2 and get it merged in. It looks like there's not a variant which works with both old and new esp-idf so doing it in steps with rgbmatrix briefly disabled is probably not a bad way to handle it. Please open an issue here so that I have a reminder of the task.

**Comment by jepler** [comment]
What BOARD= can I build with to test esp32-s3 support in this PR?

**Comment by microDev1** [comment]
> What BOARD= can I build with to test esp32-s3 support in this PR?

You can take any esp32s2 board and replace `s2`/`S2` with `s3`/`S3`.

**Comment by ladyada** [comment]
@microDev1 we tried to build but got this
```
�ESP-ROM:esp32s3-20210327f
Build:Mar 27 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40048836
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
```
maybe we did something wrong, do you mind also commiting a board we could try against like one of the ESP S3 eval boards? they all have 4MB flash and one has 2 MB PSRAM. it would help us with testing :)

**Comment by jepler** [comment]
With the latest changes I was able to get the https://www.adafruit.com/product/5310 working, including spiram.  Thank you.

**Comment by microDev1** [comment]
I believe following change was lost when I rebased my branch and merged main before making the PR.
The `BOOTLOADER_OFFSET` for esp32, esp32s2 is `0x1000` and esp32c3, esp32s3 is `0x0`, I have corrected this now. :-)

**Comment by jepler** [comment]
I've made an extremely lightly tested board definition for the psram variant of the esp32s3-devkitc at https://github.com/adafruit/circuitpython/compare/main...jepler:esp32s3-devkitc?expand=1 if you want to make that a part of this PR that would be great. If not I can make a fresh PR after this one is merged. I tested that it comes up, that os.uname() seems right, and that the neopixel works.

**Comment by microDev1** [comment]
Let's get this merged, the board can be added in a separate PR.

**Comment by tannewt** [comment]
We're going to wait just a little bit (a day or two) so that we can branch 7.1.0 before merging this into main. We'll want to add a 7.2.0-alpha.0 tag for it then too.

**Review by tannewt — APPROVED** [review]
Thank you for doing this update!

**Comment by alexwhittemore** [comment]
Damnit now I need to go get an ESP32-S3 board before the rush! Great Hanukkah present, thanks y'all,

**Pull request merged**
