### PR TITLE
Unify iMX RT flash config and add Metro M7 1011

### PR DESCRIPTION
**Pull request by tannewt**
This unifies the flash config to the settings used by the Boot ROM.
This makes the config unique per board which allows for changing
quad enable and status bit differences per flash device. It also
allows for timing differences due to the board layout.

This change also tweaks linker layout to leave more ram space for
the CircuitPython heap.

### CODE REVIEW

**Review by arturo182 — APPROVED** [review]

**Comment by tannewt** [comment]
@jepler Do you have time to review this?

**Comment by tannewt** [comment]
Thanks @jepler! I left fsl as-is because it's directly sourced from the sdk.

**Comment by arturo182** [comment]
@tannewt have you tested this code on any boards? I just tried HEAD of main branch and my Feather RT1011 doesn't boot, it works for the v6 beta 3, bisecting between HEAD and beta 3 led me down to this commit as the breaking one :sweat_smile:

**Comment by tannewt** [comment]
Yes. I don't have your boards so I didn't test them. I added you as a reviewer for that reason. I did test on the EVKs (1020 is broken), the new Metro and the Teensys.

**Comment by arturo182** [comment]
Damn :disappointed:

**Pull request merged**
