### PR TITLE
set the connected status of a socket after UDP & raw connect

### PR DESCRIPTION
**Pull request by jepler**
This is a speculative fix for https://github.com/adafruit/Adafruit_CircuitPython_NTP/issues/33

### CODE REVIEW

**Comment by anecdata** [comment]
NTP lib:
```py
                sock.connect(self._socket_address)
                sock.send(self._packet)
                sock.recv_into(self._packet)
```

`Adafruit CircuitPython 9.1.0-beta.1-25-g13ea06f1ae on 2024-05-15; Raspberry Pi Pico W with rp2040`
```
code.py output:
struct_time(tm_year=2024, tm_mon=5, tm_mday=15, tm_hour=18, tm_min=41, tm_sec=14, tm_wday=2, tm_yday=136, tm_isdst=-1)
# etc...
```

**Comment by jepler** [comment]
thanks for the quick testing. I hadn't even gotten a board out yet.

**Comment by justmobilize** [comment]
Is there any other testing that's needed? I could see this coming up somewhere else...

**Comment by anecdata** [comment]
I didn't test RAW, only used the (interim) NTP lib to test UDP.

**Pull request merged**
