### PR TITLE
Espressif: Add Esp32s3 devkitc board definitions

### PR DESCRIPTION
**Pull request by jepler**
These both mount CIRCUITPY & blink the RGB LED. That's about all the testing I did.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks for making both versions!

**Comment by anecdata** [comment]
Submitted (but not yet merged) PR to Espressif to resolve the duplicate PID check: can use 0x7005 for the `nopsram` variant...

Existing PIDs, changed name to distinguish psram vs. nopsram:
```
0x7002 | ESP32-S3-DevKitC-1-N8R2 - UF2 Bootloader
0x7003 | ESP32-S3-DevKitC-1-N8R2 - CircuitPython
```

New PIDs:
```
0x7004 | ESP32-S3-DevKitC-1-N8 - UF2 Bootloader
0x7005 | ESP32-S3-DevKitC-1-N8 - CircuitPython
```

(I tried to do a patch PR to this file, but got a 404)

**Comment by willproctor** [comment]
Adafruit CircuitPython 7.2.0-alpha.0-2-g23e0a25aa on 2021-12-03; ESP32-S3-DevKitC-1-nopsram with ESP32S3

From the REPL importing the wifi module causes a reset

**Comment by willproctor** [comment]
> Adafruit CircuitPython 7.2.0-alpha.0-2-g23e0a25aa on 2021-12-03; ESP32-S3-DevKitC-1-nopsram with ESP32S3
> 
> From the REPL importing the wifi module causes a reset

This is tracked under https://github.com/adafruit/circuitpython/issues/5662

**Comment by jepler** [comment]
No, I erred in using the wrong VID, it should be the Espressif one if we're using a PID from Espressif.  (And we should use a PID from Espressif for all new devkits they make)

**Comment by anecdata** [comment]
Is it desirable to go back and change the Adafruit VIDs to Espressif VIDs in prior Espressif boards (any harm in changing them after the fact)? If so, I can track them down and do a PR.

**Comment by jepler** [comment]
I don't think so but maybe @dhalbert has an opinion about changing to an Espressif VID/PID for older espressif devkit.

**Comment by anecdata** [comment]
Saola and Kaluga are self-consistent: Adafruit VID and PID), so probably no strong reason for change.

I did notice checking just now though that the Kaluga 1 and Kaluga 1.3 have the same `USB_PID = 0x80C8`
and `USB_PRODUCT = "Kaluga 1"`, though they have different firmware. I don't think this would pass the current build check.

Another possible quirk: there are two version of no-PSRAM ESP32-S3 in the store:
• PRODUCT ID: 5311 ESP32-S3-DevKitM-1-N8 - ESP32-S3-MINI-1 Dev Board - 8 MB Flash
• PRODUCT ID: 5312 ESP32-S3-DevKitC-1-N8 - ESP32-S3-WROOM-1 Dev Board - 8MB Flash
Presumably these run the same firmware, it's just a difference of module size?

I think as Espressif releases more variations, this will become a common question of how to do the PID, USB_PRODUCT, and whether to just create a board alias like PyPortal & Titano, or whether to create a new board.

I also have newer ESP32-S2 Espressif dev boards which run Saola WROVER firmware (4MB flash, 2MB RAM), but there are other variations of flash and RAM.

**Comment by jepler** [comment]
I think that right now the Adafruit PIDs are only documented internally.

I used a duplicate PID for the newer Kaluga board in this PR, perhaps it did not receive sufficient review: https://github.com/adafruit/circuitpython/pull/4870

**Comment by dhalbert** [comment]
> I don't think so but maybe @dhalbert has an opinion about changing to an Espressif VID/PID for older espressif devkit.

I don't think it's much of an issue. Mu no longer depends on VID/PIDs to identify boards. The new VID/PID will cause Windows 10 to install a new device, but that's fine.

**Review by ladyada — APPROVED** [review]

**Pull request merged**
