### PR TITLE
STM32: Cpython compatibility flag 2

### LINKED ISSUE #2433: STM32: possible problem with strings and adafruit_minimqtt library (AdafruitIO)
I have the Feather STM32F405 Express board. I built firmware for it on Christmas. I have an LPS3x bord connected via QT. If I just print data, everything is fine. If I try to push the data to AdafruitIO, though, I get an error "AttributeError: 'str' object has no attribute 'encode'. When I run 
 adafruit/Adafruit_CircuitPython_AdafruitIO/examples/mqtt/adafruit_io_simpletest.py it throws the same error and backtrace. Here's the backtrace, code to follow down below.
```
Press any key to enter the REPL. Use CTRL-D to reload.soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 93, in <module>
  File "adafruit_minimqtt.py", line 121, in __init__
AttributeError: 'str' object has no attribute 'encode'
```
Then I thought maybe something had changed, so I went back to the Adafruit IO guides and could not find resolution.

Then I went to the library bundle 5.x source as of 20191223 and looked at line 121 in adafruit_minimqtt.py. (If you need me to include a snippet here, I will.) There didn't seem t be anything unusual, but I did see the .encode() method that was causing the problem.

Then I just connected to the REPL, created a string and called the same encode method:
```
Adafruit CircuitPython 5.0.0-beta.2-13-g7387f6092 on 2019-12-27; Feather STM32F405 Express with STM32F405RG
>>> foo = "heresastringtotestwith"
>>> foo.encode('utf-u')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'encode'
>>> 
```
The last couple of issues I raised LadyAda had to exercise extreme patience with my bumbling, so I hope this is more cohesive and helpful. I still assume I'm just doing something stupid, but people on Discord don't seem to think so.

Here is the code that generated the original backtrace:
```
# Example of using the Adafruit IO CircuitPython MQTT client
# to subscribe to an Adafruit IO feed and publish random data
# to be received by the feed.
#
# Example by Tony DiCola for Adafruit Industries
# Modified by Brent Rubell for Adafruit Industries, 2019
import time
from random import randint


import board
import busio
from adafruit_esp32spi import adafruit_esp32spi
from adafruit_esp32spi import adafruit_esp32spi_wifimanager
import adafruit_esp32spi.adafruit_esp32spi_socket as socket
from digitalio import DigitalInOut
import neopixel
from adafruit_io.adafruit_io import IO_MQTT
from adafruit_minimqtt import MQTT

### WiFi ###

# Get wifi details and more from a secrets.py file
try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise

# If you have an externally connected ESP32:
esp32_cs = DigitalInOut(board.D13)
esp32_ready = DigitalInOut(board.D11)
esp32_reset = DigitalInOut(board.D12)


spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
esp = adafruit_esp32spi.ESP_SPIcontrol(spi, esp32_cs, esp32_ready, esp32_reset)
"""Use below for Most Boards"""
status_light = neopixel.NeoPixel(
    board.NEOPIXEL, 1, brightness=0.2
)  # Uncomment for Most Boards
"""Uncomment below for ItsyBitsy M4"""
# status_light = dotstar.DotStar(board.APA102_SCK, board.APA102_MOSI, 1, brightness=0.2)
# Uncomment below for an externally defined RGB LED
# import adafruit_rgbled
# from adafruit_esp32spi import PWMOut
# RED_LED = PWMOut.PWMOut(esp, 26)
# GREEN_LED = PWMOut.PWMOut(esp, 27)
# BLUE_LED = PWMOut.PWMOut(esp, 25)
# status_light = adafruit_rgbled.RGBLED(RED_LED, BLUE_LED, GREEN_LED)
wifi = adafruit_esp32spi_wifimanager.ESPSPI_WiFiManager(esp, secrets, status_light)

# Define callback functions which will be called when certain events happen.
# pylint: disable=unused-argument
def connected(client):
    # Connected function will be called when the client is connected to Adafruit IO.
    # This is a good place to subscribe to feed changes.  The client parameter
    # passed to this function is the Adafruit IO MQTT client so you can make
    # calls against it easily.
    print("Connected to Adafruit IO!  Listening for DemoFeed changes...")
    # Subscribe to changes on a feed named DemoFeed.
    client.subscribe("DemoFeed")

def subscribe(client, userdata, topic, granted_qos):
    # This method is called when the client subscribes to a new feed.
    print('Subscribed to {0} with QOS level {1}'.format(topic, granted_qos))

def unsubscribe(client, userdata, topic, pid):
    # This method is called when the client unsubscribes from a feed.
    print('Unsubscribed from {0} with PID {1}'.format(topic, pid))

# pylint: disable=unused-argument
def disconnected(client):
    # Disconnected function will be called when the client disconnects.
    print("Disconnected from Adafruit IO!")

# pylint: disable=unused-argument
def message(client, feed_id, payload):
    # Message function will be called when a subscribed feed has a new value.
    # The feed_id parameter identifies the feed, and the payload parameter has
    # the new value.
    print("Feed {0} received new value: {1}".format(feed_id, payload))


# Connect to WiFi
wifi.connect()

# Initialize a new MQTT Client object
mqtt_client = MQTT(
    socket=socket,
    broker="io.adafruit.com",
    username=secrets["aio_username"],
    password=secrets["aio_key"],
    network_manager=wifi
)

# Initialize an Adafruit IO MQTT Client
io = IO_MQTT(mqtt_client)

# Connect the callback methods defined above to Adafruit IO
io.on_connect = connected
io.on_disconnect = disconnected
io.on_subscribe = subscribe
io.on_unsubscribe = unsubscribe
io.on_message = message

# Connect to Adafruit IO
io.connect()

# Below is an example of manually publishing a new  value to Adafruit IO.
last = 0
print("Publishing a new message every 10 seconds...")
while True:
    # Explicitly pump the message loop.
    io.loop()
    # Send a new message every 10 seconds.
    if (time.monotonic() - last) >= 5:
        value = randint(0, 100)
        print("Publishing {0} to DemoFeed.".format(value))
        io.publish("DemoFeed", value)
        last = time.monotonic()


# You can also call loop_blocking if you only want to receive values.
# NOTE: If uncommented, no code below this line will run.
# io.loop_blocking()
```

### PR DESCRIPTION
**Pull request by hierophect**
A continuation of #2439, which got merged prematurely. Please do not merge until @jerryneedell has had a chance to review. Should resolve #2433  when finished.

### CODE REVIEW

**Comment by jerryneedell** [comment]
still no joy
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-beta.2-91-gb778aee21 on 2020-01-06; Feather STM32F405 Express with STM32F405RG
>>> import minimqtt_demo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "minimqtt_demo.py", line 94, in <module>
  File "adafruit_minimqtt.py", line 120, in __init__
AttributeError: 'str' object has no attribute 'encode'
>>> string = "test"
>>> dir(string)
['count', 'endswith', 'find', 'format', 'index', 'isalpha', 'isdigit', 'islower', 'isspace', 'isupper', 'join', 'lower', 'lstrip', 'replace', 'rfind', 'rindex', 'rsplit', 'rstrip', 'split', 'startswith', 'strip', 'upper']
>>> 

```

**Comment by hierophect** [comment]
This will require further investigation then. I was hoping the build order would put the board settings and overrides last. I'll need to dig deeper on how things are ordered. 

Can you provide a zip of this `minimqtt_demo.py` file you're using so I can test it?

**Comment by jerryneedell** [comment]
yes but you don't need it to test -- just do the dir(string)  to see if encode is there.
will post the code in a sec.

**Comment by hierophect** [comment]
> yes but you don't need it to test -- just do the dir(string) to see if encode is there.
> will post the code in a sec.

In that case, I'll just need a full list of whatever other includes I need to replicate your result.

**Comment by jerryneedell** [comment]
> > yes but you don't need it to test -- just do the dir(string) to see if encode is there.
> > will post the code in a sec.
> 
> In that case, I'll just need a full list of whatever other includes I need to replicate your result.

none - do a clean boot
```
string = "test"
dir(string)
```

**Comment by hierophect** [comment]
Ah, sorry! I'm actually quite bad at python. All C over here :)

**Comment by hierophect** [comment]
Shouldn't need anything else. I'll ping you once I've got the attribute back in there and we'll do another full hardware test.

**Comment by jerryneedell** [comment]
> Ah, sorry! I'm actually quite bad at python. All C over here :)

no problem! it's a simple check -- also if you have another board - any express board with full build -- you can do the same thing to compare the output -- that was what I meant by showing the grandcentral result.

**Comment by jerryneedell** [comment]
> Shouldn't need anything else. I'll ping you once I've got the attribute back in there and we'll do another full hardware test.

it worked ok when I changed it in  py/circuitpy_mpconfigport.h
```
#define MICROPY_CPYTHON_COMPAT                (CIRCUITPY_FULL_BUILD)
to
#define MICROPY_CPYTHON_COMPAT                1
```

**Comment by hierophect** [comment]
Right, the trick is that's overriding the port level define, rather than the other way around. So I'll need to add some logic there to get around that.

**Comment by hierophect** [comment]
Sorry for the delay, slipped my todo list today. Just needed to swap over to a CFLAG and add the redefine logic to the .h file. Works for me now (raw test with string dir, I don't have MiniMQTT set up). This whole section still needs a conceptual revamp, but we'll follow up on that in #2458. 

Give this a spin and hopefully we can get it in stat.

**Comment by hierophect** [comment]
@dhalbert just wanted to quickly check with you whether this mpconfig.h change is ok

**Comment by jerryneedell** [comment]
Is this awaiting further review?

**Comment by hierophect** [comment]
I was hoping either @tannewt or @dhalbert would review this small addition to circuitpy_mpconfig.h, since that's a micropython holdover, and I'm not always aware of cascade affects that can occur from changes to that kind of file.

**Pull request merged**
