### PR TITLE
Add support MIMXRT1052

### PR DESCRIPTION
**Pull request by sabas1080**
Hi @arturo182 
I am new in the family MIMXRT10xx, but I have the dev board RT1052 of NXP

This is the port for RT1052, I await your review

Thanks

### CODE REVIEW

**Comment by arturo182** [comment]
Thanks for the PR! Have you tested that it works on the 1052 EVK?

**Comment by tannewt** [comment]
The 1050 EVK isn't building: https://github.com/adafruit/circuitpython/pull/2918/checks?check_run_id=682359651

Are you missing submodule updates?

**Comment by arturo182** [comment]
I merged Sabas' PR in the SDK repo, think the SDK submodule needs to be updated to point to that https://github.com/adafruit/MIMXRT10xx_SDK/pull/3

**Comment by hierophect** [comment]
The recently merged #2898 adds just one thing you'll need to account for here, which is adding never-reset pins for the flash banks, USB and SWD pins. Should be just like the 1062: https://github.com/hierophect/circuitpython/blob/38fd9c25f22ec68920afcf736cb75d4d316ba8bb/ports/mimxrt10xx/boards/imxrt1060_evk/board.c

Happy to help if you've got any questions.

**Comment by hierophect** [comment]
Continued in #3044

**Pull request closed without merging**
