### PR TITLE
Add Board bluemicro840

### PR DESCRIPTION
**Pull request by jpconstantineau**
Adding BlueMicro840 as board.

Used pre-existing/pre-approved VID/PID from openmoko.
https://github.com/openmoko/openmoko-usb-oui/blob/master/usb_product_ids.psv

What PID should be used? one specific for the board (bootloader) or a circuitpython-specific one?

Thanks

### CODE REVIEW

**Comment by tannewt** [comment]
> What PID should be used? one specific for the board (bootloader) or a circuitpython-specific one?

We generally recommend a unique PID for CircuitPython but it's really up to you. I would pick the application pid 0x6161 over the bootloader one though. Our concern is that the PID is unique amongst CP boards.

**Comment by jpconstantineau** [comment]
Thanks. I'll update the PID to the app one.

**Review by tannewt — APPROVED** [review]
Looks good! Thanks!

**Comment by ajs256** [comment]
It looks like the CI failures were due to the [outages this morning](https://www.githubstatus.com/history). It wouldn't hurt to poke them again, but this should be safe to merge.

**Pull request merged**
