### PR TITLE
Update Raspberry Pi Pico SDK to 2.1.0

### LINKED ISSUE #9829: Update pico-sdk to 2.1.0
https://github.com/raspberrypi/pico-sdk/releases/tag/2.1.0

More support in various places for pin numbers >= 32. Various fixes.

### PR DESCRIPTION
**Pull request by eightycc**
Update Raspberry Pi Pico SDK to 2.1.0. Update `cyw43-driver` submodule to CF924BB to match SDK included version.

Changes add a few newly required include paths. Also adds `hardware_xip_cache/xip_cache.c`.

Resolves #9829.

Boots, doesn't catch fire. I'm making this a draft pull just in case anyone cares to take it out for a spin.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
This looks good to me! Happy to have it tested via "Absolute Newest". If we're worried we could do a 9.3.0 pre-release with it too.

**Comment by eightycc** [comment]
@tannewt SDK 2.1.0 is where we'll have to live for full RP2350B support, so I don't see any reason to delay stepping up to it past the 9.2.x timeline. I'd like to hold off merging for a day or two to give me a chance to test WiFi on a couple of RP2040 and RP2350 boards.

**Comment by eightycc** [comment]
Re-based to pick up pimoroni_pico_plus2w board. Tested WifFi with this board, an RP2350B with an RM2 on the board. Ready for review.

**Review by tannewt — APPROVED** [review]
Great! Thanks for the update!

**Pull request merged**
