### PR TITLE
initial support for additional bitdepths in OnDiskBitmap

### PR DESCRIPTION
**Pull request by siddacious**
This adds support for 565 16bpp BMPs as well as hacky support for 8bpp grayscale that ignores the  palette because it's just a ramp of values and uses the index as a value for RGB. I started looking into actually reading in the palette for 8bpp indexed images but figured to check in before I go any farther.

The output is also kinda hacky; in the case of 565 each of the color values have been shifted up only to later be shifted back down by ColorConverter.

I'm sure there is much room for improvement!

While doing some testing, I also noticed that there seems to be an existing issue with 24bpp BMPs where reds and blues look like they may be swapped? I though it was something I did but I checked with Beta 2 and it shows up there as well. I can try and fix that as well.

### CODE REVIEW

**Comment by siddacious** [comment]
@ladyada and @tannewt  I _think_ the travis issue isn't my fault (but then again it may just be masking an issue that _is_ my fault :) ). Please take a gander when you have a minute

**Comment by dhalbert** [comment]
Travis is having trouble due to multple PR's at once and only fetch depth 1. We're working on fixing it. Not your fault.

**Comment by dhalbert** [comment]
Travis failing on translations; try `make translate` and commit and re-push. I think that will work, but if ut fails, you may need to merge from upstream.

**Comment by siddacious** [comment]
bleh; my git fu is weak; I'll have to fix this when I get home

**Comment by siddacious** [comment]
Also I'm aware that the initial reading in of the header is not right; I think I will probably update it to read in up to the initial bit of the DIB header to get its length and then read more from there.

**Comment by siddacious** [comment]
hey @ladyada This is broken; my ILI9340 was configured with RGB/BGR backwards so I ordered them wrong in `_get_pixel`; fixing now.

**Comment by ladyada** [comment]
reviewing & breakin' :)

**Comment by Tasm-Devil** [comment]
Removed conflict with locale/de_DE.po

**Comment by ladyada** [comment]
@tannewt this is tested and ready for merging if good by you!

**Comment by siddacious** [comment]
sorry @ladyada I had to fix a conflict that popped up in the interim.

**Comment by siddacious** [comment]
hey @dhalbert it looks like the German hallowing build failed for being too big but I'm not sure what to do to resolve it.

**Comment by dhalbert** [comment]
Easiest way to fix this now is probably to set
```
CFLAGS_INLINE_LIMIT = 55
```
or some similar value in `ports/atmel-samd/boards/hallowing_m0_express/mpconfigport.mk`.
There are examples of doing the same in `circuitplayground_express` and other boards.

We could also consider what to turn off in this build, for instance, do we need `audiobusio` for the audio, or just `audioio`? But the `CFLAGS_INLINE_LIMIT` is quick.

**Pull request merged**
