### PR TITLE
Muselab nanoESP32-S2 w/WROVER

### PR DESCRIPTION
**Pull request by reppad**
Added Muselab nanoESP32-S2 w/WROVER and rename nanoESP32-S2 w/WROOM to be more explicit and consistent

### CODE REVIEW

**Comment by ladyada** [comment]
this is doing a board rename

**Comment by reppad** [comment]
Indeed, if you are OK with that I will push an update for the circuitpython download site for the new board as well as the renamed board.
https://github.com/reppad/circuitpython-org/tree/nanoESP32-S2

**Comment by ladyada** [comment]
yep! just making a note of it!

**Review by tannewt — APPROVED** [review]
Looks good to me! clarity++

**Pull request merged**
