### PR TITLE
Port/Broadcom Switch to "unmeasured" core clock speed check

### LINKED ISSUE #5887: Broadcom: Can't set baudrate on SPI bus
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0-alpha.1-132-gba008ddfb on 2022-01-18; Raspberry Pi Zero W with bcm2835
```

### Code/REPL

```python
import board
import busio

def test(n=1_000_000):
    bus = busio.SPI(board.SCK, board.MOSI, board.MISO)
    with bus as spi:
        while not spi.try_lock():
            print("no lock")
        spi.configure(baudrate=n)
        spi.unlock()
        print(f"frequency={spi.frequency}")
    bus.deinit()
test()
```

### Behavior

It reports the frequency as zero.

I can run `test()` multiple times on other devices, but on the Pi Zero W the second and later times I run it I get:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_spi.py", line 6, in test
ValueError: Invalid pins
```

### Description

Sometimes I get fast SPI (24 MHz). But if I get zero I have to do a hard reset.

Also something isn't getting released by `deinit()`.

I'm trying to use the PiTFT 1.14" display. I have to cycle power until I get the fast SPI bus.

### Additional information

_No response_

### LINKED ISSUE #5913: Broadcom Slow I2C
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0-alpha.1-201-g4d0e1d905 on 2022-01-23; Raspberry Pi Zero W with bcm2835
```

### Code/REPL

```python
import os
import random
import time
import board
import displayio
import vectorio
from adafruit_ssd1327 import SSD1327 # Zio 128x128 grayscale
from adafruit_display_text.label import Label
from terminalio import FONT

displayio.release_displays()

i2c = board.I2C()
i2c_bus = displayio.I2CDisplay(i2c, device_address=0x3C)
display = SSD1327(i2c_bus, width=128, height=128)

splash = displayio.Group()

pal = displayio.Palette(1)
pal[0] = 0x99FF99
vc = vectorio.Circle(radius=60, x=0, y=display.height, pixel_shader=pal)
splash.append(vc)

label = Label(FONT, text=f"0.0000", x=20, y=16, color=0x999999)
splash.append(label)
version = Label(FONT, text=os.uname().version[18:], x=20, y=32, color=0xFFFFFF)
splash.append(version)
display.show(splash)

def any_gray():
    v = random.randint(64,255)
    return (v,v,v)

mark = 0.0
while True:
    t0 = time.monotonic()
    time.sleep(0.2)
    pal[0]=any_gray()
    label.text = f"{mark:.04f}"
    mark = time.monotonic() - t0
```

### Behavior

Screen repaints in about 6.2 seconds on the Raspberry Pi Zero W.

Same code and hardware on Funhouse repaints in about 0.2 seconds.

### Description

Painfully slow.

### Additional information

Perhaps this is the same problem  #5887 as with SPI?

### PR DESCRIPTION
**Pull request by RetiredWizard**
When sending requests to the video core to return the "measured" CORE clock rate the mailbox registers frequently hang preventing any further access to the video core. This PR replaces the "measured" CORE clock rate checks with an unmeasured request. Fixes #5887 & fixes #5913.

A separate pull request to adafruit/broadcom-peripherals (https://github.com/adafruit/broadcom-peripherals/pull/1) is being submitted to add the additional mailbox call routine.

This will also resolve the deinit issue noted in #5887

Tested on zero2w, zero_w and pi4b.

### CODE REVIEW

**Comment by RetiredWizard** [comment]
So the updated broadcom-peripherals changed a lot of the parameter names. I'm working my way through the modules swapping in the new names but it's going to take a while.

**Comment by RetiredWizard** [comment]
There was one file in the broadcom-peripherals repository that needed to be updated with the new parameter names. I'll wait for that to be merged (https://github.com/adafruit/broadcom-peripherals/pull/2) before pushing the *hopefully* final updates for this PR

**Review by tannewt — APPROVED** [review]
Thank you for the updates!

**Comment by criptych** [comment]
Is it safe to assume that this didn't yet make it into 8.0.3?  I'm experiencing similar issues trying to control a Crickit HAT (which communicates via I2C): motors are moving out of sync, updating the *onboard* NeoPixel has an obvious delay; but I only noticed now that this wasn't merged until yesterday.

**Comment by RetiredWizard** [comment]
Looking at the github 8.0.3 tag this update isn't included so I'm guessing it hasn't been merged into the released builds yet. If you used the "absolute newest" link from the circuitpython.org downloads page you should get a firmware file with this update merged in.

**Comment by dhalbert** [comment]
This was merged into `main`, which is on the 8.1.0-beta track, and will probably not be backported to the `8.0.x` branch. We'll be making 8.1.0-beta.0 soon.

**Comment by criptych** [comment]
Good to know, thank you both.  I should have some time this evening to check out the beta.

**Pull request merged**
