### PR TITLE
Add New Board - Seeeduino XIAO RP2040

### PR DESCRIPTION
**Pull request by jpconstantineau**
Been in contact with MengDu from Seeed on discord.

Preparing new board for their new Seeed Xiao RP2040.
Pending review from Seeed and their PID.

EXTERNAL_FLASH_DEVICES to be confirmed.  Seems small  (Seeed to confirm) ~~and not sure if this config is available (build will let us know).~~

This PR will kick-off a GHA job for Seeed to test the UF2 on actual hardware.

Link to Design files: https://www.seeedstudio.com/XIAO-RP2040-v1-0-p-5026.html
Wiki: https://wiki.seeedstudio.com/XIAO-RP2040-with-CircuitPython/

### CODE REVIEW

**Comment by jpconstantineau** [comment]
Updated the nvm.toml module and lots more  boards started to fail... The module brought in a few more new files and I suspect that it's these that are causing the issues.  I only tested with my files (puya)
What's the plan? Cherry pick or figure out what's wrong with these other files? 

Is there a way to get where the toml processor fails?

**Comment by dhalbert** [comment]
The builds are still working on recent PR's. Have rebased or merged from upstream since the builds started failing? Your toml submodule appears to be out of date now according to the file comparisons.

**Comment by jpconstantineau** [comment]
I just merged upstream and the builds are still failing.

The toml submodule has added new files. See [here](https://github.com/adafruit/circuitpython/pull/5519/files)
Unfortunately, more than my files got added and I suspect that it's the other files that are problematic...

**Comment by jepler** [comment]
Based on the error message, I tried making the following edit down in nvm.toml and the error seems to be resolved:
```diff
diff --git a/flash/puya/P25Q16H.toml b/flash/puya/P25Q16H.toml
index e4fd193..d7c6903 100644
--- a/flash/puya/P25Q16H.toml
+++ b/flash/puya/P25Q16H.toml
@@ -3,7 +3,6 @@
 # This config is still untested.
 total_size = 0x200000 # 2 MiB # Page 17
 capacity = 0x15 
-manufacturer_id = 0x85 #  Page 49
 write_status_register_split = false
 01_continuous_status_write = true # page 21
 e7_quad_word_read = false # couldn't find in page 21/22
```

It seems that `manufacturer_id` was already specified in `flash/puya/puya.html`, though I don't know why redundantly specifying it should be an error.  @tannewt?

Is there some kind of quality check needed in nvm.toml to detect problems, at least that a script 'like' gen_nvm_devices can succeed.

**Comment by jpconstantineau** [comment]
Apart from testing on the hardware itself, this PR is pretty much ready.  
MengDu from Seeed on discord indicated that supply is tight right now.  Getting some hardware for testing might take a while.  

There are some out there right now (Zack Freedman's latest keyboard uses one).  Do we get it out now and wait for people to load them up and let us know of any issues or do we wait to merge?  Let me know and I'll update the WIP title...

**Comment by dhalbert** [comment]
If you can get anyone to see if it loads and runs, with CIRCUITPY working, that would be great. The only failure points I see would be the flash definition, and the pin assignments. The latter can be triple-checked, but the former really needs a test with a real board.

**Comment by jpconstantineau** [comment]
Thanks Dan.  That's my impression too (pins can be triple-checked but testing with flash can only be done on real hardware).   I messaged MengDu to see if they have someone who could load it on their side.  I'll want to test it myself as this is the same format as the original Xiao and the QT PY(s) and these are all boards that can be used with my basic macropad/encoder.  Having the same pin definition helps in keeping the python code to be the same across all boards...

**Comment by jpconstantineau** [comment]
Brief update on this: Seeed is still waiting on stock before one can be shipped to me for testing.

**Comment by prplz** [comment]
I received my board yesterday and it runs this PR fine. Interestingly, the pi pico build also works fine.

**Comment by jpconstantineau** [comment]
@prplz Thanks for the update.  I am still waiting for mine.
@tannewt Removing the WIP from the title.  Will press the "Ready for  review button" shortly...

**Comment by prplz** [comment]
Perhaps you should include the neopixel library?

**Comment by jpconstantineau** [comment]
@prplz Does it have a neopixel on board? (Guess so: GPIO12)  That's something we can add easily.  However, it is normal for including it in the frozen libraries?

**Comment by prplz** [comment]
I'm unsure, I see some with onboard neopixel that include it, but also some that don't.

**Comment by prplz** [comment]
Just checked to be sure, and the flash command `RDID` returns `85 60 15` as the datasheet says it should.

**Comment by tannewt** [comment]
I don't suggest freezing in libraries unless you need to save RAM later. The RP2040 has plenty, so I'd leave the neopixel library out.

**Pull request merged**
