### PR TITLE
Support OSError subclasses and attributes

### PR DESCRIPTION
**Pull request by notro**
This adds support for the OSError subclasses listed in the [Python docs](https://docs.python.org/3/library/exceptions.html):
```
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
```

When OSError is raised, the errno value is checked to see if a subclass should be used following the
CPython rules in [Objects/exceptions.c:_PyExc_Init()](https://github.com/python/cpython/blob/v3.4.9/Objects/exceptions.c#L2597-L2632).

These [OSError](https://docs.python.org/3/library/exceptions.html#OSError) attributes are added: errno, strerror, filename and filename2.

samd51 has MICROPY_CPYTHON_COMPAT enabled and will get these additions.

On samd51 use the default MICROPY_PY_UERRNO_LIST to give libraries access to all the errno values:
```
>>> import errno
>>> print('\n'.join(dir(errno)))
__class__
__name__
EACCES
EADDRINUSE
EAGAIN
EALREADY
EBADF
ECONNABORTED
ECONNREFUSED
ECONNRESET
EEXIST
EHOSTUNREACH
EINPROGRESS
EINVAL
EIO
EISDIR
ENOBUFS
ENODEV
ENOENT
ENOMEM
ENOTCONN
EOPNOTSUPP
EPERM
ETIMEDOUT
```

Test coverage in the ported stdlib: [lib/test/test_pep3151.py](https://github.com/notro/tmp_CircuitPython_stdlib/blob/master/lib/test/test_pep3151.py) and [lib/test/test_exceptions.py](https://github.com/notro/tmp_CircuitPython_stdlib/blob/master/lib/test/test_exceptions.py)

### CODE REVIEW

**Comment by notro** [comment]
Forgot to mention flash usage:
```
Base:
58368 bytes free in flash out of 499712 bytes ( 488.0 kb ).

OSError patch: Use 2468 bytes
55900 bytes free in flash out of 499712 bytes ( 488.0 kb ).

uerrno patch: Use 320 bytes
55580 bytes free in flash out of 499712 bytes ( 488.0 kb ).
```

**Comment by notro** [comment]
**Version 2**
- Fix viper_misc test

**Comment by notro** [comment]
**Version 3**
- Really fix the test including the expected result file

**Comment by dhalbert** [comment]
Unfortunately, since this makes the SAMD21 builds throw different exceptions, this is a pretty user-visible incompatibility. We don't really have room for this in the M0 builds now.

@tannewt notes that each new class adds 60 bytes for the class object, and the most of rest could be qstrs. He has some ideas about shrinking the class objects.

**Comment by notro** [comment]
**Version 4**
- Drop subclasses

As expected, a lot less flash use:
```
Base:
58368 bytes free in flash out of 499712 bytes ( 488.0 kb ).

OSError patch: Use 384 bytes
57984 bytes free in flash out of 499712 bytes ( 488.0 kb ).

uerrno patch: Use 328 bytes
57656 bytes free in flash out of 499712 bytes ( 488.0 kb ).
```

**Comment by tannewt** [comment]
Sorry for the late reply on this. I was heads down on USB.

I'd prefer to have the subclasses on M4. It does take more space but means we are closer to CPython. Its backwards compatible to M0 because except clauses account for object inheritance. Can we use macros on the M0 for the subclasses?

**Comment by dhalbert** [comment]
Class alias names could be OK, but we will still need more qstr space. Maybe we can get it to fit.

**Comment by notro** [comment]
> Unfortunately, since this makes the SAMD21 builds throw different exceptions, this is a pretty user-visible incompatibility.

@dhalbert I suppose you're referring to the fact that the same fault will result in different exceptions (OSError vs. FileNotFoundError).

I don't see how an alias like this:
```
STATIC const mp_rom_map_elem_t mp_module_builtins_globals_table[] = {

    { MP_ROM_QSTR(MP_QSTR_FileNotFoundError), MP_ROM_PTR(&mp_type_OSError) },
```
can help with that situation.

It will ofc help libraries that raise these exceptions directly, but maybe we should deal with that when/if it becomes necessary?
As @dhalbert says, there's not much room available on some of the M0 boards.

**Comment by dhalbert** [comment]
Instead of adding these as builtin exceptions and errno's, could you instead provide one or more shim libraries, written in Python, that provided the exceptions for those libraries that throw those exceptions? Then they only take space when needed, instead of occupying space and being unused most of the time.

**Comment by notro** [comment]
Nah, in that case for me it's better to just fixup the stdlib modules instead.
@tannewt expressed a wish to move closer to CPython, and I thought that this would be something that would be useful because these exceptions should always be available without having to import something.

**Comment by dhalbert** [comment]
@tannewt This is OK by me in the current form. OK by you?

**Pull request merged**
