### PR TITLE
Devcontainer update

### LINKED ISSUE #9029: .devcontainer: Uses incorrect ARM toolchain version
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0 rc0
```

### Code/REPL

```python
n/a
```

### Behavior

n/a

### Description

The gcc compiler installed by `.devcontainer/cortex-m/on-create.sh` is an out of date version of the ARM toolchain for an `x86_64` build host. The version installed is `gcc-arm-none-eabi-10-2020-q4-major`, but should be `arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi` for an `x86_64` build host.

Additionally, support should be provided for other build hosts.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bablokb**
This adds support for Github-codespaces for CP 9.x.x.

It fixes #9029.

Another major change is that the devcontainer-alternatives are now on a per port basis (major speedup in codespace creation since the codespace only fetches submodules relevant to the selected port). Currently only ports using espressif and cortex-m are supported.

### CODE REVIEW

**Comment by dhalbert** [comment]
You should be able to use pre-commit locally to catch these: https://learn.adafruit.com/building-circuitpython/build-circuitpython#install-pre-commit-3096511

**Comment by bablokb** [comment]
The problem is that trailing whitespace is valid markup (two trailing blanks signal a line break), so I think you should change pre-commit. Anyhow, I removed the whitespace so this is fine now.

**Comment by dhalbert** [comment]
I think it would be better to use `<br>` in general: it's valid markdown and is not invisible like trailing whitespace. But no problem here now.

**Review by dhalbert — APPROVED** [review]
Thanks! I think it would be good to write this up in https://adafruit-playground.com/. I could link to that from the "Building CircuitPython" guide and/or at least link to the Readme here.

**Comment by bablokb** [comment]
> it would be good to write this up in https://adafruit-playground.com/.

Yes, that is on my todo-list.

**Comment by bablokb** [comment]
@dhalbert : Note on Adafruit-Playground is available:<https://adafruit-playground.com/u/picofun/pages/using-github-codespaces-for-circuitpython-development>

**Comment by dhalbert** [comment]
@bablokb I have added [a page in the Building CircuitPython guide](https://learn.adafruit.com/building-circuitpython/github-codespaces) that points to your Playground note. I will also blog it on the Adafruit blog.

**Comment by dhalbert** [comment]
https://blog.adafruit.com/2024/03/25/using-github-codespaces-for-circuitpython-development-adafruitplayground-featurednote-adafruit/

**Pull request merged**
