### PR TITLE
Build extensions in mpconfigport and mpconfigboard

### LINKED ISSUE #6269: Move "extension_by_board" deeper into Ports
I'm adding a C3 board, so I had to specify it is BIN only in `tools/build_board_info.py` which triggers all of CP ports to build.

If this could be moved deeper in the folder hierarchy like under ports/<port_name> that would alleviate builds which are not needed from being triggered.

### PR DESCRIPTION
**Pull request by Neradoc**
Move the list of extensions per board into mpconfigport.mk an mpconfigboard.mk, with `CIRCUITPY_BUILD_EXTENSIONS` as a list of the exact extensions, eg: `bin,uf2`. Default port value is set in the port config file, by variant if necessary (like IDF_TARGET).
resolves #6269 and replaces #6618

The list of extensions is retrieved along other configuration data with `get_settings_from_makefile` which uses a call to `make` in order to automatically manage defaults per port and overrides per board.
It is used from 3 files:
- shared_bindings_matrix.py which is part of the build-doc workflow and Read The Docs.
- build_board_info.py which is part of the circuitpython.org update workflow.
- build_release_files.py which is part of the build workflow, once per board.

The support matrix docs page seems properly generated.
The json generated by build_board_info matches the output from main.
The build CI on my fork reported no errors, though I only briefly checked if the generated files matched (uf2, bin, etc.).

Other notes:
- support_matrix_by_board returns each board info as a dict. (with changes to support_matrix.rst)
- that dictionary now contains the list of extensions to build.
- the frozen modules can optionally be paired with the URL of the module's repo for the matrix.
- move get_board_mapping() into the support matrix script.

I originally wanted to reorganize the python tools a little bit with this PR, by making a module in the tools directory for the common functions. However, this demands a little bit more consideration, to separate configuration data that should cause a build of all boards, versus those that don't. It can come later.

For example `ALIASES_BRAND_NAMES` only matters for the website update, whereas adding to `LANGUAGE_ALLOW_LIST` should probably trigger a compile of all, baring a trick to only compile the new language.

### CODE REVIEW

**Review by jepler — DISMISSED** [review]
I didn't spot any concerns. I didn't do any direct testing, though, so leaving unmerged right this second in case someone else wants to do that. Thanks for working on this! The scripts don't have to be perfected today, but it's good to take a look every now and then to see what can be better. Please feel free to ping if nobody else weighs in.

**Review by tannewt — CHANGES_REQUESTED** [review]
Awesome! I merged a conflict in (sorry!) so it'll need one more rev. Thanks!

**Comment by Neradoc** [comment]
Rebased on main.

**Comment by tannewt** [comment]
This was a network error.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
