### PR TITLE
Add new board for atmel-samd port: bdmicro_vina-m0

### PR DESCRIPTION
**Pull request by bd34n**
Add new board BDMICRO 'Vina M0'.

This board includes the newly added MX25L51245G 64MB SPI flash chip for the CircuitPython file system. Has been extensively tested with CircuitPython and works well.

Thank you for reviewing!

### CODE REVIEW

**Comment by bd34n** [comment]
My apologies ... in my initial pull request to add the new board, I neglected to add the board to the workflows/build.yml, and the automated test failed. I made that change in my fork and somehow it magically showed up above. Is that now part of the pull request? Do I need to do anything else to get that change into this pull request?

And how to restart the automated tests?

**Comment by tannewt** [comment]
Hi @bd34n! No problem iterating. The PR will match your `master` branch. The tests should automatically run. I have a feeling you need to use spaces instead of a tab and then the test will run. (It is highlighted red in the diff on GitHub.)

**Comment by bd34n** [comment]
Thank you, @tannewt. I should have realized the tab issue myself. That bites me on a regular basis editing yaml using emacs. And has prompted me to change my .emacs defaults to disable indent with tabs mode.

**Comment by bd34n** [comment]
Ok,, thank you for that feedback. I didn't know. I wondered, though - I noticed that most boards all used underbars. I also noticed a few they used a hyphen, so I thought it while not common, it was ok. I have renamed the board, rebuilt locally and tested the resulting firmware. And also updated the workflows/build.yml file - didn't want to forget that again! :-) Tests are running now.

Thanks!

**Comment by bd34n** [comment]
Excellent, thank you very much, @tannewt !!

**Pull request merged**
