### PR TITLE
STM32: Fix I2C repeated start by converting to IT mode

### LINKED ISSUE #3736: Feather STM32F405 Does not properly handle I2C repeated start
I'm working on a library and happened to grab a Feather STM32F405 to work on  and eventually found that the bug I was experiencing was due to the following code not being executed as a repeated start;

```
        buffer = bytearray([0x80, command_id])
        with self.i2c_device as i2c:
            i2c.write_then_readinto(buffer, buffer, in_end=1)
        return buffer[0]
```

Here's the trace of the STM32, flashed to CP6.1.0beta 1
image

And the same code run on a nRF52840 with the same CP version:
image

### PR DESCRIPTION
**Pull request by hierophect**
The existing implementation of I2C does not currently recognize requests for a repeated start condition, which caused reads to fail on some chips. Since only the "IT" interrupt-driven versions of the ST HAL support this feature, fixing this issue also required implementing the usual infrastructure for ST interrupts, matching other modules like UART and PulseIn.

@tannewt I didn't really touch the base implementation here, but if you think we'd benefit from moving regular I2C operations to the interrupt mode (non-blocking) I can add in the requisite timeouts/keyboard interrupt stuff.

Resolves #3736

### CODE REVIEW

**Comment by dhalbert** [comment]
The single build failure the `stm/boards/espruino_pico` `ja` build, which is overflowing by over 2k bytes, which is odd, because I would have expected previous PR's to cause this.

**Review by jepler — APPROVED** [review]
If you gotta, you gotta.  No testing performed.  I initially wondered if i2c_assign_irq needed a "free irq" counterpart, but now I see it's just determining the preassigned IRQ for the peripheral...  I'll stick on an Approve but I don't know what's going on with that failed build .. doesn't make much sense

**Comment by tannewt** [comment]
I'm fine with whatever you want to do. Please stick to one reviewer. You need to sort out the build issue before we can merge.

**Comment by hierophect** [comment]
@tannewt I added @siddacious since it was originally his issue, and he might have wanted to test.

**Comment by hierophect** [comment]
@jepler quick ping for your review again, this should be good to go.

**Review by jepler — APPROVED** [review]
change to save storage seems fine to me.  though, rgbmatrix and sharpdisplay both become less useful without framebufferio so consider disabling them as well in a future commit.

**Comment by dhalbert** [comment]
We can find something else to remove instead. We were not able to understand why the `ja` build suddenly seemed so much larger.

**Comment by hierophect** [comment]
@jepler @dhalbert I really wouldn't worry about it - the STM32F401xD line are very tiny chips that we only see used on the Espruino Pico. It'd be a poor pick for any form of display work anyway.

**Pull request merged**
