### PR TITLE
Revert "atmel-samd: Tweak mass storage code to finish read sooner."

### LINKED ISSUE #422: 2017-11-08 3.0beta build - no REPL or mass storage mount
I rebuilt the firmware tonight and flashed my Metro M4 Express. Now I cannot get Putty to open a serial connection to the COM port (I get an "Unable to open connection to COM50 Cannot open serial port" error). Also, CIRCUITPY does not appear when the M4 is connected. This behavior is the same regardless of which USB port I use or whether I connect to a USB hub. Rebooting the laptop doesn't change the behavior (this is Windows 10, by the way). No pattern of resetting the M4 or dropping into the bootloader changes the behavior.

### PR DESCRIPTION
**Pull request by dhalbert**
This reverts commit 182a946b0ef12f6f031e846af788cdeb2eecd3a6.

Fixes #422.

### CODE REVIEW

**Comment by tannewt** [comment]
I'm gonna take a peek at the usb logs for this before approving. I have no idea why this would make a difference.

**Comment by dhalbert** [comment]
I have no idea either! I thought it might have been a descriptor issue. Do you want me to take some Windows Beagle USB logs for you with and without the revert?

**Comment by tannewt** [comment]
Ill do it with my windows box

**Comment by dhalbert** [comment]
This revert is just to get MSC working on Windows again. There are still known problems. The "Align SCSI responses" commit fixes one, but others fixes are still being debugged.

**Pull request merged**
