### PR TITLE
Bring 7.1.x changes into main - cascadetoml undo + alarm fixes

### PR DESCRIPTION
**Pull request by dhalbert**
Reverts #5754 now that there is a fixed release of `cascadetoml`.

### CODE REVIEW

**Review by tannewt — DISMISSED** [review]
I think this should revert the windows changes as well. I missed that with my revert.

**Comment by dhalbert** [comment]
> I think this should revert the windows changes as well. I missed that with my revert.

The windows change was never merged into `main`. I closed the PR: #5756 before it was merged, so I think it's OK. I don't see any change in `main`: did I miss something?

**Comment by jepler** [comment]
I agree, this needs to revert f527ef0.

**Comment by dhalbert** [comment]
> I agree, this needs to revert [f527ef0](https://github.com/adafruit/circuitpython/commit/f527ef0eb8e6e1eb744c9c552d3dba4c76a81102).

That commit is only in 7.1.x? Could you submit a 7.1.x revert PR? Thanks.

**Comment by tannewt** [comment]
I made #5765 through the github UI.

**Comment by dhalbert** [comment]
This PR is now a general `main` update from `7.1.x`.

**Review by jepler — APPROVED** [review]
now it should be good to go

**Pull request merged**
