### PR TITLE
Add basic Pybadge board definition

### PR DESCRIPTION
**Pull request by jreese**
Currently boots on board and can connect to REPL,
but does not appear as mountable drive in OS.
Starting REPL gives the following error message:

```
You are running in safe mode which means something unanticipated happened.
Looks like our core CircuitPython code crashed hard. Whoops!
Please file an issue at https://github.com/adafruit/circuitpython/issues
 with the contents of your CIRCUITPY drive and this message:
Crash into the HardFault_Handler.
```

### CODE REVIEW

**Comment by dhalbert** [comment]
We'll wait for your word that it's working before merging.

**Comment by jreese** [comment]
This was done during the PyCascades sprint, using a board borrowed from @tannewt that I no longer have access to.

**Comment by tannewt** [comment]
@dhalbert I've fixed this up and am passing tests.

**Comment by dhalbert** [comment]
#1626 fixed in a more obvious way :smiley: . Never mind about that.

**Pull request merged**
