### PR TITLE
Fix audacity mp3 (erroneous EOF detected)

### PR DESCRIPTION
**Pull request by jepler**
The old formulation
 * could cause an erroneous EOF and stop playing
 * wouldn't work if there were ID3 tags at the end
 * would choose whether to background-refill the inbuf
   based on a check before skipping to the next sync word, which
   could be incorrect.

I think point 3 triggered point 1, leading to the EOF
problem fixed in the first commit. This would depend on specific data
sizes and offsets occuring in the file such that a read would be
scheduled but then the buffer would be filled and left 100% full by
find_sync_word(). It's just lucky(?) that a particular person produced
such a file, and/or many files produced by Audacity have those
characteristics.

### CODE REVIEW

**Review by gamblor21 — APPROVED** [review]
Changes look fine, but I did not test. If you want a test I would need an mp3 file to try it on.

**Comment by jepler** [comment]
Attachment has affected mp3s (I tested with 1.mp3): https://forums.adafruit.com/download/file.php?id=92072

forum thread: https://forums.adafruit.com/viewtopic.php?f=60&t=189312

**Comment by dhalbert** [comment]
> * could cause an

missing words?

**Comment by jepler** [comment]
Original reporter says this fixes their mp3 files: https://forums.adafruit.com/viewtopic.php?f=60&t=189312&p=922186&e=922186

**Pull request merged**
