### PR TITLE
Tilegrid size properties

### PR DESCRIPTION
**Pull request by FoamyGuy**
This change introduces properties to access `height`, `width`, as well as `tile_height`, and `tile_width` for TileGrid objects. Can be accessed like this:
```py
print("width: {}".format(tile_grid.width))
print("height: {}".format(tile_grid.height))
print("tile_height: {}".format(tile_grid.tile_height))
print("tile_width: {}".format(tile_grid.tile_width))
```
These values can make it easier to place a TileGrid in some relative position i.e. center it in the center of the display.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
This passed pre-commit locally:
```
circuitpython_adafruit on  tilegrid_size_props [$?] via 🐍 v3.8.10 
❯ pre-commit run --all-files
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
Translations.............................................................Passed
Formatting...............................................................Passed
```
But it failed the formatting check in CI. I'm not sure what could account for the difference. Trying to look into it to see if my version of uncrustify could be different.

**Comment by jepler** [comment]
The build failures are due to tomlkit==0.8.0 being incompatible with 0.7.2.  I'll look into it further. It'll probably need a cascadetoml release to fix.

The pre-commit failures are "correct", your code isn't properly indented.  Let's figure out why your local config is not working. First, what's `uncrustify --version` print?

**Comment by FoamyGuy** [comment]
@jepler thank you
```
❯ uncrustify --version
Uncrustify-0.71.0_f
```

**Review by jepler — APPROVED** [review]
This looks good, thanks.  Didn't actually test it. The cascadetoml build failures will need to be fixed by other means.

**Pull request merged**
