### PR TITLE
pIRKey tested w/ hardware

### PR DESCRIPTION
**Pull request by ladyada**
basically a trinket or gemma with only dotstar LED + IR Receiver

### CODE REVIEW

**Comment by dhalbert** [comment]
@ladyada I looked at the new files and compared with Trinket and they look OK by me. Do you want a review and merge?
@tannewt ok by you?

**Comment by ladyada** [comment]
hiya yes plz review and merge if acceptable for 2.3

**Comment by ladyada** [comment]
PCBs ordered!

**Comment by dhalbert** [comment]
woowee!

**Pull request merged**
