### PR TITLE
Use nina-fw root certs

### PR DESCRIPTION
**Pull request by tannewt**
That way we have one set we use for all of Adafruit's connected
devices.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
It looks fine, but no idea how to test.

**Comment by jepler** [comment]
.. except for build failures anyway.  doxygen needs to be directed away from the newly added md files?

**Comment by tannewt** [comment]
@jepler This is ready. The one failure was transient.

**Review by dhalbert — APPROVED** [review]
:+1:

**Pull request merged**
