### PR TITLE
same54: Use the same optimization as other sam d5x/e5x

### PR DESCRIPTION
**Pull request by jepler**
It's likely that this is a relic of my early testing.

### CODE REVIEW

**Comment by dhalbert** [comment]
I think the `-O2`s were from #3190. I had to change back the SAMX51's because 512kB of flash was no longer sufficient.

**Review by dhalbert — COMMENTED** [review]
I would suggest that we not do this. #3190 found significant performance improvements with -O2. On SAME54 right now, we have plenty of flash, so let's not do this unless necessary. It's too bad the SAMx51 builds are filling up enough to have to go back to -Os, but that's the price of features :)

**Comment by dhalbert** [comment]
Closing based on my review, but can revisit.

**Comment by jepler** [comment]
Do we want to ditch the "no inline" flag though?

**Comment by dhalbert** [comment]
> Do we want to ditch the "no inline" flag though?

Trying that.

**Review by dhalbert — APPROVED** [review]
OK, `-O2` fits on the big SAME54, so let's get better performance in this case.

**Pull request merged**
