### PR TITLE
STM32: Neopixel support

### LINKED ISSUE #2264: Support neopixel_write on STM
nis reported on Discord that `neopixel_write` isn't available on the STM32F405 feather. This either means it's not implemented at all or the module isn't turned on.

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds Neopixel support to the STM32 port. Tested on a Feather F405 with success. This implementation uses the DWT->CYCCNT to avoid conflicts with Systick timing and allow use in a disabled interrupt context. 

Timings are roughly borrowed from the [Arduino implementation](https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp#L1902), but I found they did not work in practice with either external neopixels or the on-feather one, so adjusted magic values had to be used instead. In addition, I'm not entirely certain why the DWT access register assignment `ITM->LAR = 0xC5ACCE55` _isn't_ required. These issues might warrant another look at a later time. 

Resolves #2264

### CODE REVIEW

**Comment by ladyada** [comment]
will test if you toss me a bin!

**Comment by hierophect** [comment]
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3853417/firmware.bin.zip)

**Comment by hierophect** [comment]
Also, just wanted to check on the expected behavior of the on-board neopixel. On my Atmel control, it is green during runtime and flashes yellow when reset, but on my ST board, it only flashes yellow when reset and is otherwise dark. Is this a bug or a version difference?

**Comment by dhalbert** [comment]
> Also, just wanted to check on the expected behavior of the on-board neopixel. On my Atmel control, it is green during runtime and flashes yellow when reset, but on my ST board, it only flashes yellow when reset and is otherwise dark. Is this a bug or a version difference?

The Atmel behavior is the expected behavior. The yellow is a 700ms window when you can click again and get into safe mode. So sounds like the RGB status setup on the STM Feather is not correct.

**Comment by ladyada** [comment]
tested with neopixel library and fancyled - works like a treat :)

**Comment by hierophect** [comment]
Looks like I missed some manual reset conditions in Microcontroller related to the rgb_status shared binding. I'm working on that now, should resolve how the Neopixel isn't consistently showing green during runtime properly.

**Comment by hierophect** [comment]
@dhalbert new commit should fix status LED issues. 

@ladyada bin if you'd like to try it again with good status LED 
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3860162/firmware.bin.zip)

**Comment by ladyada** [comment]
yep neopixel status is now working as expected

**Comment by dhalbert** [comment]
I'm seeing a brief bright flicker on the pulsing green NeoPixel (before entering REPL), and when I enter REPL then NeoPixel is extremely bright. Do you see this?

**Comment by hierophect** [comment]
@dhalbert I don't see any differences between my board and my m4_express. I assume you're using the binary in my latest post?

**Comment by dhalbert** [comment]
> @dhalbert I don't see any differences between my board and my m4_express. I assume you're using the binary in my latest post?

I pulled from your repo and am building the latest `stm32-neopixel` branch version. Hmm.

**Comment by hierophect** [comment]
You could try the binary, but it's possible I still missed something about the status LED guts - can you give me exact repro steps? And when you say extremely bright, is it as bright as the max LED strength if you plug in 0 FF 0 in a test sketch?

**Comment by dhalbert** [comment]
@hierophect That STM Feather board is bad in some way. I have another board that works fine. Also the bad board is very difficult to get into DFU mode (though it gets into REPL just fine).

**Pull request merged**
