### PR TITLE
add robots.txt to specify doc versions to appear in search engines

### LINKED ISSUE #3263: Prevent old versions of the documentation from being indexed by Google
A common issue when searching for Circuitpython's ReadTheDocs hosted documentation is that the pages for module APIs returned by Google are often very old, sometimes even going back to version 3.x or even 2.x. A prominent warning has been added to these pages to prevent users confusing old APIs for current ones, but a better solution would be to prevent these pages from being indexed by search engines altogether. 

I found a [Github issue](https://github.com/readthedocs/readthedocs.org/issues/2430) for readthedocs started by the Astropy project that mirrors this exact issue. This conversation indicates a solution is possible, documented here: https://docs.readthedocs.io/en/latest/faq.html#how-can-i-avoid-search-results-having-a-deprecated-version-of-my-docs

An example of Astropy's implementation of this feature is in their PR here: https://github.com/astropy/astropy/pull/8383

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #3263 in a simple way, adding a static `robots.txt` file. The stable version specified in the `robots.txt` needs to be updated when it changes; it's currently `5.3.x`. The `robots.txt` could generated automatically, though I'm not sure how off the bat.

### CODE REVIEW

**Comment by jepler** [comment]
How will this affect URLs on circuitpython.readthedocs.io such as https://circuitpython.readthedocs.io/projects/display_text/en/latest/ -- will search engines still be permitted to index them?  The way I read it, they would be forbidden.

**Comment by dhalbert** [comment]
> How will this affect URLs on circuitpython.readthedocs.io such as https://circuitpython.readthedocs.io/projects/display_text/en/latest/ -- will search engines still be permitted to index them? The way I read it, they would be forbidden.

Good point: I mistakenly thought those were under another URL. I'll add a prefix to robots.txt.

**Comment by dhalbert** [comment]
This needs a lot more thought. Converting to draft. https://circuitpython.readthedocs.io/projects, for instance, is not a searchable top-level point.

**Comment by sommersoft** [comment]
I think that the sub-project pages will be allowed via the `Allow: /*/latest/`, after reviewing the syntax for `robots.txt` and using an online tester.
rtd_robots_test

Probably worth getting this in, and seeing the result after a couple days. Google's documentation does say not to rely on `robots.txt` and use meta tags instead. It may end up being a multi-pronged approach.

**Comment by hierophect** [comment]
Following the rabbit hole on the [original issue](https://github.com/readthedocs/readthedocs.org/issues/2430) I linked, I saw a number of discussions involving tags vs robots, so there may be some resources available off that original discussion.

**Comment by tannewt** [comment]
Where are we at on this? It's marked as blocking 6.0.0

**Comment by dhalbert** [comment]
I would like to revive this, and have un-drafted it. @sommersoft's [old comment](https://github.com/adafruit/circuitpython/pull/3291#issuecomment-674914574) may assuage my original concerns.

Info from readthedocs: https://docs.readthedocs.io/en/latest/hosting.html#custom-robots-txt-pages

**Review by tannewt — APPROVED** [review]
Thanks for circling back on this!

**Comment by dhalbert** [comment]
I hope it works! We'll have to take a look at the search results after a while.

**Comment by hierophect** [comment]
How fast do we expect this to propagate? Checking it today, it still shows out of date documentation as the first result.

Results from today (incognito). First link is to the 2.x version, second is to latest.
Screen Shot 2021-01-14 at 2 11 09 PM

If it's too early, hopefully this image is a helpful baseline to test again - ideally we should only see the second result appear in search.

**Comment by dhalbert** [comment]
It can take a while: https://developers.google.com/search/docs/advanced/crawling/ask-google-to-recrawl

**Comment by hierophect** [comment]
As of today, I'm still seeing results from 2.x and 3.x as the first result on Google, but it's now hiding the content. Typically the Latest docs are the second result. So... partial success? At least it's now easy to tell from the search results page which links are going to go to Latest, even if the bad links still show up. 

Screen Shot 2021-03-08 at 12 40 02 PM

**Pull request merged**
