### PR TITLE
Finer grained, per port tick locking

### LINKED ISSUE #3504: Problems with _pew on SAMD21
I have been receiving some reports that the gamepad library and the _pew library don't work reliable on SAMD21 on 6.x. I suspect it's related to changes around the system tick. I didn't have time to investigate this properly yet, but I'm creating this issue to let everyone know that there is a potential problem.

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #3504 hopefully.

cc @deshipu and @cwalther

### CODE REVIEW

**Review by deshipu — DISMISSED** [review]
I just tested it with PewPew10 and it seems to fix the issue #3504, there is no flickering visible anymore.

**Review by DavePutz — DISMISSED** [review]
Tested on the SAMD21 boards; Pulsein works fine and didn't see any other issues. I tested without setting RTC_READREQ_RREQ in rtc_set_continuous(), and it looks like it works fine without that bit set.

**Review by jepler — COMMENTED** [review]
Glad we had the Discord discussion about this, it helped me follow what was going on better.  Thanks @tannewt 

The key is, this reduces the length of time that interrupts are disabled when reading the RTC.  This is especially important on SAMD21 but fixes were applied to each port that potentially required them.

**Review by jepler — APPROVED** [review]

**Comment by cwalther** [comment]
Confirmed, the flickering is much improved on a PewPew 10.2 with the binary from CI, though not totally gone. Interestingly, the influence of the USB connection is reversed now: With a USB connection, I never get any flickering. Without a USB connection, I still get some flickering when CPU usage is low (much time spent in `time.sleep()`).

**Pull request merged**
