### PR TITLE
extend visibility of nibble_to_hex_upper and nibble_to_hex_lower

### PR DESCRIPTION
**Pull request by tvieira**
This fixes the error of multiple definition that I've been finding during linking process.

### CODE REVIEW

**Comment by tvieira** [comment]
The errors I've been getting on a Fedora 32 are:

```
/usr/bin/ld: build/py/parse.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/parse.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/persistentcode.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/persistentcode.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/runtime.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/runtime.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/obj.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/obj.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objarray.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objarray.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objexcept.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objexcept.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objint.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objint.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objnamedtuple.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objnamedtuple.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objstr.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objstr.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objstrunicode.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objstrunicode.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objstringio.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objstringio.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/objtype.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/objtype.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/stream.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/stream.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/builtinimport.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/builtinimport.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/modbuiltins.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/modbuiltins.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/py/modsys.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/py/modsys.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/extmod/modure.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/extmod/modure.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
/usr/bin/ld: build/extmod/vfs.o:(.rodata.nibble_to_hex_lower+0x0): multiple definition of `nibble_to_hex_lower'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_lower+0x0): first defined here
/usr/bin/ld: build/extmod/vfs.o:(.rodata.nibble_to_hex_upper+0x0): multiple definition of `nibble_to_hex_upper'; build/py/gc_long_lived.o:(.rodata.nibble_to_hex_upper+0x0): first defined here
collect2: error: ld returned 1 exit status
```

My compiler version is:

```
➜ gcc --version
gcc (GCC) 10.1.1 20200507 (Red Hat 10.1.1-1)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tvieira** [comment]
Could it be this patch is unnecessary in the quest to solve this issue #3179?

**Comment by tannewt** [comment]
Ya, I think so. Can you just always add extern? That's what I did with my gcc10 changes. https://github.com/tannewt/circuitpython/tree/gcc10

**Comment by jepler** [comment]
Normally, you would make the declaration site be `extern`:
```
extern const char nibble_to_hex_upper[16];
extern const char nibble_to_hex_lower[16];
```
and in the one source file which defines them,
```
const char nibble_to_hex_upper[16];
const char nibble_to_hex_lower[16];
```
By doing this, the somewhat magic preprocessor macro EXTERN is not required.

**Comment by tvieira** [comment]
@tannewt did the work with #3194

**Pull request closed without merging**
