### PR TITLE
Add PortalBase and Fake Requests and update Frozen Libs on Portal boards

### PR DESCRIPTION
**Pull request by makermelissa**
This will free up some memory on a few of the boards that use the PortalBase library, which currently does not function on the MatrixPortal and is pretty close to the max space on the others.

### CODE REVIEW

**Comment by makermelissa** [comment]
Nope, it's this error actually:
```
Error: Build matrixportal_m4 for de_DE took 1.[11](https://github.com/adafruit/circuitpython/runs/5221196089?check_suite_focus=true#step:9:11)s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
mkdir -p build-matrixportal_m4/genhdr
FREEZE ../../frozen/Adafruit_CircuitPython_PortalBase ../../frozen/Adafruit_CircuitPython_Requests ../../frozen/Adafruit_CircuitPython_ESP32SPI ../../frozen/Adafruit_CircuitPython_NeoPixel ../../frozen/Adafruit_CircuitPython_Display_Text ../../frozen/Adafruit_CircuitPython_LIS3DH ../../frozen/Adafruit_CircuitPython_FakeRequests
fatal: no tag exactly matches '01f050e40[16](https://github.com/adafruit/circuitpython/runs/5221196089?check_suite_focus=true#step:9:16)87066de7bc6017c1ef8df2b4e76ed'
fatal: No tags can describe '01f050e401687066de7bc6017c1ef8df2b4e76ed'.
```
I probably froze it wrong.

**Comment by jepler** [comment]
Make sure that the submodule is pointed exactly at a tagged release, not at the tip of main.

**Comment by makermelissa** [comment]
> Make sure that the submodule is pointed exactly at a tagged release, not at the tip of main.

I don't think I did that. How is that done?

**Comment by makermelissa** [comment]
I went into the submodule and checked out the release tag for each and then committed. Hopefully that's right.

**Comment by dhalbert** [comment]
@makermelissa If you go to the top level at `circuitpython/`, there is a make target: `make update-frozen-libraries`, which does this for you. It will update all that need updating.

**Comment by jepler** [comment]
It's too much for poor matrixportal to handle .. by a lot :cry: 
```
/usr/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: build-matrixportal_m4/firmware.elf section `.text' will not fit in region `FLASH_FIRMWARE'
/usr/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH_FIRMWARE' overflowed by 33872 bytes
```

**Comment by makermelissa** [comment]
Ok, hmm. Now to figure out what to leave out. I did give it everything relevant to it.

**Comment by makermelissa** [comment]
I removed DisplayText from MatrixPortal since it really contains 3 variations and only one is loaded in memory, but it uses 60k of frozen space.

**Comment by makermelissa** [comment]
I tested compiling locally and it was still failing, so I removed a couple more frozen libs and disabled some modules that likely aren't used such as sharpdisplay, sdcardio, and bleio. If any of those are actually needed, we can shuffle it around some more.

**Comment by jepler** [comment]
Don't portal boards have SD card slots? It'd be nice to put back sdcardio.  Is the inclusion of FakeRequests unavoidable? well, I guess it's not very big...

**Comment by makermelissa** [comment]
> ~Don't portal boards have SD card slots? It'd be nice to put back sdcardio.~ Oh, that applied only to matrixportal, which doesn't have an SD slot.
Correct.

> Is the inclusion of FakeRequests unavoidable? well, I guess it's not very big...
Yeah, it's more of a convenience thing. We could remove it.

**Review by dhalbert — APPROVED** [review]
Looks good! It's too bad we have to do this even on these big chips, but there's a lot of code.

**Comment by makermelissa** [comment]
> Looks good! It's too bad we have to do this even on these big chips, but there's a lot of code.

Agreed, I think optimizing the portal libraries would help. I have an issue open to do that.

**Pull request merged**
