### PR TITLE
update tinyusb

### LINKED ISSUE #4190: RP2040: USB data stopping
I created a test program that loops turning a MIDI note on and off. After running for a while (minutes not hours) I lose USB communications (both USB-MIDI and serial debug). I have the LED flashing to debug and it appears the loop is continuing it's just USB comms that stops inexplicably.

This is only reproducible on one of my Wins10 PCs (Dell XPS desktop) and the USB driver is still active when data isn't flowing. Further if I switch to a Teensy 4.0 running the same test (written in C++) USB comms continues indefinitely. 

See forum thread for troubleshooting details: https://forums.adafruit.com/viewtopic.php?f=60&t=175112&p=854548 ]

[edit by dhalbert: on RPi Pico]

### LINKED ISSUE #5125: Update TinyUSB to include latest fixes
There are MIDI fixes and I think other fixes that are more recent than our last submodule update.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #5125.
Fixes #4190.
May fix some other issues.

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Thanks! I checked that this was a clean fast-forward update of the tinyusb submodule. No testing performed.

**Comment by dhalbert** [comment]
@LibertyBeta Could you test this after it builds? You can click on a completed "Details" link in the builds and find the "Artficats" dropdown. Thanks.

**Comment by LibertyBeta** [comment]
> @LibertyBeta Could you test this after it builds? You can click on a completed "Details" link in the builds and find the "Artficats" dropdown. Thanks.

Will do. Should hook into the `supervisor.usb_connected` right?

**Comment by dhalbert** [comment]
> Will do. Should hook into the `supervisor.usb_connected` right?

I think it should, without further effort, because that's not port-specific.

**Comment by LibertyBeta** [comment]
Can confirm that this reports correct status for `supervisor.runtime.usb_connected`.

**Pull request merged**
