### PR TITLE
Fast(ish) special purpose bitbang spi over i2c

### PR DESCRIPTION
**Pull request by jepler**
with the i2c bus operating at 400kHz this achieves a 4.8kHz SPI clock rate which could be worse.

It accepts the same style of init sequence as displayio.

tested by scoping the pins on the espressif lcd dev kit with a dummy init sequence:
<details>
<summary>Initialization exercise code</summary>

```python
import busio, microcontroller, dotclockframebuffer
expander_addr = 32
init_sequence=b"\x55\3\xaa\xff\x00" * 100

bus = busio.I2C(microcontroller.pin.GPIO18, microcontroller.pin.GPIO8, frequency=400_000)

if not bus.try_lock():
    raise RuntimeError("Bus already locked")
bus.writeto(expander_addr, b"\3\xf1")
bus.writeto(expander_addr, b"\2\0")
bus.unlock()

dotclockframebuffer.ioexpander_send_init_sequence(
    bus=bus,
    i2c_address=expander_addr, 
    gpio_address=1,
    gpio_data_len=1,
    gpio_data=0xff,
    cs_bit=1,
    mosi_bit=3,
    clk_bit=2,
    init_sequence=init_sequence)
```
</details>

image

I'm not 100% thrilled with the naming & placement of this function so please feel free to bikeshed that.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Isn't the main reason to have this natively is for boards with native displays? It's a bit weird that there isn't one using it. I wonder if it should only be made available internally.

From Python can't we do IOExpander DigitalInOuts + bitbangio?

**Comment by jepler** [comment]
Yes, this is needed to support boards with built-in displays like the esp32s3 lcd dev kit. but if you like I can gather numbers showing it's also a good deal faster than a pure Python bitbang spi-over-i2c. (even so, it's not fast; each SPI bit is 2 I2C transactions with 24 bits each, so the absolute maximum with a 100kHz I2C bus is about 2kHz and in practice it's slower; the 400kHz I2C bus only got to 4.8kHz SPI bit rate)

**Comment by jepler** [comment]
I can rebase out this commit if you like: https://github.com/adafruit/circuitpython/pull/8401/commits/a8b81ce9438f2ed448c7b6c4f9d7f3054c599948

**Comment by tannewt** [comment]
We discussed this in the weeds today. This is a good interim solution until we decide how to use abstract DigitalInOut-like objects with native `bitbangio` for native IOExpander support.

**Review by tannewt — APPROVED** [review]

**Pull request merged**
