### PR TITLE
Prevent folder from trying to move inside itself

### LINKED ISSUE #6812: Web Workflow: Renaming a folder to be inside itself removes it
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.0
```

### Code/REPL

```python
N/A
```

### Behavior

If you go into the offline editor http://circuitpython.local/fs/ and rename a folder, it shows the full path. If you set it so it is inside itself (for instance you rename /test/ to /test/test2/) then the folder disappears with no error. I would expect an error message.

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes #6812. 

Tested on Feather ESP32-S3 TFT using Web Workflow offline file manager:
- Tested that attempting to move a folder into itself fails
- Tested that attempting to move folder into another folder that doesn't exist fails
- Tested that moving a folder into another folder that does exist still works
- Tested that moving a file into a folder that exists still works
- Tested that renaming a folder still works
- Tested that renaming a file still works
- Tested renaming and moving in the same operation works

### CODE REVIEW

**Comment by dhalbert** [comment]
I would like to see about putting this check inside `fs_rename()` so it can apply in more cases (and moving the existing check out of `fat_vfs_rename()`).

**Comment by makermelissa** [comment]
> I would like to see about putting this check inside `fs_rename()` so it can apply in more cases (and moving the existing check out of `fat_vfs_rename()`).

Did you mean `f_rename()`? If so, is it used in other places too? Your suggestion  also makes sense to reduce duplicate code.

**Comment by dhalbert** [comment]
> Did you mean `f_rename()`?

Yes, sorry, fixed.

**Comment by makermelissa** [comment]
Ok, code moved. I also re-ran all the checks with Web Workflow again with the same results. I wasn't sure how to test the changes inside `fat_vfs_rename()`.

**Comment by makermelissa** [comment]
Ok, it looks like the `extmod/vfs_fat_fileio2.py` unit test is now failing from this change and this has gone way over my head.

**Comment by dhalbert** [comment]
Thanks for working on it. I will add this to my list to work on. Since it's not a show-stopper, I won't do it immediately, but will try to fix before 8.0.0.

**Comment by makermelissa** [comment]
Thank you.

**Review by dhalbert — APPROVED** [review]
OK, I touched up a return value, which fixed the test, and I added a test for the actual case of trying to rename a dir inside itself. Thanks @makermelissa for working on this!

**Pull request merged**
