### PR TITLE
Only enable is31fl3741 for led glasses board

### PR DESCRIPTION
**Pull request by prplz**
From the description of #5584, the `is31fl3741` is supposed to only be enabled for the led glasses board. I found that it was mistakenly enabled by default on all nrf boards.

Also fixed an uninitialized variable warning that prevents the module from building in debug mode. I don't actually know anything about this device and I just assumed the variable was supposed to start at zero. I don't own the led glasses board, so I was unable to test.

I confirmed the led glasses build still includes the is31fl3741 module, by inspection of the .map file and confirmed that another unrelated nrf board no longer contains the unneeded module.

### CODE REVIEW

**Comment by dhalbert** [comment]
@ladyada is this what you'd like: `is31fl3741` enabled only on the glasses driver board?

**Comment by gamblor21** [comment]
The missing initialization is fixed in #5726 which has a lot of changes to the whole structure of the **is31fl3741** module. The PR is still waiting to be merged.

As to which boards it is enabled on I cannot remember the initial discussion but an product like https://www.adafruit.com/product/5201 can take advantage of this module as well.

At the time I submitted the first PR I had only been working on NRF boards so had not had the time to test it on other types of boards like ESP/RP2040/M4 (though it should work)

**Comment by ladyada** [comment]
@dhalbert yep only on the led glasses

**Review by dhalbert — APPROVED** [review]
Thanks! @gamblor21, I will merge this for now, and we can still work on your PR.

**Comment by gamblor21** [comment]
> Thanks! @gamblor21, I will merge this for now, and we can still work on your PR.

Sounds good. I'll try to take a look later but it probably will not conflict.

**Pull request merged**
