### PR TITLE
rgbmatrix: update protomatter to 1.0.5 tag

### PR DESCRIPTION
**Pull request by jepler**
this is tested on
 * stm32f405 feather
 * matrixportal
 * nrf52840 feather
which covers all of the supported microcontroller families.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I built and tested this on Matrix Portal running the Monster eyes project everything is working well. I can test a few other devices as well.

**Review by FoamyGuy — COMMENTED** [review]
Tested this on Feather M4 with the rainbow 2 line text scroller from here: https://learn.adafruit.com/rgb-led-matrices-matrix-panels-with-circuitpython/example-two-line-colorful-text-scroller and it's working well.

**Comment by jepler** [comment]
do you have an nrf52840 or stm32 you could test with?  I expect all the m4 boards to function about the same, but testing these other too would be good.  I'll set aside a bit of time on monday for it if you don't have the chance.

**Comment by FoamyGuy** [comment]
I'm trying to test out the 2 line text scroller linked above with Feather nrf52840 but having some trouble. I think it may be unrelated to this PR though. It seems the `board` pins are different. I'll see if I can get the correct pins worked out.

**Comment by FoamyGuy** [comment]
I tried to follow the pins from here: https://learn.adafruit.com/rgb-matrix-featherwing/pinouts#nrf52840-featherwing-wiring-3070338-12. My initializer looks like this: 
```python
matrix = rgbmatrix.RGBMatrix(
    width=64, height=32, bit_depth=4,
    rgb_pins=[board.D6, board.A5, board.A1, board.A0, board.A4, board.D11],
    addr_pins=[board.D10, board.D5, board.D13, board.D9],
    clock_pin=board.D12, latch_pin=board.RX, output_enable_pin=board.TX)
```
It's not throwing errors any more, but it's only showing a single blue row of pixels on one long edge of the screen. None of the scrolling text is drawing for me. I tried with this PR build as well as `5.3.1` and `6.0.0.beta2` and I am getting the same results on all of them.

**Comment by FoamyGuy** [comment]
I see now there is a separate feather wing needed for the nrf feathers, that is the source of my trouble. 

I did also built this for stm32f405 and flashed a device with it. No issues that I noticed. But I'm not set up to run the matrix with that feather either.

**Comment by jepler** [comment]
Thanks for the testing you could do!  I'll run this on some HW I do have, tomorrow.

**Comment by jepler** [comment]
I tested this on the STM32F405 Feather and the nRF52840 Feather.  all work fine.

**Review by tannewt — APPROVED** [review]
Thank you! Clean up looks good.

**Pull request merged**
