### PR TITLE
make nrf touchio be generic: now available for SAMD51 too

### LINKED ISSUE #268: Add `touchio` support to the M4.

### PR DESCRIPTION
**Pull request by dhalbert**
- Generalize the nRF "charge up pin" touchio implementation so it can be used by all ports, and move it to `shared-module/touchio`.
- Turn on generic `touchio` for SAMD51. Now all CircuitPython ports have `touchio`.
- Add `CIRCUITPY_TOUCHIO_USE_NATIVE` flag to indicate whether to use `common-hal/touchio` or `shared-module/touchio`. Because SAMD21 has a native implementation, but SAMD51 does not, it was difficult to do this automatically, using, say, weak references. The lists of source directories (`SRC_COMMON_HAL` and `SRC_SHARED_MODULE`) in `circuitpy_defns.mk` were generalized a bit to allow conditional inclusion of files in those lists.

Tested on Feather and Metro M4, and Feather nRF52840. Also verified that native implementation is still used on SAMD21. Tested with a 1Meg pulldown. Tested with finger touch and a banana. Test jig eaten later.

The generic implementation now uses high pin drive instead of the previous use of standard drive on nRF52840, because high drive is our default for `common-hal` GPIO. This does not seem to be a problem and may actually work better for long captouch leads.

Fixes #268 and #1517.

Tagging @nickzoic for interest.

### CODE REVIEW

**Comment by dhalbert** [comment]
> 1. Can you verify the existence of the resistor and error if it's not attached?

Yes, it turns out I can detect that. I have a change to throw an exception and will push that later after resolving the discussion below.

> 2. What happens when we add native touch support? Is it ok to leave the resistor on? Should we name this differently so it's clear that it's a separate implementation?

I tested on a SAMD21 with native `touchio` and it still works even with a 1M resistor. 

I don't think we should name this differently, because then programs that use `TouchIn` aren't interchangeable between boards. It works identically from the user's point of view, except for requiring a pulldown.

One interesting thing is that native touch support is not available on all pins on SAMD21. We could fall back to this implementation for pins that don't support native touch. In that case (only), it could have a different name, or we could silently fall back. @ladyada Do you have an opinion about this?

**Comment by tannewt** [comment]
Why aren't uses of TouchIn interchangeable? Is the API different?

**Comment by dhalbert** [comment]
> Why aren't uses of TouchIn interchangeable? Is the API different?

They are interchangeable. I was responding to _Should we name this differently so it's clear that it's a separate implementation?_ and saying we shouldn't name them differently. Or did you just mean .c/.h filenames.

**Comment by tannewt** [comment]
Ah right. I misread it. All good from me if the native touch works when the resistor is there if we ever "upgrade" the implementation.

**Comment by dhalbert** [comment]
Update:
- Complain if no pullup.
- Complain if pin in use. Missed this before, found it during testing.

**Comment by ladyada** [comment]
no opinion, shared naming is fine by me

**Comment by dhalbert** [comment]
@tannewt ok, should be all set now

**Pull request merged**
