### PR TITLE
Document TileGrid limitation to tile values 0..255 & improve mp3 doc

### LINKED ISSUE #6133: RP2040 mp3 playback is static
Reported on the forum and confirmed by Neradoc and cater on Discord:

https://forums.adafruit.com/viewtopic.php?f=60&t=189077&p=915505#p915505

### LINKED ISSUE #6149: displayio.TileGrid does not document limitation to 255 frames
[TileGrid.__setitem__](https://docs.circuitpython.org/en/latest/shared-bindings/displayio/index.html#displayio.TileGrid.__setitem__) enforces, but does not document, a limitation to 255 tile elements.

This limitation is not great for my needs, but the failure to document what's going on, or provide a more informative error message, led to a merry hour of debugging.  TileGrid also doesn't allow introspection in any way of how many tiles are available to be addressed, so I was extremely confused until I finally just tried "keep setting tiles up to the highest index valid until we crash," at which point I discovered the crash at 256, which immediately suggested a problem with TileGrid, not the design of the bitmap I was indexing into.

### PR DESCRIPTION
**Pull request by jepler**
Closes #6149. Closes #6133.

### CODE REVIEW

**Comment by jepler** [comment]
That's not to say we shouldn't improve tilegrid in the future!

**Review by dhalbert — APPROVED** [review]
Thanks for noting this!

**Review by dhalbert — DISMISSED** [review]

**Review by FoamyGuy — COMMENTED** [review]
I just ran into this TileGrid limitation yesterday as well and looked into the code and came to the same conclusion about the 255 limit. Thank you for adding some mention of it to the docs.

It might be worth documenting this limit on the `__setitem__` docstring down here as well: https://github.com/adafruit/circuitpython/blob/359d8e57730a8c9a68fd5429691f5825bdc3cf61/shared-bindings/displayio/TileGrid.c#L389 This is one of the places I looked before going into the code.

**Review by dhalbert — APPROVED** [review]
Thanks!

**Pull request merged**
