### PR TITLE
Request to add a COSMO-Pico board

### PR DESCRIPTION
**Pull request by startup-potech**
I followed the "Get Setup to Add Your Board" to create a new board called COSMO-Pico. Please confirm.

- [x] Update VID/PID.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Looks good! I'd like to wait until the PID is published by raspberry pi.

**Comment by startup-potech** [comment]
Thanks, the PID has been filed with the Raspberry Pi Foundation. It will be published soon.

**Comment by dhalbert** [comment]
Made draft due to awaiting VID/PID.

**Comment by startup-potech** [comment]
IDs are as follows
The table has not been updated, but the numbers are valid.

Vendor ID = 0x2E8A
Product ID = 0x104C

PID_mail

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
