### PR TITLE
Add support for WeAct Studio Pico

### PR DESCRIPTION
**Pull request by fabaff**
Add support for WeAct Studio Pico

- Details: https://de.aliexpress.com/item/1005003708090298.html?gatewayAdapt=glo2deu
- Request for PID: https://github.com/WeActTC/WeActStudio.RP2040CoreBoard/issues/2

### CODE REVIEW

**Comment by fabaff** [comment]
Assigned PID: 0x102E (https://github.com/raspberrypi/usb-pid/commit/690a77c1e3061db7aa20557bd422ba0b707a190c)

**Review by dhalbert — APPROVED** [review]
Thanks for the contribution and getting the PID!

**Comment by domdfcoding** [comment]
Does this change support the 4MB/8MB/16MB flash variants, or only the 2MB version?

**Comment by fabaff** [comment]
> Does this change support the 4MB/8MB/16MB flash variants, or only the 2MB version?

I think only the 2 MB variants as that was the only hardware I had at the point in time when I worked on this unit.

**Pull request merged**
