### PR TITLE
Custom builds for forks and branches

### PR DESCRIPTION
**Pull request by tyeth**
This updates the custom builds action to support forks, also renaming it to increase visibility as it has been off the bottom of the actions list for a while, but might be more used if more seen.

### CODE REVIEW

**Comment by dhalbert** [comment]
> renaming it to increase visibility as it has been off the bottom of the actions list for a while,

Could you show a screen shot?

We should document this in the Building CircuitPython guide!

**Comment by tyeth** [comment]
That's a great idea (adding it to the docs).

I think the actions list is both alphabetically and last used, so normally
it's off screen, but currently as I've been hammering the builds for BLE
testing it might be visible.

This is what my phone see's


Whereas with this change the single board action will be second (just above
Build boards), along with supporting forks and branch selection (only used
if version/tag is default of latest)

**Comment by tyeth** [comment]
TIL: sending image attachments as part of email replies doesn't work.

My phone sees this:

**Comment by tyeth** [comment]
And on Desktop: 
image

**Review by dhalbert — APPROVED** [review]
Thanks!

We should look at that list of build actions more carefully. Some are inapplicable, like the cc3200 port...

**Pull request merged**
