### PR TITLE
main: redesign boot_out.txt writing

### PR DESCRIPTION
**Pull request by jepler**
New design:
 * capture output to a vstr
 * compare the complete vstr to boot_out.txt
 * rewrite if not a complete match

This is resilient against future changes to the automatic text written to boot_out.txt.

This also fixes rewriting boot_out.txt in the case where boot.py prints something.

Perhaps it also saves a bit of code space. Some tricks:
 * no need to close a file in read mode
 * no need to switch on/off USB write access, going down to the   oofatfs layer doesn't check it anyway

This is  a possible alternative to 
 * #5535 .

### CODE REVIEW

**Review by dhalbert — COMMENTED** [review]
What happens if a write goes past the end of the `vstr`? Does it just discard the overflow?

How did you test? The easiest way I found to test whether a rewrite happened or not was to lengthen the 1 second delay to 10 seconds. I had a `code.py` that blinked `board.LED`, so I knew when it started.

**Comment by jepler** [comment]
> What happens if a write goes past the end of the vstr? Does it just discard the overflow?

The allocation is increased, until it fails.  This means you could now MemoryError yourself if `boot.py` produces a lot of output.

> How did you test? The easiest way I found to test whether a rewrite happened or not was to lengthen the 1 second delay to 10 seconds. I had a code.py that blinked board.LED, so I knew when it started.

I temporarily had code that turned the LED red during the 1 second delay before writing out the file. After changing boot.py to output something else and hitting reset, I would get the red LED once but not the next time I hit reset.

**Comment by dhalbert** [comment]
> > What happens if a write goes past the end of the vstr? Does it just discard the overflow?
> 
> The allocation is increased, until it fails. This means you could now MemoryError yourself if `boot.py` produces a lot of output.

That's a bit of a pathological case, but I think the exception should be caught if possible so you don't get no output, which is what would happen.

**Comment by dhalbert** [comment]
If it's hard to catch the MemoryError, then you could just truncate the output after some relatively small amount (a few thousand chars), and add an ellipsis or something.

**Comment by jepler** [comment]
Now this boot.py:
```py
for i in range(1000):
    print(i)
```
creates a 512-byte boot_out.txt that ends
```
88
89
...
```

**Review by dhalbert — APPROVED** [review]
I like it! Thanks for fixing this well.

**Pull request merged**
