### PR TITLE
STM32: Add PYB Nano support

### PR DESCRIPTION
**Pull request by hierophect**
This PR adds support for the [PYB Nano V2](https://www.elecrow.com/micropython-development-board-pyb-nano-compatible-with-python.html), which uses the STM32F411CE on a small form factor board with a W25Q64JV_IQ for external flash support and a built in MMA7660FC accelerometer. Tested for flash operation and multiple modules of support with success. 

Drops the Blackpill from #2312, since it has proven flaky in testing. Partially addresses #2196

### CODE REVIEW

**Comment by ladyada** [comment]
please upload a photo or diagram showing what external chips you have wired up

**Comment by tannewt** [comment]
Please remove the stm32f401 changes from here since the PYB Nano is a 411. No need to open a new PR though. Just push a new commit here.

**Comment by hierophect** [comment]
@tannewt sure, good catch. Those should go in with the Meowbit

**Comment by hierophect** [comment]
@ladyada Here's a photo of a full test rig: 
IMG_2509
Here's the PYB nano pinout. Tested using I2C1, SPI1 + X8 CS, A0, PWM on X1, and the TX/RX on X2/X3 (if you try the other serial note that the TX/RX on PB7 and PB6 in this picture is WRONG, they're switched, R:7 T:6). 
pybnano_pinout
Test code (all pins already named): 
[testcode.py.zip](https://github.com/adafruit/circuitpython/files/3912468/testcode.py.zip)
Bin:
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3912470/firmware.bin.zip)

Currently this code suffers the #2346 issue, but that's across all 8MHz boards, so I'm working on it separately.

**Comment by ladyada** [comment]
thanks I realized i actually have a different board - so i ordered a bunch of em :) the board i have this this one: https://www.aliexpress.com/item/4000069263843.html which has a 25mhz xtal. it'll be a week till i get the pybnano in, dya wanna try making a def for this board intead/as well?

**Comment by hierophect** [comment]
@ladyada I actually have done all the pin definitions for that as the "blackpill" (you recommended both a couple months back, I think), but I've had some problems, which is why I dropped #2312. It's erratic to flash (frequently fails validation or won't load the flash loader, doesn't work at all with gdb, etc), and I can't get USB to enumerate. I can keep hacking at it, but the PYB Nano is MUCH more stable with the same MCU (F411) which makes me wonder if there's a sourcing related issue with the blackpill. 

Do you have the schematics for the blackpill, by the way? I couldn't get them to download off Baidu without an account

**Comment by ladyada** [comment]
minif4 v1 3
minif4 2 0

**Comment by hierophect** [comment]
@tannewt @ladyada cool cool. Did we get a chance to double check the board?

**Comment by ladyada** [comment]
my order hasnt come in yet :(

**Comment by hierophect** [comment]
All good we can probably just revisit. I tested it pretty thoroughly I don't think we should see any issues.

**Comment by tannewt** [comment]
We can always fix it later. :-)

**Comment by ladyada** [comment]
yep thank you :)

**Comment by ladyada** [comment]
@makermelissa this'll need a circuitpython.org card!

**Comment by makermelissa** [comment]
Ok

**Pull request merged**
