### PR TITLE
Make chosen features consistent across all boards and ports atmel-samd, esp8266, and nrf.

### LINKED ISSUE #384: bytes objects lack a decode method in smaller non-Express builds
The `decode` method for converting from bytes to str is missing in non-Express builds. This makes it awkward to take data from I/O and print it.  It seems like this should exist, obviously the codec is ignored on a microcontroller but being able to switch immutable data types from one that iterates as ints to one that is printable and iterates as one character strings is desirable. Depending on the micropython gc internals both could share the same data buffer behind the scenes (I haven't looked inside that box yet...).

Workaround, a silly looking: `''.join(chr(b) for b in bytes_data)`

Noticed when using the Feather M0 Basic 2.1.0 circuitpython release.  I had to work around this when moving code over from where I developed it on an Express.

### PR DESCRIPTION
**Pull request by dhalbert**
1. Turn **off** `MICROPY_CPYTHON_COMPAT`, which includes a number of minor CPython compatibility features, most of which have workarounds, but uses up significant flash.
2. Turn **on** `MICROPY_PY_SYS_MAXSIZE`, which implements `sys.maxsize`.
3. Turn **on** `MICROPY_CAN_OVERRIDE_BUILTINS`, which implements "_" as the most recent value in the REPL, and also enables redefining builtins.

Fixes #384, #442, #480, respectively.

### CODE REVIEW

**Comment by jerryneedell** [comment]
Do you also want to enable ```#define MICROPY_ENABLE_SOURCE_LINE               (0)``` in the nerf build?

**Comment by dhalbert** [comment]
@jerryneedell Good idea. I didn't do any kind of comprehensive look at what's different in nrf. If you know of anything else let me know.

**Comment by jerryneedell** [comment]
That is the one I usually add along with uncommenting out the BLE_MODULE and UBLUEPY_MODULE but I think Kevin wants this tested more before they are mainstreamed.  I have been playing with them a little but happy to deal with them myself for now.

**Comment by tannewt** [comment]
Do the workarounds for CPython compat still work in CPython? I don't want us teaching bad habits that break when moving to CPython.

**Comment by microbuilder** [comment]
@jerryneedell I'm hoping to put in a PR this week with BLE support enabled out of the box, but we migrated to a different version of the SD so I need to make sure there aren't any gotchas or breaking changes that aren't immediately visible.

**Comment by jerryneedell** [comment]
@microbuilder Thanks.  So far, I have tried enabling BLE with the current version and executed the ubluepy_scan and the ubluepy_eddystone examples.

**Comment by jerryneedell** [comment]
I added the 2 proposed changes to the feather52 mpconfigport.h  ( with PR #528 as well)

#define MICROPY_ENABLE_SOURCE_LINE (1)
#define MICROPY_CPYTHON_COMPAT                   (0)

The build compiles OK and I have not seen any adverse impact.
The Source line does show up in the REPL for  Exception Tracebacks - nice!

Are there specific things to try to test turning off the CPYTHON_COMPAT ?

**Pull request merged**
