### PR TITLE
Add support for LILYGO TTGO T8 ESP32-S2

### PR DESCRIPTION
**Pull request by fabaff**
Support for the [LILYGO TTGO T8 ESP32-S2](http://www.lilygo.cn/prod_view.aspx?TypeId=50063&Id=1300&FId=t3:50063:3).

It's heavily based on the already available `LILYGO TTGO T8 ESP32-S2 V1.1 ST77789`. The main difference seems that this unit doesn't have a display, more GPIOs to use and a third button ("KEY", not implemented at the moment).

### CODE REVIEW

**Comment by fabaff** [comment]
```
Duplicate VID/PID usage found!
 - VID/PID: 0x303a:0x8007
  Boards: lilygo_ttgo_t8_s2, lilygo_ttgo_t8_s2_st7789
```

```
$ lsusb
[...]
Bus 003 Device 002: ID 06cb:00f9 Synaptics, Inc. 
Bus 003 Device 046: ID 303a:8007 LILYGO TTGO T8 ESP32-S2
```

Ignore it?

**Comment by ladyada** [comment]
hi, no they need unique PIDs please!

**Comment by tannewt** [comment]
Looks like the first version is from Espressif so you can request a second one here: https://github.com/espressif/usb-pids You may want to update the description of the original ones as well to make it clear that they have screens and a different pinout.

**Comment by fabaff** [comment]
PID request: https://github.com/espressif/usb-pids/pull/37

**Comment by fabaff** [comment]
PID: `0x80ED`

**Review by dhalbert — CHANGES_REQUESTED** [review]
Could you merge or rebase from adafruit/circuitpython? There should not be a deletion in `locale/circuitpython.pot`.

**Comment by fabaff** [comment]
> Could you merge or rebase from adafruit/circuitpython? There should not be a deletion in locale/circuitpython.pot.

The `pot` file should no longer be part of the changes. Not sure if the `pre-commit` hooks somehow interfered.

**Review by dhalbert — APPROVED** [review]
Thanks! Could you now submit a PR to https://github.com/adafruit/circuitpython-or for the board?

**Comment by fabaff** [comment]
Doc PR: https://github.com/adafruit/circuitpython-org/pull/886

**Pull request merged**
