### PR TITLE
Update ESP-IDF to 5.2.1

### PR DESCRIPTION
**Pull request by tannewt**
This updates the underlying I2C API and allocates memory. So, I switched busio.I2C to using a finalizer for reset instead of bulk reset.

### CODE REVIEW

**Comment by tannewt** [comment]
I tried this on my memento. It runs but the camera stops working. I'll look tomorrow if @jepler doesn't get to it first.

**Comment by tannewt** [comment]
Still draft because it needs: https://github.com/adafruit/esp32-camera/pull/8

**Comment by bill88t** [comment]
Just out of curiosity, why is 120m unstable?
With ESP-PSRAM64(H) chips, I didn't have a single crash due to psram.
It's a supported frequency according to the [datasheet](https://cdn-shop.adafruit.com/product-files/4677/4677_esp-psram64_esp-psram64h_datasheet_en.pdf). Is there an idf timing issue?

**Comment by tannewt** [comment]
> Just out of curiosity, why is 120m unstable? With ESP-PSRAM64(H) chips, I didn't have a single crash due to psram. It's a supported frequency according to the [datasheet](https://cdn-shop.adafruit.com/product-files/4677/4677_esp-psram64_esp-psram64h_datasheet_en.pdf). Is there an idf timing issue?

From [here](https://github.com/espressif/esp-idf/blob/be06a6f5ffe36f9554cfc91fe2036e0fc85fea60/components/esp_psram/esp32s3/Kconfig.spiram#L91-L97):

>                - Octal PSRAM 120 MHz is an experimental feature, it works when
>                  the temperature is stable.
>
>                    Risks:
>                        If your chip powers on at a certain temperature, then after the temperature
>                        increases or decreases by approximately 20 Celsius degrees (depending on the
>                        chip), the accesses to / from PSRAM will crash randomly.

**Comment by tannewt** [comment]
Ok, @dhalbert this is ready for review.

**Review by bill88t — CHANGES_REQUESTED** [review]
Port `waveshare_esp32s2_pico` still has `CIRCUITPY_ESP_PSRAM_FREQ = 120m`.
I ran a string search just in case there are others, but no.

**Review by dhalbert — APPROVED** [review]
OK, looks good! Looking forward to 9.1.0-beta.0!

**Pull request merged**
