### PR TITLE
Add shIRtty board

### PR DESCRIPTION
**Pull request by sarfata**
I believe this PR has everything requested in the "add a board" doc now. Let me know if you have any comment before this goes in. I am not sure it's worthy of appearing on the website but if you think that would be useful I will do it. Thanks!

cc @tannewt @siddacious @chrisgervang

### CODE REVIEW

**Comment by sarfata** [comment]
Hmmm - it looks like I am cutting it too close on codespace. I have re-enabled i2cslave for this board because it is meant to be used as a shitty addon and the spec defines pines to use as i2c communication. That would explain why it fails here but not for trinket_m0.

Any advice/suggestion to quickly reclaim some space?

```
Build shirtty for zh_Latn_pinyin took 12.66s and failed
make: Entering directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: build-shirtty/firmware.elf section `.text' will not fit in region `FLASH'
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 140 bytes
collect2: error: ld returned 1 exit status
Makefile:314: recipe for target 'build-shirtty/firmware.elf' failed
make: *** [build-shirtty/firmware.elf] Error 1
make: Leaving directory '/home/runner/work/circuitpython/circuitpython/ports/atmel-samd'
```

**Comment by tannewt** [comment]
Does the board do any touch sensing? You could turn off `touchio` like pIRkey does: https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/boards/pirkey_m0/mpconfigboard.mk#L23

**Comment by makermelissa** [comment]
Hi @sarfata, I need to add this board to the circuitpython.org website so it doesn't show up as an unknown board. I found the URL https://github.com/sarfata/shirtty-addon. Do you have any more info such as a photo of the board we could use? Thanks!

**Comment by siddacious** [comment]
@makermelissa I have this one if you want to use it
IMG_20191114_220900313

**Comment by makermelissa** [comment]
Awesome @siddacious. Would it be possible to get a photo in good lighting without the hand? I often just use a sheet of printer paper behind my photos. Thanks.

**Comment by siddacious** [comment]
@makermelissa I took that photo at SuperCon but give me a few to set up my lightbox

**Comment by siddacious** [comment]
@makermelissa actually it appears that I packed my shIRtty away somewhere while reorganizing my office. If I find it I'll take a decent picture

**Comment by makermelissa** [comment]
Ok, thanks.

**Comment by sarfata** [comment]
Hi @makermelissa - and thanks @siddacious for jumping on this.

I am in France at the moment, without any of the boards with me. But I have added 3 pictures to the repo I had on my phone:




Maybe @chrisgervang can help too.

**Comment by makermelissa** [comment]
Excellent @sarfata. I'm going to crop down the middle image and use that for now.

**Pull request merged**
