### PR TITLE
Fix PulseIn buffer overread in popleft #6318

### PR DESCRIPTION
**Pull request by mwisslead**
Tested and working correctly on an esp32-s2. I went ahead and made the change for all ports that have the bug but I don't currently have boards for testing.

### CODE REVIEW

**Review by gamblor21 — COMMENTED** [review]
Maybe I'm off here but while this may fix the symptom is the root case earlier in most ports where this code occurs:
```        
if (self->len < self->maxlen) {
    self->len++;
} else {
    self->start++;
}
```

It seems in other instances start is increased the max_len is checked but in this instance it is not. If this is similar to the line (just after the one you changed): `self->start = (self->start + 1) % self->maxlen;` would that fix the cause?

**Comment by mwisslead** [comment]
It is. Should I go ahead and add a change to bound self->start to maxlen but keep the additional bounding in popleft? The espressif port has an extra increment by 2 I wasn't sure about but looking into that it's also problematic so maybe I could fix that in this PR as well? That one appears to be the cause of #4368

**Comment by dhalbert** [comment]
It does look to me like it's not wrapping properly at that one spot, and you can remove the modulus elsewhere where you added it. In the case where it's checking for two values in a row, there the modulus may need to be one less. I will look at this in more detail tomorrow. But try fxing the increment in the case:
```c
if (self->len < self->maxlen) {
    self->len++;
} else {
    self->start++;
}
```

**Comment by dhalbert** [comment]
Thanks, when you test these new fixes, do they work as well as your original ones?

**Comment by mwisslead** [comment]
Testing for #6318 and #4368 seems to fix both issues now.

**Review by dhalbert — APPROVED** [review]
This fix looks good to me, and thanks for finding the root cause and testing! @gamblor21 Do you want to take another look?

**Review by gamblor21 — APPROVED** [review]
Looks good to me now too, thanks for the fixes!

**Pull request merged**
