### PR TITLE
Issue3247 - Compiler optimization level causing displayio instability

### PR DESCRIPTION
**Pull request by DavePutz**
Testing the demo spirit level script for the Clue showed that with the -O2 optimization from PR #3190 the display was not stable. This PR reverts the optimization back to -Os.

### CODE REVIEW

**Comment by dhalbert** [comment]
> Testing the demo spirit level script for the Clue showed that with the -O2 optimization from PR #3190 the display was not stable. This PR reverts the optimization back to -Os.

In the past this kind of behavior (usually `-Og` vs `-Os`) has typically meant that something that should be `volatile` is not, or that there's some uninitialized.

**Comment by DavePutz** [comment]
@dhalbert Are there any tools to help track that sort of thing down? I think safest for now is to take the relatively small performance hit and revert the optimization.

**Comment by dhalbert** [comment]
We have no such tools now. Could you file a bug re displayio and optimization level? Thanks! I think we should assume this is a bug, not a compiler problem?

**Comment by deshipu** [comment]
I wonder if you could run valgrind on the unix build?

**Comment by DavePutz** [comment]
Closing, fixed by PR #3281. Tested OK with a Clue and Circuitplayground Bluefruit with an attached Gizmo display.

**Comment by dhalbert** [comment]
Great, thank you for testing!

**Pull request closed without merging**
