### PR TITLE
Adafruit Macropad RP2040: Fix SPI definition

### LINKED ISSUE #4965: Macropad RP2040 locks up using board.SPI()
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.3-471-g7f39779f4 on 2021-07-01; Adafruit Macropad RP2040 with rp2040
```

### Code/REPL

```python
import board
import displayio

from adafruit_displayio_sh1106 import SH1106

OLED_WIDTH = 128
OLED_HEIGHT = 64

displayio.release_displays()

display_bus = displayio.FourWire(
    board.SPI(),
    command=board.OLED_DC,
    chip_select=board.OLED_CS,
    reset=board.OLED_RESET,
    baudrate=1000000,
)

display = SH1106(display_bus, width=OLED_WIDTH, height=OLED_HEIGHT)
```

### Behavior

When creating display_bus, the board locks.  Serial stops responding and the CIRCUITPY drive becomes unavailable.

### Description

_No response_

### Additional information

Using busio, the display initializes as expected.

```
import board
import displayio
import busio

from adafruit_displayio_sh1106 import SH1106

OLED_WIDTH = 128
OLED_HEIGHT = 64

displayio.release_displays()
spi = busio.SPI(board.SCK, board.MOSI)
display_bus = displayio.FourWire(
    spi,
    command=board.OLED_DC,
    chip_select=board.OLED_CS,
    reset=board.OLED_RESET,
    baudrate=1000000,
)
display = SH1106(display_bus, width=OLED_WIDTH, height=OLED_HEIGHT)
```

### PR DESCRIPTION
**Pull request by dgriswo**
Fixes #4965

### CODE REVIEW

**Review by microDev1 — APPROVED** [review]
@dgriswo Thanks for spotting and fixing this issue. :)

**Comment by ladyada** [comment]
woops - good catch 😅

**Comment by dgriswo** [comment]
@ladyada, a huge shout-out to @tannewt for the Friday Deep Dives.  I'm not a C programmer and a marginal Python programmer, sometimes knowing where to look and how things work is half the battle. 😉

**Comment by tannewt** [comment]
You are a C programmer now! :-D

**Pull request merged**
