### PR TITLE
added translations

### PR DESCRIPTION
**Pull request by hexthat**
just added missing translations

### CODE REVIEW

**Comment by hexthat** [comment]
msgid "Extended advertisements with scan response not supported."

is like line 785, I think it has latest

**Comment by hexthat** [comment]
think it has latest at line 682

**Comment by dhalbert** [comment]
Try `git fetch` from upstream (`adafruit/circuitpython`), then `git merge`, then do a `make translate` and push agian.

**Comment by hexthat** [comment]
> 
> 
> Try `git fetch` from upstream (`adafruit/circuitpython`), then `git merge`, then do a `make translate` and push again.

I only use the a firefox web browser for github. I don't see those options.

**Comment by hexthat** [comment]
I tried "Compare" between "Adafruit/circuitpython" and "hexthat/circuitpython" only 1 file changed.

**Comment by dhalbert** [comment]
It's hard to do in GitHub, because the translation files get all scrambled. Would it be hard for you to start a new PR and make your change on that?

**Comment by tannewt** [comment]
@hexthat I'll do the merge and push your branch. Thanks!

**Comment by tannewt** [comment]
Ok, I think it should be ok now.

@hexthat any time you start adding more translations please start with https://github.com/adafruit/circuitpython/blob/master/locale/zh_Latn_pinyin.po, click the pencil edit icon and then commit to a new branch. I think these changes were confused because the commit was done on an old version of master rather than the latest.

Thanks!

**Pull request merged**
