### PR TITLE
ulab: actually update the submodule

### PR DESCRIPTION
**Pull request by jepler**
#2802 missed the submodule update itself.

### CODE REVIEW

**Comment by jepler** [comment]
We may now face the first need to disable a ulab module, such as the newly added comparison module.  At least the espruino pico board no longer builds with this PR, due to overflowing flash.

**Comment by v923z** [comment]
> We may now face the first need to disable a ulab module, such as the newly added comparison module. At least the espruino pico board no longer builds with this PR, due to overflowing flash.

@jepler @tannewt I am willing to change the sub-module structure, if necessity be. I would, perhaps, suggest at this point to run a poll on which functions people need, and use the results as a guideline.

**Comment by jepler** [comment]
I chose to disable ulab altogether on the espruino pico.

**Comment by tannewt** [comment]
Are we able to disable submodules of `ulab` independently?

**Comment by jepler** [comment]
@tannewt yes, we are able to selectively disable parts of ulab.  I originally investigated that as a solution, but with the new ulab.comparison module deactivated it left only about 2kB (I forget exactly) of flash free.  My gut said, better to fully disable ulab on this board than return within days or weeks to revisit the issue.  If we get lto and it reclaims 20+kB as I suspect it would, that would be a great time to re-revisit it.  However, I can change this PR to disable as little as possible, if that's what you prefer.  Please merge or let me know.

**Comment by tannewt** [comment]
This is fine. Thanks!

**Comment by v923z** [comment]
> I chose to disable ulab altogether on the espruino pico.

This brings up another issue, which, perhaps, deserves its own thread: it would be really great, if users could customise their own `ulab` (or any other external module, for that matter). I have come to realise that in `circuitpython` the main tripping point is that the makefile, `py.mk`, has to be modified. Would it be possible to accept arbitrary `make` fragments from external modules, exactly as is done in `micropython`? With that, this issue of the espruino pico would be rendered redundant. 

I believe, this would benefit everyone, because `circuitpython` users could then be able to pull directly from the `ulab` repository, and try whatever they want.

**Comment by tannewt** [comment]
@v923z We should discuss this on a separate issue. Generally, we don't support users integrating their own C code into CircuitPython.

**Comment by v923z** [comment]
> @v923z We should discuss this on a separate issue. 

OK. It is here: https://github.com/adafruit/circuitpython/issues/2825

> Generally, we don't support users integrating their own C code into CircuitPython.

I understand this, but here seems to be a legitimate reason for changing that.

**Pull request merged**
