### PR TITLE
msys at least breaks elsewhere now

### PR DESCRIPTION
**Pull request by ladyada**
hopefully will not break other plats!

### CODE REVIEW

**Comment by jepler** [comment]
Our CI hates it :( :(
```
                              Check if your project's top-level CMakeLists.txt includes the right
                              CMake files. Environment IDF_PATH will be used for the build:
                              /home/runner/work/circuitpython/circuitpython/ports/espressif/esp-idf/components/bootloader/subproject/"/home/runner/work/circuitpython/circuitpython/ports/espressif/esp-idf"
```
I'll try reverting the quoting of IDF_PATH because the other fixes would be good to have.

**Comment by ladyada** [comment]
yah only the first thing is really needed (for samd builds, e.g.)

**Review by jepler — APPROVED** [review]
Good to merge if the CI is green!

**Comment by ladyada** [comment]
@jepler blah it lost the review, plz re 👀

**Review by dhalbert — DISMISSED** [review]
approving this since @jepler is not around

**Review by dhalbert — APPROVED** [review]

**Pull request merged**
