### PR TITLE
Reject RLE-compressed BMP files

### LINKED ISSUE #7450: displayio.OnDiskBitmap shows corrupted image when using a compressed BMP
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.6 on 2022-12-21; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3
Board ID:adafruit_feather_esp32s3_4mbflash_2mbpsram
```

### Code/REPL

```python
displayio.OnDiskBitmap("compressed.bmp")
```

### Behavior

The system displays an image, but it is corrupted and looks like it is not using the proper scan line width or something. I see the right colors, but displayed incorrectly

### Description

I have tried making a compressed BMP in many ways from Photoshop to other image editors. Removing compression works fine, but I have not found any compressed BMP that will draw properly.

I have tried on a Feather M4 Express as well as a Feather ESP32S3 on the 1.14" LCD display as well as the 1.3" LCD display.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #7450. Fixes #8374.

`OnDiskBitmap` did not check for compression values 1 and 2, which indicate RLE compression.

Tested with files from #8374 on a Matrix Portal S3. `NYJ.bmp` throws the new exception, as expected: it is RLE-compressed. `NYJ1.bmp` is not compressed and works.

### CODE REVIEW

**Comment by dhalbert** [comment]
I have to get 36 bytes back in metro m0 pinyin:
```
253732 bytes used, -36 bytes free in flash firmware space out of 253696 bytes (247.75kB).
```

**Review by tannewt — DISMISSED** [review]
Thank you!

**Comment by dhalbert** [comment]
Some errors that were paraphrases of each other were consolidated to a single message. Some qstr refactoring was also done, though this sometimes produces little or no size improvement.

**Review by jepler — COMMENTED** [review]
Thank you!

**Pull request merged**
