### PR TITLE
Implement gifio.GifWriter

### PR DESCRIPTION
**Pull request by jepler**
This involves:
 * Adding a new "L8" colorspace for colorconverters
 * factoring out displayio_colorconverter_convert_pixel
 * Making a minimal "colorspace only" version of displayio for the unix port (testing purposes)
 * fixing an error message

img0108

### CODE REVIEW

**Comment by jepler** [comment]
I'll be doing a bit more testing before I mark this as ready for review.

**Comment by jepler** [comment]
On Kaluga I can capture 320x240 to SD card at about 2.4fps.

**Comment by jepler** [comment]
A very superficial look at a digital scope trace of the SD "clock" pin implies it is mostly waiting for the SD card to signal a write is complete. The shaded portion represents transferring a 512-byte sector (4096 bits) while the spiky bit after it represents the time waiting for the card to confirm the write has completed. The larger gaps would represent the CPU processing time, and the shorter spiky bit before the write starts is setting up the write operation.

image

**Comment by jepler** [comment]
I found some performance by using "CMD25" (write multiple blocks) but it's still not super-fast. This got me a bit over 5fps.

**Comment by jepler** [comment]
image

When the optimization is working, there are fewer post-write spikies (note different horizontal scale). But this depends on the blocks written to be at contiguous block numbers.  It's true on a fresh card, but less so on a card that has had files added & erased (fragmentation).

**Comment by jepler** [comment]
The sd card optimization may be wrong (truncating or corrupting files at the end), needs more investigation and should probably be broken into a separate pr.

**Comment by ladyada** [comment]
hmmm

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!

**Comment by tannewt** [comment]
One conflict that needs to be resolved.

**Review by tannewt — APPROVED** [review]
Thanks!

**Pull request merged**
