### PR TITLE
Add alternative clock pin name to match silkscreen

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Comment by dhalbert** [comment]
CI doc failure only, which we are fixing.

**Review by dhalbert — APPROVED** [review]
:+1:

**Comment by dhalbert** [comment]
I don't know why the CI rebuilt so many things for a one-board change.

**Comment by tannewt** [comment]
> I don't know why the CI rebuilt so many things for a one-board change.

I think it did because the original commit was on an adafruit branch (and we do full builds on them.)

**Comment by tannewt** [comment]
These failures are unrelated so I'm going to merge.

**Pull request merged**
