### PR TITLE
Fix minor typo in MicroPython libraries page

### PR DESCRIPTION
**Pull request by tylercrumpton**

### CODE REVIEW

**Comment by dhalbert** [comment]
Thanks! Could you merge this into the `main` branch instead, we don't expect more releases on the 5.3.x branch.

**Comment by jepler** [comment]
I tried changing the base branch to "main", but it created merge conflicts so I changed it back.  I recommend preparing a fresh PR from a fresh branch based on "main".

**Comment by tylercrumpton** [comment]
Can do! I guess the “Edit on GitHub” button automatically chose the currently viewed branch. I’ll fix that up on the main branch shortly.

**Comment by tylercrumpton** [comment]
Closed this PR and opened https://github.com/adafruit/circuitpython/pull/3122

**Pull request closed without merging**
