### PR TITLE
I2C Timeout "Fix" for Espressif devices.

### PR DESCRIPTION
**Pull request by litui**
- Similar code has been tested in ESP-IDF on another project of mine with great success https://github.com/litui/esp32_bbq10kbd/blob/a3804a3436f964e52af432ee632b72a2b3149ff2/src/BBQ10Keyboard.cpp#L97
- The reason this code is important is that A. the default timeouts on I2C on ESP32 are too short for most applications, resulting in frustration trying to use CircuitPython with ESP32 chips, and B. different numbers of bits are used to store the timeout value in the I2C register depending on which chip revision, hence the need to abstract the value to a "percentage of max."
- It is better to control the timeout value at build/initialization time than accept whatever defaults Espressif happens to assume for us.
- I haven't yet inventoried the libraries for every ESP32-based chip so my i2c.h conditional load of defined values from `soc/i2c_reg.h` may need expansion.
- May not be applicable to all use cases or hardware configurations, but is working under my own use cases on the Unexpected Maker FeatherS3 boards. I've tested my similar ESP-IDF code on Adafruit "Huzzah32" Feather and Sparkfun Thing Plus C boards, though neither of these, to my knowledge, supports CircuitPython easily.

### CODE REVIEW

**Comment by litui** [comment]
I should also note, this appears to fix the "random" inability of CircuitPython to detect pullup resistors. It seems it was mainly a timeout issue.

**Comment by litui** [comment]
Looks like my "fix" is another approach to the solutions discussed here https://github.com/espressif/esp-idf/issues/8770

**Comment by tannewt** [comment]
@dhalbert has the most context so I asked him to review. He's on vacation this week though so he'll get back next week. Thanks for the PR!

**Comment by dhalbert** [comment]
@litui Sorry I dropped the ball on reviewing this after returning from vacation. Couple of questions:

1. Are the timing values counts or actual durations? (I could research this but you would know immediately).
2. Do you have examples of I2C devices that fail without this fix that are sold by Adafruit? I could test a few on a variety of boards. If you have gotten more CircuitPython boards since this PR, your testing would also be very helpful. Thanks.

**Comment by litui** [comment]
@dhalbert no worries. It's been awhile since I've been actively looking at circuitpython so I'll need to take a deeper dive with more recent versions before this can move forward I think. In hindsight this may be more of a blunt approach than is necessary if it ends up only being a few devices. Notably, the Solder Party Keyboard Featherwing needed this timeout value change for the keyboard to work, but I don't recall extensively testing with other I2C devices. I'll get back to you.

**Comment by tannewt** [comment]
@litui Any chance you want to polish this up so we can include it in 8.0? Thanks!

**Comment by dhalbert** [comment]
There is still an open ESP-IDF issue I think is related to this: https://github.com/espressif/esp-idf/issues/8741

**Comment by dhalbert** [comment]
Closing for now, but feel free to reopen.

**Pull request closed without merging**
