### PR TITLE
Adds builds for sparkfun_qwiic_micro with and without flash

### PR DESCRIPTION
**Pull request by edspark**
Hello CircuitPython People,

We have a new release coming tomorrow and I have two builds for this product - one for the product with _no_ flash and another for the product _with_ flash. I hope that works for you all. I've only needed to add these builds to the **boards** directory _without_ modifying anything else. Let me know what you need from me! :fist_raised:

Thanks!

### CODE REVIEW

**Comment by ladyada** [comment]
hiya please also add the boards to the build yml so they get built on releases/PRs
https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/customizing-the-board-files#slash-dot-github-slash-workflows-slash-build-dot-yml-5-30

**Comment by edspark** [comment]
Added, what else is needed?

**Comment by ladyada** [comment]
ok actions has to run now - once that is done if you can ping again we'll merge if its passing. 

meanwhile, please follow this guide
https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website
to add it to the downloads page!

**Comment by edspark** [comment]
I'll get the **pictures** and **.md page** added sometime tomorrow! Thanks @ladyada

**Comment by ladyada** [comment]
@edspark hiya plz fix the actions complaint 
https://github.com/adafruit/circuitpython/pull/2241/checks?check_run_id=272343542

**Comment by edspark** [comment]
Saw that, derp. Fixed.

**Pull request merged**
