### PR TITLE
Split displayio

### PR DESCRIPTION
**Pull request by tannewt**
These are moved:
* Display -> busdisplay.BusDisplay
* FourWire -> fourwire.FourWire
* EPaperDisplay -> epaperdisplay.EPaperDisplay
* I2CDisplay -> i2cdisplaybus.I2CDisplayBus

`paralleldisplay` is now `paralleldisplaybus` (and registered as
`paralleldisplay` too).

Bus related helpers are split out of display_core into bus_core.
It is in still displayio since it is a dependency of both
busdisplay and epaperdisplay.

Fixes https://github.com/adafruit/circuitpython/issues/7667

This PR also fixes .root_group assignment. It was broken by a MP merge.

The PDF doc build now fails due to the size of the support matrix. So it is split out into its own PDF. The main PDF now has a dedicated root file `docs/pdf.rst`.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I briefly tested the artifacts from this PR in 3 contexts:

- Funhouse using print() to show messages on the display that was initialized automatically by default
- Magtag using adafruit_display_text to show a label on the display at various locations
- Matrix portal using some Bitmaps that have lines drawn within them, the display was initialized by adafruit_matrixportal library

All appeared to work as expected.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks for fixing all the `MP_TYPE_FLAG_HAS_SPECIAL_ACCESSORS`!

I just have some `CIRCUITPY-CHANGE` changes and a few doc additions.

**Comment by tannewt** [comment]
Updated! Sorry for the rebase.

**Review by dhalbert — APPROVED** [review]
:+1:

**Pull request merged**
