### PR TITLE
docs: Add list of supported board to each module's page

### PR DESCRIPTION
**Pull request by jepler**

### CODE REVIEW

**Comment by jepler** [comment]
https://user-images.githubusercontent.com/1517291/126878964-8f1942ec-cc4a-42e3-9d15-7628f2d6440e.mp4

**Review by dhalbert — DISMISSED** [review]
I like this! Thanks. Saves using browser search.

**Review by tannewt — COMMENTED** [review]
Could you put it in a proper html list? That'd make it easier to read I think.

**Comment by jepler** [comment]
Updated!
image

**Review by microDev1 — APPROVED** [review]
This looks good. Thanks @jepler.

**Review by dhalbert — APPROVED** [review]
Looks nice!

**Comment by tannewt** [comment]
Thanks for the update!

**Pull request merged**
