### PR TITLE
Adding Support for AT25DF641A SPI Flash

### PR DESCRIPTION
**Pull request by skerr92**
This is related to issue #3782 for adding support for the AT25DF641A 8MiB SPI Flash.

I've included a commented out section in the addition for the other SPI Flash referenced in my comment on the issue. I'm still awaiting the chip and will do another PR to add support once I can verify.

I tested the AT25DF641A on the Qt Py (A little tight soldering this chonky chip) and I was able to verify expanded storage and functionality with the chip.

Passes local pre-commit as well, so there shouldn't be any CI issues.

### CODE REVIEW

**Comment by tannewt** [comment]
I converted this to a draft while you sort out the CI. Undraft once it's happy and I'll review.

**Comment by skerr92** [comment]
Included #3794 on this PR. There was issues with build CI tests with the comments on the devices.h file. I included the 64MiB MX SPI Flash, it's good to go after it passed CI I believe.

**Comment by skerr92** [comment]
> I converted this to a draft while you sort out the CI. Undraft once it's happy and I'll review.

Can you take another look at this @tannewt ?

**Review by dhalbert — APPROVED** [review]
Looks good! Thanks for trying and adding these new chips.

**Pull request merged**
