### PR TITLE
Clarified i2 c init error msg take 2

### PR DESCRIPTION
**Pull request by BiffoBear**
A fresh attempt at clarifying the I2C init error message, after I ran `git train --wreck` on the last one.

### CODE REVIEW

**Review by ajs256 — DISMISSED** [review]
Looks okay to me (a grammar nerd), but some more experienced eyes should check first.

**Comment by ajs256** [comment]
Looks like the CI fail was for Trinket M0 in `ja`, that might need some shrinking.

**Comment by BiffoBear** [comment]
> Looks like the CI fail was for Trinket M0 in `ja`, that might need some shrinking.

Thanks, this caused mayhem in my last attempt. @dhalbert has a fix, so I'll wait for his advice. I appreciate you taking the time to review my PR.

**Comment by dhalbert** [comment]
Just replace `boards/trinket_m0/mpconfigboard.mk` with this version:
https://github.com/adafruit/circuitpython/blob/595356d7fdd132c41c42a1441d41ade999b8f7b4/ports/atmel-samd/boards/trinket_m0/mpconfigboard.mk

**Comment by BiffoBear** [comment]
> Just replace `boards/trinket_m0/mpconfigboard.mk` with this version:
> https://github.com/adafruit/circuitpython/blob/595356d7fdd132c41c42a1441d41ade999b8f7b4/ports/atmel-samd/boards/trinket_m0/mpconfigboard.mk

OK that's done. Thank you for your help and patience.

**Review by dhalbert — APPROVED** [review]
Thanks for _your_ patience as well, and for the original idea!

**Pull request merged**
