### PR TITLE
OnDiskBitmap: INCOMPATIBLE CHANGE: Allow them to use palettes

### PR DESCRIPTION
**Pull request by jepler**
Before, when an OnDiskBitmap was a paletted bitmap type, the palette was internal to the OnDiskBitmap, and it internally performed the palette conversion itself.  When using with a tilegrid, a ColorConverter() object always had to be passed.

Now, an OnDiskBitmap has a "pixel_shader" property.  If the bitmap is a paletted bitmap type, it is a (modifiable) Palette object.  Otherwise, it is a ColorConverter() object as before. This allows palette effects to be applied to paletted OnDiskBitmaps.

Code that used to say:
```python
face = displayio.TileGrid(odb, pixel_shader=displayio.ColorConverter())
```
must be updated to say:
```python
face = displayio.TileGrid(odb, pixel_shader=odb.pixel_shader)
```

Compatible code for 6.x and 7.x can say
```python
face = displayio.TileGrid(odb, pixel_shader=getattr(odb, 'pixel_shader', ColorConverter())
```

Closes: #4636.  An alternative to #4438 which adds less code and is more general.

### CODE REVIEW

**Comment by jepler** [comment]
@tannewt requesting your review since this is an incompatible change.

**Review by gamblor21 — COMMENTED** [review]
Looked it all over and looks good to me. I won't approve until someone else can view the incompatibility part.

**Review by tannewt — APPROVED** [review]
This looks good to me! I believe it'll only break indexed on disk bitmaps. non-indexed bitmaps will use ColorConverter regardless.

**Comment by jepler** [comment]
Thank you!

**Comment by ladyada** [comment]
@jepler @tannewt for breaking changes like these, we need to put a plan in place for who will go through and update all the guides and tutorials. lets chat on monday and come up with a system since there are so many breaking changes in 7.x :)

**Comment by tannewt** [comment]
It's now tracked in https://github.com/adafruit/circuitpython/issues/4982 and I've asked @jepler to do the reviews for @lesamouraipourpre on that issue.

**Pull request merged**
