### PR TITLE
Espruino Pico: Remove settings for DNP oscillator

### LINKED ISSUE #4714: CircuitPython 6.2.0 does not boot on Espruino Pico
I've tried to flash adafruit-circuitpython-espruino_pico-en_US-6.2.0.bin on the Espruino Pico following the advanced reflashing instructions on https://www.espruino.com/Pico#advanced-reflashing , but after what seemed a succesful flash the board didn't react in any way (nothing was logged in dmesg).

I have also tried 7.0.0-alpha.1 with the same result

On the same board I have successfully flashed micropython, following the same instructions.

I've also found this post on the forum https://forums.adafruit.com/viewtopic.php?f=60&t=174183&p=849038&hilit=espruino#p849038 so I'm opening this issue.

Please let me know if you need me to do any further test; I'm using linux on the host I'm using to flash the board.

### PR DESCRIPTION
**Pull request by hierophect**
The LSE on the Espruino Pico is actually DNP, which isn't documented on the schematic. This was causing a clock failure after the 6.0 STM32 timekeeping reworks.

Resolves #4714

### CODE REVIEW

**Comment by hierophect** [comment]
It appears the CI is failing for unrelated reasons on the ESP32-S2, nothing to do with this I don't think.

**Comment by dhalbert** [comment]
> It appears the CI is failing for unrelated reasons on the ESP32-S2, nothing to do with this I don't think.

Yeah, I fixed the build problem with #4721. This seems to happen every time there is some updated software on the build system VPS's.

**Comment by dhalbert** [comment]
@hierophect Could you drop an Espruino Pico build in #4714 for the OP there to test? I thought I could point to an artifact, but I don't see any artifacts. Thanks.

**Comment by hierophect** [comment]
That's weird, don't they normally show up even when the build fails overall? Anyway yeah I can drop one over there.

**Comment by dhalbert** [comment]
> That's weird, don't they normally show up even when the build fails overall? Anyway yeah I can drop one over there.

Yes, I am confused why they aren't there.

**Review by dhalbert — APPROVED** [review]
Thanks for figuring this out! And thanks to @valholl for testing!

**Pull request merged**
