### PR TITLE
LILYGO T-Watch-S3

### PR DESCRIPTION
**Pull request by bill88t**
A board (or I should better say, a normal looking watch) from LILYGO.
Got it from the official aliexpress store. Similar to `lilygo_twatch_2020_v3`.

Note: 
For supporting all of the hardware out of the box, a few frozen modules were added that are not by adafruit, or by me.
While I am actively testing them, these modules seem pretty final.
If adding frozen modules of 3rd parties without their knowledge is an issue, I am willing to fork & pledge to maintain them.

Task checklist:
 - [x] Display.
 - [x] Pins.
 - [x] [USB-PID/VID PR](https://github.com/espressif/usb-pids/pull/168).
 - [x] [TinyUF2 PR](https://github.com/adafruit/tinyuf2/pull/399).
 - [x] PMIC module (AXP2101).
 - [x] Test PMIC.
 - [x] axis sensor module (BMA423).
 - [x] Test axis sensor.
 - FAIL | Test mic (idk how). NotImplementedError: PDMIn
 - [x] IR blaster module (IRRemote).
 - [x] Test IR blaster.
 - [x] RTC module (PCF8563).
 - [x] Test RTC.
 - [x] Haptics module (DRV2605).
 - [x] Test haptics.
 - [x] Touchscreen module (FocalTouch).
 - [x] Test touchscreen.
 - [x] Speaker (audiobusio).
 - [x] Test speaker.

There is also a SX1262, but there is currently no working driver, so not including for now.

### CODE REVIEW

**Comment by tannewt** [comment]
Thanks! Just ordered one for myself.

**Comment by bill88t** [comment]
**IMPORTANT!**

This board does some pretty weird AXP2101 with the RTC, and claims differently in the docs.

To get all the hw to work, following configuration commands are run after the pmic is loaded:
```py
pmic._aldo1_voltage_setpoint = 3300
pmic._bldo1_voltage_setpoint = 0
pmic._bldo2_voltage_setpoint = 3300
pmic._aldo1_voltage_setpoint = 3300
if pmic._read_register8(24) != 13:
    pmic._write_register8(24, 13) # Charge VBackup at 3v3
```

If the coin cell battery is not charged for an extended period of time the RTC will not advance (it will set the time and not tick).

Optionally, to configure the power button to behave a bit more normally:
```
if pmic._read_register8(39) != 31:
    pmic._write_register8(39, 31) # 2s on time, 10s off time
```

I will provide the commands to init all the hardware once I have everything working.

<details>
<summary>Technical details</summary>
They claim PCF8563 is powered through ALDO1, however in the schematic we can see the path exists, but is disconnected due to a NC.<br />
Instead the rtc takes it's power from VBackup. Configuring VBackup is not something the current library support.<br />
Register `24` is `0x18` which is responsible for all the charging and efuel stuff.<br />
Value `13` is `0xD` and sets the bits as `0000 1101`, which is the correct charging voltages limits and stuff.<br />
At least that's what I think for now. I'll test some more stuff later.<br />
I did test with a multimeter and verified the coin cell is being charged.<br />
</details>

**Comment by bill88t** [comment]
The PR is kinda ready, I'll update the branch and fix the merge conflicts in a moment.

Hardware init guide:
<details><summary>PMIC (AXP2101)</summary>

```py
import board
from axp2101 import AXP2101
pmic = AXP2101(board.I2C())
pmic._aldo1_voltage_setpoint = 3300
pmic._bldo1_voltage_setpoint = 0
pmic._bldo2_voltage_setpoint = 3300
pmic._aldo1_voltage_setpoint = 3300
if pmic._read_register8(24) != 15:
    pmic._write_register8(24, 15) # Charge VBackup at 3v3
if pmic._read_register8(39) != 31:
    pmic._write_register8(39, 31) # 2s on time, 10s off time
```
</details>
<details><summary>Axis + temperature sensor (BMA423)</summary>

```py
import board
from bma423 import BMA423
bma = BMA423(board.I2C())
```
</details>
<details><summary>MAX98357A Speaker</summary>

```py
import board, audiobusio
audio = audiobusio.I2SOut(board.I2S_BCK, board.I2S_WS, board.I2S_DOUT)
```
</details>
<details><summary>Vibrator (DRV2605)</summary>

```py
import board
import adafruit_drv2605
i2c = board.I2C()
drv = adafruit_drv2605.DRV2605(i2c)
```
</details>
<details><summary>RTC (PCF8563)</summary>

```py
import board
from adafruit_pcf8563.pcf8563 import PCF8563
i2c = board.I2C()
rtc = PCF8563(i2c)
```
</details>
<details><summary>Touchscreen (FocalTouch)</summary>

```py
from adafruit_focaltouch import Adafruit_FocalTouch
i2c = board.I2C()
ftouch = Adafruit_FocalTouch(i2c)
```
</details>
<details><summary>IR LED</summary>

```py
import pulseio
import board
import adafruit_irremote
pulseout = pulseio.PulseOut(board.IR_LED, frequency=38000, duty_cycle=2**15)
encoder = adafruit_irremote.GenericTransmit(
    ...
)
```
</details>

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
