### PR TITLE
UART changes: timeout in secs, write bytes, etc.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes the remaining items in #1128:
- **Breaking Change**: `busio.UART` constructor `timeout` parameter is now in seconds instead of msecs
- `UART.readinto(buf)` now does not allow an optional length parameter `UART.readinto(buf, len)`
- `UART.write(...)` no longer allows strings to be written. The bytes written must be `bytes` or `bytearray` or an `array.array`.

The fixes are to make `UART` more compatible with `PySerial`, so that `PySerial` can substitute for `UART` on Linux platforms.

### CODE REVIEW

**Comment by ladyada** [comment]
yay thanks - i can test soon i hope

**Comment by jerryneedell** [comment]
tried this PR with a GPS breakout on a Metro_M4_express -- works OK.
Also tried on feather_m4_express  -- communicating to BLE UART friend -- OK

It is important to update the timeout in existing code ;-)

**Comment by tannewt** [comment]
@ladyada feel free to follow up after the merge with any other feedback.

**Comment by ladyada** [comment]
verifying...
   * timeout is now in seconds (correct) - i will note if you set the timeout to a long time the board seems to 'hang' - you cant ^C out, and wont reset on save. seems bricked but isnt. maybe worth fixin?

**Comment by dhalbert** [comment]
@tannewt suggested throwing an exception for a timeout >=1000 to catch old that was still thinking in msecs.

**Comment by ladyada** [comment]
i think anything more than 100, a 2 minute timeout is massive. but still...its really 'hangin' is it normal to not be able to interrupt ?

**Comment by dhalbert** [comment]
There's a call to the VM soft interrupt handler in the busy wait loop, but I think we may have to check for the interrupt in the loop too. This logic hasn't changed, but now it's more obvious it's painful. I'll take a look.

**Comment by ladyada** [comment]
bug found: uart.readinto(buffer) does not obey the timeout, it will hang until all the data is read. it should time out and return the # of bytes?

**Comment by ladyada** [comment]
UART.in_waiting works fine, but i am noticing now our UART input buffer is only 64 bytes? thats really little on the M4 - can we bump it to 256 at least?

**Comment by ladyada** [comment]
uart.reset_input_buffer() working all good
ok thats my testing!

**Comment by dhalbert** [comment]
I think these are all existing bugs. We're just testing better. Did `.readinto()` used to time out, in your experience?

**Comment by ladyada** [comment]
i dont think i did... i agree these are likely older bugs - i can open up new issues if ya like!

**Pull request merged**
