### PR TITLE
switch to checkout@master

### PR DESCRIPTION
**Pull request by jepler**
To see whether we will be compatible with https://github.com/actions/checkout/issues/176

### CODE REVIEW

**Comment by jepler** [comment]
we don't want to _take_ this in the current form.  Rather, we should give feedback to actions/checkout based on the outcome.  Later, they intend to add this functionality in checkout@v2, and that is the change we should take.

**Comment by jepler** [comment]
Thie CI shows failures, but actually it's a success:  The one sub-task I changed to checkout@master succeeded, and then succeeded again on "re-run all tasks".  Another sub-task using checkout@v1 encountered the failure to checkout on re-run that has been vexing us for some time.

Once checkout@v2 is tagged to include the current checkout@master, we should update *all* our checkout@v1 to checkout@v2.  I'll leave this PR open and rebase it later.

**Comment by dhalbert** [comment]
The last time I looked `checkout@v2` by default does a `--depth 1` clone, which doesn't work for us, because we use the nearest tag for version information.

To do a full clone, we need to add:
```
with:
  fetch-depth: 0
```

See https://github.com/adafruit/circuitpython/issues/2683#issuecomment-595811252 for some more discussion.

**Comment by jepler** [comment]
@dhalbert thanks, I'll include that when I update this PR.  Any idea whether we can turn the missing information (tags?) into an overt error at build time?

**Comment by jepler** [comment]
The related bug is marked closed:
> Thanks all for the feedback! I updated V2 to include the recent submodule/SSH changes from master.
I will update this PR soon to use checkout@v2 with submodules:true and fetch-depth:0 for all checkouts.

**Pull request closed without merging**
