### PR TITLE
esp32s2: Ensure proper wifi_disconnect and reset

### LINKED ISSUE #3743: ESP32S2 hangs when interrupting running code that includes I2C object
Using the current (as of now) main  App version:      6.1.0-beta.1-14-g16fe2de70 I can running code to hang after interrupting, 
The code only instantiates an I2C object then loops forever printing something. 
Interrupted with CTRL-C works 1st time
Interrupted again with CTRL-C hangs. 
This was tested with both an Espressif Saola WROVER and Unexpectedmaker FeatherS2
```python
import wifi
import time
import board
from busio import I2C,SPI

# i2c = I2C(board.SCL, board.SDA)
i2c = I2C(board.IO2, board.IO1)  
# spi = SPI(board.SCK, MISO=board.MISO)

while True:
    print("Looping for fun\n")
    time.sleep(1)
```
The code was compiled with DEBUG=1 which outputs some wifi debug info.  Nothing interesting (to me appeared)
I have attached the log from restart to hang. 
[log.txt](https://github.com/adafruit/circuitpython/files/5585492/log.txt)
The last output before the hang was:
```text
I (15918) wifi:enable tsf
I (15918) wifi:mode : sta (7c:df:a1:00:49:fe)
I (27298) wifi:flush txq
I (27298) wifi:stop sw txq
I (27298) wifi:lmac stop hw txq
I (27298) wifi:Deinit lldesc rx mblock:4
I (27308) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pull                                       down: 0| Intr:0
```

### PR DESCRIPTION
**Pull request by BennyE**
This should fix #3743

### CODE REVIEW

**Comment by BennyE** [comment]
I have to add that I tested this just with a code that runs some i2c and has "import wifi". I didn't have time to test this longer and some additional fixes might be necessary.

**Review by jepler — COMMENTED** [review]
I didn't get a chance to test this for myself, but it seems like a good find and extremely plausible as a reason for problems subsequent to importing wifi.  Thank you!

**Comment by jepler** [comment]
The single CI failure can be ignored.

**Comment by BennyE** [comment]
> I didn't get a chance to test this for myself, but it seems like a good find and extremely plausible as a reason for problems subsequent to importing wifi. Thank you!

Hi @jepler , thanks for your review and positive comment. I tried this briefly with a "real wifi setup" and I ran into a backtrace. I'll look into this during my evening (writing this post during my lunch break). Please don't merge yet, I should have done this as a draft and was overly excited & confident. I'll get back to you all later today.

**Comment by skieast** [comment]
Yes. Was playing with that as well. Some esp32 forum idf comments have pointed to similar issues with making sure that disconnect is finished. Cant test until later as I'm mostly skiing in the mornings here. :)

**Comment by BennyE** [comment]
#3803 fixes what this pull request was meant for. Thank you, Bruce! :)

**Pull request closed without merging**
