### PR TITLE
Share the implementation of hashlib across ports

### PR DESCRIPTION
**Pull request by jepler**
.. many platforms can use mbedtls to implement hashlib.

Compile-tested with pico-w. Tested on feather rp2040 dvi. Enabled on rp2040 for now. Could hypothetically be enabled on other ports.

Alternative to https://github.com/adafruit/circuitpython/pull/8719 (ping @anecdata)

### CODE REVIEW

**Comment by Akkiesoft** [comment]
I don't know how to test it, however CI doesn't seem to build images for WIZnet boards.

**Comment by dhalbert** [comment]
@anecdata how are you on this?

**Comment by anecdata** [comment]
I'm an observer (no relevant expertise), certainly no objections. This originally arose due to someone noticing that websockets in HTTPServer didn't have access to native `hashlib` (someone there should eventually re-test). But I think @Akkiesoft is right that there are no `raspberry` builds, WIZnet or otherwise.

**Comment by jepler** [comment]
Due to the way the CI optimizes building fewer boards when possible, the rp2040 builds are on a previous Actions run. I think you can get the artifact you'd want for testing from here: https://github.com/adafruit/circuitpython/actions/runs/7305598483?pr=8749

**Comment by anecdata** [comment]
Performs a similar calculation as in HTTPServer web sockets:
<details>
<summary>EXPAND...</summary>

```py
import time

GUID = b"258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
ITERATIONS = 10_000

def hashme():
    key = "dGhlIHNhbXBsZSBub25jZQ=="
    start = time.monotonic_ns()
    for _ in range(0, ITERATIONS):
        response_key = hashlib.new("sha1", key.encode())
        response_key.update(GUID)
    return time.monotonic_ns() - start

import hashlib
duration = hashme()
print(f"{ITERATIONS} iterations in {duration} ns - hashlib")
#import adafruit_hashlib as hashlib
#duration = hashme()
#print(f"{ITERATIONS} iterations in {duration} ns - adafruit_hashlib")
```
</details>

```
Adafruit CircuitPython 9.0.0-alpha.6-5-g9a7fe7aef4 on 2023-12-23; W5500-EVB-Pico with rp2040
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
10000 iterations in 531250000 ns - hashlib
```
Native hashlib is now present and executes... LGTM!

**Comment by Akkiesoft** [comment]
Thank you @jepler !

I tested with W5500-EVB-Pico.

I no longer get the hashlib error when I run the code used in the following Issue URL. 
https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer/issues/73

LGTM.

**Review by ladyada — COMMENTED** [review]
reviewed but did not test, however nothing looks amiss to me :)

**Review by ladyada — APPROVED** [review]

**Pull request merged**
