### PR TITLE
Rework socketpool.Socket.recv to return sooner

### PR DESCRIPTION
**Pull request by tannewt**
Now it will return the available bytes instead of waiting for the time out before doing so.

Also, tweak IDF settings to reduce memory footprint.

### CODE REVIEW

**Comment by anecdata** [comment]
```
Saola 1 w/Wrover with ESP32S2
6.1.0-alpha.0-186-g872615e9d on 2020-11-03 (artifact from this PR)
Requests 1.7.4
```
After testing this for a couple of hours, to the point of confusion (encountering other open issues, intermittent errors, different behavior with different URLs, etc.)... some scenarios work fine, and I don't see any clear new issues. Not sure what the test case is for testing the reduced delay. I do still see intermittent `espidf.MemoryError: ` in `File "adafruit_requests.py", line 440, in _get_socket` in some cases, typically after some other exception.

**Comment by tannewt** [comment]
The reduced delay case comes up when the response has a long header. The coin base API is an example. The long header grows the request buffer and causes a recv_into with a large buffer to get the remainder of the request. When the buffer is larger than the remaining bytes, it causes us to hit the time out.

**Comment by anecdata** [comment]
This one? [http://api.coindesk.com/v1/bpi/currentprice/USD.json](http://api.coindesk.com/v1/bpi/currentprice/USD.json) I don't see inordinate delays with rc.0 or this PR build. Maybe 0.1s improvement in time to print the headers.

[https://learn.adafruit.com/api/guides/new.json?count=5](https://learn.adafruit.com/api/guides/new.json?count=5) has long headers and long response body. Times are longer and much more variable, but it's hard to isolate out variations in server and network performance. I'm not seeing what I would consider unusual delays with this PR build.

**Comment by tannewt** [comment]
@anecdata This one: http://api.coinbase.com/v2/prices/spot?currency=USD

**Comment by mytechnotalent** [comment]
@tannewt and reviewers I have tested this branch by pulling it in and building from source on a Metro ESP32-S2 testing on my demo code:

```
import gc
import ipaddress
import wifi
import adafruit_requests
import time
import ssl
import socketpool
# import adafruit_dht
from secrets import secrets

# dht = adafruit_dht.DHT11(board.D7)

print(wifi.radio.connect(secrets['ssid'], secrets['password']))

print('ip', wifi.radio.ipv4_address)

ipv4 = ipaddress.ip_address('8.8.8.8')
print('ping', wifi.radio.ping(ipv4))

pool = socketpool.SocketPool(wifi.radio)

requests = adafruit_requests.Session(pool, ssl.create_default_context())

# Set up where we'll be fetching data from
DATA_SOURCE = 'https://hacker-news.firebaseio.com/v0/topstories.json'

# Perform a GET on the DATA_SOURCE and instantiate into a response object
print('Fetching DATA_SOURCE')

# Garbage collect before our GET request
gc.collect()

response = requests.get(DATA_SOURCE)
DATA = response.json()
response.close()

# Garbage collect after our GET request
gc.collect()

while True:
    try:
        # Cycle through articles
        for i in DATA:
            ARTICLE = 'https://hacker-news.firebaseio.com/v0/item/{0}.json'.format(i)
            gc.collect()
            print('Fetching ARTICLE')
            response = requests.get(ARTICLE)
            ARTICLE_JSON = response.json()
            response.close()
            gc.collect()
            print(ARTICLE_JSON['by'])
            print(ARTICLE_JSON['score'])
            print(ARTICLE_JSON['title'])
            time.sleep(10)
    except KeyboardInterrupt:
        break
    except Exception as e:
        # An RuntimeError in addition to other errors can occur if you lose
        # internet so reset the device
        print(e)
        print('Exception')
        import microcontroller
        microcontroller.reset()
```


Results:
```
ip 192.168.1.10
ping 0.023
Fetching DATA_SOURCE
Fetching ARTICLE
looperhacks
230
GitHub: Widespread Injection Vulnerabilities in Actions
```

It is in fact a success.

**Comment by anecdata** [comment]
With this PR build, I'm seeing <0.01 seconds to retrieve the headers on [http://api.coinbase.com/v2/prices/spot?currency=USD](http://api.coinbase.com/v2/prices/spot?currency=USD). Can't compare to baseline of rc.0 due to `espidf.MemoryError: `.

**Comment by jerryneedell** [comment]
I am finding the the order in which https calls are made makes a big difference
 using this code -- note the first request is commented out
```
import ipaddress
import wifi
import adafruit_requests
import time
import ssl
import socketpool

print(wifi.radio.connect('Needell Airport', 'browndog'))

print('ip', wifi.radio.ipv4_address)

ipv4 = ipaddress.ip_address('8.8.8.8')
print('ping', wifi.radio.ping(ipv4))

pool = socketpool.SocketPool(wifi.radio)

https = adafruit_requests.Session(pool, ssl.create_default_context())



#response = https.get("https://api.github.com/repos/adafruit/circuitpython")
#print(response.status_code)
#print("circuitpython open issues", response.json()["open_issues_count"])
#print("circuitpython stars", response.json()["stargazers_count"])
#response.close()

TEXT_URL = "https://httpbin.org/get"
JSON_GET_URL = "https://httpbin.org/get"
JSON_POST_URL = "https://httpbin.org/post"

print("Fetching text from %s" % TEXT_URL)
response = https.get(TEXT_URL)
print("-" * 40)

print("Text Response: ", response.text)
print("-" * 40)
response.close()

print("Fetching JSON data from %s" % JSON_GET_URL)
response = https.get(JSON_GET_URL)
print("-" * 40)

print("JSON Response: ", response.json())
print("-" * 40)
response.close()

data = "31F"
print("POSTing data to {0}: {1}".format(JSON_POST_URL, data))
response = https.post(JSON_POST_URL, data=data)
print("-" * 40)

json_resp = response.json()
# Parse out the 'data' key from json_resp dict.
print("Data received from server:", json_resp["data"])
print("-" * 40)
response.close()

json_data = {"Date": "July 25, 2019"}
print("POSTing data to {0}: {1}".format(JSON_POST_URL, json_data))
response = https.post(JSON_POST_URL, json=json_data)
response = https.post(JSON_POST_URL, json=json_data)
print("-" * 40)

json_resp = response.json()
# Parse out the 'json' key from json_resp dict.
print("JSON Data received from server:", json_resp["json"])
print("-" * 40)
response.close()

```

the test runs normally


```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.1.0-alpha.0-185-g7441344c6 on 2020-11-03; Metro ESP32S2 with ESP32S2
>>> import wifi_https
None
ip 10.0.0.30
ping 0.034
Fetching text from https://httpbin.org/get
----------------------------------------
Text Response:  {
  "args": {}, 
  "headers": {
    "Host": "httpbin.org", 
    "User-Agent": "Adafruit CircuitPython", 
    "X-Amzn-Trace-Id": "Root=1-5fa1a595-492220e225b40837301b4ec5"
  }, 
  "origin": "73.61.89.123", 
  "url": "https://httpbin.org/get"
}

----------------------------------------
Fetching JSON data from https://httpbin.org/get
----------------------------------------
JSON Response:  {'url': 'https://httpbin.org/get', 'headers': {'User-Agent': 'Adafruit CircuitPython', 'Host': 'httpbin.org', 'X-Amzn-Trace-Id': 'Root=1-5fa1a595-7b5698654aff180e64fb6cba'}, 'args': {}, 'origin': '73.61.89.123'}
----------------------------------------
POSTing data to https://httpbin.org/post: 31F
----------------------------------------
Data received from server: 31F
----------------------------------------
POSTing data to https://httpbin.org/post: {'Date': 'July 25, 2019'}
----------------------------------------
JSON Data received from server: {'Date': 'July 25, 2019'}
----------------------------------------
>>> 
```
but if I uncomment  the first request
```

response = https.get("https://api.github.com/repos/adafruit/circuitpython")
print(response.status_code)
print("circuitpython open issues", response.json()["open_issues_count"])
print("circuitpython stars", response.json()["stargazers_count"])
response.close()
```
the first request works, but then  the next one fails
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.1.0-alpha.0-185-g7441344c6 on 2020-11-03; Metro ESP32S2 with ESP32S2
>>> 
>>> import wifi_https
None
ip 10.0.0.30
ping 0.052
200
circuitpython open issues 336
circuitpython stars 1886
Fetching text from https://httpbin.org/get
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wifi_https.py", line 32, in <module>
  File "adafruit_requests.py", line 555, in get
  File "adafruit_requests.py", line 535, in request
  File "adafruit_requests.py", line 429, in _get_socket
  File "adafruit_requests.py", line 425, in _get_socket
OSError: Failed SSL handshake
>>> 

```

**Comment by mytechnotalent** [comment]
@jerryneedell with your example I confirmed the same results I wonder why my `response = https.get("https://api.github.com/repos/adafruit/circuitpython")` is working for me as that is https?  It is confusing to me as your https examples are failing for me as well.  This is a tricky one for sure.

**Comment by anecdata** [comment]
_(updated my previous comment, forgot when I instrumented that headers were not fetched separately like content/text/json)_

**Comment by tannewt** [comment]
@jerryneedell do you think this change makes it worse? Otherwise we can fix the ordering issue in a follow up PR.

**Comment by jerryneedell** [comment]
@tannewt It seems to be behaving about the same

**Comment by dhalbert** [comment]
I would vote for adding this PR, and then opening a new issue describing the ordering problem.

**Comment by tannewt** [comment]
@dhalbert Please approve then. :-)

@jerryneedell We'll keep poking at it. I have some tweaks to Requests we'll want to test with too.

**Review by dhalbert — APPROVED** [review]
Good idea being parsimonious with RAM.

**Comment by dhalbert** [comment]
Could someone file a new issue about the remaining problem, since this issue got closed by the PR? Thanks.

Also, I did some looking at esp-idf bugs, and found this possibly related one:
[Inconsistent TLS negotiation failure with (AP+STA) and max power save mode (IDFGH-4142)](https://github.com/espressif/esp-idf/issues/6006)

**Comment by jerryneedell** [comment]
@dhalbert I'll retest the "order" issue and if still present open a new issue.  I won't get to it until tomorrow. If anyone else wants to do it first, please do.

**Pull request merged**
