### PR TITLE
spresense: update SDK to 2.2.0

### PR DESCRIPTION
**Pull request by kamtom480**
Update Spresense SDK to version 2.2.0.

### CODE REVIEW

**Comment by dhalbert** [comment]
A new version of `sphinx-autoapi` broke the documentation build. I pushed the fix that @tannewt did that is already in use in #5066 and #5068.

**Review by jepler — DISMISSED** [review]
This looks fishy.  @dhalbert is it possible your added commit reverted the spresense-exported-sdk  submodule update?

**Comment by dhalbert** [comment]
> This looks fishy. @dhalbert is it possible your added commit reverted the spresense-exported-sdk submodule update?

Yes, thank you. I forgot to update the submodules when I switched to this branch. Force-pushed a fix.

**Comment by dhalbert** [comment]
It appears that sometimes this runs with `micropython` as the top level directory and sometimes `circuitpython`. I saw the duplicate PID/VID checker script fail with `micropython`, and then succeed on a rerun (!), so that's why I loosened the check. @kamtom480's fork is named `micropython`.

**Review by dhalbert — APPROVED** [review]
@kamtom480 Thanks for this quick fix.
@jepler Thanks for spotting the issues in my commits.

**Pull request merged**
