### PR TITLE
Trinkey pixel fixes

### LINKED ISSUE #4601: NeoPixel LEDs remain lit up from code when entering the REPL
As it is, with the Neo Trinkey specifically, the non-status NeoPixels remain lit up if they were lit up from code in code.py when you enter the REPL. The status LED changes to indicate that you have entered the REPL. So, for example, if you had all four LEDs turned red in your code, and then entered the REPL, three would remain red, and one would turn white. This confused me as I moved onto something else and forgot I had entered the REPL - I figured out what was going on when I came back to it and found I was in the REPL (I thought something had become corrupted). I imagine this might confuse others as well.

Is it worth turning off the remaining non-status LEDs when entering the REPL to avoid confusion? This is only relevant on boards with more than one LED, where one of those LEDs only is a status LED.

@ladyada How would you want this to work?

This is what it looks like when the LEDs were red from code, and then you enter the REPL:
repl_led

### PR DESCRIPTION
**Pull request by ajs256**
Add a `board_reset_user_neopixels` to the Slidey Trinkey, NeoTrinkey, and Prox Trinkey `board.c` files to reset the NeoPixels when entering REPL.

**This is untested as I do not have hardware.**

Closes #4601.

### CODE REVIEW

**Review by ladyada — DISMISSED** [review]

**Comment by ajs256** [comment]
Could someone give the CI approval again? I fixed the issue that caused it to fail last time.

**Comment by kattni** [comment]
@ajs256 Thank you for this fix! I may not have time to test it today, but I will tomorrow for sure. I wanted to let you know that it is on my list.

**Review by kattni — APPROVED** [review]
Tested successfully on Neo Trinkey (neopixel_trinkey_m0)! Thank you for the fix!

**Comment by kattni** [comment]
As the others do not exist yet, I cannot test them. If there are issues, we'll catch them at a later date.

**Pull request merged**
