### PR TITLE
Don't reset GPIO4 on the MagTag (used for voltage monitoring)

### LINKED ISSUE #6148: MagTag battery voltage incorrect in 7.2.0
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0 on 2022-02-24; Adafruit MagTag with ESP32S2
```

### Code/REPL

```python
import analogio
import board

battery_value = (analogio.AnalogIn(board.BATTERY).value / 65535.0) * 3.3 * 2
```

### Behavior

It seems the battery voltage calculated from the code is longer correct in CircuitPython 7.2.0 (code based on https://github.com/adafruit/Adafruit_CircuitPython_MagTag/blob/main/adafruit_magtag/peripherals.py).

Using 7.0.0 it returns around 3.7 but with 7.2.0 it returns 5.4 which is considerably more than the capacity of the battery (3.7v 420mAh)

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DavePutz**
Fixes #6148. Since the re-doing of Espressif GPIO resets done as part of PR #5892 the voltage monitoring done on the MagTag by pin GPIO4 has been always returning high values. This fix avoids resetting that pin on the MagTag and allows correct readings of the voltage.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Looks good - thanks!

**Comment by jepler** [comment]
I'm happy if this fixes a problem .. but .. it would also be interesting to know what's different about ADC on a pin that has been 'reset', because if we understood that maybe we'd get better ADC behavior on all pins.

**Comment by dhalbert** [comment]
I think it is that the resets now set the pin to be an output with a pull-up, instead of an input. @tannewt did that in Perhaps the change should instead be that we make sure to undo the pull-up when setting up `AnalogIn`. https://github.com/adafruit/circuitpython/pull/6057. @DavePutz, I think maybe that is the better fix.

**Comment by dhalbert** [comment]
I am working on a different fix with the same effect.

**Comment by dhalbert** [comment]
I think there are two problems here:
1. The default pull-up on the pin pulls the voltage to the wrong value.
2. The impedance of the voltage divider that's checking the voltage is very high. It's two 1Mohm resistors, with a capacitor across one. So once the pin is set up for ADC, it takes a while for it to get to the right value.

Here is a test program running on CircuitPython 7.2.3, with no fixes. Notice the voltage is wrong to begin with, moves down, and then stabilizes. But it takes almost a second for that.
```py
import analogio, board, time

elapsed_msecs = 0
a = analogio.AnalogIn(board.BATTERY)
while True:
    print(elapsed_msecs / 1000, a.value / 65535 * 3.3 * 2)
    time.sleep(0.1)
    elapsed_msecs += 100
```
```
0.0 5.33599
0.1 4.59799
0.2 4.33998
0.3 4.29798
0.4 4.28791
0.5 4.28791
0.6 4.28599
0.7 4.28197
0.8 4.28398
0.9 4.28599
1.0 4.28599
...
```
So it is not stuck, but it is wrong for a while. Removing the reset works because it takes a while for CircuitPython to start up from a hard reset (when the pin is initially pulled up to high by the ESP-IDF reset (see `gpio_pin_reset()`), and by that time the voltage reading is correct.

I tried disabling the pullup in the `AnalogIn` constructor, but there's not enough time between that happening and doing an ADC read for the pin to stabilize. I also tried pulling the pin _down_ for 10 msecs or so, but that didn't really help. The time constant is really long, as you can see.

So the fix in this PR works because the pin never gets the pull-up set on it. It is a bit accidental. If the ESP-IDF startup reset the pin using its own reset routine (which sets the pullup), we'd have the same problem.

I'm not sure whether to keep this or to simply document that you should wait at least a second after the program starts to read `board.BATTERY`.

@DavePutz, did you already come to this conclusion? @jepler what do you think?

**Comment by DavePutz** [comment]
@danh, I was wondering if pins other than the GPIO4 used for the voltage monitor would have similar issues when used for ADC readings. If so, then disabling the pullup in the AnalogIn constructor might be the only solution. Also, would boards other than the Espressif boards have the same problem?

**Comment by dhalbert** [comment]
[btw @ danh on GitHub is someone else, not me; I am @dhalbert]

> I was wondering if pins other than the GPIO4 used for the voltage monitor would have similar issues when used for ADC readings. If so, then disabling the pullup in the AnalogIn constructor might be the only solution. 

I tested other `AnalogIn` pins, just floating, and I don't see this problem. Even without disabling the pull-up, their values are near zero. I think maybe the cap on the voltage divider is a big culprit here. I was worrying that `AnalogIn` was really broken completely now, but that is not the case.

> Also, would boards other than the Espressif boards have the same problem?

Espressif is unique in saying that enabling the pull-up causes lower power consumption. On all the other boards, we reset pins to floating with no pulls in either direction.

If so, then disabling the pullup in the AnalogIn constructor might be the only solution. Also, would boards other than the Espressif boards have the same problem?

**Review by dhalbert — APPROVED** [review]
I talked with @jepler about this, and we decided to disable the pull-up( I added 99dc402), and we'll also keep your no-reset change, so that one need not wait to read the battery voltage. We can change this in the future, but for now, this is the easiest for the end user. Thanks for your work on this.

**Pull request merged**
