### PR TITLE
espressif: Allow one build to work with psram & non-psram versions of a board

### PR DESCRIPTION
**Pull request by jepler**
By setting CONFIG_SPIRAM_TYPE_AUTO=y and CONFIG_SPIRAM_IGNORE_NOTFOUND=y, the boot code will adapt to whatever PSRAM is present, or fall back to running without it if no psram is present. This means we don't need two (or more, for the 'M' version(s)) artifacts for the variants of the ESP32-S3 DevKit family

On a psram board ([DevKitC-1-N8R2](https://www.adafruit.com/product/5310)):
```python
Adafruit CircuitPython 7.2.0-alpha.0-38-g121b22b0c-dirty on 2021-12-07; ESP32-S3-DevKitC-1 with ESP32S3
>>> import gc
>>> gc.mem_free()
2048144
```

On a non-psram board (actually the [ESP32-S3-DevKitM-1-N8](https://www.adafruit.com/product/5311)):
```python
Adafruit CircuitPython 7.2.0-alpha.0-38-g121b22b0c-dirty on 2021-12-07; ESP32-S3-DevKitC-1 with ESP32S3
>>> import gc
>>> gc.mem_free()
46992
```

### CODE REVIEW

**Review by microDev1 — COMMENTED** [review]
Nice! Thanks @jepler. This `sdkconfig` should work for every board, would you like to modify the common `skdconfig.defaults`?

**Comment by jepler** [comment]
@microDev1 I thought about that. I can do it if there's agreement. Two possible reasons not to:
 * it's a change that would affect all espressif builds, not just this one (so more testing would be needed)
 * on a board where we "know" there's psram, do we want to continue without it?

**Comment by jepler** [comment]
one more wrinkle .. I noticed on the esp32s3-box that the 8MB PSRAM was also an octal chip, so swapping out different modules with different psram within the can ACTUALLY requires a different set of never-reset pins.

**Comment by tannewt** [comment]
I'm ok with having a board for each variant. It can make it easier to debug if the board id matches an exact board.

**Comment by microDev1** [comment]
I still believe this is a good change. We should have a better way of building & communicating a board's flash & ram config.

**Building:**
```py
make BOARD=... FLASH=... (defaults to lowest flash size) RAM=auto
```

**Communicating:**
```py
# in boot_out
Adafruit CircuitPython 7.1.0 on 2021-12-02; MicroDev microS2 with ESP32-S2
Board ID:microdev_micro_s2_f16_r8
```

**Comment by tannewt** [comment]
@microDev1 How many variations will exist do you think? Maybe we should only distinguish internal vs external ram and ignore flash size completely? That's how I'm handling boards in the `broadcom` port since both SD card and RAM sizes can vary.

**Pull request closed without merging**
