### PR TITLE
Add Piunora and Zero. Also, enable full build

### LINKED ISSUE #5631: Support full line of RPI
We currently only support 64-bit CPUs. If we supported 32-bit, then we could support Pi 1, Pi 2 and the original Pi Zero.

Additional boards to add:

- [ ] Piunora
- [ ] Zero
- [ ] Zero W
- [ ] Pi 3 A+

### LINKED ISSUE #5768: Broadcom port doesn't include io module
### CircuitPython version

```python
Adafruit CircuitPython 7.1.0-beta.3 on 2021-12-13; Raspberry Pi Zero 2W with rp3a0
Adafruit CircuitPython 7.1.0-beta.3-174-gbea052695-dirty on 2021-12-22; Raspberry Pi Zero 2W with bcm2837
```

### Code/REPL

```python
import io
```

### Behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'io'

### Description

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #5768 and fixes #5631

### CODE REVIEW

**Review by ladyada — DISMISSED** [review]
lol at 
`void board_init(void) {
    videocore_framebuffer_obj_t *fb = &allocate_display_bus()->videocore;
    fb->base.type = &videocore_framebuffer_type;
    common_hal_videocore_framebuffer_construct(fb, 640, 480);

    framebufferio_framebufferdisplay_obj_t *display = &displays[0].framebuffer_display;
    display->base.type = &framebufferio_framebufferdisplay_type;
    common_hal_framebufferio_framebufferdisplay_construct(
        display,
        MP_OBJ_FROM_PTR(fb),
        0,
        true);
}
`
"display can support i2c oleds, spi tfts, or 60hz 4K HDMI displays"

**Comment by tannewt** [comment]
And eink too!

**Comment by jerryneedell** [comment]
Downloaded and executed artifacts for cm4io, pi zero-w, pizero2w,  PiZeroW and pi4b.

All booted OK -- mounted CIRCUITPY and was able to access REPL via USB

**Review by dhalbert — APPROVED** [review]
Looks good!

**Pull request merged**
