### PR TITLE
Update ulab

### PR DESCRIPTION
**Pull request by jepler**
This gets us
 - the new "approx" submodule
 - the new "equal / not_equal" predicates (since we can't do `array == array` due to technical limitations)
 - vectorise() for vectori(s/z)ing arbitrary Python functions with reasonably good performance

~~The specific submodule ref is in a pending PR https://github.com/v923z/micropython-ulab/pull/122 so it should not be merged while that PR is not resolved.~~

### CODE REVIEW

**Comment by v923z** [comment]
> This gets us
> 
>     * the new "approx" submodule
> 
>     * the new "equal / not_equal" predicates (since we can't do `array == array` due to technical limitations)
> 
>     * vectorise() for vectori(s/z)ing arbitrary Python functions with reasonably good performance
> 

This is definitely `vectorize()`. Since it was an original `numpy` function, I stuck with the American spelling:)

> The specific submodule ref is in a pending PR [v923z/micropython-ulab#122](https://github.com/v923z/micropython-ulab/pull/122) so it should not be merged while that PR is not resolved.

The sub-module itself has been in master for approx. (pun intended) two weeks now.

**Comment by jepler** [comment]
> > The specific submodule ref is in a pending PR [v923z/micropython-ulab#122](https://github.com/v923z/micropython-ulab/pull/122) so it should not be merged while that PR is not resolved.
> 
> The sub-module itself has been in master for approx. (pun intended) two weeks now.

Overloaded terms.  I mean to say, the git submodule ref for `extmod/ulab` is in the non-merged PR v923z/micropython-ulab#122.

**Comment by tannewt** [comment]
Why can't we do `==` and `!=`? We shouldn't introduce a new API just because we can't match MicroPython or CPython.

**Comment by jepler** [comment]
equal and not_equal are in numpy.  https://numpy.org/doc/stable/reference/generated/numpy.not_equal.html

However, on some more full implementations of Python, == and != can be used for this functionality as well (I think there may be a minor difference in how non-finite values are handled)

**Comment by v923z** [comment]
> Why can't we do `==` and `!=`? We shouldn't introduce a new API just because we can't match MicroPython or CPython.

Here is what you need for the `==`, and `!=` operators to work: https://github.com/micropython/micropython/pull/5593

I am not emotionally attached to the `equal`, and `not_equal` functions, so if you want, we can remove them. It was more like a temporary measure for `circuitpython`. As far as I remember, it was specifically a user request.

**Comment by tannewt** [comment]
Thanks @v923z. I opened #2999 for reasons to merge upstream changes.

**Pull request merged**
