### PR TITLE
6.3.x cherry pick from main

### LINKED ISSUE #4753: ulab array corruption with slices
I noticed this on CircuitPython 6.2.0 on a CLUE (nRF52840):

```
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit CLUE nRF52840 Express with nRF52840
>>> import ulab
>>> import ulab.numerical
>>> import ulab.filter
>>> data = ulab.ones(10000)
>>> fir_taps = ulab.array([0.15, 0.2, 0.3, 0.2, 0.15])
>>> filtered_data = ulab.filter.convolve(data, fir_taps)[6:-6]
>>> ulab.numerical.sum(filtered_data)
9992.0
>>> len(filtered_data)
9992
>>> a = []  ### append to an array to write and use up free memory
>>> for idx in range(1_000_000):
...     a.append("AYMABTU")
...
...
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
MemoryError: memory allocation failed, allocating 131072 bytes
>>> del a
>>> ulab.numerical.sum(filtered_data)  ### no longer 9992.0 !!
9882.01
>>> ulab.numerical.sum(data)  ### although this one is ok
10000.0
>>> filtered_data[0:10]
array([2.98023e-08, 0.0, 1.19209e-07, 0.0, -6.61744e-24, 0.0, -2.64698e-23, 0.0, 1.70141e+38, 0.0], dtype=float32)
```

I'd guess it's related to premature GC of the `ndarray` returned by `ulab.filter.convolve()`. That would be inappropriate as the _slice_ is a view onto that data as I understand it.

### PR DESCRIPTION
**Pull request by dhalbert**
Many cherry picks from main to add new boards, correct pin errors, and fix a few ~~useful~~ significant bugs.

Artisense RD00 board #4512. Thanks @m-byte.
Correct pins for UM TinyS2. #4534. Thanks @UnexpectedMaker.
HunterCat NFC board. #4545. Thanks @sabas1080
BDMicro VINA-D51 updates. #4561. Thanks @bd34n.
QT Py RP2040 D3 pin correction. #4581. Thanks @dhalbert.
STM32F4 Black Pill add flash chip. #4582. Thanks @kevinlutzer.
Remove robots.txt from ReadTheDocs. #4584. Thanks @dhalbert.
Adafruit NeoKey Trinkey. #4595. Thanks @ladyada.
Adafruit ProxLight Trinkey. #4594. Thanks @ladyada.
Adafruit Rotary Trinkey. #4594. Thanks @ladyada.
Adafruit Slide Trinkey. #4595. Thanks @ladyada.
Turn `storage` back on for NeoPixel Trinkey. #4599. Thanks @dhalbert.
Pimoroni Pico LiPo 4MB. #4612, #4633. Thanks @ZodiusInfuser.
Pimoroni Pico LiPo 16MB. #4612, #4633. Thanks @ZodiusInfuser.
Add `VBUS_SENSE` pin to Pi Pico. #4624. Thanks @dhalbert.
SparkFun MicroMod RP2040. #4625. Thanks @stonehippo.
ARAMCON2 Badge. #4627. Thanks @bmeisels.
Fix `board.I2C()` pins for Feather M0 Adalogger. #4631. Thanks @anecdata.
Adafruit ItsyBitsy RP2040 corrections. #4687. Thanks @kattni.
Fix crystal settings for Espruino Pico. #4719. Thanks @hierophect.
Fix pins on SparkFun Pro Micro RP2040. #4733. Thanks @nm3210.
Free up PA00 and PA01 on Big Honking Button. #4735. Thanks @bleything.
Fix FunHouse name. #4736. Thanks @Neradoc.
Add LED pin to many Adafruit boards. #4742. Thanks @kattni.
Adafruit QT 2040 Trinkey. #4750. Thanks @ladyada.
Fix overwrite of `run_reason`. #4708. Thanks @hierophect.
Update SparkFun ThingPlus RP2040 pins. #4691. Thanks @nm3210.
Fix GC problem in `ulab`. Fixes #4753. https://github.com/v923z/micropython-ulab/issues/387. Thanks @v923z.
Fix SparkFun MicroMod RP2040 pins. #4663. Thanks @zapwizard.
Update frozen libraries. `adafruit_hid` is deliberately held at 4.3.0, instead of 5.0.0. Thanks @dhalbert.
Add Arduino Nano RP2040. #4802 (done manually). Thanks @BlitzCityDIY.
Do not leave `board.I2C()` locked on soft reload. #4801. Thanks @dhalbert.
Length crystal oscillator startup time on RP2040. https://github.com/adafruit/pico-sdk/pull/4. Thanks @dhalbert.

### CODE REVIEW

**Comment by hierophect** [comment]
Want to put in the run reason fix? #4708

**Comment by nm3210** [comment]
I'd request #4691 to be in too, if possible.

**Review by hierophect — DISMISSED** [review]
LGTM

**Comment by ajs256** [comment]
> Remove robots.txt from ReadTheDocs. #4584. Thanks @\hdalbert

I think that was a typo, as @\hdalbert appears to have nothing to do with CP!

**Comment by dhalbert** [comment]
> > Remove robots.txt from ReadTheDocs. #4584. Thanks @\hdalbert
> 
> I think that was a typo, as @\hdalbert appears to have nothing to do with CP!

Sometimes I have trouble typing my own name :slightly_smiling_face:

**Comment by dhalbert** [comment]
@tannewt anything you want to add to this?

**Comment by tannewt** [comment]
> @tannewt anything you want to add to this?

Not that I can think of. I don't really remember anything prior to the merge. :-)

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by v923z** [comment]
@dhalbert 

> Many cherry picks from main to add new boards, correct pin errors, and fix a few useful bugs.

Out of curiosity, what is a useful bug?

**Comment by dhalbert** [comment]
Needs cherry-pick from #4765.

**Comment by stonehippo** [comment]
I think it needs #4663, too

**Comment by anecdata** [comment]
`Adafruit Rotary Trinkey. #4594. Thanks @ladyada.` from above... Rotary Trinkey is #4449, but it looks like that should be in 6.2.0 except that downloading it from circuitpython.org gets a `NoSuchKey` XML error.

**Comment by dhalbert** [comment]
@anecdata This will add the missing boards to 6.3.0. I'm not sure why they are listed in the boards file for 6.2.0; that is an error, obviously.

**Comment by dhalbert** [comment]
The last thing I plan to add to this before rc.0 will be a fix for RP2040 slow crystal oscillator startup, which is dependent on https://github.com/adafruit/pico-sdk/pull/4/

**Comment by dhalbert** [comment]
This is ready to try as a release candidate. I just need a review and then I will make a release.

**Review by kattni — APPROVED** [review]
Looks good to me!

**Pull request merged**
