### PR TITLE
shared/runtime/sys_stdio_mphal: Fix docstring for stdio.

### PR DESCRIPTION
**Pull request by timdechant**
Incorporating `stdio` recommendations from micropython#15708.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Thanks! It was good to get Damien's take on this.

**Review by dhalbert — CHANGES_REQUESTED** [review]
The Metro M0 build German build is overflowing by 16 bytes. Tomorrow I will see about shrinking this build slightly. The other build failures are transient CI issues.

**Review by dhalbert — APPROVED** [review]
Now it fits!

**Comment by timdechant** [comment]
Thanks, Dan!  And thanks for all your work here, it's a great project!

**Pull request merged**
