### PR TITLE
M5Stack Cardputer : I2S_DATA  pin name typo

### PR DESCRIPTION
**Pull request by RetiredWizard**
I'm sorry I didn't get a chance to test this before the merge but I was out of town most of this week and when I got back this evening my cardputer had just arrived :grin:.

I threw the latest build on and did a few quick tests which mostly seemed to work fine. I did spot this one typo though. I'll give it some more testing tomorrow.

### CODE REVIEW

**Comment by dhalbert** [comment]
@RetiredWizard I will wait a bit in case you have a few more changes.

**Comment by RetiredWizard** [comment]
> @RetiredWizard I will wait a bit in case you have a few more changes.

Thanks Dan! :grin: I've tested I2S Audio Out, I2C, SPI (SD Card/TFT), keyboard pins... All looks good to me.

**Comment by RetiredWizard** [comment]
Sorry Dan, I should have reminded you when I saw you getting close to RC1, but it's probably not a big deal, this can be fixed in RC2 :grin:

**Review by dhalbert — APPROVED** [review]
I missed your last post, sorry!

**Pull request merged**
