### PR TITLE
CI: More fixes and refactoring

### PR DESCRIPTION
**Pull request by MicroDev1**
This PR contains the following changes:

- Split `atmel-samd` instead of `raspberrypi`: This more evenly distributes the number boards across matrix jobs.
- Refactor and simplify fetching port deps: Now port specific stuff can be placed in `.github/actions/deps/ports/...`.
- Fix for empty exclude commit: Use `github.event.pull_request.head.sha` instead of `github.event.after` which can be empty.

### CODE REVIEW

**Review by tannewt — CHANGES_REQUESTED** [review]
Would you mind just splitting out every port? I split nrf out in #7497 because I needed to install `nrfutil` for it. See that PR for some renaming too.

**Comment by MicroDev1** [comment]
> Would you mind just splitting out every port?

I took a look at the `nrfutil` changes and this pr simplifies it.

The port specific configuration steps/dependencies for nrf can go in:
```yml
# .github/actions/deps/ports/nrf/action.yml

name: Fetch nrf port deps

runs:
  using: composite
  steps:
    - name: Get nrfutil 7+
      run: |
        wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
        chmod +x nrfutil
        ./nrfutil install nrf5sdk-tools
        mkdir -p $HOME/.local/bin
        mv nrfutil $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Print nrfutil version
      run: nrfutil -V
      shell: bash
```
Then the following conditional step can be added in:
```yml
# .github/actions/deps/ports/action.yml

- name: Set up nrf port
  if: steps.board-to-port.outputs.port == 'nrf'
  uses: ./.github/actions/deps/ports/nrf
```

**Comment by jepler** [comment]
It would be unfortunate to switch to this tool as we have user/developers who build on arm64 linux platforms (e.g., rpi)...

**Comment by tannewt** [comment]
> It would be unfortunate to switch to this tool as we have user/developers who build on arm64 linux platforms (e.g., rpi)...

Are you talking about `nrfutil`? If so, #7497 is a better place to discuss this.

**Comment by tannewt** [comment]
> > Would you mind just splitting out every port?
> 
> I took a look at the `nrfutil` changes and this pr simplifies it.

I agree it simplifies that part but I'd still like to split the matrix by port rather than architecture. That would be clearer than having a mix as you have now.

**Review by tannewt — APPROVED** [review]
Approving and merging. @MicroDev1 will follow up with rework to each port.

**Pull request merged**
