### PR TITLE
Update to the very latest SDK w/GP15 restore

### LINKED ISSUE #4039: Get unique ID from flash
The RP2040 chip itself doesn't have a unique id so implement it by getting the flash chip's ID.

### PR DESCRIPTION
**Pull request by tannewt**
Also adds unique id support

Fixes #4039 and hopefully #4107

### CODE REVIEW

**Review by jepler — APPROVED** [review]
Seems OK.  It'll be nice to have a unique identifier.  No testing performed.  The changes to link.ld seem to mirror those in the SDK, but I don't understand 'em.

**Review by dhalbert — APPROVED** [review]

**Comment by sgbaird** [comment]
So, in CircuitPython, how do I get the unique ID? I'm used to `from machine import unique_id` from MicroPython.

**Comment by dhalbert** [comment]
> So, in CircuitPython, how do I get the unique ID? I'm used to `from machine import unique_id` from MicroPython.

https://docs.circuitpython.org/en/latest/shared-bindings/microcontroller/index.html#microcontroller.Processor.uid

Good places to ask questions like this are in https://adafru.it/discord or https://forums.adafruit.com.

**Comment by sgbaird** [comment]
@dhalbert thanks for clarifying! 

> Good places to ask questions like this are in [adafru.it/discord](https://adafru.it/discord) or [forums.adafruit.com](https://forums.adafruit.com).

Ah, right 😓 I keep forgetting that

**Pull request merged**
