### PR TITLE
changed msgpack to use ByteStream type annotations

### PR DESCRIPTION
**Pull request by rimwolf-redux**
The IO parameters in msgpack.pack and msgpack.unpack are now named `stream` and annotated as `circuitpython_typing.ByteStream`. Fixes issue #6050.

### CODE REVIEW

**Comment by rimwolf-redux** [comment]
build-doc is failing for `msgpack/__init__.pyi`, apparently because `shared-bindings/circuitpython_typing/__init__.pyi` does not have the new ByteStream definition in it. How do I correct this?

**Comment by dhalbert** [comment]
> build-doc is failing for `msgpack/__init__.pyi`, apparently because `shared-bindings/circuitpython_typing/__init__.pyi` does not have the new ByteStream definition in it. How do I correct this?

I thought i had released circuitpython_typing 1.1.0, but apparently not. I just released it, confirmed it's in pypi.org, and am rerunning the PR jobs.

**Comment by dhalbert** [comment]
I think we canremove `shared-bindings/circuitpython_typing` and instead make it part of `requirements-dev.txt`. I thought at first it was a reference to a submodule, but it's just a copy of what was in `adafruit-blinka `and is now in `adafruit-circuitpython-typing`.

@jepler do you think that would work for the stubs generation? 

I will try this in the morning; it's too late now.

**Comment by dhalbert** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_Typing/pull/6 has some required changes that should then enable further changes here to finish this PR.

**Comment by dhalbert** [comment]
The failing CI checks are all CI glitches.

**Review by dhalbert — APPROVED** [review]
I think this is OK for now. I updated https://github.com/adafruit/Adafruit_CircuitPython_Typing, and made various build changes and other changes, as you see.

Thanks for initiating this and working with me on this!

**Comment by rimwolf-redux** [comment]
And I thought this was going to be an easy one! Thanks so much for seeing this through; I've learned a lot following the various changes you've had to make.

**Pull request merged**
