### PR TITLE
espressif: Add ESP32-S3-DevKitM-1 board support

### PR DESCRIPTION
**Pull request by arturo182**
Based on the ESP32-S3-DevKitC-1-N8 board files. Verified on the actual HW.

Requested the PID here: https://github.com/espressif/usb-pids/pull/34

Pinout for reference: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/_images/ESP32-S3_DevKitM-1_pinlayout.jpg

### CODE REVIEW

**Comment by anecdata** [comment]
is this different than https://circuitpython.org/board/espressif_esp32s3_devkitc_1_n8/ ?

**Comment by arturo182** [comment]
Let's see, if they disagree then I'll just change it to use the DevKitC PID :)

**Comment by prplz** [comment]
You should add IO40 (see #5975)

**Comment by jepler** [comment]
They've previously asked us to use the same USB VID/PID for "similar" boards (varying only in flash/psram capacity), let us know if you need help modifying `tools/ci_check_duplicate_usb_vid_pid.py` to make this OK with the CI.

**Comment by arturo182** [comment]
https://github.com/espressif/usb-pids/pull/34 got merged so we can merge this too now :)

**Review by tannewt — CHANGES_REQUESTED** [review]
Would you mind adding `_n8` to the end of the board name? I know the dev board only has one module it comes with now but I wouldn't be surprised if espressif made another mini module later and put it on the same board. Adding the n8 would allow us to distinguish it in the future.

**Comment by arturo182** [comment]
Should I also add `-N8` to `MICROPY_HW_BOARD_NAME` and `USB_PRODUCT` ?

**Comment by tannewt** [comment]
> Should I also add `-N8` to `MICROPY_HW_BOARD_NAME` and `USB_PRODUCT` ?

Sure! It's easy to change those after the fact. The board name is trickier since we use it as an id.

**Review by tannewt — APPROVED** [review]
Thank you!

**Pull request merged**
